<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Seeder;

class RbacSeeder extends Seeder
{
    public function run(): void
    {
        collect([
            'settings.company.view' => 'ดูข้อมูลบริษัท',
            'settings.company.update' => 'แก้ไขข้อมูลบริษัท',
            'settings.users.view' => 'ดูผู้ใช้งาน',
            'settings.users.create' => 'เพิ่มผู้ใช้งาน',
            'settings.users.update' => 'แก้ไขผู้ใช้งาน',
            'settings.users.delete' => 'ลบผู้ใช้งาน',
            'settings.branches.view' => 'ดูสาขา',
            'settings.branches.create' => 'เพิ่มสาขา',
            'settings.branches.update' => 'แก้ไขสาขา',
            'settings.branches.delete' => 'ลบสาขา',
            'settings.warehouses.view' => 'ดูคลังสินค้า',
            'settings.warehouses.create' => 'เพิ่มคลังสินค้า',
            'settings.warehouses.update' => 'แก้ไขคลังสินค้า',
            'settings.warehouses.delete' => 'ลบคลังสินค้า',
            'settings.roles.view' => 'ดูบทบาทและสิทธิ์',
            'settings.roles.manage' => 'จัดการบทบาทและสิทธิ์',
            'settings.roles.delete' => 'ลบบทบาทและสิทธิ์',
            'settings.audit.view' => 'ดูประวัติการเปลี่ยนแปลง',
            'settings.workflow.view' => 'ดูคู่มือการทำงาน Settings',
            'accounting.accounts.view' => 'ดูผังบัญชี',
            'accounting.accounts.create' => 'เพิ่มบัญชี',
            'accounting.accounts.update' => 'แก้ไขบัญชี',
            'accounting.accounts.delete' => 'ลบบัญชี',
            'accounting.accounts.import' => 'อัปโหลดและตรวจสอบผังบัญชีจาก Excel',
            'accounting.accounts.import.commit' => 'ยืนยันนำเข้าผังบัญชีจาก Excel',
            'accounting.account-mappings.view' => 'ดูการตั้งค่าบัญชีสำหรับเอกสาร',
            'accounting.account-mappings.create' => 'เพิ่มการตั้งค่าบัญชีสำหรับเอกสาร',
            'accounting.account-mappings.update' => 'แก้ไขการตั้งค่าบัญชีสำหรับเอกสาร',
            'accounting.tax-codes.view' => 'ดู Tax Code',
            'accounting.tax-codes.create' => 'เพิ่ม Tax Code',
            'accounting.tax-codes.update' => 'แก้ไข Tax Code',
            'accounting.tax-codes.delete' => 'ลบ Tax Code',
            'accounting.periods.view' => 'ดูปีและงวดบัญชี',
            'accounting.periods.create' => 'สร้างปีและงวดบัญชี',
            'accounting.periods.close' => 'Soft close งวดบัญชี',
            'accounting.periods.reopen' => 'เปิดงวดบัญชีอีกครั้ง',
            'accounting.periods.lock' => 'Lock งวดบัญชี',
            'accounting.journal-books.view' => 'ดูสมุดบัญชี',
            'accounting.journal-books.update' => 'ตั้งค่าสมุดบัญชี',
            'accounting.journal-entries.view' => 'ดูรายการบัญชี',
            'accounting.journal-entries.create' => 'สร้างรายการบัญชี Draft',
            'accounting.journal-entries.update' => 'แก้ไขรายการบัญชี Draft',
            'accounting.journal-entries.submit' => 'ส่งรายการบัญชีเพื่ออนุมัติ',
            'accounting.journal-entries.approve' => 'อนุมัติและลงบัญชีรายการทั่วไป',
            'accounting.journal-entries.reverse' => 'กลับรายการบัญชีที่ลงบัญชีแล้ว',
            'accounting.reports.view' => 'ดูรายงานบัญชีและงบการเงิน',
            'accounting.reports.comparative-income.view' => 'ดูรายงานเปรียบเทียบรายได้',
            'accounting.reports.withholding-expense.view' => 'ดูรายงานภาษีหัก ณ ที่จ่ายค่าใช้จ่าย',
            'accounting.reports.withholding-received.view' => 'ดูรายงานภาษีถูกหัก ณ ที่จ่าย',
            'finance.dashboard.view' => 'ดู Finance Dashboard',
            'finance.ar-open-items.view' => 'ดูรายการลูกหนี้คงค้าง',
            'finance.ar-aging.view' => 'ดู Aging ลูกหนี้',
            'finance.ap-open-items.view' => 'ดูรายการเจ้าหนี้คงค้าง',
            'finance.ap-aging.view' => 'ดู Aging เจ้าหนี้',
            'finance.bank-accounts.view' => 'ดูบัญชีเงินสดและธนาคาร',
            'finance.bank-accounts.create' => 'เพิ่มบัญชีเงินสดและธนาคาร',
            'finance.bank-accounts.update' => 'แก้ไขบัญชีเงินสดและธนาคาร',
            'finance.bank-accounts.delete' => 'ลบบัญชีเงินสดและธนาคาร',
            'finance.payment-terms.view' => 'ดูเงื่อนไขการชำระเงิน',
            'finance.payment-terms.create' => 'เพิ่มเงื่อนไขการชำระเงิน',
            'finance.payment-terms.update' => 'แก้ไขเงื่อนไขการชำระเงิน',
            'finance.payment-terms.delete' => 'ลบเงื่อนไขการชำระเงิน',
            'finance.other-categories.view' => 'ดูรายได้และรายจ่ายอื่น',
            'finance.other-categories.create' => 'เพิ่มรายได้และรายจ่ายอื่น',
            'finance.other-categories.update' => 'แก้ไขรายได้และรายจ่ายอื่น',
            'finance.other-categories.delete' => 'ลบรายได้และรายจ่ายอื่น',
            'finance.document-sequences.view' => 'ดูรหัสและรูปแบบเอกสาร',
            'finance.document-sequences.create' => 'เพิ่มรหัสและรูปแบบเอกสาร',
            'finance.document-sequences.update' => 'แก้ไขรหัสและรูปแบบเอกสาร',
            'finance.document-sequences.delete' => 'ลบรหัสและรูปแบบเอกสาร',
            'finance.settlements.view' => 'ดูเอกสารรับเงินและจ่ายเงิน',
            'finance.settlements.create' => 'สร้างเอกสารรับเงินและจ่ายเงิน',
            'finance.settlements.approve' => 'อนุมัติเอกสารรับเงินและจ่ายเงิน',
            'finance.settlements.post' => 'ลงบัญชีเอกสารรับเงินและจ่ายเงิน',
            'finance.settlements.void' => 'ยกเลิกเอกสารรับเงินและจ่ายเงินที่ยังไม่ลงบัญชี',
            'finance.settlements.reverse' => 'กลับรายการเอกสารรับเงินและจ่ายเงินที่ลงบัญชีแล้ว',
            'finance.payment-vouchers.view' => 'ดูใบขอจ่ายและใบสำคัญจ่าย',
            'finance.payment-vouchers.create' => 'สร้างใบขอจ่ายและใบสำคัญจ่าย',
            'finance.payment-vouchers.submit' => 'ส่งใบขอจ่ายและใบสำคัญจ่ายเพื่ออนุมัติ',
            'finance.payment-vouchers.approve' => 'อนุมัติใบขอจ่ายและใบสำคัญจ่าย',
            'finance.payment-vouchers.void' => 'ยกเลิกใบขอจ่ายและใบสำคัญจ่าย',
            'finance.payment-vouchers.settle' => 'สร้าง Settlement จากใบสำคัญจ่ายที่อนุมัติแล้ว',
            'finance.reports.payment-activity.view' => 'ดูรายงานธุรกรรมการเงินรับและจ่าย',
            'finance.advance-deposits.view' => 'ดูเงินรับล่วงหน้าและเงินมัดจำ',
            'finance.advance-deposits.create' => 'สร้างเงินล่วงหน้าและเงินมัดจำจากเอกสารรับจ่ายที่ลงบัญชีแล้ว',
            'finance.advance-deposits.apply' => 'นำเงินล่วงหน้าและเงินมัดจำไปตัดเอกสาร',
            'wms.dashboard.view' => 'ดู Purchasing Dashboard',
            'wms.workflow.view' => 'ดูคู่มือการทำงาน Purchasing และ WMS',
            'wms.suppliers.view' => 'ดู Supplier',
            'wms.suppliers.create' => 'เพิ่ม Supplier',
            'wms.suppliers.update' => 'แก้ไข Supplier',
            'wms.suppliers.delete' => 'ลบ Supplier',
            'wms.items.view' => 'ดูสินค้า',
            'wms.items.create' => 'เพิ่มสินค้า',
            'wms.items.update' => 'แก้ไขสินค้า',
            'wms.item-categories.view' => 'ดูหมวดสินค้า',
            'wms.item-categories.create' => 'เพิ่มหมวดสินค้า',
            'wms.item-categories.update' => 'แก้ไขหมวดสินค้า',
            'wms.item-categories.delete' => 'ลบหมวดสินค้า',
            'wms.uoms.view' => 'ดูหน่วยนับ',
            'wms.uoms.create' => 'เพิ่มหน่วยนับ',
            'wms.uoms.update' => 'แก้ไขหน่วยนับ',
            'wms.uom-conversions.view' => 'ดูอัตราแปลงหน่วย',
            'wms.uom-conversions.create' => 'เพิ่มอัตราแปลงหน่วย',
            'wms.stock.view' => 'ดู Stock Card และยอดคงเหลือ',
            'wms.inventory-adjustments.view' => 'ดูรายการปรับปรุงสินค้าคงเหลือ',
            'wms.inventory-adjustments.create' => 'สร้างรายการปรับปรุงสินค้าคงเหลือ',
            'wms.inventory-adjustments.update' => 'แก้ไขร่างรายการปรับปรุงสินค้าคงเหลือ',
            'wms.inventory-adjustments.delete' => 'ลบร่างรายการปรับปรุงสินค้าคงเหลือ',
            'wms.inventory-adjustments.approve' => 'อนุมัติรายการปรับปรุงสินค้าคงเหลือ',
            'wms.inventory-adjustments.post' => 'ลงบัญชีรายการปรับปรุงสินค้าคงเหลือ',
            'wms.inventory-adjustments.reverse' => 'กลับรายการปรับปรุงสินค้าคงเหลือที่ลงบัญชีแล้ว',
            'wms.issues.view' => 'ดูใบเบิกสินค้า',
            'wms.issues.create' => 'สร้างใบเบิกสินค้า',
            'wms.issues.update' => 'แก้ไขร่างใบเบิกสินค้า',
            'wms.issues.delete' => 'ลบร่างใบเบิกสินค้า',
            'wms.issues.approve' => 'อนุมัติใบเบิกสินค้า',
            'wms.issues.post' => 'ลง Stock ใบเบิกสินค้า',
            'wms.issue-returns.view' => 'ดูใบรับคืนจากการเบิก',
            'wms.issue-returns.create' => 'สร้างใบรับคืนจากการเบิก',
            'wms.issue-returns.update' => 'แก้ไขร่างใบรับคืนจากการเบิก',
            'wms.issue-returns.delete' => 'ลบร่างใบรับคืนจากการเบิก',
            'wms.issue-returns.approve' => 'อนุมัติใบรับคืนจากการเบิก',
            'wms.issue-returns.post' => 'ลง Stock ใบรับคืนจากการเบิก',
            'wms.stock-counts.view' => 'ดูเอกสารตรวจนับสินค้าและผลต่าง',
            'wms.stock-counts.create' => 'สร้างเอกสารตรวจนับสินค้า',
            'wms.stock-counts.update' => 'แก้ไขเอกสารตรวจนับสินค้าร่าง',
            'wms.stock-counts.approve' => 'อนุมัติผลตรวจนับสินค้า',
            'wms.stock-counts.delete' => 'ลบร่างเอกสารตรวจนับสินค้า',
            'wms.stock-valuation.view' => 'ดูรายงานมูลค่าสินค้าคงเหลือ',
            'wms.stock-policies.view' => 'ดูการตั้งค่า Min/Max Stock',
            'wms.stock-policies.create' => 'สร้างการตั้งค่า Min/Max Stock',
            'wms.stock-policies.update' => 'แก้ไขการตั้งค่า Min/Max Stock',
            'wms.stock-policies.delete' => 'ลบการตั้งค่า Min/Max Stock',
            'wms.issue-types.view' => 'ดูประเภทการเบิกสินค้า',
            'wms.issue-types.create' => 'สร้างประเภทการเบิกสินค้า',
            'wms.issue-types.update' => 'แก้ไขประเภทการเบิกสินค้า',
            'wms.issue-types.delete' => 'ลบประเภทการเบิกสินค้า',
            'wms.transfers.view' => 'ดูรายการโอนคลัง',
            'wms.transfers.create' => 'สร้างร่างโอนคลัง',
            'wms.transfers.dispatch' => 'ส่งโอนออกจากคลังต้นทาง',
            'wms.transfers.complete' => 'รับหรือปฏิเสธโอนเข้าคลังปลายทาง',
            'wms.transfers.void' => 'ยกเลิก Transfer ที่ปลายทางปฏิเสธ',
            'wms.recost.retry' => 'ส่งรายการ Recost ที่ค้างกลับเข้าคิว',
            'wms.cost-allocation-reviews.view' => 'ดูรายการ Cost Allocation Legacy ที่ต้องตรวจสอบ',
            'wms.purchase-documents.view' => 'ดูใบตั้งหนี้และใบลดหนี้ซื้อ',
            'wms.purchase-documents.print' => 'พิมพ์ใบตั้งหนี้และใบลดหนี้ซื้อเป็น PDF',
            'wms.purchase-documents.create' => 'สร้างใบตั้งหนี้และใบลดหนี้ซื้อ',
            'wms.purchase-documents.update' => 'แก้ไขร่างใบตั้งหนี้และใบลดหนี้ซื้อ',
            'wms.purchase-documents.delete' => 'ลบร่างใบตั้งหนี้และใบลดหนี้ซื้อก่อนอนุมัติ',
            'wms.purchase-documents.approve' => 'อนุมัติใบตั้งหนี้และใบลดหนี้ซื้อ',
            'wms.purchase-documents.post' => 'Post ใบตั้งหนี้และใบลดหนี้ซื้อเข้าบัญชี',
            'wms.purchase-documents.inventory-post' => 'Post ใบซื้อเข้าสต็อกและบัญชี Inventory',
            'wms.purchase-documents.inventory-reverse' => 'กลับรายการใบซื้อ Inventory ที่ลงบัญชีแล้ว',
            'wms.purchase-documents.void' => 'ยกเลิกใบตั้งหนี้และใบลดหนี้ซื้อที่ยังไม่ลงบัญชี',
            'wms.purchase-requisitions.view' => 'ดูใบขอซื้อ',
            'wms.purchase-requisitions.print' => 'พิมพ์ใบขอซื้อเป็น PDF',
            'wms.purchase-requisitions.create' => 'สร้างใบขอซื้อ',
            'wms.purchase-requisitions.update' => 'แก้ไขใบขอซื้อร่างหรือตีกลับ',
            'wms.purchase-requisitions.delete' => 'ลบใบขอซื้อร่างหรือตีกลับ',
            'wms.purchase-requisitions.submit' => 'ส่งใบขอซื้อเพื่ออนุมัติ',
            'wms.purchase-requisitions.approve' => 'อนุมัติใบขอซื้อ',
            'wms.purchase-requisitions.reject' => 'ตีกลับใบขอซื้อ',
            'wms.purchase-requisitions.void' => 'ยกเลิกใบขอซื้อ',
            'wms.purchase-requisitions.create-po' => 'สร้าง Purchase Order จากใบขอซื้อที่อนุมัติแล้ว',
            'wms.purchase-orders.view' => 'ดูใบสั่งซื้อ',
            'wms.purchase-orders.print' => 'พิมพ์ใบสั่งซื้อเป็น PDF',
            'wms.purchase-orders.create' => 'สร้างใบสั่งซื้อ',
            'wms.purchase-orders.update' => 'แก้ไขร่างใบสั่งซื้อและกรอกราคา',
            'wms.purchase-orders.delete' => 'ลบร่างใบสั่งซื้อ',
            'wms.purchase-orders.approve' => 'อนุมัติใบสั่งซื้อ',
            'wms.purchase-orders.void' => 'ยกเลิกใบสั่งซื้อ',
            'wms.purchase-receipts.view' => 'ดู Draft Receipt จากใบซื้อ',
            'wms.purchase-receipts.print' => 'พิมพ์ใบรับสินค้าเป็น PDF',
            'wms.purchase-receipts.create' => 'สร้าง Draft Receipt จากใบซื้อ',
            'wms.purchase-receipts.update' => 'แก้ไข Draft Receipt',
            'wms.purchase-receipts.approve' => 'อนุมัติ Receipt',
            'wms.purchase-receipts.void' => 'ยกเลิก Receipt',
            'pos.dashboard.view' => 'ดู Sales Dashboard',
            'pos.sales-reports.view' => 'ดูรายงานยอดขาย',
            'pos.branch-sales-targets.view' => 'ดูเป้ายอดขายสาขา',
            'pos.branch-sales-targets.create' => 'ตั้งเป้ายอดขายสาขา',
            'pos.branch-sales-targets.update' => 'แก้ไขเป้ายอดขายสาขา',
            'pos.branch-sales-targets.delete' => 'ลบเป้ายอดขายสาขา',
            'pos.workflow.view' => 'ดูคู่มือการทำงาน Sales/POS',
            'pos.customers.view' => 'ดูลูกค้า',
            'pos.customers.create' => 'เพิ่มลูกค้า',
            'pos.customers.update' => 'แก้ไขลูกค้า',
            'pos.customers.delete' => 'ลบลูกค้า',
            'pos.customer-groups.view' => 'ดูกลุ่มลูกค้า',
            'pos.customer-groups.create' => 'เพิ่มกลุ่มลูกค้า',
            'pos.customer-groups.update' => 'แก้ไขกลุ่มลูกค้า',
            'pos.customer-groups.delete' => 'ลบกลุ่มลูกค้า',
            'pos.price-lists.view' => 'ดูรายการราคา',
            'pos.price-lists.create' => 'สร้างรายการราคา',
            'pos.price-lists.update' => 'แก้ไขรายการราคา',
            'pos.price-lists.delete' => 'ลบรายการราคา',
            'pos.promotions.view' => 'ดูโปรโมชั่น',
            'pos.promotions.create' => 'สร้างโปรโมชั่น',
            'pos.promotions.update' => 'แก้ไขโปรโมชั่น',
            'pos.promotions.delete' => 'ลบโปรโมชั่น',
            'pos.commission-plans.view' => 'ดูการตั้งค่าคอมมิชชั่นขาย',
            'pos.commission-plans.create' => 'สร้างแผนคอมมิชชั่นขาย',
            'pos.commission-plans.update' => 'แก้ไขแผนคอมมิชชั่นขาย',
            'pos.commission-plans.delete' => 'ลบแผนคอมมิชชั่นขาย',
            'pos.employee-sales-targets.view' => 'ดูเป้าหมายพนักงานขาย',
            'pos.employee-sales-targets.create' => 'เพิ่มเป้าหมายพนักงานขาย',
            'pos.employee-sales-targets.update' => 'แก้ไขเป้าหมายพนักงานขาย',
            'pos.employee-sales-targets.delete' => 'ลบเป้าหมายพนักงานขาย',
            'pos.sales-commissions.view' => 'ดูรายงานคอมมิชชั่นขาย',
            'pos.sales-commissions.approve' => 'อนุมัติคอมมิชชั่นขาย',
            'pos.sales-commissions.pay' => 'สร้างและส่งชุดจ่ายคอมมิชชั่นให้ฝ่ายการเงิน',
            'pos.commission-payouts.view' => 'ดูชุดจ่ายคอมมิชชั่น',
            'pos.commission-payouts.create' => 'สร้างชุดจ่ายคอมมิชชั่น',
            'pos.commission-payouts.post' => 'Post ชุดจ่ายคอมมิชชั่น',
            'pos.commission-payouts.void' => 'ยกเลิกชุดจ่ายคอมมิชชั่น',
            'pos.commission-payouts.reverse' => 'กลับรายการจ่ายคอมมิชชั่น',
            'finance.commission-payouts.view' => 'ดูชุดจ่ายคอมมิชชั่น',
            'finance.commission-payouts.create' => 'สร้างชุดจ่ายคอมมิชชั่น',
            'finance.commission-payouts.post' => 'Post ชุดจ่ายคอมมิชชั่น',
            'finance.commission-payouts.void' => 'ยกเลิกชุดจ่ายคอมมิชชั่น',
            'finance.commission-payouts.reverse' => 'กลับรายการจ่ายคอมมิชชั่น',
            'pos.sales-documents.view' => 'ดูใบแจ้งหนี้และใบลดหนี้ขาย',
            'pos.sales-documents.create' => 'สร้างใบแจ้งหนี้และใบลดหนี้ขาย',
            'pos.sales-documents.update' => 'แก้ไขร่างใบแจ้งหนี้และใบลดหนี้ขาย',
            'pos.sales-documents.approve' => 'อนุมัติใบแจ้งหนี้และใบลดหนี้ขาย',
            'pos.sales-documents.post' => 'Post ใบแจ้งหนี้และใบลดหนี้ขายเข้าบัญชี',
            'pos.sales-documents.void' => 'ยกเลิกใบแจ้งหนี้และใบลดหนี้ขายที่ยังไม่ลงบัญชี',
            'pos.sales-rfqs.view' => 'ดูใบขอราคาขาย',
            'pos.sales-rfqs.create' => 'สร้างใบขอราคาขาย',
            'pos.sales-rfqs.update' => 'แก้ไขร่างใบขอราคาขาย',
            'pos.sales-rfqs.send' => 'ส่งใบขอราคาขาย',
            'pos.sales-rfqs.close' => 'ปิดใบขอราคาขาย',
            'pos.sales-rfqs.cancel' => 'ยกเลิกใบขอราคาขาย',
            'pos.sales-rfqs.print' => 'พิมพ์ใบขอราคา PDF',
            'pos.sales-rfqs.approve' => 'พิจารณาและอนุมัติ RFQ',
            'pos.sales-quotations.view' => 'ดูใบเสนอราคา',
            'pos.sales-quotations.create' => 'สร้างใบเสนอราคาจากใบขอราคา',
            'pos.sales-quotations.update' => 'แก้ไขร่างใบเสนอราคา',
            'pos.sales-quotations.print' => 'พิมพ์ใบเสนอราคา PDF',
            'pos.sales-quotations.send' => 'ส่งใบเสนอราคา',
            'pos.sales-quotations.accept' => 'ตอบรับใบเสนอราคา',
            'pos.sales-quotations.reject' => 'ปฏิเสธใบเสนอราคา',
            'pos.sales-quotations.cancel' => 'ยกเลิกใบเสนอราคา',
            'pos.sales-orders.view' => 'ดูใบสั่งขาย',
            'pos.sales-orders.create' => 'สร้างใบสั่งขายจากใบเสนอราคา',
            'pos.sales-orders.confirm' => 'ยืนยันใบสั่งขาย',
            'pos.sales-orders.cancel' => 'ยกเลิกใบสั่งขาย',
            'pos.sales-orders.print' => 'พิมพ์ใบสั่งขาย PDF',
            'pos.sales-intakes.view' => 'ดูใบรับข้อมูลเบื้องต้น',
            'pos.sales-intakes.create' => 'สร้างใบรับข้อมูลเบื้องต้น',
            'pos.sales-intakes.update' => 'แก้ไขร่างใบรับข้อมูลเบื้องต้น',
            'pos.sales-intakes.complete' => 'ทำใบรับข้อมูลเบื้องต้นให้เสร็จสิ้น',
            'pos.sales-intakes.cancel' => 'ยกเลิกใบรับข้อมูลเบื้องต้น',
            'pos.sales-intakes.delete' => 'ลบร่างใบรับข้อมูลเบื้องต้น',
            'pos.sales-intakes.convert' => 'เปลี่ยนใบรับข้อมูลเป็นใบขอราคา',
            'pos.sales-intakes.print' => 'พิมพ์ใบรับข้อมูลเบื้องต้น PDF',
            'pos.physical-sales.view' => 'ดูใบขายสดและใบขายเชื่อ HS/IV',
            'pos.physical-sales.create' => 'สร้างร่างใบขายสดและใบขายเชื่อ HS/IV',
            'pos.physical-sales.post' => 'ยืนยันขายและลงบัญชี HS/IV',
            'pos.physical-sales.cancel-full' => 'ยกเลิกทั้งใบ HS/IV ที่ลงบัญชีแล้วด้วยเอกสารคืนสินค้าและลดหนี้เต็มจำนวน',
            'pos.physical-sales.receive-payment' => 'รับชำระเงิน HS/IV จากหน้า POS',
            'pos.physical-sales.print' => 'พิมพ์ใบขายสดและใบขายเชื่อ PDF',
            'pos.receipts.view' => 'ดูเอกสารรับชำระหนี้ใน POS',
            'pos.receipts.create' => 'สร้างเอกสารรับชำระหนี้ใน POS',
            'pos.receipts.approve' => 'อนุมัติเอกสารรับชำระหนี้ใน POS',
            'pos.receipts.post' => 'ลงบัญชีเอกสารรับชำระหนี้ใน POS',
            'pos.receipts.reverse' => 'ยกเลิกเอกสารรับชำระหนี้ที่ลงบัญชีแล้วใน POS',
            'pos.receivables.view' => 'ดูและติดตามลูกหนี้คงค้างใน POS',
            'pos.advance-deposits.view' => 'ดูใบรับเงินล่วงหน้า AI ใน POS',
            'pos.advance-deposits.create' => 'สร้างและรับชำระใบรับเงินล่วงหน้า AI ใน POS',
            'pos.advance-deposits.refund' => 'คืนเงินและกลับรายการใบรับเงินล่วงหน้า AI ที่ยังไม่ถูกนำไปใช้',
            'pos.advance-deposits.print' => 'พิมพ์ใบรับเงินล่วงหน้า AI PDF',
            'pos.sales-returns.view' => 'ดูใบรับคืนและใบลดหนี้จาก HS/IV',
            'pos.sales-returns.create' => 'สร้างร่างใบรับคืนและใบลดหนี้',
            'pos.sales-returns.post' => 'Post ใบรับคืนและใบลดหนี้ให้กระทบ Stock และ GL',
            'pos.sales-returns.cancel' => 'ยกเลิกร่างใบรับคืนและใบลดหนี้',
            'pos.sales-returns.print' => 'พิมพ์ใบรับคืนและใบลดหนี้ PDF',
        ])->each(function (string $name, string $code) {
            $permission = Permission::query()->withTrashed()->firstOrNew(['code' => $code]);
            $permission->fill(['name' => $name]);
            $permission->deleted_at = null;
            $permission->save();
        });

        // Purchasing is the canonical module name. Keep an explicit alias
        // set for the extracted /purchasing surface; User::hasPermission()
        // bridges these codes with the legacy wms.* permissions during the
        // compatibility period.
        collect([
            'purchasing.dashboard.view' => 'ดู Purchasing Dashboard',
            'purchasing.workflow.view' => 'ดูคู่มือการทำงาน Purchasing',
            'purchasing.reports.view' => 'ดูรายงานปฏิบัติการจัดซื้อ',
            'purchasing.suppliers.view' => 'ดู Supplier',
            'purchasing.suppliers.create' => 'เพิ่ม Supplier',
            'purchasing.suppliers.update' => 'แก้ไข Supplier',
            'purchasing.suppliers.delete' => 'ลบ Supplier',
            'purchasing.purchase-requisitions.view' => 'ดูใบขอซื้อ',
            'purchasing.purchase-requisitions.print' => 'พิมพ์ใบขอซื้อเป็น PDF',
            'purchasing.purchase-requisitions.create' => 'สร้างใบขอซื้อ',
            'purchasing.purchase-requisitions.update' => 'แก้ไขใบขอซื้อ',
            'purchasing.purchase-requisitions.delete' => 'ลบใบขอซื้อร่าง',
            'purchasing.purchase-requisitions.submit' => 'ส่งใบขอซื้อเพื่ออนุมัติ',
            'purchasing.purchase-requisitions.approve' => 'อนุมัติใบขอซื้อ',
            'purchasing.purchase-requisitions.reject' => 'ตีกลับใบขอซื้อ',
            'purchasing.purchase-requisitions.void' => 'ยกเลิกใบขอซื้อ',
            'purchasing.purchase-requisitions.create-po' => 'สร้างใบสั่งซื้อจากใบขอซื้อ',
            'purchasing.purchase-orders.view' => 'ดูใบสั่งซื้อ',
            'purchasing.purchase-orders.print' => 'พิมพ์ใบสั่งซื้อเป็น PDF',
            'purchasing.purchase-orders.create' => 'สร้างใบสั่งซื้อ',
            'purchasing.purchase-orders.update' => 'แก้ไขใบสั่งซื้อร่าง',
            'purchasing.purchase-orders.delete' => 'ลบใบสั่งซื้อร่าง',
            'purchasing.purchase-orders.approve' => 'อนุมัติใบสั่งซื้อ',
            'purchasing.purchase-orders.void' => 'ยกเลิกใบสั่งซื้อ',
            'purchasing.purchase-receipts.view' => 'ดูใบรับสินค้า',
            'purchasing.purchase-receipts.print' => 'พิมพ์ใบรับสินค้าเป็น PDF',
            'purchasing.purchase-receipts.create' => 'สร้างใบรับสินค้า',
            'purchasing.purchase-receipts.update' => 'แก้ไขใบรับสินค้าร่าง',
            'purchasing.purchase-receipts.approve' => 'อนุมัติใบรับสินค้า',
            'purchasing.purchase-receipts.void' => 'ยกเลิกใบรับสินค้า',
            'purchasing.purchase-documents.view' => 'ดูใบตั้งหนี้และใบลดหนี้ซื้อ',
            'purchasing.purchase-documents.print' => 'พิมพ์ใบตั้งหนี้และใบลดหนี้ซื้อเป็น PDF',
            'purchasing.purchase-documents.create' => 'สร้างใบตั้งหนี้และใบลดหนี้ซื้อ',
            'purchasing.purchase-documents.update' => 'แก้ไขใบตั้งหนี้ร่าง',
            'purchasing.purchase-documents.delete' => 'ลบใบตั้งหนี้ร่าง',
            'purchasing.purchase-documents.approve' => 'อนุมัติใบตั้งหนี้และใบลดหนี้ซื้อ',
            'purchasing.purchase-documents.post' => 'Post ใบตั้งหนี้และใบลดหนี้ซื้อ',
            'purchasing.purchase-documents.inventory-post' => 'Post ใบซื้อเข้า Inventory',
            'purchasing.purchase-documents.inventory-reverse' => 'กลับรายการใบซื้อ Inventory',
            'purchasing.purchase-documents.void' => 'ยกเลิกใบตั้งหนี้ที่ยังไม่ลงบัญชี',
        ])->each(function (string $name, string $code) {
            $permission = Permission::query()->withTrashed()->firstOrNew(['code' => $code]);
            $permission->fill(['name' => $name]);
            $permission->deleted_at = null;
            $permission->save();
        });

        $adminRole = Role::query()->withTrashed()->firstOrNew(['code' => 'admin']);
        $adminRole->fill([
            'name' => 'ผู้ดูแลระบบ',
            'description' => 'เข้าถึงและจัดการระบบได้ทุกส่วน',
            'is_active' => true,
        ]);
        $adminRole->deleted_at = null;
        $adminRole->save();

        $adminRole->permissions()->sync(Permission::query()->pluck('id'));

        User::query()->where('username', 'admin')->first()?->roles()->syncWithoutDetaching([$adminRole->id]);
    }
}
