@extends('Crm::layout')
@section('title','การแจ้งเตือน | CRM')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page module-dashboard module-dashboard--crm">
    <div class="module-dashboard-hero mb-4 crm-page-header"><p class="module-dashboard-kicker mb-2"><span></span>CRM / NOTIFICATIONS</p><h1>การแจ้งเตือน</h1><p class="mb-0">งานใกล้ครบกำหนด งานเกินกำหนด และสรุปงานประจำวัน</p></div>
    <section class="card mb-4" aria-labelledby="reminder-title"><form class="card-body" id="reminder-preference"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3"><div><h2 class="h5 mb-1" id="reminder-title">แจ้งเตือนก่อนถึงกำหนด</h2><p class="text-secondary mb-0">ใช้กับ Activity ที่คุณเป็นผู้รับผิดชอบ ทั้ง In-app และ Browser Push ที่เปิดใช้งาน</p></div><div class="d-flex flex-wrap align-items-end gap-2"><div class="form-check form-switch mb-2"><input class="form-check-input" id="reminder-enabled" name="reminder_enabled" type="checkbox" value="1" @checked($reminderEnabled)><label class="form-check-label" for="reminder-enabled">เปิดแจ้งเตือน</label></div><div><label class="form-label" for="reminder-minutes">แจ้งล่วงหน้า</label><select class="form-select" id="reminder-minutes" name="reminder_minutes">@foreach([5=>'5 นาที',15=>'15 นาที',30=>'30 นาที',60=>'1 ชั่วโมง',120=>'2 ชั่วโมง',1440=>'1 วัน'] as $minutes=>$label)<option value="{{ $minutes }}" @selected($reminderMinutes===$minutes)>{{ $label }}</option>@endforeach</select></div><button class="btn btn-app-primary" id="reminder-save" type="submit"><i class="bx bx-save me-1" aria-hidden="true"></i>บันทึก</button></div></div><div class="small mt-2 d-none" id="reminder-feedback" role="status"></div></form></section>
    <section class="card mb-4" aria-labelledby="push-title"><div class="card-body d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3"><div><h2 class="h5 mb-1" id="push-title">Browser Push Notification</h2><p class="text-secondary mb-0" id="push-status">กำลังตรวจสอบความพร้อมของ Browser...</p></div><button class="btn btn-app-primary align-self-start align-self-md-center" id="push-toggle" type="button" disabled><i class="bx bx-bell me-1" aria-hidden="true"></i>เปิด Browser Push</button></div></section>
    <div class="card mb-4"><div class="card-body"><form id="notification-filter" class="d-flex gap-2"><select class="form-select" name="status" aria-label="สถานะ"><option value="ALL">ทั้งหมด</option><option value="UNREAD">ยังไม่ได้อ่าน</option></select><button class="btn btn-app-primary" type="submit">ค้นหา</button></form></div></div>
    <div class="d-flex justify-content-between mb-3"><h2 class="h5">รายการแจ้งเตือน</h2><span class="small text-secondary" id="notification-summary">กำลังโหลด...</span></div><div id="notification-list" aria-live="polite" aria-busy="true"></div><nav id="notification-pagination" class="mt-4"></nav>
</div>
@endsection
@push('scripts')
<script>
$(function(){
 const form=$('#notification-filter'),list=$('#notification-list'),pages=$('#notification-pagination'),summary=$('#notification-summary'),url=@json(route('crm.notifications.data'));let request;
 function load(page){if(request)request.abort();const p=new URLSearchParams(new FormData(form[0]));if(page>1)p.set('page',page);list.attr('aria-busy','true').html('<div class="text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2"></span>กำลังโหลด...</div>');request=$.getJSON(url,p.toString()).done(d=>{list.html(d.html).attr('aria-busy','false');pages.html(d.pagination);summary.text(d.total?'แสดง '+d.from+'–'+d.to+' จาก '+d.total:'ไม่พบรายการ');}).fail((x,s)=>{if(s!=='abort')list.html('<div class="alert alert-danger">โหลดการแจ้งเตือนไม่สำเร็จ</div>');});}
 $('#reminder-preference').on('submit',function(e){e.preventDefault();const button=$('#reminder-save'),feedback=$('#reminder-feedback');button.prop('disabled',true);$.ajax({url:@json(route('crm.notifications.preferences.update')),method:'PUT',data:{reminder_enabled:$('#reminder-enabled').is(':checked')?1:0,reminder_minutes:$('#reminder-minutes').val(),_token:$('meta[name=csrf-token]').attr('content')}}).done(response=>feedback.removeClass('d-none text-danger').addClass('text-success').text(response.msg)).fail(xhr=>feedback.removeClass('d-none text-success').addClass('text-danger').text(xhr.responseJSON?.message||'บันทึกการตั้งค่าไม่สำเร็จ')).always(()=>button.prop('disabled',false));});$('#reminder-enabled').on('change',function(){$('#reminder-minutes').prop('disabled',!this.checked);}).trigger('change');
 form.on('submit',e=>{e.preventDefault();load(1);});pages.on('click','a',function(e){e.preventDefault();load(Number(new URL(this.href).searchParams.get('page')||1));});list.on('click','.js-read-notification',function(){const b=$(this);b.prop('disabled',true);$.post(b.data('url'),{_token:$('meta[name=csrf-token]').attr('content')}).done(()=>load(1)).fail(x=>{b.prop('disabled',false);window.erpAjaxError(x);});});load(1);
 const toggle=$('#push-toggle'),status=$('#push-status'),publicKey=@json($vapidPublicKey),subscribeUrl=@json(route('crm.notifications.push.subscribe')),unsubscribeUrl=@json(route('crm.notifications.push.unsubscribe'));let registration,subscription;
 const bytes=value=>{const padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)));};
 function paint(){const denied=Notification.permission==='denied';toggle.prop('disabled',denied||!registration).toggleClass('btn-app-primary',!subscription).toggleClass('btn-app-danger',!!subscription).html(subscription?'<i class="bx bx-bell-off me-1" aria-hidden="true"></i>ปิด Browser Push':'<i class="bx bx-bell me-1" aria-hidden="true"></i>เปิด Browser Push');status.text(denied?'Browser ปฏิเสธการแจ้งเตือน กรุณาอนุญาตจากการตั้งค่าเว็บไซต์':(subscription?'เปิด Browser Push บนอุปกรณ์นี้แล้ว':'ยังไม่ได้เปิด Browser Push บนอุปกรณ์นี้'));}
 async function initPush(){if(!window.isSecureContext||!('serviceWorker'in navigator)||!('PushManager'in window)||!publicKey){status.text('Browser Push ต้องใช้ HTTPS หรือ localhost และ VAPID key');return;}registration=await navigator.serviceWorker.register('/crm-push-sw.js');subscription=await registration.pushManager.getSubscription();paint();}
 toggle.on('click',async function(){try{toggle.prop('disabled',true);if(subscription){await $.ajax({url:unsubscribeUrl,method:'DELETE',data:{endpoint:subscription.endpoint},headers:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}});await subscription.unsubscribe();subscription=null;}else{const permission=await Notification.requestPermission();if(permission!=='granted'){paint();return;}subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(publicKey)});const payload=subscription.toJSON();await $.post(subscribeUrl,{endpoint:payload.endpoint,keys:payload.keys,contentEncoding:(PushManager.supportedContentEncodings||[])[0]||null,_token:$('meta[name="csrf-token"]').attr('content')});}paint();}catch(error){paint();const pushServiceError=(error.message||'').toLowerCase().includes('push service');status.text(pushServiceError?'ติดต่อ Push Service ของ Browser ไม่สำเร็จ กรุณาตรวจการตั้งค่า Browser และเครือข่าย':'ตั้งค่า Browser Push ไม่สำเร็จ');Swal.fire({icon:'error',title:'ตั้งค่า Browser Push ไม่สำเร็จ',html:pushServiceError?'Browser ติดต่อ Push Service ไม่ได้<br><small>Chrome/Edge: ตรวจว่าอนุญาต Notification และไม่ได้ปิด Google/Microsoft Push Service<br>Brave: เปิด Use Google services for push messaging แล้วเปิด Browser ใหม่</small>':$('<div>').text(error.message||'กรุณาลองใหม่').html()});}});initPush().catch(()=>status.text('ไม่สามารถเริ่ม Browser Push ได้'));
});
</script>
@endpush
