@extends('Wms::layout')
@section('title', 'ปรับปรุงสินค้าคงเหลือ | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
 <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">WMS / INVENTORY</p><h1 class="h3 mb-2">ปรับปรุงสินค้าคงเหลือ</h1><p class="text-secondary mb-0">สร้างรายการเพิ่ม/ลดจากการตรวจนับ แล้วอนุมัติก่อนลง Stock และ GL</p></div><div class="d-flex flex-wrap align-items-end gap-2">@include('Wms::partials.warehouse-selector') <a class="btn btn-dark" href="{{ route('wms.inventory-adjustments.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>สร้างรายการ</a></div></div>
 <div class="card border-0 shadow-sm"><div class="card-body"><table id="adjustment-table" class="table table-hover align-middle w-100" data-url="{{ route('wms.inventory-adjustments.data') }}"><thead><tr><th>เลขที่เอกสาร</th><th>วันที่</th><th>รายการ</th><th>ทิศทาง</th><th>จำนวนรวม</th><th>มูลค่ารวม</th><th>เหตุผล</th><th>สถานะ</th><th>จัดการ</th></tr></thead></table></div></div>
</div>
@endsection
@push('scripts')
<script>
$(function(){const t=$('#adjustment-table'),esc=$.fn.dataTable.render.text();const table=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:t.data('url'),buttons:[window.erpExcelButton(t)],columns:[{data:'document_number',render:esc.display},{data:'business_date',render:esc.display},{data:null,render:function(v,type,r){if(type!=='display')return r.line_count;return '<div>'+esc.display(r.line_count+' รายการ')+'</div><small class="text-secondary d-block text-truncate" style="max-width:280px" title="'+esc.display(r.item_label)+'">'+esc.display(r.item_label)+'</small>';}},{data:'direction_label',render:esc.display},{data:'quantity',className:'text-end',render:esc.display},{data:'value',className:'text-end',render:esc.display},{data:'reason',render:esc.display},{data:'status_label',render:function(v,type,r){return type==='display'?'<span class="badge '+(r.status==='POSTED'?'app-status-success':r.status==='APPROVED'?'app-status-info':r.status==='REVERSED'?'app-status-warning':'app-status-neutral')+'">'+esc.display(v)+'</span>':v;}},{data:null,orderable:false,searchable:false,className:'text-end text-nowrap',render:function(v,type,r){if(type!=='display')return '';let h='<a class="btn btn-sm btn-app-soft" href="'+r.show_url+'" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-show" aria-hidden="true"></i></a> ';if(r.can_approve)h+='<button class="btn btn-sm btn-app-soft js-adjust-action" data-id="'+r.id+'" data-action="approve" title="อนุมัติ" aria-label="อนุมัติ"><i class="bx bx-check" aria-hidden="true"></i></button> ';if(r.can_post)h+='<button class="btn btn-sm btn-app-soft js-adjust-action" data-id="'+r.id+'" data-action="post" title="ลงบัญชี" aria-label="ลงบัญชี"><i class="bx bx-send" aria-hidden="true"></i></button> ';if(r.can_reverse)h+='<button class="btn btn-sm btn-app-danger js-adjust-reverse" data-id="'+r.id+'" title="กลับรายการทั้งเอกสาร" aria-label="กลับรายการทั้งเอกสาร"><i class="bx bx-revision" aria-hidden="true"></i></button> ';if(r.can_delete)h+='<button class="btn btn-sm btn-app-danger js-adjust-action" data-id="'+r.id+'" data-action="delete" title="ลบร่าง" aria-label="ลบร่าง"><i class="bx bx-trash" aria-hidden="true"></i></button>';return h;}}]}));
$(document).on('click','.js-adjust-action',function(){const b=$(this),a=b.data('action'),url='{{ url('/wms/inventory-adjustments/documents') }}/'+b.data('id')+'/'+a;Swal.fire({icon:'warning',title:a==='approve'?'อนุมัติเอกสารนี้?':a==='post'?'ลงบัญชีเอกสารนี้?':'ลบร่างเอกสารนี้?',showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ยกเลิก'}).then(x=>{if(!x.isConfirmed)return;$.ajax({url:url,type:a==='delete'?'DELETE':'POST',data:{_token:$('meta[name=csrf-token]').attr('content')}}).done(r=>{Swal.fire({icon:'success',text:r.msg,timer:1200,showConfirmButton:false});table.ajax.reload(null,false)}).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ดำเนินการไม่สำเร็จ'}));});});
$(document).on('click','.js-adjust-reverse',function(){const b=$(this);Swal.fire({icon:'warning',title:'กลับรายการทั้งเอกสาร?',input:'textarea',inputPlaceholder:'เหตุผลอย่างน้อย 10 ตัวอักษร',showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ยกเลิก',preConfirm:v=>{if(!v||v.trim().length<10){Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร');return false;}return v;}}).then(x=>{if(!x.isConfirmed)return;$.post('{{ url('/wms/inventory-adjustments/documents') }}/'+b.data('id')+'/reverse',{_token:$('meta[name=csrf-token]').attr('content'),reversal_date:'{{ now()->format('Y-m-d') }}',reason:x.value}).done(r=>{Swal.fire({icon:'success',text:r.msg,timer:1200,showConfirmButton:false});table.ajax.reload(null,false)}).fail(e=>{const errors=e.responseJSON?.errors||{};const detail=Object.values(errors).flat().join(' ')||e.responseJSON?.message||'กลับรายการไม่สำเร็จ';Swal.fire({icon:'error',text:detail});});});});});
</script>
@endpush
