@extends('Pos::layout')

@section('title', ($target->exists ? 'แก้ไข' : 'เพิ่ม').' เป้ายอดขายสาขา | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><p class="eyebrow mb-2">POS / TARGETS</p><h1 class="h3 mb-2">{{ $target->exists ? 'แก้ไข' : 'เพิ่ม' }}เป้ายอดขายสาขา</h1><p class="text-secondary mb-4">บันทึกเฉพาะสาขา {{ $branch->code }} · {{ $branch->name }} ที่เลือกอยู่ในขณะนี้</p><div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><form id="branch-sales-target-form" method="POST" action="{{ $target->exists ? route('pos.branch-sales-targets.update', $target) : route('pos.branch-sales-targets.store') }}">@csrf @if($target->exists)@method('PUT')@endif<div class="row g-3"><div class="col-md-3"><label class="form-label" for="period-start">วันที่เริ่ม <span class="text-danger">*</span></label><input id="period-start" class="form-control" type="date" name="period_start" value="{{ old('period_start', $target->period_start?->format('Y-m-d')) }}" required><div class="invalid-feedback" data-error-for="period_start"></div></div><div class="col-md-3"><label class="form-label" for="period-end">วันที่สิ้นสุด <span class="text-danger">*</span></label><input id="period-end" class="form-control" type="date" name="period_end" value="{{ old('period_end', $target->period_end?->format('Y-m-d')) }}" required><div class="invalid-feedback" data-error-for="period_end"></div></div><div class="col-md-3"><label class="form-label" for="target-sales">เป้ายอดขาย</label><input id="target-sales" class="form-control text-end" type="number" min="0" step="0.01" name="target_sales_amount" value="{{ old('target_sales_amount', $target->target_sales_amount) }}"><div class="form-text">ยอดขายสุทธิหลัง VAT และคืนสินค้า</div><div class="invalid-feedback" data-error-for="target_sales_amount"></div></div><div class="col-md-3"><label class="form-label" for="target-gp">เป้ากำไรขั้นต้น</label><input id="target-gp" class="form-control text-end" type="number" step="0.01" name="target_gross_profit_amount" value="{{ old('target_gross_profit_amount', $target->target_gross_profit_amount) }}"><div class="form-text">ยอดขายสุทธิหักต้นทุนและคอมมิชชั่น</div><div class="invalid-feedback" data-error-for="target_gross_profit_amount"></div></div></div><div class="mt-4"><button class="btn btn-dark" type="submit">บันทึก</button> <a class="btn btn-outline-secondary" href="{{ route('pos.branch-sales-targets.index') }}">ย้อนกลับ</a></div></form></div></div></div>
@endsection

@push('scripts')<script>$(function(){window.erpAjaxForm({form:'#branch-sales-target-form',redirect:{{ $target->exists ? 'false' : 'true' }}});});</script>@endpush
