@extends('Asset::layout')

@section('title', 'สร้างชุดคำนวณค่าเสื่อม | New ERP')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / DEPRECIATION</p><h1 class="h3 mb-2">สร้างชุดคำนวณค่าเสื่อม</h1><p class="text-secondary mb-0">ระบบจะสร้างรายการร่างจากสินทรัพย์ที่เข้าเงื่อนไขในสาขาปัจจุบัน</p></div><a class="btn btn-outline-dark" href="{{ route('asset.depreciations.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>รายการทั้งหมด</a></div>
    <form class="card border-0 shadow-sm" id="depreciation-form" method="post" action="{{ route('asset.depreciations.store') }}">@csrf
        <div class="card-body p-4"><div class="row g-3"><div class="col-12 col-md-6"><label class="form-label" for="fiscal_period_id">งวดบัญชี <span class="text-danger">*</span></label><select class="form-select js-select2" id="fiscal_period_id" name="fiscal_period_id" required><option value="">เลือกงวดบัญชี</option>@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->name }} · {{ $period->start_date?->format('d/m/Y') }} – {{ $period->end_date?->format('d/m/Y') }}</option>@endforeach</select><div class="invalid-feedback" data-error-for="fiscal_period_id"></div></div><div class="col-12 col-md-6"><label class="form-label" for="book_type">สมุดค่าเสื่อม <span class="text-danger">*</span></label><select class="form-select" id="book_type" name="book_type" required><option value="BOOK">บัญชี (Book)</option><option value="TAX">ภาษี (Tax)</option></select><div class="invalid-feedback" data-error-for="book_type"></div></div><div class="col-12 col-md-6"><label class="form-label" for="run_through_date">คำนวณถึงวันที่ <span class="text-danger">*</span></label><input class="form-control" id="run_through_date" type="date" name="run_through_date" value="{{ today()->toDateString() }}" required><div class="form-text">ใช้วันที่สิ้นสุดของงวดที่ต้องการคิดค่าเสื่อม</div><div class="invalid-feedback" data-error-for="run_through_date"></div></div></div><hr class="my-4"><div class="d-flex justify-content-between align-items-center mb-2"><div><h2 class="h5 mb-1">สินทรัพย์ที่คำนวณ</h2><p class="small text-secondary mb-0">ระบบเลือกทั้งหมดเป็นค่าเริ่มต้น; นำเครื่องหมายออกเพื่อตั้งเป็นข้อยกเว้นของงวดนี้</p></div><button class="btn btn-sm btn-outline-dark" id="select-all-assets" type="button">เลือกทั้งหมด</button></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="text-center"><span class="visually-hidden">เลือก</span></th><th>สินทรัพย์</th><th>หมวด</th><th>เหตุผลเมื่อยกเว้น</th></tr></thead><tbody>@forelse($assets as $asset)<tr class="js-asset-row" data-books="{{ $asset->depreciationBooks->pluck('book_type')->join(',') }}"><td class="text-center"><input class="form-check-input js-asset" type="checkbox" name="asset_ids[]" value="{{ $asset->id }}" checked></td><td><div class="fw-semibold">{{ $asset->asset_number }}</div><div class="small text-secondary">{{ $asset->name }}</div></td><td>{{ $asset->category?->code ? $asset->category->code.' · '.$asset->category->name : '-' }}</td><td><input class="form-control form-control-sm js-exclusion-reason d-none" name="exclusion_reasons[{{ $asset->id }}]" maxlength="500" placeholder="ระบุเหตุผลอย่างน้อย 10 ตัวอักษร"></td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">ไม่พบสินทรัพย์ที่เข้าเงื่อนไข</td></tr>@endforelse</tbody></table></div><div class="invalid-feedback d-block" data-error-for="asset_ids"></div></div>
        <div class="card-footer bg-white border-0 p-4 pt-0 d-flex justify-content-end gap-2"><a class="btn btn-outline-dark" href="{{ route('asset.depreciations.index') }}">ยกเลิก</a><button class="btn btn-dark" type="submit"><i class="bx bx-calculator me-1" aria-hidden="true"></i>สร้างและคำนวณ</button></div>
    </form>
</div>
@endsection

@push('scripts')
<script>$(function(){var $book=$('#book_type'),$rows=$('.js-asset-row');function sync(){var type=$book.val();$rows.each(function(){var $row=$(this),available=($row.data('books')||'').split(',').indexOf(type)>=0,$check=$row.find('.js-asset'),$reason=$row.find('.js-exclusion-reason');$row.toggleClass('d-none',!available);$check.prop({disabled:!available,checked:available});$reason.toggleClass('d-none',true).prop('required',false).val('');});}$(document).on('change','.js-asset',function(){var $reason=$(this).closest('tr').find('.js-exclusion-reason'),excluded=!this.checked;$reason.toggleClass('d-none',!excluded).prop('required',excluded);});$book.on('change',sync);$('#select-all-assets').on('click',function(){$rows.not('.d-none').find('.js-asset').prop('checked',true).trigger('change');});sync();window.erpAjaxForm({form:'#depreciation-form',redirect:true,reload:false});});</script>
@endpush
