@extends('Asset::layout')

@section('title', $run->document_number.' | New ERP')

@section('content')
@php
    $labels=['CALCULATING'=>'กำลังคำนวณ','DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'พร้อมลงบัญชี','POSTED'=>'ลงบัญชีแล้ว','REVERSED'=>'ยกเลิกแล้ว','VOID'=>'ยกเลิกแล้ว','FAILED'=>'คำนวณไม่สำเร็จ'];
    $classes=['CALCULATING'=>'app-badge-info','DRAFT'=>'app-badge-soft','SUBMITTED'=>'app-badge-info','APPROVED'=>'app-badge-info','POSTED'=>'app-badge-success','REVERSED'=>'app-status-danger','VOID'=>'app-status-danger','FAILED'=>'app-status-danger'];
    $isBook=$run->book_type==='BOOK';
    $openingTotal=$run->lines->sum(fn ($line) => (float) $line->opening_cost - (float) $line->opening_accumulated_depreciation - (float) $line->opening_accumulated_impairment);
    $closingTotal=$run->lines->sum(fn ($line) => (float) $line->closing_book_value);
    $auditTrail=collect([
        ['สร้างชุดคำนวณ', $run->created_at, $run->createdBy?->name, null],
        ['ส่งอนุมัติ', $run->submitted_at, $run->submittedBy?->name, null],
        ['อนุมัติ', $run->approved_at, $run->approvedBy?->name, null],
        [$isBook ? 'ลงบัญชี' : 'ลง Tax book', $run->posted_at, $run->postedBy?->name, null],
        ['ยกเลิก', $run->reversed_at, $run->reversedBy?->name, $run->reversal_reason],
        ['ยกเลิก', $run->cancelled_at, $run->cancelledBy?->name, $run->cancellation_reason],
    ])->filter(fn ($event) => $event[1])->sortByDesc(fn ($event) => $event[1]);
@endphp
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-xl-row justify-content-between align-items-xl-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / DEPRECIATION</p><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><h1 class="h3 mb-0">{{ $run->document_number }}</h1><span class="badge {{ $classes[$run->status] ?? 'app-status-neutral' }}">{{ $labels[$run->status] ?? $run->status }}</span></div><p class="text-secondary mb-0"><i class="bx bx-calendar me-1" aria-hidden="true"></i>{{ $isBook ? 'ค่าเสื่อมทางบัญชี (Book)' : 'ค่าเสื่อมทางภาษี (Tax)' }} · คำนวณถึง {{ $run->run_through_date?->format('d/m/Y') }}</p></div>
        <div class="d-flex flex-wrap gap-2">
            @if($run->status==='DRAFT' && auth()->user()->hasPermission('asset.depreciation.submit'))<button class="btn btn-dark js-action" type="button" data-url="{{ route('asset.depreciations.submit',$run) }}" data-confirm="ส่งชุดคำนวณค่าเสื่อมเพื่ออนุมัติ?"><i class="bx bx-send me-1" aria-hidden="true"></i>ส่งอนุมัติ</button>@endif
            @if($run->status==='SUBMITTED' && auth()->user()->hasPermission('asset.depreciation.approve'))<button class="btn btn-primary js-action" type="button" data-url="{{ route('asset.depreciations.approve',$run) }}" data-confirm="อนุมัติชุดคำนวณค่าเสื่อมนี้?"><i class="bx bx-check me-1" aria-hidden="true"></i>อนุมัติ</button>@endif
            @if($run->status==='SUBMITTED' && auth()->user()->hasPermission('asset.depreciation.submit'))<button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#cancel-modal"><i class="bx bx-x-circle me-1" aria-hidden="true"></i>ยกเลิก</button>@endif
            @if($run->status==='APPROVED' && auth()->user()->hasPermission('asset.depreciation.post'))@if($postReadiness['ready'])<button class="btn btn-success js-action" type="button" data-url="{{ route('asset.depreciations.post',$run) }}" data-confirm="ลงบัญชีชุดค่าเสื่อมนี้? รายการที่ลงบัญชีแล้วจะแก้ไขโดยตรงไม่ได้"><i class="bx bx-book-open me-1" aria-hidden="true"></i>ลงบัญชี</button>@else<button class="btn btn-success" type="button" disabled><i class="bx bx-book-open me-1" aria-hidden="true"></i>ลงบัญชี</button>@endif @endif
            @if($run->status==='POSTED' && auth()->user()->hasPermission('asset.depreciation.reverse'))<button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#reverse-modal"><i class="bx bx-revision me-1" aria-hidden="true"></i>ยกเลิก</button>@endif
            <a class="btn btn-outline-dark" href="{{ route('asset.depreciations.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>รายการทั้งหมด</a>
        </div>
    </div>
    @if($run->status === 'APPROVED' && !($postReadiness['ready'] ?? false))<div class="alert alert-warning border-0 shadow-sm mb-4"><strong>ยังลงบัญชีไม่ได้</strong><ul class="mb-0 mt-2">@foreach($postReadiness['blockers'] as $blocker)<li>{{ $blocker }}</li>@endforeach</ul></div>@endif
    @if($run->status==='FAILED' && $run->error_message)<div class="alert alert-danger border-0 shadow-sm mb-4"><div class="fw-semibold">คำนวณไม่สำเร็จ</div><div class="small mt-1">{{ $run->error_message }}</div></div>@endif
    <div class="row g-3 mb-4"><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="small text-secondary mb-1">ค่าเสื่อมรวม</div><div class="fs-3 fw-semibold">{{ number_format((float) $run->total_depreciation, 2) }}</div><div class="small text-secondary mt-1">รวม catch-up {{ number_format((float) $run->total_catch_up_adjustment, 2) }}</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="small text-secondary mb-1">สินทรัพย์ในชุดคำนวณ</div><div class="fs-3 fw-semibold">{{ number_format($run->asset_count) }}</div><div class="small text-secondary mt-1">งวดบัญชี {{ $run->fiscalPeriod?->name ?? '-' }}</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="small text-secondary mb-1">Journal Entry</div><div class="fw-semibold">{{ $isBook ? ($run->journalEntry?->entry_number ?? 'รอลงบัญชี') : 'Tax book ไม่ลง GL' }}</div><div class="small text-secondary mt-1">{{ $run->posted_at?->format('d/m/Y H:i') ?? 'ยังไม่มีการ Post' }}</div></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-header bg-white border-0 d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2 py-3 px-3 px-lg-4"><div><h2 class="h5 mb-1">รายละเอียดการคำนวณ</h2><p class="small text-secondary mb-0">ตรวจสอบยอดก่อนและหลังคิดค่าเสื่อมรายสินทรัพย์</p></div><span class="badge app-status-neutral">{{ $run->lines->count() }} รายการ</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-3 ps-lg-4">สินทรัพย์</th><th>หมวด</th><th class="text-end text-nowrap">มูลค่าเปิดงวด</th><th class="text-end text-nowrap">ค่าเสื่อมงวดนี้</th><th class="text-end text-nowrap">Catch-up</th><th class="text-end text-nowrap pe-3 pe-lg-4">มูลค่าปิดงวด</th></tr></thead><tbody>@forelse($run->lines as $line)<tr><td class="ps-3 ps-lg-4"><a class="fw-semibold text-decoration-none" href="{{ route('asset.assets.show',$line->asset) }}">{{ $line->asset_number }}</a><div class="small text-secondary">{{ $line->asset?->name ?? '-' }}</div></td><td><span class="text-secondary">{{ $line->category_name ?: '-' }}</span></td><td class="text-end text-nowrap">{{ number_format((float) $line->opening_cost - (float) $line->opening_accumulated_depreciation - (float) $line->opening_accumulated_impairment,2) }}</td><td class="text-end text-nowrap fw-semibold">{{ number_format((float) $line->period_depreciation,2) }}</td><td class="text-end text-nowrap">{{ number_format((float) $line->catch_up_adjustment,2) }}</td><td class="text-end text-nowrap fw-semibold pe-3 pe-lg-4">{{ number_format((float) $line->closing_book_value,2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">ไม่พบรายการสินทรัพย์ในชุดคำนวณ</td></tr>@endforelse</tbody><tfoot class="table-light border-top"><tr><th colspan="2" class="text-end ps-3 ps-lg-4">รวมทั้งชุดคำนวณ</th><th class="text-end text-nowrap">{{ number_format($openingTotal,2) }}</th><th class="text-end text-nowrap">{{ number_format((float) $run->total_depreciation,2) }}</th><th class="text-end text-nowrap">{{ number_format((float) $run->total_catch_up_adjustment,2) }}</th><th class="text-end text-nowrap pe-3 pe-lg-4">{{ number_format($closingTotal,2) }}</th></tr></tfoot></table></div></div>
    @if($run->exceptions->isNotEmpty())<div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white border-0 py-3 px-3 px-lg-4"><h2 class="h5 mb-1">ข้อยกเว้นของงวดนี้</h2><p class="small text-secondary mb-0">สินทรัพย์เหล่านี้ไม่ได้ถูกคำนวณในชุดนี้</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-3 ps-lg-4">สินทรัพย์</th><th class="pe-3 pe-lg-4">เหตุผล</th></tr></thead><tbody>@foreach($run->exceptions as $exception)<tr><td class="ps-3 ps-lg-4"><div class="fw-semibold">{{ $exception->asset_number }}</div><div class="small text-secondary">{{ $exception->asset_name }}</div></td><td class="pe-3 pe-lg-4">{{ $exception->reason }}</td></tr>@endforeach</tbody></table></div></div>@endif
    <div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white border-0 py-3 px-3 px-lg-4"><h2 class="h5 mb-1">ประวัติการทำรายการ</h2><p class="small text-secondary mb-0">Audit Trail ของชุดค่าเสื่อมนี้ · เวลาไทย (UTC+7)</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-3 ps-lg-4">วันเวลา</th><th>เหตุการณ์</th><th>ผู้ดำเนินการ</th><th class="pe-3 pe-lg-4">หมายเหตุ</th></tr></thead><tbody>@forelse($auditTrail as [$action,$occurredAt,$actor,$note])<tr><td class="ps-3 ps-lg-4 text-nowrap">{{ $occurredAt->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</td><td class="fw-semibold">{{ $action }}</td><td>{{ $actor ?? '-' }}</td><td class="pe-3 pe-lg-4">{{ $note ?? '-' }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">ยังไม่มีประวัติการทำรายการ</td></tr>@endforelse</tbody></table></div></div>
</div>
@if($run->status==='POSTED')<div class="modal fade" id="reverse-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form class="modal-content" id="reverse-form" method="post" action="{{ route('asset.depreciations.reverse',$run) }}">@csrf<div class="modal-header"><h2 class="modal-title h5">ยกเลิกชุดค่าเสื่อม</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label" for="reversal_date">วันที่ยกเลิก <span class="text-danger">*</span></label><input class="form-control" id="reversal_date" type="date" name="reversal_date" value="{{ today()->toDateString() }}" required><div class="invalid-feedback" data-error-for="reversal_date"></div></div><div><label class="form-label" for="reversal_reason">เหตุผล <span class="text-danger">*</span></label><textarea class="form-control" id="reversal_reason" name="reversal_reason" minlength="10" maxlength="500" required></textarea><div class="invalid-feedback" data-error-for="reversal_reason"></div></div></div><div class="modal-footer"><button class="btn btn-outline-dark" type="button" data-bs-dismiss="modal">ปิด</button><button class="btn btn-danger" type="submit">ยืนยันยกเลิก</button></div></form></div></div>@endif
@if($run->status==='SUBMITTED')<div class="modal fade" id="cancel-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form class="modal-content" id="cancel-form" method="post" action="{{ route('asset.depreciations.cancel',$run) }}">@csrf<div class="modal-header"><h2 class="modal-title h5">ยกเลิกชุดค่าเสื่อม</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body"><p class="small text-secondary">ชุดนี้ยังไม่ลงบัญชี จึงยกเลิกได้โดยไม่กระทบ Journal หรือยอดสินทรัพย์</p><label class="form-label" for="cancellation_reason">เหตุผล <span class="text-danger">*</span></label><textarea class="form-control" id="cancellation_reason" name="cancellation_reason" minlength="10" maxlength="500" required></textarea><div class="invalid-feedback" data-error-for="cancellation_reason"></div></div><div class="modal-footer"><button class="btn btn-outline-dark" type="button" data-bs-dismiss="modal">ปิด</button><button class="btn btn-danger" type="submit">ยืนยันยกเลิก</button></div></form></div></div>@endif
@endsection

@push('scripts')
<script>
$(function(){
    $('.js-action').on('click',function(){var b=$(this);Swal.fire({icon:'warning',title:'ยืนยันการทำรายการ',text:b.data('confirm'),showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ยกเลิก'}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.ajax({url:b.data('url'),method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')||''}}).done(function(x){Swal.fire({icon:'success',title:x.msg}).then(function(){window.location=x.redirect||window.location.href;});}).fail(function(x){var r=x.responseJSON||{};Swal.fire({icon:'error',title:'ไม่สามารถดำเนินการได้',text:r.msg||r.message||'กรุณาลองใหม่'});}).always(function(){b.prop('disabled',false);});});});
    window.erpAjaxForm({form:'#reverse-form',redirect:true,reload:false});
    window.erpAjaxForm({form:'#cancel-form',redirect:true,reload:false});
});
</script>
@endpush
