@extends('Finance::layout')
@section('title', $settlement->document_number.' | Finance')
@section('content')
    @php($labels=['DRAFT'=>'ร่าง','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','VOID'=>'ยกเลิก'])
    @php($classes=['DRAFT'=>'app-status-neutral','APPROVED'=>'app-status-info','POSTED'=>'app-status-success','VOID'=>'app-status-danger'])
    <div class="container-fluid px-3 px-lg-4 py-4"><p class="eyebrow mb-2">FINANCE / SETTLEMENT</p><div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h3 mb-2">{{ $settlement->document_number }}</h1><div class="text-secondary">{{ $settlement->document_type === 'RECEIPT' ? 'รับเงิน' : 'จ่ายเงิน' }}</div></div><div class="d-flex flex-wrap gap-2"><span class="badge {{ $classes[$settlement->status] ?? 'app-status-neutral' }}">{{ $labels[$settlement->status] ?? $settlement->status }}</span>@if($settlement->journalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-app-soft" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $settlement->journalEntry) }}"><i class="bx bx-book-open me-1"></i>ดู GL</button>@endif @if($settlement->status === 'POSTED' && auth()->user()->hasPermission('finance.settlements.reverse'))<button class="btn btn-outline-danger js-settlement-reverse" type="button" data-url="{{ route('finance.settlements.reverse', $settlement) }}" data-document="{{ $settlement->document_number }}">ยกเลิกเอกสาร</button>@endif<a class="btn btn-outline-secondary" href="{{ route('finance.settlements.index') }}">ย้อนกลับ</a></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="row g-3"><div class="col-md-3"><div class="small text-secondary">วันที่เอกสาร</div>{{ $settlement->document_date?->format($dateFormat) ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">วันที่รับ/จ่ายจริง</div>{{ $settlement->settlement_date?->format($dateFormat) ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">คู่ค้า</div>{{ $settlement->party?->code ?? '—' }} · {{ $settlement->party?->name ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">บัญชีเงิน</div>{{ $settlement->bankAccount?->code ?? '—' }} · {{ $settlement->bankAccount?->name ?? '—' }}</div><div class="col-md-4"><div class="small text-secondary">ยอดรวม</div><strong>{{ number_format((float) $settlement->gross_amount, 2) }}</strong></div><div class="col-md-4"><div class="small text-secondary">หัก ณ ที่จ่าย</div>{{ number_format((float) $settlement->withholding_amount, 2) }}</div><div class="col-md-4"><div class="small text-secondary">ยอดสุทธิ</div><strong>{{ number_format((float) $settlement->net_amount, 2) }}</strong></div><div class="col-md-6"><div class="small text-secondary">Journal</div>{{ $settlement->journalEntry?->entry_number ?? '—' }}</div><div class="col-md-6"><div class="small text-secondary">รายละเอียด</div>{{ $settlement->description ?? '—' }}</div></div></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><h2 class="h5 mb-0">รายการจัดสรร</h2><div class="d-flex gap-4"><div class="text-end"><div class="small text-secondary">จัดสรรแล้ว</div><strong>{{ number_format((float) $allocatedAmount, 2) }}</strong></div>@if($settlement->document_type === 'RECEIPT')<div class="text-end"><div class="small text-secondary">รับล่วงหน้า/ยังไม่จัดสรร</div><strong>{{ number_format((float) $unappliedAmount, 2) }}</strong></div>@endif</div></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>เอกสาร</th><th class="text-end">จำนวนเงิน</th></tr></thead><tbody>@forelse($settlement->allocationIntents as $intent)<tr><td>{{ $intent->line_number }}</td><td>{{ $intent->openItem?->document_number ?? '—' }}</td><td class="text-end">{{ number_format((float) $intent->amount, 2) }}</td></tr>@empty<tr><td colspan="3" class="text-center text-secondary">ไม่มีรายการจัดสรร</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-1">ช่องทางรับ/จ่ายเงิน</h2><p class="text-secondary small mb-3">ยอดเงินจริงตามบัญชีเงินสด/ธนาคารที่บันทึกไว้</p><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>บัญชีเงินสด/ธนาคาร</th><th>เลขอ้างอิง</th><th class="text-end">จำนวนเงิน</th></tr></thead><tbody>@forelse($settlement->tenders as $tender)<tr><td>{{ $tender->bankAccount?->code ?: '—' }} · {{ $tender->bankAccount?->name ?: '—' }}</td><td>{{ $tender->reference ?: '—' }}</td><td class="text-end fw-semibold">{{ number_format((float) $tender->amount, 2) }}</td></tr>@empty<tr><td colspan="3" class="text-center text-secondary">ไม่มีรายละเอียดช่องทางรับ/จ่าย</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{ $event->created_at->format('d/m/Y H:i') }}</div><div><strong>{{ $event->action }}</strong><div class="small text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">รายละเอียด:</span> {{ $event->reason }}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติ</p>@endforelse</div></div>
    </div>
@endsection
@push('scripts')<script>$(function () { $(document).on('click', '.js-settlement-reverse', function () { const button = $(this); Swal.fire({ title: 'ยกเลิกเอกสาร ' + button.data('document'), html: '<input id="reverse-date" class="swal2-input" type="date" value="{{ today()->format('Y-m-d') }}"><textarea id="reverse-reason" class="swal2-textarea" placeholder="เหตุผลอย่างน้อย 10 ตัวอักษร"></textarea>', showCancelButton: true, confirmButtonText: 'ยกเลิกเอกสาร', cancelButtonText: 'ย้อนกลับ', preConfirm: () => { const reason = $.trim($('#reverse-reason').val() || ''), date = $('#reverse-date').val(); if (!date || reason.length < 10) { Swal.showValidationMessage('กรุณาระบุวันที่และเหตุผลอย่างน้อย 10 ตัวอักษร'); return false; } return { reversal_date: date, reason: reason }; } }).then(result => { if (!result.isConfirmed) return; $.ajax({ url: button.data('url'), method: 'PUT', data: result.value, headers: { Accept: 'application/json', 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') } }).done(response => Swal.fire({ icon: 'success', text: response.msg }).then(() => location.reload())).fail(xhr => Swal.fire({ icon: 'error', text: xhr.responseJSON?.message || 'ไม่สามารถยกเลิกเอกสารได้' })); }); }); });</script>@endpush
