@extends('Crm::layout')
@section('title','ตรวจสอบลูกค้าซ้ำ | CRM')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page module-dashboard module-dashboard--crm">
    <div class="module-dashboard-hero d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4 crm-page-header"><div><p class="module-dashboard-kicker mb-2"><span></span>CRM / DATA QUALITY</p><h1>ตรวจสอบลูกค้าซ้ำ</h1><p class="mb-0">รายการนี้เป็นคำเตือนเพื่อช่วยตรวจสอบ ยังไม่มีการรวม เปลี่ยนแปลง หรือลบข้อมูลอัตโนมัติ</p></div><a class="btn btn-outline-secondary" href="{{ route('crm.customers.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a></div>
    <div class="alert alert-info border-0"><strong>ระดับความมั่นใจ:</strong> Tax ID, เบอร์โทร และอีเมลตรงกันมีความมั่นใจสูง ส่วนชื่อเหมือนกันต้องตรวจสอบเพิ่มเติม</div>
    <div class="card crm-filter-card mb-4"><div class="card-body"><form class="row g-2" id="duplicate-filter"><div class="col-12 col-md-7"><label class="visually-hidden" for="duplicate-q">ค้นหา</label><div class="input-group"><span class="input-group-text bg-white"><i class="bx bx-search" aria-hidden="true"></i></span><input class="form-control" id="duplicate-q" name="q" value="{{ $search }}" maxlength="100" placeholder="ค้นหา Tax ID เบอร์โทร อีเมล หรือชื่อ"></div></div><div class="col-8 col-md-3"><label class="visually-hidden" for="duplicate-type">ประเภทข้อมูลซ้ำ</label><select class="form-select" id="duplicate-type" name="type"><option value="">ทุกประเภท</option><option value="TAX" @selected($type==='TAX')>Tax ID</option><option value="PHONE" @selected($type==='PHONE')>เบอร์โทร</option><option value="EMAIL" @selected($type==='EMAIL')>อีเมล</option><option value="NAME" @selected($type==='NAME')>ชื่อ</option></select></div><div class="col-4 col-md-2"><button class="btn btn-app-primary w-100" type="submit">ค้นหา</button></div></form></div></div>
    <div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">กลุ่มที่อาจซ้ำ</h2><span class="small text-secondary" id="duplicate-summary">กำลังโหลด...</span></div>
    <div class="row g-3" id="duplicate-list" aria-live="polite" aria-busy="true"><div class="col-12"><div class="card"><div class="card-body text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>กำลังตรวจสอบ...</div></div></div></div>
    <nav class="mt-4" id="duplicate-pagination" aria-label="หน้ารายการลูกค้าที่อาจซ้ำ"></nav>
</div>
@endsection
@push('scripts')
<script>
$(function(){const form=$('#duplicate-filter'),list=$('#duplicate-list'),pagination=$('#duplicate-pagination'),summary=$('#duplicate-summary'),indexUrl=@json(route('crm.customers.duplicates')),dataUrl=@json(route('crm.customers.duplicates.data')),dismissUrl=@json(route('crm.customers.duplicates.dismiss'));let request;function load(page,updateUrl){if(request)request.abort();const params=new URLSearchParams(new FormData(form[0]));if(page>1)params.set('page',page);list.attr('aria-busy','true').html('<div class="col-12"><div class="card"><div class="card-body text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2"></span>กำลังตรวจสอบ...</div></div></div></div>');pagination.empty();request=$.getJSON(dataUrl,params.toString()).done(function(data){list.html(data.html).attr('aria-busy','false');pagination.html(data.pagination);summary.text(data.total?'แสดง '+data.from+'–'+data.to+' จาก '+Number(data.total).toLocaleString('th-TH')+' กลุ่ม':'ไม่พบข้อมูลที่อาจซ้ำ');if(updateUrl)history.pushState({},'',indexUrl+(params.toString()?'?'+params.toString():''));}).fail(function(xhr,status){if(status==='abort')return;list.attr('aria-busy','false').html('<div class="col-12"><div class="alert alert-danger">ตรวจสอบข้อมูลไม่สำเร็จ <button class="btn btn-sm btn-outline-danger ms-2 js-retry" type="button">ลองใหม่</button></div></div>');});}form.on('submit',function(event){event.preventDefault();load(1,true);});pagination.on('click','a.page-link',function(event){event.preventDefault();load(Number(new URL(this.href).searchParams.get('page')||1),true);});list.on('click','.js-retry',()=>load(1,false)).on('click','.js-dismiss-duplicate',function(){const button=$(this);Swal.fire({icon:'question',title:'ยืนยันว่าไม่ใช่ข้อมูลซ้ำ?',text:'กลุ่มนี้จะไม่แสดงในการตรวจสอบจนกว่าสมาชิกในกลุ่มจะเปลี่ยน',showCancelButton:true,confirmButtonText:'ไม่ใช่ข้อมูลซ้ำ',cancelButtonText:'ยกเลิก'}).then(result=>{if(!result.isConfirmed)return;button.prop('disabled',true);$.post(dismissUrl,{_token:@json(csrf_token()),match_type:button.data('type'),match_key:button.data('key')}).done(()=>load(1,false)).fail(xhr=>{button.prop('disabled',false);Swal.fire({icon:'error',title:'บันทึกไม่สำเร็จ',text:xhr.responseJSON?.message||'กรุณาลองใหม่'});});});});window.addEventListener('popstate',()=>location.reload());load(Number(new URL(location.href).searchParams.get('page')||1),false);});
</script>
@endpush
