@extends('Crm::layout')
@section('title', 'Customer 360 | CRM')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page module-dashboard module-dashboard--crm">
    <div class="module-dashboard-hero d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4 crm-page-header"><div><p class="module-dashboard-kicker mb-2"><span></span>CRM / CUSTOMER 360</p><h1>ลูกค้า 360°</h1><p class="mb-0">ดูข้อมูลติดต่อ Pipeline กิจกรรม และเอกสารขายจากจุดเดียว</p></div><div class="d-flex flex-wrap gap-2">@if(auth()->user()->hasPermission('crm.opportunities.create'))<a class="btn btn-app-soft" href="{{ route('crm.opportunities.create') }}"><i class="bx bx-target-lock me-1" aria-hidden="true"></i>สร้างโอกาสการขาย</a>@endif @if(auth()->user()->hasPermission('crm.customers.create'))<a class="btn btn-app-primary" href="{{ route('crm.customers.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>สร้างลูกค้า</a>@endif</div></div>
    <div class="card crm-filter-card mb-4"><div class="card-body"><form class="d-flex flex-column flex-sm-row gap-2" id="customer-filter"><label class="visually-hidden" for="customer-q">ค้นหาลูกค้า</label><div class="input-group"><span class="input-group-text bg-white"><i class="bx bx-search" aria-hidden="true"></i></span><input class="form-control" id="customer-q" name="q" value="{{ $search }}" maxlength="100" placeholder="ค้นหารหัส ชื่อ ผู้ติดต่อ โทรศัพท์ หรืออีเมล"></div><label class="visually-hidden" for="customer-status">สถานะ</label><select class="form-select flex-sm-grow-0" id="customer-status" name="status" style="max-width:12rem"><option value="ACTIVE" @selected($status==='ACTIVE')>ใช้งาน</option><option value="INACTIVE" @selected($status==='INACTIVE')>ปิดใช้งาน</option></select><button class="btn btn-app-primary flex-shrink-0" type="submit">ค้นหา</button></form></div></div>
    <div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">รายชื่อลูกค้า</h2><span class="small text-secondary" id="customer-summary">กำลังโหลด...</span></div>
    <div class="row g-3" id="customer-list" aria-live="polite" aria-busy="true"><div class="col-12"><div class="card"><div class="card-body text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>กำลังโหลดลูกค้า...</div></div></div></div>
    <nav class="mt-4" id="customer-pagination" aria-label="หน้ารายชื่อลูกค้า"></nav>
</div>
@endsection
@push('scripts')
<script>
$(function(){const form=$('#customer-filter'),list=$('#customer-list'),pagination=$('#customer-pagination'),summary=$('#customer-summary'),indexUrl=@json(route('crm.customers.index')),dataUrl=@json(route('crm.customers.data'));let request;function load(page,updateUrl){if(request)request.abort();const params=new URLSearchParams(new FormData(form[0]));if(page>1)params.set('page',page);list.attr('aria-busy','true').html('<div class="col-12"><div class="card"><div class="card-body text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>กำลังโหลดลูกค้า...</div></div></div>');pagination.empty();request=$.getJSON(dataUrl,params.toString()).done(function(data){list.html(data.html).attr('aria-busy','false');pagination.html(data.pagination);summary.text(data.total?'แสดง '+data.from+'–'+data.to+' จาก '+Number(data.total).toLocaleString('th-TH')+' รายการ':'ไม่พบลูกค้า');if(updateUrl)history.pushState({},'',indexUrl+(params.toString()?'?'+params.toString():''));}).fail(function(xhr,status){if(status==='abort')return;list.attr('aria-busy','false').html('<div class="col-12"><div class="alert alert-danger">โหลดข้อมูลลูกค้าไม่สำเร็จ</div></div>');});}form.on('submit',function(event){event.preventDefault();load(1,true);});pagination.on('click','a.page-link',function(event){event.preventDefault();load(Number(new URL(this.href).searchParams.get('page')||1),true);});window.addEventListener('popstate',function(){location.reload();});load(Number(new URL(location.href).searchParams.get('page')||1),false);});
</script>
@endpush
