@extends('Crm::layout')
@section('title','รวมข้อมูลลูกค้า | CRM')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page module-dashboard module-dashboard--crm"><div class="module-dashboard-hero d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4 crm-page-header"><div><p class="module-dashboard-kicker mb-2"><span></span>CRM / DATA QUALITY</p><h1>ตรวจสอบก่อนรวมข้อมูลลูกค้า</h1><p class="mb-0">ข้อมูลจากลูกค้ารองจะย้ายเข้าลูกค้าหลัก และลูกค้ารองจะถูก Soft Delete</p></div><a class="btn btn-outline-secondary" href="{{ route('crm.customers.duplicates') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้าตรวจสอบ</a></div>
@if($blockers)<div class="alert alert-danger"><strong>ยังรวมไม่ได้</strong><ul class="mb-0 mt-2">@foreach($blockers as $blocker)<li>{{ $blocker }}</li>@endforeach</ul></div>@else<div class="alert alert-warning"><strong>ผลของการดำเนินการ:</strong> Contact, Opportunity, ที่อยู่ และกลุ่มลูกค้าจะย้ายเข้าลูกค้าหลัก การดำเนินการนี้ย้อนกลับอัตโนมัติไม่ได้</div>@endif
<div class="row g-3 mb-4"><div class="col-12 col-lg-6"><div class="card h-100"><div class="card-body"><span class="badge app-status-success mb-2">ลูกค้าหลัก — เก็บไว้</span><h2 class="h5">{{ $target->code }} · {{ $target->name }}</h2><dl class="row small mb-0"><dt class="col-4">Tax ID</dt><dd class="col-8">{{ $target->tax_id ?: '-' }} / {{ $target->branch_code }}</dd><dt class="col-4">โทรศัพท์</dt><dd class="col-8">{{ $target->phone ?: '-' }}</dd><dt class="col-4">อีเมล</dt><dd class="col-8 text-break">{{ $target->email ?: '-' }}</dd></dl></div></div></div><div class="col-12 col-lg-6"><div class="card h-100"><div class="card-body"><span class="badge app-status-danger mb-2">ลูกค้ารอง — Soft Delete</span><h2 class="h5">{{ $source->code }} · {{ $source->name }}</h2><dl class="row small mb-0"><dt class="col-4">Tax ID</dt><dd class="col-8">{{ $source->tax_id ?: '-' }} / {{ $source->branch_code }}</dd><dt class="col-4">โทรศัพท์</dt><dd class="col-8">{{ $source->phone ?: '-' }}</dd><dt class="col-4">อีเมล</dt><dd class="col-8 text-break">{{ $source->email ?: '-' }}</dd></dl></div></div></div></div>
<div class="card mb-4"><div class="card-header"><h2 class="h6 mb-0">ข้อมูลที่จะย้าย</h2></div><div class="card-body"><div class="row g-3 text-center">@foreach(['contacts'=>'ผู้ติดต่อ','opportunities'=>'Opportunity','addresses'=>'ที่อยู่','groups'=>'กลุ่มลูกค้า'] as $key=>$label)<div class="col-6 col-md-3"><div class="fs-4 fw-semibold">{{ number_format($counts[$key]) }}</div><div class="small text-secondary">{{ $label }}</div></div>@endforeach</div></div></div>
<div class="d-flex flex-wrap justify-content-end gap-2"><a class="btn btn-app-soft" href="{{ route('crm.customers.merge.preview',[$source,$target]) }}"><i class="bx bx-transfer-alt me-1" aria-hidden="true"></i>สลับลูกค้าหลัก</a>@unless($blockers)<button class="btn btn-app-danger" id="merge-customer" type="button"><i class="bx bx-git-merge me-1" aria-hidden="true"></i>รวมข้อมูลลูกค้า</button>@endunless</div></div>
@endsection
@push('scripts')
<script>$(function(){$('#merge-customer').on('click',function(){const button=$(this);Swal.fire({icon:'warning',title:'รวมข้อมูลลูกค้า?',text:'{{ $source->code }} จะถูก Soft Delete และข้อมูลจะย้ายเข้า {{ $target->code }}',showCancelButton:true,confirmButtonText:'รวมข้อมูลลูกค้า',cancelButtonText:'ยกเลิก'}).then(result=>{if(!result.isConfirmed)return;button.prop('disabled',true);$.post(@json(route('crm.customers.merge',[$target,$source])),{_token:@json(csrf_token())}).done(data=>location.href=data.redirect).fail(xhr=>{button.prop('disabled',false);Swal.fire({icon:'error',title:'รวมข้อมูลไม่สำเร็จ',text:xhr.responseJSON?.errors?.merge?.[0]||xhr.responseJSON?.message||'กรุณาลองใหม่'});});});});});</script>
@endpush
