@extends('Wms::layout')
@section('title','ใบสั่งซื้อ | Purchasing')
@section('content')
@php($moduleRoutePrefix=$moduleRoutePrefix??'wms')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex justify-content-between align-items-end mb-4"><div><p class="eyebrow mb-2">PURCHASING / PROCUREMENT</p><h1 class="h3 mb-2">ใบสั่งซื้อ (Purchase Order)</h1><p class="text-secondary mb-0">สร้างและติดตามคำสั่งซื้อก่อนรับสินค้า</p></div>@if(auth()->user()->hasPermission('wms.purchase-orders.create'))<a class="btn btn-dark" href="{{route($moduleRoutePrefix.'.purchase-orders.create')}}"><i class="bx bx-plus me-1"></i>สร้าง PO</a>@endif</div>
<div class="card border-0 shadow-sm"><div class="card-body"><div class="table-responsive"><table id="purchase-orders-table" class="table table-hover align-middle w-100" data-url="{{route($moduleRoutePrefix.'.purchase-orders.data')}}"><thead><tr><th>เลขที่</th><th>วันที่</th><th>Supplier</th><th>อ้างอิง PR</th><th>วันที่คาดรับ</th><th class="text-end">ยอดรวม</th><th>สถานะ</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div></div>
@endsection
@push('scripts')
<script>
$(function(){
    var t=$('#purchase-orders-table'),x=$.fn.dataTable.render.text();
    $('<div class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">วันที่เอกสาร ตั้งแต่</label><input id="po-filter-date-from" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">ถึง</label><input id="po-filter-date-to" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">Supplier</label><select id="po-filter-supplier" class="form-select" data-url="{{route($moduleRoutePrefix.'.purchase-documents.supplier-options')}}"></select></div><div class="col-md-3"><label class="form-label">สถานะ</label><select id="po-filter-status" class="form-select"><option value="">ทั้งหมด</option><option value="DRAFT">ร่าง</option><option value="APPROVED">อนุมัติแล้ว</option><option value="VOID">ยกเลิก</option></select></div><div class="col-md-3"><label class="form-label">คาดรับ ตั้งแต่</label><input id="po-filter-expected-from" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">คาดรับ ถึง</label><input id="po-filter-expected-to" type="date" class="form-control"></div><div class="col-md-3"><button id="po-filter-reset" type="button" class="btn btn-outline-secondary">ล้างตัวกรอง</button></div></div></div></div>').insertBefore(t.closest('.card'));
    window.erpInitSelect2('#po-filter-supplier',{placeholder:'ค้นหา Supplier',allowClear:true,ajax:{url:$('#po-filter-supplier').data('url'),delay:250,data:function(p){return{q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});
    var table=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.document_date_from=$('#po-filter-date-from').val();d.document_date_to=$('#po-filter-date-to').val();d.expected_date_from=$('#po-filter-expected-from').val();d.expected_date_to=$('#po-filter-expected-to').val();d.supplier_id=$('#po-filter-supplier').val();d.status=$('#po-filter-status').val();}},order:[[1,'desc']],buttons:[window.erpExcelButton(t)],columns:[
        {data:'document_number',render:function(v,type,r){return type==='display'?'<a href="'+x.display(r.show_url)+'">'+x.display(v)+'</a>':v;}},
        {data:'document_date_label',render:x.display},{data:'supplier_label',render:x.display},
        {data:'purchase_requisition_label',render:function(v,type,r){return type==='display'&&r.purchase_requisition_url?'<a href="'+x.display(r.purchase_requisition_url)+'">'+x.display(v)+'</a>':x.display(v);}},
        {data:'expected_date_label',render:x.display},{data:'total_amount',className:'text-end',render:$.fn.dataTable.render.number(',','.',2)},
        {data:'status_label',render:function(v,type,r){if(type!=='display')return r.status;var c={DRAFT:'app-status-neutral',APPROVED:'app-status-success',VOID:'app-status-danger'};return '<span class="badge '+c[r.status]+'">'+x.display(v)+'</span>'; }},
        {data:null,orderable:false,searchable:false,className:'text-end text-nowrap',render:function(v,type,r){if(type!=='display')return '';var a=['<a class="btn btn-sm btn-outline-dark" title="ดูรายละเอียด" aria-label="ดูรายละเอียด" href="'+x.display(r.show_url)+'"><i class="bx bx-show"></i></a>'];if(r.approve_url)a.push('<button class="btn btn-sm btn-app-soft js-po-action" title="อนุมัติ" aria-label="อนุมัติ" data-url="'+x.display(r.approve_url)+'"><i class="bx bx-check"></i></button>');if(r.void_url)a.push('<button class="btn btn-sm btn-outline-danger js-po-void" title="ยกเลิก" aria-label="ยกเลิก" data-url="'+x.display(r.void_url)+'"><i class="bx bx-x"></i></button>');if(r.delete_url)a.push('<button class="btn btn-sm btn-outline-danger js-po-delete" title="ลบเอกสาร" aria-label="ลบเอกสาร" data-url="'+x.display(r.delete_url)+'"><i class="bx bx-trash"></i></button>');return a.join(' ');}}
    ]}));
    $(document).on('click','.js-po-action',function(){var b=$(this);if(b.data('busy'))return;b.data('busy',1).prop('disabled',1);Swal.fire({icon:'warning',title:'อนุมัติใบสั่งซื้อ?',showCancelButton:true,confirmButtonText:'อนุมัติ',cancelButtonText:'ยกเลิก'}).then(function(r){if(!r.isConfirmed){b.data('busy',0).prop('disabled',0);return;}$.post(b.data('url'),{_token:$('meta[name=csrf-token]').attr('content')}).done(function(v){Swal.fire({icon:'success',text:v.msg});table.ajax.reload(null,false);}).fail(function(q){Swal.fire({icon:'error',text:(q.responseJSON||{}).message||'ดำเนินการไม่สำเร็จ'});}).always(function(){b.data('busy',0).prop('disabled',0);});});});
    $(document).on('click','.js-po-void',function(){var b=$(this);Swal.fire({icon:'warning',title:'ยกเลิก PO',input:'textarea',inputLabel:'เหตุผลอย่างน้อย 10 ตัวอักษร',showCancelButton:true,confirmButtonText:'ยกเลิกเอกสาร',cancelButtonText:'กลับ',preConfirm:function(v){if($.trim(v||'').length<10){Swal.showValidationMessage('กรุณาระบุเหตุผล');return false;}return v;}}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',1);$.post(b.data('url'),{_token:$('meta[name=csrf-token]').attr('content'),reason:r.value}).done(function(v){Swal.fire({icon:'success',text:v.msg});table.ajax.reload(null,false);}).fail(function(q){Swal.fire({icon:'error',text:(q.responseJSON||{}).message||'ดำเนินการไม่สำเร็จ'});}).always(function(){b.prop('disabled',0);});});});
    $(document).on('click','.js-po-delete',function(){var b=$(this);Swal.fire({icon:'warning',title:'ลบ PO?',text:'ลบได้เฉพาะ PO ที่ยังเป็นร่าง',showCancelButton:true,confirmButtonText:'ลบเอกสาร',cancelButtonText:'ยกเลิก'}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',1);$.ajax({url:b.data('url'),method:'DELETE',data:{_token:$('meta[name=csrf-token]').attr('content')}}).done(function(v){Swal.fire({icon:'success',text:v.msg});table.ajax.reload(null,false);}).fail(function(q){Swal.fire({icon:'error',text:(q.responseJSON||{}).message||'ลบเอกสารไม่สำเร็จ'});}).always(function(){b.prop('disabled',0);});});});
    $('#po-filter-date-from,#po-filter-date-to,#po-filter-expected-from,#po-filter-expected-to,#po-filter-status').on('change',function(){table.ajax.reload();});
    $('#po-filter-supplier').on('change',function(){table.ajax.reload();});
    $('#po-filter-reset').on('click',function(){$('#po-filter-date-from,#po-filter-date-to,#po-filter-expected-from,#po-filter-expected-to,#po-filter-status').val('');$('#po-filter-supplier').val(null).trigger('change');table.ajax.reload();});
});
    table.on('draw',function(){table.rows({page:'current'}).every(function(){var r=this.data(),$cell=$(this.node()).find('td:last');if(r.print_url&&!$cell.find('.js-pdf-print').length)$cell.prepend('<a class="btn btn-sm btn-app-soft js-pdf-print" target="_blank" title="พิมพ์ PDF" aria-label="พิมพ์ PDF" href="'+x.display(r.print_url)+'"><i class="bx bx-printer"></i></a> ');});});
</script>
@endpush
