@extends('Pos::layout')

@section('title', ($document->exists ? 'แก้ไข' : 'เพิ่ม').'เอกสารขาย | POS / Sales')

@section('content')
@php
    $isCredit = $document->document_type === 'CREDIT_NOTE';
    $rows = old('lines', $document->exists ? $document->lines->map->only(['description','quantity','unit','unit_price','discount_amount','revenue_account_id','tax_code_id','item_id','uom_id','stock_uom_id','uom_factor','conversion_snapshot','price_snapshot'])->all() : [['description'=>'','quantity'=>'1.0000','unit'=>'งาน','unit_price'=>'0.0000','discount_amount'=>'0.00','revenue_account_id'=>null,'tax_code_id'=>$taxCodes->firstWhere('kind','NONE_VAT')?->id,'item_id'=>null,'uom_id'=>null,'stock_uom_id'=>null,'uom_factor'=>null,'conversion_snapshot'=>null,'price_snapshot'=>null]]);
@endphp
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">POS / SALES</p><h1 class="h3 mb-4">{{ $document->exists ? 'แก้ไข' : 'เพิ่ม' }} {{ $isCredit ? 'ใบลดหนี้' : 'ใบแจ้งหนี้' }}</h1>
    @if($source)<div class="alert alert-info">อ้างอิง Invoice {{ $source->document_number }} · {{ $source->party_code }} {{ $source->party_name }}</div>@endif
    <form id="sales-document-form" method="POST" action="{{ $document->exists ? route('pos.sales-documents.update', $document) : route('pos.sales-documents.store') }}">
        @csrf @if($document->exists) @method('PUT') @endif
        <input type="hidden" name="document_type" value="{{ $document->document_type }}"><input type="hidden" name="source_invoice_id" value="{{ $document->source_invoice_id }}"><input type="hidden" name="price_includes_vat" value="0">
        <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3">
            <div class="col-md-6"><label class="form-label">ลูกค้า</label><select class="form-select" id="party-id" name="party_id" required @disabled($isCredit)><option value="{{ old('party_id',$document->party_id) }}">{{ $selectedParty ? $selectedParty->code.' · '.$selectedParty->name : '' }}</option></select>@if($isCredit)<input type="hidden" name="party_id" value="{{ $document->party_id }}">@endif<div class="invalid-feedback" data-error-for="party_id"></div></div>
            <div class="col-md-3"><label class="form-label">วันที่เอกสาร</label><input class="form-control" type="date" name="document_date" value="{{ old('document_date', optional($document->document_date)->format('Y-m-d')) }}" required><div class="invalid-feedback" data-error-for="document_date"></div></div>
            @unless($isCredit)<div class="col-md-3"><label class="form-label">วันครบกำหนด</label><div class="form-control bg-light text-secondary">คำนวณจากเงื่อนไขชำระเงิน</div></div>@endunless
            <div class="col-md-6"><label class="form-label">เงื่อนไขชำระเงิน</label><select class="form-select" name="payment_term_id" @required(!$isCredit)><option value="">ไม่กำหนด</option>@foreach($paymentTerms as $term)<option value="{{ $term->id }}" @selected((string)old('payment_term_id',$document->payment_term_id)===(string)$term->id)>{{ $term->code }} · {{ $term->name }}</option>@endforeach</select><div class="invalid-feedback" data-error-for="payment_term_id"></div></div>
            <div class="col-md-4"><label class="form-label">ภาษีหัก ณ ที่จ่าย</label><select class="form-select" id="sales-wht-code" name="withholding_tax_code_id" @disabled($isCredit)>@if($withholdingTaxCode)<option value="{{ $withholdingTaxCode->id }}" selected>{{ $withholdingTaxCode->code }} · {{ $withholdingTaxCode->name }} ({{ $withholdingTaxCode->rate }}%)</option>@endif</select><div class="invalid-feedback" data-error-for="withholding_tax_code_id"></div></div>
            <div class="col-md-2"><label class="form-label">ฐานหัก ณ ที่จ่าย</label><input class="form-control" type="number" step="0.01" min="0" name="withholding_base" value="{{ old('withholding_base',$document->withholding_base ?? '0.00') }}" @disabled($isCredit)><div class="invalid-feedback" data-error-for="withholding_base"></div></div>
            <div class="col-md-6"><label class="form-label">หมายเหตุ</label><input class="form-control" name="description" maxlength="500" value="{{ old('description',$document->description) }}"></div>
        </div></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between mb-3"><div><h2 class="h5 mb-1">รายการขาย</h2><small class="text-secondary">เลือกสินค้าเพื่อเก็บหน่วยและ Conversion snapshot; Invoice ใหม่ใช้ราคาและส่วนลดจาก Price List ที่ตรงเงื่อนไขเมื่อบันทึก</small></div><button class="btn btn-sm btn-outline-dark" id="add-line" type="button">เพิ่มรายการ</button></div>
            <div class="table-responsive"><table class="table align-middle" style="min-width:1250px"><thead><tr><th style="min-width:220px">สินค้า / รายละเอียด</th><th style="width:110px">จำนวน</th><th style="width:150px">หน่วย</th><th style="width:140px">ราคา/หน่วย</th><th style="width:130px">ส่วนลด</th><th style="min-width:210px">บัญชีรายได้</th><th style="min-width:150px">ภาษี</th><th></th></tr></thead><tbody id="line-rows">
            @foreach($rows as $i=>$line)<tr class="line-row"><td><select class="form-select item-select" name="lines[{{ $i }}][item_id]" data-field="item_id"><option value="">บริการ / ไม่ระบุสินค้า</option>@if($item=$selectedItems->get($line['item_id'] ?? null))<option value="{{ $item->id }}" selected>{{ $item->code }} · {{ $item->name }}</option>@endif</select><input class="form-control mt-1" name="lines[{{ $i }}][description]" data-field="description" maxlength="500" value="{{ $line['description'] ?? '' }}" placeholder="รายละเอียด" required><input type="hidden" data-field="stock_uom_id" value="{{ $line['stock_uom_id'] ?? '' }}"><input type="hidden" data-field="uom_factor" value="{{ $line['uom_factor'] ?? '' }}"><input type="hidden" data-field="conversion_snapshot" value='@json($line['conversion_snapshot'] ?? null)'></td><td><input class="form-control text-end" name="lines[{{ $i }}][quantity]" data-field="quantity" type="number" min="0.0001" step="0.0001" value="{{ $line['quantity'] ?? '1.0000' }}" required></td><td><select class="form-select uom-select" name="lines[{{ $i }}][uom_id]" data-field="uom_id"><option value="">บริการ</option>@if($uom=$selectedUoms->get($line['uom_id'] ?? null))<option value="{{ $uom->id }}" selected>{{ $uom->code }} · {{ $uom->name }}</option>@endif</select><input class="form-control mt-1" name="lines[{{ $i }}][unit]" data-field="unit" maxlength="30" value="{{ $line['unit'] ?? 'งาน' }}" required></td><td><input class="form-control text-end" name="lines[{{ $i }}][unit_price]" data-field="unit_price" type="number" min="0" step="0.0001" value="{{ $line['unit_price'] ?? '0.0000' }}" required></td><td><input class="form-control text-end" name="lines[{{ $i }}][discount_amount]" data-field="discount_amount" type="number" min="0" step="0.01" value="{{ $line['discount_amount'] ?? '0.00' }}" required></td><td><select class="form-select account-select" name="lines[{{ $i }}][revenue_account_id]" data-field="revenue_account_id" required>@if($account=$selectedAccounts->get($line['revenue_account_id'] ?? null))<option value="{{ $account->id }}" selected>{{ $account->code }} · {{ $account->name }}</option>@endif</select></td><td><select class="form-select tax-select" name="lines[{{ $i }}][tax_code_id]" data-field="tax_code_id" required>@foreach($taxCodes as $tax)<option value="{{ $tax->id }}" @selected((string)($line['tax_code_id']??'')===(string)$tax->id)>{{ $tax->code }} · {{ $tax->name }}</option>@endforeach</select></td><td><button class="btn btn-sm btn-outline-danger remove-line" type="button" title="ลบรายการ">ลบ</button></td></tr>@endforeach
            </tbody></table></div>
            <div class="invalid-feedback d-block" data-error-for="lines"></div><div class="mt-3"><button class="btn btn-dark" type="submit">บันทึกร่าง</button> <a class="btn btn-outline-secondary" href="{{ route('pos.sales-documents.index') }}">ยกเลิก</a></div>
        </div></div>
    </form>
</div>

<template id="line-template"><tr class="line-row"><td><select class="form-select item-select" data-field="item_id"><option value="">บริการ / ไม่ระบุสินค้า</option></select><input class="form-control mt-1" data-field="description" maxlength="500" placeholder="รายละเอียด" required><input type="hidden" data-field="stock_uom_id"><input type="hidden" data-field="uom_factor"><input type="hidden" data-field="conversion_snapshot"></td><td><input class="form-control text-end" data-field="quantity" type="number" min="0.0001" step="0.0001" value="1.0000" required></td><td><select class="form-select uom-select" data-field="uom_id"><option value="">บริการ</option></select><input class="form-control mt-1" data-field="unit" maxlength="30" value="งาน" required></td><td><input class="form-control text-end" data-field="unit_price" type="number" min="0" step="0.0001" value="0.0000" required></td><td><input class="form-control text-end" data-field="discount_amount" type="number" min="0" step="0.01" value="0.00" required></td><td><select class="form-select account-select" data-field="revenue_account_id" required></select></td><td><select class="form-select tax-select" data-field="tax_code_id" required>@foreach($taxCodes as $tax)<option value="{{ $tax->id }}">{{ $tax->code }} · {{ $tax->name }}</option>@endforeach</select></td><td><button class="btn btn-sm btn-outline-danger remove-line" type="button" title="ลบรายการ">ลบ</button></td></tr></template>
@endsection

@push('scripts')
<script>
$(function(){
    var accountUrl=@json(route('pos.sales-documents.revenue-account-options')), partyUrl=@json(route('pos.sales-documents.party-options')), taxCodeUrl=@json(route('pos.sales-documents.tax-code-options')), whtUrl=@json(route('pos.sales-documents.withholding-tax-code-options')), itemUrl=@json(route('pos.sales-documents.item-options')), uomUrl=@json(route('pos.sales-documents.uom-options')), priceUrl=@json(route('pos.sales-documents.price-preview')), businessDate=$('[name="document_date"]').val(), isInvoice=@json(! $isCredit);
    function accounts(scope){$(scope).find('.account-select').each(function(){if($(this).hasClass('select2-hidden-accessible'))return; $(this).select2({theme:'bootstrap-5',width:'100%',ajax:{url:accountUrl,dataType:'json',delay:250,data:function(p){return {q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});});}
    function taxes(scope){$(scope).find('.tax-select').each(function(){if($(this).hasClass('select2-hidden-accessible'))return; $(this).select2({theme:'bootstrap-5',width:'100%',ajax:{url:taxCodeUrl,dataType:'json',delay:250,data:function(p){return {q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});});}
    function setSnapshot(row,itemId,uomId,stockUomId,factor){row.find('[data-field="stock_uom_id"]').val(stockUomId||'');row.find('[data-field="uom_factor"]').val(factor||'');row.find('[data-field="conversion_snapshot"]').val(itemId&&uomId&&factor?JSON.stringify({purchase_uom_id:Number(uomId),stock_uom_id:Number(stockUomId),factor:String(factor),business_date:businessDate}):'');}
    function previewPrice(row){var itemId=row.find('.item-select').val(),uomId=row.find('.uom-select').val(),partyId=$('#party-id').val(),quantity=row.find('[data-field="quantity"]').val();if(!isInvoice||row.data('price-manual')||!itemId||!uomId||!partyId||!quantity)return;$.getJSON(priceUrl,{item_id:itemId,uom_id:uomId,party_id:partyId,quantity:quantity,document_date:$('[name="document_date"]').val()}).done(function(data){if(data.price_snapshot&&!row.data('price-manual')){row.find('[data-field="unit_price"]').val(data.unit_price);row.find('[data-field="discount_amount"]').val(data.discount_amount);}});}
    function loadUoms(row,itemId){var uom=row.find('.uom-select'),selected=String(uom.val()||'');uom.empty().append(new Option('บริการ',''));setSnapshot(row,itemId,'','','');if(!itemId)return;$.getJSON(uomUrl,{item_id:itemId,business_date:businessDate}).done(function(data){(data.results||[]).forEach(function(option){var el=new Option(option.text,option.id,false,String(option.id)===selected);$(el).attr('data-factor',option.factor||'1').attr('data-stock-uom-id',option.stock_uom_id||'');uom.append(el);});uom.trigger('change');});}
    function items(scope){$(scope).find('.item-select').each(function(){if($(this).hasClass('select2-hidden-accessible'))return;$(this).select2({theme:'bootstrap-5',width:'100%',ajax:{url:itemUrl,dataType:'json',delay:250,data:function(p){return {q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}}).on('change.sales',function(){var row=$(this).closest('.line-row');row.data('price-manual',false);row.find('.uom-select').val(null).trigger('change');loadUoms(row,$(this).val());});});}
    function uoms(scope){$(scope).find('.uom-select').each(function(){if($(this).hasClass('select2-hidden-accessible'))return;$(this).select2({theme:'bootstrap-5',width:'100%'}).on('change.sales',function(){var row=$(this).closest('.line-row'),selected=$(this).find(':selected'),itemId=row.find('.item-select').val(),uomId=$(this).val(),factor=selected.data('factor')||'';setSnapshot(row,itemId,uomId,selected.data('stock-uom-id')||'',factor);previewPrice(row);});});}
    function names(){ $('#line-rows .line-row').each(function(i){$(this).find('[data-field]').each(function(){this.name='lines['+i+']['+$(this).data('field')+']';});}); }
    $('#party-id').select2({theme:'bootstrap-5',width:'100%',ajax:{url:partyUrl,dataType:'json',delay:250,data:function(p){return {q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});
    $('#sales-wht-code').select2({theme:'bootstrap-5',width:'100%',allowClear:true,placeholder:'ไม่หัก ณ ที่จ่าย',ajax:{url:whtUrl,dataType:'json',delay:250,data:function(p){return {q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}}); accounts(document); taxes(document); items(document); uoms(document); names(); $('#line-rows .line-row').each(function(){var item=$(this).find('.item-select').val();if(item)loadUoms($(this),item);});
    $('#add-line').on('click',function(){var row=$($('#line-template').html()); $('#line-rows').append(row); names(); accounts(row); taxes(row); items(row); uoms(row);});
    $(document).on('click','.remove-line',function(){if($('.line-row').length===1)return; $(this).closest('tr').remove(); names();});
    $('#line-rows').on('input','[data-field="unit_price"],[data-field="discount_amount"]',function(){$(this).closest('.line-row').data('price-manual',true);}).on('input','[data-field="quantity"]',function(){previewPrice($(this).closest('.line-row'));});
    $('#party-id,[name="document_date"]').on('change.sales',function(){$('#line-rows .line-row').each(function(){$(this).data('price-manual',false);previewPrice($(this));});});
    window.erpAjaxForm({form:'#sales-document-form',redirect:true});
});
</script>
@endpush
