@extends('Pos::layout')

@section('title', $salesDocument->document_number.' | POS / Sales')

@section('content')
@php
    $statusMap=['DRAFT'=>['secondary','ร่าง'],'APPROVED'=>['primary','อนุมัติแล้ว'],'POSTED'=>['success','ลงบัญชีแล้ว'],'VOID'=>['danger','ยกเลิก']];
    [$statusColor,$statusLabel]=$statusMap[$salesDocument->status] ?? ['secondary',$salesDocument->status];
    $paymentMap=['UNPAID'=>['warning','ยังไม่ชำระ'],'PARTIAL'=>['info','ชำระบางส่วน'],'PAID'=>['success','ชำระครบ']];
@endphp
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex justify-content-between align-items-start mb-4"><div><p class="eyebrow mb-2">POS / SALES</p><h1 class="h3 mb-2">{{ $salesDocument->document_number }}</h1><span class="badge bg-{{ $statusColor }}-subtle text-{{ $statusColor }}-emphasis">{{ $statusLabel }}</span></div><div class="d-flex gap-2">
        @if($salesDocument->status==='DRAFT' && auth()->user()->hasPermission('pos.sales-documents.update'))<a class="btn btn-outline-dark" href="{{ route('pos.sales-documents.edit',$salesDocument) }}">แก้ไข</a>@endif
        @if($salesDocument->status==='DRAFT' && auth()->user()->hasPermission('pos.sales-documents.approve'))<button class="btn btn-primary js-approve" data-url="{{ route('pos.sales-documents.approve',$salesDocument) }}">อนุมัติ</button>@endif
        @if($salesDocument->status==='APPROVED' && auth()->user()->hasPermission('pos.sales-documents.post'))<button class="btn btn-success js-post" data-url="{{ route('pos.sales-documents.post',$salesDocument) }}">Post</button>@endif
        @if(in_array($salesDocument->status,['DRAFT','APPROVED'],true) && auth()->user()->hasPermission('pos.sales-documents.void'))<button class="btn btn-outline-danger js-void" data-url="{{ route('pos.sales-documents.void',$salesDocument) }}">ยกเลิก</button>@endif
        @if($salesDocument->document_type==='INVOICE' && $salesDocument->status==='POSTED' && auth()->user()->hasPermission('pos.sales-documents.create'))<a class="btn btn-outline-primary" href="{{ route('pos.sales-documents.create',['documentType'=>'CREDIT_NOTE','source_invoice_id'=>$salesDocument->id]) }}">สร้างใบลดหนี้</a>@endif
        @if($salesDocument->journal_entry_id && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-app-soft" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $salesDocument->journal_entry_id) }}"><i class="bx bx-book-open me-1"></i>ดู GL</button>@endif
    </div></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-3"><small class="text-secondary">ประเภท</small><div>{{ $salesDocument->document_type==='INVOICE'?'ใบแจ้งหนี้':'ใบลดหนี้' }}</div></div><div class="col-md-3"><small class="text-secondary">วันที่เอกสาร</small><div>{{ $salesDocument->document_date->format((string) app(\App\Modules\Settings\Services\GlobalSettings::class)->value('date_format')) }}</div></div><div class="col-md-3"><small class="text-secondary">ครบกำหนด</small><div>{{ $salesDocument->due_date?->format((string) app(\App\Modules\Settings\Services\GlobalSettings::class)->value('date_format')) ?? '—' }}</div></div><div class="col-md-3"><small class="text-secondary">Invoice ต้นทาง</small><div>{{ $salesDocument->sourceInvoice?->document_number ?? '—' }}</div></div><div class="col-md-3"><small class="text-secondary">วิธีคิดภาษี</small><div>{{ $salesDocument->tax_amount > 0 ? ($salesDocument->price_includes_vat ? 'ราคารวมภาษี' : 'ราคาไม่รวมภาษี') : 'ไม่คิดภาษี' }}</div></div><div class="col-md-3"><small class="text-secondary">อัตราภาษี</small><div>{{ $salesDocument->lines->pluck('tax_rate')->filter(fn ($rate) => (float) $rate > 0)->unique()->sort()->map(fn ($rate) => rtrim(rtrim(number_format((float) $rate, 4, '.', ''), '0'), '.').'%')->join(', ') ?: '—' }}</div></div><div class="col-md-6"><small class="text-secondary">ลูกค้า</small><div>{{ $salesDocument->party_code }} · {{ $salesDocument->party_name }}</div></div><div class="col-md-6"><small class="text-secondary">เลขผู้เสียภาษี / สาขา</small><div>{{ $salesDocument->party_tax_id ?: '—' }} / {{ $salesDocument->party_branch_code ?: '—' }}</div></div><div class="col-12"><small class="text-secondary">ที่อยู่</small><div class="text-pre-wrap">{{ $salesDocument->party_address ?: '—' }}</div></div></div></div></div>
    @if($payment)<div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-0">สถานะการรับชำระ</h2><small class="text-secondary">คำนวณจาก AR Open Item ณ วันนี้</small></div>@php($paymentMeta = $paymentMap[$payment['status']])<span class="badge bg-{{ $paymentMeta[0] }}-subtle text-{{ $paymentMeta[0] }}-emphasis">{{ $paymentMeta[1] }}</span></div><div class="row g-3"><div class="col-sm-4"><div class="text-secondary small">ยอดใบแจ้งหนี้</div><div class="fs-5 fw-semibold">{{ number_format((float) $payment['original'], 2) }}</div></div><div class="col-sm-4"><div class="text-secondary small">รับชำระแล้ว</div><div class="fs-5 fw-semibold">{{ number_format((float) $payment['paid'], 2) }}</div></div><div class="col-sm-4"><div class="text-secondary small">คงเหลือ</div><div class="fs-5 fw-semibold">{{ number_format((float) $payment['remaining'], 2) }}</div></div></div>@if($payment['status'] !== 'PAID' && $paymentOpenItem && auth()->user()->hasPermission('finance.settlements.create'))<div class="mt-3"><a class="btn btn-app-soft" href="{{ route('finance.settlements.create', ['open_item_id' => $paymentOpenItem->id]) }}">รับชำระ Invoice นี้</a></div>@endif</div></div>@endif
    @if($salesDocument->discount_approval_snapshot)<div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">หลักฐานส่วนลดตอนอนุมัติ</h2><div class="row g-3"><div class="col-sm-3"><div class="text-secondary small">ส่วนลดจาก Price List</div><div class="fw-semibold">{{ number_format((float) $salesDocument->discount_approval_snapshot['price_list_discount_amount'], 2) }}</div></div><div class="col-sm-3"><div class="text-secondary small">ส่วนลดนอก Price List</div><div class="fw-semibold">{{ number_format((float) $salesDocument->discount_approval_snapshot['manual_discount_amount'], 2) }}</div></div><div class="col-sm-3"><div class="text-secondary small">ส่วนลดนอก Price List</div><div class="fw-semibold">{{ $salesDocument->discount_approval_snapshot['manual_discount_percent'] }}%</div></div><div class="col-sm-3"><div class="text-secondary small">เพดานที่ใช้ตรวจ</div><div class="fw-semibold">{{ $salesDocument->discount_approval_snapshot['threshold_percent'] }}%</div></div></div>@if($salesDocument->approval_reason)<div class="mt-3"><span class="text-secondary small">เหตุผลอนุมัติ</span><div>{{ $salesDocument->approval_reason }}</div></div>@endif</div></div>@endif
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>รายละเอียด</th><th class="text-end">จำนวน</th><th>หน่วย</th><th class="text-end">ราคา/หน่วย</th><th class="text-end">ส่วนลด</th><th>บัญชีรายได้</th><th>ภาษี</th><th class="text-end">สุทธิ</th></tr></thead><tbody>@foreach($salesDocument->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->description }}</td><td class="text-end">{{ number_format((float)$line->quantity,4) }}</td><td>{{ $line->unit }}</td><td class="text-end">{{ number_format((float)$line->unit_price,4) }}</td><td class="text-end">{{ number_format((float)$line->discount_amount,2) }}</td><td>{{ $line->revenueAccount->code }} · {{ $line->revenueAccount->name }}</td><td>{{ $line->taxCode->code }}</td><td class="text-end">{{ number_format((float)$line->line_total,2) }}</td></tr>@endforeach</tbody><tfoot><tr><th colspan="8" class="text-end">ก่อนหักส่วนลด</th><th class="text-end">{{ number_format((float)$salesDocument->subtotal,2) }}</th></tr><tr><th colspan="8" class="text-end">ส่วนลด</th><th class="text-end">{{ number_format((float)$salesDocument->discount_amount,2) }}</th></tr><tr><th colspan="8" class="text-end">ภาษี</th><th class="text-end">{{ number_format((float)$salesDocument->tax_amount,2) }}</th></tr><tr><th colspan="8" class="text-end">ยอดสุทธิ</th><th class="text-end">{{ number_format((float)$salesDocument->total_amount,2) }}</th></tr></tfoot></table></div></div></div>
    <a class="btn btn-outline-secondary mt-3" href="{{ route('pos.sales-documents.index') }}">กลับรายการ</a>
</div>
@endsection

@push('scripts')
<script>$(function(){function submitState(button,reason){button.prop('disabled',true);$.post(button.data('url'),{reason:reason||''}).done(function(x){Swal.fire({icon:'success',text:x.msg}).then(function(){location.reload();});}).fail(function(x){button.prop('disabled',false);Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถดำเนินการได้'});});}$('.js-approve').on('click',function(){var b=$(this);Swal.fire({icon:'question',title:'อนุมัติเอกสาร',input:'textarea',inputLabel:'เหตุผลส่วนลด (เมื่อเกินเพดาน ต้องอย่างน้อย 10 ตัวอักษร)',showCancelButton:true,confirmButtonText:'อนุมัติ',cancelButtonText:'ยกเลิก'}).then(function(r){if(r.isConfirmed)submitState(b,r.value);});});$('.js-void').on('click',function(){var b=$(this);Swal.fire({icon:'warning',title:'ยกเลิกเอกสาร',input:'textarea',inputLabel:'เหตุผล (อย่างน้อย 10 ตัวอักษร)',showCancelButton:true,confirmButtonText:'ยืนยันยกเลิก',cancelButtonText:'ยกเลิก',preConfirm:function(v){if(!v||v.trim().length<10)Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร');return v;}}).then(function(r){if(r.isConfirmed)submitState(b,r.value);});});$('.js-post').on('click',function(){var b=$(this);Swal.fire({title:'Post เอกสาร',input:'date',inputLabel:'วันที่ Post',inputValue:@json(today()->format('Y-m-d')),showCancelButton:true,confirmButtonText:'Post',cancelButtonText:'ยกเลิก',preConfirm:function(v){if(!v)Swal.showValidationMessage('กรุณาระบุวันที่ Post');return v;}}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.post(b.data('url'),{posting_date:r.value}).done(function(x){Swal.fire({icon:'success',text:x.msg}).then(function(){location.reload();});}).fail(function(x){b.prop('disabled',false);Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถ Post ได้'});});});});});</script>
@endpush
