<?php

use App\Modules\Pos\Controllers\AdvanceDepositController;
use App\Modules\Pos\Controllers\BranchSalesTargetController;
use App\Modules\Pos\Controllers\CommissionPaymentBatchController;
use App\Modules\Pos\Controllers\CustomerController;
use App\Modules\Pos\Controllers\CustomerGroupController;
use App\Modules\Pos\Controllers\EmployeeSalesTargetController;
use App\Modules\Pos\Controllers\EntryController;
use App\Modules\Pos\Controllers\PhysicalSaleController;
use App\Modules\Pos\Controllers\PhysicalSaleReceiptController;
use App\Modules\Pos\Controllers\PriceListController;
use App\Modules\Pos\Controllers\PromotionController;
use App\Modules\Pos\Controllers\ReceiptController;
use App\Modules\Pos\Controllers\ReceivableController;
use App\Modules\Pos\Controllers\SalesCommissionController;
use App\Modules\Pos\Controllers\SalesCommissionPlanController;
use App\Modules\Pos\Controllers\SalesDocumentController;
use App\Modules\Pos\Controllers\SalesIntakeController;
use App\Modules\Pos\Controllers\SalesIntakePdfController;
use App\Modules\Pos\Controllers\SalesOrderController;
use App\Modules\Pos\Controllers\SalesOrderPdfController;
use App\Modules\Pos\Controllers\SalesQuotationController;
use App\Modules\Pos\Controllers\SalesQuotationPdfController;
use App\Modules\Pos\Controllers\SalesReportController;
use App\Modules\Pos\Controllers\SalesReturnController;
use App\Modules\Pos\Controllers\SalesRfqController;
use App\Modules\Pos\Controllers\SalesRfqPdfController;
use App\Modules\Pos\Controllers\WorkflowController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'program:pos', 'warehouse'])->prefix('pos')->name('pos.')->group(function () {
    Route::get('/', EntryController::class)->middleware('permission:pos.dashboard.view')->name('index');
    Route::get('/dashboard/data/{section}', [EntryController::class, 'data'])->middleware('permission:pos.dashboard.view')->name('dashboard.data');
    Route::get('/workflow', [WorkflowController::class, 'index'])->name('workflow.index');
    Route::get('/sales-intakes', [SalesIntakeController::class, 'index'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.index');
    Route::get('/sales-intakes/data', [SalesIntakeController::class, 'data'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.data');
    Route::get('/sales-intakes/party-options', [SalesIntakeController::class, 'partyOptions'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.party-options');
    Route::get('/sales-intakes/party-addresses', [SalesIntakeController::class, 'partyAddresses'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.party-addresses');
    Route::get('/sales-intakes/item-options', [SalesIntakeController::class, 'itemOptions'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.item-options');
    Route::get('/sales-intakes/item-defaults', [SalesIntakeController::class, 'itemDefaults'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.item-defaults');
    Route::get('/sales-intakes/promotion-options', [SalesIntakeController::class, 'promotionOptions'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.promotion-options');
    Route::get('/sales-intakes/uom-options', [SalesIntakeController::class, 'uomOptions'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.uom-options');
    Route::get('/sales-intakes/create', [SalesIntakeController::class, 'create'])->middleware('permission:pos.sales-intakes.create')->name('sales-intakes.create');
    Route::post('/sales-intakes', [SalesIntakeController::class, 'store'])->middleware('permission:pos.sales-intakes.create')->name('sales-intakes.store');
    Route::post('/sales-intakes/{salesIntake}/to-rfq', [SalesIntakeController::class, 'toRfq'])->middleware('permission:pos.sales-intakes.convert')->name('sales-intakes.to-rfq');
    Route::post('/sales-intakes/{salesIntake}/to-quotation', [SalesQuotationController::class, 'fromIntake'])->middleware('permission:pos.sales-quotations.create')->name('sales-quotations.from-intake');
    Route::post('/sales-intakes/{salesIntake}/to-order', [SalesOrderController::class, 'fromIntake'])->middleware('permission:pos.sales-orders.create')->name('sales-orders.from-intake');
    Route::get('/sales-intakes/{salesIntake}/edit', [SalesIntakeController::class, 'edit'])->middleware('permission:pos.sales-intakes.update')->name('sales-intakes.edit');
    Route::put('/sales-intakes/{salesIntake}', [SalesIntakeController::class, 'update'])->middleware('permission:pos.sales-intakes.update')->name('sales-intakes.update');
    Route::post('/sales-intakes/{salesIntake}/complete', [SalesIntakeController::class, 'complete'])->middleware('permission:pos.sales-intakes.complete')->name('sales-intakes.complete');
    Route::post('/sales-intakes/{salesIntake}/cancel', [SalesIntakeController::class, 'cancel'])->middleware('permission:pos.sales-intakes.cancel')->name('sales-intakes.cancel');
    Route::delete('/sales-intakes/{salesIntake}', [SalesIntakeController::class, 'destroy'])->middleware('permission:pos.sales-intakes.delete')->name('sales-intakes.destroy');
    Route::get('/sales-intakes/{salesIntake}/pdf', [SalesIntakePdfController::class, 'show'])->middleware('permission:pos.sales-intakes.print')->name('sales-intakes.pdf');
    Route::get('/sales-intakes/{salesIntake}', [SalesIntakeController::class, 'show'])->middleware('permission:pos.sales-intakes.view')->name('sales-intakes.show');
    Route::get('/sales-rfqs', [SalesRfqController::class, 'index'])->middleware('permission:pos.sales-rfqs.view')->name('sales-rfqs.index');
    Route::get('/sales-rfqs/data', [SalesRfqController::class, 'data'])->middleware('permission:pos.sales-rfqs.view')->name('sales-rfqs.data');
    Route::get('/sales-rfqs/party-options', [SalesRfqController::class, 'partyOptions'])->middleware('permission:pos.sales-rfqs.view')->name('sales-rfqs.party-options');
    Route::get('/sales-rfqs/item-options', [SalesRfqController::class, 'itemOptions'])->middleware('permission:pos.sales-rfqs.view')->name('sales-rfqs.item-options');
    Route::get('/sales-rfqs/uom-options', [SalesRfqController::class, 'uomOptions'])->middleware('permission:pos.sales-rfqs.view')->name('sales-rfqs.uom-options');
    Route::get('/sales-rfqs/{salesRfq}/review', [SalesRfqController::class, 'review'])->middleware('permission:pos.sales-rfqs.approve')->name('sales-rfqs.review');
    Route::post('/sales-rfqs/{salesRfq}/review', [SalesRfqController::class, 'decide'])->middleware('permission:pos.sales-rfqs.approve')->name('sales-rfqs.decide');
    Route::get('/sales-rfqs/{salesRfq}/pdf', [SalesRfqPdfController::class, 'show'])->middleware('permission:pos.sales-rfqs.print')->name('sales-rfqs.pdf');
    Route::post('/sales-rfqs/{salesRfq}/cancel', [SalesRfqController::class, 'cancel'])->middleware('permission:pos.sales-rfqs.cancel')->name('sales-rfqs.cancel');
    Route::post('/sales-rfqs/{salesRfq}/to-quotation', [SalesQuotationController::class, 'fromRfq'])->middleware('permission:pos.sales-quotations.create')->name('sales-quotations.from-rfq');
    Route::post('/sales-quotations/{salesQuotation}/to-order', [SalesOrderController::class, 'fromQuotation'])->middleware('permission:pos.sales-orders.create')->name('sales-orders.from-quotation');
    Route::post('/sales-rfqs/{salesRfq}/to-order', [SalesOrderController::class, 'fromRfq'])->middleware('permission:pos.sales-orders.create')->name('sales-orders.from-rfq');
    Route::post('/sales-orders/{salesOrder}/confirm', [SalesOrderController::class, 'confirm'])->middleware('permission:pos.sales-orders.confirm')->name('sales-orders.confirm');
    Route::post('/sales-orders/{salesOrder}/cancel', [SalesOrderController::class, 'cancel'])->middleware('permission:pos.sales-orders.cancel')->name('sales-orders.cancel');
    Route::get('/sales-quotations/{salesQuotation}/pdf', [SalesQuotationPdfController::class, 'show'])->middleware('permission:pos.sales-quotations.print')->name('sales-quotations.pdf');
    Route::get('/sales-orders/{salesOrder}/pdf', [SalesOrderPdfController::class, 'show'])->middleware('permission:pos.sales-orders.print')->name('sales-orders.pdf');
    Route::post('/sales-quotations/{salesQuotation}/send', [SalesQuotationController::class, 'send'])->middleware('permission:pos.sales-quotations.send')->name('sales-quotations.send');
    Route::post('/sales-quotations/{salesQuotation}/accept', [SalesQuotationController::class, 'accept'])->middleware('permission:pos.sales-quotations.accept')->name('sales-quotations.accept');
    Route::post('/sales-quotations/{salesQuotation}/reject', [SalesQuotationController::class, 'reject'])->middleware('permission:pos.sales-quotations.reject')->name('sales-quotations.reject');
    Route::post('/sales-quotations/{salesQuotation}/cancel', [SalesQuotationController::class, 'cancel'])->middleware('permission:pos.sales-quotations.cancel')->name('sales-quotations.cancel');
    Route::get('/sales-quotations/{salesQuotation}/edit', [SalesQuotationController::class, 'edit'])->middleware('permission:pos.sales-quotations.update')->name('sales-quotations.edit');
    Route::put('/sales-quotations/{salesQuotation}', [SalesQuotationController::class, 'update'])->middleware('permission:pos.sales-quotations.update')->name('sales-quotations.update');
    Route::get('/sales-rfqs/{salesRfq}', [SalesRfqController::class, 'show'])->middleware('permission:pos.sales-rfqs.view')->name('sales-rfqs.show');
    Route::get('/sales-quotations', [SalesQuotationController::class, 'index'])->middleware('permission:pos.sales-quotations.view')->name('sales-quotations.index');
    Route::get('/sales-quotations/data', [SalesQuotationController::class, 'data'])->middleware('permission:pos.sales-quotations.view')->name('sales-quotations.data');
    Route::get('/sales-orders', [SalesOrderController::class, 'index'])->middleware('permission:pos.sales-orders.view')->name('sales-orders.index');
    Route::get('/sales-orders/data', [SalesOrderController::class, 'data'])->middleware('permission:pos.sales-orders.view')->name('sales-orders.data');
    Route::get('/reports/daily-sales', [SalesReportController::class, 'index'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.daily.index');
    Route::get('/reports/daily-sales/data', [SalesReportController::class, 'dailyData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.daily.data');
    Route::get('/reports/daily-sales/tenders', [SalesReportController::class, 'dailyTenderData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.daily.tenders');
    Route::get('/reports/customer-sales', [SalesReportController::class, 'customerIndex'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.customer.index');
    Route::get('/reports/customer-sales/data', [SalesReportController::class, 'customerData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.customer.data');
    Route::get('/reports/customer-options', [SalesReportController::class, 'customerOptions'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.customer-options');
    Route::get('/reports/reconciliation', [SalesReportController::class, 'reconciliationIndex'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.reconciliation.index');
    Route::get('/reports/reconciliation/data', [SalesReportController::class, 'reconciliationData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.reconciliation.data');
    Route::get('/reports/item-sales', [SalesReportController::class, 'itemIndex'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.item.index');
    Route::get('/reports/item-sales/data', [SalesReportController::class, 'itemData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.item.data');
    Route::get('/reports/gross-profit', [SalesReportController::class, 'grossProfitIndex'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.gross-profit.index');
    Route::get('/reports/gross-profit/data', [SalesReportController::class, 'grossProfitData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.gross-profit.data');
    Route::get('/reports/sales-target-performance', [SalesReportController::class, 'salesTargetPerformanceIndex'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.sales-target-performance.index');
    Route::get('/reports/sales-target-performance/data', [SalesReportController::class, 'salesTargetPerformanceData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.sales-target-performance.data');
    Route::get('/reports/promotion-performance', [SalesReportController::class, 'promotionIndex'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.promotion.index');
    Route::get('/reports/promotion-performance/data', [SalesReportController::class, 'promotionData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.promotion.data');
    Route::get('/reports/campaign-roi', [SalesReportController::class, 'campaignRoiIndex'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.campaign-roi.index');
    Route::get('/reports/campaign-roi/data', [SalesReportController::class, 'campaignRoiData'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.campaign-roi.data');
    Route::get('/reports/promotion-options', [SalesReportController::class, 'promotionOptions'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.promotion-options');
    Route::get('/reports/item-options', [SalesReportController::class, 'itemOptions'])->middleware('permission:pos.sales-reports.view')->name('sales-reports.item-options');
    Route::get('/branch-sales-targets', [BranchSalesTargetController::class, 'index'])->middleware('permission:pos.branch-sales-targets.view')->name('branch-sales-targets.index');
    Route::get('/branch-sales-targets/data', [BranchSalesTargetController::class, 'data'])->middleware('permission:pos.branch-sales-targets.view')->name('branch-sales-targets.data');
    Route::get('/branch-sales-targets/create', [BranchSalesTargetController::class, 'create'])->middleware('permission:pos.branch-sales-targets.create')->name('branch-sales-targets.create');
    Route::post('/branch-sales-targets', [BranchSalesTargetController::class, 'store'])->middleware('permission:pos.branch-sales-targets.create')->name('branch-sales-targets.store');
    Route::get('/branch-sales-targets/{branchSalesTarget}/edit', [BranchSalesTargetController::class, 'edit'])->middleware('permission:pos.branch-sales-targets.update')->name('branch-sales-targets.edit');
    Route::put('/branch-sales-targets/{branchSalesTarget}', [BranchSalesTargetController::class, 'update'])->middleware('permission:pos.branch-sales-targets.update')->name('branch-sales-targets.update');
    Route::delete('/branch-sales-targets/{branchSalesTarget}', [BranchSalesTargetController::class, 'destroy'])->middleware('permission:pos.branch-sales-targets.delete')->name('branch-sales-targets.destroy');
    Route::get('/sales-commissions', [SalesCommissionController::class, 'index'])->middleware('permission:pos.sales-commissions.view')->name('sales-commissions.index');
    Route::get('/sales-commissions/data', [SalesCommissionController::class, 'data'])->middleware('permission:pos.sales-commissions.view')->name('sales-commissions.data');
    Route::get('/sales-commissions/recipient-options', [SalesCommissionController::class, 'recipientOptions'])->middleware('permission:pos.sales-commissions.view')->name('sales-commissions.recipient-options');
    Route::get('/sales-commissions/{commissionRecord}/history', [SalesCommissionController::class, 'history'])->middleware('permission:pos.sales-commissions.view')->name('sales-commissions.history');
    Route::put('/sales-commissions/{commissionRecord}/approve', [SalesCommissionController::class, 'approve'])->middleware('permission:pos.sales-commissions.approve')->name('sales-commissions.approve');
    Route::put('/sales-commissions/{commissionRecord}/reject', [SalesCommissionController::class, 'reject'])->middleware('permission:pos.sales-commissions.approve')->name('sales-commissions.reject');
    Route::put('/sales-commissions/{commissionRecord}/status', [SalesCommissionController::class, 'updateStatus'])->middleware('permission:pos.sales-commissions.approve')->name('sales-commissions.update-status');
    Route::get('/sales-commission-payment-batches/data', [CommissionPaymentBatchController::class, 'data'])->middleware('permission:pos.sales-commissions.view')->name('sales-commission-payment-batches.data');
    Route::get('/sales-commission-payment-batches/{commissionPaymentBatch}/history', [CommissionPaymentBatchController::class, 'history'])->middleware('permission:pos.sales-commissions.view')->name('sales-commission-payment-batches.history');
    Route::get('/sales-commission-payment-batches/create', [CommissionPaymentBatchController::class, 'create'])->middleware('permission:pos.sales-commissions.pay')->name('sales-commission-payment-batches.create');
    Route::post('/sales-commission-payment-batches', [CommissionPaymentBatchController::class, 'store'])->middleware('permission:pos.sales-commissions.pay')->name('sales-commission-payment-batches.store');
    Route::get('/sales-commission-payment-batches/{commissionPaymentBatch}', [CommissionPaymentBatchController::class, 'show'])->middleware('permission:pos.sales-commissions.view')->name('sales-commission-payment-batches.show');
    Route::post('/sales-commission-payment-batches/{commissionPaymentBatch}/submit', [CommissionPaymentBatchController::class, 'submit'])->middleware('permission:pos.sales-commissions.pay')->name('sales-commission-payment-batches.submit');
    Route::post('/sales-commission-payment-batches/{commissionPaymentBatch}/cancel', [CommissionPaymentBatchController::class, 'cancel'])->middleware('permission:pos.sales-commissions.pay')->name('sales-commission-payment-batches.cancel');
    Route::get('/sales-quotations/{salesQuotation}', [SalesQuotationController::class, 'show'])->middleware('permission:pos.sales-quotations.view')->name('sales-quotations.show');
    Route::get('/sales-orders/{salesOrder}', [SalesOrderController::class, 'show'])->middleware('permission:pos.sales-orders.view')->name('sales-orders.show');
    Route::get('/sales-documents', [SalesDocumentController::class, 'index'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.index');
    Route::get('/sales-documents/data', [SalesDocumentController::class, 'data'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.data');
    Route::get('/sales-documents/party-options', [SalesDocumentController::class, 'partyOptions'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.party-options');
    Route::get('/sales-documents/revenue-account-options', [SalesDocumentController::class, 'revenueAccountOptions'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.revenue-account-options');
    Route::get('/sales-documents/tax-code-options', [SalesDocumentController::class, 'taxCodeOptions'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.tax-code-options');
    Route::get('/sales-documents/withholding-tax-code-options', [SalesDocumentController::class, 'withholdingTaxCodeOptions'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.withholding-tax-code-options');
    Route::get('/sales-documents/item-options', [SalesDocumentController::class, 'itemOptions'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.item-options');
    Route::get('/sales-documents/uom-options', [SalesDocumentController::class, 'uomOptions'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.uom-options');
    Route::get('/sales-documents/price-preview', [SalesDocumentController::class, 'pricePreview'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.price-preview');
    Route::get('/sales-documents/create/{documentType?}', [SalesDocumentController::class, 'create'])->middleware('permission:pos.sales-documents.create')->name('sales-documents.create');
    Route::post('/sales-documents', [SalesDocumentController::class, 'store'])->middleware('permission:pos.sales-documents.create')->name('sales-documents.store');
    Route::get('/sales-documents/{salesDocument}', [SalesDocumentController::class, 'show'])->middleware('permission:pos.sales-documents.view')->name('sales-documents.show');
    Route::get('/physical-sales', [PhysicalSaleController::class, 'index'])->middleware('permission:pos.physical-sales.view')->name('physical-sales.index');
    Route::get('/physical-sales/data', [PhysicalSaleController::class, 'data'])->middleware('permission:pos.physical-sales.view')->name('physical-sales.data');
    Route::get('/physical-sales/create', [PhysicalSaleController::class, 'create'])->middleware('permission:pos.physical-sales.create')->name('physical-sales.create');
    Route::post('/physical-sales', [PhysicalSaleController::class, 'store'])->middleware('permission:pos.physical-sales.create')->name('physical-sales.store');
    Route::post('/physical-sales/{physicalSale}/post', [PhysicalSaleController::class, 'post'])->middleware('permission:pos.physical-sales.post')->name('physical-sales.post');
    Route::get('/physical-sales/{physicalSale}/eligible-advance-deposits', [AdvanceDepositController::class, 'eligibleForPhysicalSale'])->middleware('permission:pos.physical-sales.post')->name('physical-sales.eligible-advance-deposits');
    Route::post('/physical-sales/{physicalSale}/cancel-full', [PhysicalSaleController::class, 'cancelFull'])->middleware('permission:pos.physical-sales.cancel-full')->name('physical-sales.cancel-full');
    Route::get('/physical-sales/{physicalSale}/receive-payment', [PhysicalSaleReceiptController::class, 'create'])->middleware('permission:pos.receipts.create')->name('physical-sales.receive-payment.create');
    Route::get('/physical-sales/{physicalSale}/receive-payment/summary', [PhysicalSaleReceiptController::class, 'summary'])->middleware('permission:pos.receipts.create')->name('physical-sales.receive-payment.summary');
    Route::post('/physical-sales/{physicalSale}/receive-payment', [PhysicalSaleReceiptController::class, 'store'])->middleware('permission:pos.receipts.create')->name('physical-sales.receive-payment.store');
    Route::post('/physical-sales/{physicalSale}/void', [PhysicalSaleController::class, 'void'])->middleware('permission:pos.physical-sales.create')->name('physical-sales.void');
    Route::get('/physical-sales/{physicalSale}/pdf', [PhysicalSaleController::class, 'pdf'])->middleware('permission:pos.physical-sales.print')->name('physical-sales.pdf');
    Route::get('/physical-sales/{physicalSale}', [PhysicalSaleController::class, 'show'])->middleware('permission:pos.physical-sales.view')->name('physical-sales.show');
    Route::get('/receipts', [ReceiptController::class, 'index'])->middleware('permission:pos.receipts.view')->name('receipts.index');
    Route::get('/receipts/data', [ReceiptController::class, 'data'])->middleware('permission:pos.receipts.view')->name('receipts.data');
    Route::get('/receipts/party-options', [ReceiptController::class, 'partyOptions'])->middleware('permission:pos.receipts.create')->name('receipts.party-options');
    Route::get('/receipts/open-item-options', [ReceiptController::class, 'openItemOptions'])->middleware('permission:pos.receipts.create')->name('receipts.open-item-options');
    Route::get('/receipts/create', [ReceiptController::class, 'create'])->middleware('permission:pos.receipts.create')->name('receipts.create');
    Route::post('/receipts', [ReceiptController::class, 'store'])->middleware('permission:pos.receipts.create')->name('receipts.store');
    Route::get('/receipts/{receipt}', [ReceiptController::class, 'show'])->middleware('permission:pos.receipts.view')->name('receipts.show');
    Route::put('/receipts/{receipt}/approve', [ReceiptController::class, 'approve'])->middleware('permission:pos.receipts.approve')->name('receipts.approve');
    Route::post('/receipts/{receipt}/post', [ReceiptController::class, 'post'])->middleware('permission:pos.receipts.post')->name('receipts.post');
    Route::put('/receipts/{receipt}/reverse', [ReceiptController::class, 'reverse'])->middleware('permission:pos.receipts.reverse')->name('receipts.reverse');
    Route::get('/receivables', [ReceivableController::class, 'index'])->middleware('permission:pos.receivables.view')->name('receivables.index');
    Route::get('/receivables/data', [ReceivableController::class, 'data'])->middleware('permission:pos.receivables.view')->name('receivables.data');
    Route::get('/receivables/party-options', [ReceivableController::class, 'partyOptions'])->middleware('permission:pos.receivables.view')->name('receivables.party-options');
    Route::get('/receivables/aging', [ReceivableController::class, 'agingIndex'])->middleware('permission:pos.receivables.view')->name('receivables.aging.index');
    Route::get('/receivables/aging/data', [ReceivableController::class, 'agingData'])->middleware('permission:pos.receivables.view')->name('receivables.aging.data');
    Route::get('/receivables/{openItem}', [ReceivableController::class, 'show'])->middleware('permission:pos.receivables.view')->name('receivables.show');
    Route::get('/advance-deposits', [AdvanceDepositController::class, 'index'])->middleware('permission:pos.advance-deposits.view')->name('advance-deposits.index');
    Route::get('/advance-deposits/data', [AdvanceDepositController::class, 'data'])->middleware('permission:pos.advance-deposits.view')->name('advance-deposits.data');
    Route::get('/advance-deposits/create', [AdvanceDepositController::class, 'create'])->middleware('permission:pos.advance-deposits.create')->name('advance-deposits.create');
    Route::post('/advance-deposits', [AdvanceDepositController::class, 'store'])->middleware('permission:pos.advance-deposits.create')->name('advance-deposits.store');
    Route::post('/advance-deposits/{advanceDeposit}/refund', [AdvanceDepositController::class, 'refund'])->middleware('permission:pos.advance-deposits.refund')->name('advance-deposits.refund');
    Route::get('/advance-deposits/{advanceDeposit}/pdf', [AdvanceDepositController::class, 'pdf'])->middleware('permission:pos.advance-deposits.print')->name('advance-deposits.pdf');
    Route::get('/advance-deposits/{advanceDeposit}', [AdvanceDepositController::class, 'show'])->middleware('permission:pos.advance-deposits.view')->name('advance-deposits.show');
    Route::get('/sales-returns', [SalesReturnController::class, 'index'])->middleware('permission:pos.sales-returns.view')->name('sales-returns.index');
    Route::get('/sales-returns/data', [SalesReturnController::class, 'data'])->middleware('permission:pos.sales-returns.view')->name('sales-returns.data');
    Route::get('/sales-returns/sale-options', [SalesReturnController::class, 'saleOptions'])->middleware('permission:pos.sales-returns.view')->name('sales-returns.sale-options');
    Route::get('/sales-returns/source-lines/{physicalSale}', [SalesReturnController::class, 'sourceLineOptions'])->middleware('permission:pos.sales-returns.view')->name('sales-returns.source-lines');
    Route::get('/sales-returns/create', [SalesReturnController::class, 'create'])->middleware('permission:pos.sales-returns.create')->name('sales-returns.create');
    Route::post('/sales-returns', [SalesReturnController::class, 'store'])->middleware('permission:pos.sales-returns.create')->name('sales-returns.store');
    Route::post('/sales-returns/{salesReturn}/post', [SalesReturnController::class, 'post'])->middleware('permission:pos.sales-returns.post')->name('sales-returns.post');
    Route::post('/sales-returns/{salesReturn}/cancel', [SalesReturnController::class, 'cancel'])->middleware('permission:pos.sales-returns.cancel')->name('sales-returns.cancel');
    Route::get('/sales-returns/{salesReturn}/pdf', [SalesReturnController::class, 'pdf'])->middleware('permission:pos.sales-returns.print')->name('sales-returns.pdf');
    Route::get('/sales-returns/{salesReturn}', [SalesReturnController::class, 'show'])->middleware('permission:pos.sales-returns.view')->name('sales-returns.show');
    Route::get('/sales-documents/{salesDocument}/edit', [SalesDocumentController::class, 'edit'])->middleware('permission:pos.sales-documents.update')->name('sales-documents.edit');
    Route::put('/sales-documents/{salesDocument}', [SalesDocumentController::class, 'update'])->middleware('permission:pos.sales-documents.update')->name('sales-documents.update');
    Route::post('/sales-documents/{salesDocument}/approve', [SalesDocumentController::class, 'approve'])->middleware('permission:pos.sales-documents.approve')->name('sales-documents.approve');
    Route::post('/sales-documents/{salesDocument}/post', [SalesDocumentController::class, 'post'])->middleware('permission:pos.sales-documents.post')->name('sales-documents.post');
    Route::post('/sales-documents/{salesDocument}/void', [SalesDocumentController::class, 'void'])->middleware('permission:pos.sales-documents.void')->name('sales-documents.void');
    Route::get('/customers', [CustomerController::class, 'index'])->middleware('permission:pos.customers.view')->name('customers.index');
    Route::get('/customers/data', [CustomerController::class, 'data'])->middleware('permission:pos.customers.view')->name('customers.data');
    Route::get('/customers/options', [CustomerController::class, 'options'])->middleware('permission:pos.customers.view')->name('customers.options');
    Route::get('/customers/quick-options', [CustomerController::class, 'quickOptions'])->middleware('permission:pos.customers.create')->name('customers.quick-options');
    Route::get('/customer-groups/options', [CustomerController::class, 'groupOptions'])->middleware('permission:pos.customers.view')->name('customer-groups.options');
    Route::get('/customer-groups', [CustomerGroupController::class, 'index'])->middleware('permission:pos.customer-groups.view')->name('customer-groups.index');
    Route::get('/customer-groups/data', [CustomerGroupController::class, 'data'])->middleware('permission:pos.customer-groups.view')->name('customer-groups.data');
    Route::get('/customer-groups/create', [CustomerGroupController::class, 'create'])->middleware('permission:pos.customer-groups.create')->name('customer-groups.create');
    Route::post('/customer-groups', [CustomerGroupController::class, 'store'])->middleware('permission:pos.customer-groups.create')->name('customer-groups.store');
    Route::get('/customer-groups/{customerGroup}/edit', [CustomerGroupController::class, 'edit'])->middleware('permission:pos.customer-groups.update')->name('customer-groups.edit');
    Route::put('/customer-groups/{customerGroup}', [CustomerGroupController::class, 'update'])->middleware('permission:pos.customer-groups.update')->name('customer-groups.update');
    Route::delete('/customer-groups/{customerGroup}', [CustomerGroupController::class, 'destroy'])->middleware('permission:pos.customer-groups.delete')->name('customer-groups.destroy');
    Route::get('/price-lists', [PriceListController::class, 'index'])->middleware('permission:pos.price-lists.view')->name('price-lists.index');
    Route::get('/price-lists/data', [PriceListController::class, 'data'])->middleware('permission:pos.price-lists.view')->name('price-lists.data');
    Route::get('/price-lists/item-options', [PriceListController::class, 'itemOptions'])->middleware('permission:pos.price-lists.view')->name('price-lists.item-options');
    Route::get('/price-lists/uom-options', [PriceListController::class, 'uomOptions'])->middleware('permission:pos.price-lists.view')->name('price-lists.uom-options');
    Route::get('/price-lists/group-options', [PriceListController::class, 'groupOptions'])->middleware('permission:pos.price-lists.view')->name('price-lists.group-options');
    Route::get('/price-lists/create', [PriceListController::class, 'create'])->middleware('permission:pos.price-lists.create')->name('price-lists.create');
    Route::post('/price-lists', [PriceListController::class, 'store'])->middleware('permission:pos.price-lists.create')->name('price-lists.store');
    Route::get('/price-lists/{priceList}/edit', [PriceListController::class, 'edit'])->middleware('permission:pos.price-lists.update')->name('price-lists.edit');
    Route::put('/price-lists/{priceList}', [PriceListController::class, 'update'])->middleware('permission:pos.price-lists.update')->name('price-lists.update');
    Route::delete('/price-lists/{priceList}', [PriceListController::class, 'destroy'])->middleware('permission:pos.price-lists.delete')->name('price-lists.destroy');
    Route::get('/sales-commission-plans', [SalesCommissionPlanController::class, 'index'])->middleware('permission:pos.commission-plans.view')->name('sales-commission-plans.index');
    Route::get('/sales-commission-plans/data', [SalesCommissionPlanController::class, 'data'])->middleware('permission:pos.commission-plans.view')->name('sales-commission-plans.data');
    Route::get('/sales-commission-plans/create', [SalesCommissionPlanController::class, 'create'])->middleware('permission:pos.commission-plans.create')->name('sales-commission-plans.create');
    Route::post('/sales-commission-plans', [SalesCommissionPlanController::class, 'store'])->middleware('permission:pos.commission-plans.create')->name('sales-commission-plans.store');
    Route::get('/sales-commission-plans/{salesCommissionPlan}/edit', [SalesCommissionPlanController::class, 'edit'])->middleware('permission:pos.commission-plans.update')->name('sales-commission-plans.edit');
    Route::put('/sales-commission-plans/{salesCommissionPlan}', [SalesCommissionPlanController::class, 'update'])->middleware('permission:pos.commission-plans.update')->name('sales-commission-plans.update');
    Route::delete('/sales-commission-plans/{salesCommissionPlan}', [SalesCommissionPlanController::class, 'destroy'])->middleware('permission:pos.commission-plans.delete')->name('sales-commission-plans.destroy');
    Route::get('/employee-sales-targets', [EmployeeSalesTargetController::class, 'index'])->middleware('permission:pos.employee-sales-targets.view')->name('employee-sales-targets.index');
    Route::get('/employee-sales-targets/data', [EmployeeSalesTargetController::class, 'data'])->middleware('permission:pos.employee-sales-targets.view')->name('employee-sales-targets.data');
    Route::get('/employee-sales-targets/create', [EmployeeSalesTargetController::class, 'create'])->middleware('permission:pos.employee-sales-targets.create')->name('employee-sales-targets.create');
    Route::post('/employee-sales-targets', [EmployeeSalesTargetController::class, 'store'])->middleware('permission:pos.employee-sales-targets.create')->name('employee-sales-targets.store');
    Route::get('/employee-sales-targets/{employeeSalesTarget}/edit', [EmployeeSalesTargetController::class, 'edit'])->middleware('permission:pos.employee-sales-targets.update')->name('employee-sales-targets.edit');
    Route::put('/employee-sales-targets/{employeeSalesTarget}', [EmployeeSalesTargetController::class, 'update'])->middleware('permission:pos.employee-sales-targets.update')->name('employee-sales-targets.update');
    Route::delete('/employee-sales-targets/{employeeSalesTarget}', [EmployeeSalesTargetController::class, 'destroy'])->middleware('permission:pos.employee-sales-targets.delete')->name('employee-sales-targets.destroy');
    Route::get('/promotions', [PromotionController::class, 'index'])->middleware('permission:pos.promotions.view')->name('promotions.index');
    Route::get('/promotions/data', [PromotionController::class, 'data'])->middleware('permission:pos.promotions.view')->name('promotions.data');
    Route::get('/promotions/item-options', [PromotionController::class, 'itemOptions'])->middleware('permission:pos.promotions.view')->name('promotions.item-options');
    Route::get('/promotions/uom-options', [PromotionController::class, 'uomOptions'])->middleware('permission:pos.promotions.view')->name('promotions.uom-options');
    Route::get('/promotions/group-options', [PromotionController::class, 'groupOptions'])->middleware('permission:pos.promotions.view')->name('promotions.group-options');
    Route::get('/promotions/create', [PromotionController::class, 'create'])->middleware('permission:pos.promotions.create')->name('promotions.create');
    Route::post('/promotions', [PromotionController::class, 'store'])->middleware('permission:pos.promotions.create')->name('promotions.store');
    Route::get('/promotions/{promotion}', [PromotionController::class, 'show'])->middleware('permission:pos.promotions.view')->name('promotions.show');
    Route::post('/promotions/{promotion}/campaign-costs', [PromotionController::class, 'storeCampaignCost'])->middleware('permission:pos.promotions.update')->name('promotions.campaign-costs.store');
    Route::get('/promotions/{promotion}/edit', [PromotionController::class, 'edit'])->middleware('permission:pos.promotions.update')->name('promotions.edit');
    Route::put('/promotions/{promotion}', [PromotionController::class, 'update'])->middleware('permission:pos.promotions.update')->name('promotions.update');
    Route::delete('/promotions/{promotion}', [PromotionController::class, 'destroy'])->middleware('permission:pos.promotions.delete')->name('promotions.destroy');
    Route::get('/customers/create', [CustomerController::class, 'create'])->middleware('permission:pos.customers.create')->name('customers.create');
    Route::post('/customers', [CustomerController::class, 'store'])->middleware('permission:pos.customers.create')->name('customers.store');
    Route::post('/customers/{customer}/addresses', [CustomerController::class, 'storeQuickAddress'])->middleware('permission:pos.customers.update')->name('customers.addresses.store');
    Route::get('/customers/{customer}/edit', [CustomerController::class, 'edit'])->middleware('permission:pos.customers.update')->name('customers.edit');
    Route::put('/customers/{customer}', [CustomerController::class, 'update'])->middleware('permission:pos.customers.update')->name('customers.update');
    Route::delete('/customers/{customer}', [CustomerController::class, 'destroy'])->middleware('permission:pos.customers.delete')->name('customers.destroy');
});
