@extends('Finance::layout')

@section('title', 'สร้างรายการโอนเงินระหว่างบัญชี | Finance')

@php($editing = ($transfer ?? null)?->exists)

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">FINANCE / INTERNAL TRANSFERS</p><h1 class="h3 mb-1">{{ $editing ? 'แก้ไขรายการโอนเงินระหว่างบัญชี' : 'สร้างรายการโอนเงินระหว่างบัญชี' }}</h1><p class="text-secondary mb-0">บันทึกเป็นร่าง และส่งอนุมัติตามลำดับขั้นตอน</p></div><a class="btn btn-outline-secondary" href="{{ $editing ? route('finance.internal-transfers.show', $transfer) : route('finance.internal-transfers.index') }}">กลับ</a></div>
<form id="internal-transfer-form" method="post" action="{{ $editing ? route('finance.internal-transfers.update', $transfer) : route('finance.internal-transfers.store') }}">@csrf @if($editing) @method('PUT') @endif<div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="source-bank-account-id">บัญชีต้นทาง <span class="text-danger">*</span></label><select class="form-select" id="source-bank-account-id" name="source_bank_account_id" required><option value="">เลือกบัญชีต้นทาง</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string)old('source_bank_account_id', $transfer->source_bank_account_id ?? '') === (string)$account->id)>{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label" for="destination-bank-account-id">บัญชีปลายทาง <span class="text-danger">*</span></label><select class="form-select" id="destination-bank-account-id" name="destination_bank_account_id" required><option value="">เลือกบัญชีปลายทาง</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string)old('destination_bank_account_id', $transfer->destination_bank_account_id ?? '') === (string)$account->id)>{{ $account->code }} · {{ $account->name }}</option>@endforeach</select><div class="form-text">บัญชีต้นทางและปลายทางต้องเป็นคนละบัญชี</div></div><div class="col-md-4"><label class="form-label" for="document-date">วันที่เอกสาร <span class="text-danger">*</span></label><input class="form-control" id="document-date" type="date" name="document_date" value="{{ old('document_date', ($transfer->document_date ?? today())->format('Y-m-d')) }}" required></div><div class="col-md-4"><label class="form-label" for="amount">จำนวนเงิน <span class="text-danger">*</span></label><input class="form-control text-end" id="amount" type="number" name="amount" min="0.01" step="0.01" value="{{ old('amount', $transfer->amount ?? '') }}" required></div><div class="col-12"><label class="form-label" for="description">รายละเอียด</label><textarea class="form-control" id="description" name="description" maxlength="500" rows="3">{{ old('description', $transfer->description ?? '') }}</textarea></div></div></div></div><div class="d-flex gap-2 mt-4"><button class="btn btn-dark" type="submit">{{ $editing ? 'บันทึกการแก้ไข' : 'บันทึกฉบับร่าง' }}</button><a class="btn btn-outline-secondary" href="{{ $editing ? route('finance.internal-transfers.show', $transfer) : route('finance.internal-transfers.index') }}">ยกเลิก</a></div></form></div>
@endsection

@push('scripts')
<script>
$(function () { const source = $('#source-bank-account-id'); const destination = $('#destination-bank-account-id'); function syncAccounts() { const sourceId = source.val(); destination.find('option').prop('disabled', false); if (sourceId) { destination.find('option[value="' + sourceId + '"]').prop('disabled', true); if (destination.val() === sourceId) destination.val(''); } } source.on('change', syncAccounts); syncAccounts(); $('#internal-transfer-form').on('submit', function (event) { event.preventDefault(); const form = $(this); const button = form.find('[type=submit]'); if (button.prop('disabled')) return; button.prop('disabled', true); $.ajax({ url: form.attr('action'), method: '{{ $editing ? 'PUT' : 'POST' }}', data: form.serialize(), headers: { Accept: 'application/json', 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') } }).done(function (response) { Swal.fire({ icon: 'success', text: response.msg }).then(function () { window.location.href = response.redirect; }); }).fail(function (xhr) { const response = xhr.responseJSON || {}; const errors = response.errors || {}; Swal.fire({ icon: 'error', text: Object.values(errors).flat()[0] || response.message || 'ไม่สามารถบันทึกรายการได้' }); }).always(function () { button.prop('disabled', false); }); }); });
</script>
@endpush
