@extends('Finance::layout')
@section('title', $transfer->document_number.' | Finance')
@section('content')
@php($labels=['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','REVERSED'=>'กลับรายการแล้ว','VOID'=>'ยกเลิก'])
@php($classes=['DRAFT'=>'app-status-neutral','SUBMITTED'=>'app-status-info','APPROVED'=>'app-status-success','POSTED'=>'app-status-success','REVERSED'=>'app-status-warning','VOID'=>'app-status-danger'])
<div class="container-fluid px-3 px-lg-4 py-4">
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><p class="eyebrow mb-2">FINANCE / INTERNAL TRANSFERS</p><h1 class="h3 mb-2">{{ $transfer->document_number }}</h1><span class="badge {{ $classes[$transfer->status] ?? 'app-status-neutral' }}">{{ $labels[$transfer->status] ?? $transfer->status }}</span></div><div class="d-flex flex-wrap justify-content-lg-end gap-2">
<a class="btn btn-outline-secondary" href="{{ route('finance.internal-transfers.index') }}">กลับ</a>
@if($transfer->status === 'DRAFT' && auth()->user()->hasPermission('finance.internal-transfers.update'))<a class="btn btn-outline-dark" href="{{ route('finance.internal-transfers.edit', $transfer) }}">แก้ไข</a>@endif
@if($transfer->status === 'DRAFT' && auth()->user()->hasPermission('finance.internal-transfers.delete'))<button class="btn btn-outline-danger js-transfer-delete" type="button" data-url="{{ route('finance.internal-transfers.destroy', $transfer) }}">ลบ Draft</button>@endif
@if($transfer->journalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-app-soft" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $transfer->journalEntry) }}"><i class="bx bx-book-open me-1" aria-hidden="true"></i>ดู GL</button>@endif
@if($transfer->reversalJournalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-outline-danger" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $transfer->reversalJournalEntry) }}"><i class="bx bx-undo me-1" aria-hidden="true"></i>ดู GL ยกเลิก</button>@endif
@if($transfer->status === 'DRAFT' && auth()->user()->hasPermission('finance.internal-transfers.submit'))<button class="btn btn-dark js-transfer-action" type="button" data-url="{{ route('finance.internal-transfers.submit', $transfer) }}" data-method="PUT" data-title="ส่งอนุมัติ">ส่งอนุมัติ</button>@endif
@if($transfer->status === 'SUBMITTED' && auth()->user()->hasPermission('finance.internal-transfers.approve'))<button class="btn btn-dark js-transfer-action" type="button" data-url="{{ route('finance.internal-transfers.approve', $transfer) }}" data-method="PUT" data-title="อนุมัติ">อนุมัติ</button>@endif
@if(in_array($transfer->status, ['SUBMITTED','APPROVED'], true) && auth()->user()->hasPermission('finance.internal-transfers.void'))<button class="btn btn-outline-danger js-transfer-action" type="button" data-url="{{ route('finance.internal-transfers.void', $transfer) }}" data-method="PUT" data-title="ยกเลิก">ยกเลิก</button>@endif
@if($transfer->status === 'APPROVED' && auth()->user()->hasPermission('finance.internal-transfers.post'))<button class="btn btn-dark js-transfer-action" type="button" data-url="{{ route('finance.internal-transfers.post', $transfer) }}" data-method="POST" data-title="ลงบัญชี">ลงบัญชี</button>@endif
@if($transfer->status === 'POSTED' && auth()->user()->hasPermission('finance.internal-transfers.reverse'))<button class="btn btn-outline-danger js-transfer-reverse" type="button" data-url="{{ route('finance.internal-transfers.reverse', $transfer) }}">ยกเลิกรายการ</button>@endif
</div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-4"><div class="col-md-3"><div class="small text-secondary">วันที่เอกสาร</div>{{ $transfer->document_date?->format($dateFormat) ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">บัญชีต้นทาง</div><strong>{{ $transfer->sourceBankAccount?->code }}</strong><div class="text-secondary">{{ $transfer->sourceBankAccount?->name }}</div></div><div class="col-md-3"><div class="small text-secondary">บัญชีปลายทาง</div><strong>{{ $transfer->destinationBankAccount?->code }}</strong><div class="text-secondary">{{ $transfer->destinationBankAccount?->name }}</div></div><div class="col-md-3"><div class="small text-secondary">จำนวนเงิน</div><strong class="fs-5">{{ number_format((float)$transfer->amount,2) }}</strong></div><div class="col-12"><div class="small text-secondary">รายละเอียด</div>{{ $transfer->description ?: '—' }}</div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{ $event->created_at?->format('d/m/Y H:i') }}</div><div><strong>{{ $event->action }}</strong><div class="small text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">รายละเอียด:</span> {{ $event->reason }}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติเอกสาร</p>@endforelse</div></div></div>
@endsection
@push('scripts')
<script>
$(function () { $('.js-transfer-action').on('click', function () { const button=$(this); if(button.prop('disabled')) return; Swal.fire({icon:'question',title:button.data('title')+'เอกสารนี้?',showCancelButton:true,confirmButtonText:button.data('title'),cancelButtonText:'ย้อนกลับ'}).then(function(r){if(!r.isConfirmed)return;button.prop('disabled',true);$.ajax({url:button.data('url'),method:button.data('method'),headers:{Accept:'application/json','X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}}).done(function(x){Swal.fire({icon:'success',text:x.msg}).then(function(){location.reload();});}).fail(function(x){Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถดำเนินการได้'});}).always(function(){button.prop('disabled',false);});}); });
$('.js-transfer-delete').on('click', function(){const button=$(this);Swal.fire({icon:'warning',title:'ลบเอกสาร Draft?',text:'เอกสารจะถูกลบออกจากรายการ',showCancelButton:true,confirmButtonText:'ลบเอกสาร',cancelButtonText:'ย้อนกลับ',confirmButtonColor:'#dc3545'}).then(function(r){if(!r.isConfirmed)return;button.prop('disabled',true);$.ajax({url:button.data('url'),method:'DELETE',data:{_token:$('meta[name="csrf-token"]').attr('content')},headers:{Accept:'application/json'}}).done(function(x){Swal.fire({icon:'success',text:x.msg}).then(function(){window.location.href=x.redirect;});}).fail(function(x){Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถลบเอกสารได้'});});}); });
$('.js-transfer-reverse').on('click', function(){const button=$(this);Swal.fire({title:'ยกเลิกรายการโอน',input:'textarea',inputPlaceholder:'เหตุผลอย่างน้อย 10 ตัวอักษร',showCancelButton:true,confirmButtonText:'ยกเลิกรายการ',cancelButtonText:'ย้อนกลับ',preConfirm:function(reason){reason=$.trim(reason||'');if(reason.length<10){Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร');return false;}return{reversal_date:'{{ today()->format('Y-m-d') }}',reason:reason};}}).then(function(r){if(!r.isConfirmed)return;$.ajax({url:button.data('url'),method:'PUT',data:r.value,headers:{Accept:'application/json','X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}}).done(function(x){Swal.fire({icon:'success',text:x.msg}).then(function(){location.reload();});}).fail(function(x){Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถยกเลิกรายการได้'});});}); }); });
</script>
@endpush
