@extends('Pos::layout')

@section('title', 'ใบรับคืน '.$returnDocument->document_number)

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="app-eyebrow">SALES / RETURN</p>
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
        <div><h1 class="h2 mb-2">ใบรับคืน / ใบลดหนี้ {{ $returnDocument->document_number }}</h1>@include('Pos::partials.document-status-badge', ['status' => $returnDocument->status, 'label' => ['DRAFT' => 'ร่าง', 'POSTED' => 'ลงบัญชีแล้ว', 'VOID' => 'ยกเลิก'][$returnDocument->status] ?? $returnDocument->status])</div>
        <div class="d-flex flex-wrap justify-content-end gap-2">
            @if($returnDocument->status === 'DRAFT' && auth()->user()->hasPermission('pos.sales-returns.post'))<button class="btn btn-primary d-inline-flex align-items-center gap-1 js-sales-return-post" data-url="{{ route('pos.sales-returns.post', $returnDocument) }}" data-reason="{{ $returnDocument->reason }}" type="button"><i class="bx bx-check-circle" aria-hidden="true"></i>Post เอกสาร</button>@endif
            @if($returnDocument->status === 'DRAFT' && auth()->user()->hasPermission('pos.sales-returns.cancel'))<button class="btn btn-outline-danger d-inline-flex align-items-center gap-1 js-sales-return-cancel" data-url="{{ route('pos.sales-returns.cancel', $returnDocument) }}" type="button"><i class="bx bx-x-circle" aria-hidden="true"></i>ยกเลิก</button>@endif
            @if(auth()->user()->hasPermission('pos.sales-returns.print'))<a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-returns.pdf', $returnDocument) }}" target="_blank" rel="noopener"><i class="bx bx-printer" aria-hidden="true"></i>พิมพ์ PDF</a>@endif
            @if(auth()->user()->hasPermission('accounting.journal-entries.view') && $returnDocument->journal_entry_id)<button class="btn btn-app-soft d-inline-flex align-items-center gap-1" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $returnDocument->journal_entry_id) }}"><i class="bx bx-book-open" aria-hidden="true"></i>ดู GL ลดหนี้</button>@endif
            @if(auth()->user()->hasPermission('accounting.journal-entries.view') && $returnDocument->cogs_journal_entry_id)<button class="btn btn-app-soft d-inline-flex align-items-center gap-1" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $returnDocument->cogs_journal_entry_id) }}"><i class="bx bx-package" aria-hidden="true"></i>ดู GL ต้นทุน</button>@endif
            <a class="btn btn-outline-secondary d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-returns.index') }}"><i class="bx bx-arrow-back" aria-hidden="true"></i>กลับรายการ</a>
        </div>
    </div>

    <div class="alert {{ $returnDocument->status === 'DRAFT' ? 'alert-info' : ($returnDocument->status === 'VOID' ? 'alert-danger' : 'alert-success') }} mb-4">{{ $returnDocument->status === 'DRAFT' ? 'เอกสารนี้เป็นร่างและยังไม่กระทบ Stock/GL; ระบบจะตรวจใบขายต้นทาง ปริมาณคืน Stock และงวดบัญชีที่เปิดอยู่ก่อน Post' : ($returnDocument->status === 'VOID' ? 'เอกสารนี้ถูกยกเลิกแล้ว'.($returnDocument->void_reason ? ' · เหตุผล: '.$returnDocument->void_reason : '') : 'เอกสารนี้ลงบัญชีและคืน Stock/GL แล้ว') }}</div>

    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h6 text-uppercase text-secondary mb-3">ข้อมูลเอกสาร</h2><div class="row g-3"><div class="col-md-3"><div class="text-secondary small">วันที่เอกสาร</div><div class="fw-semibold">{{ $returnDocument->document_date?->format($dateFormat) }}</div></div><div class="col-md-3"><div class="text-secondary small">ลูกค้า</div><div class="fw-semibold">{{ $returnDocument->party_code }} · {{ $returnDocument->party_name }}</div></div><div class="col-md-3"><div class="text-secondary small">HS/IV ต้นทาง</div><div class="fw-semibold">{{ $returnDocument->sale?->document_number ?? '—' }}</div></div><div class="col-md-3"><div class="text-secondary small">เหตุผลการคืน</div><div class="fw-semibold">{{ $returnDocument->reason }}</div></div>@if($returnDocument->refundBankAccount)<div class="col-md-3"><div class="text-secondary small">บัญชีคืนเงิน</div><div class="fw-semibold">{{ $returnDocument->refundBankAccount->code }} · {{ $returnDocument->refundBankAccount->name }}</div></div><div class="col-md-3"><div class="text-secondary small">ยอดคืนผ่านเงินสด/ธนาคาร</div><div class="fw-semibold">{{ number_format((float) $returnDocument->refund_amount, 2) }}</div></div>@endif</div></div></div>

    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">รายการสินค้าที่คืน</h2><strong>{{ number_format((float) $returnDocument->total_amount, 2) }}</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>#</th><th>สินค้า</th><th>หน่วย</th><th class="text-end">จำนวน</th><th class="text-end">ราคา/หน่วย</th><th class="text-end">รวม</th></tr></thead><tbody>@forelse($returnDocument->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ data_get($line->item_snapshot, 'code', $line->item?->code) }} · {{ data_get($line->item_snapshot, 'name', $line->item?->name) }}</td><td>{{ $line->uom?->code ?? '—' }}</td><td class="text-end">{{ number_format((float) $line->quantity, $decimalPlaces) }}</td><td class="text-end">{{ number_format((float) $line->unit_price, 2) }}</td><td class="text-end fw-semibold">{{ number_format((float) $line->line_total, 2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">ไม่มีรายการ</td></tr>@endforelse</tbody><tfoot class="table-light"><tr><th colspan="5" class="text-end">ยอดรวม</th><th class="text-end">{{ number_format((float) $returnDocument->total_amount, 2) }}</th></tr></tfoot></table></div></div></div>

    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">เอกสารที่เกี่ยวข้อง</h2><div class="d-flex flex-wrap align-items-center gap-2">@if($returnDocument->sale)<a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.physical-sales.show', $returnDocument->sale) }}"><i class="bx bx-receipt" aria-hidden="true"></i>HS/IV {{ $returnDocument->sale->document_number }}</a><i class="bx bx-right-arrow-alt text-secondary" aria-hidden="true"></i>@endif<span class="badge app-badge-info">ใบรับคืน {{ $returnDocument->document_number }}</span>@if($returnDocument->status === 'POSTED')<i class="bx bx-right-arrow-alt text-secondary" aria-hidden="true"></i><span class="badge app-badge-success">Stock / GL กลับรายการแล้ว</span>@endif</div></div></div>

    <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="border-bottom py-2"><span class="text-secondary small">{{ $event->created_at?->format($dateFormat.' H:i') }}</span> <strong>{{ ['pos.sales-return.created' => 'สร้างร่างใบรับคืน', 'pos.sales-return.posted.financial' => 'Post ใบรับคืน/ลดหนี้และกลับ Stock/GL', 'pos.sales-return.voided' => 'ยกเลิกใบรับคืน/ลดหนี้'][$event->action] ?? $event->action }}</strong> <span class="text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</span></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection

@push('scripts')
<script>
$(function () {
    $('.js-sales-return-post').on('click', async function () { const button = $(this), isCashSale = @json($returnDocument->sale?->document_type === 'HS'); const date = await Swal.fire({ icon: 'warning', title: 'Post ใบรับคืน/ลดหนี้?', html: 'ระบบจะคืน Stock และสร้าง GL<br><small>เหตุผล: '+$('<div>').text(button.data('reason')).html()+'</small>', input: 'date', inputLabel: 'วันที่ Post', inputValue: @json(today()->format('Y-m-d')), showCancelButton: true, confirmButtonText: 'ถัดไป', cancelButtonText: 'กลับ', preConfirm: value => { if (!value) Swal.showValidationMessage('กรุณาระบุวันที่ Post'); return value; } }); if (!date.isConfirmed) return; let refundBankAccountId = null; if (isCashSale) { const account = await Swal.fire({ icon: 'warning', title: 'เลือกบัญชีคืนเงินลูกค้า', input: 'select', inputOptions: @json($bankAccounts->mapWithKeys(fn ($account) => [$account->id => $account->code.' · '.$account->name])), inputPlaceholder: 'เลือกบัญชีเงินสด/ธนาคาร', showCancelButton: true, confirmButtonText: 'ยืนยัน Post', cancelButtonText: 'กลับ', preConfirm: value => { if (!value) Swal.showValidationMessage('กรุณาเลือกบัญชีคืนเงิน'); return value; } }); if (!account.isConfirmed) return; refundBankAccountId = account.value; } button.prop('disabled', true); $.post(button.data('url'), { _token: $('meta[name="csrf-token"]').attr('content'), posting_date: date.value, refund_bank_account_id: refundBankAccountId }).done(response => Swal.fire({ icon: 'success', text: response.msg }).then(() => location.reload())).fail(xhr => Swal.fire({ icon: 'error', text: xhr.responseJSON?.message || 'ไม่สามารถ Post ใบรับคืนได้' })).always(() => button.prop('disabled', false)); });
    $('.js-sales-return-cancel').on('click', function () { const button = $(this); Swal.fire({ icon: 'warning', title: 'ยกเลิกใบรับคืน/ลดหนี้?', input: 'textarea', inputLabel: 'เหตุผล (อย่างน้อย 10 ตัวอักษร)', showCancelButton: true, confirmButtonText: 'ยืนยันยกเลิก', cancelButtonText: 'กลับ', preConfirm: value => { if (!value || value.trim().length < 10) Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร'); return value; } }).then(result => { if (!result.isConfirmed) return; button.prop('disabled', true); $.post(button.data('url'), { _token: $('meta[name="csrf-token"]').attr('content'), reason: result.value }).done(response => Swal.fire({ icon: 'success', text: response.msg }).then(() => location.reload())).fail(xhr => Swal.fire({ icon: 'error', text: xhr.responseJSON?.message || 'ไม่สามารถยกเลิกเอกสารได้' })).always(() => button.prop('disabled', false)); }); });
});
</script>
@endpush
