@extends('Pos::layout')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="app-eyebrow mb-2">SALES / RFQ</p>
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h2 mb-2">ใบขอราคา {{ $x->document_number }}</h1>@include('Pos::partials.document-status-badge', ['status' => $x->status, 'label' => ['WAIT'=>'รอพิจารณา','APPROVED'=>'อนุมัติแล้ว','REJECTED'=>'ไม่อนุมัติ','CANCELLED'=>'ยกเลิก'][$x->status] ?? $x->status])</div><div class="d-flex flex-wrap justify-content-end gap-2">@if($x->status === 'WAIT' && auth()->user()->hasPermission('pos.sales-rfqs.approve'))<a class="btn btn-primary d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-rfqs.review', $x) }}"><i class="bx bx-check-circle"></i>พิจารณา RFQ</a>@endif @if($x->quotation)<a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-quotations.show', $x->quotation) }}"><i class="bx bx-file"></i>ดูใบเสนอราคา</a>@elseif($x->status === 'APPROVED' && auth()->user()->hasPermission('pos.sales-quotations.create'))<form class="d-inline-flex" method="post" action="{{ route('pos.sales-quotations.from-rfq', $x) }}">@csrf<button class="btn btn-primary d-inline-flex align-items-center gap-1" type="submit"><i class="bx bx-plus-circle"></i>สร้างใบเสนอราคา</button></form>@endif<a class="btn btn-outline-secondary d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-rfqs.index') }}"><i class="bx bx-arrow-back"></i>กลับรายการ</a></div></div>
    @include('Pos::partials.document-trail', ['flowDocuments' => $flowDocuments])
    @include('Pos::partials.sales-document-header', ['document' => $x, 'sourceIntake' => $flowDocuments['intake'] ?? null])
    @if($x->description || $x->cancel_reason)<div class="card border-0 shadow-sm mb-3"><div class="card-body p-4">@if($x->description)<div><div class="text-secondary small">รายละเอียด</div><div>{{ $x->description }}</div></div>@endif @if($x->cancel_reason)<div class="alert alert-danger-subtle mt-3 mb-0">เหตุผลที่ยกเลิก: {{ $x->cancel_reason }}</div>@endif</div></div>@endif
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-4"><h2 class="h5 mb-3">รายการสินค้า/รายละเอียด</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>สินค้า/รายละเอียด</th><th>หน่วย</th><th class="text-end">จำนวน</th></tr></thead><tbody>@forelse($x->lines as $l)<tr><td>{{ $l->line_number }}</td><td>{{ data_get($l->item_snapshot, 'code') }}{{ data_get($l->item_snapshot, 'name') ? ' · '.data_get($l->item_snapshot, 'name') : '' }}{{ $l->description ? ' — '.$l->description : '' }}</td><td>{{ data_get($l->uom_snapshot, 'code', '-') }}</td><td class="text-end">{{ number_format((float) $l->quantity, 4) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">ไม่พบรายการ</td></tr>@endforelse</tbody></table></div>@include('Pos::partials.sales-tax-summary', ['document' => $x, 'sourceIntake' => $flowDocuments['intake'] ?? null])</div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $h)<div class="d-flex gap-3 border-bottom py-2"><div class="text-secondary small text-nowrap">{{ optional($h->created_at)->format('d/m/Y H:i') }}</div><div><div class="fw-semibold">{{ $h->action }}</div><div class="text-secondary small">{{ optional($h->user)->name ?? 'ระบบ' }}@if($h->reason) · {{ $h->reason }}@endif</div></div></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection
