@extends('Pos::layout')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="app-eyebrow mb-2">SALES / RFQ</p>
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h2 mb-2">ใบขอราคา {{ $x->document_number }}</h1>@include('Pos::partials.document-status-badge', ['status' => $x->status, 'label' => ['WAIT'=>'รอพิจารณา','APPROVED'=>'อนุมัติแล้ว','REJECTED'=>'ไม่อนุมัติ','CANCELLED'=>'ยกเลิก'][$x->status] ?? $x->status])</div><div class="d-flex flex-wrap justify-content-end gap-2"><a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-rfqs.index') }}"><i class="bx bx-arrow-back"></i>กลับหน้ารายการ</a>@if(auth()->user()->hasPermission('pos.sales-rfqs.print'))<a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-rfqs.pdf', $x) }}" target="_blank" rel="noopener"><i class="bx bx-printer"></i>พิมพ์ PDF</a>@endif @if($x->quotation)<a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-quotations.show', $x->quotation) }}"><i class="bx bx-file"></i>ดูใบเสนอราคา</a>@elseif($x->status === 'APPROVED' && auth()->user()->hasPermission('pos.sales-quotations.create'))<form class="d-inline-flex" method="post" action="{{ route('pos.sales-quotations.from-rfq', $x) }}">@csrf<button class="btn btn-app-primary d-inline-flex align-items-center gap-1" type="submit"><i class="bx bx-plus-circle"></i>สร้างใบเสนอราคา</button></form>@endif @if($x->status === 'WAIT' && auth()->user()->hasPermission('pos.sales-rfqs.approve'))<a class="btn btn-app-primary d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-rfqs.review', $x) }}"><i class="bx bx-check-circle"></i>พิจารณา RFQ</a>@endif @if($x->status === 'WAIT' && auth()->user()->hasPermission('pos.sales-rfqs.cancel'))<button type="button" class="btn btn-app-danger d-inline-flex align-items-center gap-1 js-rfq-cancel" data-url="{{ route('pos.sales-rfqs.cancel', $x) }}"><i class="bx bx-x-circle"></i>ยกเลิกเอกสาร</button>@endif</div></div>
    @if($x->status === 'WAIT')<div class="alert alert-info border-0 shadow-sm mb-4"><strong>ขั้นถัดไป:</strong> พิจารณา RFQ เพื่ออนุมัติและสร้างใบเสนอราคา หรือยกเลิกเอกสารหากไม่ดำเนินการต่อ</div>@elseif($x->status === 'APPROVED' && ! $x->quotation)<div class="alert alert-info border-0 shadow-sm mb-4"><strong>ขั้นถัดไป:</strong> สร้างใบเสนอราคาจาก RFQ ที่อนุมัติแล้ว</div>@elseif($x->quotation)<div class="alert alert-success border-0 shadow-sm mb-4"><strong>มีใบเสนอราคาที่เชื่อมโยงแล้ว</strong> เปิดเอกสารที่เชื่อมโยงเพื่อติดตามการขายต่อ</div>@endif
    @include('Pos::partials.document-trail', ['flowDocuments' => $flowDocuments])
    @include('Pos::partials.sales-document-header', ['document' => $x, 'sourceIntake' => $flowDocuments['intake'] ?? null])
    @if($x->description || $x->cancel_reason)<div class="card border-0 shadow-sm mb-3"><div class="card-body p-4">@if($x->description)<div><div class="text-secondary small">รายละเอียด</div><div>{{ $x->description }}</div></div>@endif @if($x->cancel_reason)<div class="alert alert-danger-subtle mt-3 mb-0">เหตุผลที่ยกเลิก: {{ $x->cancel_reason }}</div>@endif</div></div>@endif
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-4"><h2 class="h5 mb-3">รายการสินค้า/รายละเอียด</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>สินค้า/รายละเอียด</th><th>หน่วย</th><th class="text-end">จำนวน</th></tr></thead><tbody>@forelse($x->lines as $l)<tr><td>{{ $l->line_number }}</td><td>{{ data_get($l->item_snapshot, 'code') }}{{ data_get($l->item_snapshot, 'name') ? ' · '.data_get($l->item_snapshot, 'name') : '' }}{{ $l->description ? ' — '.$l->description : '' }}</td><td>{{ data_get($l->uom_snapshot, 'code', '-') }}</td><td class="text-end">{{ number_format((float) $l->quantity, 4) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">ไม่พบรายการ</td></tr>@endforelse</tbody></table></div>@include('Pos::partials.sales-tax-summary', ['document' => $x, 'sourceIntake' => $flowDocuments['intake'] ?? null])</div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $h)<div class="d-flex gap-3 border-bottom py-2"><div class="text-secondary small text-nowrap">{{ optional($h->created_at)->format('d/m/Y H:i') }}</div><div><div class="fw-semibold">{{ $h->action }}</div><div class="text-secondary small">{{ optional($h->user)->name ?? 'ระบบ' }}@if($h->reason) · {{ $h->reason }}@endif</div></div></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection
@push('scripts')<script>$(function(){$('.js-rfq-cancel').on('click',function(){const button=$(this);Swal.fire({icon:'warning',title:'ยกเลิกเอกสารใบขอราคา?',input:'textarea',inputLabel:'เหตุผล (อย่างน้อย 10 ตัวอักษร)',showCancelButton:true,confirmButtonText:'ยกเลิกเอกสาร',cancelButtonText:'กลับ',inputValidator:value=>value&&value.trim().length>=10?undefined:'กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร'}).then(result=>{if(!result.isConfirmed)return;button.prop('disabled',true);$.post(button.data('url'),{_token:$('meta[name=csrf-token]').attr('content'),reason:result.value}).done(response=>Swal.fire({icon:'success',text:response.msg}).then(()=>location.reload())).fail(xhr=>{button.prop('disabled',false);Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ดำเนินการไม่สำเร็จ'})})})})});</script>@endpush
