@extends('Asset::layout')

@section('title', $impairment->document_number.' | New ERP')

@section('content')
@php
    $labels = ['DRAFT' => 'ร่าง', 'SUBMITTED' => 'รออนุมัติ', 'APPROVED' => 'อนุมัติแล้ว', 'POSTED' => 'ลงบัญชีแล้ว', 'CANCELLED' => 'ยกเลิก'];
    $classes = ['DRAFT' => 'app-status-neutral', 'SUBMITTED' => 'app-status-info', 'APPROVED' => 'app-status-success', 'POSTED' => 'app-status-success', 'CANCELLED' => 'app-status-danger'];
@endphp
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-xl-row justify-content-between align-items-xl-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">ASSET / IMPAIRMENT</p><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><h1 class="h3 mb-0">{{ $impairment->document_number }}</h1><span class="badge {{ $classes[$impairment->status] ?? 'app-status-neutral' }}">{{ $labels[$impairment->status] ?? $impairment->status }}</span></div><p class="text-secondary mb-0">{{ $impairment->asset?->asset_number }} · {{ $impairment->asset?->name }} · ประเมิน {{ $impairment->assessment_date?->format('d/m/Y') }}</p></div>
        <div class="d-flex flex-wrap gap-2"><a class="btn btn-app-soft" href="{{ route('asset.impairments.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a>@if($impairment->status==='DRAFT')<button class="btn btn-app-primary js-action" data-url="{{ route('asset.impairments.submit',$impairment) }}"><i class="bx bx-send me-1" aria-hidden="true"></i>ส่งอนุมัติ</button>@elseif($impairment->status==='SUBMITTED')<button class="btn btn-app-primary js-action" data-url="{{ route('asset.impairments.approve',$impairment) }}"><i class="bx bx-check me-1" aria-hidden="true"></i>อนุมัติ</button>@elseif($impairment->status==='APPROVED')@if($postReadiness['ready'])<button class="btn btn-app-primary js-action" data-url="{{ route('asset.impairments.post',$impairment) }}"><i class="bx bx-send me-1" aria-hidden="true"></i>ลงบัญชี</button>@else<button class="btn btn-app-primary" disabled><i class="bx bx-send me-1" aria-hidden="true"></i>ลงบัญชี</button>@endif @endif @if($impairment->status==='POSTED' && !$impairment->reversal_of_id)<button class="btn btn-app-danger js-reverse" data-url="{{ route('asset.impairments.reverse',$impairment) }}"><i class="bx bx-x-circle me-1" aria-hidden="true"></i>ยกเลิกเอกสาร</button>@endif @if(in_array($impairment->status,['DRAFT','SUBMITTED','APPROVED']))<button class="btn btn-app-danger js-cancel" data-url="{{ route('asset.impairments.cancel',$impairment) }}"><i class="bx bx-x-circle me-1" aria-hidden="true"></i>ยกเลิกเอกสาร</button>@endif @if($impairment->status==='DRAFT' && auth()->user()->hasPermission('asset.impairments.create'))<button class="btn btn-app-danger js-delete-impairment" data-url="{{ route('asset.impairments.destroy',$impairment) }}" type="button"><i class="bx bx-trash me-1" aria-hidden="true"></i>ลบร่าง</button>@endif</div>
    </div>
    @if($impairment->status === 'APPROVED' && !($postReadiness['ready'] ?? false))<div class="alert alert-warning border-0 shadow-sm mb-4"><strong>ยังลงบัญชีไม่ได้</strong><ul class="mb-0 mt-2">@foreach($postReadiness['blockers'] as $blocker)<li>{{ $blocker }}</li>@endforeach</ul></div>@endif
    <div class="alert alert-info border-0 shadow-sm d-flex gap-2" role="note"><i class="bx bx-info-circle fs-5" aria-hidden="true"></i><div>การด้อยค่าจะปรับฐานค่าเสื่อมในอนาคตแบบ Prospective และเอกสารที่ลงบัญชีแล้วต้องใช้ “กลับรายการ” เป็นเอกสารใหม่เท่านั้น</div></div>
    <div class="row g-4 mb-4"><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">มูลค่าตามบัญชีก่อนด้อยค่า</div><div class="fs-4 fw-semibold mt-1">{{ number_format((float)$impairment->carrying_amount,2) }}</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">มูลค่าที่คาดว่าจะได้รับคืน</div><div class="fs-4 fw-semibold mt-1">{{ number_format((float)$impairment->recoverable_amount,2) }}</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">จำนวนด้อยค่า</div><div class="fs-4 fw-semibold text-danger mt-1">{{ number_format((float)$impairment->impairment_amount,2) }}</div></div></div></div></div>
    <div class="row g-4"><div class="col-12 col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h5 mb-1">รายละเอียดการประเมิน</h2><p class="small text-secondary mb-0">หลักฐานและเหตุผลประกอบการด้อยค่า</p></div><div class="card-body p-4"><dl class="row mb-0"><dt class="col-sm-4 text-secondary fw-normal">สินทรัพย์</dt><dd class="col-sm-8">{{ $impairment->asset?->asset_number }} · {{ $impairment->asset?->name }}</dd><dt class="col-sm-4 text-secondary fw-normal">หลักฐานอ้างอิง</dt><dd class="col-sm-8">{{ $impairment->evidence_reference ?: '-' }}</dd><dt class="col-sm-4 text-secondary fw-normal">เหตุผล</dt><dd class="col-sm-8">{{ $impairment->reason }}</dd></dl></div></div></div><div class="col-12 col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h5 mb-1">สถานะบัญชี</h2><p class="small text-secondary mb-0">ข้อมูลการลงบัญชีและการกลับรายการ</p></div><div class="card-body p-4"><dl class="row mb-0"><dt class="col-6 text-secondary fw-normal">Journal</dt><dd class="col-6 text-end">{{ $impairment->journal_entry_id ? '#'.$impairment->journal_entry_id : 'ยังไม่มี' }}</dd><dt class="col-6 text-secondary fw-normal">เอกสารต้นฉบับ</dt><dd class="col-6 text-end">{{ $impairment->reversal_of_id ? '#'.$impairment->reversal_of_id : '-' }}</dd><dt class="col-6 text-secondary fw-normal">ผู้สร้าง</dt><dd class="col-6 text-end">{{ $impairment->createdBy?->name ?? '-' }}</dd></dl></div></div></div></div>
    <div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h5 mb-1">ประวัติการทำรายการ</h2><p class="small text-secondary mb-0">Audit Trail · เวลาไทย (UTC+7)</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>เหตุการณ์</th><th>วันเวลา</th><th>ผู้ดำเนินการ</th></tr></thead><tbody><tr><td>สร้างเอกสาร</td><td>{{ $impairment->created_at?->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</td><td>{{ $impairment->createdBy?->name ?? '-' }}</td></tr>@if($impairment->submitted_at)<tr><td>ส่งอนุมัติ</td><td>{{ $impairment->submitted_at->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</td><td>-</td></tr>@endif @if($impairment->approved_at)<tr><td>อนุมัติ</td><td>{{ $impairment->approved_at->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</td><td>-</td></tr>@endif @if($impairment->posted_at)<tr><td>ลงบัญชี</td><td>{{ $impairment->posted_at->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</td><td>-</td></tr>@endif</tbody></table></div></div>
</div>
@endsection

@push('scripts')
<script>
$(function(){window.erpAjaxDelete({button:'.js-delete-impairment',redirect:@json(route('asset.impairments.index')),confirm:'ยืนยันการลบเอกสารด้อยค่าร่างนี้หรือไม่?'});function action(selector,title,extra){$(selector).on('click',function(){var b=$(this);Swal.fire({icon:'warning',title:title,input:extra?'textarea':undefined,inputLabel:extra?'เหตุผล':'' ,showCancelButton:true,preConfirm:function(v){if(extra&&(!v||v.trim().length<10))Swal.showValidationMessage('ระบุเหตุผลอย่างน้อย 10 ตัวอักษร');}}).then(function(r){if(!r.isConfirmed)return;var data={_token:'{{ csrf_token() }}'};if(extra)data[selector==='.js-cancel'?'cancellation_reason':'reason']=r.value;$.post(b.data('url'),data).done(function(x){Swal.fire({icon:'success',title:x.msg}).then(function(){location.href=x.redirect;});}).fail(window.erpAjaxError);});});}action('.js-action','ยืนยันเปลี่ยนสถานะ?',false);action('.js-reverse','ยืนยันกลับรายการ?',true);action('.js-cancel','ยืนยันยกเลิกเอกสาร?',true);});
</script>
@endpush
