@extends('Wms::layout')
@php($editing = filled($document))
@section('title', ($editing ? 'แก้ไข' : 'สร้าง').' Adjustment | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
 <div class="d-flex justify-content-between align-items-end mb-4"><div><p class="eyebrow mb-2">WMS / INVENTORY ADJUSTMENT</p><h1 class="h3 mb-2">{{ $editing ? 'แก้ไขร่าง' : 'สร้าง' }} ปรับปรุงสินค้าคงเหลือ</h1><p class="text-secondary mb-0">สร้างเอกสารหนึ่งใบได้หลายรายการ และอนุมัติก่อนลง Stock และ GL</p></div><a class="btn btn-outline-secondary" href="{{ route('wms.inventory-adjustments.index') }}"><i class="bx bx-arrow-back" aria-hidden="true"></i> กลับ</a></div>
 <div class="card border-0 shadow-sm"><div class="card-body p-4"><form id="adjustment-document-form" method="post" action="{{ $editing ? route('wms.inventory-adjustments.documents.update', $document) : route('wms.inventory-adjustments.store') }}">@csrf @if($editing) @method('PUT') @endif
  <div class="row g-3 mb-4"><div class="col-md-3"><label class="form-label">วันที่เอกสาร</label><input class="form-control" name="document_date" type="date" value="{{ $document?->document_date?->format('Y-m-d') ?? now()->format('Y-m-d') }}" required></div><div class="col-md-3"><label class="form-label">ประเภทการปรับปรุง</label><select class="form-select" name="direction" required><option value="GAIN" @selected(old('direction', $document?->direction ?? 'GAIN') === 'GAIN')>เพิ่มสินค้า</option><option value="LOSS" @selected(old('direction', $document?->direction) === 'LOSS')>ลดสินค้า</option></select><div class="form-text">ทั้งเอกสารใช้ทิศทางเดียวกันทุกบรรทัด</div></div><div class="col-md-6"><label class="form-label">เหตุผล</label><input class="form-control" name="reason" minlength="10" maxlength="500" value="{{ old('reason', $document?->reason) }}" placeholder="เช่น ปรับยอดจากผลตรวจนับคลัง วันที่..." required></div></div>
  <div class="d-flex justify-content-between align-items-center mb-2"><h2 class="h5 mb-0">รายการปรับปรุง</h2><button class="btn btn-sm btn-app-soft" type="button" id="add-adjustment-line"><i class="bx bx-plus" aria-hidden="true"></i> เพิ่มรายการ</button></div>
  <div class="table-responsive"><table class="table align-middle" id="adjustment-lines"><thead><tr><th style="min-width:260px">สินค้า</th><th style="min-width:150px">หน่วย Stock (หน่วยฐาน)</th><th style="min-width:150px" class="text-end">จำนวน</th><th style="min-width:170px" class="text-end">มูลค่ารวม</th><th style="width:60px">จัดการ</th></tr></thead><tbody>
  @if($editing) @foreach($document->lines as $i => $line)<tr data-index="{{ $i }}"><td><select class="form-select js-adjustment-item" name="lines[{{ $i }}][item_id]" data-url="{{ route('wms.inventory-adjustments.item-options') }}" required><option value="{{ $line->item_id }}" selected>{{ $line->item?->code }} · {{ $line->item?->name }}</option></select></td><td><select class="form-select" name="lines[{{ $i }}][uom_id]" required><option value="{{ $line->uom_id }}" selected>{{ $line->uom?->code }} · {{ $line->uom?->name }}</option></select></td><td><input class="form-control text-end" name="lines[{{ $i }}][quantity]" type="number" min="0.00000001" step="any" value="{{ $line->quantity }}" required></td><td><input class="form-control text-end" name="lines[{{ $i }}][value]" type="number" min="0.01" step="any" value="{{ $line->value }}" required></td><td><button class="btn btn-sm btn-app-danger js-remove-line" type="button" title="ลบรายการ" aria-label="ลบรายการ"><i class="bx bx-trash" aria-hidden="true"></i></button></td></tr>@endforeach @else
  <tr data-index="0"><td><select class="form-select js-adjustment-item" name="lines[0][item_id]" data-url="{{ route('wms.inventory-adjustments.item-options') }}" required><option value="">ค้นหาสินค้า</option></select></td><td><select class="form-select" name="lines[0][uom_id]" required><option value="">หน่วย Stock</option></select></td><td><input class="form-control text-end" name="lines[0][quantity]" type="number" min="0.00000001" step="any" required></td><td><input class="form-control text-end" name="lines[0][value]" type="number" min="0.01" step="any" required></td><td><button class="btn btn-sm btn-app-danger js-remove-line" type="button" title="ลบรายการ" aria-label="ลบรายการ"><i class="bx bx-trash" aria-hidden="true"></i></button></td></tr>
  @endif</tbody></table></div>
  <div class="d-flex gap-2 mt-4"><button class="btn btn-dark" type="submit"><i class="bx bx-save me-1" aria-hidden="true"></i>บันทึกร่าง</button><a class="btn btn-outline-secondary" href="{{ route('wms.inventory-adjustments.index') }}">ยกเลิก</a></div>
 </form></div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){const tbody=$('#adjustment-lines tbody'),url='{{ route('wms.inventory-adjustments.item-options') }}';function init($s){window.erpInitSelect2($s,{ajax:{url:url,delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:d=>d}});$s.on('select2:select',e=>{const d=e.params.data,u=$s.closest('tr').find('select[name$="[uom_id]"]'),label=d.base_uom_label||'ไม่พบหน่วย Stock';u.empty().append(new Option(label,d.base_uom_id,true,true));});}$('.js-adjustment-item').each(function(){init($(this));});$('#add-adjustment-line').on('click',function(){let i=tbody.find('tr').length;let r=$('<tr data-index="'+i+'"><td><select class="form-select js-adjustment-item" name="lines['+i+'][item_id]" required><option value="">ค้นหาสินค้า</option></select></td><td><select class="form-select" name="lines['+i+'][uom_id]" required><option value="">หน่วย Stock</option></select></td><td><input class="form-control text-end" name="lines['+i+'][quantity]" type="number" min="0.00000001" step="any" required></td><td><input class="form-control text-end" name="lines['+i+'][value]" type="number" min="0.01" step="any" required></td><td><button class="btn btn-sm btn-app-danger js-remove-line" type="button" title="ลบรายการ" aria-label="ลบรายการ"><i class="bx bx-trash" aria-hidden="true"></i></button></td></tr>');tbody.append(r);init(r.find('.js-adjustment-item'));});tbody.on('click','.js-remove-line',function(){if(tbody.find('tr').length>1)$(this).closest('tr').remove();});window.erpAjaxForm({form:'#adjustment-document-form',url:$('#adjustment-document-form').attr('action'),method:'{{ $editing ? 'PUT' : 'POST' }}',redirect:true});});</script>
@endpush
