@extends('Wms::layout')
@php($wmsDecimal = \App\Modules\Wms\Support\WmsDecimal::class)
@php($statusLabels=['DRAFT'=>'ร่าง','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','VOID'=>'ยกเลิก','REVERSED'=>'กลับรายการแล้ว'])
@php($statusClasses=['DRAFT'=>'neutral','APPROVED'=>'info','POSTED'=>'success','VOID'=>'danger','REVERSED'=>'warning'])
@php($directionLabels=['GAIN'=>'เพิ่มสินค้า','LOSS'=>'ลดสินค้า']) @php($events=['wms.inventory_adjustment.created'=>'สร้างร่างเอกสาร','wms.inventory_adjustment.updated'=>'แก้ไขร่างเอกสาร','wms.inventory_adjustment.approved'=>'อนุมัติเอกสาร','wms.inventory_adjustment.posted'=>'ลงบัญชีเอกสาร','wms.inventory_adjustment.deleted'=>'ลบร่างเอกสาร','wms.inventory_adjustment.reversed'=>'กลับรายการเอกสาร','wms.inventory_adjustment.document_reversed'=>'กลับรายการทั้งเอกสาร'])
@section('title','รายละเอียด Adjustment | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><p class="eyebrow mb-2">WMS / INVENTORY ADJUSTMENT</p><h1 class="h3 mb-2">{{ $document->document_number }}</h1><p class="text-secondary mb-0">ปรับปรุงสินค้าคงเหลือ · {{ $document->warehouse?->code }} · {{ $document->document_date?->format($dateFormat) }}</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ route('wms.inventory-adjustments.index') }}" title="กลับรายการ" aria-label="กลับรายการ"><i class="bx bx-arrow-back" aria-hidden="true"></i></a>@if($document->status==='DRAFT' && auth()->user()->hasPermission('wms.inventory-adjustments.update'))<a class="btn btn-app-soft" href="{{ route('wms.inventory-adjustments.documents.edit',$document) }}" title="แก้ไข" aria-label="แก้ไข"><i class="bx bx-edit" aria-hidden="true"></i></a>@endif @if($document->status==='DRAFT' && auth()->user()->hasPermission('wms.inventory-adjustments.approve'))<button class="btn btn-app-soft js-doc-action" data-action="approve" title="อนุมัติ" aria-label="อนุมัติ"><i class="bx bx-check" aria-hidden="true"></i></button>@endif @if($document->status==='APPROVED' && config('erp.inventory.adjustment_posting_enabled',false) && auth()->user()->hasPermission('wms.inventory-adjustments.post'))<button class="btn btn-app-soft js-doc-action" data-action="post" title="ลงบัญชี" aria-label="ลงบัญชี"><i class="bx bx-send" aria-hidden="true"></i></button>@endif @if($document->status==='POSTED' && $document->reversal_status !== 'REVERSED' && config('erp.inventory.adjustment_posting_enabled',false) && auth()->user()->hasPermission('wms.inventory-adjustments.reverse'))<button class="btn btn-app-danger js-doc-reverse" title="กลับรายการทั้งเอกสาร" aria-label="กลับรายการทั้งเอกสาร"><i class="bx bx-revision" aria-hidden="true"></i></button>@endif</div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex flex-wrap gap-2 mb-3"><span class="badge app-status-{{ $statusClasses[$document->status] ?? 'neutral' }}">{{ $statusLabels[$document->status] ?? $document->status }}</span><span class="badge app-status-neutral">{{ $document->lines->count() }} รายการ</span></div><div class="row g-3"><div class="col-md-3"><small class="text-secondary d-block">วันที่เอกสาร</small><strong>{{ $document->document_date?->format($dateFormat) }}</strong></div><div class="col-md-3"><small class="text-secondary d-block">คลังสินค้า</small><strong>{{ $document->warehouse?->code }} · {{ $document->warehouse?->name }}</strong></div><div class="col-md-6"><small class="text-secondary d-block">เหตุผล</small><strong>{{ $document->reason }}</strong></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">รายการสินค้า</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>สินค้า</th><th>ทิศทาง</th><th>หน่วย</th><th class="text-end">จำนวน</th><th class="text-end">มูลค่า</th><th>สถานะ</th></tr></thead><tbody>@foreach($document->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->item?->code }} · {{ $line->item?->name }}</td><td class="{{ $line->direction==='GAIN'?'text-success':'text-danger' }}">{{ $directionLabels[$line->direction] ?? $line->direction }}</td><td>{{ $line->uom?->code }}</td><td class="text-end">{{ $wmsDecimal::format($line->quantity) }}</td><td class="text-end">{{ $wmsDecimal::format($line->value) }}</td><td><span class="badge app-status-{{ $statusClasses[$line->status] ?? 'neutral' }}">{{ $statusLabels[$line->status] ?? $line->status }}</span></td></tr>@endforeach</tbody></table></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Stock Movement / Cost Allocation / Journal</h2><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>สินค้า</th><th>Movement</th><th>Cost Allocation</th><th>Journal</th></tr></thead><tbody>@foreach($document->lines as $line)<tr><td>{{ $line->item?->code }}</td><td>{{ $line->movement?->source_reference ?? 'ยังไม่มี' }}</td><td>{{ $line->allocation?->method ?? 'ยังไม่มี' }} @if($line->allocation) · {{ $wmsDecimal::format($line->allocation->value) }} @endif</td><td>{{ $line->allocation?->journalEntry?->entry_number ?? 'ยังไม่มี' }}</td></tr>@endforeach</tbody></table></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{ $event->created_at?->format($dateFormat.' H:i') }}</div><div><strong>{{ $events[$event->action] ?? $event->action }}</strong><div class="small text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">เหตุผล:</span> {{ $event->reason }}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติ</p>@endforelse</div></div></div>
@endsection
@push('scripts')<script>$(function(){$('.js-doc-action').on('click',function(){const b=$(this),a=b.data('action'),u=a==='approve'?'{{ route('wms.inventory-adjustments.documents.approve',$document) }}':'{{ route('wms.inventory-adjustments.documents.post',$document) }}';Swal.fire({icon:'warning',title:a==='approve'?'อนุมัติ Adjustment?':'ลงบัญชี Adjustment?',showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ยกเลิก'}).then(x=>{if(!x.isConfirmed)return;$.post(u,{_token:$('meta[name=csrf-token]').attr('content')}).done(r=>{Swal.fire({icon:'success',text:r.msg,timer:1200,showConfirmButton:false}).then(()=>location.reload())}).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ดำเนินการไม่สำเร็จ'}));});});$('.js-doc-reverse').on('click',function(){Swal.fire({icon:'warning',title:'กลับรายการทั้งเอกสาร?',input:'textarea',inputPlaceholder:'เหตุผลอย่างน้อย 10 ตัวอักษร',showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ยกเลิก',preConfirm:v=>{if(!v||v.trim().length<10){Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร');return false;}return v;}}).then(x=>{if(!x.isConfirmed)return;$.post('{{ route('wms.inventory-adjustments.documents.reverse',$document) }}',{_token:$('meta[name=csrf-token]').attr('content'),reversal_date:'{{ now()->format('Y-m-d') }}',reason:x.value}).done(r=>{Swal.fire({icon:'success',text:r.msg,timer:1200,showConfirmButton:false}).then(()=>location.reload())}).fail(e=>Swal.fire({icon:'error',text:e.responseJSON?.message||'กลับรายการไม่สำเร็จ'}));});});});</script>@endpush
