@extends('Asset::layout')
@section('title', 'สร้าง'.$documentLabel.' | New ERP')
@section('content')
    @php($isManual = old('source_type', request('source_type')) === 'MANUAL_RECLASS')
    <div class="container-fluid px-3 px-lg-4 py-4"><div class="mb-4"><p class="eyebrow mb-2">ASSET / {{ $isAddition ? 'ADDITION' : 'CAPITALIZATION' }}</p><h1 class="h3 mb-2">สร้าง{{ $documentLabel }}</h1><p class="text-secondary mb-0">{{ $isAddition ? 'เพิ่มต้นทุนของสินทรัพย์ Active จากใบแจ้งหนี้ซื้อหรือบัญชีพักสินทรัพย์' : 'รับรู้จากใบแจ้งหนี้ซื้อ หรือโอนจากบัญชีพัก/ค่าใช้จ่ายสำหรับสินทรัพย์ที่เพิ่มเอง' }}</p></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-4 p-md-5"><form id="capitalization-form" action="{{ route($routePrefix.'.store') }}" method="post" novalidate>@csrf
            <div class="row g-3">
                <div class="col-12 col-md-4"><label class="form-label" for="document_date">วันที่เอกสาร <span class="text-danger">*</span></label><input class="form-control" id="document_date" name="document_date" type="date" value="{{ old('document_date', today()->toDateString()) }}" required><div class="invalid-feedback" data-error-for="document_date"></div></div>
                <div class="col-12 col-md-4"><label class="form-label" for="source_type">ที่มาของการรับรู้ <span class="text-danger">*</span></label><select class="form-select" id="source_type" name="source_type" required><option value="PURCHASE_DOCUMENT" @selected(! $isManual)>ใบแจ้งหนี้ซื้อ</option><option value="MANUAL_RECLASS" @selected($isManual)>สินทรัพย์เพิ่มเอง / ตั้งทุนใหม่</option></select><div class="form-text">ยอดยกมาก่อนใช้ระบบให้ใช้ Opening Balance เพื่อไม่สร้าง GL ซ้ำ</div></div>
                <div class="col-12 col-md-4"><label class="form-label" for="description">หมายเหตุ <span class="text-danger js-description-required {{ $isManual ? '' : 'd-none' }}">*</span></label><input class="form-control" id="description" name="description" minlength="10" maxlength="500" value="{{ old('description') }}"><div class="invalid-feedback" data-error-for="description"></div></div>
                <div class="col-12 {{ $isManual ? 'd-none' : '' }}" id="purchase-source-wrap"><label class="form-label" for="source_line">รายการต้นทางจากใบแจ้งหนี้ซื้อ <span class="text-danger">*</span></label><select class="form-select" id="source_line"><option value="">ค้นหาและเลือกรายการต้นทาง</option></select><input type="hidden" name="source_id" id="source_id"><div class="form-text">แสดงเฉพาะ Item ที่ตั้งค่าให้รับรู้เป็นสินทรัพย์</div><div class="invalid-feedback" data-error-for="lines.0.source_line_id"></div></div>
                <div class="col-12 {{ $isManual ? '' : 'd-none' }}" id="manual-reclass-help"><div class="alert alert-info mb-0"><i class="bx bx-info-circle me-1" aria-hidden="true"></i>เลือกบัญชีเครดิตในแต่ละบรรทัด เช่น บัญชีพักสินทรัพย์หรือบัญชีค่าใช้จ่ายที่เคยบันทึกไว้ ระบบจะสร้าง Dr สินทรัพย์ / Cr บัญชีที่เลือก เมื่อ Post</div></div>
                @if(auth()->user()->hasPermission('asset.capitalizations.exception'))<div class="col-12" id="manual-exception-wrap"><input type="hidden" name="is_manual_exception" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" id="is_manual_exception" name="is_manual_exception" value="1"><label class="form-check-label" for="is_manual_exception">ใช้ข้อยกเว้นสำหรับรายการซื้อที่ไม่ได้ตั้งค่าใน Item Master</label></div><div class="mt-2 d-none" id="manual-exception-reason"><label class="form-label" for="manual_exception_reason">เหตุผลข้อยกเว้น <span class="text-danger">*</span></label><textarea class="form-control" id="manual_exception_reason" name="manual_exception_reason" minlength="10" maxlength="500"></textarea></div></div>@else<input type="hidden" name="is_manual_exception" value="0">@endif
            </div>
            <hr class="my-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">{{ $isAddition ? 'รายการเพิ่มมูลค่า' : 'รายการรับรู้' }} <span class="text-danger">*</span></h2><p class="text-secondary small mb-0">เลือกสินทรัพย์{{ $isAddition ? 'ที่ Active' : 'ร่าง' }}และระบุต้นทุนที่จะ{{ $isAddition ? 'เพิ่ม' : 'รับรู้' }}</p></div><button class="btn btn-outline-dark btn-sm" type="button" id="add-line"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มรายการ</button></div>
            <div class="table-responsive"><table class="table align-middle" id="capitalization-lines"><thead><tr><th>สินทรัพย์ <span class="text-danger">*</span></th><th class="text-end">ต้นทุนรับรู้ <span class="text-danger">*</span></th><th><span class="js-clearing-label">บัญชีเครดิต</span> <span class="text-danger js-clearing-required d-none">*</span></th><th>รายละเอียด</th><th></th></tr></thead><tbody></tbody><tfoot><tr><th>รวม</th><th class="text-end" id="total-cost">0.00</th><th colspan="3"></th></tr></tfoot></table></div>
            <div class="d-flex justify-content-between mt-4"><a class="btn btn-outline-dark" href="{{ route($routePrefix.'.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับ</a><button class="btn btn-dark" type="submit" data-busy-text="กำลังบันทึก..."><i class="bx bx-save me-1" aria-hidden="true"></i>บันทึกร่าง</button></div>
        </form></div></div></div>
@endsection
@push('scripts')
<script>
$(function () {
    var $body=$('#capitalization-lines tbody'),line=0,source=null,manualAsset=@json($manualAsset ? ['id'=>$manualAsset->id,'text'=>$manualAsset->asset_number.' · '.$manualAsset->name,'cost'=>$manualAsset->original_cost] : null),isAddition=@json($isAddition);
    function select($el,url,placeholder,extra){$el.select2({width:'100%',allowClear:true,placeholder:placeholder,ajax:{url:url,dataType:'json',delay:250,data:function(params){return $.extend({q:params.term||'',page:params.page||1},extra?extra():{});},processResults:function(data){return data;},cache:true}});}
    function sourceSelect(){select($('#source_line'),@json(route($routePrefix.'.sources')),'ค้นหารายการต้นทาง',function(){return {type:'PURCHASE_DOCUMENT',manual_exception:$('#is_manual_exception').is(':checked')?1:0};});$('#source_line').on('select2:select',function(e){source=e.params.data;$('#source_id').val(source.source_id||'');$body.find('.js-source-type').val('PURCHASE_DOCUMENT');$body.find('.js-source-id').val(source.source_id||'');$body.find('.js-source-line-id').val(source.source_line_id||'');if($body.children().length===1)$body.find('.js-cost').first().val(Number(source.amount||0).toFixed(2)).trigger('input');});}
    function addLine(){var i=line++;$body.append('<tr><td><select class="form-select js-asset" name="lines['+i+'][asset_id]" required><option value="">ค้นหาสินทรัพย์'+(isAddition?'ที่ใช้งานอยู่':'ร่าง')+'</option></select><input class="js-source-type" type="hidden" name="lines['+i+'][source_type]"><input class="js-source-id" type="hidden" name="lines['+i+'][source_id]"><input class="js-source-line-id" type="hidden" name="lines['+i+'][source_line_id]"><div class="invalid-feedback" data-error-for="lines.'+i+'.asset_id"></div></td><td><input class="form-control text-end js-cost" type="number" name="lines['+i+'][capitalized_cost]" min="0.01" step="0.01" required><div class="invalid-feedback" data-error-for="lines.'+i+'.capitalized_cost"></div></td><td><select class="form-select js-account" name="lines['+i+'][clearing_account_id]"><option value="">ใช้บัญชีจากต้นทาง</option></select><div class="invalid-feedback" data-error-for="lines.'+i+'.clearing_account_id"></div></td><td><input class="form-control" name="lines['+i+'][description]" maxlength="500"></td><td class="text-end"><button class="btn btn-sm btn-outline-danger js-remove" type="button" aria-label="ลบรายการ"><i class="bx bx-trash" aria-hidden="true"></i></button></td></tr>');var $row=$body.children().last();select($row.find('.js-asset'),@json(route($routePrefix.'.assets')),'ค้นหาสินทรัพย์'+(isAddition?'ที่ใช้งานอยู่':'ร่าง'),function(){return {asset_category_id:source?source.default_asset_category_id||'':''};});select($row.find('.js-account'),@json(route($routePrefix.'.accounts')),'เลือกบัญชีเครดิต');if(source){$row.find('.js-source-type').val('PURCHASE_DOCUMENT');$row.find('.js-source-id').val(source.source_id||'');$row.find('.js-source-line-id').val(source.source_line_id||'');}if(manualAsset&&$body.children().length===1){$row.find('.js-asset').append(new Option(manualAsset.text,manualAsset.id,true,true)).trigger('change');$row.find('.js-cost').val(Number(manualAsset.cost||0).toFixed(2));}}
    function total(){var sum=0;$body.find('.js-cost').each(function(){sum+=Number($(this).val()||0);});$('#total-cost').text(sum.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}));}
    function setSourceType(){var manual=$('#source_type').val()==='MANUAL_RECLASS';source=null;$('#source_id').val('');$('#source_line').val(null).trigger('change');$('#purchase-source-wrap').toggleClass('d-none',manual);$('#manual-reclass-help').toggleClass('d-none',!manual);$('#manual-exception-wrap').toggleClass('d-none',manual);$('#description').prop('required',manual);$('.js-description-required').toggleClass('d-none',!manual);$('.js-account').prop('required',manual);$('.js-clearing-required').toggleClass('d-none',!manual);$('.js-clearing-label').text(manual?'บัญชีเครดิต':'บัญชีเครดิต (หากต่างจากต้นทาง)');}
    $('#add-line').on('click',addLine);$body.on('input','.js-cost',total).on('click','.js-remove',function(){$(this).closest('tr').remove();total();});$('#is_manual_exception').on('change',function(){source=null;$('#source_id').val('');$('#source_line').val(null).trigger('change');$('#manual-exception-reason').toggleClass('d-none',!this.checked).find('textarea').prop('required',this.checked);});$('#source_type').on('change',setSourceType);sourceSelect();addLine();setSourceType();total();window.erpAjaxForm({form:'#capitalization-form',redirect:true,reload:false});
});
</script>
@endpush
