@extends('Asset::layout')
@section('title', $capitalization->document_number.' | New ERP')

@section('content')
@php
    $labels=['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'พร้อมลงบัญชี','POSTED'=>'ลงบัญชีแล้ว','REVERSED'=>'กลับรายการแล้ว','VOID'=>'ยกเลิก'];
    $classes=['DRAFT'=>'app-badge-soft','SUBMITTED'=>'app-badge-info','APPROVED'=>'app-badge-info','POSTED'=>'app-badge-success','REVERSED'=>'app-status-danger','VOID'=>'app-status-danger'];
    $total=$capitalization->lines->sum(fn($line)=>(float)$line->capitalized_cost);
    $purchase=$capitalization->source_type==='PURCHASE_DOCUMENT';
    $auditTrail=collect([['สร้างร่าง',$capitalization->created_at,$capitalization->createdBy?->name,null],['ส่งอนุมัติ',$capitalization->submitted_at,$capitalization->submittedBy?->name,null],['อนุมัติ',$capitalization->approved_at,$capitalization->approvedBy?->name,null],['ลงบัญชี',$capitalization->posted_at,$capitalization->postedBy?->name,null],['ยกเลิก',$capitalization->voided_at,$capitalization->voidedBy?->name,$capitalization->void_reason],['กลับรายการ',$capitalization->reversed_at,$capitalization->reversedBy?->name,$capitalization->reversal_reason]])->filter(fn($event)=>$event[1])->sortByDesc(fn($event)=>$event[1]);
@endphp
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-xl-row justify-content-between align-items-xl-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">ASSET / CAPITALIZATION</p><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><h1 class="h3 mb-0">{{ $capitalization->document_number }}</h1><span class="badge {{ $classes[$capitalization->status] ?? 'app-status-neutral' }}">{{ $labels[$capitalization->status] ?? $capitalization->status }}</span></div><p class="text-secondary mb-0"><i class="bx {{ $purchase?'bx-receipt':'bx-import' }} me-1"></i>{{ $purchase?'Purchase Invoice':'Opening Balance' }} · วันที่เอกสาร {{ $capitalization->document_date?->format('d/m/Y') }}</p></div>
        <div class="d-flex flex-wrap gap-2">
            @if($capitalization->status==='DRAFT' && auth()->user()->hasPermission('asset.capitalizations.create'))<button class="btn btn-outline-danger js-delete-capitalization" type="button" data-url="{{route('asset.capitalizations.destroy',$capitalization)}}"><i class="bx bx-trash me-1"></i>ลบ</button>@endif
            @if($capitalization->status==='DRAFT' && auth()->user()->hasPermission('asset.capitalizations.submit'))<button class="btn btn-dark js-action" data-url="{{route('asset.capitalizations.submit',$capitalization)}}" data-confirm="ส่งใบรับรู้เพื่ออนุมัติ?"><i class="bx bx-send me-1"></i>ส่งอนุมัติ</button>@endif
            @if($capitalization->status==='SUBMITTED' && auth()->user()->hasPermission('asset.capitalizations.approve'))<button class="btn btn-primary js-action" data-url="{{route('asset.capitalizations.approve',$capitalization)}}" data-confirm="อนุมัติใบรับรู้นี้?"><i class="bx bx-check me-1"></i>อนุมัติ</button>@endif
            @if(in_array($capitalization->status,['SUBMITTED','APPROVED'],true) && auth()->user()->hasPermission('asset.capitalizations.approve'))<button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#void-modal"><i class="bx bx-x-circle me-1"></i>ยกเลิก</button>@endif
            @if($capitalization->status==='APPROVED' && auth()->user()->hasPermission('asset.capitalizations.post'))<button class="btn btn-success js-action" data-url="{{route('asset.capitalizations.post',$capitalization)}}" data-confirm="ลงบัญชีและเปิดใช้งานสินทรัพย์? การดำเนินการนี้แก้ไขโดยตรงไม่ได้"><i class="bx bx-book-open me-1"></i>ลงบัญชี</button>@endif
            @if($capitalization->status==='POSTED' && auth()->user()->hasPermission('asset.capitalizations.reverse'))<button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#reverse-modal"><i class="bx bx-revision me-1"></i>กลับรายการ</button>@endif
            <a class="btn btn-outline-dark" href="{{route('asset.capitalizations.index')}}"><i class="bx bx-arrow-back me-1"></i>รายการทั้งหมด</a>
        </div>
    </div>
    @if($capitalization->is_manual_exception)<div class="alert alert-warning border-0 shadow-sm d-flex gap-2 mb-4"><i class="bx bx-error-circle fs-5"></i><div><strong>ใช้ข้อยกเว้น Item Master</strong><div class="small mt-1">{{ $capitalization->manual_exception_reason }}</div></div></div>@endif
    <div class="row g-3 mb-4"><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="small text-secondary mb-1">ต้นทุนรับรู้รวม</div><div class="fs-3 fw-semibold">{{number_format($total,2)}}</div><div class="small text-secondary mt-1">{{$capitalization->lines->count()}} สินทรัพย์</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="small text-secondary mb-1">แหล่งต้นทุน</div><div class="fw-semibold"><i class="bx {{$purchase?'bx-receipt':'bx-import'}} me-1"></i>{{$purchase?'Purchase Invoice':'Opening Balance'}}</div><div class="small text-secondary mt-1">เลขที่อ้างอิง #{{$capitalization->source_id ?: '-'}}</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="small text-secondary mb-1">Journal Entry</div><div class="fw-semibold">{{$capitalization->journalEntry?->entry_number ?? 'รอลงบัญชี'}}</div><div class="small text-secondary mt-1">{{$capitalization->posted_at?->format('d/m/Y H:i') ?? 'ยังไม่มีการ Post'}}</div></div></div></div></div>
    @if($capitalization->description)<div class="card border-0 shadow-sm mb-4"><div class="card-body py-3"><div class="small text-secondary mb-1">หมายเหตุ</div>{{$capitalization->description}}</div></div>@endif
    <div class="row g-4"><div class="col-12 col-xl-8"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white border-0 d-flex justify-content-between align-items-center py-3 px-3 px-lg-4"><div><h2 class="h5 mb-1">รายการรับรู้ต้นทุน</h2><p class="small text-secondary mb-0">ต้นทุนที่จะเปลี่ยนเป็นมูลค่าทางบัญชีของแต่ละ Asset</p></div><span class="badge app-status-neutral">{{$capitalization->lines->count()}} รายการ</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-3 ps-lg-4">Asset</th><th>หมวด</th><th>บัญชีเครดิต</th><th>รายละเอียด</th><th class="text-end pe-3 pe-lg-4">ต้นทุนรับรู้</th></tr></thead><tbody>@forelse($capitalization->lines as $line)<tr><td class="ps-3 ps-lg-4"><a class="text-decoration-none fw-semibold" href="{{route('asset.assets.show',$line->asset)}}">{{$line->asset?->asset_number}}</a><div class="small text-secondary">{{$line->asset?->name}}</div></td><td>{{$line->asset?->category?->name ?? '-'}}</td><td class="small">{{$line->clearingAccount ? $line->clearingAccount->code.' · '.$line->clearingAccount->name : 'ใช้บัญชีจากต้นทาง'}}</td><td class="text-secondary">{{$line->description ?: '-'}}</td><td class="text-end fw-semibold pe-3 pe-lg-4">{{number_format((float)$line->capitalized_cost,2)}}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">ไม่มีรายการรับรู้</td></tr>@endforelse</tbody><tfoot class="table-light"><tr><th colspan="4" class="text-end ps-3">รวมต้นทุน</th><th class="text-end pe-3 pe-lg-4">{{number_format($total,2)}}</th></tr></tfoot></table></div></div></div>
    <div class="col-12 col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="h5 mb-1">สถานะเอกสาร</h2><p class="small text-secondary mb-0">ติดตามลำดับการทำงาน</p></div><i class="bx bx-git-branch fs-4 text-secondary"></i></div>@foreach([['สร้างร่าง',$capitalization->created_at,'bx-file'],['ส่งอนุมัติ',$capitalization->submitted_at,'bx-send'],['อนุมัติ',$capitalization->approved_at,'bx-check-circle'],['ลงบัญชี',$capitalization->posted_at,'bx-book-open']] as [$label,$time,$icon])<div class="d-flex gap-3 {{$loop->last?'':'pb-3'}}"><div class="rounded-circle {{$time?'bg-success-subtle text-success':'bg-light text-secondary'}} d-inline-flex align-items-center justify-content-center flex-shrink-0" style="width:2rem;height:2rem"><i class="bx {{$icon}}"></i></div><div><div class="fw-semibold">{{$label}}</div><div class="small text-secondary">{{$time?->format('d/m/Y H:i') ?? 'รอดำเนินการ'}}</div></div></div>@endforeach
@if($capitalization->reversed_at)<hr><div class="alert alert-danger mb-0 py-2"><div class="fw-semibold">กลับรายการแล้ว</div><div class="small">{{$capitalization->reversed_at->format('d/m/Y H:i')}} · {{$capitalization->reversal_reason}}</div></div>@endif</div></div></div></div>
    <div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white border-0 py-3 px-3 px-lg-4"><h2 class="h5 mb-1">ประวัติการทำรายการ</h2><p class="small text-secondary mb-0">Audit Trail ของใบรับรู้สินทรัพย์นี้ · เวลาไทย (UTC+7)</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-3 ps-lg-4">วันเวลา</th><th>เหตุการณ์</th><th>ผู้ดำเนินการ</th><th class="pe-3 pe-lg-4">หมายเหตุ</th></tr></thead><tbody>@foreach($auditTrail as [$action,$occurredAt,$actor,$note])<tr><td class="ps-3 ps-lg-4 text-nowrap">{{$occurredAt->timezone('Asia/Bangkok')->format('d/m/Y H:i')}}</td><td class="fw-semibold">{{$action}}</td><td>{{$actor ?? '-'}}</td><td class="pe-3 pe-lg-4">{{$note ?? '-'}}</td></tr>@endforeach</tbody></table></div></div>
</div>
<div class="modal fade" id="reverse-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form class="modal-content" id="reverse-form" method="post" action="{{route('asset.capitalizations.reverse',$capitalization)}}">@csrf<div class="modal-header"><h2 class="modal-title h5">กลับรายการใบรับรู้</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label" for="reversal_date">วันที่กลับรายการ <span class="text-danger">*</span></label><input class="form-control" id="reversal_date" type="date" name="reversal_date" value="{{today()->toDateString()}}" required><div class="invalid-feedback" data-error-for="reversal_date"></div></div><div><label class="form-label" for="reversal_reason">เหตุผล <span class="text-danger">*</span></label><textarea class="form-control" id="reversal_reason" name="reversal_reason" maxlength="500" required></textarea><div class="invalid-feedback" data-error-for="reversal_reason"></div></div></div><div class="modal-footer"><button class="btn btn-outline-dark" type="button" data-bs-dismiss="modal">ยกเลิก</button><button class="btn btn-danger" type="submit">ยืนยันกลับรายการ</button></div></form></div></div>
<div class="modal fade" id="void-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form class="modal-content" id="void-form" method="post" action="{{route('asset.capitalizations.void',$capitalization)}}">@csrf<div class="modal-header"><h2 class="modal-title h5">ยกเลิกใบรับรู้</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body"><p class="text-secondary small">เอกสารนี้ยังไม่ลงบัญชี จึงยกเลิกได้โดยไม่สร้างรายการกลับบัญชี</p><label class="form-label" for="void_reason">เหตุผล <span class="text-danger">*</span></label><textarea class="form-control" id="void_reason" name="void_reason" minlength="10" maxlength="500" required></textarea><div class="invalid-feedback" data-error-for="void_reason"></div></div><div class="modal-footer"><button class="btn btn-outline-dark" type="button" data-bs-dismiss="modal">กลับ</button><button class="btn btn-danger" type="submit">ยืนยันยกเลิก</button></div></form></div></div>
@endsection
@push('scripts')<script>$(function(){$('.js-action').on('click',function(){var b=$(this);Swal.fire({icon:'warning',title:'ยืนยันการทำรายการ',text:b.data('confirm'),showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ยกเลิก'}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.ajax({url:b.data('url'),method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')||''}}).done(function(x){Swal.fire({icon:'success',title:x.msg}).then(function(){window.location=x.redirect||window.location.href;});}).fail(function(x){var r=x.responseJSON||{};Swal.fire({icon:'error',title:'ไม่สามารถดำเนินการได้',text:r.msg||r.message||'กรุณาลองใหม่'});}).always(function(){b.prop('disabled',false);});});});window.erpAjaxDelete({button:'.js-delete-capitalization',redirect:@json(route('asset.capitalizations.index')),confirm:'ยืนยันการลบใบรับรู้สินทรัพย์ร่างนี้หรือไม่?'});window.erpAjaxForm({form:'#reverse-form',redirect:true,reload:false});window.erpAjaxForm({form:'#void-form',redirect:true,reload:false});});</script>@endpush
