@extends('Finance::layout')
@section('title', $clearing->document_number.' | Finance')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">FINANCE / EMPLOYEE ADVANCE</p><h1 class="h3 mb-1">{{ $clearing->document_number }}</h1><span class="badge {{ $classes[$clearing->status] ?? 'app-status-neutral' }}">{{ $labels[$clearing->status] ?? $clearing->status }}</span></div>
        <div class="d-flex flex-wrap gap-2">
            <a class="btn btn-outline-secondary" href="{{ route('finance.employee-advance-clearings.index') }}">กลับ</a>
            @if($clearing->status==='DRAFT' && auth()->user()->hasPermission('finance.employee-advance-clearings.update'))<a class="btn btn-outline-dark" href="{{ route('finance.employee-advance-clearings.edit',$clearing) }}">แก้ไขใบเคลียร์</a><form method="POST" action="{{ route('finance.employee-advance-clearings.destroy',$clearing) }}" class="d-inline" onsubmit="event.preventDefault(); var form=this; Swal.fire({icon:'warning',title:'ลบเอกสาร Draft?',text:'เอกสารจะถูกลบออกจากรายการ',showCancelButton:true,confirmButtonText:'ลบเอกสาร',cancelButtonText:'ยกเลิก',confirmButtonColor:'#dc3545'}).then(function(result){if(!result.isConfirmed)return; $.ajax({url:form.action,method:'DELETE',data:{_token:$('meta[name=csrf-token]').attr('content')},headers:{Accept:'application/json'}}).done(function(response){Swal.fire({icon:'success',text:response.msg||'ลบเอกสารแล้ว'}).then(function(){window.location.href=response.redirect;});}).fail(function(xhr){Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ไม่สามารถลบเอกสารได้'});});});">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">ลบ Draft</button></form>@endif
            @if($clearing->journalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-app-soft" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show',$clearing->journalEntry) }}">ดู GL</button>@endif
            @if($clearing->reversalJournalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-outline-danger" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show',$clearing->reversalJournalEntry) }}">ดู GL ยกเลิก</button>@endif
            @if($clearing->status==='DRAFT' && auth()->user()->hasPermission('finance.employee-advance-clearings.submit'))<button class="btn btn-dark js-action" data-url="{{ route('finance.employee-advance-clearings.submit',$clearing) }}">ส่งอนุมัติ</button>@endif
            @if($clearing->status==='SUBMITTED' && auth()->user()->hasPermission('finance.employee-advance-clearings.approve'))<button class="btn btn-dark js-action" data-url="{{ route('finance.employee-advance-clearings.approve',$clearing) }}">อนุมัติ</button><button class="btn btn-outline-danger js-void" data-url="{{ route('finance.employee-advance-clearings.reject',$clearing) }}">ไม่อนุมัติ</button>@endif
            @if($clearing->status==='APPROVED' && auth()->user()->hasPermission('finance.employee-advance-clearings.post'))<button class="btn btn-dark js-action" data-url="{{ route('finance.employee-advance-clearings.post',$clearing) }}">ลงบัญชี</button>@endif
            @if($clearing->status==='CLEARED' && auth()->user()->hasPermission('finance.employee-advance-clearings.reverse'))<button class="btn btn-outline-danger js-reverse" data-url="{{ route('finance.employee-advance-clearings.reverse',$clearing) }}">ยกเลิกรายการ</button>@endif
            @if(in_array($clearing->status,['SUBMITTED','APPROVED'],true) && auth()->user()->hasPermission('finance.employee-advance-clearings.void'))<button class="btn btn-outline-danger js-void" data-url="{{ route('finance.employee-advance-clearings.void',$clearing) }}">ยกเลิก</button>@endif
        </div>
    </div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-4"><div class="col-md-3"><div class="small text-secondary">ใบเงินทดรอง</div><strong>{{ $clearing->advance?->document_number ?: '—' }}</strong><div>{{ $clearing->advance?->employee?->name ?: '—' }}</div></div><div class="col-md-3"><div class="small text-secondary">วันที่เอกสาร</div>{{ $clearing->document_date?->format('d/m/Y') ?: '—' }}</div><div class="col-md-3"><div class="small text-secondary">ค่าใช้จ่ายสุทธิ</div><strong>{{ number_format((float)$clearing->net_expense_amount,2) }}</strong></div><div class="col-md-3"><div class="small text-secondary">เงินคืน / เบิกเพิ่ม</div>{{ number_format((float)$clearing->refund_amount,2) }} / {{ number_format((float)$clearing->additional_amount,2) }}</div><div class="col-12"><div class="small text-secondary">รายละเอียด</div>{{ $clearing->description ?: '—' }}</div>@if($clearing->status === 'REVERSED' && $clearing->reversal_reason)<div class="col-12"><div class="small text-secondary">เหตุผลยกเลิกรายการ</div><div class="text-danger">{{ $clearing->reversal_reason }}</div></div>@endif</div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">รายการค่าใช้จ่าย</h2><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>#</th><th>หมวดค่าใช้จ่าย</th><th>รายละเอียด</th><th>ใบเสร็จ</th><th class="text-end">ฐาน</th><th class="text-end">VAT</th><th class="text-end">WHT</th></tr></thead><tbody>@forelse($clearing->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->expense_category_code }} · {{ $line->expense_category_name }}</td><td>{{ $line->description ?: '—' }}</td><td>{{ $line->receipt_reference ?: '—' }}</td><td class="text-end">{{ number_format((float)$line->amount,2) }}</td><td class="text-end">{{ number_format((float)$line->tax_amount,2) }}</td><td class="text-end">{{ number_format((float)$line->withholding_amount,2) }}</td></tr>@empty<tr><td colspan="7" class="text-center text-secondary">ยังไม่มีรายการ</td></tr>@endforelse</tbody></table></div></div></div>
    @include('Finance::partials.petty-cash-attachments', ['subject' => $clearing, 'subjectType' => 'EMPLOYEE_ADVANCE_CLEARING'])
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{ $event->created_at?->format('d/m/Y H:i') }}</div><div><strong>{{ $event->action }}</strong><div class="small text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">รายละเอียด:</span> {{ $event->reason }}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติเอกสาร</p>@endforelse</div></div>
</div>
@endsection
@push('scripts')<script>$(function(){function send($b,data){$.ajax({url:$b.data('url'),method:'POST',data:$.extend({_token:$('meta[name="csrf-token"]').attr('content')},data||{}),headers:{Accept:'application/json'}}).done(function(x){Swal.fire({icon:'success',text:x.msg}).then(function(){location.reload();});}).fail(function(x){Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถดำเนินการได้'});});}$('.js-action').on('click',function(){var b=$(this);Swal.fire({icon:'question',text:'ยืนยันการดำเนินการ?',showCancelButton:true}).then(function(r){if(r.isConfirmed)send(b);});});$('.js-void,.js-reverse').on('click',function(){var b=$(this),reverse=b.hasClass('js-reverse');Swal.fire({input:'textarea',inputLabel:'เหตุผล',showCancelButton:true,preConfirm:function(v){if(!$.trim(v||'')){Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร');return false;}return v;}}).then(function(r){if(r.isConfirmed)send(b,{reason:r.value,reversal_date:reverse?new Date().toISOString().slice(0,10):undefined});});});});</script>@endpush
