@forelse($items as $interest)
@php
    $info=($commercial??[])[$interest->id]??[];$available=(string)($info['available']??'0');
    $stockShort=function_exists('bccomp')?bccomp($available,(string)$interest->quantity,6)<0:(float)$available<(float)$interest->quantity;
@endphp
<article class="crm-product-interest border rounded-3 p-3 mb-2">
    <div class="d-flex justify-content-between gap-2"><div class="min-w-0"><strong class="text-break">{{ $interest->item?->code }} · {{ $interest->item?->name }}</strong><div class="small text-secondary">{{ \App\Modules\Wms\Support\WmsDecimal::format($interest->quantity) }} {{ $interest->uom?->code?:$interest->uom?->name }}</div></div>@if(auth()->user()->hasPermission('crm.opportunities.update')&&!in_array($opportunity->stage,['WON','LOST'],true))<div class="d-flex gap-1"><button class="btn btn-sm btn-app-soft js-edit-interest" type="button" title="แก้ไข" aria-label="แก้ไข" data-id="{{ $interest->id }}" data-item-id="{{ $interest->item_id }}" data-item-text="{{ $interest->item?->code }} · {{ $interest->item?->name }}" data-uom-id="{{ $interest->uom_id }}" data-uom-label="{{ $interest->uom?->code }} · {{ $interest->uom?->name }}" data-quantity="{{ \App\Modules\Wms\Support\WmsDecimal::input($interest->quantity) }}" data-target-price="{{ \App\Modules\Wms\Support\WmsDecimal::input($interest->target_unit_price) }}" data-budget="{{ \App\Modules\Wms\Support\WmsDecimal::input($interest->budget_amount) }}" data-requirements="{{ $interest->requirements }}"><i class="bx bx-edit" aria-hidden="true"></i></button><button class="btn btn-sm btn-app-danger js-delete-interest" type="button" title="ลบ" aria-label="ลบ" data-id="{{ $interest->id }}"><i class="bx bx-trash" aria-hidden="true"></i></button></div>@endif</div>
    <div class="row g-2 mt-2"><div class="col-6"><small class="text-secondary d-block">ราคาเป้าหมาย/หน่วย</small><span>{{ $interest->target_unit_price!==null?\App\Modules\Wms\Support\WmsDecimal::format($interest->target_unit_price).' บาท':'-' }}</span></div><div class="col-6"><small class="text-secondary d-block">งบประมาณ</small><span>{{ $interest->budget_amount!==null?\App\Modules\Wms\Support\WmsDecimal::format($interest->budget_amount).' บาท':'-' }}</span></div>@if($interest->requirements)<div class="col-12"><small class="text-secondary d-block">ความต้องการ</small><span class="text-break">{{ $interest->requirements }}</span></div>@endif</div>
    <div class="crm-interest-commercial row g-2 mt-2"><div class="col-12 col-md-4"><div class="h-100 rounded-3 p-2 bg-light"><small class="text-secondary d-block">ราคาขายมาตรฐาน</small>@if($price=$info['price']??null)<strong>{{ \App\Modules\Wms\Support\WmsDecimal::format($price['unit_price']) }} {{ $price['currency'] }}</strong><small class="d-block text-secondary">Price List {{ $price['price_list_code'] }}@if((float)($price['discount_percent']??0)>0) · ลด {{ \App\Modules\Wms\Support\WmsDecimal::format($price['discount_percent']) }}%@endif</small>@else<span class="text-secondary">ยังไม่พบราคาที่ใช้ได้</span>@endif</div></div><div class="col-12 col-md-4"><div class="h-100 rounded-3 p-2 bg-light"><small class="text-secondary d-block">Promotion ที่แนะนำ</small>@if($promotion=$info['promotion']??null)<strong>{{ $promotion['promotion_code'] }}</strong><small class="d-block text-secondary">ราคา {{ \App\Modules\Wms\Support\WmsDecimal::format($promotion['unit_price']) }} {{ $promotion['currency'] }}</small>@else<span class="text-secondary">ไม่มี Promotion ที่ใช้ได้</span>@endif</div></div><div class="col-12 col-md-4"><div class="h-100 rounded-3 p-2 {{ $stockShort?'app-status-warning':'bg-light' }}"><small class="text-secondary d-block">Stock พร้อมใช้รวมในสาขา</small><strong>{{ \App\Modules\Wms\Support\WmsDecimal::format($available) }} {{ $interest->uom?->code }}</strong>@if($stockShort)<small class="d-block">ต่ำกว่าจำนวนที่สนใจ</small>@endif</div></div></div>
    <div class="small text-secondary mt-2"><i class="bx bx-info-circle me-1" aria-hidden="true"></i>ข้อมูลราคา Promotion และ Stock ณ {{ $info['as_of']??'-' }} เป็นข้อมูลประมาณการและยังไม่จอง Stock</div>
</article>
@empty<div class="text-center text-secondary py-4">ยังไม่มีสินค้าที่ลูกค้าสนใจ</div>@endforelse
