@extends('Crm::layout')
@php($editing = $opportunity->exists)
@section('title', ($editing ? 'แก้ไข' : 'สร้าง').'โอกาสการขาย | CRM')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4 crm-page-header"><div><p class="eyebrow mb-2">CRM / OPPORTUNITY</p><h1 class="h3 mb-1">{{ $editing ? 'แก้ไขโอกาสการขาย' : 'สร้างโอกาสการขาย' }}</h1><p class="text-secondary mb-0">บันทึกข้อมูลเท่าที่มี แล้วกำหนดงานถัดไปเพื่อไม่ให้ลูกค้าหลุดจากการติดตาม</p></div><a class="btn btn-outline-secondary" href="{{ $editing ? route('crm.opportunities.show',$opportunity) : route('crm.opportunities.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a></div>

    <form id="opportunity-form" method="post" action="{{ $editing ? route('crm.opportunities.update',$opportunity) : route('crm.opportunities.store') }}">@csrf @if($editing)@method('PUT')@endif
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ข้อมูลลูกค้าเป้าหมาย</h2><div class="row g-3">
            <div class="col-12"><label class="form-label" for="title">ชื่อโอกาสการขาย <span class="text-danger">*</span></label><input class="form-control" id="title" name="title" maxlength="255" value="{{ old('title',$opportunity->title) }}" placeholder="เช่น โครงการติดตั้งระบบสาขาใหม่" required><div class="invalid-feedback" data-error-for="title"></div></div>
            <div class="col-12"><label class="form-label" for="party_id">ลูกค้าในระบบ</label><select class="form-select" id="party_id" name="party_id" data-url="{{ route('crm.opportunities.customer-options') }}"><option value="">ยังไม่ผูกลูกค้า</option>@if($party)<option value="{{ $party->id }}" selected>{{ $party->code }} · {{ $party->name }}</option>@endif</select><div class="form-text">ผูกลูกค้าเมื่อพร้อมสร้างเอกสารต่อใน POS</div><div class="invalid-feedback" data-error-for="party_id"></div></div>
            <div class="col-12 col-md-4"><label class="form-label" for="contact_name">ผู้ติดต่อ</label><input class="form-control" id="contact_name" name="contact_name" maxlength="255" value="{{ old('contact_name',$opportunity->contact_name) }}"></div>
            <div class="col-12 col-sm-6 col-md-4"><label class="form-label" for="phone">โทรศัพท์</label><input class="form-control" id="phone" name="phone" type="tel" inputmode="tel" maxlength="50" value="{{ old('phone',$opportunity->phone) }}"></div>
            <div class="col-12 col-sm-6 col-md-4"><label class="form-label" for="email">อีเมล</label><input class="form-control" id="email" name="email" type="email" maxlength="255" value="{{ old('email',$opportunity->email) }}"></div>
            <div class="col-12 col-md-6"><label class="form-label" for="source">แหล่งที่มา</label><input class="form-control" id="source" name="source" maxlength="100" value="{{ old('source',$opportunity->source) }}" placeholder="เช่น Facebook, Website, ลูกค้าแนะนำ"></div>
            <div class="col-12 col-md-6"><label class="form-label" for="owner_id">ผู้รับผิดชอบ <span class="text-danger">*</span></label><select class="form-select" id="owner_id" name="owner_id" data-url="{{ route('crm.opportunities.owner-options') }}" required>@if($owner)<option value="{{ $owner->id }}" selected>{{ $owner->employee_code ? $owner->employee_code.' · ' : '' }}{{ $owner->name }}</option>@endif</select><div class="form-text">ค้นหาและเลือกสร้างแทนพนักงานขายคนอื่นได้ งานจะอยู่ในรายการของผู้รับผิดชอบที่เลือก</div></div>
        </div></div></div>

        <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">Pipeline และงานถัดไป</h2><div class="row g-3">
            <div class="col-12 col-md-4"><label class="form-label" for="stage">ขั้นตอน <span class="text-danger">*</span></label><select class="form-select" id="stage" name="stage" required>@foreach($stages as $code=>$stage)<option value="{{ $code }}" data-probability="{{ $stage['probability'] }}" @selected(old('stage',$opportunity->stage)===$code)>{{ $stage['label'] }}</option>@endforeach</select></div>
            <div class="col-6 col-md-4"><label class="form-label" for="expected_value">มูลค่าคาดการณ์</label><input class="form-control text-end" id="expected_value" name="expected_value" type="number" min="0" step="0.01" value="{{ old('expected_value',$opportunity->expected_value) }}" required></div>
            <div class="col-6 col-md-4"><label class="form-label" for="probability">โอกาสสำเร็จ (%)</label><input class="form-control text-end" id="probability" name="probability" type="number" min="0" max="100" step="1" value="{{ old('probability',$opportunity->probability) }}" required></div>
            <div class="col-12 col-md-6"><label class="form-label" for="expected_close_date">วันที่คาดว่าจะปิด</label><input class="form-control" id="expected_close_date" name="expected_close_date" type="date" value="{{ old('expected_close_date',$opportunity->expected_close_date?->format('Y-m-d')) }}"></div>
            <div class="col-12 col-md-6"><label class="form-label" for="next_action_at">วันเวลางานถัดไป</label><input class="form-control" id="next_action_at" name="next_action_at" type="datetime-local" value="{{ old('next_action_at',$opportunity->next_action_at?->format('Y-m-d\TH:i')) }}"></div>
            <div class="col-12"><label class="form-label" for="notes">หมายเหตุ</label><textarea class="form-control" id="notes" name="notes" rows="4" maxlength="5000">{{ old('notes',$opportunity->notes) }}</textarea></div>
            <div class="col-12 d-none" id="lost-reason-wrap"><label class="form-label" for="lost_reason">เหตุผลที่ไม่สำเร็จ <span class="text-danger">*</span></label><textarea class="form-control" id="lost_reason" name="lost_reason" rows="3" maxlength="1000">{{ old('lost_reason',$opportunity->lost_reason) }}</textarea></div>
        </div><div class="d-flex flex-wrap gap-2 mt-4 crm-form-actions"><button class="btn btn-app-primary" type="submit"><i class="bx bx-save me-1" aria-hidden="true"></i>{{ $editing ? 'บันทึกการแก้ไข' : 'บันทึกโอกาสการขาย' }}</button><a class="btn btn-outline-secondary" href="{{ $editing ? route('crm.opportunities.show',$opportunity) : route('crm.opportunities.index') }}">ยกเลิก</a></div></div></div>
    </form>
</div>
@endsection
@push('scripts')
<script>$(function(){const party=$('#party_id'),owner=$('#owner_id'),stage=$('#stage'),lost=$('#lost-reason-wrap');window.erpInitSelect2(party,{theme:'bootstrap-5',placeholder:'ค้นหาด้วยรหัส ชื่อ หรือโทรศัพท์',allowClear:true,ajax:{url:party.data('url'),dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:d=>d}});window.erpInitSelect2(owner,{theme:'bootstrap-5',placeholder:'ค้นหารหัสหรือชื่อพนักงาน',ajax:{url:owner.data('url'),dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:d=>d}});party.on('select2:select',function(e){const d=e.params.data;if(d.contact_name&&!$('#contact_name').val())$('#contact_name').val(d.contact_name);if(d.phone&&!$('#phone').val())$('#phone').val(d.phone);if(d.email&&!$('#email').val())$('#email').val(d.email);});function syncStage(updateProbability){const option=stage.find(':selected');lost.toggleClass('d-none',stage.val()!=='LOST');$('#lost_reason').prop('required',stage.val()==='LOST');if(updateProbability)$('#probability').val(option.data('probability'));}stage.on('change',()=>syncStage(true));syncStage(false);window.erpAjaxForm({form:'#opportunity-form',redirect:true});});</script>
@endpush
