@extends('Crm::layout')
@section('title','Kanban Pipeline | CRM')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page module-dashboard module-dashboard--crm">
    <div class="module-dashboard-hero d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4 crm-page-header"><div><p class="module-dashboard-kicker mb-2"><span></span>CRM / PIPELINE</p><h1>Kanban Pipeline</h1><p class="mb-0">มองภาพรวม Opportunity ทุกขั้นตอนและเปิดรายละเอียดเพื่อลงมือทำ</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-app-soft" href="{{ route('crm.opportunities.index') }}"><i class="bx bx-list-ul me-1" aria-hidden="true"></i>มุมมองรายการ</a>@if(auth()->user()->hasPermission('crm.opportunities.create'))<a class="btn btn-app-primary" href="{{ route('crm.opportunities.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>สร้างโอกาสการขาย</a>@endif</div></div>
    <div class="card crm-filter-card mb-4"><div class="card-header bg-white d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">ตัวกรอง Pipeline</h2><button class="btn btn-sm btn-app-soft d-md-none" type="button" data-bs-toggle="collapse" data-bs-target="#kanban-filter-body"><i class="bx bx-filter-alt me-1"></i>ตัวกรอง</button></div><div class="collapse d-md-block" id="kanban-filter-body"><div class="card-body"><form class="row g-2" id="kanban-filter"><div class="col-12 col-lg-3"><input class="form-control" name="q" value="{{ $filters['q'] }}" maxlength="100" placeholder="ค้นหา Opportunity หรือลูกค้า" aria-label="ค้นหา"></div><div class="col-12 col-sm-6 col-lg-2"><select class="form-select" name="team_id" aria-label="ทีมขาย"><option value="">ทุกทีม</option>@foreach($teams as $team)<option value="{{ $team->id }}" @selected($filters['team_id']===$team->id)>{{ $team->name }}</option>@endforeach</select></div><div class="col-12 col-sm-6 col-lg-2"><select class="form-select js-kanban-owner" name="owner_id" data-url="{{ route('crm.opportunities.owner-options') }}"><option value="">ผู้รับผิดชอบทุกคน</option>@if($selectedOwner)<option value="{{ $selectedOwner->id }}" selected>{{ $selectedOwner->name }}</option>@endif</select></div><div class="col-6 col-lg"><input class="form-control" name="value_min" type="number" min="0" step="0.01" value="{{ $filters['value_min'] }}" placeholder="มูลค่าต่ำสุด" aria-label="มูลค่าต่ำสุด"></div><div class="col-6 col-lg"><input class="form-control" name="value_max" type="number" min="0" step="0.01" value="{{ $filters['value_max'] }}" placeholder="มูลค่าสูงสุด" aria-label="มูลค่าสูงสุด"></div><div class="col-6 col-lg"><input class="form-control" name="close_month" type="month" value="{{ $filters['close_month'] }}" aria-label="เดือนที่คาดปิด"></div><div class="col-6 col-lg-auto"><button class="btn btn-app-primary w-100" type="submit"><i class="bx bx-search me-1"></i>ค้นหา</button></div></form></div></div></div>
    @if(auth()->user()->hasPermission('crm.opportunities.update'))<div class="alert alert-info py-2"><i class="bx bx-info-circle me-1" aria-hidden="true"></i>ลากการ์ดไปยังขั้นตอนใหม่บน Desktop หรือกด “เปลี่ยนขั้นตอน” บนมือถือ รายการที่ Won/Lost แล้วจะล็อกเพื่อรักษาประวัติ</div>@endif
    <div class="crm-kanban-board" id="kanban-board" aria-live="polite">@foreach($stages as $code=>$stage)<section class="crm-kanban-column" data-stage="{{ $code }}"><header><div><h2>{{ $stage['label'] }}</h2><small>{{ $code }}</small></div><span class="badge {{ $stage['class'] }} js-stage-count">...</span></header><div class="crm-kanban-items"><div class="text-center text-secondary py-4"><span class="spinner-border spinner-border-sm"></span></div></div><button class="btn btn-sm btn-app-soft w-100 mt-2 js-load-more d-none" type="button">โหลดเพิ่ม</button></section>@endforeach</div>
</div>
@endsection
@push('scripts')
<script>
$(function(){
    const form=$('#kanban-filter'),columns=$('.crm-kanban-column'),dataUrl=@json(route('crm.opportunities.kanban.data')),transitionUrl=@json(route('crm.opportunities.stage',['opportunity'=>'__ID__'])),indexUrl=@json(route('crm.opportunities.kanban')),stages=@json(collect($stages)->map(fn($stage)=>['label'=>$stage['label']])->all()),csrf=$('meta[name="csrf-token"]').attr('content');let requests={};
    const owner=$('.js-kanban-owner');window.erpInitSelect2(owner,{theme:'bootstrap-5',placeholder:'ผู้รับผิดชอบทุกคน',allowClear:true,ajax:{url:owner.data('url'),dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:d=>d}});
    function load(column,page,append){const stage=column.data('stage');if(requests[stage])requests[stage].abort();const params=new URLSearchParams(new FormData(form[0]));params.set('stage',stage);params.set('page',page);const items=column.find('.crm-kanban-items'),more=column.find('.js-load-more');if(!append)items.html('<div class="text-center text-secondary py-4"><span class="spinner-border spinner-border-sm"></span></div>');more.addClass('d-none');requests[stage]=$.getJSON(dataUrl,params.toString()).done(function(data){if(append)items.append(data.html);else items.html(data.html||'<div class="crm-kanban-empty">ไม่มี Opportunity</div>');column.find('.js-stage-count').text(Number(data.total).toLocaleString('th-TH'));more.toggleClass('d-none',!data.next_page).data('next-page',data.next_page||'');}).fail(function(xhr,status){if(status!=='abort'&&!append)items.html('<div class="alert alert-danger small">โหลดข้อมูลไม่สำเร็จ</div>');});}
    function loadAll(push){columns.each(function(){load($(this),1,false);});if(push){const params=new URLSearchParams(new FormData(form[0]));history.pushState({},'',indexUrl+(params.toString()?'?'+params.toString():''));}}
    async function chooseStage(card){const options={};Object.entries(stages).forEach(([code,stage])=>{if(code!==card.data('stage'))options[code]=stage.label;});const result=await Swal.fire({title:'เปลี่ยนขั้นตอน',text:card.data('title'),input:'select',inputOptions:options,inputPlaceholder:'เลือกขั้นตอนใหม่',showCancelButton:true,confirmButtonText:'ถัดไป',cancelButtonText:'ยกเลิก',inputValidator:value=>!value?'กรุณาเลือกขั้นตอน':null});if(result.isConfirmed)transition(card,result.value);}
    async function transition(card,stage){if(!stage||stage===card.data('stage'))return;let values={stage};if(stage==='LOST'){const result=await Swal.fire({icon:'warning',title:'ระบุเหตุผลที่ไม่สำเร็จ',input:'textarea',inputPlaceholder:'เหตุผลอย่างน้อย 5 ตัวอักษร',showCancelButton:true,confirmButtonText:'บันทึกว่าไม่สำเร็จ',cancelButtonText:'ยกเลิก',inputValidator:value=>!value||value.trim().length<5?'กรุณาระบุเหตุผลอย่างน้อย 5 ตัวอักษร':null});if(!result.isConfirmed)return;values.lost_reason=result.value.trim();}else if(stage==='WON'){const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10),result=await Swal.fire({icon:'success',title:'ข้อมูลปิดการขาย',html:'<label class="form-label d-block text-start" for="swal-won-value">มูลค่าปิดการขาย</label><input id="swal-won-value" class="swal2-input m-0 w-100" type="number" min="0.01" step="0.01" value="'+Number(card.data('value')).toFixed(2)+'"><label class="form-label d-block text-start mt-3" for="swal-won-date">วันที่ปิดการขาย</label><input id="swal-won-date" class="swal2-input m-0 w-100" type="date" max="'+today+'" value="'+today+'">',showCancelButton:true,confirmButtonText:'บันทึกปิดการขาย',cancelButtonText:'ยกเลิก',preConfirm:()=>{const value=document.getElementById('swal-won-value').value,date=document.getElementById('swal-won-date').value;if(!value||Number(value)<=0||!date){Swal.showValidationMessage('กรุณาระบุมูลค่าและวันที่ปิดการขาย');return false;}return{value,date};}});if(!result.isConfirmed)return;values.won_value=result.value.value;values.won_date=result.value.date;}else{const result=await Swal.fire({icon:'question',title:'เปลี่ยนเป็น '+stages[stage].label+'?',text:card.data('title'),showCancelButton:true,confirmButtonText:'เปลี่ยนขั้นตอน',cancelButtonText:'ยกเลิก'});if(!result.isConfirmed)return;}
        Swal.fire({title:'กำลังบันทึก...',allowOutsideClick:false,didOpen:()=>Swal.showLoading()});$.ajax({url:transitionUrl.replace('__ID__',card.data('opportunity-id')),method:'PATCH',data:{...values,_token:csrf}}).done(function(response){Swal.fire({icon:'success',title:response.msg,timer:1200,showConfirmButton:false});loadAll(false);}).fail(function(xhr){const errors=xhr.responseJSON?.errors,message=errors?Object.values(errors).flat()[0]:(xhr.responseJSON?.message||'เปลี่ยนขั้นตอนไม่สำเร็จ');Swal.fire({icon:'error',title:'เปลี่ยนขั้นตอนไม่สำเร็จ',text:message});});
    }
    form.on('submit',function(e){e.preventDefault();loadAll(true);});columns.on('click','.js-load-more',function(){const button=$(this),column=button.closest('.crm-kanban-column');load(column,Number(button.data('next-page')),true);}).on('click','.js-change-stage',function(){chooseStage($(this).closest('.crm-kanban-card'));}).on('dragstart','.crm-kanban-card[draggable="true"]',function(e){e.originalEvent.dataTransfer.effectAllowed='move';e.originalEvent.dataTransfer.setData('text/plain',$(this).data('opportunity-id'));$(this).addClass('is-dragging');}).on('dragend','.crm-kanban-card',function(){$(this).removeClass('is-dragging');columns.removeClass('is-drag-over');}).on('dragover',function(e){e.preventDefault();$(this).addClass('is-drag-over');}).on('dragleave',function(){$(this).removeClass('is-drag-over');}).on('drop',function(e){e.preventDefault();columns.removeClass('is-drag-over');const id=e.originalEvent.dataTransfer.getData('text/plain'),card=$('.crm-kanban-card[data-opportunity-id="'+id+'"]');transition(card,$(this).data('stage'));});
    window.addEventListener('popstate',()=>location.reload());loadAll(false);
});
</script>
@endpush
