@extends('Crm::layout')
@php($stage = $stages[$opportunity->stage] ?? ['label'=>$opportunity->stage,'class'=>'app-status-neutral'])
@section('title', $opportunity->title.' | CRM')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page module-dashboard module-dashboard--crm">
    <div class="module-dashboard-hero d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4 crm-page-header">
        <div><p class="module-dashboard-kicker mb-2"><span></span>CRM / OPPORTUNITY</p><h1>{{ $opportunity->title }}</h1><span class="badge {{ $stage['class'] }}">{{ $stage['label'] }}</span></div>
        <div class="d-flex flex-wrap gap-2 crm-action-bar">
            <a class="btn btn-outline-secondary" href="{{ route('crm.opportunities.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a>
            @if(auth()->user()->hasPermission('crm.opportunities.update') && !in_array($opportunity->stage, ['WON', 'LOST'], true))
                <a class="btn btn-app-soft" href="{{ route('crm.opportunities.edit', $opportunity) }}"><i class="bx bx-edit me-1" aria-hidden="true"></i>แก้ไข</a>
            @endif
            @if(auth()->user()->hasPermission('crm.opportunities.convert-pos') && $canOpenPos && $opportunity->party_id)
                @if($opportunity->salesIntake)
                    <form method="post" action="{{ route('crm.opportunities.to-pos', $opportunity) }}">@csrf<button class="btn btn-app-primary" type="submit"><i class="bx bx-cart-add me-1" aria-hidden="true"></i>เปิด Sales Intake {{ $opportunity->salesIntake->document_number }}</button></form>
                @elseif($warehouses->count()===1)
                    <form class="js-send-pos-direct" method="post" action="{{ route('crm.opportunities.to-pos',$opportunity) }}">@csrf<input type="hidden" name="warehouse_id" value="{{ $warehouses->first()->id }}"><button class="btn btn-app-primary" type="submit"><i class="bx bx-cart-add me-1" aria-hidden="true"></i>สร้างใบรับข้อมูลใน POS</button></form>
                @else
                    <button class="btn btn-app-primary js-send-pos" type="button" data-bs-toggle="modal" data-bs-target="#send-pos-modal" @disabled($warehouses->isEmpty())><i class="bx bx-cart-add me-1" aria-hidden="true"></i>สร้างใบรับข้อมูลใน POS</button>
                @endif
            @endif
            @if(auth()->user()->hasPermission('crm.opportunities.delete') && in_array($opportunity->stage, ['NEW', 'CONTACTED'], true) && $activityCount === 0 && !$opportunity->sales_intake_id)
                <button class="btn btn-app-danger js-delete-opportunity" type="button"><i class="bx bx-trash me-1" aria-hidden="true"></i>ลบร่าง</button>
            @endif
        </div>
    </div>

    @if(!$opportunity->party_id)
        <div class="alert alert-warning border-0 mb-4"><strong>ขั้นตอนถัดไป:</strong> ผูกลูกค้าในระบบก่อนสร้างเอกสารขายต่อใน POS</div>
    @elseif(!$opportunity->salesIntake && $canOpenPos && $warehouses->isEmpty())
        <div class="alert alert-warning border-0 mb-4"><strong>ยังส่งต่อ POS ไม่ได้:</strong> ผู้ใช้ยังไม่ได้รับสิทธิ์คลังสินค้าในสาขานี้</div>
    @elseif(!$opportunity->salesIntake)
        <div class="alert alert-info border-0 mb-4"><strong>ขั้นตอนถัดไป:</strong> บันทึกกิจกรรมหรือสร้างใบรับข้อมูลใน POS เมื่อพร้อมเสนอขาย</div>
    @else
        <div class="alert alert-success border-0 mb-4">เชื่อมต่อ POS แล้ว: {{ $opportunity->salesIntake->document_number }} · {{ $opportunity->salesIntake->status }}</div>
    @endif

    <div class="row g-4 mb-4">
        <div class="col-12 col-xl-8"><div class="card h-100"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ข้อมูลโอกาสการขาย</h2><div class="row g-3">
            <div class="col-12 col-md-6"><div class="small text-secondary">ลูกค้า</div><strong>{{ $opportunity->party ? $opportunity->party->code.' · '.$opportunity->party->name : 'ยังไม่ผูกลูกค้า' }}</strong></div>
            <div class="col-12 col-sm-6 col-md-3"><div class="small text-secondary">ผู้ติดต่อ</div><strong>{{ $opportunity->contact_name ?: $opportunity->party?->contact_name ?: '-' }}</strong></div>
            <div class="col-12 col-sm-6 col-md-3"><div class="small text-secondary">โทรศัพท์</div>@php($phone = $opportunity->phone ?: $opportunity->party?->phone)<strong>@if($phone)<a class="crm-contact-link" href="tel:{{ $phone }}">{{ $phone }}</a>@else-@endif</strong></div>
            <div class="col-12 col-md-6"><div class="small text-secondary">อีเมล</div>@php($email = $opportunity->email ?: $opportunity->party?->email)<strong>@if($email)<a class="crm-contact-link text-break" href="mailto:{{ $email }}">{{ $email }}</a>@else-@endif</strong></div>
            <div class="col-12 col-md-6"><div class="small text-secondary">แหล่งที่มา</div><strong>{{ $opportunity->source ?: '-' }}</strong></div>
            <div class="col-12"><div class="small text-secondary">หมายเหตุ</div><div class="text-break">{{ $opportunity->notes ?: '-' }}</div></div>
            @if($opportunity->lost_reason)<div class="col-12"><div class="small text-secondary">เหตุผลที่ไม่สำเร็จ</div><div class="text-danger">{{ $opportunity->lost_reason }}</div></div>@endif
        </div></div></div></div>
        <div class="col-12 col-xl-4"><div class="card h-100"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">สรุป Pipeline</h2><div class="mb-3"><div class="small text-secondary">มูลค่าคาดการณ์</div><div class="fs-3 fw-semibold text-primary">{{ number_format((float)$opportunity->expected_value,2) }}</div></div><div class="row g-3"><div class="col-6"><div class="small text-secondary">โอกาสสำเร็จ</div><strong>{{ $opportunity->probability }}%</strong></div><div class="col-6"><div class="small text-secondary">มูลค่าถ่วงน้ำหนัก</div><strong>{{ number_format((float)$opportunity->expected_value*$opportunity->probability/100,2) }}</strong></div><div class="col-6"><div class="small text-secondary">วันที่คาดปิด</div><strong>{{ $opportunity->expected_close_date?->format('d/m/Y') ?: '-' }}</strong></div><div class="col-6"><div class="small text-secondary">ผู้รับผิดชอบ</div><strong>{{ $opportunity->owner?->name ?: '-' }}</strong></div><div class="col-12"><div class="small text-secondary">งานถัดไป</div><strong class="{{ $opportunity->next_action_at?->isPast() ? 'text-danger' : '' }}">{{ $opportunity->next_action_at?->format('d/m/Y H:i') ?: '-' }}</strong></div></div></div></div></div>
    </div>

    <section class="card mb-4" aria-labelledby="product-interest-title"><div class="card-header bg-white d-flex justify-content-between align-items-center gap-2"><div><h2 class="h5 mb-1" id="product-interest-title">สินค้าที่ลูกค้าสนใจ</h2><p class="small text-secondary mb-0"><span class="badge app-status-info" id="product-interest-count">0</span> รายการ · ใช้เตรียมข้อมูลส่งต่อ POS</p></div>@if(auth()->user()->hasPermission('crm.opportunities.update')&&!in_array($opportunity->stage,['WON','LOST'],true))<button class="btn btn-sm btn-app-primary" type="button" data-bs-toggle="collapse" data-bs-target="#product-interest-form"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มสินค้า</button>@endif</div>
        @if(auth()->user()->hasPermission('crm.opportunities.update')&&!in_array($opportunity->stage,['WON','LOST'],true))<div class="collapse" id="product-interest-form"><div class="card-body border-bottom"><form id="interest-form">@csrf<input name="interest_id" type="hidden"><input name="uom_id" type="hidden"><div class="row g-3"><div class="col-12 col-lg-5"><label class="form-label">สินค้า <span class="text-danger">*</span></label><select class="form-select js-interest-item" name="item_id" data-url="{{ route('crm.opportunities.product-item-options') }}" required></select><div class="invalid-feedback" data-error-for="item_id"></div></div><div class="col-6 col-lg-2"><label class="form-label">จำนวน <span class="text-danger">*</span></label><input class="form-control" name="quantity" type="number" min="{{ \App\Modules\Wms\Support\WmsDecimal::step() }}" step="{{ \App\Modules\Wms\Support\WmsDecimal::step() }}" required><div class="invalid-feedback" data-error-for="quantity"></div></div><div class="col-6 col-lg-2"><label class="form-label">หน่วย</label><input class="form-control" name="uom_label" readonly></div><div class="col-6 col-lg-3"><label class="form-label">ราคาเป้าหมาย/หน่วย</label><input class="form-control" name="target_unit_price" type="number" min="0" step="{{ \App\Modules\Wms\Support\WmsDecimal::step() }}"></div><div class="col-6 col-lg-3"><label class="form-label">งบประมาณ</label><input class="form-control" name="budget_amount" type="number" min="0" step="{{ \App\Modules\Wms\Support\WmsDecimal::step() }}"></div><div class="col-12 col-lg-9"><label class="form-label">ความต้องการของลูกค้า</label><textarea class="form-control" name="requirements" rows="2" maxlength="2000"></textarea></div></div><div class="d-flex flex-wrap gap-2 mt-3"><button class="btn btn-app-primary" type="submit"><i class="bx bx-save me-1" aria-hidden="true"></i>บันทึกสินค้า</button><button class="btn btn-app-soft js-reset-interest" type="button">ล้างข้อมูล</button></div></form></div></div>@endif
        <div class="card-body"><div id="product-interest-list" aria-live="polite" aria-busy="true"><div class="text-center text-secondary py-4"><span class="spinner-border spinner-border-sm"></span></div></div><nav id="product-interest-pagination" class="mt-3" aria-label="หน้ารายการสินค้าที่สนใจ"></nav></div>
    </section>

    @if($documentTrail)
    <section class="card mb-4" aria-labelledby="opportunity-document-trail-title"><div class="card-body p-3 p-lg-4"><div class="mb-3"><h2 class="h5 mb-1" id="opportunity-document-trail-title">เส้นทางเอกสารขาย</h2><p class="small text-secondary mb-0">ติดตามเอกสารตั้งแต่ Sales Intake จนถึงการรับชำระเงิน</p></div><div class="row g-2">@foreach($documentTrail as $step)<div class="col-6 col-lg-2"><div class="border rounded-3 p-3 h-100"><div class="small text-secondary mb-2">{{ $step['label'] }}</div>@if($step['id'])@if($step['can_open'])<form method="post" action="{{ route('crm.opportunities.documents.open',[$opportunity,$step['type'],$step['id']]) }}">@csrf<button class="btn btn-link fw-semibold text-start p-0 text-decoration-none text-break" type="submit">{{ $step['number'] }}</button></form>@else<div class="fw-semibold text-break">{{ $step['number'] }}</div>@endif<div class="small text-secondary mt-1">{{ $step['date'] }}</div><span class="badge mt-2 {{ in_array($step['status'],['POSTED','COMPLETED','APPROVED','ACCEPTED','CONFIRMED','FULFILLED'],true)?'app-status-success':(in_array($step['status'],['VOID','CANCELLED','REJECTED'],true)?'app-status-danger':($step['status']==='DRAFT'?'app-status-neutral':'app-status-info')) }}">{{ $step['status_label'] }}</span>@else<div class="text-secondary">ยังไม่มี</div><span class="badge app-status-neutral mt-2">รอดำเนินการ</span>@endif</div></div>@endforeach</div></div></section>
    @endif

    <section class="row g-4" aria-labelledby="activity-section-title">
        <div class="col-12 col-xl-4">
            @if(auth()->user()->hasPermission('crm.activities.create'))<div class="card crm-activity-compose"><div class="card-header bg-white d-flex justify-content-between align-items-center p-3"><div><h2 class="h5 mb-0">เพิ่มกิจกรรม</h2><small class="text-secondary">กำหนดงานให้ตนเองหรือพนักงานคนอื่น</small></div><button class="btn btn-sm btn-app-soft d-xl-none" type="button" data-bs-toggle="collapse" data-bs-target="#activity-compose-body" aria-expanded="false"><i class="bx bx-plus" aria-hidden="true"></i></button></div><div class="collapse d-xl-block" id="activity-compose-body"><div class="card-body p-3 p-lg-4"><form id="activity-form" method="post" action="{{ route('crm.opportunities.activities.store',$opportunity) }}">@csrf<div class="row g-3"><div class="col-6"><label class="form-label">ประเภท</label><select class="form-select" name="type" required><option value="CALL">โทรศัพท์</option><option value="MEETING">นัดหมาย</option><option value="TASK">งานติดตาม</option><option value="NOTE">บันทึก</option></select></div><div class="col-6"><label class="form-label">ผู้รับผิดชอบ</label><select class="form-select js-activity-assignee" name="assigned_to" data-url="{{ route('crm.opportunities.owner-options') }}"><option value="{{ auth()->id() }}" selected>{{ auth()->user()->employee_code ? auth()->user()->employee_code.' · ' : '' }}{{ auth()->user()->name }}</option></select></div><div class="col-12"><label class="form-label">หัวข้อ <span class="text-danger">*</span></label><input class="form-control" name="subject" maxlength="255" required><div class="invalid-feedback" data-error-for="subject"></div></div><div class="col-12"><label class="form-label">กำหนดเวลา</label><input class="form-control" name="due_at" type="datetime-local"></div><div class="col-12"><label class="form-label">รายละเอียด</label><textarea class="form-control" name="details" rows="3" maxlength="2000"></textarea></div></div><button class="btn btn-app-primary mt-3 crm-activity-submit" type="submit"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มกิจกรรม</button></form></div></div></div>@endif
        </div>
        <div class="col-12 col-xl-8">
            <div class="card"><div class="card-body p-3 p-lg-4">
                <div class="d-flex flex-column flex-md-row justify-content-between gap-2 mb-3"><div><h2 class="h5 mb-1" id="activity-section-title">กิจกรรมและการติดตาม</h2><p class="small text-secondary mb-0"><span id="activity-count">{{ number_format($activityCount) }}</span> กิจกรรม · โหลดครั้งละ 8 รายการ</p></div></div>
                <form class="row g-2 mb-3" id="activity-filter-form"><div class="col-12 col-md-5"><label class="visually-hidden" for="activity-q">ค้นหา</label><input class="form-control" id="activity-q" name="q" placeholder="ค้นหาหัวข้อ รายละเอียด หรือผู้รับผิดชอบ"></div><div class="col-6 col-md-3"><label class="visually-hidden" for="activity-status">สถานะ</label><select class="form-select" id="activity-status" name="status"><option value="ALL">ทุกสถานะ</option><option value="OPEN">ยังไม่เสร็จ</option><option value="COMPLETED">เสร็จแล้ว</option></select></div><div class="col-6 col-md-2"><label class="visually-hidden" for="activity-type">ประเภท</label><select class="form-select" id="activity-type" name="type"><option value="">ทุกประเภท</option><option value="CALL">โทรศัพท์</option><option value="MEETING">นัดหมาย</option><option value="TASK">งานติดตาม</option><option value="NOTE">บันทึก</option></select></div><div class="col-12 col-md-2"><button class="btn btn-app-soft w-100" type="submit"><i class="bx bx-search me-1" aria-hidden="true"></i>ค้นหา</button></div></form>
                <div id="activity-list" aria-live="polite" aria-busy="true"><div class="text-center text-secondary py-5"><span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>กำลังโหลดกิจกรรม...</div></div>
                <nav id="activity-pagination" class="mt-3" aria-label="หน้ารายการกิจกรรม"></nav>
            </div></div>
        </div>
    </section>
</div>
@if(!$opportunity->salesIntake && auth()->user()->hasPermission('crm.opportunities.convert-pos') && $canOpenPos && $opportunity->party_id && $warehouses->count()>1)
<div class="modal fade" id="send-pos-modal" tabindex="-1" aria-labelledby="send-pos-title" aria-hidden="true"><div class="modal-dialog"><form class="modal-content" method="post" action="{{ route('crm.opportunities.to-pos',$opportunity) }}">@csrf<div class="modal-header"><h2 class="modal-title fs-5" id="send-pos-title">ส่ง Product Interest ไป POS</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body"><p class="text-secondary">ระบบจะนำรายการสินค้าไปเตรียม Sales Intake และให้ POS คำนวณราคา Promotion ภาษี และ Stock ใหม่ก่อนบันทึก</p><label class="form-label" for="pos-warehouse">คลังสินค้า <span class="text-danger">*</span></label><select class="form-select" id="pos-warehouse" name="warehouse_id" required><option value="">เลือกคลังสินค้า</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->code }} · {{ $warehouse->name }}</option>@endforeach</select>@if($warehouses->isEmpty())<div class="alert alert-warning mt-3 mb-0">ผู้ใช้ยังไม่ได้รับสิทธิ์คลังสินค้าในสาขานี้</div>@endif</div><div class="modal-footer"><button class="btn btn-app-soft" type="button" data-bs-dismiss="modal">ยกเลิก</button><button class="btn btn-app-primary" type="submit" @disabled($warehouses->isEmpty())><i class="bx bx-send me-1" aria-hidden="true"></i>ไปสร้าง Sales Intake</button></div></form></div></div>
@endif
@endsection
@push('scripts')
<script>
$(function(){
 const assignee=$('.js-activity-assignee'),filter=$('#activity-filter-form'),list=$('#activity-list'),pagination=$('#activity-pagination'),count=$('#activity-count'),dataUrl=@json(route('crm.opportunities.activities.data',$opportunity));let activityRequest;
 const interestForm=$('#interest-form'),interestList=$('#product-interest-list'),interestPages=$('#product-interest-pagination'),interestCount=$('#product-interest-count'),interestDataUrl=@json(route('crm.opportunities.product-interests.data',$opportunity)),interestStoreUrl=@json(route('crm.opportunities.product-interests.store',$opportunity)),interestUpdateUrl=@json(route('crm.opportunities.product-interests.update',['opportunity'=>$opportunity,'productInterest'=>'__ID__'])),interestDeleteUrl=@json(route('crm.opportunities.product-interests.destroy',['opportunity'=>$opportunity,'productInterest'=>'__ID__']));let interestTotal=0;
 window.erpInitSelect2(assignee,{theme:'bootstrap-5',placeholder:'ค้นหารหัสหรือชื่อพนักงาน',ajax:{url:assignee.data('url'),dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:d=>d}});
 window.erpAjaxForm({form:'#activity-form',reload:true});
 if(interestForm.length){const item=interestForm.find('.js-interest-item');window.erpInitSelect2(item,{theme:'bootstrap-5',placeholder:'ค้นหารหัสหรือชื่อสินค้า',ajax:{url:item.data('url'),dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:d=>d}});item.on('select2:select',function(e){interestForm.find('[name=uom_id]').val(e.params.data.uom_id);interestForm.find('[name=uom_label]').val(e.params.data.uom_label);});}
 function resetInterest(){if(!interestForm.length)return;interestForm[0].reset();interestForm.find('[name=interest_id],[name=uom_id]').val('');interestForm.find('.js-interest-item').val(null).trigger('change');interestForm.find('.is-invalid').removeClass('is-invalid');}
 function loadInterests(page){const params=page>1?'?page='+page:'';interestList.attr('aria-busy','true');$.getJSON(interestDataUrl+params).done(function(data){interestList.html(data.html).attr('aria-busy','false');interestPages.html(data.pagination);interestTotal=Number(data.total);interestCount.text(interestTotal.toLocaleString('th-TH'));}).fail(function(){interestList.attr('aria-busy','false').html('<div class="alert alert-danger mb-0">โหลดสินค้าที่สนใจไม่สำเร็จ</div>');});}
 interestForm.on('submit',function(e){e.preventDefault();const id=interestForm.find('[name=interest_id]').val(),button=interestForm.find('[type=submit]').prop('disabled',true),data=interestForm.serializeArray();if(id)data.push({name:'_method',value:'PUT'});interestForm.find('.is-invalid').removeClass('is-invalid');$.post(id?interestUpdateUrl.replace('__ID__',id):interestStoreUrl,data).done(function(response){resetInterest();bootstrap.Collapse.getOrCreateInstance(document.getElementById('product-interest-form')).hide();loadInterests(1);Swal.fire({icon:'success',title:response.msg,timer:1200,showConfirmButton:false});}).fail(function(xhr){const errors=xhr.responseJSON?.errors||{};Object.entries(errors).forEach(([field,messages])=>{const input=interestForm.find('[name="'+field+'"]');input.addClass('is-invalid');interestForm.find('[data-error-for="'+field+'"]').text(messages[0]);});window.erpAjaxError(xhr);}).always(()=>button.prop('disabled',false));});
 interestPages.on('click','a',function(e){e.preventDefault();loadInterests(Number(new URL(this.href).searchParams.get('page')||1));});interestList.on('click','.js-edit-interest',function(){const b=$(this),select=interestForm.find('.js-interest-item');resetInterest();interestForm.find('[name=interest_id]').val(b.data('id'));select.append(new Option(b.data('item-text'),b.data('item-id'),true,true)).trigger('change');interestForm.find('[name=uom_id]').val(b.data('uom-id'));interestForm.find('[name=uom_label]').val(b.data('uom-label'));interestForm.find('[name=quantity]').val(b.data('quantity'));interestForm.find('[name=target_unit_price]').val(b.data('target-price'));interestForm.find('[name=budget_amount]').val(b.data('budget'));interestForm.find('[name=requirements]').val(b.data('requirements'));bootstrap.Collapse.getOrCreateInstance(document.getElementById('product-interest-form')).show();document.getElementById('product-interest-form').scrollIntoView({behavior:'smooth',block:'center'});}).on('click','.js-delete-interest',function(){const id=$(this).data('id');Swal.fire({icon:'warning',title:'ลบสินค้าที่สนใจ?',showCancelButton:true,confirmButtonText:'ลบ',cancelButtonText:'ยกเลิก'}).then(result=>{if(!result.isConfirmed)return;$.ajax({url:interestDeleteUrl.replace('__ID__',id),method:'DELETE',data:{_token:$('meta[name=csrf-token]').attr('content')}}).done(function(response){loadInterests(1);Swal.fire({icon:'success',title:response.msg||'ลบสินค้าที่สนใจแล้ว',timer:1200,showConfirmButton:false});}).fail(window.erpAjaxError);});});interestForm.on('click','.js-reset-interest',resetInterest);
 function loadActivities(page){if(activityRequest)activityRequest.abort();const params=new URLSearchParams(new FormData(filter[0]));if(page>1)params.set('page',page);list.attr('aria-busy','true').html('<div class="text-center text-secondary py-5"><span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>กำลังโหลดกิจกรรม...</div>');pagination.empty();activityRequest=$.getJSON(dataUrl,params.toString()).done(function(data){list.html(data.html).attr('aria-busy','false');pagination.html(data.pagination);count.text(Number(data.total).toLocaleString('th-TH'));}).fail(function(xhr,status){if(status==='abort')return;list.attr('aria-busy','false').html('<div class="alert alert-danger mb-0">โหลดกิจกรรมไม่สำเร็จ กรุณาลองใหม่</div>');});}
 filter.on('submit',function(event){event.preventDefault();loadActivities(1);});
 pagination.on('click','a.page-link',function(event){event.preventDefault();loadActivities(Number(new URL(this.href).searchParams.get('page')||1));});
 list.on('click','.js-complete-activity',function(){const button=$(this);button.prop('disabled',true);$.post(button.data('url'),{_token:$('meta[name=csrf-token]').attr('content')}).done(function(){loadActivities(1);}).fail(function(xhr){button.prop('disabled',false);window.erpAjaxError(xhr);});});
 if(location.hash==='#activity-form'){bootstrap.Collapse.getOrCreateInstance(document.getElementById('activity-compose-body')).show();}
 function warnEmptyInterests(){Swal.fire({icon:'warning',title:'ยังไม่มีสินค้าที่ลูกค้าสนใจ',text:'เพิ่มสินค้าอย่างน้อย 1 รายการก่อนสร้างใบรับข้อมูลใน POS',confirmButtonText:'ตกลง'});}
 $('#send-pos-modal').on('show.bs.modal',function(event){if(interestTotal>0)return;event.preventDefault();warnEmptyInterests();});
 $('.js-send-pos-direct').on('submit',function(event){if(interestTotal>0)return;event.preventDefault();warnEmptyInterests();});
 $('.js-delete-opportunity').on('click',function(){Swal.fire({icon:'warning',title:'ลบโอกาสการขาย?',text:'ลบได้เฉพาะรายการเริ่มต้นที่ยังไม่มีกิจกรรม',showCancelButton:true,confirmButtonText:'ลบร่าง',cancelButtonText:'กลับ'}).then(function(result){if(!result.isConfirmed)return;$.ajax({url:@json(route('crm.opportunities.destroy',$opportunity)),method:'DELETE',data:{_token:$('meta[name=csrf-token]').attr('content')}}).done(function(response){location.href=response.redirect;}).fail(window.erpAjaxError);});});
 loadInterests(1);loadActivities(1);
});
</script>
@endpush
