@extends('Asset::layout')
@section('title', 'Asset Dashboard | New ERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4" id="asset-dashboard" data-url="{{ route('asset.dashboard.data', ['section' => '__section__']) }}">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / DASHBOARD</p><h1 class="h3 mb-2">ภาพรวมสินทรัพย์</h1><p class="text-secondary mb-0">สาขา {{ $branch->name }} · ข้อมูลแบ่งโหลดตามส่วนเพื่อให้หน้าเปิดได้รวดเร็ว</p></div><a class="btn btn-outline-dark" href="{{ route('asset.assets.index') }}">ทะเบียนสินทรัพย์</a></div>
    <div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">สินทรัพย์ทั้งหมด</div><div class="fs-3 fw-semibold" data-summary="total_assets">—</div></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">กำลังใช้งาน</div><div class="fs-3 fw-semibold text-success" data-summary="active_assets">—</div></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">อยู่ระหว่างซ่อม</div><div class="fs-3 fw-semibold text-warning" data-summary="under_repair">—</div></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">มูลค่าตามบัญชี</div><div class="fs-3 fw-semibold" data-summary="book_value">—</div></div></div></div></div>
    <div class="row g-4 mb-4"><div class="col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">แนวโน้มใบแจ้งซ่อม</h2><p class="small text-secondary mb-0">จำนวนใบแจ้งซ่อมย้อนหลัง 6 เดือน</p></div><span class="badge app-status-info">6 เดือน</span></div><canvas id="maintenance-trend-chart" height="120" role="img" aria-label="แนวโน้มใบแจ้งซ่อมย้อนหลัง 6 เดือน"></canvas></div></div></div><div class="col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">งานที่ต้องติดตาม</h2><p class="small text-secondary mb-0">สถานะปัจจุบันของสาขา</p></div><a class="btn btn-sm btn-outline-dark" href="{{ route('asset.maintenance.index') }}">ดูงานซ่อม</a></div><div class="vstack gap-3"><div class="d-flex justify-content-between"><span>งานซ่อมค้าง</span><strong data-maintenance="open_count">—</strong></div><div class="d-flex justify-content-between"><span>งาน Critical</span><strong class="text-danger" data-maintenance="critical_count">—</strong></div><div class="d-flex justify-content-between"><span>รออะไหล่</span><strong data-maintenance="waiting_parts">—</strong></div><div class="d-flex justify-content-between"><span>แผนใกล้ครบกำหนด</span><strong data-maintenance="due_schedules">—</strong></div></div></div></div></div></div>
    <div class="row g-4"><div class="col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h6">ค่าเสื่อมเดือนนี้ (Book)</h2><div class="fs-4 fw-semibold mt-2" data-summary="monthly_depreciation">—</div><a class="small" href="{{ route('asset.depreciations.index') }}">ดูรายการค่าเสื่อม</a></div></div></div><div class="col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h6">สถานะสินทรัพย์ปลายทาง</h2><div class="small text-secondary mt-2">เลิกใช้งาน/ตัดจำหน่าย</div><div class="fs-4 fw-semibold" data-summary="retired_assets">—</div></div></div></div><div class="col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h6">ทางลัด</h2><div class="d-flex flex-wrap gap-2 mt-3"><a class="btn btn-sm btn-app-soft" href="{{ route('asset.reports.maintenance.index') }}">รายงานงานซ่อม</a><a class="btn btn-sm btn-outline-dark" href="{{ route('asset.reports.depreciation.index') }}">รายงานค่าเสื่อม</a></div></div></div></div></div>
    <div class="card border-0 shadow-sm mt-4" data-dashboard-section="controls"><div class="card-body p-3 p-lg-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">ความพร้อมก่อนปิดงวด</h2><p class="small text-secondary mb-0">รายการค้างที่ควรตรวจสอบก่อนส่งให้บัญชีปิดงวด</p></div><a class="btn btn-sm btn-outline-dark" href="{{ route('asset.workflow.index') }}">เปิด Workflow Center</a></div><div class="row g-3"><div class="col-6 col-xl-3"><a class="d-block border rounded-3 p-3 h-100 text-reset text-decoration-none" href="{{ route('asset.depreciations.index') }}"><div class="small text-secondary">ค่าเสื่อมค้าง</div><div class="fs-4 fw-semibold" data-controls="pending_depreciation">—</div><div class="small text-primary mt-2">ตรวจรายการ <i class="bx bx-right-arrow-alt" aria-hidden="true"></i></div></a></div><div class="col-6 col-xl-3"><a class="d-block border rounded-3 p-3 h-100 text-reset text-decoration-none" href="{{ route('asset.impairments.index') }}"><div class="small text-secondary">ด้อยค่าค้าง</div><div class="fs-4 fw-semibold" data-controls="pending_impairment">—</div><div class="small text-primary mt-2">ตรวจรายการ <i class="bx bx-right-arrow-alt" aria-hidden="true"></i></div></a></div><div class="col-6 col-xl-3"><a class="d-block border rounded-3 p-3 h-100 text-reset text-decoration-none" href="{{ route('asset.disposals.index') }}"><div class="small text-secondary">จำหน่ายค้าง</div><div class="fs-4 fw-semibold" data-controls="pending_disposal">—</div><div class="small text-primary mt-2">ตรวจรายการ <i class="bx bx-right-arrow-alt" aria-hidden="true"></i></div></a></div><div class="col-6 col-xl-3"><a class="d-block border rounded-3 p-3 h-100 text-reset text-decoration-none" href="{{ route('asset.depreciations.index') }}"><div class="small text-secondary">Posted ไม่ผูก Journal</div><div class="fs-4 fw-semibold text-danger" data-controls="unlinked_posted">—</div><div class="small text-primary mt-2">ตรวจ Journal linkage <i class="bx bx-right-arrow-alt" aria-hidden="true"></i></div></a></div></div></div></div>
    <div class="card border-0 shadow-sm mt-4" data-dashboard-section="reconciliation"><div class="card-body p-3 p-lg-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h2 class="h5 mb-1">กระทบยอดทะเบียนกับ GL</h2><p class="small text-secondary mb-0" data-reconciliation="period_name">กำลังโหลดงวดบัญชี…</p></div><a class="btn btn-sm btn-outline-dark" href="{{ route('asset.reports.reconciliation.index') }}">เปิดรายงานและ Drill-down</a></div><div class="d-flex align-items-baseline gap-3 mt-3"><div class="fs-3 fw-semibold" data-reconciliation="variance">—</div><span class="badge app-status-neutral" data-reconciliation="status">กำลังตรวจสอบ</span></div><div class="small text-secondary mt-1">ผลต่างรวมของ Cost, ค่าเสื่อมสะสม และด้อยค่าสะสม</div></div></div>
</div>
@endsection
@push('scripts')
<script>
$(function(){var root=$('#asset-dashboard'),money=function(v){return Number(v||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});},url=function(s){return root.data('url').replace('__section__',s);},load=function(s,done){$.getJSON(url(s)).done(done).fail(function(){root.find('[data-'+(s==='summary'?'summary':s==='controls'?'controls':s==='reconciliation'?'reconciliation':'maintenance')+']').text('—');});};load('summary',function(d){$.each(d,function(k,v){root.find('[data-summary="'+k+'"]').text(k==='book_value'||k==='monthly_depreciation'?money(v):Number(v||0).toLocaleString('th-TH'));});});load('maintenance',function(d){$.each(d,function(k,v){root.find('[data-maintenance="'+k+'"]').text(Number(v||0).toLocaleString('th-TH'));});});load('controls',function(d){$.each(d,function(k,v){root.find('[data-controls="'+k+'"]').text(Number(v||0).toLocaleString('th-TH'));});});load('reconciliation',function(d){root.find('[data-reconciliation="period_name"]').text(d.period_name||'ยังไม่มีงวดบัญชี');root.find('[data-reconciliation="variance"]').text(money(d.variance));var $status=root.find('[data-reconciliation="status"]');$status.text(d.status==='OK'?'ผ่าน':d.status==='NO_PERIOD'?'ไม่มีงวด':'มีผลต่าง').removeClass('app-status-neutral app-status-success app-status-danger').addClass(d.status==='OK'?'app-status-success':d.status==='NO_PERIOD'?'app-status-neutral':'app-status-danger');});load('trend',function(d){if(!window.Chart)return;new Chart(document.getElementById('maintenance-trend-chart'),{type:'line',data:{labels:d.labels,datasets:[{label:'ใบแจ้งซ่อม',data:d.values,borderColor:'#1d70f7',backgroundColor:'rgba(29,112,247,.12)',fill:true,tension:.35,pointRadius:3}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});});});
</script>
@endpush
