@extends('Asset::layout')
@section('title', 'Import Batch สินทรัพย์ | MintERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / IMPORT BATCHES</p><h1 class="h3 mb-2">Import Batch สินทรัพย์</h1><p class="text-secondary mb-0">ติดตามชุดข้อมูลยอดยกมาที่อัปโหลด ตรวจสอบ และนำเข้าสู่ทะเบียนสินทรัพย์</p></div><a class="btn btn-app-primary" href="{{ route('asset.assets.import.create') }}"><i class="bx bx-upload me-1" aria-hidden="true"></i>นำเข้าไฟล์ใหม่</a></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center gap-3 mb-3"><div><h2 class="h5 mb-1">ตัวกรอง</h2><p class="small text-secondary mb-0">กรองสถานะและวันที่ Cutover ก่อนดูรายการ</p></div><button id="import-filter-reset" class="btn btn-sm btn-app-soft" type="button"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-md-4"><label class="form-label" for="import-filter-status">สถานะ</label><select class="form-select" id="import-filter-status"><option value="">ทุกสถานะ</option><option value="DRAFT">ร่าง</option><option value="VALIDATED">ตรวจสอบแล้ว</option><option value="COMMITTED">นำเข้าแล้ว</option></select></div><div class="col-md-4"><label class="form-label" for="import-filter-date-from">วันที่ Cutover ตั้งแต่</label><input class="form-control" id="import-filter-date-from" type="date"></div><div class="col-md-4"><label class="form-label" for="import-filter-date-to">วันที่ Cutover ถึง</label><input class="form-control" id="import-filter-date-to" type="date"></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="mb-3"><h2 class="h5 mb-1">รายการชุดนำเข้ายอดยกมา</h2><p class="small text-secondary mb-0">ค้นหา จัดเรียง และส่งออกข้อมูลของหน้าปัจจุบันได้</p></div><div class="table-responsive"><table class="table table-hover align-middle w-100" id="asset-import-batches" data-url="{{ route('asset.assets.import.data') }}"><thead><tr><th>Batch</th><th>วันที่ Cutover</th><th>สถานะ</th><th class="text-end">จำนวนรายการ</th><th class="text-end">ต้นทุนยกมา</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){var $table=$('#asset-import-batches'),text=$.fn.dataTable.render.text(),filters=function(){return {status:$('#import-filter-status').val(),cutover_date_from:$('#import-filter-date-from').val(),cutover_date_to:$('#import-filter-date-to').val()};},labels={DRAFT:'ร่าง',VALIDATED:'ตรวจสอบแล้ว',COMMITTED:'นำเข้าแล้ว'},classes={DRAFT:'app-status-neutral',VALIDATED:'app-status-info',COMMITTED:'app-status-success'},table=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(data){$.extend(data,filters());}},order:[[1,'desc']],buttons:[window.erpExcelButton($table)],columns:[{data:'batch_reference',render:text.display},{data:'cutover_date',render:text.display},{data:'status',render:function(value,type){return type==='display'?'<span class="badge '+(classes[value]||'app-status-neutral')+'">'+text.display(labels[value]||value)+'</span>':value;}},{data:'lines_count',className:'text-end',render:text.display},{data:'total_opening_cost',className:'text-end',render:function(value,type){return type==='display'?Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):value;}},{data:'show_url',orderable:false,searchable:false,className:'text-end',render:function(value,type){return type==='display'?'<a class="btn btn-sm btn-app-soft" href="'+text.display(value)+'" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-file-find" aria-hidden="true"></i></a>':'';}}]}));$('#import-filter-status,#import-filter-date-from,#import-filter-date-to').on('change',function(){table.ajax.reload();});$('#import-filter-reset').on('click',function(){$('#import-filter-status,#import-filter-date-from,#import-filter-date-to').val('');table.ajax.reload();});});</script>@endpush
