@extends('Asset::layout')
@section('title', 'รายละเอียด Import Batch | New ERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / IMPORT BATCH</p><div class="d-flex align-items-center gap-2"><h1 class="h3 mb-0">{{ $batch->batch_reference }}</h1><span class="badge {{ ['DRAFT'=>'app-badge-soft','VALIDATED'=>'app-badge-info','COMMITTED'=>'app-badge-success'][$batch->status] ?? 'app-status-neutral' }}">{{ ['DRAFT'=>'ร่าง','VALIDATED'=>'ตรวจสอบแล้ว','COMMITTED'=>'นำเข้าแล้ว'][$batch->status] ?? $batch->status }}</span></div><p class="text-secondary mb-0 mt-2">Cutover {{ $batch->cutover_date?->format('d/m/Y') }} · อ้างอิง {{ $batch->reconciliation_reference }}</p></div><div class="d-flex gap-2"><a class="btn btn-outline-dark" href="{{ route('asset.assets.import.index') }}">รายการทั้งหมด</a>@if($batch->status==='VALIDATED')<button class="btn btn-primary" id="commit-import" data-url="{{ route('asset.assets.import.commit', $batch) }}"><i class="bx bx-check me-1" aria-hidden="true"></i>นำเข้าและสร้างทะเบียน</button>@endif</div></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">จำนวนรายการ</div><div class="fs-4 fw-semibold">{{ number_format($batch->total_rows) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">ต้นทุนยกมา</div><div class="fs-4 fw-semibold">{{ number_format($batch->total_opening_cost,2) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">ค่าเสื่อม/ด้อยค่าสะสม</div><div class="fs-4 fw-semibold">{{ number_format($batch->total_accumulated_depreciation + $batch->total_accumulated_impairment,2) }}</div></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white border-0"><h2 class="h5 mb-1">รายการใน Batch</h2><p class="small text-secondary mb-0">ตรวจสอบข้อมูลก่อนนำเข้าเพื่อสร้างทะเบียนสินทรัพย์ (ไม่สร้าง Journal)</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>รหัสแถว</th><th>สินทรัพย์</th><th class="text-end">ต้นทุนยกมา</th><th class="text-end">ค่าเสื่อมสะสม</th><th class="text-end">ด้อยค่าสะสม</th><th>สถานะ</th></tr></thead><tbody>@foreach($batch->lines as $line)<tr><td>{{ $line->row_key }}</td><td><div class="fw-semibold">{{ data_get($line->asset_payload,'asset_number') }}</div><div class="small text-secondary">{{ data_get($line->asset_payload,'name') }}</div></td><td class="text-end">{{ number_format($line->opening_cost,2) }}</td><td class="text-end">{{ number_format($line->opening_accumulated_depreciation,2) }}</td><td class="text-end">{{ number_format($line->opening_accumulated_impairment,2) }}</td><td>@if($line->asset_id)<span class="badge app-badge-success">นำเข้าแล้ว</span>@else<span class="badge app-badge-warning">รอนำเข้า</span>@endif</td></tr>@endforeach</tbody></table></div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){ $('#commit-import').on('click',function(){var b=$(this);Swal.fire({icon:'question',title:'ยืนยันนำเข้า Opening Balance?',text:'ระบบจะสร้างทะเบียนสินทรัพย์และไม่สร้าง Journal',showCancelButton:true,confirmButtonText:'ยืนยันนำเข้า',cancelButtonText:'กลับ'}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.post(b.data('url'),{_token:@json(csrf_token())}).done(function(x){Swal.fire({icon:'success',title:x.msg}).then(function(){location.href=x.redirect;});}).fail(window.erpAjaxError).always(function(){b.prop('disabled',false);});});});});</script>
@endpush
