@extends('Pos::layout')
@section('title', $advanceDeposit->document_number.' | POS')
@section('content')
@php($labels=['DRAFT'=>'ร่าง','POSTED'=>'พร้อมใช้','PARTIAL'=>'ใช้บางส่วน','APPLIED'=>'ใช้ครบแล้ว','VOID'=>'ยกเลิก'])
@php($statusBadges=['DRAFT'=>'app-badge-soft','POSTED'=>'app-badge-success','PARTIAL'=>'app-badge-info','APPLIED'=>'app-badge-success','VOID'=>'text-bg-danger'])
@php($activeApplications = $advanceDeposit->applications->whereNull('reversed_at'))
@php($canRefund = in_array($advanceDeposit->status, ['POSTED', 'PARTIAL'], true) && $activeApplications->isEmpty() && $advanceDeposit->tenders->isNotEmpty())
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">POS / ADVANCE DEPOSIT</p>
    <div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 mb-2">{{ $advanceDeposit->document_number }}</h1><span class="badge app-badge-info">ใบรับเงินล่วงหน้า</span> <span class="badge {{ $statusBadges[$advanceDeposit->status] ?? 'app-badge-soft' }}">{{ $labels[$advanceDeposit->status] ?? $advanceDeposit->status }}</span></div><div class="d-flex flex-wrap gap-2">@if($advanceDeposit->journalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-app-soft" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $advanceDeposit->journalEntry) }}"><i class="bx bx-book-open me-1" aria-hidden="true"></i>ดู GL</button>@endif @if($canRefund && auth()->user()->hasPermission('pos.advance-deposits.refund'))<button class="btn btn-outline-danger js-advance-deposit-cancel" id="refund-advance-deposit" type="button">ยกเลิกเอกสาร</button>@endif @if(auth()->user()->hasPermission('pos.advance-deposits.print'))<a class="btn btn-app-soft" target="_blank" href="{{ route('pos.advance-deposits.pdf',$advanceDeposit) }}">พิมพ์ PDF</a>@endif<a class="btn btn-outline-secondary" href="{{ route('pos.advance-deposits.index') }}">ย้อนกลับ</a></div></div>
    @if(!$canRefund && $advanceDeposit->status !== 'VOID')<div class="alert alert-warning">ไม่สามารถคืนเงินใบรับเงินล่วงหน้านี้ได้: ต้องมีสถานะพร้อมใช้/ใช้บางส่วนที่ไม่มีรายการตัดเงินรับล่วงหน้าที่ยังใช้งานอยู่ และต้องมีช่องทางรับเงินเดิม</div>@endif
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="row g-3"><div class="col-md-4"><div class="small text-secondary">ลูกค้า</div><strong>{{ $advanceDeposit->party?->code }} · {{ $advanceDeposit->party?->name }}</strong></div><div class="col-md-2"><div class="small text-secondary">วันที่เอกสาร</div>{{ $advanceDeposit->document_date?->format($dateFormat) }}</div><div class="col-md-2"><div class="small text-secondary">VAT</div>{{ $advanceDeposit->prices_include_vat ? 'ราคารวม VAT' : 'ไม่รวม VAT' }}</div><div class="col-md-2"><div class="small text-secondary">ยอด WHT</div>{{ number_format((float)($advanceDeposit->withholding_amount ?? 0),2) }}</div><div class="col-md-2"><div class="small text-secondary">ยอดรับ</div><strong>{{ number_format((float)$advanceDeposit->original_amount,2) }}</strong></div></div></div></div>
    <div class="row g-3 mb-4"><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><div class="small text-secondary">ยอดตั้งต้น</div><div class="h4 mb-0">{{ number_format((float) $advanceDeposit->original_amount, 2) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><div class="small text-secondary">ใช้ไปแล้ว</div><div class="h4 mb-0">{{ number_format((float) $advanceDeposit->applied_amount, 2) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm h-100 border-start border-4 border-primary"><div class="card-body p-4"><div class="small text-secondary">ยอดคงเหลือใช้ได้</div><div class="h4 mb-0 text-primary">{{ number_format((float) $remainingAmount, 2) }}</div></div></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-0">รายละเอียดการรับเงิน</h2><small class="text-secondary">ช่องทางรับเงินที่บันทึกพร้อมใบรับเงินล่วงหน้า</small></div>@if($advanceDeposit->journalEntry)<span class="badge app-badge-success">Post GL แล้ว · {{ $advanceDeposit->journalEntry->entry_number }}</span>@endif</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>บัญชีเงินสด/ธนาคาร</th><th>เลขอ้างอิง</th><th class="text-end">จำนวนเงิน</th></tr></thead><tbody>@forelse($advanceDeposit->tenders as $tender)<tr><td>{{ $tender->bankAccount?->code ?: '—' }} · {{ $tender->bankAccount?->name ?: '—' }}</td><td>{{ $tender->reference ?: '—' }}</td><td class="text-end fw-semibold">{{ number_format((float) $tender->amount, 2) }}</td></tr>@empty<tr><td colspan="3" class="text-center text-secondary">ไม่พบรายละเอียดช่องทางรับเงิน</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5">ประวัติการใช้เงินรับล่วงหน้ากับ HS</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>วันที่</th><th>ใบขาย HS</th><th class="text-end">ยอดที่ใช้</th><th>Journal</th><th>สถานะ</th></tr></thead><tbody>@forelse($advanceDeposit->applications as $application)<tr><td>{{ $application->application_date?->format($dateFormat) ?: '—' }}</td><td>{{ $application->physicalSale?->document_number ?: '—' }}</td><td class="text-end">{{ number_format((float)$application->amount,2) }}</td><td>@if($application->journalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<a href="{{ route('accounting.journal-preview.show',$application->journalEntry) }}">{{ $application->journalEntry->entry_number }}</a>@else{{ $application->journalEntry?->entry_number ?: '—' }}@endif</td><td><span class="badge {{ $application->reversed_at ? 'text-bg-danger' : 'app-badge-success' }}">{{ $application->reversed_at ? 'กลับรายการแล้ว' : 'ใช้แล้ว' }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary">ยังไม่มีการนำเงินรับล่วงหน้าไปใช้กับ HS</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@if($canRefund && auth()->user()->hasPermission('pos.advance-deposits.refund'))<div class="modal fade" id="advance-deposit-refund-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="advance-deposit-refund-form" method="post" action="{{ route('pos.advance-deposits.refund',$advanceDeposit) }}">@csrf<div class="modal-header"><h2 class="h5 mb-0">ยกเลิกเอกสารรับเงินล่วงหน้า</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-warning">ยกเลิกได้เฉพาะใบรับเงินล่วงหน้าที่ยังไม่มีรายการตัดที่ใช้งานอยู่ และวันที่กลับรายการต้องอยู่ในงวดบัญชีที่เปิดอยู่ ระบบจะคืนเงินเข้าบัญชีเงินสด/ธนาคารเดิมทุกช่องทางตามยอดเดิม</div><div class="row g-3"><div class="col-md-4"><label class="form-label">วันที่กลับรายการ</label><input class="form-control" type="date" name="refund_date" value="{{ today()->format('Y-m-d') }}" required></div><div class="col-md-8"><label class="form-label">ช่องทางคืนเงิน</label><div class="border rounded-3 p-2">@foreach($advanceDeposit->tenders as $tender)<div class="d-flex justify-content-between gap-3"><span>{{ $tender->bankAccount?->code }} · {{ $tender->bankAccount?->name }}</span><strong>{{ number_format((float) $tender->amount, 2) }}</strong></div>@endforeach</div></div><div class="col-12"><label class="form-label">เหตุผล</label><textarea class="form-control" name="reason" rows="3" minlength="10" required></textarea></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">กลับ</button><button class="btn btn-danger js-advance-deposit-cancel" type="submit">ยกเลิกเอกสาร</button></div></form></div></div></div>@endif
@endsection
@push('scripts')<script>$(function(){const modal=$('#advance-deposit-refund-modal'),form=$('#advance-deposit-refund-form');$('#refund-advance-deposit').on('click',()=>bootstrap.Modal.getOrCreateInstance(modal[0]).show());form.on('submit',function(e){e.preventDefault();const button=form.find('[type="submit"]');if(button.data('submitting'))return;button.data('submitting',true).prop('disabled',true);$.post(form.attr('action'),form.serialize()).done(r=>Swal.fire({icon:'success',text:r.msg}).then(()=>location.reload())).fail(xhr=>Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ไม่สามารถคืนเงินใบรับเงินล่วงหน้าได้'})).always(()=>button.data('submitting',false).prop('disabled',false));});});</script>@endpush
