@extends('Settings::layout')
@section('title', 'Document Templates | New ERP')
@section('content')
<style>
    #template-sections .template-section { flex-wrap: wrap !important; padding: .75rem !important; background: #fff; }
    #template-sections .template-section > .layout-properties { flex: 0 0 100%; }
    #template-sections .template-section > select { min-width: 0; flex: 1 1 180px; }
    #template-sections .template-section > select:first-of-type { flex-basis: 150px; }
    #template-sections .layout-properties { border-top: 1px solid var(--bs-border-color); padding-top: .65rem; }
    #template-sections .layout-properties > * { flex: 1 1 130px; min-width: 0; }
    #template-sections .layout-properties .form-check { flex: 0 0 auto; }
    @media (max-width: 575.98px) {
        #template-sections .template-section > select { flex-basis: calc(100% - 42px); }
        #template-sections .template-section > select:first-of-type { flex-basis: calc(100% - 42px); }
        #template-sections .layout-properties > * { flex-basis: 100%; max-width: none !important; }
    }
</style>
<div class="container-fluid px-3 px-lg-4 py-4" id="template-builder">
    <div class="mb-4"><p class="eyebrow mb-2">GLOBAL SETTINGS / DOCUMENT TEMPLATES</p><h1 class="h3 mb-1">Document Templates</h1><p class="text-secondary mb-0">ออกแบบเอกสารด้วย Section และ Field โดยไม่ต้องเขียน JSON</p></div>
    @if($formMode ?? false)<div class="mb-3 d-flex gap-2"><a class="btn btn-sm btn-outline-secondary" href="{{ route('settings.document-templates.index') }}">← กลับรายการ Template</a>@if($editVersion)<a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ route('settings.document-templates.preview-version', $editVersion) }}"><i class="bx bx-file me-1"></i>Preview PDF</a>@endif</div>@else<div class="d-flex justify-content-end mb-3"><a class="btn btn-dark" href="{{ route('settings.document-templates.create') }}"><i class="bx bx-plus me-1"></i>สร้าง Template ใหม่</a></div>@endif
    <div class="row g-4">
        @if(!($formMode ?? false))<div class="col-xl-7"><div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">Template ที่มีอยู่</h2><div class="vstack gap-2">
        @forelse($templates as $template)
            @php($latest = $template->versions->first())
            <div class="border rounded p-3 d-flex justify-content-between align-items-center">
                <div><div class="fw-semibold">{{ $template->name }} @if($template->is_default)<span class="badge app-status-success ms-1">Default</span>@endif</div><small class="text-secondary">{{ $template->document_type }} · {{ $template->versions->count() }} version</small></div>
                <div class="text-end"><span class="badge app-status-neutral">{{ $template->status }}</span><div class="small text-secondary mt-1">{{ $latest?->status ?? 'ยังไม่มี version' }}</div>
                    @if($latest)
                        <a class="btn btn-sm btn-outline-secondary mt-2" target="_blank" href="{{ route('settings.document-templates.preview-version', $latest) }}">Preview</a>
                        @if($latest->status === 'DRAFT')
                    <a class="btn btn-sm btn-outline-primary mt-2" href="{{ route('settings.document-templates.edit', $latest) }}">แก้ไข Draft</a>
                            <form method="post" action="{{ route('settings.document-templates.publish', $latest) }}" class="d-inline">@csrf<button class="btn btn-sm btn-app-soft mt-2" type="submit">Publish v{{ $latest->version }}</button></form>
                        @else
                            <form method="post" action="{{ route('settings.document-templates.new-version', $template) }}" class="d-inline">@csrf<button class="btn btn-sm btn-outline-primary mt-2" type="submit">สร้าง Version ใหม่</button></form>
                        @endif
                    @endif
                    <form method="post" action="{{ route('settings.document-templates.archive', $template) }}" class="d-inline" onsubmit="return confirm('Archive Template นี้หรือไม่? เอกสารเดิมจะไม่ถูกลบ')">@csrf<button class="btn btn-sm btn-outline-danger mt-2" type="submit">Archive</button></form>
                </div>
            </div>
        @empty
            <div class="text-secondary py-3">ยังไม่มี Custom Template</div>
        @endforelse
        </div></div></div></div>@endif
        @if($formMode ?? false)<div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">{{ $editVersion ? 'แก้ไข Template Draft v'.$editVersion->version : 'สร้าง Template Draft' }}</h2><form id="template-form" method="post" action="{{ $editVersion ? route('settings.document-templates.update', $editVersion) : route('settings.document-templates.store') }}">@csrf @if($editVersion) @method('PUT') @endif
            <div class="mb-3"><label class="form-label">ประเภทเอกสาร</label><select class="form-select" name="document_type" required @if($editVersion) disabled @endif>@foreach($documentTypes as $type)<option value="{{ $type }}" @selected(($editVersion?->template?->document_type ?? $documentTypes[0]) === $type)>{{ $type }}</option>@endforeach</select></div>
            <div class="mb-3"><label class="form-label">ชื่อ Template</label><input class="form-control" name="name" value="{{ $editVersion?->template?->name }}" required maxlength="160" placeholder="เช่น PO บริษัทหลัก" @if($editVersion) disabled @endif></div>
            <div class="mb-3"><div class="d-flex justify-content-between align-items-center mb-2"><label class="form-label mb-0">Layout Sections</label><button class="btn btn-sm btn-outline-secondary" type="button" id="add-template-section"><i class="bx bx-plus me-1"></i>เพิ่ม Section</button></div><div id="template-sections" class="vstack gap-2"></div><input type="hidden" name="definition" id="template-definition"><div class="form-text">ลากเพื่อจัดลำดับ Section ได้</div></div>
            @unless($editVersion)<div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_default" value="1" id="template-default"><label class="form-check-label" for="template-default">ใช้เป็น Default Template</label></div>@endunless
            <div class="d-flex gap-2"><button class="btn btn-outline-secondary" id="template-preview-button" type="button">ดู Preview</button><button class="btn btn-dark" type="submit">{{ $editVersion ? 'บันทึกการแก้ไข' : 'บันทึก Draft' }}</button></div>
        </form></div></div><div class="card border-0 shadow-sm mt-4"><div class="card-body p-4"><h2 class="h5 mb-3">Field ที่ใช้ได้</h2><div class="d-flex flex-wrap gap-2">@foreach($fields as $field => $meta)<span class="badge app-badge-soft font-monospace">{{ $field }}</span>@endforeach</div></div></div></div>
        <div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">Preview</h2><p class="small text-secondary mb-0">ใช้ sample data เท่านั้น</p></div><span class="badge app-status-neutral" id="preview-status">ยังไม่ได้ Preview</span></div><div id="template-preview" class="bg-light rounded p-3"><div class="text-secondary text-center py-5">กด “ดู Preview” เพื่อแสดงตัวอย่างเอกสาร</div></div></div></div></div>@endif
    </div>
</div>
@endsection
@push('scripts')
@php($initialSections = $editVersion?->definition['sections'] ?? [['type' => 'text', 'field' => 'company.name'], ['type' => 'field', 'field' => 'document.number'], ['type' => 'table', 'field' => 'lines'], ['type' => 'totals', 'field' => 'totals.grand_total']])
<script>$(function(){var f=$('#template-form'),b=$('#template-preview-button'),box=$('#template-preview'),status=$('#preview-status'),sections=$('#template-sections'),fields=@json(array_keys($fields)),initial=@json($initialSections);function sync(){var out=[];sections.find('.template-section').each(function(){var q=$(this).find('select');out.push({type:q.eq(0).val(),field:q.eq(1).val()});});$('#template-definition').val(JSON.stringify({sections:out}));}function row(type,field){var r=$('<div class="border rounded p-2 d-flex gap-2 align-items-center template-section" draggable="true"></div>'),t=$('<select class="form-select form-select-sm" style="max-width:150px"><option value="text">ข้อความ</option><option value="field">Field</option><option value="image">รูปภาพ</option><option value="table">ตารางรายการ</option><option value="totals">ยอดรวม</option><option value="signature">ลายเซ็น</option></select>').val(type||'field'),s=$('<select class="form-select form-select-sm"></select>');fields.forEach(function(x){s.append($('<option>').val(x).text(x));});s.val(field||fields[0]);r.append($('<span class="text-secondary">☷</span>'),t,s,$('<button type="button" class="btn btn-sm btn-outline-danger" aria-label="ลบ section"><i class="bx bx-trash"></i></button>'));r.find('button').on('click',function(){r.remove();sync();});r.find('select').on('change',sync);sections.append(r);}initial.forEach(function(x){row(x.type,x.field);});sync();$('#add-template-section').on('click',function(){row();sync();});b.on('click',function(){sync();b.prop('disabled',true);status.text('กำลังสร้าง Preview…');var data=f.serializeArray().filter(function(x){return x.name !== '_method';});if(!data.some(function(x){return x.name === 'document_type';}))data.push({name:'document_type',value:f.find('[name="document_type"]').val()});$.post('{{ route('settings.document-templates.preview') }}',$.param(data)).done(function(html){box.html(html);status.text('Preview จาก Sample Data').removeClass('app-status-danger').addClass('app-status-success');}).fail(function(x){box.html('<div class="alert alert-danger mb-0">'+(x.responseJSON?.message||'Definition ไม่ถูกต้อง')+'</div>');status.text('ตรวจสอบ Definition').removeClass('app-status-neutral').addClass('app-status-danger');}).always(function(){b.prop('disabled',false);});});f.on('submit',function(){sync();});var drag=null;sections.on('dragstart',function(e){drag=e.target.closest('.template-section');$(drag).addClass('opacity-50');});sections.on('dragover',function(e){e.preventDefault();var r=e.target.closest('.template-section');if(!drag||!r||r===drag)return;var rect=r.getBoundingClientRect();sections[0].insertBefore(drag,e.clientY<rect.top+rect.height/2?r:r.nextSibling);sync();});sections.on('dragend',function(){if(drag)$(drag).removeClass('opacity-50');drag=null;sync();});});</script>
<script>$(function(){var sections=$('#template-sections'),initial=@json($initialSections);function enhance(){sections.find('.template-section').each(function(i){var r=$(this);if(r.find('.layout-properties').length)return;var x=initial[i]||{};var p=$('<div class="layout-properties d-flex flex-wrap gap-2 mt-2 w-100"></div>');p.append($('<select class="form-select form-select-sm layout-align" style="max-width:120px"><option value="left">ซ้าย</option><option value="center">กลาง</option><option value="right">ขวา</option></select>').val(x.align||'left'));p.append($('<input class="form-control form-control-sm layout-spacing" type="number" min="0" max="100" placeholder="ระยะห่าง px" style="max-width:130px">').val(x.spacing||0));p.append($('<input class="form-control form-control-sm layout-size" type="number" min="10" max="300" placeholder="ขนาดรูป px" style="max-width:130px">').val(x.size||''));p.append($('<input class="form-control form-control-sm layout-label" maxlength="120" placeholder="Label (ถ้ามี)" style="max-width:180px">').val(x.label||''));p.append($('<label class="form-check form-check-inline small pt-1"><input class="form-check-input layout-visible" type="checkbox" checked> แสดง</label>'));r.append(p);p.on('change input',syncLayout);r.children('select').off('change.layout').on('change.layout',function(){setTimeout(syncLayout,0);});});}function syncLayout(){var out=[];sections.find('.template-section').each(function(){var r=$(this),q=r.children('select'),p=r.find('.layout-properties');out.push({type:q.eq(0).val(),field:q.eq(1).val(),align:p.find('.layout-align').val()||'left',spacing:Number(p.find('.layout-spacing').val()||0),size:Number(p.find('.layout-size').val()||0),label:p.find('.layout-label').val()||'',visible:p.find('.layout-visible').prop('checked')});});$('#template-definition').val(JSON.stringify({sections:out}));}enhance();$('#add-template-section').on('click',function(){setTimeout(function(){enhance();syncLayout();},0);});$('#template-form').on('submit',function(){enhance();syncLayout();});});</script>
@if($editVersion)<script>$(function(){setTimeout(function(){$('#template-preview-button').trigger('click');},100);});</script>@endif
@if($editVersion)<script>$(function(){var f=$('#template-form'),save=f.find('button[type="submit"]');f.on('submit.templateAjax',function(e){e.preventDefault();save.prop('disabled',true).text('กำลังบันทึก…');$.ajax({url:f.attr('action'),method:'POST',data:f.serialize(),dataType:'json',headers:{Accept:'application/json'}}).done(function(){save.text('บันทึกแล้ว');$('#preview-status').text('กำลังอัปเดต Preview…');$('#template-preview-button').trigger('click');setTimeout(function(){save.prop('disabled',false).text('บันทึกการแก้ไข');},800);}).fail(function(x){save.prop('disabled',false).text('บันทึกการแก้ไข');$('#preview-status').text(x.responseJSON?.message||'บันทึกไม่สำเร็จ').removeClass('app-status-neutral').addClass('app-status-danger');});});});</script>@endif
@endpush
