@extends('Accounting::layout')
@section('title', 'กระทบยอด AR/AP | New ERP')
@section('content')
@php($defaultPeriod = $periods->first(fn ($period) => now()->between($period->start_date, $period->end_date)) ?: $periods->first())
@php($selectedPeriodId = (int) request('period_id', optional($defaultPeriod)->id))
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">ACCOUNTING / RECONCILIATION</p><h1 class="h3 mb-2">กระทบยอด AR/AP</h1><p class="text-secondary mb-0">ตรวจสอบยอดลูกหนี้และเจ้าหนี้ใน GL เทียบกับ Subledger</p></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">ตัวกรองรายงาน</h2><button type="button" class="btn btn-outline-secondary btn-sm" id="report-filter-reset"><i class="bx bx-reset me-1"></i>ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-12 col-md-4"><label class="form-label">งวดบัญชี</label><select class="form-select" id="recon-period">@foreach($periods as $period)<option value="{{ $period->id }}" @selected($period->id === $selectedPeriodId)>{{ $period->fiscalYear->name }} / {{ $period->name }}</option>@endforeach</select></div><div class="col-12 col-md-4"><label class="form-label">สาขา</label><select class="form-select" id="report-branch"><option value="current">สาขาปัจจุบัน</option><option value="all">ทุกสาขาที่มีสิทธิ์</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->code }} · {{ $branch->name }}</option>@endforeach</select></div><div class="col-12 col-md-4"><label class="form-label">คลัง</label><select class="form-select" id="report-warehouse"><option value="">ทุกคลังที่มีสิทธิ์</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->code }} · {{ $warehouse->name }}</option>@endforeach</select></div></div></div></div>
    <div class="row g-3 mb-4">@foreach([['gl_balance','ยอด GL'],['subledger_balance','ยอด Subledger'],['difference','ผลต่าง']] as [$key,$label])<div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">{{ $label }}</div><div class="h5 mb-0" data-total="{{ $key }}">0.00</div></div></div></div>@endforeach</div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="ar-ap-reconciliation-table" data-url="{{ route('accounting.reports.ar-ap-reconciliation.data') }}"><thead><tr><th>ประเภท</th><th>รหัสบัญชี</th><th>ชื่อบัญชี</th><th class="text-end">ยอด GL</th><th class="text-end">ยอด Subledger</th><th class="text-end">ผลต่าง</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){var t=$('#ar-ap-reconciliation-table'),p=$('#recon-period'),br=$('#report-branch'),w=$('#report-warehouse'),x=$.fn.dataTable.render.text();var dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.period_id=p.val();d.branch_scope=br.val();d.warehouse_id=w.val()},dataSrc:function(r){$.each(r.totals||{},function(k,v){$('[data-total="'+k+'"]').text(window.erpAccountingFormat(v))});return r.data}},order:[[1,'asc']],buttons:[window.erpExcelButton(t,function(){return{period_id:p.val(),branch_scope:br.val(),warehouse_id:w.val()}})],columns:[{data:'control_account_type',name:'accounts.control_account_type',render:x.display},{data:'code',name:'accounts.code',render:x.display},{data:'name',name:'accounts.name',render:x.display},{data:'gl_balance',name:'gl_balance',className:'text-end',render:x.display},{data:'subledger_balance',name:'subledger_balance',className:'text-end',render:x.display},{data:'difference',name:'difference',className:'text-end',render:x.display},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,t,row){return t==='display'?'<a class="btn btn-sm btn-outline-dark" href="'+x.display(row.account_url)+'">ดู GL</a>':'';}}]}));p.add(br).add(w).on('change',function(){dt.ajax.reload()});$('#report-filter-reset').on('click',function(){p.val('{{ $selectedPeriodId }}');br.val('current');w.val('');dt.ajax.reload()})});</script>@endpush
