@extends('Accounting::layout')
@section('title', 'งบดุล | New ERP')
@section('content')
@php($selectedPeriod = $periods->first(fn ($period) => now()->between($period->start_date, $period->end_date)) ?: $periods->first())
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">ACCOUNTING / BALANCE SHEET</p><h1 class="h3 mb-2">งบดุล</h1><p class="text-secondary mb-0">ฐานะการเงิน ณ วันสิ้นงวด พร้อมกำไร(ขาดทุน)สะสมที่คำนวณจาก GL</p></div>
    <div class="card border-0 shadow-sm mb-4" id="balance-sheet-filters"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">ตัวกรองรายงาน</h2><button type="button" class="btn btn-outline-secondary btn-sm" id="report-filter-reset"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3">
        <div class="col-12 col-md-4"><label class="form-label" for="bs-period">งวดบัญชี</label><select class="form-select" id="bs-period">@foreach ($periods as $period)<option value="{{ $period->id }}" @selected($period->id === (int) request('period_id', $selectedPeriod?->id))>{{ $period->fiscalYear->name }} / {{ $period->name }}</option>@endforeach</select></div>
        <div class="col-12 col-md-4"><label class="form-label" for="report-branch">สาขา</label><select class="form-select" id="report-branch"><option value="current" @selected(request('branch_scope', 'current') === 'current')>สาขาปัจจุบัน</option><option value="all" @selected(request('branch_scope') === 'all')>ทุกสาขาที่มีสิทธิ์</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string) request('branch_scope') === (string) $branch->id)>{{ $branch->code }} · {{ $branch->name }}</option>@endforeach</select></div>
        <div class="col-12 col-md-4"><label class="form-label" for="report-warehouse">คลัง</label><select class="form-select" id="report-warehouse"><option value="">ทุกคลังที่มีสิทธิ์</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected((int) request('warehouse_id') === (int) $warehouse->id)>{{ $warehouse->code }} · {{ $warehouse->name }}</option>@endforeach</select></div>
    </div></div></div>
    <div class="row g-3 mb-4">@foreach ([['assets','สินทรัพย์'],['liabilities','หนี้สิน'],['equity','ทุนรวมกำไรสุทธิ'],['net_profit','กำไร(ขาดทุน)สะสม'],['difference','ผลต่างตรวจสอบ']] as [$key,$label])<div class="col-6 col-xl"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">{{ $label }}</div><div class="h5 mb-0" data-total="{{ $key }}">0</div></div></div></div>@endforeach</div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><table class="table table-hover align-middle w-100" id="balance-sheet-table" data-url="{{ route('accounting.reports.balance-sheet.data') }}" data-export-url="{{ route('accounting.reports.balance-sheet.export') }}"><thead><tr><th>หมวด</th><th>รหัสบัญชี</th><th>ชื่อบัญชี</th><th class="text-end">เดบิต</th><th class="text-end">เครดิต</th><th class="text-end">ยอดคงเหลือ</th><th class="text-end">ดู GL</th></tr></thead></table></div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){var t=$('#balance-sheet-table'),p=$('#bs-period'),br=$('#report-branch'),w=$('#report-warehouse'),x=$.fn.dataTable.render.text(),dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.period_id=p.val();d.branch_scope=br.val();d.warehouse_id=w.val()},dataSrc:function(r){$.each(r.totals||{},function(k,v){$('[data-total="'+k+'"]').text(window.erpAccountingFormat(v))});return r.data}},order:[[1,'asc']],buttons:[window.erpExcelButton(t,function(){return{period_id:p.val(),branch_scope:br.val(),warehouse_id:w.val()}})],columns:[{data:'account_type_name',name:'account_types.name',render:x.display},{data:'code',name:'accounts.code',render:x.display},{data:'name',name:'accounts.name',render:x.display},{data:'debit',name:'movement.debit',className:'text-end',render:x.display},{data:'credit',name:'movement.credit',className:'text-end',render:x.display},{data:'amount',name:'amount',className:'text-end',render:x.display},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,t,r){return t==='display'?'<a class="btn btn-sm btn-outline-dark" href="'+x.display(r.account_url)+'"><i class="bx bx-book-open me-1" aria-hidden="true"></i>ดู GL</a>':'';}}]}));p.add(br).add(w).on('change',function(){dt.ajax.reload()});$('#report-filter-reset').on('click',function(){br.val('current');w.val('');dt.ajax.reload()})});</script>
@endpush
