@extends('Accounting::layout')
@section('title', 'กระแสเงินสด | New ERP')
@section('content')
@php($selectedPeriodId = (int) ($selectedPeriodId ?? request('period_id')))
<div class="container-fluid px-3 px-lg-4 py-4">
<div class="mb-4"><p class="eyebrow mb-2">ACCOUNTING / FINANCIAL REPORTS</p><h1 class="h3 mb-2">รายงานกระแสเงินสด</h1><p class="text-secondary mb-0">สรุปเงินเข้าและเงินออกจาก Journal ที่ Post แล้ว</p></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">ตัวกรองรายงาน</h2><button class="btn btn-outline-secondary btn-sm" id="cash-flow-reset" type="button">ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-md-3"><label class="form-label">งวดบัญชี</label><select class="form-select" id="cash-flow-period">@foreach($periods as $period)<option value="{{ $period->id }}" @selected($period->id === $selectedPeriodId)>{{ $period->fiscalYear->name }} / {{ $period->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">สาขา</label><select class="form-select" id="cash-flow-branch"><option value="current">สาขาปัจจุบัน</option><option value="all">ทุกสาขาที่มีสิทธิ์</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->code }} · {{ $branch->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">คลัง</label><select class="form-select" id="cash-flow-warehouse"><option value="">ทุกคลังที่มีสิทธิ์</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->code }} · {{ $warehouse->name }}</option>@endforeach</select></div></div></div></div>
<div class="row g-3 mb-4">@foreach([['debit','เงินเข้า'],['credit','เงินออก'],['net','กระแสเงินสดสุทธิ']] as [$key,$label])<div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">{{ $label }}</div><div class="h4 mb-0" data-cash-total="{{ $key }}">0.00</div></div></div></div>@endforeach</div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><table class="table table-hover align-middle w-100" id="cash-flow-table" data-url="{{ route('accounting.reports.cash-flow.data') }}"><thead><tr><th>บัญชีเงินสด/ธนาคาร</th><th class="text-end">เงินเข้า (Debit)</th><th class="text-end">เงินออก (Credit)</th><th class="text-end">สุทธิ</th></tr></thead></table></div></div></div>
@endsection
@push('scripts')<script>$(function(){var t=$('#cash-flow-table'),p=$('#cash-flow-period'),b=$('#cash-flow-branch'),w=$('#cash-flow-warehouse'),x=$.fn.dataTable.render.text(),dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.period_id=p.val();d.branch_scope=b.val();d.warehouse_id=w.val()},dataSrc:function(r){$.each(r.totals||{},function(k,v){$('[data-cash-total="'+k+'"]').text(window.erpAccountingFormat(v))});return r.data}},order:[[0,'asc']],buttons:[window.erpExcelButton(t,function(){return{period_id:p.val(),branch_scope:b.val(),warehouse_id:w.val()}})],columns:[{data:null,name:'accounts.code',render:function(v,t,row){return t==='display'?x.display(row.code+' · '+row.name):row.code}},{data:'debit',name:'debit',className:'text-end',render:x.display},{data:'credit',name:'credit',className:'text-end',render:x.display},{data:'net',name:'net',className:'text-end',render:x.display}]}));p.add(b).add(w).on('change',function(){dt.ajax.reload()});$('#cash-flow-reset').on('click',function(){p.val('{{ $selectedPeriodId }}');b.val('current');w.val('');dt.ajax.reload()})});</script>@endpush
