@extends('Accounting::layout')
@section('title', 'Posting Error / Exception | New ERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">ACCOUNTING / AUDIT & CONTROL</p><h1 class="h3 mb-2">Posting Error / Exception</h1><p class="text-secondary mb-0">ตรวจสอบรายการที่ระบบ Post ไม่สำเร็จและดำเนินการแก้ไข</p></div><a class="btn btn-outline-secondary" href="{{ route('accounting.workflow.index') }}"><i class="bx bx-map-alt me-1"></i>เปิดคู่มือการทำงาน</a></div>
<div class="card border-0 shadow-sm mb-4" id="posting-exception-filters"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">ตัวกรอง</h2><button class="btn btn-sm btn-outline-secondary" id="posting-exception-reset" type="button"><i class="bx bx-reset me-1"></i>ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-12 col-md-3"><label class="form-label" for="posting-exception-module">Module</label><select class="form-select" id="posting-exception-module"><option value="">ทุก Module</option><option value="Asset">Asset</option></select></div><div class="col-12 col-md-3"><label class="form-label" for="posting-exception-branch">สาขา</label><select class="form-select" id="posting-exception-branch"><option value="">สาขาปัจจุบัน</option><option value="all">ทุกสาขาที่มีสิทธิ์</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->code }} · {{ $branch->name }}</option>@endforeach</select></div><div class="col-12 col-md-3"><label class="form-label" for="posting-exception-date-from">วันที่เริ่มต้น</label><input class="form-control" type="date" id="posting-exception-date-from"></div><div class="col-12 col-md-3"><label class="form-label" for="posting-exception-date-to">วันที่สิ้นสุด</label><input class="form-control" type="date" id="posting-exception-date-to"></div></div></div></div>
    <div class="row g-3 mb-4"><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3"><div class="small text-secondary">รายการ Error</div><div class="h4 mb-0" data-exception-total>0</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3"><div class="small text-secondary">สถานะ</div><div class="h4 mb-0 text-warning">ต้องตรวจสอบ</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3"><div class="small text-secondary">แหล่งข้อมูล</div><div class="h6 mb-0">Posting Services</div></div></div></div></div>
    <div class="alert alert-info border-0 shadow-sm"><i class="bx bx-info-circle me-1"></i>ขณะนี้แสดง Error ที่บันทึกจาก Asset Depreciation Runs สถานะ FAILED และจะขยายไปยัง Posting Services อื่นตามลำดับ</div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><table class="table table-hover align-middle w-100" id="posting-exceptions-table" data-url="{{ route('accounting.reports.posting-exceptions.data') }}"><thead><tr><th>เอกสาร</th><th>Module</th><th>งวด</th><th>วันที่</th><th>ข้อความผิดพลาด</th><th class="text-end">จัดการ</th></tr></thead></table></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){var t=$('#posting-exceptions-table'),m=$('#posting-exception-module'),b=$('#posting-exception-branch'),f=$('#posting-exception-date-from'),to=$('#posting-exception-date-to'),x=$.fn.dataTable.render.text();var dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.module=m.val();d.branch_id=b.val();d.date_from=f.val();d.date_to=to.val()},dataSrc:function(r){$('[data-exception-total]').text(Number(r.recordsFiltered||0).toLocaleString('en-US'));return r.data}},order:[[3,'desc']],buttons:[window.erpExcelButton(t,function(){return{module:m.val(),branch_id:b.val(),date_from:f.val(),date_to:to.val()}})],columns:[{data:'document_number',name:'runs.document_number',render:x.display},{data:null,render:function(){return 'Asset'}},{data:'period_name',name:'fiscal_periods.name',render:x.display},{data:'run_through_date',name:'runs.run_through_date',render:x.display},{data:'error_message',name:'runs.error_message',render:x.display},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,type,row){return type==='display'?'<a class="btn btn-sm btn-outline-dark" target="_blank" href="'+x.display(row.show_url)+'"><i class="bx bx-link-external me-1"></i>เปิดเอกสาร</a>':'';}}]}));m.add(b).add(f).add(to).on('change',function(){dt.ajax.reload()});$('#posting-exception-reset').on('click',function(){m.val('');b.val('');f.val('');to.val('');dt.ajax.reload()})});</script>@endpush
