@extends('Accounting::layout')
@section('title', 'งบกำไรขาดทุน | New ERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">ACCOUNTING / PROFIT & LOSS</p><h1 class="h3 mb-2">งบกำไรขาดทุน</h1><p class="text-secondary mb-0">รายได้และค่าใช้จ่ายจากรายการที่ลงบัญชีแล้ว</p></div><div class="col-12 col-md-4"><label class="form-label" for="pl-period">งวดบัญชี</label><select class="form-select" id="pl-period">@foreach ($periods as $period)<option value="{{ $period->id }}">{{ $period->fiscalYear->name }} / {{ $period->name }}</option>@endforeach</select></div></div>
    <div class="row g-3 mb-4">@foreach ([['revenue','รายได้'],['expense','ค่าใช้จ่าย'],['net_profit','กำไร(ขาดทุน)สุทธิ']] as [$key,$label])<div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">{{ $label }}</div><div class="h5 mb-0" data-total="{{ $key }}">0.00</div></div></div></div>@endforeach</div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><table class="table table-hover align-middle w-100" id="profit-loss-table" data-url="{{ route('accounting.reports.profit-loss.data') }}" data-export-url="{{ route('accounting.reports.profit-loss.export') }}"><thead><tr><th>ประเภท</th><th>รหัสบัญชี</th><th>ชื่อบัญชี</th><th class="text-end">เดบิต</th><th class="text-end">เครดิต</th><th class="text-end">จำนวนเงิน</th><th class="text-end">ดู GL</th></tr></thead></table></div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){var t=$('#profit-loss-table'),p=$('#pl-period'),x=$.fn.dataTable.render.text(),dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.period_id=p.val()},dataSrc:function(r){$.each(r.totals||{},function(k,v){$('[data-total="'+k+'"]').text(v||'0.00')});return r.data}},order:[[1,'asc']],buttons:[window.erpExcelButton(t,function(){return{period_id:p.val()}})],columns:[{data:'line_type',name:'line_type',render:x.display},{data:'code',name:'accounts.code',render:x.display},{data:'name',name:'accounts.name',render:x.display},{data:'debit',name:'movement.debit',className:'text-end',render:x.display},{data:'credit',name:'movement.credit',className:'text-end',render:x.display},{data:'amount',name:'amount',className:'text-end',render:x.display},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,t,r){return t==='display'?'<a class="btn btn-sm btn-outline-dark" href="'+x.display(r.account_url)+'"><i class="bx bx-book-open me-1" aria-hidden="true"></i>ดู GL</a>':'';}}]}));p.on('change',function(){dt.ajax.reload()})});</script>
@endpush
