@extends('Accounting::layout')
@section('title', 'กระทบยอดบัญชีคุม | New ERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">ACCOUNTING / RECONCILIATION</p><h1 class="h3 mb-2">กระทบยอดบัญชีคุม</h1><p class="text-secondary mb-0">เปรียบเทียบยอด GL กับรายการที่มี Subledger reference ถึงวันสิ้นงวด</p></div><div class="col-12 col-md-4"><label class="form-label" for="recon-period">งวดบัญชี</label><select class="form-select" id="recon-period">@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->fiscalYear->name }} / {{ $period->name }}</option>@endforeach</select></div></div>
<div class="row g-3 mb-4">@foreach([['gl_balance','ยอด GL'],['subledger_balance','ยอด Subledger'],['difference','ผลต่าง']] as [$key,$label])<div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">{{ $label }}</div><div class="h5 mb-0" data-total="{{ $key }}">0.00</div></div></div></div>@endforeach</div>
<div class="row g-3 mb-4"><div class="col-12 col-md-3"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">Inventory Allocation</div><div class="h6 mb-0" data-inventory-total="allocation_value">-</div></div></div></div><div class="col-12 col-md-3"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">Inventory GL</div><div class="h6 mb-0" data-inventory-total="gl_inventory_value">-</div></div></div></div><div class="col-12 col-md-3"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">ผลต่าง Allocation/GL</div><div class="h6 mb-0" data-inventory-total="allocation_vs_gl_difference">-</div></div></div></div><div class="col-12 col-md-3"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">สถานะ Inventory</div><div class="h6 mb-0" data-inventory-total="status">-</div></div></div></div></div>
<div class="alert alert-info border-0">รายงานนี้เป็น foundation สำหรับ AR/AP/Inventory โดย Inventory ใช้ allocation และ GL ณ วันสิ้นงวด ส่วน Stock Balance ที่แสดงเป็น current projection จนกว่าจะมี historical snapshot</div><div class="card border-0 shadow-sm"><div class="card-body p-4"><table class="table table-hover align-middle w-100" id="reconciliation-table" data-url="{{ route('accounting.reports.reconciliation.data') }}" data-export-url="{{ route('accounting.reports.reconciliation.export') }}"><thead><tr><th>ประเภท</th><th>รหัสบัญชี</th><th>ชื่อบัญชี</th><th class="text-end">ยอด GL</th><th class="text-end">ยอด Subledger</th><th class="text-end">ผลต่าง</th><th class="text-end">ดู GL</th></tr></thead></table></div></div></div>
@endsection
@push('scripts')<script>$(function(){var t=$('#reconciliation-table'),p=$('#recon-period'),x=$.fn.dataTable.render.text(),dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.period_id=p.val()},dataSrc:function(r){$.each(r.totals||{},function(k,v){$('[data-total="'+k+'"]').text(v||'0.00')});$.each(r.inventory_reconciliation||{},function(k,v){$('[data-inventory-total="'+k+'"]').text(v===null||v===undefined||v===''?'-':v)});return r.data}},order:[[1,'asc']],buttons:[window.erpExcelButton(t,function(){return{period_id:p.val()}})],columns:[{data:'control_account_type',name:'accounts.control_account_type',render:x.display},{data:'code',name:'accounts.code',render:x.display},{data:'name',name:'accounts.name',render:x.display},{data:'gl_balance',name:'gl_balance',className:'text-end',render:x.display},{data:'subledger_balance',name:'subledger_balance',className:'text-end',render:x.display},{data:'difference',name:'difference',className:'text-end',render:x.display},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,type,row){return type==='display'?'<a class="btn btn-sm btn-outline-dark" href="'+x.display(row.account_url)+'">ดู GL</a>':'';}}]}));p.on('change',function(){dt.ajax.reload()})});</script>@endpush
