@extends('Accounting::layout')
@section('title', 'รายงานภาษี | New ERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
@php($selectedPeriod = $periods->first(fn ($period) => now()->between($period->start_date, $period->end_date)) ?: $periods->first())
<div class="mb-4"><p class="eyebrow mb-2">ACCOUNTING / TAX REPORT</p><h1 class="h3 mb-2">{{ $taxKind === 'VAT_IN' ? 'รายการภาษีซื้อ' : ($taxKind === 'VAT_OUT' ? 'รายงานภาษีขาย' : 'รายงานภาษี') }}</h1><p class="text-secondary mb-0">{{ $taxKind ? 'เตรียมตรวจสอบและส่งข้อมูลภาษีให้สรรพากรจากรายการที่ Post แล้ว' : 'VAT IN, VAT OUT และ WHT จาก posted journal tax dimensions' }}</p></div>
<div class="card border-0 shadow-sm mb-4" id="tax-filters"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">ตัวกรองรายงาน</h2><button type="button" class="btn btn-outline-secondary btn-sm" id="report-filter-reset"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3">
<div class="col-12 col-md-3"><label class="form-label" for="tax-period">งวดบัญชี</label><select class="form-select" id="tax-period">@foreach($periods as $period)<option value="{{ $period->id }}" @selected($period->id === (int) request('period_id', $selectedPeriod?->id))>{{ $period->fiscalYear->name }} / {{ $period->name }}</option>@endforeach</select></div>
<div class="col-12 col-md-3"><label class="form-label" for="tax-basis">วันที่รายงาน</label><select class="form-select" id="tax-basis"><option value="SETTLEMENT">วันที่รับ/จ่ายจริง</option><option value="TAX_POINT">Tax Point / วันที่เอกสาร</option></select></div>
<div class="col-12 col-md-3"><label class="form-label" for="report-branch">สาขา</label><select class="form-select" id="report-branch"><option value="current" @selected(request('branch_scope', 'current') === 'current')>สาขาปัจจุบัน</option><option value="all" @selected(request('branch_scope') === 'all')>ทุกสาขาที่มีสิทธิ์</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->code }} · {{ $branch->name }}</option>@endforeach</select></div>
<div class="col-12 col-md-3"><label class="form-label" for="report-warehouse">คลัง</label><select class="form-select" id="report-warehouse"><option value="">ทุกคลังที่มีสิทธิ์</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->code }} · {{ $warehouse->name }}</option>@endforeach</select></div>
</div></div></div>
<div class="row g-3 mb-4">@foreach([['vat_in','VAT IN'],['vat_out','VAT OUT'],['wht','WHT']] as [$key,$label])<div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="small text-secondary">{{ $label }}</div><div class="h5 mb-0" data-total="{{ $key }}">0</div></div></div></div>@endforeach</div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><table class="table table-hover align-middle w-100" id="tax-report-table" data-url="{{ route('accounting.reports.tax.data') }}" data-export-url="{{ route('accounting.reports.tax.export') }}"><thead><tr><th>วันที่</th><th>เลขที่ Journal</th><th>Tax Code</th><th>ประเภท</th><th>บัญชี</th><th class="text-end">ฐานภาษี</th><th class="text-end">ภาษี</th><th class="text-end">ดู</th></tr></thead></table></div></div></div>
@endsection
@push('scripts')<script>$(function(){var t=$('#tax-report-table'),p=$('#tax-period'),b=$('#tax-basis'),x=$.fn.dataTable.render.text(),dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.period_id=p.val();d.date_basis=b.val();d.tax_kind=@json($taxKind);d.branch_scope=$('#report-branch').val();d.warehouse_id=$('#report-warehouse').val()},dataSrc:function(r){$.each(r.totals||{},function(k,v){$('[data-total="'+k+'"]').text(window.erpAccountingFormat(v))});return r.data}},order:[[0,'asc']],buttons:[window.erpExcelButton(t,function(){return{period_id:p.val(),date_basis:b.val(),tax_kind:@json($taxKind),branch_scope:$('#report-branch').val(),warehouse_id:$('#report-warehouse').val()}})],columns:[{data:null,name:'journal_entry_lines.tax_point_date',render:function(v,type,row){return type==='display'?x.display(b.val()==='TAX_POINT'?row.tax_point_date_label:row.tax_settlement_date_label):b.val()==='TAX_POINT'?row.tax_point_date:row.tax_settlement_date}},{data:'entry_number',name:'entries.entry_number',render:x.display},{data:'tax_code',name:'tax_codes.code',render:x.display},{data:'tax_kind',name:'tax_codes.kind',render:x.display},{data:null,name:'accounts.code',render:function(v,type,row){return type==='display'?x.display(row.account_code+' · '+row.account_name):v}},{data:'tax_base',name:'journal_entry_lines.tax_base',className:'text-end',render:x.display},{data:'tax_amount',name:'journal_entry_lines.tax_amount',className:'text-end',render:x.display},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,type,row){return type==='display'?'<a class="btn btn-sm btn-outline-dark" href="'+x.display(row.entry_url)+'">ดู</a>':'';}}]}));p.add(b).add($('#report-branch')).add($('#report-warehouse')).on('change',function(){dt.ajax.reload()});$('#report-filter-reset').on('click',function(){$('#report-branch').val('current');$('#report-warehouse').val('');dt.ajax.reload()})});</script>@endpush
