@php($accountingDecimalPlaces = max(0, min(4, (int) (\App\Models\CompanySetting::query()->value('tax_decimal_places') ?? 2))))
<html><head><meta charset="utf-8"><style>
@page{margin:9mm 10mm 8mm}*{box-sizing:border-box}body{font-family:dejavusans,sans-serif;font-size:9.5pt;color:#111;margin:0}.small{font-size:8pt}.muted{color:#555}.center{text-align:center}.right{text-align:right}.line{display:inline}.box{border:1px solid #222;border-radius:3px;padding:3mm;margin-top:2mm}.title{font-size:17pt;font-weight:bold;line-height:1.2}.subtitle{font-size:10pt}.grid{width:100%;border-collapse:collapse}.grid td{padding:1.2mm 1mm;vertical-align:bottom}.taxid{padding:1mm 2mm;letter-spacing:1mm}.section{font-weight:bold;font-size:11pt;margin-bottom:1mm}.formtable{width:100%;border-collapse:collapse;table-layout:fixed}.formtable th,.formtable td{border:1px solid #222;padding:1.3mm 1.5mm}.formtable th{font-weight:bold;text-align:center;line-height:1.15}.formtable td{height:7.5mm}.formtable .desc{width:55%}.formtable .date{width:15%}.formtable .money{width:15%}.formtable .tax{width:15%}.check{font-family:dejavusans;font-size:11pt}.totals{width:48%;margin-left:auto;border-collapse:collapse}.totals td{padding:1.2mm}.signature{height:18mm;vertical-align:bottom;text-align:center}.footer{border:1px solid #222;margin-top:2mm;padding:2mm}.copy{font-size:8pt;line-height:1.3}
</style></head><body>
<table class="grid"><tr><td class="copy" style="width:47%">ฉบับที่ 1&nbsp; (สำหรับผู้ถูกหักภาษี ณ ที่จ่าย ใช้แนบพร้อมกับแบบแสดงรายการภาษี)<br>ฉบับที่ 2&nbsp; (สำหรับผู้มีหน้าที่หักภาษี ณ ที่จ่าย เก็บไว้เป็นหลักฐาน)</td><td class="right small">เลขที่เอกสาร<br><b>{{ $row->document_number ?: '—' }}</b></td></tr></table>
<div class="box" style="padding:3mm 4mm 2mm"><div class="center title">หนังสือรับรองการหักภาษี ณ ที่จ่าย</div><div class="center subtitle">ตามมาตรา 50 ทวิ แห่งประมวลรัษฎากร</div>
<table class="grid" style="margin-top:2mm"><tr><td style="width:50%"><b>ผู้มีหน้าที่หักภาษี ณ ที่จ่าย :</b> {{ $company?->company_name ?: '—' }}<br>ชื่อ <span class="line" style="width:70mm">{{ $company?->company_name ?: '—' }}</span><br>ที่อยู่ <span class="line" style="width:74mm">{{ $company?->company_address ?: '—' }}</span></td><td>เลขประจำตัวผู้เสียภาษีอากร<br><span class="taxid">{{ $company?->tax_id ?: '—' }}</span></td></tr></table></div>
<div class="box"><div><b>ผู้ถูกหักภาษี ณ ที่จ่าย :</b> {{ $row->party_name ?: '—' }}</div><table class="grid"><tr><td style="width:56%">ชื่อ <span class="line" style="width:72mm">{{ $row->party_name ?: '—' }}</span><br>ที่อยู่ <span class="line" style="width:72mm">—</span></td><td>เลขประจำตัวผู้เสียภาษีอากร<br><span class="muted">{{ $row->tax_id ?: '—' }}</span><br>สาขา <span class="line" style="width:25mm">{{ $row->branch_code ?: '00000' }}</span></td></tr></table><div style="margin-top:1mm"><b>ลำดับที่</b> <span class="line" style="width:20mm">—</span> ในแบบ&nbsp;&nbsp; <span class="check">☐</span> ภ.ง.ด.1&nbsp;&nbsp; <span class="check">☐</span> ภ.ง.ด.2&nbsp;&nbsp; <span class="check">{{ $formType === 'ภ.ง.ด.3' ? '☑' : '☐' }}</span> ภ.ง.ด.3&nbsp;&nbsp; <span class="check">{{ $formType === 'ภ.ง.ด.53' ? '☑' : '☐' }}</span> ภ.ง.ด.53</div></div>
<table class="formtable" style="margin-top:2mm"><thead><tr><th class="desc">ประเภทเงินได้พึงประเมินที่จ่าย</th><th class="date">วัน เดือน ปี<br>หรือปีภาษีที่จ่าย</th><th class="money">จำนวนเงินที่จ่าย</th><th class="tax">ภาษีที่หัก<br>และนำส่งไว้</th></tr></thead><tbody>
@foreach(['1. เงินเดือน ค่าจ้าง เบี้ยเลี้ยง โบนัส ฯลฯ ตามมาตรา 40 (1)','2. ค่าธรรมเนียม ค่านายหน้า ฯลฯ ตามมาตรา 40 (2)','3. ค่าแห่งลิขสิทธิ์ ฯลฯ ตามมาตรา 40 (3)','4. ดอกเบี้ย ฯลฯ ตามมาตรา 40 (4)','5. การจ่ายเงินได้ที่ต้องหักภาษี ณ ที่จ่าย ตามคำสั่งกรมสรรพากร','6. อื่น ๆ (ระบุ)'] as $label)<tr><td class="desc">{{ $label }}@if($loop->first)<br><span class="muted small">{{ $row->tax_name ?: $row->tax_code }}</span>@endif</td><td class="date">{{ $loop->first ? \Carbon\Carbon::parse($row->settlement_date)->format('d/m/Y') : '' }}</td><td class="money right">{{ $loop->first ? number_format((float) $row->tax_base, $accountingDecimalPlaces, '.', ',') : '' }}</td><td class="tax right">{{ $loop->first ? number_format((float) $row->tax_amount, $accountingDecimalPlaces, '.', ',') : '' }}</td></tr>@endforeach
<tr><td colspan="2" class="right"><b>รวมเงินที่จ่ายและภาษีที่หักนำส่ง</b></td><td class="right"><b>{{ number_format((float) $row->tax_base, $accountingDecimalPlaces, '.', ',') }}</b></td><td class="right"><b>{{ number_format((float) $row->tax_amount, $accountingDecimalPlaces, '.', ',') }}</b></td></tr></tbody></table>
<div class="footer"><table class="grid"><tr><td>ผู้จ่ายเงิน&nbsp; <span class="check">☑</span> หัก ณ ที่จ่าย&nbsp;&nbsp; <span class="check">☐</span> ออกให้ตลอดไป&nbsp;&nbsp; <span class="check">☐</span> ออกให้ครั้งเดียว</td><td class="right">วันที่ออกหนังสือรับรองฯ<br><b>{{ \Carbon\Carbon::parse($row->settlement_date)->format('d/m/Y') }}</b></td></tr><tr><td class="signature" colspan="2">ลงชื่อ ........................................................ ผู้จ่ายเงิน<br><span class="small">({{ $company?->company_name ?: 'ผู้มีหน้าที่หักภาษี ณ ที่จ่าย' }})</span></td></tr></table></div>
<div class="small muted" style="margin-top:2mm">เอกสารนี้จัดทำตามข้อมูลการจ่ายเงินจริงในระบบบัญชี โปรดตรวจสอบรายละเอียดและแบบนำส่งกับหลักเกณฑ์ของกรมสรรพากรก่อนใช้งาน</div>
</body></html>
