@extends('Pos::layout')

@section('title', ($plan->exists ? 'แก้ไข' : 'เพิ่ม').'แผนคอมมิชชั่นขาย | POS')

@section('content')
@php($assignments = old('assignments', $assignments->map(fn ($assignment) => ['user_id' => $assignment->user_id, 'branch_id' => $assignment->branch_id])->all() ?: [['user_id' => '', 'branch_id' => $branch->id]]))
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">POS / SALES / MASTER DATA</p><h1 class="h3 mb-1">{{ $plan->exists ? 'แก้ไข' : 'เพิ่ม' }}แผนคอมมิชชั่นขาย</h1><p class="text-secondary mb-2">ใช้ตั้งค่าเท่านั้น การคำนวณสิทธิ์และการจ่ายคอมมิชชั่นจะทำในขั้นตอนถัดไป</p>@if($plan->exists)<p class="small text-secondary mb-4">รายละเอียดแผนเป็นข้อมูลกลาง; หน้านี้กำหนดผู้รับเฉพาะสาขาปัจจุบัน</p>@else<p class="small text-secondary mb-4">แผนจะถูกกำหนดผู้รับให้สาขาปัจจุบันก่อน</p>@endif
    <form id="commission-plan-form" method="POST" action="{{ $plan->exists ? route('pos.sales-commission-plans.update', $plan) : route('pos.sales-commission-plans.store') }}">@csrf @if($plan->exists)@method('PUT')@endif
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-3">
            <div class="col-md-3"><label class="form-label" for="commission-code">รหัส <span class="text-danger">*</span></label><input id="commission-code" class="form-control text-uppercase" name="code" maxlength="50" value="{{ old('code', $plan->code) }}" required><div class="invalid-feedback" data-error-for="code"></div></div>
            <div class="col-md-5"><label class="form-label" for="commission-name">ชื่อแผน <span class="text-danger">*</span></label><input id="commission-name" class="form-control" name="name" maxlength="255" value="{{ old('name', $plan->name) }}" required><div class="invalid-feedback" data-error-for="name"></div></div>
            <div class="col-md-4"><label class="form-label" for="commission-basis">ฐานคำนวณ <span class="text-danger">*</span></label><select id="commission-basis" class="form-select" name="basis" required><option value="POSTED_SALE" @selected(old('basis', $plan->basis) === 'POSTED_SALE')>ยอดขายที่ลงบัญชี</option><option value="COLLECTED_RECEIPT" @selected(old('basis', $plan->basis) === 'COLLECTED_RECEIPT')>ยอดรับชำระ</option><option value="GROSS_PROFIT" @selected(old('basis', $plan->basis) === 'GROSS_PROFIT')>กำไรขั้นต้น</option></select><div class="invalid-feedback" data-error-for="basis"></div></div>
            <div class="col-md-3"><label class="form-label" for="commission-rate">อัตรา % <span class="text-danger">*</span></label><input id="commission-rate" class="form-control text-end" type="number" min="0" max="100" step="0.0001" name="rate" value="{{ old('rate', $plan->rate) }}" required><div class="invalid-feedback" data-error-for="rate"></div></div>
            <div class="col-md-3"><label class="form-label" for="commission-from">วันที่เริ่มมีผล</label><input id="commission-from" class="form-control" type="date" name="effective_from" value="{{ old('effective_from', $plan->effective_from?->format('Y-m-d')) }}"><div class="invalid-feedback" data-error-for="effective_from"></div></div>
            <div class="col-md-3"><label class="form-label" for="commission-to">วันที่สิ้นสุด</label><input id="commission-to" class="form-control" type="date" name="effective_to" value="{{ old('effective_to', $plan->effective_to?->format('Y-m-d')) }}"><div class="invalid-feedback" data-error-for="effective_to"></div></div>
            <div class="col-md-3 d-flex align-items-end"><div class="form-check mb-2"><input type="hidden" name="is_active" value="0"><input id="commission-active" class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active', $plan->is_active ?? true))><label class="form-check-label" for="commission-active">เปิดใช้งานแผน</label></div></div>
        </div></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center gap-3 mb-3"><div><h2 class="h5 mb-1">ผู้รับคอมมิชชั่น <span class="text-danger">*</span></h2><p class="text-secondary small mb-0">กำหนดผู้รับสำหรับสาขา {{ $branch->code }} · {{ $branch->name }}</p></div><button id="add-commission-assignment" class="btn btn-sm btn-app-soft" type="button"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มผู้รับ</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>ผู้ใช้งาน</th><th>สาขา</th><th class="text-end">จัดการ</th></tr></thead><tbody id="commission-assignments">@foreach($assignments as $index => $assignment)<tr class="commission-assignment"><td><select class="form-select" name="assignments[{{ $index }}][user_id]" required><option value="">เลือกผู้ใช้งาน</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) ($assignment['user_id'] ?? '') === (string) $user->id)>{{ $user->name }}{{ $user->username ? ' · '.$user->username : '' }}</option>@endforeach</select></td><td><input type="hidden" name="assignments[{{ $index }}][branch_id]" value="{{ $branch->id }}"><span class="form-control-plaintext">{{ $branch->code }} · {{ $branch->name }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-danger js-remove-commission-assignment" type="button" title="ลบผู้รับ"><i class="bx bx-trash" aria-hidden="true"></i><span class="visually-hidden">ลบผู้รับ</span></button></td></tr>@endforeach</tbody></table></div><div class="invalid-feedback d-block" data-error-for="assignments"></div><div class="mt-4"><button class="btn btn-dark" type="submit">บันทึก</button> <a class="btn btn-outline-secondary" href="{{ route('pos.sales-commission-plans.index') }}">ย้อนกลับ</a></div></div></div>
    </form>
</div>
<template id="commission-assignment-template"><tr class="commission-assignment"><td><select class="form-select" name="assignments[__INDEX__][user_id]" required><option value="">เลือกผู้ใช้งาน</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}{{ $user->username ? ' · '.$user->username : '' }}</option>@endforeach</select></td><td><input type="hidden" name="assignments[__INDEX__][branch_id]" value="{{ $branch->id }}"><span class="form-control-plaintext">{{ $branch->code }} · {{ $branch->name }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-danger js-remove-commission-assignment" type="button" title="ลบผู้รับ"><i class="bx bx-trash" aria-hidden="true"></i><span class="visually-hidden">ลบผู้รับ</span></button></td></tr></template>
@endsection

@push('scripts')
<script>
$(function(){var assignments=$('#commission-assignments'),template=$('#commission-assignment-template').html(),nextIndex=Math.max(-1,...assignments.find('.commission-assignment').map(function(){var match=$(this).find('[name]').first().attr('name').match(/assignments\\[(\\d+)]/);return match?Number(match[1]):-1;}).get())+1;$('#add-commission-assignment').on('click',function(){assignments.append(template.replace(/__INDEX__/g,nextIndex++));});assignments.on('click','.js-remove-commission-assignment',function(){if(assignments.find('.commission-assignment').length>1)$(this).closest('.commission-assignment').remove();});window.erpAjaxForm({form:'#commission-plan-form',redirect:{{ $plan->exists ? 'false' : 'true' }}});});
</script>
@endpush
