@extends('Pos::layout')

@section('title', 'ตั้งค่าคอมมิชชั่นขาย | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">POS / SALES / MASTER DATA</p><h1 class="h3 mb-2">ตั้งค่าคอมมิชชั่นขาย</h1><p class="text-secondary mb-0">กำหนดฐานคำนวณ อัตรา และผู้รับคอมมิชชั่นก่อนประมวลผลเอกสารขาย</p></div>@if(auth()->user()->hasPermission('pos.commission-plans.create'))<a class="btn btn-dark" href="{{ route('pos.sales-commission-plans.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มแผนคอมมิชชั่น</a>@endif</div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3 align-items-end"><div class="col-12 col-md-4"><label class="form-label" for="commission-plan-basis">ฐานคำนวณ</label><select class="form-select" id="commission-plan-basis"><option value="">ทั้งหมด</option><option value="POSTED_SALE">ยอดขายที่ลงบัญชี</option><option value="COLLECTED_RECEIPT">ยอดรับชำระ</option><option value="GROSS_PROFIT">กำไรขั้นต้น</option></select></div><div class="col-12 col-md-4"><label class="form-label" for="commission-plan-active">สถานะ</label><select class="form-select" id="commission-plan-active"><option value="">ทั้งหมด</option><option value="1">ใช้งาน</option><option value="0">ปิดใช้งาน</option></select></div><div class="col-6 col-md-2"><button class="btn btn-outline-secondary w-100" id="commission-plan-filter" type="button"><i class="bx bx-filter-alt me-1" aria-hidden="true"></i>กรอง</button></div><div class="col-6 col-md-2"><button class="btn btn-outline-secondary w-100" id="commission-plan-reset" type="button">ล้าง</button></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="commission-plans-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.sales-commission-plans.data') }}"><thead><tr><th>รหัส</th><th>ชื่อแผน</th><th>ฐานคำนวณ</th><th class="text-end">อัตรา %</th><th>เริ่มมีผล</th><th>สิ้นสุด</th><th class="text-end">ผู้รับ</th><th>สถานะ</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>
$(function(){var $table=$('#commission-plans-table'),text=$.fn.dataTable.render.text(),number=$.fn.dataTable.render.number(',', '.', 4),table=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(data){data.basis=$('#commission-plan-basis').val();data.is_active=$('#commission-plan-active').val();}},order:[[0,'asc']],buttons:[window.erpExcelButton($table)],columns:[{data:'code',render:text.display},{data:'name',render:text.display},{data:'basis_label',render:text.display},{data:'rate',className:'text-end',render:number},{data:'effective_from',render:text.display},{data:'effective_to',render:text.display},{data:'assignments_count',className:'text-end'},{data:'status_label',render:function(v,t){if(t!=='display')return v;return v==='ใช้งาน'?'<span class="badge app-badge-success">ใช้งาน</span>':'<span class="badge app-badge-soft">ปิดใช้งาน</span>';}},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,t,row){if(t!=='display')return '';var actions=[];if(row.edit_url)actions.push('<a class="btn btn-sm btn-outline-dark" title="แก้ไข" href="'+text.display(row.edit_url)+'"><i class="bx bx-edit-alt" aria-hidden="true"></i><span class="visually-hidden">แก้ไข</span></a>');if(row.delete_url)actions.push('<button class="btn btn-sm btn-outline-danger js-delete-commission-plan" type="button" title="ลบ" data-url="'+text.display(row.delete_url)+'"><i class="bx bx-trash" aria-hidden="true"></i><span class="visually-hidden">ลบ</span></button>');return actions.join(' ');}}]}));$('#commission-plan-filter').on('click',function(){table.ajax.reload();});$('#commission-plan-reset').on('click',function(){$('#commission-plan-basis,#commission-plan-active').val('');table.ajax.reload();});window.erpAjaxDelete({button:'.js-delete-commission-plan',reload:'#commission-plans-table',confirm:'ยืนยันการลบแผนคอมมิชชั่นนี้หรือไม่?'});});
</script>
@endpush
