<?php

use App\Modules\Crm\Controllers\ActivityController;
use App\Modules\Crm\Controllers\CalendarController;
use App\Modules\Crm\Controllers\ContactController;
use App\Modules\Crm\Controllers\CustomerController;
use App\Modules\Crm\Controllers\CustomerAssignmentController;
use App\Modules\Crm\Controllers\CustomerTimelineController;
use App\Modules\Crm\Controllers\DashboardController;
use App\Modules\Crm\Controllers\ForecastController;
use App\Modules\Crm\Controllers\KanbanController;
use App\Modules\Crm\Controllers\MyWorkController;
use App\Modules\Crm\Controllers\NotificationController;
use App\Modules\Crm\Controllers\OpportunityController;
use App\Modules\Crm\Controllers\OwnershipTransferController;
use App\Modules\Crm\Controllers\ProductInterestController;
use App\Modules\Crm\Controllers\SalesTeamController;
use App\Modules\Crm\Controllers\TeamWorkController;
use App\Modules\Crm\Controllers\WorkflowController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'program:crm', 'branch'])->prefix('crm')->name('crm.')->group(function (): void {
    Route::get('/', DashboardController::class)->middleware('permission:crm.dashboard.view')->name('index');
    Route::get('/workflow', [WorkflowController::class, 'index'])->middleware('permission:crm.dashboard.view')->name('workflow.index');
    Route::get('/calendar', [CalendarController::class, 'index'])->middleware('permission:crm.calendar.view')->name('calendar.index');
    Route::get('/calendar/data', [CalendarController::class, 'data'])->middleware('permission:crm.calendar.view')->name('calendar.data');
    Route::get('/calendar/export', [CalendarController::class, 'export'])->middleware('permission:crm.calendar.view')->name('calendar.export');
    Route::get('/calendar/owner-options', [CalendarController::class, 'ownerOptions'])->middleware('permission:crm.calendar.view')->name('calendar.owner-options');
    Route::get('/calendar/opportunity-options', [CalendarController::class, 'opportunityOptions'])->middleware(['permission:crm.calendar.view', 'permission:crm.activities.create'])->name('calendar.opportunity-options');
    Route::get('/forecast', [ForecastController::class, 'index'])->middleware('permission:crm.forecast.view')->name('forecast.index');
    Route::get('/forecast/data', [ForecastController::class, 'data'])->middleware('permission:crm.forecast.view')->name('forecast.data');
    Route::get('/forecast/owner-options', [ForecastController::class, 'ownerOptions'])->middleware('permission:crm.forecast.view')->name('forecast.owner-options');
    Route::get('/notifications', [NotificationController::class, 'index'])->middleware('permission:crm.opportunities.view')->name('notifications.index');
    Route::get('/notifications/data', [NotificationController::class, 'data'])->middleware('permission:crm.opportunities.view')->name('notifications.data');
    Route::put('/notifications/preferences', [NotificationController::class, 'updatePreference'])->middleware('permission:crm.opportunities.view')->name('notifications.preferences.update');
    Route::post('/notifications/push/subscribe', [NotificationController::class, 'subscribe'])->middleware('permission:crm.opportunities.view')->name('notifications.push.subscribe');
    Route::delete('/notifications/push/subscribe', [NotificationController::class, 'unsubscribe'])->middleware('permission:crm.opportunities.view')->name('notifications.push.unsubscribe');
    Route::get('/notifications/{notification}/open', [NotificationController::class, 'open'])->middleware('permission:crm.opportunities.view')->name('notifications.open');
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'read'])->middleware('permission:crm.opportunities.view')->name('notifications.read');
    Route::get('/my-work', [MyWorkController::class, 'index'])->middleware('permission:crm.opportunities.view')->name('my-work.index');
    Route::get('/my-work/data', [MyWorkController::class, 'data'])->middleware('permission:crm.opportunities.view')->name('my-work.data');
    Route::get('/team-work', [TeamWorkController::class, 'index'])->middleware('permission:crm.team-work.view')->name('team-work.index');
    Route::get('/team-work/data', [TeamWorkController::class, 'data'])->middleware('permission:crm.team-work.view')->name('team-work.data');
    Route::get('/ownership-transfers', [OwnershipTransferController::class, 'index'])->middleware('permission:crm.customers.transfer-owner')->name('ownership-transfers.index');
    Route::post('/ownership-transfers/preview', [OwnershipTransferController::class, 'preview'])->middleware('permission:crm.customers.transfer-owner')->name('ownership-transfers.preview');
    Route::post('/ownership-transfers', [OwnershipTransferController::class, 'store'])->middleware('permission:crm.customers.transfer-owner')->name('ownership-transfers.store');
    Route::get('/ownership-transfers/user-options', [OwnershipTransferController::class, 'userOptions'])->middleware('permission:crm.customers.transfer-owner')->name('ownership-transfers.user-options');
    Route::get('/ownership-transfers/customer-options', [OwnershipTransferController::class, 'customerOptions'])->middleware('permission:crm.customers.transfer-owner')->name('ownership-transfers.customer-options');
    Route::get('/teams', [SalesTeamController::class, 'index'])->middleware('permission:crm.teams.manage')->name('teams.index');
    Route::get('/teams/create', [SalesTeamController::class, 'create'])->middleware('permission:crm.teams.manage')->name('teams.create');
    Route::post('/teams', [SalesTeamController::class, 'store'])->middleware('permission:crm.teams.manage')->name('teams.store');
    Route::get('/teams/{salesTeam}/edit', [SalesTeamController::class, 'edit'])->middleware('permission:crm.teams.manage')->name('teams.edit');
    Route::put('/teams/{salesTeam}', [SalesTeamController::class, 'update'])->middleware('permission:crm.teams.manage')->name('teams.update');
    Route::get('/customers', [CustomerController::class, 'index'])->middleware('permission:crm.opportunities.view')->name('customers.index');
    Route::get('/customers/data', [CustomerController::class, 'data'])->middleware('permission:crm.opportunities.view')->name('customers.data');
    Route::get('/customers/duplicates', [CustomerController::class, 'duplicateReview'])->middleware('permission:crm.customers.update')->name('customers.duplicates');
    Route::get('/customers/duplicates/data', [CustomerController::class, 'duplicateData'])->middleware('permission:crm.customers.update')->name('customers.duplicates.data');
    Route::post('/customers/duplicates/dismiss', [CustomerController::class, 'dismissDuplicate'])->middleware('permission:crm.customers.merge')->name('customers.duplicates.dismiss');
    Route::get('/customers/assignment/user-options', [CustomerAssignmentController::class, 'userOptions'])->middleware('permission:crm.customers.assign')->name('customers.assignment.user-options');
    Route::get('/customers/create', [CustomerController::class, 'create'])->middleware('permission:crm.customers.create')->name('customers.create');
    Route::get('/customers/duplicate-options', [CustomerController::class, 'duplicateOptions'])->middleware('permission:crm.customers.create')->name('customers.duplicate-options');
    Route::post('/customers', [CustomerController::class, 'store'])->middleware('permission:crm.customers.create')->name('customers.store');
    Route::get('/customers/{target}/merge/{source}', [CustomerController::class, 'mergePreview'])->middleware('permission:crm.customers.merge')->name('customers.merge.preview');
    Route::post('/customers/{target}/merge/{source}', [CustomerController::class, 'merge'])->middleware('permission:crm.customers.merge')->name('customers.merge');
    Route::get('/customers/{customer}/edit', [CustomerController::class, 'edit'])->middleware('permission:crm.customers.update')->name('customers.edit');
    Route::put('/customers/{customer}', [CustomerController::class, 'update'])->middleware('permission:crm.customers.update')->name('customers.update');
    Route::get('/customers/{customer}', [CustomerController::class, 'show'])->middleware('permission:crm.opportunities.view')->name('customers.show');
    Route::put('/customers/{customer}/assignment', [CustomerAssignmentController::class, 'update'])->middleware('permission:crm.customers.assign')->name('customers.assignment.update');
    Route::patch('/customers/{customer}/activate', [CustomerController::class, 'activate'])->middleware('permission:crm.customers.update')->name('customers.activate');
    Route::patch('/customers/{customer}/deactivate', [CustomerController::class, 'deactivate'])->middleware('permission:crm.customers.update')->name('customers.deactivate');
    Route::delete('/customers/{customer}', [CustomerController::class, 'destroy'])->middleware('permission:crm.customers.delete')->name('customers.destroy');
    Route::get('/customers/{customer}/timeline', CustomerTimelineController::class)->middleware('permission:crm.opportunities.view')->name('customers.timeline');
    Route::post('/customers/{customer}/contacts', [ContactController::class, 'store'])->middleware('permission:crm.opportunities.update')->name('customers.contacts.store');
    Route::put('/customers/{customer}/contacts/{contact}', [ContactController::class, 'update'])->middleware('permission:crm.opportunities.update')->name('customers.contacts.update');
    Route::delete('/customers/{customer}/contacts/{contact}', [ContactController::class, 'destroy'])->middleware('permission:crm.opportunities.update')->name('customers.contacts.destroy');
    Route::get('/opportunities', [OpportunityController::class, 'index'])->middleware('permission:crm.opportunities.view')->name('opportunities.index');
    Route::get('/opportunities/data', [OpportunityController::class, 'data'])->middleware('permission:crm.opportunities.view')->name('opportunities.data');
    Route::get('/opportunities/kanban', [KanbanController::class, 'index'])->middleware('permission:crm.opportunities.view')->name('opportunities.kanban');
    Route::get('/opportunities/kanban/data', [KanbanController::class, 'data'])->middleware('permission:crm.opportunities.view')->name('opportunities.kanban.data');
    Route::patch('/opportunities/{opportunity}/stage', [KanbanController::class, 'transition'])->middleware('permission:crm.opportunities.update')->name('opportunities.stage');
    Route::get('/opportunities/owner-options', [OpportunityController::class, 'ownerOptions'])->name('opportunities.owner-options');
    Route::get('/opportunities/customer-options', [OpportunityController::class, 'customerOptions'])->middleware('permission:crm.opportunities.view')->name('opportunities.customer-options');
    Route::get('/opportunities/product-item-options', [ProductInterestController::class, 'itemOptions'])->middleware('permission:crm.opportunities.view')->name('opportunities.product-item-options');
    Route::get('/opportunities/create', [OpportunityController::class, 'create'])->middleware('permission:crm.opportunities.create')->name('opportunities.create');
    Route::post('/opportunities', [OpportunityController::class, 'store'])->middleware('permission:crm.opportunities.create')->name('opportunities.store');
    Route::get('/opportunities/{opportunity}', [OpportunityController::class, 'show'])->middleware('permission:crm.opportunities.view')->name('opportunities.show');
    Route::get('/opportunities/{opportunity}/edit', [OpportunityController::class, 'edit'])->middleware('permission:crm.opportunities.update')->name('opportunities.edit');
    Route::put('/opportunities/{opportunity}', [OpportunityController::class, 'update'])->middleware('permission:crm.opportunities.update')->name('opportunities.update');
    Route::delete('/opportunities/{opportunity}', [OpportunityController::class, 'destroy'])->middleware('permission:crm.opportunities.delete')->name('opportunities.destroy');
    Route::post('/opportunities/{opportunity}/documents/{documentType}/{documentId}/open', [OpportunityController::class, 'openDocument'])->middleware('permission:crm.opportunities.view')->whereIn('documentType',['intake','rfq','quotation','order','sale','payment'])->whereNumber('documentId')->name('opportunities.documents.open');
    Route::get('/opportunities/{opportunity}/product-interests', [ProductInterestController::class, 'data'])->middleware('permission:crm.opportunities.view')->name('opportunities.product-interests.data');
    Route::post('/opportunities/{opportunity}/product-interests', [ProductInterestController::class, 'store'])->middleware('permission:crm.opportunities.update')->name('opportunities.product-interests.store');
    Route::put('/opportunities/{opportunity}/product-interests/{productInterest}', [ProductInterestController::class, 'update'])->middleware('permission:crm.opportunities.update')->name('opportunities.product-interests.update');
    Route::delete('/opportunities/{opportunity}/product-interests/{productInterest}', [ProductInterestController::class, 'destroy'])->middleware('permission:crm.opportunities.update')->name('opportunities.product-interests.destroy');
    Route::get('/opportunities/{opportunity}/activities', [ActivityController::class, 'data'])->middleware('permission:crm.opportunities.view')->name('opportunities.activities.data');
    Route::post('/opportunities/{opportunity}/activities', [ActivityController::class, 'store'])->middleware('permission:crm.activities.create')->name('opportunities.activities.store');
    Route::put('/opportunities/{opportunity}/activities/{activity}', [ActivityController::class, 'update'])->middleware('permission:crm.activities.update')->name('opportunities.activities.update');
    Route::patch('/opportunities/{opportunity}/activities/{activity}/schedule', [ActivityController::class, 'reschedule'])->middleware('permission:crm.activities.update')->name('opportunities.activities.schedule');
    Route::post('/opportunities/{opportunity}/activities/{activity}/complete', [ActivityController::class, 'complete'])->middleware('permission:crm.activities.complete')->name('opportunities.activities.complete');
    Route::post('/opportunities/{opportunity}/to-pos', [OpportunityController::class, 'toPos'])->middleware('permission:crm.opportunities.convert-pos')->name('opportunities.to-pos');
});
