@extends('Wms::layout')
@section('title', 'มูลค่าสินค้าคงเหลือ | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">WMS / REPORT</p><h1 class="h3 mb-2">มูลค่าสินค้าคงเหลือปัจจุบัน</h1><p class="text-secondary mb-0">ตรวจสอบ current projection ของจำนวน ต้นทุนเฉลี่ย และมูลค่าสินค้าตามคลังที่เลือก</p></div>
        @include('Wms::partials.warehouse-selector')
    </div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body d-flex flex-wrap align-items-center justify-content-between gap-3">
        <div><div class="small text-secondary mb-1">โหมดรายงาน</div><div class="fw-semibold">Current projection</div><div class="small text-secondary">ยอดปัจจุบันจาก Stock Balance และต้นทุนที่คำนวณแล้ว ณ {{ now()->format((string) app(\App\Modules\Settings\Services\GlobalSettings::class)->value('date_format')) }}</div></div>
        <div class="d-flex align-items-center gap-2"><span class="badge text-bg-success">กำลังดูอยู่</span></div>
    </div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body row g-3 align-items-end">
        <div class="col-md-6"><label class="form-label">สินค้า (ไม่เลือก = ทั้งหมด)</label><select id="valuation-item" class="form-select"><option value="">สินค้าทั้งหมด</option></select></div>
        <div class="col-md-3"><label class="form-label">Historical ณ วันที่</label><input id="historical-as-of" class="form-control" type="date" value="{{ now()->format('Y-m-d') }}"></div><div class="col-md-3"><button id="valuation-load" class="btn btn-dark w-100" type="button">แสดงข้อมูล</button></div>
    </div></div>
    <ul class="nav nav-tabs mb-3" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#current-valuation" type="button">Current projection</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#historical-valuation" type="button">Historical valuation</button></li></ul>
    <div class="alert alert-info border-0 small mb-4"><i class="bx bx-time-five me-1" aria-hidden="true"></i><strong>Pending cost / RECOST</strong> หมายถึงยังมีต้นทุนจริงหรือการคำนวณใหม่ที่รอประมวลผล ไม่ใช่ยอดที่ยืนยันแล้ว ควรตรวจรายการรับสินค้า/ต้นทุนต้นทางและรอให้สถานะกลับเป็นปกติก่อนปิดงวด</div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-3 align-items-center"><div><div class="small text-secondary">Inventory → GL Preflight</div><div class="h6 mb-0" id="preflight-status">กำลังตรวจสอบ...</div></div><div class="d-flex flex-wrap gap-3 small text-secondary"><span>Posted Movement: <strong id="preflight-movements">-</strong></span><span>Pending: <strong id="preflight-pending">-</strong></span><span>Unlinked: <strong id="preflight-unlinked">-</strong></span><span>Line proof: <strong id="preflight-line-proof">-</strong></span><span>Missing Mapping: <strong id="preflight-mapping">-</strong></span></div></div><div id="preflight-guidance" class="alert alert-warning border-0 small mt-3 mb-0"><span id="preflight-guidance-text">กำลังอ่าน readiness gate...</span>@if (auth()->user()->hasPermission('wms.cost-allocation-reviews.view'))<a id="preflight-legacy-review-link" class="btn btn-sm btn-outline-warning ms-2 d-none" href="{{ route('wms.legacy-allocation-reviews.index') }}" title="เปิดรายการ Legacy ที่ต้องตรวจสอบ" aria-label="เปิดรายการ Legacy ที่ต้องตรวจสอบ"><i class="bx bx-search-alt-2 me-1" aria-hidden="true"></i>เปิด Legacy Review</a>@endif</div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><div class="small text-secondary">RECOST Queue Health</div><div class="h6 mb-0" id="recost-health-status">กำลังตรวจสอบ...</div><div class="small text-secondary">SLA <span id="recost-sla">-</span> นาที · แสดงรายการค้างล่าสุดไม่เกิน 50 รายการ</div></div><button type="button" class="btn btn-outline-secondary btn-sm" id="recost-health-refresh"><i class="bx bx-refresh me-1" aria-hidden="true"></i>ตรวจสอบใหม่</button></div><div class="d-flex flex-wrap gap-3 small mb-3"><span class="badge app-status-warning">รอดำเนินการ <strong id="recost-pending">0</strong></span><span class="badge app-status-info">กำลังทำ <strong id="recost-processing">0</strong></span><span class="badge app-status-danger">ล้มเหลว <strong id="recost-failed">0</strong></span><span class="badge app-status-neutral">เกิน SLA <strong id="recost-stale">0</strong></span></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>รายการ</th><th>สถานะ</th><th>ครั้งที่ลอง</th><th>อัปเดตล่าสุด</th><th>ข้อผิดพลาด</th><th class="text-end">จัดการ</th></tr></thead><tbody id="recost-health-rows"><tr><td colspan="6" class="text-center text-secondary">กำลังโหลด...</td></tr></tbody></table></div></div></div>
    <div class="tab-content"><div class="tab-pane fade show active" id="current-valuation"><div class="card border-0 shadow-sm"><div class="card-body"><table id="valuation-table" class="table table-hover w-100" data-url="{{ route('wms.stock-valuation.data') }}"><thead><tr><th>สินค้า</th><th>หน่วย</th><th>คงเหลือ</th><th>จอง</th><th>ใช้ได้</th><th>ต้นทุนเฉลี่ย</th><th>มูลค่า</th><th>สถานะต้นทุน</th><th>Re-cost</th><th>จัดการ</th></tr></thead></table></div></div></div><div class="tab-pane fade" id="historical-valuation"><div class="alert alert-warning border-0 small"><i class="bx bx-info-circle me-1" aria-hidden="true"></i>Historical อ่านจาก immutable cost allocation ตามวันที่เลือก ไม่ใช้ยอดปัจจุบันจาก Stock Balance; รายการรอ Recost ยังไม่รวมใน Final valuation</div><div class="card border-0 shadow-sm mb-4"><div class="card-body"><table id="historical-valuation-table" class="table table-hover w-100" data-url="{{ route('wms.stock-valuation.historical-data') }}"><thead><tr><th>สินค้า</th><th>หน่วย</th><th>Final จำนวน</th><th>Final มูลค่า</th><th>Pending มูลค่า</th><th>Pending รายการ</th><th>สถานะ</th><th>จัดการ</th></tr></thead></table></div></div><h2 class="h6 mb-3">Historical Inventory ↔ Stock Balance ↔ GL</h2><div class="card border-0 shadow-sm"><div class="card-body"><table id="historical-reconciliation-table" class="table table-hover w-100" data-url="{{ route('wms.stock-valuation.historical-reconciliation-data') }}"><thead><tr><th>สินค้า</th><th>Final Inventory</th><th>Stock Balance</th><th>Inventory GL</th><th>Final ↔ GL</th><th>Balance ↔ Final</th><th>Pending</th><th>Unlinked</th><th>สถานะ</th><th>จัดการ</th></tr></thead></table></div></div></div></div>
    <div class="alert alert-warning border-0 small mb-4" id="preflight-deferred-note" hidden><i class="bx bx-info-circle me-1" aria-hidden="true"></i><strong>รายการที่ยังไม่เข้า Inventory → GL MVP:</strong> Issue, Issue Return และ Transfer จะยังคงแสดงเป็น Deferred จนกว่าจะมี source posting contract ครบ</div>
</div>
@endsection
@push('scripts')
<script>
$(function () {
    var tableElement = $('#valuation-table'), historicalElement = $('#historical-valuation-table'), reconciliationElement = $('#historical-reconciliation-table'), text = $.fn.dataTable.render.text();
    function loadRecostHealth() { $.getJSON('{{ route('wms.stock-valuation.recost-health') }}').done(function (r) { var s = r.summary || {}; $('#recost-sla').text(r.sla_minutes || '-'); $('#recost-pending').text(s.PENDING || 0); $('#recost-processing').text(s.PROCESSING || 0); $('#recost-failed').text(s.FAILED || 0); $('#recost-stale').text(s.STALE || 0); var open = (s.PENDING || 0) + (s.PROCESSING || 0) + (s.FAILED || 0) + (s.STALE || 0); $('#recost-health-status').text(open ? 'มีรายการที่ต้องติดตาม' : 'คิวปกติ ไม่มีรายการค้าง'); var labels = {PENDING: 'รอดำเนินการ', PROCESSING: 'กำลังประมวลผล', FAILED: 'ล้มเหลว', STALE: 'เกิน SLA'}; var classes = {PENDING: 'app-status-warning', PROCESSING: 'app-status-info', FAILED: 'app-status-danger', STALE: 'app-status-neutral'}; var rows = (r.items || []).map(function (item) { var action = @json(auth()->user()->hasPermission('wms.recost.retry')) && ['FAILED', 'STALE'].indexOf(item.status) !== -1 ? '<button type="button" class="btn btn-sm btn-outline-primary js-recost-retry" title="ส่งกลับเข้าคิว" aria-label="ส่งกลับเข้าคิว" data-id="' + item.id + '"><i class="bx bx-refresh" aria-hidden="true"></i></button>' : '-'; return '<tr><td>#' + item.id + '</td><td><span class="badge ' + (classes[item.status] || 'app-status-neutral') + '">' + (labels[item.status] || 'ไม่ทราบสถานะ') + '</span></td><td>' + item.attempts + '</td><td>' + $('<div>').text(item.updated_at).html() + '</td><td class="text-truncate" style="max-width:240px" title="' + $('<div>').text(item.last_error).html() + '">' + $('<div>').text(item.last_error).html() + '</td><td class="text-end">' + action + '</td></tr>'; }).join(''); $('#recost-health-rows').html(rows || '<tr><td colspan="6" class="text-center text-secondary">ไม่มีรายการค้าง</td></tr>'); }).fail(function () { $('#recost-health-status').text('ไม่สามารถอ่านสถานะ Queue ได้'); $('#recost-health-rows').html('<tr><td colspan="6" class="text-center text-danger">ตรวจสอบ Queue Health ไม่สำเร็จ</td></tr>'); }); }
$.getJSON('{{ route('wms.stock-valuation.preflight-summary') }}').done(function (r) { $('#preflight-status').text(r.ready ? 'พร้อมสำหรับการตรวจต่อ' : 'ต้องตรวจสอบก่อนเปิด GL posting'); $('#preflight-movements').text(r.posted_movements || 0); $('#preflight-pending').text(r.pending || 0); $('#preflight-unlinked').text(r.unlinked || 0); $('#preflight-line-proof').text(r.line_proof_available ? ((r.line_unlinked || 0) + (r.line_mismatched || 0)) : 'ยังไม่ติดตั้ง'); $('#preflight-mapping').text((r.missingInventory || 0) + (r.missingCogs || 0)); var blockers = []; if ((r.pending || 0) > 0) blockers.push('รอ Recost'); if ((r.unlinked || 0) > 0 || (r.line_unlinked || 0) > 0 || (r.line_mismatched || 0) > 0) blockers.push('ตรวจ allocation/linkage'); if ((r.missingInventory || 0) > 0 || (r.missingCogs || 0) > 0) blockers.push('ตั้งค่า Account Mapping'); if ((r.missingSource || 0) > 0) blockers.push('เติม source identity'); if ((r.unresolved_legacy_review || 0) > 0) blockers.push('กักกัน Legacy review (' + r.unresolved_legacy_review + ')'); if ((r.global_unresolved_legacy_review || 0) > 0) blockers.push('Global มี Legacy review (' + r.global_unresolved_legacy_review + ')'); if (!r.reconciliation_ready) blockers.push('Reconciliation: ' + ((r.reconciliation_blockers || []).join(', ') || 'ต้องตรวจสอบ')); var guidance = r.posting_enabled ? (r.ready && r.global_ready ? 'พร้อมสำหรับการตรวจต่อ แต่ยังต้องผ่าน operational sign-off ก่อน Post' : 'ยังไม่พร้อม Post: ' + (blockers.join(' · ') || 'ตรวจสอบรายการที่ไม่ผ่าน')) : 'โหมด Preview เท่านั้น — Inventory → GL posting ยังปิดอยู่; แก้รายการที่ไม่พร้อมแล้วรอผู้ดูแลเปิด feature flag'; $('#preflight-guidance-text').text(guidance); $('#preflight-legacy-review-link').toggleClass('d-none', !((r.unresolved_legacy_review || 0) > 0 || (r.global_unresolved_legacy_review || 0) > 0)); $('#preflight-guidance').toggleClass('alert-warning', !r.ready || !r.global_ready || !r.posting_enabled).toggleClass('alert-success', r.ready && r.global_ready && r.posting_enabled); }).fail(function () { $('#preflight-status').text('ไม่สามารถอ่านสถานะ Preflight ได้'); $('#preflight-guidance-text').text('อ่าน readiness gate ไม่สำเร็จ กรุณาตรวจสิทธิ์และระบบข้อมูลก่อนดำเนินการ'); });
    loadRecostHealth(); $('#recost-health-refresh').on('click', loadRecostHealth); $(document).on('click', '.js-recost-retry', function () { var button = $(this); button.prop('disabled', true); $.ajax({ url: '{{ route('wms.stock-valuation.recost-retry') }}', method: 'POST', data: { _token: $('meta[name="csrf-token"]').attr('content'), request_id: button.data('id') } }).done(function (r) { Swal.fire({ icon: 'success', text: r.msg || 'ส่งกลับเข้าคิวแล้ว', timer: 1400, showConfirmButton: false }); loadRecostHealth(); }).fail(function (xhr) { Swal.fire({ icon: 'error', text: xhr.responseJSON?.message || 'Retry ไม่สำเร็จ' }); }).always(function () { button.prop('disabled', false); }); });
    var table = tableElement.DataTable($.extend(true, {}, window.erpDataTableDefaults, { ajax: { url: tableElement.data('url'), dataSrc: 'data', data: function (d) { d.item_id = $('#valuation-item').val(); } }, buttons: [window.erpExcelButton(tableElement)], columns: [
        { data: 'item_label', render: text.display }, { data: 'uom_label', render: text.display }, { data: 'on_hand', render: text.display }, { data: 'reserved', render: text.display }, { data: 'available', render: text.display }, { data: 'average_unit_cost', render: text.display }, { data: 'inventory_value', render: text.display }, { data: 'costing_label', render: text.display }, { data: 'recost_label', render: text.display }, { data: null, orderable: false, searchable: false, render: function (value, type, row) { return type === 'display' ? '<a class="btn btn-sm btn-app-soft" href="' + text.display(row.detail_url) + '" title="ดูรายละเอียดต้นทุน" aria-label="ดูรายละเอียดต้นทุน"><i class="bx bx-show" aria-hidden="true"></i></a>' : ''; } }
    ] }));
    var historicalTable = historicalElement.DataTable($.extend(true, {}, window.erpDataTableDefaults, { ajax: { url: historicalElement.data('url'), dataSrc: 'data', data: function (d) { d.item_id = $('#valuation-item').val(); d.as_of_date = $('#historical-as-of').val(); } }, buttons: [window.erpExcelButton(historicalElement)], columns: [
        { data: 'item_label', render: text.display }, { data: 'uom_label', render: text.display }, { data: 'final_quantity', render: text.display }, { data: 'final_value', render: text.display }, { data: 'pending_value', render: text.display }, { data: 'pending_count', render: text.display }, { data: 'status_label', render: text.display }, { data: null, orderable: false, searchable: false, render: function (value, type, row) { return type === 'display' ? '<a class="btn btn-sm btn-app-soft" href="' + text.display(row.detail_url) + '" title="ดูรายละเอียดต้นทุน" aria-label="ดูรายละเอียดต้นทุน"><i class="bx bx-show" aria-hidden="true"></i></a>' : ''; } }
    ] }));
    var reconciliationTable = reconciliationElement.DataTable($.extend(true, {}, window.erpDataTableDefaults, { ajax: { url: reconciliationElement.data('url'), dataSrc: 'data', data: function (d) { d.item_id = $('#valuation-item').val(); d.as_of_date = $('#historical-as-of').val(); } }, buttons: [window.erpExcelButton(reconciliationElement)], columns: [
        { data: 'item_label', render: text.display }, { data: 'final_value', render: text.display }, { data: 'balance_value', render: text.display }, { data: 'gl_value', render: text.display }, { data: 'difference', render: text.display }, { data: 'balance_difference', render: text.display }, { data: 'pending_count', render: text.display }, { data: 'unlinked_count', render: text.display }, { data: 'status_label', render: text.display }, { data: null, orderable: false, searchable: false, render: function (value, type, row) { return type === 'display' ? '<a class="btn btn-sm btn-app-soft" href="' + text.display(row.detail_url) + '" title="ดูรายละเอียดต้นทุน" aria-label="ดูรายละเอียดต้นทุน"><i class="bx bx-show" aria-hidden="true"></i></a>' : ''; } }
    ] }));
    window.erpInitSelect2('#valuation-item', { ajax: { url: '{{ route('wms.stock.item-options') }}', delay: 250, data: function (p) { return { q: p.term || '', page: p.page || 1 }; }, processResults: function (d) { return d; } } });
    $('#valuation-load').on('click', function () { table.ajax.reload(); historicalTable.ajax.reload(); reconciliationTable.ajax.reload(); });
    $('button[data-bs-toggle="tab"]').on('shown.bs.tab', function () {
        table.columns.adjust();
        historicalTable.columns.adjust();
        reconciliationTable.columns.adjust();
    });
});
</script>
<script>
$(function () {
    $.getJSON('{{ route('wms.stock-valuation.preflight-summary') }}').done(function (r) {
        var deferred = Number(r.deferred_unlinked || 0);
        if (deferred > 0) {
            $('#preflight-deferred-note').prop('hidden', false).append(' <span class="badge app-status-warning ms-2">' + deferred + ' รายการ</span>');
            var guidance = $('#preflight-guidance-text').text();
            if (guidance.indexOf('Deferred Issue/Return/Transfer') === -1) {
                $('#preflight-guidance-text').text(guidance + ' · Deferred Issue/Return/Transfer (' + deferred + ')');
            }
        }
    });
});
</script>
@endpush
