@extends('Wms::layout')
@section('title', 'Revaluation Run | WMS')
@section('content')
<style>
    .reval-page { max-width: 1800px; }
    .reval-summary { position: sticky; top: .75rem; z-index: 10; background: rgba(248,249,250,.94); backdrop-filter: blur(8px); padding: .5rem 0; }
    .reval-nav { display:flex; gap:.5rem; overflow-x:auto; white-space:nowrap; }
    .reval-nav a { color:inherit; text-decoration:none; }
    .reval-section { scroll-margin-top: 8rem; }
    .reval-checks { max-height: 29rem; overflow:auto; }
    .reval-table { max-height: 32rem; overflow:auto; }
    .reval-table thead th { position:sticky; top:0; z-index:2; background:#fff; white-space:nowrap; }
    .reval-table td, .reval-table th { white-space:nowrap; }
    .reval-history { max-height: 20rem; overflow:auto; }
    .reval-workflow { border-left: .35rem solid #0d6efd; }
    .reval-stepper { display:flex; gap:.5rem; overflow-x:auto; padding-bottom:.25rem; }
    .reval-step { min-width: 10.5rem; flex:1 0 10.5rem; border:1px solid #dee2e6; border-radius:.75rem; padding:.7rem .8rem; background:#fff; }
    .reval-step.is-done { border-color:#198754; background:#f0fff7; }
    .reval-step.is-current { border-color:#0d6efd; box-shadow:0 0 0 .15rem rgba(13,110,253,.12); }
    .reval-step.is-blocked { border-color:#dc3545; background:#fff7f7; }
    .reval-step small { display:block; color:#6c757d; }
    @media (max-width: 767.98px) {
        .reval-summary { position:static; }
        .reval-checks, .reval-table { max-height: none; }
    }
</style>
<div class="container-fluid px-3 px-lg-4 py-4 reval-page">
    @php $statusLabels = ['QUEUED' => 'รอประมวลผล', 'CALCULATING' => 'กำลังคำนวณ', 'WAITING_CONTINUATION' => 'รอทำงานต่อ', 'PENDING_APPROVAL' => 'รออนุมัติ', 'APPROVED' => 'อนุมัติแล้ว', 'APPLYING' => 'กำลัง Apply', 'STOCK_PROJECTED' => 'ปรับ Stock แล้ว', 'GL_POSTED' => 'ลงบัญชีแล้ว', 'COMPLETED' => 'เสร็จสมบูรณ์', 'REQUIRES_REVIEW' => 'ต้องตรวจสอบ', 'FAILED_RETRYABLE' => 'รอลองใหม่', 'LIMIT_REACHED' => 'ถึงขีดจำกัด', 'REJECTED' => 'ปฏิเสธ', 'CANCELLED' => 'ยกเลิกแล้ว']; $displayStatus = $statusLabels[$run->status] ?? $run->status; @endphp
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-3"><div><p class="eyebrow mb-2">WMS / COSTING CONTROL</p><h1 class="h3 mb-2">Revaluation Run #{{ $run->id }}</h1><p class="text-secondary mb-0">Allocation #{{ $run->root_allocation_id }} · {{ $run->rootAllocation?->movement?->source_reference ?: '-' }}</p></div><div class="d-flex align-items-center gap-2"><span class="badge app-status-info" title="{{ $run->status }}">{{ $displayStatus }}</span><a class="btn btn-outline-secondary" href="{{ route('wms.stock-valuation.revaluation.index') }}">กลับ Queue</a></div></div>
    @if(session('success'))<div class="alert {{ in_array($run->status, ['REQUIRES_REVIEW', 'FAILED_RETRYABLE', 'LIMIT_REACHED'], true) ? 'alert-warning' : 'alert-success' }} border-0">{{ session('success') }}@if(in_array($run->status, ['REQUIRES_REVIEW', 'FAILED_RETRYABLE', 'LIMIT_REACHED'], true))<div class="small mt-1">แต่ Run นี้ยังไม่พร้อมสำหรับการอนุมัติ ต้องตรวจสอบผลการคำนวณหรือสร้าง Run ใหม่จากเอกสารต้นทาง</div>@endif</div>@endif
    @if($errors->any())<div class="alert alert-danger border-0"><strong>ดำเนินการไม่สำเร็จ</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if(data_get($run->batch?->trigger_snapshot, 'compensation.type') === 'REVERSAL_AFTER_REVALUATION')
    <div class="alert alert-info border-0"><strong>Compensating Revaluation:</strong> Run นี้คำนวณจากเอกสารกลับรายการโดยไม่แก้ไข Run เดิม
        <div class="small mt-1">อ้างอิง Run ต้นทาง:
            @foreach(collect(data_get($run->batch->trigger_snapshot, 'compensation.links', []))->pluck('source_run_ids')->flatten()->unique() as $sourceRunId)
                <a href="{{ route('wms.stock-valuation.revaluation.show', $sourceRunId) }}">#{{ $sourceRunId }}</a>{{ $loop->last ? '' : ', ' }}
            @endforeach
        </div>
    </div>
    @endif
    <div class="alert alert-warning border-0 small"><i class="bx bx-shield-quarter me-1" aria-hidden="true"></i><strong>Review only:</strong> ตรวจ Snapshot, Variance และ Delta ก่อนตัดสินใจ การอนุมัติยังไม่เปลี่ยนข้อมูล Stock/Allocation/Journal</div>
    <div class="reval-summary mb-3"><nav class="reval-nav mb-2" aria-label="ส่วนของ Revaluation Run"><a class="btn btn-sm btn-app-soft" href="#preflight">ตรวจสอบ</a><a class="btn btn-sm btn-app-soft" href="#planned-delta">รายการปรับต้นทุน</a><a class="btn btn-sm btn-app-soft" href="#reconciliation">กระทบยอด</a><a class="btn btn-sm btn-app-soft" href="#recovery">กู้คืน/ยกเลิก</a><a class="btn btn-sm btn-app-soft" href="#history">ประวัติ</a></nav><div class="row g-2"><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body py-2"><div class="small text-secondary">สถานะ</div><div class="fw-semibold">{{ $displayStatus }}</div><div class="small text-secondary">{{ $run->status }}</div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body py-2"><div class="small text-secondary">ต้นทุนใหม่</div><div class="fw-semibold">{{ $run->proposed_unit_cost }}</div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body py-2"><div class="small text-secondary">Delta โดยประมาณ</div><div class="fw-semibold text-primary">{{ $run->estimated_delta_value }}</div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body py-2"><div class="small text-secondary">จำนวน Node</div><div class="fw-semibold">{{ $run->nodes_affected }}</div></div></div></div></div></div>
    @php
        $variance = $run->shadow_snapshot['variance_report'] ?? [];
        $calculationContract = (string) ($run->shadow_snapshot['calculation_contract_version'] ?? '');
        $isLegacyCalculation = $calculationContract === '' || ! str_starts_with($calculationContract, 'cost-shadow-v2-');
        $resumeStatuses = ['QUEUED', 'CALCULATING', 'WAITING_CONTINUATION', 'FAILED_RETRYABLE', 'APPROVED', 'APPLYING'];
        $cancelStatuses = ['QUEUED', 'CALCULATING', 'WAITING_CONTINUATION', 'FAILED_RETRYABLE', 'REQUIRES_REVIEW', 'LIMIT_REACHED', 'PENDING_APPROVAL', 'APPROVED', 'APPLYING'];
        $workflowSteps = [
            ['label' => 'ตรวจสอบผลคำนวณ', 'anchor' => '#preflight', 'rank' => 1],
            ['label' => 'อนุมัติแผน', 'anchor' => '#decision', 'rank' => 2],
            ['label' => 'Apply Stock/Cost', 'anchor' => '#apply', 'rank' => 3],
            ['label' => 'ลงบัญชี GL', 'anchor' => '#post-journal', 'rank' => 4],
            ['label' => 'ปิดรายการ', 'anchor' => '#reconciliation', 'rank' => 5],
        ];
        $workflowRank = match ($run->status) {
            'PENDING_APPROVAL' => 2,
            'APPROVED' => 3,
            'STOCK_PROJECTED' => 4,
            'GL_POSTED' => 5,
            'COMPLETED' => 6,
            default => 1,
        };
        $nextAction = match ($run->status) {
            'PENDING_APPROVAL' => ['title' => 'ตรวจสอบและอนุมัติแผน', 'detail' => 'ตรวจ Preflight และ Planned Delta แล้วตัดสินใจอนุมัติหรือปฏิเสธ', 'anchor' => '#decision'],
            'APPROVED' => ['title' => 'ส่งเข้า Apply Queue', 'detail' => 'ระบบจะปรับ Stock/Cost ตาม Planned Delta โดยยังไม่ลงบัญชี', 'anchor' => '#apply'],
            'STOCK_PROJECTED' => ['title' => 'ลงบัญชี Revaluation', 'detail' => 'สร้าง Journal จากผล Apply ก่อนตรวจ Reconciliation', 'anchor' => '#post-journal'],
            'GL_POSTED' => ['title' => 'ตรวจสอบและปิด Revaluation Run', 'detail' => 'Reconciliation ผ่านแล้ว จึงสามารถปิดรายการได้', 'anchor' => '#reconciliation'],
            'COMPLETED' => ['title' => 'ดำเนินการเสร็จสมบูรณ์', 'detail' => 'Run นี้ผ่าน Apply, GL Posting และ Reconciliation แล้ว', 'anchor' => '#history'],
            'QUEUED', 'CALCULATING', 'WAITING_CONTINUATION', 'APPLYING' => ['title' => 'รอระบบประมวลผล', 'detail' => 'ระบบกำลังทำงานอัตโนมัติ ไม่ต้องกดซ้ำ', 'anchor' => '#history'],
            default => ['title' => 'ตรวจสอบ Blocker', 'detail' => 'แก้ไขสาเหตุที่แสดงใน Preflight หรือสร้าง Run ใหม่ตามคำแนะนำ', 'anchor' => '#preflight'],
        };
    @endphp
    @if($isLegacyCalculation && $run->status === 'REQUIRES_REVIEW')<div class="alert alert-warning border-0"><strong>Run นี้เป็น Calculation Contract รุ่นเก่า</strong><div class="small mt-1">Run #{{ $run->id }} ไม่มี Canonical Shadow Snapshot จึงไม่สามารถอนุมัติหรือ Apply ได้ ให้ใช้ Run ใหม่ที่สร้างจากเอกสารต้นทางแทน</div></div>@endif
    <div class="alert {{ ($variance['status'] ?? '') === 'READY_FOR_REVIEW' ? 'alert-success' : 'alert-danger' }} border-0"><strong>Variance Report: {{ $variance['status'] ?? 'UNKNOWN' }}</strong>@if(!empty($variance['blockers']))<div class="small mt-1">Blocker: {{ implode(', ', $variance['blockers']) }}</div>@endif</div>
    <div class="card border-0 shadow-sm mb-4 reval-workflow"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3"><div><div class="small text-uppercase text-secondary fw-semibold">ขั้นตอนการทำงาน</div><h2 class="h5 mb-1">{{ $nextAction['title'] }}</h2><p class="text-secondary mb-0">{{ $nextAction['detail'] }}</p></div>@if($run->status !== 'COMPLETED')<a class="btn btn-dark" href="{{ $nextAction['anchor'] }}">ไปยังขั้นตอนนี้ <i class="bx bx-right-arrow-alt ms-1" aria-hidden="true"></i></a>@else<span class="badge app-status-success fs-6">เสร็จสมบูรณ์</span>@endif</div><div class="reval-stepper mt-3" aria-label="ลำดับขั้นตอน Revaluation">@foreach($workflowSteps as $step)@php $stepClass = $workflowRank > $step['rank'] ? 'is-done' : ($workflowRank === $step['rank'] ? 'is-current' : ''); @endphp<a class="reval-step {{ $stepClass }} text-decoration-none text-reset" href="{{ $step['anchor'] }}"><strong>{{ $loop->iteration }}. {{ $step['label'] }}</strong><small>{{ $workflowRank > $step['rank'] ? 'เสร็จแล้ว' : ($workflowRank === $step['rank'] ? 'ขั้นตอนปัจจุบัน' : 'รอดำเนินการ') }}</small></a>@endforeach</div></div></div>
    <div id="preflight" class="card border-0 shadow-sm mb-4 reval-section"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Preflight ก่อนอนุมัติ/Apply <span class="small text-secondary">({{ count($preflight['checks']) }} checks)</span></h2><span class="badge {{ $preflight['ready'] ? 'app-status-success' : 'app-status-danger' }}">{{ $preflight['ready'] ? 'พร้อมตรวจสอบต่อ' : 'ติด Blocker' }}</span></div><div class="reval-table"><table id="reval-preflight-table" class="table table-hover align-middle w-100" data-url="{{ route('wms.stock-valuation.revaluation.preflight-data', $run) }}"><thead><tr><th>ลำดับ</th><th>สถานะ</th><th>Check</th><th>รายละเอียด</th></tr></thead></table></div>@if($preflight['blockers'])<div class="small text-danger mt-3">Blocker: {{ implode(', ', $preflight['blockers']) }}</div>@endif</div></div>
    <div id="planned-delta" class="card border-0 shadow-sm mb-4 reval-section"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Planned Delta <span class="small text-secondary">({{ $deltaCount }} รายการ)</span></h2><span class="small text-secondary">โหลดทีละหน้าเพื่อรองรับข้อมูลจำนวนมาก</span></div><div class="reval-table"><table id="reval-delta-table" class="table table-hover align-middle w-100" data-url="{{ route('wms.stock-valuation.revaluation.deltas-data', $run) }}"><thead><tr><th>ลำดับ</th><th>Allocation</th><th>สถานะ</th><th>ต้นทุนเดิม</th><th>ต้นทุนใหม่</th><th>Delta</th><th>Applied Allocation</th></tr></thead></table></div></div></div>
    @if((in_array($run->status, $resumeStatuses, true) && auth()->user()->hasPermission('wms.cost-revaluation.recover')) || (in_array($run->status, $cancelStatuses, true) && !$hasAppliedDelta && auth()->user()->hasPermission('wms.cost-revaluation.cancel')))
    <div id="recovery" class="card border-warning shadow-sm mb-4 reval-section"><div class="card-body"><h2 class="h5 mb-2">Recovery Control</h2><p class="text-secondary small">Resume ใช้ checkpoint เดิมและไม่สร้าง Delta ซ้ำ ส่วน Cancel ใช้ได้ก่อนเริ่มกระทบ Stock/Cost เท่านั้น</p><div class="row g-4">
        @if(in_array($run->status, $resumeStatuses, true) && auth()->user()->hasPermission('wms.cost-revaluation.recover'))<div class="col-lg-6"><form method="post" action="{{ route('wms.stock-valuation.revaluation.resume', $run) }}">@csrf<label class="form-label">เหตุผลที่ Resume</label><textarea name="reason" class="form-control mb-3" rows="3" minlength="10" maxlength="1000" required>{{ old('reason') }}</textarea><button class="btn btn-dark" type="submit"><i class="bx bx-refresh me-1"></i>ส่งกลับเข้าคิว</button></form></div>@endif
        @if(in_array($run->status, $cancelStatuses, true) && !$hasAppliedDelta && auth()->user()->hasPermission('wms.cost-revaluation.cancel'))<div class="col-lg-6"><form method="post" action="{{ route('wms.stock-valuation.revaluation.cancel', $run) }}">@csrf<label class="form-label">เหตุผลที่ยกเลิก</label><textarea name="reason" class="form-control mb-2" rows="3" minlength="10" maxlength="1000" required></textarea><label class="form-label small">พิมพ์ <code>CANCEL RUN {{ $run->id }}</code> เพื่อยืนยัน</label><input name="confirmation" class="form-control mb-3" required autocomplete="off"><button class="btn btn-outline-danger" type="submit"><i class="bx bx-x-circle me-1"></i>ยกเลิก Run</button></form></div>@endif
    </div>@if($run->last_error)<div class="alert alert-danger border-0 mt-3 mb-0"><strong>ข้อผิดพลาดล่าสุด:</strong> {{ $run->last_error }}</div>@endif</div></div>
    @endif
    @if($run->status === 'PENDING_APPROVAL' && auth()->user()->hasPermission('wms.cost-revaluation.approve'))<div id="decision" class="card border-0 shadow-sm reval-section"><div class="card-body"><h2 class="h5 mb-3">ตัดสินใจ</h2><div class="row g-3"><div class="col-md-8"><label class="form-label">เหตุผล <span class="text-danger">*</span></label><textarea id="reason" class="form-control" rows="3" minlength="10" placeholder="ระบุเหตุผลอย่างน้อย 10 ตัวอักษร"></textarea></div><div class="col-md-4 d-flex align-items-end gap-2"><form method="post" action="{{ route('wms.stock-valuation.revaluation.approve', $run) }}" class="js-decision-form">@csrf<input type="hidden" name="reason" class="decision-reason"><button class="btn btn-dark flex-fill" type="submit">อนุมัติแผน</button></form><form method="post" action="{{ route('wms.stock-valuation.revaluation.reject', $run) }}" class="js-decision-form">@csrf<input type="hidden" name="reason" class="decision-reason"><button class="btn btn-outline-danger flex-fill" type="submit">ปฏิเสธ</button></form></div></div></div></div>@endif
    @if($run->status === 'STOCK_PROJECTED' && auth()->user()->hasPermission('wms.cost-revaluation.post'))<div id="post-journal" class="card border-0 shadow-sm reval-section"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h2 class="h5 mb-1">ลงบัญชี Revaluation</h2><p class="text-secondary mb-0">สร้าง Journal ตาม event `inventory.recost` หลัง Stock Projection แล้ว โดยต้องเปิด Feature Gate ก่อน</p></div><form method="post" action="{{ route('wms.stock-valuation.revaluation.post-journal', $run) }}">@csrf<button class="btn btn-dark" type="submit">ลงบัญชี Revaluation</button></form></div></div>@endif
    @if($run->status === 'APPROVED' && auth()->user()->hasPermission('wms.cost-revaluation.post'))<div id="apply" class="card border-warning shadow-sm mb-4 reval-section"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h2 class="h5 mb-1">Apply Revaluation</h2><p class="text-secondary mb-0">ส่งงานไปปรับ Stock/Cost ตาม Planned Delta แบบ bounded job; ยังไม่ลงบัญชีจนกว่าจะถึงขั้น GL Posting</p></div><form method="post" action="{{ route('wms.stock-valuation.revaluation.apply', $run) }}" onsubmit="return confirm('ยืนยันส่ง Run #{{ $run->id }} เข้า Apply Queue? ระบบจะเริ่มปรับ Stock/Cost ตาม Planned Delta');">@csrf<button class="btn btn-dark" type="submit">ส่งเข้า Apply Queue</button></form></div></div>@endif
    <div id="reconciliation" class="card border-0 shadow-sm mt-4 reval-section"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Post-Revaluation Reconciliation <span class="small text-secondary">({{ count($reconciliation['checks']) }} checks)</span></h2><span class="badge {{ $reconciliation['ready'] ? 'app-status-success' : 'app-status-danger' }}">{{ $reconciliation['ready'] ? 'ตรงกัน' : 'ต้องตรวจสอบ' }}</span></div><div class="reval-checks"><div class="row g-2">@foreach($reconciliation['checks'] as $check)<div class="col-md-6"><div class="border rounded p-2 small h-100"><strong class="{{ $check['status'] === 'PASS' ? 'text-success' : 'text-danger' }}">{{ $check['status'] }}</strong> · {{ $check['code'] }}<div class="text-secondary">{{ $check['detail'] }}</div></div></div>@endforeach</div></div><div class="small text-secondary mt-3">Stock Projection Delta: {{ $reconciliation['totals']['stock_projection_delta_value'] }} · Journal Inventory: {{ $reconciliation['totals']['journal_inventory_value'] }} · Journal Balance: {{ $reconciliation['totals']['journal_balance'] }}</div>@if($run->status === 'GL_POSTED' && $reconciliation['ready'] && auth()->user()->hasPermission('wms.cost-revaluation.post'))<form method="post" action="{{ route('wms.stock-valuation.revaluation.complete', $run) }}" class="mt-3">@csrf<button class="btn btn-dark" type="submit">ปิด Revaluation Run</button></form>@endif</div></div>
    <div id="history" class="card border-0 shadow-sm mt-4 reval-section"><div class="card-body"><h2 class="h5 mb-3">ประวัติ Recovery <span class="small text-secondary">({{ $history->count() }} รายการ)</span></h2><div class="reval-history">@forelse($history as $entry)<div class="border-bottom py-2"><div class="fw-semibold">{{ $entry->action }}</div><div class="small text-secondary">{{ $entry->created_at?->timezone('Asia/Bangkok')->format('d/m/Y H:i') }} · {{ $entry->user?->name ?: 'System' }}@if($entry->reason) · {{ $entry->reason }}@endif</div></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div></div>
</div>
@endsection
@push('scripts')
<script>$(function () { var text = $.fn.dataTable.render.text(), number = $.fn.dataTable.render.number(',', '.', 8), statusClass = { PASS: 'app-status-success', BLOCKED: 'app-status-danger', WARNING: 'app-status-warning' }, statusLabel = function (value, type) { if (type !== 'display') return value; return '<span class="badge '+(statusClass[value] || 'app-status-neutral')+'">'+text.display(value || '-')+'</span>'; }; $('#reval-preflight-table').DataTable($.extend(true, {}, window.erpDataTableDefaults, { processing: true, serverSide: true, deferRender: true, ajax: { url: $('#reval-preflight-table').data('url') }, order: [[2, 'asc']], columns: [window.erpRowNumberColumn(), { data: 'status', name: 'status', render: statusLabel }, { data: 'code', name: 'code', render: text.display }, { data: 'detail', name: 'detail', render: text.display }] })); $('#reval-delta-table').DataTable($.extend(true, {}, window.erpDataTableDefaults, { processing: true, serverSide: true, deferRender: true, ajax: { url: $('#reval-delta-table').data('url') }, order: [[1, 'asc']], columns: [window.erpRowNumberColumn(), { data: 'allocation_label', name: 'allocation_id', render: text.display }, { data: 'status', name: 'status', render: statusLabel }, { data: 'old_unit_cost', name: 'old_unit_cost', className: 'text-end', render: number }, { data: 'new_unit_cost', name: 'new_unit_cost', className: 'text-end', render: number }, { data: 'delta_value', name: 'delta_value', className: 'text-end', render: number }, { data: 'applied_allocation_label', name: 'applied_cost_allocation_id', render: text.display }] })); $('.js-decision-form').on('submit', function (e) { var reason = $('#reason').val().trim(); if (reason.length < 10) { e.preventDefault(); alert('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร'); return; } $(this).find('.decision-reason').val(reason); }); });</script>
@endpush
