@extends('Wms::layout')
@section('title', 'รายละเอียดต้นทุนสินค้า | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">WMS / COSTING</p><h1 class="h3 mb-2">รายละเอียดต้นทุนสินค้า</h1><p class="text-secondary mb-0">{{ $item->code }} · {{ $item->name }}</p></div><a class="btn btn-app-soft" href="{{ route('wms.stock-valuation.index') }}"><i class="bx bx-arrow-back me-1"></i>กลับมูลค่าสินค้าคงเหลือ</a></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body row g-3"><div class="col-md-4"><div class="small text-secondary">สินค้า</div><div class="fw-semibold">{{ $item->code }} · {{ $item->name }}</div></div><div class="col-md-4"><div class="small text-secondary">คลัง</div><div>{{ $warehouse?->name ?? '-' }}</div></div><div class="col-md-4"><div class="small text-secondary">วิธีคำนวณ</div><div>AVG / FIFO ตาม Cost Layer ของรายการ</div></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3">Cost Layer และการคำนวณต้นทุน</h2><table id="cost-layer-table" class="table table-hover w-100" data-url="{{ route('wms.stock-valuation.layers', $item) }}"><thead><tr><th>วันที่</th><th>วิธี</th><th>จำนวนตั้งต้น</th><th>คงเหลือใน Layer</th><th>ต้นทุนต่อหน่วย</th><th>สถานะ</th><th>เอกสารอ้างอิง</th></tr></thead></table></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">การเคลื่อนไหวสินค้า</h2><table id="movement-table" class="table table-hover w-100" data-url="{{ route('wms.stock.data') }}"><thead><tr><th>วันที่</th><th>ประเภท</th><th>ทิศทาง</th><th>จำนวนฐาน</th><th>หน่วย</th><th>เอกสารอ้างอิง</th></tr></thead></table></div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){var x=$.fn.dataTable.render.text();var c=$('#cost-layer-table');c.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:c.data('url'),buttons:[window.erpExcelButton(c)],columns:[{data:'business_date',render:x.display},{data:'method_label',render:x.display},{data:'original_quantity',className:'text-end',render:x.display},{data:'remaining_quantity',className:'text-end',render:x.display},{data:'unit_cost',className:'text-end',render:x.display},{data:'status_label',render:x.display},{data:'source_reference',render:function(v){return x.display(v||'-')}}]}));var m=$('#movement-table');m.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:m.data('url'),data:function(d){d.item_id={{ $item->id }};d.as_of=new Date().toISOString().slice(0,10)}},buttons:[window.erpExcelButton(m)],columns:[{data:'business_date',render:x.display},{data:'movement_type_label',render:x.display},{data:'direction_label',render:x.display},{data:'base_quantity_label',className:'text-end',render:x.display},{data:'uom_label',render:x.display},{data:'source_reference',render:function(v){return x.display(v||'-')}}]}));});</script>
@endpush
