@extends('Wms::layout')
@section('title', 'สร้างใบเบิกวัตถุดิบผลิต | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">WMS / PRODUCTION MATERIAL ISSUE</p><h1 class="h3 mb-2">สร้างใบเบิกวัตถุดิบผลิต</h1><p class="text-secondary mb-0">เบิกวัตถุดิบสำหรับการผลิตแบบ Manual โดยไม่ต้องเปิด Production Module</p></div><a class="btn btn-outline-secondary" href="{{ route('wms.production.material-issues.index') }}">← กลับ</a></div><div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><form id="production-issue-form" method="post" action="{{ route('wms.production.material-issues.store') }}">@csrf<input type="hidden" name="issue_type" value="PRODUCTION"><div class="row g-3 mb-4"><div class="col-md-4"><label class="form-label">วันที่เอกสาร</label><input class="form-control" type="date" name="document_date" value="{{ now()->format('Y-m-d') }}" required></div><div class="col-md-8"><label class="form-label">เหตุผล</label><input class="form-control" name="reason" minlength="5" maxlength="500" placeholder="ระบุเหตุผลการเบิกวัตถุดิบ" required></div></div><div class="d-flex justify-content-between align-items-center mb-2"><div><h2 class="h5 mb-1">รายการเบิกวัตถุดิบ</h2><p class="text-secondary small mb-0">ใช้หน่วย Stock ของสินค้าและตรวจคงเหลือจากคลังปัจจุบัน</p></div><button type="button" class="btn btn-sm btn-app-soft" id="add-production-line">+ เพิ่มรายการ</button></div><div class="table-responsive"><table class="table align-middle" id="production-issue-lines"><thead><tr><th style="min-width:320px">สินค้า</th><th style="min-width:190px">หน่วย Stock</th><th class="text-end" style="min-width:170px">คงเหลือพร้อมใช้</th><th class="text-end" style="min-width:180px">จำนวนเบิก</th><th style="width:60px">จัดการ</th></tr></thead><tbody><tr><td><select class="form-select js-production-item" name="lines[0][item_id]" required><option value="">ค้นหาสินค้า</option></select></td><td><select class="form-select js-production-uom" name="lines[0][uom_id]" required><option value="">หน่วย Stock</option></select></td><td class="text-end"><span class="js-production-available text-secondary">เลือกสินค้า</span></td><td><input class="form-control text-end" type="number" name="lines[0][quantity]" min="0.00000001" step="any" required></td><td><button type="button" class="btn btn-sm btn-app-danger js-production-remove" title="ลบรายการ"><i class="bx bx-trash"></i></button></td></tr></tbody></table></div><div class="d-flex gap-2 mt-4"><button class="btn btn-dark" type="submit">บันทึกร่าง</button><a class="btn btn-outline-secondary" href="{{ route('wms.production.material-issues.index') }}">ยกเลิก</a></div></form></div></div></div>
@endsection
@push('scripts')
<script>
$(function(){const tb=$('#production-issue-lines tbody'),itemUrl='{{ route('wms.production.material-issues.item-options') }}';function init(s){window.erpInitSelect2(s,{ajax:{url:itemUrl,delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:d=>d}});s.on('select2:select',e=>{const d=e.params.data,r=s.closest('tr');r.find('.js-production-uom').empty().append(new Option(d.uom_label||'หน่วย Stock',d.uom_id,true,true));r.find('.js-production-available').text(d.available_label||'เลือกสินค้า').toggleClass('text-success',Number(d.available_quantity)>0).toggleClass('text-danger',Number(d.available_quantity)<=0);}).on('select2:clear',()=>s.closest('tr').find('.js-production-available').text('เลือกสินค้า').removeClass('text-success text-danger'));}init($('.js-production-item'));$('#add-production-line').on('click',function(){const i=tb.find('tr').length,r=$('<tr><td><select class="form-select js-production-item" name="lines['+i+'][item_id]" required><option value="">ค้นหาสินค้า</option></select></td><td><select class="form-select js-production-uom" name="lines['+i+'][uom_id]" required><option value="">หน่วย Stock</option></select></td><td class="text-end"><span class="js-production-available text-secondary">เลือกสินค้า</span></td><td><input class="form-control text-end" type="number" name="lines['+i+'][quantity]" min="0.00000001" step="any" required></td><td><button type="button" class="btn btn-sm btn-app-danger js-production-remove" title="ลบรายการ"><i class="bx bx-trash"></i></button></td></tr>');tb.append(r);init(r.find('.js-production-item'));});tb.on('click','.js-production-remove',function(){if(tb.find('tr').length>1)$(this).closest('tr').remove();});window.erpAjaxForm({form:'#production-issue-form',url:$('#production-issue-form').attr('action'),method:'POST',redirect:true});});
</script>
@endpush
