@extends('Wms::layout')
@php($statusLabels = ['DRAFT' => 'ร่าง', 'APPROVED' => 'อนุมัติแล้ว', 'POSTED' => 'ลง Stock แล้ว', 'VOID' => 'ยกเลิกเอกสาร'])
@php($statusClasses = ['DRAFT' => 'app-status-neutral', 'APPROVED' => 'app-status-info', 'POSTED' => 'app-status-success', 'VOID' => 'app-status-danger'])
@section('title', 'ใบเบิกวัตถุดิบผลิต '.$document->document_number.' | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">WMS / PRODUCTION MATERIAL ISSUE</p><h1 class="h3 mb-2">{{ $document->document_number }}</h1><span class="badge {{ $statusClasses[$document->status] ?? 'app-status-neutral' }}">{{ $statusLabels[$document->status] ?? $document->status }}</span></div>
        <div class="d-flex flex-wrap gap-2">
            <a class="btn btn-outline-secondary" href="{{ route('wms.production.material-issues.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a>
            @if($document->status === 'DRAFT' && auth()->user()->hasPermission('wms.issues.approve'))<button class="btn btn-app-primary js-action" data-url="{{ route('wms.production.material-issues.approve', $document) }}" data-action="approve">อนุมัติ</button>@endif
            @if($document->status === 'APPROVED' && auth()->user()->hasPermission('wms.issues.post'))<button class="btn btn-app-primary js-action" data-url="{{ route('wms.production.material-issues.post', $document) }}" data-action="post">ลง Stock</button>@endif
            @if(in_array($document->status, ['DRAFT', 'APPROVED'], true) && auth()->user()->hasPermission('wms.issues.approve'))<button class="btn btn-app-danger js-action" data-url="{{ route('wms.production.material-issues.cancel', $document) }}" data-action="cancel">ยกเลิกเอกสาร</button>@endif
            @if($document->status === 'DRAFT' && auth()->user()->hasPermission('wms.issues.delete'))<button class="btn btn-app-danger js-action" data-url="{{ route('wms.production.material-issues.destroy', $document) }}" data-action="delete">ลบร่าง</button>@endif
            @if($document->status === 'POSTED' && auth()->user()->hasPermission('wms.inventory-adjustments.create'))<a class="btn btn-app-primary" href="{{ route('wms.production.finished-receipts.create', ['source_issue_id' => $document->id]) }}">สร้างใบรับผลิตเสร็จ</a>@endif
            @if($document->status === 'POSTED' && auth()->user()->hasPermission('wms.issue-returns.create'))<a class="btn btn-app-soft" href="{{ route('wms.production.issue-returns.create', ['issue_document_id' => $document->id]) }}">สร้างใบรับคืนวัตถุดิบ</a>@endif
        </div>
    </div>
    <div class="alert alert-info border-0 mb-4"><strong>ขั้นตอนถัดไป:</strong> {{ $document->status === 'DRAFT' ? 'ตรวจสอบรายการ แล้วกด “อนุมัติ”' : ($document->status === 'APPROVED' ? 'กด “ลง Stock” เพื่อบันทึกผลกระทบยอดคงเหลือ' : ($document->status === 'POSTED' ? 'สร้างใบรับผลิตเสร็จ หรือสร้างใบรับคืนวัตถุดิบตามผลการผลิต' : 'เอกสารนี้ไม่มีขั้นตอนที่ต้องดำเนินการต่อ')) }}</div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-3"><small class="text-secondary">วันที่เอกสาร</small><div class="fw-semibold">{{ $document->document_date?->format($dateFormat) ?: '-' }}</div></div><div class="col-md-3"><small class="text-secondary">ประเภทการเบิก</small><div class="fw-semibold">เบิกเข้าผลิต (PRODUCTION)</div></div><div class="col-md-6"><small class="text-secondary">เหตุผล</small><div class="fw-semibold">{{ $document->reason ?: '-' }}</div></div></div></div></div>
    @if($document->issueReturns->isNotEmpty())<div class="card border-primary-subtle shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">เอกสารรับคืนวัตถุดิบผลิต</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>เลขที่เอกสาร</th><th>วันที่</th><th>สถานะ</th><th class="text-end">จำนวนรวม</th><th>จัดการ</th></tr></thead><tbody>@foreach($document->issueReturns as $return)<tr><td>{{ $return->document_number }}</td><td>{{ $return->document_date?->format($dateFormat) ?: '-' }}</td><td>{{ $statusLabels[$return->status] ?? $return->status }}</td><td class="text-end">{{ \App\Modules\Wms\Support\WmsDecimal::format($return->lines->sum('quantity')) }}</td><td><a class="btn btn-sm btn-app-soft" href="{{ route('wms.production.issue-returns.show', $return) }}">ดูรายละเอียด</a></td></tr>@endforeach</tbody></table></div></div></div>@endif
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-1">รายการเบิกวัตถุดิบ</h2><p class="text-secondary small mb-3">คงเหลือพร้อมใช้ ณ ปัจจุบัน</p><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>สินค้า</th><th>หน่วย</th><th class="text-end">คงเหลือพร้อมใช้</th><th class="text-end">จำนวนเบิก</th><th>Movement</th><th class="text-end">ต้นทุน</th></tr></thead><tbody>@foreach($document->lines as $line)@php($available=(string)($stockBalances[$line->item_id.':'.$line->uom_id]?->available ?? '0'))<tr><td>{{ $line->line_number }}</td><td>{{ $line->item?->code }} · {{ $line->item?->name }}</td><td>{{ $line->uom?->code }}</td><td class="text-end">{{ \App\Modules\Wms\Support\WmsDecimal::format($available) }}</td><td class="text-end">{{ \App\Modules\Wms\Support\WmsDecimal::format($line->quantity) }}</td><td>{{ $line->movement?->id ? '#'.$line->movement->id : '-' }}</td><td class="text-end">{{ $line->allocation ? \App\Modules\Wms\Support\WmsDecimal::format($line->allocation->value) : '-' }}</td></tr>@endforeach</tbody></table></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $entry)<div class="border-bottom py-2"><strong>{{ $entry->action }}</strong><small class="text-secondary ms-2">{{ $entry->created_at?->format($dateFormat.' H:i') }} · {{ $entry->user?->name ?? '-' }}</small></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){$('.js-action').on('click',function(){const b=$(this),a=b.data('action');Swal.fire({icon:'warning',title:a==='approve'?'อนุมัติใบเบิกวัตถุดิบ?':a==='post'?'ลง Stock ใบเบิกวัตถุดิบ?':a==='cancel'?'ยกเลิกเอกสารใบเบิกวัตถุดิบ?':'ลบร่างใบเบิก?',input:a==='cancel'?'textarea':undefined,inputLabel:a==='cancel'?'เหตุผลการยกเลิกเอกสาร':undefined,showCancelButton:true,confirmButtonText:a==='cancel'?'ยืนยันยกเลิกเอกสาร':a==='delete'?'ลบร่าง':'ยืนยัน',cancelButtonText:'กลับ'}).then(x=>{if(!x.isConfirmed)return;const data={_token:$('meta[name=csrf-token]').attr('content')};if(a==='cancel')data.reason=x.value;$.ajax({url:b.data('url'),type:a==='delete'?'DELETE':'POST',data}).done(r=>{Swal.fire({icon:'success',text:r.msg,timer:1000,showConfirmButton:false}).then(()=>location.href=r.redirect||location.href)}).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ดำเนินการไม่สำเร็จ'}));});});});</script>
@endpush
