@extends('Pos::layout')
@section('content')
@php($activeSale = $order->physicalSales->first(fn ($sale) => $sale->status !== 'VOID'))
@php($canCreatePhysicalSale = $order->status === 'CONFIRMED' && ! $activeSale)
@php($canRequestProduction = $productionEnabled && $order->status === 'CONFIRMED' && ! $activeSale && auth()->user()->hasPermission('pos.sales-orders.confirm'))
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="app-eyebrow">SALES / SALES ORDER</p>
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
        <div><h1 class="h2 mb-2">ใบสั่งขาย {{ $order->document_number }}</h1>@include('Pos::partials.document-status-badge', ['status' => $order->status, 'label' => ['DRAFT'=>'ร่าง','CONFIRMED'=>'ยืนยันแล้ว','FULFILLED'=>'ดำเนินการแล้ว','CANCELLED'=>'ยกเลิก'][$order->status] ?? $order->status])</div>
        <div class="d-flex flex-wrap justify-content-end gap-2"><a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-orders.index') }}"><i class="bx bx-arrow-back"></i>กลับหน้ารายการ</a>@if(auth()->user()->hasPermission('pos.sales-orders.print'))<a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-orders.pdf', $order) }}" target="_blank" rel="noopener"><i class="bx bx-printer"></i>พิมพ์ PDF</a>@endif @if($order->quotation || $order->rfq || $order->sourceIntake)<a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ $order->quotation ? route('pos.sales-quotations.show', $order->quotation) : ($order->rfq ? route('pos.sales-rfqs.show', $order->rfq) : route('pos.sales-intakes.show', $order->sourceIntake)) }}"><i class="bx bx-link-external"></i>ดูเอกสารต้นทาง</a>@endif @if($order->status === 'DRAFT' && auth()->user()->hasPermission('pos.sales-orders.confirm'))<button class="btn btn-app-primary d-inline-flex align-items-center gap-1 js-order-action" data-url="{{ route('pos.sales-orders.confirm', $order) }}" data-title="ยืนยันใบสั่งขาย?" data-confirm="ยืนยัน"><i class="bx bx-check-circle"></i>ยืนยันใบสั่งขาย</button>@endif @if($canCreatePhysicalSale && auth()->user()->hasPermission('pos.physical-sales.create'))<a class="btn btn-app-primary d-inline-flex align-items-center gap-1" href="{{ route('pos.physical-sales.create', ['sales_order_id' => $order->id]) }}"><i class="bx bx-receipt"></i>สร้าง HS/IV</a>@endif @if(in_array($order->status, ['DRAFT', 'CONFIRMED'], true) && auth()->user()->hasPermission('pos.sales-orders.cancel'))<button class="btn btn-app-danger d-inline-flex align-items-center gap-1 js-order-action" data-url="{{ route('pos.sales-orders.cancel', $order) }}" data-title="ยกเลิกเอกสารใบสั่งขาย?" data-confirm="ยกเลิกเอกสาร" data-reason="1"><i class="bx bx-x-circle"></i>ยกเลิกเอกสาร</button>@endif @include('Pos::partials.draft-delete-button', ['document' => $order, 'permission' => 'pos.sales-orders.delete', 'url' => route('pos.sales-orders.destroy', $order)])</div>
    </div>
    @if($order->status === 'DRAFT')<div class="alert alert-info border-0 shadow-sm mb-4"><strong>ขั้นถัดไป:</strong> ตรวจสอบรายการและยืนยันใบสั่งขาย เพื่อเปิดสิทธิ์สร้าง HS/IV</div>@elseif($canCreatePhysicalSale)<div class="alert alert-info border-0 shadow-sm mb-4"><strong>ขั้นถัดไป:</strong> สร้าง HS/IV ตามปกติ โดยต้องมีสต็อกเพียงพอครบทุกรายการในคลังจัดส่งตอนลงรายการขาย @if($productionEnabled)ฝ่ายขายสามารถส่งคำขอสั่งผลิตให้ฝ่ายวางแผนได้; การขอผลิตไม่สร้าง WO และไม่ขัดขวางการขายจากสต็อก@endif</div>@elseif($activeSale && $order->status !== 'FULFILLED')<div class="alert alert-info border-0 shadow-sm mb-4"><strong>{{ $activeSale->status === 'POSTED' ? 'ขายแล้ว:' : 'ขั้นถัดไป:' }}</strong> HS/IV {{ $activeSale->document_number }} · คลังจัดส่ง {{ $activeSale->warehouse?->code ?? '—' }} · {{ $activeSale->status === 'POSTED' ? 'WO ที่ค้างอยู่ผลิตต่อได้โดยไม่จองสินค้าซ้ำให้ใบสั่งขายนี้' : 'ตรวจสต็อกให้ครบทุกรายการก่อนลงรายการขาย แม้ WO จะยังผลิตไม่เสร็จ' }}</div>@elseif($order->status === 'FULFILLED')<div class="alert alert-success border-0 shadow-sm mb-4"><strong>เอกสารดำเนินการครบแล้ว</strong> สามารถตรวจสอบเอกสาร HS/IV ที่เชื่อมโยงได้จากเส้นทางเอกสารด้านล่าง</div>@endif
    @include('Pos::partials.document-trail', ['flowDocuments' => $flowDocuments])
    @include('Pos::partials.sales-document-header', ['document' => $order, 'sourceIntake' => $flowDocuments['intake'] ?? null])
    @if($order->description)<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="text-secondary small">รายละเอียด</div><div>{{ $order->description }}</div></div></div>@endif
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">รายการสินค้า</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>สินค้า/รายละเอียด</th><th>หน่วย</th><th class="text-end">จำนวน</th><th>Production</th><th class="text-end">ราคา</th><th class="text-end">ส่วนลด</th><th class="text-end">รวม</th></tr></thead><tbody>@forelse($order->lines as $line)
@php($wo = $productionOrders->get($line->id))
@php($itemReady = $line->item && $line->item->is_active && $line->item->item_type === 'GOODS' && $line->item->is_stock_item && $line->item->base_uom_id && (int) $line->item->base_uom_id === (int) $line->uom_id)
@php($manufacturable = $productionEnabled && ($order->production_legacy_eligible || $line->item?->can_manufacture))
@php($bomReady = $activeBoms->has($line->item_id.':'.$line->uom_id))
<tr><td>{{ $line->line_number }}</td><td>{{ data_get($line->item_snapshot, 'code') }} · {{ data_get($line->item_snapshot, 'name', $line->description) }}</td><td>{{ data_get($line->uom_snapshot, 'code', '—') }}</td><td class="text-end">{{ number_format((float) $line->quantity, 4) }}</td><td>
@if($productionEnabled && $wo)
    @if(auth()->user()->hasPermission('production.orders.view'))<a class="btn btn-sm btn-app-soft" href="{{ route('production.orders.show', $wo) }}"><i class="bx bx-show me-1" aria-hidden="true"></i>{{ $wo->document_number }}</a>@else<span>{{ $wo->document_number }}</span>@endif
    <span class="badge app-status-{{ $wo->status === 'COMPLETED' ? 'success' : ($wo->status === 'IN_PROGRESS' ? 'warning' : ($wo->status === 'DRAFT' ? 'neutral' : 'info')) }}">{{ ['DRAFT'=>'ร่าง','RELEASED'=>'พร้อมผลิต','IN_PROGRESS'=>'กำลังผลิต','COMPLETED'=>'เสร็จแล้ว'][$wo->status] ?? $wo->status }}</span>
    <div class="small text-secondary mt-1">คลังรับผลิต: {{ $wo->receiptWarehouse?->code ?? '—' }} · </div>
@elseif($manufacturable && $activeSale)
    <span class="text-secondary small">มี HS/IV แล้ว · ไม่สร้าง WO ผูกใบสั่งขายเพิ่ม</span>
@elseif($manufacturable && ! $itemReady)
    <span class="badge app-status-warning">สินค้า/หน่วยไม่พร้อม</span>
@elseif($line->production_requested_at && $manufacturable)
    <span class="badge app-status-info">ส่งคำขอผลิตแล้ว · รอฝ่ายวางแผน</span>
    <div class="small mt-1">กำหนดส่ง {{ $line->requested_delivery_date?->format('d/m/Y') ?: '—' }} · เริ่มได้ตั้งแต่ {{ $line->requested_start_date?->format('d/m/Y') ?: 'ไม่ระบุ' }}</div>
    @if($line->production_specification)<div class="small text-secondary mt-1">ข้อกำหนดลูกค้า: {{ $line->production_specification }}</div>@endif
    @if($canRequestProduction)<button class="btn btn-sm btn-app-soft js-request-production mt-2" type="button" data-url="{{ route('pos.sales-orders.production-request', [$order, $line->id]) }}" data-item="{{ data_get($line->item_snapshot, 'name', $line->description) }}" data-quantity="{{ number_format((float) $line->quantity, 4) }} {{ data_get($line->uom_snapshot, 'code', '') }}" data-delivery="{{ $line->requested_delivery_date?->format('Y-m-d') }}" data-start="{{ $line->requested_start_date?->format('Y-m-d') }}" data-spec="{{ $line->production_specification }}"><i class="bx bx-edit me-1" aria-hidden="true"></i>แก้ไขคำขอ</button>@endif
@elseif($canRequestProduction && $manufacturable && $itemReady)
    <button class="btn btn-sm btn-app-soft js-request-production" type="button" data-url="{{ route('pos.sales-orders.production-request', [$order, $line->id]) }}" data-item="{{ data_get($line->item_snapshot, 'name', $line->description) }}" data-quantity="{{ number_format((float) $line->quantity, 4) }} {{ data_get($line->uom_snapshot, 'code', '') }}" data-delivery="{{ $order->required_delivery_date?->format('Y-m-d') }}"><i class="bx bx-send me-1" aria-hidden="true"></i>ขอสั่งผลิต</button>
    @unless($bomReady)<div class="small text-warning mt-1">ยังไม่มี Active BOM · ส่งคำขอได้ แต่ฝ่ายผลิตต้องตั้งค่า BOM ก่อนสร้าง WO</div>@endunless
@elseif($manufacturable && ! $bomReady)
    <span class="badge app-status-warning">ตั้งค่า BOM ก่อนสร้าง WO</span>
@elseif($manufacturable)
    <span class="badge app-status-info">{{ $order->status === 'CONFIRMED' ? 'ประสานฝ่ายผลิตเพื่อสร้าง WO' : 'สั่งผลิตได้หลังยืนยัน SO' }}</span>
@elseif($productionEnabled)
    <span class="text-secondary small">ยังไม่เปิดให้สั่งผลิต · ขายจากสต็อกตามปกติ</span>
@else<span class="text-secondary">—</span>@endif
</td><td class="text-end">{{ number_format((float) $line->unit_price, 2) }}</td><td class="text-end">{{ number_format((float) $line->discount_amount, 2) }}</td><td class="text-end">{{ number_format((float) $line->line_total, 2) }}</td></tr>@empty<tr><td colspan="8" class="text-center text-secondary">ไม่มีรายการ</td></tr>@endforelse</tbody><tfoot><tr><th colspan="7" class="text-end">ยอดรวม</th><th class="text-end">{{ number_format((float) $order->total_amount, 2) }}</th></tr></tfoot></table></div>@include('Pos::partials.sales-tax-summary', ['document' => $order, 'sourceIntake' => $flowDocuments['intake'] ?? null])</div></div>
    @if($canRequestProduction)<div class="modal fade" id="production-request-modal" tabindex="-1" aria-labelledby="production-request-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" id="production-request-form" method="post">@csrf<div class="modal-header"><h2 class="modal-title h5" id="production-request-title">ขอสั่งผลิต</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body"><p id="production-request-item" class="fw-semibold mb-1"></p><p id="production-request-quantity" class="text-secondary small"></p><p class="text-secondary small">ส่งข้อมูลให้ฝ่ายวางแผนพิจารณา ยังไม่สร้างใบสั่งผลิต และยังขายจากสต็อกได้</p><div class="mb-3"><label class="form-label" for="requested-delivery">กำหนดส่งที่ลูกค้าต้องการ <span class="text-danger">*</span></label><input id="requested-delivery" name="requested_delivery_date" class="form-control" type="date" required><div class="invalid-feedback" data-error-for="requested_delivery_date"></div></div><div class="mb-3"><label class="form-label" for="requested-start">ลูกค้าขอเริ่มผลิตตั้งแต่ (ถ้ามี)</label><input id="requested-start" name="requested_start_date" class="form-control" type="date"><div class="invalid-feedback" data-error-for="requested_start_date"></div><div class="form-text">ไม่ใช่วันเริ่มแผนผลิต ฝ่ายวางแผนจะกำหนดวันจริง</div></div><div><label class="form-label" for="production-specification">ข้อกำหนดเฉพาะของลูกค้าสำหรับสินค้ารายการนี้</label><textarea id="production-specification" name="production_specification" class="form-control" maxlength="2000" rows="3" placeholder="เช่น ห้ามตัดส่วน A"></textarea><div class="invalid-feedback" data-error-for="production_specification"></div></div><div id="production-request-error" class="text-danger small mt-2" role="alert" hidden></div></div><div class="modal-footer"><button type="button" class="btn btn-app-soft" data-bs-dismiss="modal">กลับ</button><button type="submit" class="btn btn-app-primary"><i class="bx bx-send me-1" aria-hidden="true"></i>ส่งคำขอสั่งผลิต</button></div></form></div></div>@endif
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $entry)<div class="border-bottom py-2"><span class="text-secondary small">{{ optional($entry->created_at)->format('d/m/Y H:i') }}</span> <strong>{{ ['pos.sales-order.created'=>'สร้างใบสั่งขาย','pos.sales-order.confirm'=>'ยืนยันใบสั่งขาย','pos.sales-order.cancel'=>'ยกเลิกใบสั่งขาย','pos.sales-order.production-requested'=>'ส่งคำขอสั่งผลิต'][$entry->action] ?? $entry->action }}</strong> @if($entry->action === 'pos.sales-order.production-requested')<span>รายการ #{{ data_get($entry->new_values, 'line_number') }}</span>@endif <span class="text-secondary">{{ $entry->user?->name }}</span></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection
@push('scripts')<script>$(function(){$(document).on('click','.js-order-action',function(){const button=$(this),cancel=button.data('reason')===1,options={icon:cancel?'warning':'question',title:button.data('title'),showCancelButton:true,confirmButtonText:button.data('confirm'),cancelButtonText:'กลับ'};if(cancel){options.input='textarea';options.inputLabel='เหตุผลการยกเลิก';options.inputPlaceholder='ระบุเหตุผลอย่างน้อย 10 ตัวอักษร';options.inputValidator=value=>value&&value.trim().length>=10?undefined:'กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร'}Swal.fire(options).then(result=>{if(!result.isConfirmed)return;button.prop('disabled',true);const data={_token:$('meta[name=csrf-token]').attr('content')};if(cancel)data.reason=result.value;$.post(button.data('url'),data).done(response=>Swal.fire({icon:'success',text:response.msg}).then(()=>location.reload())).fail(xhr=>{button.prop('disabled',false);Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ดำเนินการไม่สำเร็จ'})})})});$(document).on('click','.js-request-production',function(){const button=$(this),form=$('#production-request-form');form.attr('action',button.data('url'));form[0].reset();form.find('.is-invalid').removeClass('is-invalid');$('#production-request-error').prop('hidden',true);$('#production-request-item').text(button.data('item'));$('#production-request-quantity').text('จำนวน '+button.data('quantity')+' (คำขอเต็มจำนวนรายการ)');form.find('[name=requested_delivery_date]').val(button.attr('data-delivery')||'');form.find('[name=requested_start_date]').val(button.attr('data-start')||'');form.find('[name=production_specification]').val(button.attr('data-spec')||'');bootstrap.Modal.getOrCreateInstance(document.getElementById('production-request-modal')).show()});$('#production-request-form').on('submit',function(event){event.preventDefault();const form=$(this),button=form.find('[type=submit]').prop('disabled',true);form.find('.is-invalid').removeClass('is-invalid');$('#production-request-error').prop('hidden',true);$.post(form.attr('action'),form.serialize()).done(()=>location.reload()).fail(xhr=>{button.prop('disabled',false);const errors=xhr.responseJSON?.errors||{};Object.entries(errors).forEach(([name,messages])=>{form.find('[name='+name+']').addClass('is-invalid');form.find('[data-error-for='+name+']').text(messages[0])});$('#production-request-error').text(xhr.responseJSON?.message||'ส่งคำขอสั่งผลิตไม่สำเร็จ กรุณาลองใหม่').prop('hidden',false)})});});</script>@endpush
