@extends('Pos::layout')
@section('content')
@php($canCreatePhysicalSale = $order->status === 'CONFIRMED' && $order->physicalSales->where('status', '!=', 'VOID')->isEmpty())
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="app-eyebrow">SALES / SALES ORDER</p>
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
        <div><h1 class="h2 mb-2">ใบสั่งขาย {{ $order->document_number }}</h1>@include('Pos::partials.document-status-badge', ['status' => $order->status, 'label' => ['DRAFT'=>'ร่าง','CONFIRMED'=>'ยืนยันแล้ว','FULFILLED'=>'ดำเนินการแล้ว','CANCELLED'=>'ยกเลิก'][$order->status] ?? $order->status])</div>
        <div class="d-flex flex-wrap justify-content-end gap-2">@if($order->status === 'DRAFT' && auth()->user()->hasPermission('pos.sales-orders.confirm'))<button class="btn btn-primary d-inline-flex align-items-center gap-1 js-order-action" data-url="{{ route('pos.sales-orders.confirm', $order) }}" data-title="ยืนยันใบสั่งขาย?" data-confirm="ยืนยัน"><i class="bx bx-check-circle"></i>ยืนยันใบสั่งขาย</button>@endif @if($canCreatePhysicalSale && auth()->user()->hasPermission('pos.physical-sales.create'))<a class="btn btn-primary d-inline-flex align-items-center gap-1" href="{{ route('pos.physical-sales.create', ['sales_order_id' => $order->id]) }}"><i class="bx bx-receipt"></i>สร้าง HS/IV</a>@endif @if(in_array($order->status, ['DRAFT', 'CONFIRMED'], true) && auth()->user()->hasPermission('pos.sales-orders.cancel'))<button class="btn btn-outline-danger d-inline-flex align-items-center gap-1 js-order-action" data-url="{{ route('pos.sales-orders.cancel', $order) }}" data-title="ยกเลิกใบสั่งขาย?" data-confirm="ยกเลิก" data-reason="1"><i class="bx bx-x-circle"></i>ยกเลิก</button>@endif @if(auth()->user()->hasPermission('pos.sales-orders.print'))<a class="btn btn-app-soft d-inline-flex align-items-center gap-1" href="{{ route('pos.sales-orders.pdf', $order) }}" target="_blank" rel="noopener"><i class="bx bx-printer"></i>พิมพ์ PDF</a>@endif <a class="btn btn-outline-secondary d-inline-flex align-items-center gap-1" href="{{ $order->quotation ? route('pos.sales-quotations.show', $order->quotation) : ($order->rfq ? route('pos.sales-rfqs.show', $order->rfq) : ($order->sourceIntake ? route('pos.sales-intakes.show', $order->sourceIntake) : route('pos.sales-orders.index'))) }}"><i class="bx bx-arrow-back"></i>กลับเอกสารต้นทาง</a></div>
    </div>
    @include('Pos::partials.document-trail', ['flowDocuments' => $flowDocuments])
    @include('Pos::partials.sales-document-header', ['document' => $order, 'sourceIntake' => $flowDocuments['intake'] ?? null])
    @if($order->description)<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="text-secondary small">รายละเอียด</div><div>{{ $order->description }}</div></div></div>@endif
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">รายการสินค้า</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>สินค้า/รายละเอียด</th><th>หน่วย</th><th class="text-end">จำนวน</th><th class="text-end">ราคา</th><th class="text-end">ส่วนลด</th><th class="text-end">รวม</th></tr></thead><tbody>@forelse($order->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ data_get($line->item_snapshot, 'code') }} · {{ data_get($line->item_snapshot, 'name', $line->description) }}</td><td>{{ data_get($line->uom_snapshot, 'code', '—') }}</td><td class="text-end">{{ number_format((float) $line->quantity, 4) }}</td><td class="text-end">{{ number_format((float) $line->unit_price, 2) }}</td><td class="text-end">{{ number_format((float) $line->discount_amount, 2) }}</td><td class="text-end">{{ number_format((float) $line->line_total, 2) }}</td></tr>@empty<tr><td colspan="7" class="text-center text-secondary">ไม่มีรายการ</td></tr>@endforelse</tbody><tfoot><tr><th colspan="6" class="text-end">ยอดรวม</th><th class="text-end">{{ number_format((float) $order->total_amount, 2) }}</th></tr></tfoot></table></div>@include('Pos::partials.sales-tax-summary', ['document' => $order, 'sourceIntake' => $flowDocuments['intake'] ?? null])</div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $entry)<div class="border-bottom py-2"><span class="text-secondary small">{{ optional($entry->created_at)->format('d/m/Y H:i') }}</span> <strong>{{ ['pos.sales-order.created'=>'สร้างใบสั่งขาย','pos.sales-order.confirm'=>'ยืนยันใบสั่งขาย','pos.sales-order.cancel'=>'ยกเลิกใบสั่งขาย'][$entry->action] ?? $entry->action }}</strong> <span class="text-secondary">{{ $entry->user?->name }}</span></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection
@push('scripts')<script>$(function(){$(document).on('click','.js-order-action',function(){const button=$(this),cancel=button.data('reason')===1,options={icon:cancel?'warning':'question',title:button.data('title'),showCancelButton:true,confirmButtonText:button.data('confirm'),cancelButtonText:'กลับ'};if(cancel){options.input='textarea';options.inputLabel='เหตุผลการยกเลิก';options.inputPlaceholder='ระบุเหตุผลอย่างน้อย 10 ตัวอักษร';options.inputValidator=value=>value&&value.trim().length>=10?undefined:'กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร'}Swal.fire(options).then(result=>{if(!result.isConfirmed)return;button.prop('disabled',true);const data={_token:$('meta[name=csrf-token]').attr('content')};if(cancel)data.reason=result.value;$.post(button.data('url'),data).done(response=>Swal.fire({icon:'success',text:response.msg}).then(()=>location.reload())).fail(xhr=>{button.prop('disabled',false);Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ดำเนินการไม่สำเร็จ'})})})})});</script>@endpush
