@extends('Asset::layout')

@section('title', 'เปลี่ยนนโยบายค่าเสื่อม | New ERP')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / DEPRECIATION POLICY</p><h1 class="h3 mb-2">เปลี่ยนนโยบายค่าเสื่อมแบบกลุ่ม</h1><p class="text-secondary mb-0">กำหนดผลในอนาคตเท่านั้น โดยไม่แก้ไขค่าเสื่อมหรือรายการบัญชีที่ผ่านไปแล้ว</p></div><a class="btn btn-outline-dark" href="{{ route('asset.depreciation-policies.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>รายการคำขอ</a></div>
    <div class="alert alert-info border-0 shadow-sm d-flex gap-2 mb-4"><i class="bx bx-info-circle fs-5" aria-hidden="true"></i><div><strong>Prospective change</strong><div class="small mt-1">วันมีผลต้องเป็นวันแรกของงวดบัญชีเปิดในวันปัจจุบันหรืออนาคต ระบบจะเก็บ snapshot ก่อนอนุมัติทุกครั้ง</div></div></div>
    <form class="card border-0 shadow-sm" id="depreciation-policy-form" method="post" action="{{ route('asset.depreciation-policies.store') }}">@csrf
        <div class="card-body p-4"><div class="row g-3 mb-4"><div class="col-12 col-md-4"><label class="form-label" for="book_type">สมุดค่าเสื่อม <span class="text-danger">*</span></label><select class="form-select" id="book_type" name="book_type" required><option value="BOOK">บัญชี (Book)</option><option value="TAX">ภาษี (Tax)</option></select><div class="invalid-feedback" data-error-for="book_type"></div></div><div class="col-12 col-md-4"><label class="form-label" for="effective_date">วันมีผล <span class="text-danger">*</span></label><select class="form-select js-select2" id="effective_date" name="effective_date" required><option value="">เลือกวันเริ่มงวดบัญชี</option>@foreach($effectivePeriods as $period)<option value="{{ $period->start_date->toDateString() }}">{{ $period->name }} · เริ่ม {{ $period->start_date->format('d/m/Y') }} – {{ $period->end_date->format('d/m/Y') }}</option>@endforeach</select><div class="form-text">เลือกได้เฉพาะวันเริ่มงวดบัญชีที่ยังเปิดอยู่</div><div class="invalid-feedback" data-error-for="effective_date"></div></div><div class="col-12 col-md-4"><label class="form-label" for="method">วิธีคิดค่าเสื่อม <span class="text-danger">*</span></label><input class="form-control" id="method" value="เส้นตรง (Straight-line)" readonly><input type="hidden" name="method" value="STRAIGHT_LINE"></div><div class="col-12 col-md-6"><label class="form-label" for="useful_life_months">อายุใช้งานใหม่ (เดือน) <span class="text-danger">*</span></label><input class="form-control" id="useful_life_months" type="number" name="useful_life_months" min="1" max="1200" required><div class="invalid-feedback" data-error-for="useful_life_months"></div></div><div class="col-12 col-md-6"><label class="form-label" for="residual_value">มูลค่าคงเหลือใหม่ <span class="text-danger">*</span></label><input class="form-control" id="residual_value" type="number" name="residual_value" min="0" step="0.01" required><div class="invalid-feedback" data-error-for="residual_value"></div></div><div class="col-12"><label class="form-label" for="reason">เหตุผล <span class="text-danger">*</span></label><textarea class="form-control" id="reason" name="reason" autocomplete="off" minlength="10" maxlength="500" required></textarea><div class="form-text">อธิบายเหตุผลอย่างน้อย 10 ตัวอักษร</div><div class="invalid-feedback" data-error-for="reason"></div></div></div>
            <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2 mb-3"><div><h2 class="h5 mb-1">เลือกสินทรัพย์</h2><p class="small text-secondary mb-0">แสดงเฉพาะสินทรัพย์ ACTIVE ที่มี Book ตามประเภทที่เลือก <span id="selected-assets-count">เลือกแล้ว 0 รายการ</span></p></div><div class="form-check"><input class="form-check-input" id="select-all-assets" type="checkbox"><label class="form-check-label" for="select-all-assets">เลือกทั้งหมดในหน้านี้</label></div></div>
            <div class="table-responsive"><table class="table table-hover align-middle w-100" id="policy-assets-table" data-url="{{ route('asset.depreciation-policies.assets-data') }}"><thead><tr><th class="ps-3"><span class="visually-hidden">เลือก</span></th><th>สินทรัพย์</th><th>หมวด</th><th class="text-end pe-3">มูลค่าตามบัญชี</th></tr></thead></table></div><div class="invalid-feedback d-block d-none" data-error-for="asset_ids"></div>
        </div>
        <div class="card-footer bg-white border-0 p-4 pt-0 d-flex justify-content-end gap-2"><a class="btn btn-outline-dark" href="{{ route('asset.depreciation-policies.index') }}">ยกเลิก</a><button class="btn btn-dark" type="submit"><i class="bx bx-git-branch me-1" aria-hidden="true"></i>สร้างคำขอเปลี่ยนนโยบาย</button></div>
    </form>
</div>
@endsection

@push('scripts')
<script>
$(function(){
    var $form=$('#depreciation-policy-form'),$book=$('#book_type'),$all=$('#select-all-assets'),$count=$('#selected-assets-count'),selected={};
    var $table=$('#policy-assets-table'),text=$.fn.dataTable.render.text(),table=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(data){data.book_type=$book.val();}},order:[[1,'asc']],buttons:[window.erpExcelButton($table)],columns:[{data:'id',orderable:false,searchable:false,className:'ps-3',render:function(id,type,row){return type==='display'?'<input class="form-check-input js-policy-asset" type="checkbox" value="'+id+'" '+(selected[id]?'checked':'')+' aria-label="เลือก '+text.display(row.asset_number)+'">':'';}},{data:'asset_number',name:'asset_number',render:function(value,type,row){return type==='display'?'<div class="fw-semibold">'+text.display(value)+'</div><div class="small text-secondary">'+text.display(row.name)+'</div>':value;}},{data:'category_label',orderable:false,searchable:false,render:text.display},{data:'book_value',name:'book_value',className:'text-end pe-3',render:function(value,type){return type==='display'?Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):value;}}],drawCallback:function(){var rows=table.rows({page:'current'}).data(),allSelected=rows.length>0;$.each(rows,function(_,row){if(!selected[row.id])allSelected=false;});$all.prop('checked',allSelected);}}));
    function selectedCount(){$count.text('เลือกแล้ว '+Object.keys(selected).length+' รายการ');}
    $table.on('change','.js-policy-asset',function(){var id=$(this).val();if(this.checked)selected[id]=true;else delete selected[id];selectedCount();});
    $all.on('change',function(){table.rows({page:'current'}).data().each(function(row){if($all.prop('checked'))selected[row.id]=true;else delete selected[row.id];});table.draw(false);selectedCount();});
    $book.on('change',function(){selected={};selectedCount();table.ajax.reload();});selectedCount();
    $form.on('submit',function(e){e.preventDefault();$form.find('.js-selected-asset').remove();$.each(Object.keys(selected),function(_,id){$form.append($('<input>',{type:'hidden',name:'asset_ids[]',value:id,class:'js-selected-asset'}));});var $button=$form.find('[type="submit"]');$button.prop('disabled',true);$.ajax({url:$form.attr('action'),method:'POST',data:$form.serialize(),headers:{Accept:'application/json','X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')||''}}).done(function(response){Swal.fire({icon:'success',title:response.msg||'สร้างคำขอแล้ว'}).then(function(){window.location=response.redirect||@json(route('asset.depreciation-policies.index'));});}).fail(function(xhr){var body=xhr.responseJSON||{},errors=body.errors||{};$form.find('.is-invalid').removeClass('is-invalid');$.each(errors,function(field,messages){var $field=$form.find('[name="'+field+'"],[name="'+field+'[]"]').first();$field.addClass('is-invalid');$form.find('[data-error-for="'+field+'"]').removeClass('d-none').text(messages[0]);});Swal.fire({icon:'error',title:'ไม่สามารถสร้างคำขอได้',text:body.msg||body.message||'กรุณาตรวจสอบข้อมูล'});}).always(function(){$button.prop('disabled',false);});});
});
</script>
@endpush
