@extends('Asset::layout')

@section('title', 'ตรวจสอบคำขอเปลี่ยนนโยบายค่าเสื่อม | New ERP')

@section('content')
@php
    $requested = $change->profile_snapshot['requested_profile'] ?? [];
    $baseline = $change->profile_snapshot['approval_baseline']['book_profile'] ?? [];
    $book = $change->depreciationBook;
    $asset = $book->asset;
    $labels = ['DRAFT' => 'รออนุมัติ', 'APPROVED' => 'อนุมัติแล้ว', 'VOID' => 'ยกเลิก'];
    $classes = ['DRAFT' => 'app-badge-info', 'APPROVED' => 'app-badge-success', 'VOID' => 'app-status-danger'];
    $auditTrail = collect([
        ['สร้างคำขอ', $change->created_at, $change->createdBy?->name, null],
        ['อนุมัติ', $change->approved_at, $change->approvedBy?->name, null],
        ['ยกเลิก', $change->cancelled_at, $change->cancelledBy?->name, $change->cancellation_reason],
    ])->filter(fn ($event) => $event[1])->sortByDesc(fn ($event) => $event[1]);
@endphp
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-xl-row justify-content-between align-items-xl-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / DEPRECIATION POLICY</p><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><h1 class="h3 mb-0">{{ $asset->asset_number }}</h1><span class="badge {{ $classes[$change->status] ?? 'app-badge-soft' }}">{{ $labels[$change->status] ?? $change->status }}</span></div><p class="text-secondary mb-0">{{ $asset->name }} · {{ $book->book_type==='BOOK'?'บัญชี (Book)':'ภาษี (Tax)' }} · มีผล {{ $change->effective_date?->format('d/m/Y') }}</p></div><div class="d-flex flex-wrap gap-2">
        @if($change->status === 'DRAFT' && auth()->user()->hasPermission('asset.depreciation.approve'))
            <button class="btn btn-primary js-approve" type="button" data-url="{{ route('asset.depreciation-policies.approve') }}" data-id="{{ $change->id }}"><i class="bx bx-check me-1" aria-hidden="true"></i>อนุมัติคำขอ</button>
        @endif
        @if($change->status === 'DRAFT' && auth()->user()->hasPermission('asset.depreciation.calculate'))
            <button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#cancel-modal"><i class="bx bx-x-circle me-1" aria-hidden="true"></i>ยกเลิก</button>
        @endif
        <a class="btn btn-outline-dark" href="{{ route('asset.depreciation-policies.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>รายการคำขอ</a>
    </div></div>
    <div class="alert alert-info border-0 shadow-sm d-flex gap-2 mb-4"><i class="bx bx-info-circle fs-5" aria-hidden="true"></i><div>การเปลี่ยนนี้เป็นแบบ prospective: จะมีผลตั้งแต่วันเริ่มงวดที่ระบุ และไม่แก้ไขประวัติค่าเสื่อมหรือ Journal เดิม</div></div>
    <div class="row g-4"><div class="col-12 col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white border-0 py-3 px-3 px-lg-4"><h2 class="h5 mb-1">ค่าเดิม (Baseline)</h2><p class="small text-secondary mb-0">สถานะ Book ณ จุดตรวจสอบ{{ $baseline?' ก่อนวันมีผล':' ปัจจุบันก่อนอนุมัติ' }}</p></div><div class="card-body p-3 p-lg-4"><dl class="row mb-0"><dt class="col-sm-6 text-secondary">วิธีคิด</dt><dd class="col-sm-6">{{ ($baseline['method'] ?? $book->method)==='STRAIGHT_LINE'?'เส้นตรง':'-' }}</dd><dt class="col-sm-6 text-secondary">อายุใช้งาน</dt><dd class="col-sm-6">{{ number_format($baseline['useful_life_months'] ?? $book->useful_life_months) }} เดือน</dd><dt class="col-sm-6 text-secondary">มูลค่าคงเหลือ</dt><dd class="col-sm-6">{{ number_format((float) ($baseline['residual_value'] ?? $book->residual_value),2) }}</dd><dt class="col-sm-6 text-secondary">ค่าเสื่อมสะสม</dt><dd class="col-sm-6">{{ number_format((float) ($change->profile_snapshot['approval_baseline']['accumulated_depreciation'] ?? $book->accumulated_depreciation),2) }}</dd><dt class="col-sm-6 text-secondary">มูลค่าตามบัญชี</dt><dd class="col-sm-6">{{ number_format((float) ($change->profile_snapshot['approval_baseline']['remaining_book_value'] ?? $asset->book_value),2) }}</dd></dl></div></div></div><div class="col-12 col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white border-0 py-3 px-3 px-lg-4"><h2 class="h5 mb-1">ค่าที่ขอเปลี่ยน</h2><p class="small text-secondary mb-0">จะเริ่มใช้ตั้งแต่ {{ $change->effective_date?->format('d/m/Y') }}</p></div><div class="card-body p-3 p-lg-4"><dl class="row mb-0"><dt class="col-sm-6 text-secondary">วิธีคิด</dt><dd class="col-sm-6">{{ ($requested['method'] ?? null)==='STRAIGHT_LINE'?'เส้นตรง':'-' }}</dd><dt class="col-sm-6 text-secondary">อายุใช้งานใหม่</dt><dd class="col-sm-6">{{ number_format((int) ($requested['useful_life_months'] ?? 0)) }} เดือน</dd><dt class="col-sm-6 text-secondary">มูลค่าคงเหลือใหม่</dt><dd class="col-sm-6">{{ number_format((float) ($requested['residual_value'] ?? 0),2) }}</dd><dt class="col-sm-6 text-secondary">เหตุผล</dt><dd class="col-sm-6">{{ $change->reason }}</dd></dl></div></div></div></div>
    <div class="card border-0 shadow-sm mt-4"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-12 col-md-4"><div class="small text-secondary">ผู้สร้างคำขอ</div><div class="fw-semibold">{{ $change->createdBy?->name ?? '-' }}</div><div class="small text-secondary">{{ $change->created_at?->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</div></div><div class="col-12 col-md-4"><div class="small text-secondary">ผู้อนุมัติ</div><div class="fw-semibold">{{ $change->approvedBy?->name ?? 'รออนุมัติ' }}</div><div class="small text-secondary">{{ $change->approved_at?->timezone('Asia/Bangkok')->format('d/m/Y H:i') ?? '-' }}</div></div><div class="col-12 col-md-4"><div class="small text-secondary">หมวดสินทรัพย์</div><div class="fw-semibold">{{ $asset->category?->name ?? '-' }}</div></div></div>@if($change->cancelled_at)<hr><div class="alert alert-danger mb-0 py-2"><div class="fw-semibold">ยกเลิกคำขอแล้ว</div><div class="small">{{ $change->cancelled_at->timezone('Asia/Bangkok')->format('d/m/Y H:i') }} · {{ $change->cancelledBy?->name ?? '-' }} · {{ $change->cancellation_reason }}</div></div>@endif</div></div>
    <div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white border-0 py-3 px-3 px-lg-4"><h2 class="h5 mb-1">ประวัติการทำรายการ</h2><p class="small text-secondary mb-0">Audit Trail ของคำขอเปลี่ยนนโยบายนี้ · เวลาไทย (UTC+7)</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-3 ps-lg-4">วันเวลา</th><th>เหตุการณ์</th><th>ผู้ดำเนินการ</th><th class="pe-3 pe-lg-4">หมายเหตุ</th></tr></thead><tbody>@foreach($auditTrail as [$action,$occurredAt,$actor,$note])<tr><td class="ps-3 ps-lg-4 text-nowrap">{{ $occurredAt->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</td><td class="fw-semibold">{{ $action }}</td><td>{{ $actor ?? '-' }}</td><td class="pe-3 pe-lg-4">{{ $note ?? '-' }}</td></tr>@endforeach</tbody></table></div></div>
</div>
<div class="modal fade" id="cancel-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form class="modal-content" id="cancel-form" method="post" action="{{ route('asset.depreciation-policies.cancel', $change) }}">@csrf<div class="modal-header"><h2 class="modal-title h5">ยกเลิกคำขอเปลี่ยนนโยบาย</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body"><p class="text-secondary small">คำขอนี้ยังไม่อนุมัติ จึงยกเลิกได้โดยไม่กระทบค่าเสื่อมหรือรายการบัญชี</p><label class="form-label" for="cancellation_reason">เหตุผล <span class="text-danger">*</span></label><textarea class="form-control" id="cancellation_reason" name="cancellation_reason" minlength="10" maxlength="500" required></textarea><div class="invalid-feedback" data-error-for="cancellation_reason"></div></div><div class="modal-footer"><button class="btn btn-outline-dark" type="button" data-bs-dismiss="modal">กลับ</button><button class="btn btn-danger" type="submit">ยืนยันยกเลิก</button></div></form></div></div>
@endsection

@push('scripts')
<script>
$(function(){$('.js-approve').on('click',function(){var $button=$(this);Swal.fire({icon:'warning',title:'อนุมัติการเปลี่ยนนโยบาย?',text:'คำขอนี้จะมีผลในอนาคตตามวันที่ระบุ',showCancelButton:true,confirmButtonText:'อนุมัติ',cancelButtonText:'ยกเลิก'}).then(function(result){if(!result.isConfirmed)return;$button.prop('disabled',true);$.ajax({url:$button.data('url'),method:'POST',data:{policy_change_ids:[$button.data('id')]},headers:{Accept:'application/json','X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')||''}}).done(function(response){Swal.fire({icon:'success',title:response.msg}).then(function(){window.location.reload();});}).fail(function(xhr){var body=xhr.responseJSON||{};Swal.fire({icon:'error',title:'ไม่สามารถอนุมัติได้',text:body.msg||body.message||'กรุณาลองใหม่'});}).always(function(){$button.prop('disabled',false);});});});window.erpAjaxForm({form:'#cancel-form',redirect:true,reload:false});});
</script>
@endpush
