<?php

use App\Modules\Wms\Controllers\EntryController;
use App\Modules\Wms\Controllers\InventoryAdjustmentController;
use App\Modules\Wms\Controllers\IssueReturnController;
use App\Modules\Wms\Controllers\ItemCategoryController;
use App\Modules\Wms\Controllers\ItemController;
use App\Modules\Wms\Controllers\LegacyAllocationReviewController;
use App\Modules\Wms\Controllers\PurchaseDocumentController;
use App\Modules\Wms\Controllers\PurchaseDocumentPdfController;
use App\Modules\Wms\Controllers\PurchaseOrderController;
use App\Modules\Wms\Controllers\PurchaseReceiptController;
use App\Modules\Wms\Controllers\PurchaseRequisitionController;
use App\Modules\Wms\Controllers\StockController;
use App\Modules\Wms\Controllers\StockCountController;
use App\Modules\Wms\Controllers\StockPolicyController;
use App\Modules\Wms\Controllers\StockValuationController;
use App\Modules\Wms\Controllers\SupplierController;
use App\Modules\Wms\Controllers\TransferController;
use App\Modules\Wms\Controllers\UomController;
use App\Modules\Wms\Controllers\WorkflowController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'program:wms', 'warehouse'])->prefix('wms')->name('wms.')->group(function () {
    Route::get('/', EntryController::class)->middleware('permission:wms.dashboard.view')->name('index');
    Route::get('/workflow', [WorkflowController::class, 'index'])->name('workflow.index');
    Route::get('/stock', [StockController::class, 'index'])->middleware('permission:wms.stock.view')->name('stock.index');
    Route::get('/issues', [IssueReturnController::class, 'issuesIndex'])->middleware('permission:wms.issues.view')->name('issues.index');
    Route::get('/issues/data', [IssueReturnController::class, 'issuesData'])->middleware('permission:wms.issues.view')->name('issues.data');
    Route::get('/issues/item-options', [IssueReturnController::class, 'itemOptions'])->middleware('permission:wms.issues.create')->name('issues.item-options');
    Route::get('/issues/create', [IssueReturnController::class, 'issueCreate'])->middleware('permission:wms.issues.create')->name('issues.create');
    Route::post('/issues', [IssueReturnController::class, 'issueStore'])->middleware('permission:wms.issues.create')->name('issues.store');
    Route::get('/issues/{document}', [IssueReturnController::class, 'issueShow'])->middleware('permission:wms.issues.view')->name('issues.show');
    Route::post('/issues/{document}/approve', [IssueReturnController::class, 'issueApprove'])->middleware('permission:wms.issues.approve')->name('issues.approve');
    Route::post('/issues/{document}/post', [IssueReturnController::class, 'issuePost'])->middleware('permission:wms.issues.post')->name('issues.post');
    Route::delete('/issues/{document}', [IssueReturnController::class, 'issueDelete'])->middleware('permission:wms.issues.delete')->name('issues.destroy');
    Route::get('/issue-returns', [IssueReturnController::class, 'returnsIndex'])->middleware('permission:wms.issue-returns.view')->name('issue-returns.index');
    Route::get('/issue-returns/data', [IssueReturnController::class, 'returnsData'])->middleware('permission:wms.issue-returns.view')->name('issue-returns.data');
    Route::get('/issue-returns/issue-options', [IssueReturnController::class, 'issueOptions'])->middleware('permission:wms.issue-returns.create')->name('issue-returns.issue-options');
    Route::get('/issue-returns/issue-line-options', [IssueReturnController::class, 'issueLineOptions'])->middleware('permission:wms.issue-returns.create')->name('issue-returns.issue-line-options');
    Route::get('/issue-returns/create', [IssueReturnController::class, 'returnCreate'])->middleware('permission:wms.issue-returns.create')->name('issue-returns.create');
    Route::post('/issue-returns', [IssueReturnController::class, 'returnStore'])->middleware('permission:wms.issue-returns.create')->name('issue-returns.store');
    Route::get('/issue-returns/{document}', [IssueReturnController::class, 'returnShow'])->middleware('permission:wms.issue-returns.view')->name('issue-returns.show');
    Route::post('/issue-returns/{document}/approve', [IssueReturnController::class, 'returnApprove'])->middleware('permission:wms.issue-returns.approve')->name('issue-returns.approve');
    Route::post('/issue-returns/{document}/post', [IssueReturnController::class, 'returnPost'])->middleware('permission:wms.issue-returns.post')->name('issue-returns.post');
    Route::delete('/issue-returns/{document}', [IssueReturnController::class, 'returnDelete'])->middleware('permission:wms.issue-returns.delete')->name('issue-returns.destroy');
    Route::get('/stock-policies', [StockPolicyController::class, 'policies'])->middleware('permission:wms.stock-policies.view')->name('stock-policies.index');
    Route::get('/stock-policies/data', [StockPolicyController::class, 'policyData'])->middleware('permission:wms.stock-policies.view')->name('stock-policies.data');
    Route::get('/stock-policies/item-options', [StockPolicyController::class, 'itemOptions'])->middleware('permission:wms.stock-policies.view')->name('stock-policies.item-options');
    Route::get('/stock-policies/create', [StockPolicyController::class, 'policyCreate'])->middleware('permission:wms.stock-policies.create')->name('stock-policies.create');
    Route::post('/stock-policies', [StockPolicyController::class, 'policyStore'])->middleware('permission:wms.stock-policies.create')->name('stock-policies.store');
    Route::get('/stock-policies/{policy}/edit', [StockPolicyController::class, 'policyEdit'])->middleware('permission:wms.stock-policies.update')->name('stock-policies.edit');
    Route::put('/stock-policies/{policy}', [StockPolicyController::class, 'policyUpdate'])->middleware('permission:wms.stock-policies.update')->name('stock-policies.update');
    Route::delete('/stock-policies/{policy}', [StockPolicyController::class, 'policyDestroy'])->middleware('permission:wms.stock-policies.delete')->name('stock-policies.destroy');
    Route::get('/issue-types', [StockPolicyController::class, 'issueTypes'])->middleware('permission:wms.issue-types.view')->name('issue-types.index');
    Route::get('/issue-types/data', [StockPolicyController::class, 'issueTypeData'])->middleware('permission:wms.issue-types.view')->name('issue-types.data');
    Route::get('/issue-types/create', [StockPolicyController::class, 'issueTypeCreate'])->middleware('permission:wms.issue-types.create')->name('issue-types.create');
    Route::post('/issue-types', [StockPolicyController::class, 'issueTypeStore'])->middleware('permission:wms.issue-types.create')->name('issue-types.store');
    Route::get('/issue-types/{issueType}/edit', [StockPolicyController::class, 'issueTypeEdit'])->middleware('permission:wms.issue-types.update')->name('issue-types.edit');
    Route::put('/issue-types/{issueType}', [StockPolicyController::class, 'issueTypeUpdate'])->middleware('permission:wms.issue-types.update')->name('issue-types.update');
    Route::delete('/issue-types/{issueType}', [StockPolicyController::class, 'issueTypeDestroy'])->middleware('permission:wms.issue-types.delete')->name('issue-types.destroy');
    Route::get('/inventory-adjustments', [InventoryAdjustmentController::class, 'index'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.index');
    Route::get('/stock-counts', [StockCountController::class, 'index'])->middleware('permission:wms.stock-counts.view')->name('stock-counts.index');
    Route::get('/stock-counts/data', [StockCountController::class, 'data'])->middleware('permission:wms.stock-counts.view')->name('stock-counts.data');
    Route::get('/stock-counts/item-options', [StockCountController::class, 'itemOptions'])->middleware('permission:wms.stock-counts.view')->name('stock-counts.item-options');
    Route::get('/stock-counts/create', [StockCountController::class, 'create'])->middleware('permission:wms.stock-counts.create')->name('stock-counts.create');
    Route::post('/stock-counts', [StockCountController::class, 'store'])->middleware('permission:wms.stock-counts.create')->name('stock-counts.store');
    Route::get('/stock-counts/{document}/edit', [StockCountController::class, 'edit'])->middleware('permission:wms.stock-counts.update')->name('stock-counts.edit');
    Route::put('/stock-counts/{document}', [StockCountController::class, 'update'])->middleware('permission:wms.stock-counts.update')->name('stock-counts.update');
    Route::get('/stock-counts/{document}', [StockCountController::class, 'show'])->middleware('permission:wms.stock-counts.view')->name('stock-counts.show');
    Route::post('/stock-counts/{document}/approve', [StockCountController::class, 'approve'])->middleware('permission:wms.stock-counts.approve')->name('stock-counts.approve');
    Route::delete('/stock-counts/{document}', [StockCountController::class, 'destroy'])->middleware('permission:wms.stock-counts.delete')->name('stock-counts.destroy');
    Route::get('/inventory-adjustments/data', [InventoryAdjustmentController::class, 'data'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.data');
    Route::get('/inventory-adjustments/item-options', [InventoryAdjustmentController::class, 'itemOptions'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.item-options');
    Route::get('/inventory-adjustments/create', [InventoryAdjustmentController::class, 'create'])->middleware('permission:wms.inventory-adjustments.create')->name('inventory-adjustments.create');
    Route::post('/inventory-adjustments', [InventoryAdjustmentController::class, 'storeDocument'])->middleware('permission:wms.inventory-adjustments.create')->name('inventory-adjustments.store');
    Route::get('/inventory-adjustments/documents/{document}', [InventoryAdjustmentController::class, 'showDocument'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.documents.show');
    Route::get('/inventory-adjustments/documents/{document}/edit', [InventoryAdjustmentController::class, 'editDocument'])->middleware('permission:wms.inventory-adjustments.update')->name('inventory-adjustments.documents.edit');
    Route::put('/inventory-adjustments/documents/{document}', [InventoryAdjustmentController::class, 'updateDocument'])->middleware('permission:wms.inventory-adjustments.update')->name('inventory-adjustments.documents.update');
    Route::delete('/inventory-adjustments/documents/{document}', [InventoryAdjustmentController::class, 'deleteDocument'])->middleware('permission:wms.inventory-adjustments.delete')->name('inventory-adjustments.documents.delete');
    Route::post('/inventory-adjustments/documents/{document}/approve', [InventoryAdjustmentController::class, 'approveDocument'])->middleware('permission:wms.inventory-adjustments.approve')->name('inventory-adjustments.documents.approve');
    Route::post('/inventory-adjustments/documents/{document}/post', [InventoryAdjustmentController::class, 'postDocument'])->middleware('permission:wms.inventory-adjustments.post')->name('inventory-adjustments.documents.post');
    Route::post('/inventory-adjustments/documents/{document}/reverse', [InventoryAdjustmentController::class, 'reverseDocument'])->middleware('permission:wms.inventory-adjustments.reverse')->name('inventory-adjustments.documents.reverse');
    Route::get('/inventory-adjustments/{adjustment}', [InventoryAdjustmentController::class, 'show'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.show');
    Route::post('/inventory-adjustments/{adjustment}/approve', [InventoryAdjustmentController::class, 'approve'])->middleware('permission:wms.inventory-adjustments.approve')->name('inventory-adjustments.approve');
    Route::post('/inventory-adjustments/{adjustment}/post', [InventoryAdjustmentController::class, 'post'])->middleware('permission:wms.inventory-adjustments.post')->name('inventory-adjustments.post');
    Route::post('/inventory-adjustments/{adjustment}/reverse', [InventoryAdjustmentController::class, 'reverse'])->middleware('permission:wms.inventory-adjustments.reverse')->name('inventory-adjustments.reverse');
    Route::delete('/inventory-adjustments/{adjustment}', [InventoryAdjustmentController::class, 'destroy'])->middleware('permission:wms.inventory-adjustments.delete')->name('inventory-adjustments.destroy');
    Route::get('/stock/summary', [StockController::class, 'summary'])->middleware('permission:wms.stock.view')->name('stock.summary');
    Route::get('/stock/data', [StockController::class, 'data'])->middleware('permission:wms.stock.view')->name('stock.data');
    Route::get('/stock/item-options', [StockController::class, 'itemOptions'])->middleware('permission:wms.stock.view')->name('stock.item-options');
    Route::get('/stock/{item}', [StockController::class, 'show'])->middleware('permission:wms.stock.view')->name('stock.show');
    Route::get('/transfers/outgoing', [TransferController::class, 'index'])->defaults('direction', 'out')->middleware('permission:wms.transfers.view')->name('transfers.outgoing.index');
    Route::get('/transfers/outgoing/data', [TransferController::class, 'data'])->defaults('direction', 'out')->middleware('permission:wms.transfers.view')->name('transfers.outgoing.data');
    Route::get('/transfers/incoming', [TransferController::class, 'index'])->defaults('direction', 'in')->middleware('permission:wms.transfers.view')->name('transfers.incoming.index');
    Route::get('/transfers/incoming/data', [TransferController::class, 'data'])->defaults('direction', 'in')->middleware('permission:wms.transfers.view')->name('transfers.incoming.data');
    Route::get('/transfers', [TransferController::class, 'index'])->defaults('direction', 'all')->middleware('permission:wms.transfers.view')->name('transfers.index');
    Route::get('/transfers/data', [TransferController::class, 'data'])->defaults('direction', 'all')->middleware('permission:wms.transfers.view')->name('transfers.data');
    Route::get('/transfers/{transfer}', [TransferController::class, 'show'])->middleware('permission:wms.transfers.view')->name('transfers.show');
    Route::get('/transfers/{transfer}/receive', [TransferController::class, 'receive'])->middleware('permission:wms.transfers.complete')->name('transfers.receive');
    Route::get('/transfers/{transfer}/lines', [TransferController::class, 'lines'])->middleware('permission:wms.transfers.view')->name('transfers.lines');
    Route::get('/transfers/create', [TransferController::class, 'create'])->middleware('permission:wms.transfers.create')->name('transfers.create');
    Route::post('/transfers', [TransferController::class, 'store'])->middleware('permission:wms.transfers.create')->name('transfers.store');
    Route::post('/transfers/{transfer}/dispatch', [TransferController::class, 'dispatch'])->middleware('permission:wms.transfers.dispatch')->name('transfers.dispatch');
    Route::post('/transfers/{transfer}/complete', [TransferController::class, 'complete'])->middleware('permission:wms.transfers.complete')->name('transfers.complete');
    Route::post('/transfers/{transfer}/void', [TransferController::class, 'void'])->middleware('permission:wms.transfers.void')->name('transfers.void');
    Route::get('/stock-valuation', [StockValuationController::class, 'index'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.index');
    Route::get('/stock-valuation/item/{item}', [StockValuationController::class, 'show'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.show');
    Route::get('/stock-valuation/item/{item}/layers', [StockValuationController::class, 'layersData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.layers');
    Route::get('/stock-valuation/data', [StockValuationController::class, 'data'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.data');
    Route::get('/stock-valuation/historical-data', [StockValuationController::class, 'historicalData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.historical-data');
    Route::get('/stock-valuation/historical-reconciliation-data', [StockValuationController::class, 'historicalReconciliationData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.historical-reconciliation-data');
    Route::get('/stock-valuation/preflight-summary', [StockValuationController::class, 'preflightSummary'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.preflight-summary');
    Route::get('/stock-valuation/recost-health', [StockValuationController::class, 'recostHealth'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.recost-health');
    Route::get('/legacy-allocation-reviews', [LegacyAllocationReviewController::class, 'index'])->middleware('permission:wms.cost-allocation-reviews.view')->name('legacy-allocation-reviews.index');
    Route::get('/legacy-allocation-reviews/data', [LegacyAllocationReviewController::class, 'data'])->middleware('permission:wms.cost-allocation-reviews.view')->name('legacy-allocation-reviews.data');
    Route::get('/legacy-allocation-reviews/{review}', [LegacyAllocationReviewController::class, 'show'])->middleware('permission:wms.cost-allocation-reviews.view')->name('legacy-allocation-reviews.show');
    Route::post('/stock-valuation/recost-retry', [StockValuationController::class, 'retryRecost'])->middleware('permission:wms.recost.retry')->name('stock-valuation.recost-retry');

    // Transitional compatibility aliases. Canonical Purchasing routes live in
    // App\Modules\Purchasing\Routes\web.php; remove these only after the
    // existing WMS-linked views and bookmarks are migrated flow by flow.
    Route::get('/purchase-documents', [PurchaseDocumentController::class, 'index'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.index');
    Route::get('/purchase-orders', [PurchaseOrderController::class, 'index'])->middleware('permission:wms.purchase-orders.view')->name('purchase-orders.index');
    Route::get('/purchase-orders/data', [PurchaseOrderController::class, 'data'])->middleware('permission:wms.purchase-orders.view')->name('purchase-orders.data');
    Route::get('/purchase-orders/create', [PurchaseOrderController::class, 'create'])->middleware('permission:wms.purchase-orders.create')->name('purchase-orders.create');
    Route::post('/purchase-orders', [PurchaseOrderController::class, 'store'])->middleware('permission:wms.purchase-orders.create')->name('purchase-orders.store');
    Route::get('/purchase-orders/{purchaseOrder}', [PurchaseOrderController::class, 'show'])->middleware('permission:wms.purchase-orders.view')->name('purchase-orders.show');
    Route::get('/purchase-orders/{purchaseOrder}/pdf', [PurchaseDocumentPdfController::class, 'order'])->middleware('permission:wms.purchase-orders.print')->name('purchase-orders.pdf');
    Route::get('/purchase-orders/{purchaseOrder}/edit', [PurchaseOrderController::class, 'edit'])->middleware('permission:wms.purchase-orders.update')->name('purchase-orders.edit');
    Route::put('/purchase-orders/{purchaseOrder}', [PurchaseOrderController::class, 'update'])->middleware('permission:wms.purchase-orders.update')->name('purchase-orders.update');
    Route::delete('/purchase-orders/{purchaseOrder}', [PurchaseOrderController::class, 'destroy'])->middleware('permission:wms.purchase-orders.delete')->name('purchase-orders.destroy');
    Route::post('/purchase-orders/{purchaseOrder}/approve', [PurchaseOrderController::class, 'approve'])->middleware('permission:wms.purchase-orders.approve')->name('purchase-orders.approve');
    Route::post('/purchase-orders/{purchaseOrder}/void', [PurchaseOrderController::class, 'void'])->middleware('permission:wms.purchase-orders.void')->name('purchase-orders.void');
    Route::get('/purchase-documents/data', [PurchaseDocumentController::class, 'data'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.data');
    Route::get('/purchase-documents/supplier-options', [PurchaseDocumentController::class, 'supplierOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.supplier-options');
    Route::get('/purchase-documents/account-options', [PurchaseDocumentController::class, 'accountOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.account-options');
    Route::get('/purchase-documents/item-options', [PurchaseDocumentController::class, 'itemOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.item-options');
    Route::get('/purchase-documents/uom-options', [PurchaseDocumentController::class, 'uomOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.uom-options');
    Route::get('/purchase-documents/tax-code-options', [PurchaseDocumentController::class, 'taxCodeOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.tax-code-options');
    Route::get('/purchase-documents/withholding-tax-code-options', [PurchaseDocumentController::class, 'withholdingTaxCodeOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.withholding-tax-code-options');
    Route::get('/purchase-documents/original-options', [PurchaseDocumentController::class, 'originalOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.original-options');
    Route::get('/purchase-documents/purchase-order-line-options', [PurchaseDocumentController::class, 'purchaseOrderLineOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.purchase-order-line-options');
    Route::get('/purchase-documents/goods-receipt-line-options', [PurchaseDocumentController::class, 'goodsReceiptLineOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.goods-receipt-line-options');
    Route::get('/purchase-documents/goods-receipt-options', [PurchaseDocumentController::class, 'goodsReceiptOptions'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.goods-receipt-options');
    Route::get('/purchase-documents/goods-receipt-lines', [PurchaseDocumentController::class, 'goodsReceiptLines'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.goods-receipt-lines');
    Route::get('/purchase-documents/create', [PurchaseDocumentController::class, 'create'])->middleware('permission:wms.purchase-documents.create')->name('purchase-documents.create');
    Route::post('/purchase-documents', [PurchaseDocumentController::class, 'store'])->middleware('permission:wms.purchase-documents.create')->name('purchase-documents.store');
    Route::get('/purchase-documents/{purchaseDocument}', [PurchaseDocumentController::class, 'show'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.show');
    Route::get('/purchase-documents/{purchaseDocument}/pdf', [PurchaseDocumentPdfController::class, 'purchase'])->middleware('permission:wms.purchase-documents.print')->name('purchase-documents.pdf');
    Route::get('/purchase-documents/{purchaseDocument}/three-way-match', [PurchaseDocumentController::class, 'threeWayMatch'])->middleware('permission:wms.purchase-documents.view')->name('purchase-documents.three-way-match');
    Route::get('/purchase-documents/{purchaseDocument}/edit', [PurchaseDocumentController::class, 'edit'])->middleware('permission:wms.purchase-documents.update')->name('purchase-documents.edit');
    Route::put('/purchase-documents/{purchaseDocument}', [PurchaseDocumentController::class, 'update'])->middleware('permission:wms.purchase-documents.update')->name('purchase-documents.update');
    Route::delete('/purchase-documents/{purchaseDocument}', [PurchaseDocumentController::class, 'destroy'])->middleware('permission:wms.purchase-documents.delete')->name('purchase-documents.destroy');
    Route::post('/purchase-documents/{purchaseDocument}/approve', [PurchaseDocumentController::class, 'approve'])->middleware('permission:wms.purchase-documents.approve')->name('purchase-documents.approve');
    Route::post('/purchase-documents/{purchaseDocument}/variance-approve', [PurchaseDocumentController::class, 'varianceApprove'])->middleware('permission:wms.purchase-documents.approve')->name('purchase-documents.variance-approve');
    Route::post('/purchase-documents/{purchaseDocument}/variance-reject', [PurchaseDocumentController::class, 'varianceReject'])->middleware('permission:wms.purchase-documents.approve')->name('purchase-documents.variance-reject');
    Route::post('/purchase-documents/{purchaseDocument}/variance-recover', [PurchaseDocumentController::class, 'varianceRecover'])->middleware('permission:wms.purchase-documents.update')->name('purchase-documents.variance-recover');
    Route::post('/purchase-documents/{purchaseDocument}/post', [PurchaseDocumentController::class, 'post'])->middleware('permission:wms.purchase-documents.post')->name('purchase-documents.post');
    Route::post('/purchase-documents/{purchaseDocument}/inventory-post', [PurchaseDocumentController::class, 'inventoryPost'])->middleware('permission:wms.purchase-documents.inventory-post')->name('purchase-documents.inventory-post');
    Route::post('/purchase-documents/{purchaseDocument}/inventory-reverse', [PurchaseDocumentController::class, 'inventoryReverse'])->middleware('permission:wms.purchase-documents.inventory-reverse')->name('purchase-documents.inventory-reverse');
    Route::post('/purchase-documents/{purchaseDocument}/credit-inventory-reverse', [PurchaseDocumentController::class, 'creditInventoryReverse'])->middleware('permission:wms.purchase-documents.inventory-reverse')->name('purchase-documents.credit-inventory-reverse');
    Route::post('/purchase-documents/{purchaseDocument}/void', [PurchaseDocumentController::class, 'void'])->middleware('permission:wms.purchase-documents.void')->name('purchase-documents.void');
    Route::get('/purchase-requisitions', [PurchaseRequisitionController::class, 'index'])->middleware('permission:wms.purchase-requisitions.view')->name('purchase-requisitions.index');
    Route::get('/purchase-requisitions/data', [PurchaseRequisitionController::class, 'data'])->middleware('permission:wms.purchase-requisitions.view')->name('purchase-requisitions.data');
    Route::get('/purchase-requisitions/supplier-options', [PurchaseRequisitionController::class, 'supplierOptions'])->middleware('permission:wms.purchase-requisitions.view')->name('purchase-requisitions.supplier-options');
    Route::get('/purchase-requisitions/item-options', [PurchaseRequisitionController::class, 'itemOptions'])->middleware('permission:wms.purchase-requisitions.view')->name('purchase-requisitions.item-options');
    Route::get('/purchase-requisitions/uom-options', [PurchaseRequisitionController::class, 'uomOptions'])->middleware('permission:wms.purchase-requisitions.view')->name('purchase-requisitions.uom-options');
    Route::get('/purchase-requisitions/create', [PurchaseRequisitionController::class, 'create'])->middleware('permission:wms.purchase-requisitions.create')->name('purchase-requisitions.create');
    Route::post('/purchase-requisitions', [PurchaseRequisitionController::class, 'store'])->middleware('permission:wms.purchase-requisitions.create')->name('purchase-requisitions.store');
    Route::get('/purchase-requisitions/{purchaseRequisition}/edit', [PurchaseRequisitionController::class, 'edit'])->middleware('permission:wms.purchase-requisitions.update')->name('purchase-requisitions.edit');
    Route::get('/purchase-requisitions/{purchaseRequisition}/pdf', [PurchaseDocumentPdfController::class, 'requisition'])->middleware('permission:wms.purchase-requisitions.print')->name('purchase-requisitions.pdf');
    Route::put('/purchase-requisitions/{purchaseRequisition}', [PurchaseRequisitionController::class, 'update'])->middleware('permission:wms.purchase-requisitions.update')->name('purchase-requisitions.update');
    Route::delete('/purchase-requisitions/{purchaseRequisition}', [PurchaseRequisitionController::class, 'destroy'])->middleware('permission:wms.purchase-requisitions.delete')->name('purchase-requisitions.destroy');
    Route::post('/purchase-requisitions/{purchaseRequisition}/submit', [PurchaseRequisitionController::class, 'submit'])->middleware('permission:wms.purchase-requisitions.submit')->name('purchase-requisitions.submit');
    Route::post('/purchase-requisitions/{purchaseRequisition}/approve', [PurchaseRequisitionController::class, 'approve'])->middleware('permission:wms.purchase-requisitions.approve')->name('purchase-requisitions.approve');
    Route::post('/purchase-requisitions/{purchaseRequisition}/reject', [PurchaseRequisitionController::class, 'reject'])->middleware('permission:wms.purchase-requisitions.reject')->name('purchase-requisitions.reject');
    Route::post('/purchase-requisitions/{purchaseRequisition}/void', [PurchaseRequisitionController::class, 'void'])->middleware('permission:wms.purchase-requisitions.void')->name('purchase-requisitions.void');
    Route::post('/purchase-requisitions/{purchaseRequisition}/create-po', [PurchaseRequisitionController::class, 'createPurchaseOrder'])->middleware('permission:wms.purchase-requisitions.create-po')->name('purchase-requisitions.create-po');
    Route::get('/purchase-receipts', [PurchaseReceiptController::class, 'index'])->middleware('permission:wms.purchase-receipts.view')->name('purchase-receipts.index');
    Route::get('/purchase-receipts/data', [PurchaseReceiptController::class, 'data'])->middleware('permission:wms.purchase-receipts.view')->name('purchase-receipts.data');
    Route::get('/purchase-receipts/supplier-options', [PurchaseReceiptController::class, 'supplierOptions'])->middleware('permission:wms.purchase-receipts.view')->name('purchase-receipts.supplier-options');
    Route::get('/purchase-receipts/create', [PurchaseReceiptController::class, 'create'])->middleware('permission:wms.purchase-receipts.create')->name('purchase-receipts.create');
    Route::get('/purchase-receipts/{purchaseReceipt}/edit', [PurchaseReceiptController::class, 'edit'])->middleware('permission:wms.purchase-receipts.update')->name('purchase-receipts.edit');
    Route::get('/purchase-receipts/{purchaseReceipt}/pdf', [PurchaseDocumentPdfController::class, 'receipt'])->middleware('permission:wms.purchase-receipts.print')->name('purchase-receipts.pdf');
    Route::get('/purchase-receipts/purchase-options', [PurchaseReceiptController::class, 'purchaseOptions'])->middleware('permission:wms.purchase-receipts.create')->name('purchase-receipts.purchase-options');
    Route::get('/purchase-receipts/line-options', [PurchaseReceiptController::class, 'lineOptions'])->middleware('permission:wms.purchase-receipts.create')->name('purchase-receipts.line-options');
    Route::post('/purchase-receipts', [PurchaseReceiptController::class, 'store'])->middleware('permission:wms.purchase-receipts.create')->name('purchase-receipts.store');
    Route::put('/purchase-receipts/{purchaseReceipt}', [PurchaseReceiptController::class, 'update'])->middleware('permission:wms.purchase-receipts.update')->name('purchase-receipts.update');
    Route::post('/purchase-receipts/{purchaseReceipt}/approve', [PurchaseReceiptController::class, 'approve'])->middleware('permission:wms.purchase-receipts.approve')->name('purchase-receipts.approve');
    Route::post('/purchase-receipts/{purchaseReceipt}/void', [PurchaseReceiptController::class, 'void'])->middleware('permission:wms.purchase-receipts.void')->name('purchase-receipts.void');
    Route::get('/suppliers', [SupplierController::class, 'index'])->middleware('permission:wms.suppliers.view')->name('suppliers.index');
    Route::get('/suppliers/data', [SupplierController::class, 'data'])->middleware('permission:wms.suppliers.view')->name('suppliers.data');
    Route::get('/suppliers/options', [SupplierController::class, 'options'])->middleware('permission:wms.suppliers.view')->name('suppliers.options');
    Route::get('/suppliers/create', [SupplierController::class, 'create'])->middleware('permission:wms.suppliers.create')->name('suppliers.create');
    Route::post('/suppliers', [SupplierController::class, 'store'])->middleware('permission:wms.suppliers.create')->name('suppliers.store');
    Route::get('/suppliers/{supplier}/edit', [SupplierController::class, 'edit'])->middleware('permission:wms.suppliers.update')->name('suppliers.edit');
    Route::put('/suppliers/{supplier}', [SupplierController::class, 'update'])->middleware('permission:wms.suppliers.update')->name('suppliers.update');
    Route::delete('/suppliers/{supplier}', [SupplierController::class, 'destroy'])->middleware('permission:wms.suppliers.delete')->name('suppliers.destroy');
    Route::get('/items', [ItemController::class, 'index'])->middleware('permission:wms.items.view')->name('items.index');
    Route::get('/items/data', [ItemController::class, 'data'])->middleware('permission:wms.items.view')->name('items.data');
    Route::get('/items/category-options', [ItemController::class, 'categoryOptions'])->middleware('permission:wms.items.view')->name('items.category-options');
    Route::get('/items/account-options', [ItemController::class, 'accountOptions'])->middleware('permission:wms.items.view')->name('items.account-options');
    Route::get('/items/asset-category-options', [ItemController::class, 'assetCategoryOptions'])->middleware('permission:wms.items.view')->name('items.asset-category-options');
    Route::get('/items/uom-options', [ItemController::class, 'uomOptions'])->middleware('permission:wms.items.view')->name('items.uom-options');
    Route::get('/items/create', [ItemController::class, 'create'])->middleware('permission:wms.items.create')->name('items.create');
    Route::post('/items', [ItemController::class, 'store'])->middleware('permission:wms.items.create')->name('items.store');
    Route::get('/items/{item}/edit', [ItemController::class, 'edit'])->middleware('permission:wms.items.update')->name('items.edit');
    Route::put('/items/{item}', [ItemController::class, 'update'])->middleware('permission:wms.items.update')->name('items.update');
    Route::get('/item-categories', [ItemCategoryController::class, 'index'])->middleware('permission:wms.item-categories.view')->name('item-categories.index');
    Route::get('/item-categories/data', [ItemCategoryController::class, 'data'])->middleware('permission:wms.item-categories.view')->name('item-categories.data');
    Route::get('/item-categories/create', [ItemCategoryController::class, 'create'])->middleware('permission:wms.item-categories.create')->name('item-categories.create');
    Route::post('/item-categories', [ItemCategoryController::class, 'store'])->middleware('permission:wms.item-categories.create')->name('item-categories.store');
    Route::get('/item-categories/{category}/edit', [ItemCategoryController::class, 'edit'])->middleware('permission:wms.item-categories.update')->name('item-categories.edit');
    Route::put('/item-categories/{category}', [ItemCategoryController::class, 'update'])->middleware('permission:wms.item-categories.update')->name('item-categories.update');
    Route::delete('/item-categories/{category}', [ItemCategoryController::class, 'destroy'])->middleware('permission:wms.item-categories.delete')->name('item-categories.destroy');
    Route::get('/uoms', [UomController::class, 'index'])->middleware('permission:wms.uoms.view')->name('uoms.index');
    Route::get('/uoms/data', [UomController::class, 'data'])->middleware('permission:wms.uoms.view')->name('uoms.data');
    Route::get('/uoms/options', [UomController::class, 'options'])->middleware('permission:wms.uoms.view')->name('uoms.options');
    Route::get('/uoms/create', [UomController::class, 'create'])->middleware('permission:wms.uoms.create')->name('uoms.create');
    Route::post('/uoms', [UomController::class, 'store'])->middleware('permission:wms.uoms.create')->name('uoms.store');
    Route::get('/uoms/{uom}/edit', [UomController::class, 'edit'])->middleware('permission:wms.uoms.update')->name('uoms.edit');
    Route::put('/uoms/{uom}', [UomController::class, 'update'])->middleware('permission:wms.uoms.update')->name('uoms.update');
    Route::get('/uom-conversions', [UomController::class, 'conversions'])->middleware('permission:wms.uom-conversions.view')->name('uom-conversions.index');
    Route::get('/uom-conversions/data', [UomController::class, 'conversionData'])->middleware('permission:wms.uom-conversions.view')->name('uom-conversions.data');
    Route::post('/uom-conversions', [UomController::class, 'conversionStore'])->middleware('permission:wms.uom-conversions.create')->name('uom-conversions.store');
});
