<?php

use App\Modules\Wms\Controllers\EntryController;
use App\Modules\Wms\Controllers\InventoryAdjustmentController;
use App\Modules\Wms\Controllers\IssueReturnController;
use App\Modules\Wms\Controllers\ItemCategoryController;
use App\Modules\Wms\Controllers\ItemController;
use App\Modules\Wms\Controllers\LegacyAllocationReviewController;
use App\Modules\Wms\Controllers\OpeningBalanceController;
use App\Modules\Wms\Controllers\ProductionFinishedReceiptController;
use App\Modules\Wms\Controllers\ProductionIssueReturnController;
use App\Modules\Wms\Controllers\ProductionMaterialIssueController;
use App\Modules\Wms\Controllers\StockController;
use App\Modules\Wms\Controllers\StockCountController;
use App\Modules\Wms\Controllers\StockPolicyController;
use App\Modules\Wms\Controllers\StockValuationController;
use App\Modules\Wms\Controllers\TransferController;
use App\Modules\Wms\Controllers\UomController;
use App\Modules\Wms\Controllers\WorkflowController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'warehouse'])->prefix('wms')->name('wms.')->group(function () {
    // WMS routes are inventory-scoped; Purchasing has its own /purchasing entry.
    Route::get('/', EntryController::class)->middleware(['program:wms', 'permission:wms.dashboard.view'])->name('index');
    Route::middleware('program:wms')->group(function (): void {
        Route::get('/dashboard/data/{section}', [EntryController::class, 'data'])->middleware('permission:wms.dashboard.view')->name('dashboard.data');
        Route::get('/workflow', [WorkflowController::class, 'index'])->name('workflow.index');
        Route::get('/opening-balances', [OpeningBalanceController::class, 'index'])->middleware('permission:wms.opening-balances.view')->name('opening-balances.index');
        Route::get('/opening-balances/template', [OpeningBalanceController::class, 'template'])->middleware('permission:wms.opening-balances.create')->name('opening-balances.template');
        Route::post('/opening-balances/import', [OpeningBalanceController::class, 'importStage'])->middleware('permission:wms.opening-balances.create')->name('opening-balances.import.stage');
        Route::get('/opening-balances/import/{batch}', [OpeningBalanceController::class, 'importShow'])->middleware('permission:wms.opening-balances.create')->name('opening-balances.import.show');
        Route::get('/opening-balances/import/{batch}/errors', [OpeningBalanceController::class, 'importErrors'])->middleware('permission:wms.opening-balances.create')->name('opening-balances.import.errors');
        Route::put('/opening-balances/import/{batch}/commit', [OpeningBalanceController::class, 'importCommit'])->middleware('permission:wms.opening-balances.create')->name('opening-balances.import.commit');
        Route::get('/opening-balances/data', [OpeningBalanceController::class, 'data'])->middleware('permission:wms.opening-balances.view')->name('opening-balances.data');
        Route::get('/opening-balances/create', [OpeningBalanceController::class, 'create'])->middleware('permission:wms.opening-balances.create')->name('opening-balances.create');
        Route::post('/opening-balances', [OpeningBalanceController::class, 'store'])->middleware('permission:wms.opening-balances.create')->name('opening-balances.store');
        Route::get('/opening-balances/{batch}', [OpeningBalanceController::class, 'show'])->middleware('permission:wms.opening-balances.view')->name('opening-balances.show');
        Route::post('/opening-balances/{batch}/post', [OpeningBalanceController::class, 'post'])->middleware('permission:wms.opening-balances.post')->name('opening-balances.post');
        Route::delete('/opening-balances/{batch}', [OpeningBalanceController::class, 'destroy'])->middleware('permission:wms.opening-balances.delete')->name('opening-balances.destroy');
        Route::get('/stock', [StockController::class, 'index'])->middleware('permission:wms.stock.view')->name('stock.index');
        Route::get('/stock-valuation/legacy-accounting-proof', [StockValuationController::class, 'legacyAccountingProof'])->middleware('permission:wms.cost-revaluation.recover')->name('stock-valuation.legacy-accounting-proof');
        Route::post('/stock-valuation/legacy-accounting-proof/recover', [StockValuationController::class, 'legacyAccountingProofRecover'])->middleware('permission:wms.cost-revaluation.recover')->name('stock-valuation.legacy-accounting-proof.recover');
        Route::get('/issues', [IssueReturnController::class, 'issuesIndex'])->middleware('permission:wms.issues.view')->name('issues.index');
        Route::get('/issues/data', [IssueReturnController::class, 'issuesData'])->middleware('permission:wms.issues.view')->name('issues.data');
        Route::get('/issues/item-options', [IssueReturnController::class, 'itemOptions'])->middleware('permission:wms.issues.create')->name('issues.item-options');
        Route::get('/issues/create', [IssueReturnController::class, 'issueCreate'])->middleware('permission:wms.issues.create')->name('issues.create');
        Route::post('/issues', [IssueReturnController::class, 'issueStore'])->middleware('permission:wms.issues.create')->name('issues.store');
        Route::get('/issues/{document}', [IssueReturnController::class, 'issueShow'])->middleware('permission:wms.issues.view')->name('issues.show');
        Route::post('/issues/{document}/approve', [IssueReturnController::class, 'issueApprove'])->middleware('permission:wms.issues.approve')->name('issues.approve');
        Route::post('/issues/{document}/post', [IssueReturnController::class, 'issuePost'])->middleware('permission:wms.issues.post')->name('issues.post');
        Route::post('/issues/{document}/cancel', [IssueReturnController::class, 'issueCancel'])->middleware('permission:wms.issues.approve')->name('issues.cancel');
        Route::delete('/issues/{document}', [IssueReturnController::class, 'issueDelete'])->middleware('permission:wms.issues.delete')->name('issues.destroy');
        Route::get('/production/material-issues', [ProductionMaterialIssueController::class, 'index'])->middleware('permission:wms.issues.view')->name('production.material-issues.index');
        Route::get('/production/material-issues/data', [ProductionMaterialIssueController::class, 'data'])->middleware('permission:wms.issues.view')->name('production.material-issues.data');
        Route::get('/production/material-issues/item-options', [ProductionMaterialIssueController::class, 'itemOptions'])->middleware('permission:wms.issues.create')->name('production.material-issues.item-options');
        Route::get('/production/material-issues/create', [ProductionMaterialIssueController::class, 'create'])->middleware('permission:wms.issues.create')->name('production.material-issues.create');
        Route::post('/production/material-issues', [ProductionMaterialIssueController::class, 'store'])->middleware('permission:wms.issues.create')->name('production.material-issues.store');
        Route::get('/production/material-issues/{document}', [ProductionMaterialIssueController::class, 'show'])->middleware('permission:wms.issues.view')->name('production.material-issues.show');
        Route::post('/production/material-issues/{document}/approve', [ProductionMaterialIssueController::class, 'approve'])->middleware('permission:wms.issues.approve')->name('production.material-issues.approve');
        Route::post('/production/material-issues/{document}/post', [ProductionMaterialIssueController::class, 'post'])->middleware('permission:wms.issues.post')->name('production.material-issues.post');
        Route::post('/production/material-issues/{document}/cancel', [ProductionMaterialIssueController::class, 'cancel'])->middleware('permission:wms.issues.approve')->name('production.material-issues.cancel');
        Route::delete('/production/material-issues/{document}', [ProductionMaterialIssueController::class, 'destroy'])->middleware('permission:wms.issues.delete')->name('production.material-issues.destroy');
        Route::get('/production/issue-returns', [ProductionIssueReturnController::class, 'index'])->middleware('permission:wms.issue-returns.view')->name('production.issue-returns.index');
        Route::get('/production/issue-returns/data', [ProductionIssueReturnController::class, 'data'])->middleware('permission:wms.issue-returns.view')->name('production.issue-returns.data');
        Route::get('/production/issue-returns/issue-options', [ProductionIssueReturnController::class, 'issueOptions'])->middleware('permission:wms.issue-returns.create')->name('production.issue-returns.issue-options');
        Route::get('/production/issue-returns/issue-line-options', [ProductionIssueReturnController::class, 'issueLineOptions'])->middleware('permission:wms.issue-returns.create')->name('production.issue-returns.issue-line-options');
        Route::get('/production/issue-returns/create', [ProductionIssueReturnController::class, 'create'])->middleware('permission:wms.issue-returns.create')->name('production.issue-returns.create');
        Route::post('/production/issue-returns', [ProductionIssueReturnController::class, 'store'])->middleware('permission:wms.issue-returns.create')->name('production.issue-returns.store');
        Route::get('/production/issue-returns/{document}', [ProductionIssueReturnController::class, 'show'])->middleware('permission:wms.issue-returns.view')->name('production.issue-returns.show');
        Route::post('/production/issue-returns/{document}/approve', [ProductionIssueReturnController::class, 'approve'])->middleware('permission:wms.issue-returns.approve')->name('production.issue-returns.approve');
        Route::post('/production/issue-returns/{document}/cancel', [ProductionIssueReturnController::class, 'cancel'])->middleware('permission:wms.issue-returns.approve')->name('production.issue-returns.cancel');
        Route::post('/production/issue-returns/{document}/post', [ProductionIssueReturnController::class, 'post'])->middleware('permission:wms.issue-returns.post')->name('production.issue-returns.post');
        Route::post('/production/issue-returns/{document}/reverse', [ProductionIssueReturnController::class, 'reverse'])->middleware('permission:wms.issue-returns.post')->name('production.issue-returns.reverse');
        Route::delete('/production/issue-returns/{document}', [ProductionIssueReturnController::class, 'destroy'])->middleware('permission:wms.issue-returns.delete')->name('production.issue-returns.destroy');
        Route::get('/issue-returns', [IssueReturnController::class, 'returnsIndex'])->middleware('permission:wms.issue-returns.view')->name('issue-returns.index');
        Route::get('/issue-returns/data', [IssueReturnController::class, 'returnsData'])->middleware('permission:wms.issue-returns.view')->name('issue-returns.data');
        Route::get('/issue-returns/issue-options', [IssueReturnController::class, 'issueOptions'])->middleware('permission:wms.issue-returns.create')->name('issue-returns.issue-options');
        Route::get('/issue-returns/issue-line-options', [IssueReturnController::class, 'issueLineOptions'])->middleware('permission:wms.issue-returns.create')->name('issue-returns.issue-line-options');
        Route::get('/issue-returns/create', [IssueReturnController::class, 'returnCreate'])->middleware('permission:wms.issue-returns.create')->name('issue-returns.create');
        Route::post('/issue-returns', [IssueReturnController::class, 'returnStore'])->middleware('permission:wms.issue-returns.create')->name('issue-returns.store');
        Route::get('/issue-returns/{document}', [IssueReturnController::class, 'returnShow'])->middleware('permission:wms.issue-returns.view')->name('issue-returns.show');
        Route::post('/issue-returns/{document}/approve', [IssueReturnController::class, 'returnApprove'])->middleware('permission:wms.issue-returns.approve')->name('issue-returns.approve');
        Route::post('/issue-returns/{document}/cancel', [IssueReturnController::class, 'returnCancel'])->middleware('permission:wms.issue-returns.approve')->name('issue-returns.cancel');
        Route::post('/issue-returns/{document}/post', [IssueReturnController::class, 'returnPost'])->middleware('permission:wms.issue-returns.post')->name('issue-returns.post');
        Route::post('/issue-returns/{document}/reverse', [IssueReturnController::class, 'returnReverse'])->middleware('permission:wms.issue-returns.post')->name('issue-returns.reverse');
        Route::delete('/issue-returns/{document}', [IssueReturnController::class, 'returnDelete'])->middleware('permission:wms.issue-returns.delete')->name('issue-returns.destroy');
        Route::get('/stock-policies', [StockPolicyController::class, 'policies'])->middleware('permission:wms.stock-policies.view')->name('stock-policies.index');
        Route::get('/stock-policies/data', [StockPolicyController::class, 'policyData'])->middleware('permission:wms.stock-policies.view')->name('stock-policies.data');
        Route::get('/stock-policies/item-options', [StockPolicyController::class, 'itemOptions'])->middleware('permission:wms.stock-policies.view')->name('stock-policies.item-options');
        Route::get('/stock-policies/create', [StockPolicyController::class, 'policyCreate'])->middleware('permission:wms.stock-policies.create')->name('stock-policies.create');
        Route::post('/stock-policies', [StockPolicyController::class, 'policyStore'])->middleware('permission:wms.stock-policies.create')->name('stock-policies.store');
        Route::get('/stock-policies/{policy}/edit', [StockPolicyController::class, 'policyEdit'])->middleware('permission:wms.stock-policies.update')->name('stock-policies.edit');
        Route::put('/stock-policies/{policy}', [StockPolicyController::class, 'policyUpdate'])->middleware('permission:wms.stock-policies.update')->name('stock-policies.update');
        Route::delete('/stock-policies/{policy}', [StockPolicyController::class, 'policyDestroy'])->middleware('permission:wms.stock-policies.delete')->name('stock-policies.destroy');
        Route::get('/issue-types', [StockPolicyController::class, 'issueTypes'])->middleware('permission:wms.issue-types.view')->name('issue-types.index');
        Route::get('/issue-types/data', [StockPolicyController::class, 'issueTypeData'])->middleware('permission:wms.issue-types.view')->name('issue-types.data');
        Route::get('/issue-types/create', [StockPolicyController::class, 'issueTypeCreate'])->middleware('permission:wms.issue-types.create')->name('issue-types.create');
        Route::post('/issue-types', [StockPolicyController::class, 'issueTypeStore'])->middleware('permission:wms.issue-types.create')->name('issue-types.store');
        Route::get('/issue-types/{issueType}/edit', [StockPolicyController::class, 'issueTypeEdit'])->middleware('permission:wms.issue-types.update')->name('issue-types.edit');
        Route::put('/issue-types/{issueType}', [StockPolicyController::class, 'issueTypeUpdate'])->middleware('permission:wms.issue-types.update')->name('issue-types.update');
        Route::delete('/issue-types/{issueType}', [StockPolicyController::class, 'issueTypeDestroy'])->middleware('permission:wms.issue-types.delete')->name('issue-types.destroy');
        Route::get('/inventory-adjustments', [InventoryAdjustmentController::class, 'index'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.index');
        Route::get('/production/finished-receipts', [ProductionFinishedReceiptController::class, 'index'])->middleware('permission:wms.inventory-adjustments.view')->name('production.finished-receipts.index');
        Route::get('/production/finished-receipts/data', [ProductionFinishedReceiptController::class, 'data'])->middleware('permission:wms.inventory-adjustments.view')->name('production.finished-receipts.data');
        Route::get('/production/finished-receipts/item-options', [ProductionFinishedReceiptController::class, 'itemOptions'])->middleware('permission:wms.inventory-adjustments.create')->name('production.finished-receipts.item-options');
        Route::get('/production/finished-receipts/source-options', [ProductionFinishedReceiptController::class, 'sourceOptions'])->middleware('permission:wms.inventory-adjustments.create')->name('production.finished-receipts.source-options');
        Route::get('/production/finished-receipts/create', [ProductionFinishedReceiptController::class, 'create'])->middleware('permission:wms.inventory-adjustments.create')->name('production.finished-receipts.create');
        Route::post('/production/finished-receipts', [ProductionFinishedReceiptController::class, 'store'])->middleware('permission:wms.inventory-adjustments.create')->name('production.finished-receipts.store');
        Route::get('/production/finished-receipts/{document}/edit', [ProductionFinishedReceiptController::class, 'edit'])->middleware('permission:wms.inventory-adjustments.update')->name('production.finished-receipts.edit');
        Route::put('/production/finished-receipts/{document}', [ProductionFinishedReceiptController::class, 'update'])->middleware('permission:wms.inventory-adjustments.update')->name('production.finished-receipts.update');
        Route::post('/production/finished-receipts/{document}/approve', [ProductionFinishedReceiptController::class, 'approve'])->middleware('permission:wms.inventory-adjustments.approve')->name('production.finished-receipts.approve');
        Route::post('/production/finished-receipts/{document}/post', [ProductionFinishedReceiptController::class, 'post'])->middleware('permission:wms.inventory-adjustments.post')->name('production.finished-receipts.post');
        Route::post('/production/finished-receipts/{document}/reverse', [ProductionFinishedReceiptController::class, 'reverse'])->middleware('permission:wms.inventory-adjustments.reverse')->name('production.finished-receipts.reverse');
        Route::delete('/production/finished-receipts/{document}', [ProductionFinishedReceiptController::class, 'destroy'])->middleware('permission:wms.inventory-adjustments.delete')->name('production.finished-receipts.destroy');
        Route::get('/production/finished-receipts/{document}', [ProductionFinishedReceiptController::class, 'show'])->middleware('permission:wms.inventory-adjustments.view')->name('production.finished-receipts.show');
        Route::get('/stock-counts', [StockCountController::class, 'index'])->middleware('permission:wms.stock-counts.view')->name('stock-counts.index');
        Route::get('/stock-counts/data', [StockCountController::class, 'data'])->middleware('permission:wms.stock-counts.view')->name('stock-counts.data');
        Route::get('/stock-counts/item-options', [StockCountController::class, 'itemOptions'])->middleware('permission:wms.stock-counts.view')->name('stock-counts.item-options');
        Route::get('/stock-counts/create', [StockCountController::class, 'create'])->middleware('permission:wms.stock-counts.create')->name('stock-counts.create');
        Route::post('/stock-counts', [StockCountController::class, 'store'])->middleware('permission:wms.stock-counts.create')->name('stock-counts.store');
        Route::get('/stock-counts/{document}/edit', [StockCountController::class, 'edit'])->middleware('permission:wms.stock-counts.update')->name('stock-counts.edit');
        Route::put('/stock-counts/{document}', [StockCountController::class, 'update'])->middleware('permission:wms.stock-counts.update')->name('stock-counts.update');
        Route::get('/stock-counts/{document}', [StockCountController::class, 'show'])->middleware('permission:wms.stock-counts.view')->name('stock-counts.show');
        Route::post('/stock-counts/{document}/approve', [StockCountController::class, 'approve'])->middleware('permission:wms.stock-counts.approve')->name('stock-counts.approve');
        Route::delete('/stock-counts/{document}', [StockCountController::class, 'destroy'])->middleware('permission:wms.stock-counts.delete')->name('stock-counts.destroy');
        Route::get('/inventory-adjustments/data', [InventoryAdjustmentController::class, 'adjustmentData'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.data');
        Route::get('/inventory-adjustments/item-options', [InventoryAdjustmentController::class, 'itemOptions'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.item-options');
        Route::get('/inventory-adjustments/create', [InventoryAdjustmentController::class, 'create'])->middleware('permission:wms.inventory-adjustments.create')->name('inventory-adjustments.create');
        Route::post('/inventory-adjustments', [InventoryAdjustmentController::class, 'storeDocument'])->middleware('permission:wms.inventory-adjustments.create')->name('inventory-adjustments.store');
        Route::get('/inventory-adjustments/documents/{document}', [InventoryAdjustmentController::class, 'showDocument'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.documents.show');
        Route::get('/inventory-adjustments/documents/{document}/edit', [InventoryAdjustmentController::class, 'editDocument'])->middleware('permission:wms.inventory-adjustments.update')->name('inventory-adjustments.documents.edit');
        Route::put('/inventory-adjustments/documents/{document}', [InventoryAdjustmentController::class, 'updateDocument'])->middleware('permission:wms.inventory-adjustments.update')->name('inventory-adjustments.documents.update');
        Route::delete('/inventory-adjustments/documents/{document}', [InventoryAdjustmentController::class, 'deleteDocument'])->middleware('permission:wms.inventory-adjustments.delete')->name('inventory-adjustments.documents.delete');
        Route::post('/inventory-adjustments/documents/{document}/approve', [InventoryAdjustmentController::class, 'approveDocument'])->middleware('permission:wms.inventory-adjustments.approve')->name('inventory-adjustments.documents.approve');
        Route::post('/inventory-adjustments/documents/{document}/post', [InventoryAdjustmentController::class, 'postDocument'])->middleware('permission:wms.inventory-adjustments.post')->name('inventory-adjustments.documents.post');
        Route::post('/inventory-adjustments/documents/{document}/reverse', [InventoryAdjustmentController::class, 'reverseDocument'])->middleware('permission:wms.inventory-adjustments.reverse')->name('inventory-adjustments.documents.reverse');
        Route::get('/inventory-adjustments/{adjustment}', [InventoryAdjustmentController::class, 'show'])->middleware('permission:wms.inventory-adjustments.view')->name('inventory-adjustments.show');
        Route::post('/inventory-adjustments/{adjustment}/approve', [InventoryAdjustmentController::class, 'approve'])->middleware('permission:wms.inventory-adjustments.approve')->name('inventory-adjustments.approve');
        Route::post('/inventory-adjustments/{adjustment}/post', [InventoryAdjustmentController::class, 'post'])->middleware('permission:wms.inventory-adjustments.post')->name('inventory-adjustments.post');
        Route::post('/inventory-adjustments/{adjustment}/reverse', [InventoryAdjustmentController::class, 'reverse'])->middleware('permission:wms.inventory-adjustments.reverse')->name('inventory-adjustments.reverse');
        Route::delete('/inventory-adjustments/{adjustment}', [InventoryAdjustmentController::class, 'destroy'])->middleware('permission:wms.inventory-adjustments.delete')->name('inventory-adjustments.destroy');
        Route::get('/stock/summary', [StockController::class, 'summary'])->middleware('permission:wms.stock.view')->name('stock.summary');
        Route::get('/stock/data', [StockController::class, 'data'])->middleware('permission:wms.stock.view')->name('stock.data');
        Route::get('/stock/item-options', [StockController::class, 'itemOptions'])->middleware('permission:wms.stock.view')->name('stock.item-options');
        Route::get('/stock/{item}/reconciliation', [StockController::class, 'reconciliation'])->middleware('permission:wms.stock.view')->name('stock.reconciliation');
        Route::get('/stock/{item}', [StockController::class, 'show'])->middleware('permission:wms.stock.view')->name('stock.show');
        Route::get('/transfers/outgoing', [TransferController::class, 'index'])->defaults('direction', 'out')->middleware('permission:wms.transfers.view')->name('transfers.outgoing.index');
        Route::get('/transfers/outgoing/data', [TransferController::class, 'data'])->defaults('direction', 'out')->middleware('permission:wms.transfers.view')->name('transfers.outgoing.data');
        Route::get('/transfers/incoming', [TransferController::class, 'index'])->defaults('direction', 'in')->middleware('permission:wms.transfers.view')->name('transfers.incoming.index');
        Route::get('/transfers/incoming/data', [TransferController::class, 'data'])->defaults('direction', 'in')->middleware('permission:wms.transfers.view')->name('transfers.incoming.data');
        Route::get('/transfers', [TransferController::class, 'index'])->defaults('direction', 'all')->middleware('permission:wms.transfers.view')->name('transfers.index');
        Route::get('/transfers/data', [TransferController::class, 'data'])->defaults('direction', 'all')->middleware('permission:wms.transfers.view')->name('transfers.data');
        Route::get('/transfers/create', [TransferController::class, 'create'])->middleware('permission:wms.transfers.create')->name('transfers.create');
        Route::get('/transfers/item-options', [TransferController::class, 'itemOptions'])->middleware('permission:wms.transfers.create')->name('transfers.item-options');
        Route::get('/transfers/{transfer}/receive', [TransferController::class, 'receive'])->middleware('permission:wms.transfers.complete')->name('transfers.receive');
        Route::get('/transfers/{transfer}/lines', [TransferController::class, 'lines'])->middleware('permission:wms.transfers.view')->name('transfers.lines');
        Route::get('/transfers/{transfer}', [TransferController::class, 'show'])->middleware('permission:wms.transfers.view')->name('transfers.show');
        Route::delete('/transfers/{transfer}', [TransferController::class, 'destroy'])->middleware('permission:wms.transfers.delete')->name('transfers.destroy');
        Route::post('/transfers', [TransferController::class, 'store'])->middleware('permission:wms.transfers.create')->name('transfers.store');
        Route::post('/transfers/{transfer}/dispatch', [TransferController::class, 'dispatch'])->middleware('permission:wms.transfers.dispatch')->name('transfers.dispatch');
        Route::post('/transfers/{transfer}/complete', [TransferController::class, 'complete'])->middleware('permission:wms.transfers.complete')->name('transfers.complete');
        Route::post('/transfers/{transfer}/void', [TransferController::class, 'void'])->middleware('permission:wms.transfers.void')->name('transfers.void');
        Route::get('/stock-valuation', [StockValuationController::class, 'index'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.index');
        Route::get('/stock-valuation/lineage', [StockValuationController::class, 'lineage'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.lineage');
        Route::get('/stock-valuation/lineage/data', [StockValuationController::class, 'lineageData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.lineage.data');
        Route::get('/stock-valuation/shadow-calculation', [StockValuationController::class, 'shadowCalculation'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.shadow-calculation');
        Route::get('/stock-valuation/shadow-calculation/data', [StockValuationController::class, 'shadowCalculationData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.shadow-calculation.data');
        Route::get('/stock-valuation/shadow-calculation/allocation-options', [StockValuationController::class, 'shadowAllocationOptions'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.shadow-calculation.allocation-options');
        Route::get('/stock-valuation/revaluation', [StockValuationController::class, 'revaluationQueue'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.revaluation.index');
        Route::get('/stock-valuation/revaluation/health', [StockValuationController::class, 'revaluationHealth'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.revaluation.health');
        Route::get('/stock-valuation/revaluation/data', [StockValuationController::class, 'revaluationQueueData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.revaluation.data');
        Route::get('/stock-valuation/revaluation/{run}/preflight-data', [StockValuationController::class, 'revaluationPreflightData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.revaluation.preflight-data');
        Route::get('/stock-valuation/revaluation/{run}/deltas-data', [StockValuationController::class, 'revaluationDeltasData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.revaluation.deltas-data');
        Route::get('/stock-valuation/manual-trigger', [StockValuationController::class, 'manualTrigger'])->middleware('permission:wms.cost-revaluation.trigger')->name('stock-valuation.manual-trigger.index');
        Route::get('/stock-valuation/emergency-rebuild', [StockValuationController::class, 'emergencyRebuild'])->middleware('permission:wms.cost-revaluation.emergency-rebuild')->name('stock-valuation.emergency-rebuild.index');
        Route::post('/stock-valuation/emergency-rebuild', [StockValuationController::class, 'emergencyRebuildDispatch'])->middleware('permission:wms.cost-revaluation.emergency-rebuild')->name('stock-valuation.emergency-rebuild.dispatch');
        Route::get('/stock-valuation/manual-trigger/options', [StockValuationController::class, 'manualTriggerOptions'])->middleware('permission:wms.cost-revaluation.trigger')->name('stock-valuation.manual-trigger.options');
        Route::get('/stock-valuation/manual-trigger/preview', [StockValuationController::class, 'manualTriggerPreview'])->middleware('permission:wms.cost-revaluation.trigger')->name('stock-valuation.manual-trigger.preview');
        Route::get('/stock-valuation/manual-trigger/scope-items', [StockValuationController::class, 'manualTriggerScopeItems'])->middleware('permission:wms.cost-revaluation.trigger')->name('stock-valuation.manual-trigger.scope-items');
        Route::get('/stock-valuation/manual-trigger/scope-preview', [StockValuationController::class, 'manualTriggerScopePreview'])->middleware('permission:wms.cost-revaluation.trigger')->name('stock-valuation.manual-trigger.scope-preview');
        Route::post('/stock-valuation/manual-trigger', [StockValuationController::class, 'manualTriggerDispatch'])->middleware('permission:wms.cost-revaluation.trigger')->name('stock-valuation.manual-trigger.dispatch');
        Route::get('/stock-valuation/revaluation/{run}', [StockValuationController::class, 'revaluationShow'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.revaluation.show');
        Route::post('/stock-valuation/revaluation/{run}/approve', [StockValuationController::class, 'revaluationApprove'])->middleware('permission:wms.cost-revaluation.approve')->name('stock-valuation.revaluation.approve');
        Route::post('/stock-valuation/revaluation/{run}/reject', [StockValuationController::class, 'revaluationReject'])->middleware('permission:wms.cost-revaluation.approve')->name('stock-valuation.revaluation.reject');
        Route::post('/stock-valuation/revaluation/{run}/apply', [StockValuationController::class, 'revaluationApply'])->middleware('permission:wms.cost-revaluation.post')->name('stock-valuation.revaluation.apply');
        Route::post('/stock-valuation/revaluation/{run}/post-journal', [StockValuationController::class, 'revaluationPostJournal'])->middleware('permission:wms.cost-revaluation.post')->name('stock-valuation.revaluation.post-journal');
        Route::post('/stock-valuation/revaluation/{run}/complete', [StockValuationController::class, 'revaluationComplete'])->middleware('permission:wms.cost-revaluation.post')->name('stock-valuation.revaluation.complete');
        Route::post('/stock-valuation/revaluation/{run}/resume', [StockValuationController::class, 'revaluationResume'])->middleware('permission:wms.cost-revaluation.recover')->name('stock-valuation.revaluation.resume');
        Route::post('/stock-valuation/revaluation/{run}/cancel', [StockValuationController::class, 'revaluationCancel'])->middleware('permission:wms.cost-revaluation.cancel')->name('stock-valuation.revaluation.cancel');
        Route::get('/stock-valuation/item/{item}', [StockValuationController::class, 'show'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.show');
        Route::get('/stock-valuation/item/{item}/layers', [StockValuationController::class, 'layersData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.layers');
        Route::get('/stock-valuation/data', [StockValuationController::class, 'data'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.data');
        Route::get('/stock-valuation/historical-data', [StockValuationController::class, 'historicalData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.historical-data');
        Route::get('/stock-valuation/historical-reconciliation-data', [StockValuationController::class, 'historicalReconciliationData'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.historical-reconciliation-data');
        Route::get('/stock-valuation/preflight-summary', [StockValuationController::class, 'preflightSummary'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.preflight-summary');
        Route::get('/stock-valuation/recost-health', [StockValuationController::class, 'recostHealth'])->middleware('permission:wms.stock-valuation.view')->name('stock-valuation.recost-health');
        Route::get('/legacy-allocation-reviews', [LegacyAllocationReviewController::class, 'index'])->middleware('permission:wms.cost-allocation-reviews.view')->name('legacy-allocation-reviews.index');
        Route::get('/legacy-allocation-reviews/data', [LegacyAllocationReviewController::class, 'data'])->middleware('permission:wms.cost-allocation-reviews.view')->name('legacy-allocation-reviews.data');
        Route::get('/legacy-allocation-reviews/{review}', [LegacyAllocationReviewController::class, 'show'])->middleware('permission:wms.cost-allocation-reviews.view')->name('legacy-allocation-reviews.show');
        Route::post('/legacy-allocation-reviews/{review}/resolve', [LegacyAllocationReviewController::class, 'resolve'])->middleware('permission:wms.cost-allocation-reviews.approve')->name('legacy-allocation-reviews.resolve');
        Route::post('/legacy-allocation-reviews/{review}/approve-no-action', [LegacyAllocationReviewController::class, 'approveNoAction'])->middleware('permission:wms.cost-allocation-reviews.approve')->name('legacy-allocation-reviews.approve-no-action');
        Route::post('/stock-valuation/recost-retry', [StockValuationController::class, 'retryRecost'])->middleware('permission:wms.recost.retry')->name('stock-valuation.recost-retry');
    });

    Route::middleware('program:wms')->group(function (): void {
        Route::get('/items', [ItemController::class, 'index'])->middleware('permission:wms.items.view')->name('items.index');
        Route::get('/items/data', [ItemController::class, 'data'])->middleware('permission:wms.items.view')->name('items.data');
        Route::get('/items/category-options', [ItemController::class, 'categoryOptions'])->middleware('permission:wms.items.view')->name('items.category-options');
        Route::get('/items/account-options', [ItemController::class, 'accountOptions'])->middleware('permission:wms.items.view')->name('items.account-options');
        Route::get('/items/asset-category-options', [ItemController::class, 'assetCategoryOptions'])->middleware('permission:wms.items.view')->name('items.asset-category-options');
        Route::get('/items/uom-options', [ItemController::class, 'uomOptions'])->middleware('permission:wms.items.view')->name('items.uom-options');
        Route::get('/items/create', [ItemController::class, 'create'])->middleware('permission:wms.items.create')->name('items.create');
        Route::post('/items', [ItemController::class, 'store'])->middleware('permission:wms.items.create')->name('items.store');
        Route::get('/items/{item}/cover-image', [ItemController::class, 'coverImage'])->middleware('permission:wms.items.update')->name('items.cover-image');
        Route::get('/items/{item}/additional-images/{index}', [ItemController::class, 'additionalImage'])->whereNumber('index')->middleware('permission:wms.items.update')->name('items.additional-image');
        Route::get('/items/{item}/edit', [ItemController::class, 'edit'])->middleware('permission:wms.items.update')->name('items.edit');
        Route::put('/items/{item}', [ItemController::class, 'update'])->middleware('permission:wms.items.update')->name('items.update');
    });
    Route::middleware('program:wms')->group(function (): void {
        Route::get('/item-categories', [ItemCategoryController::class, 'index'])->middleware('permission:wms.item-categories.view')->name('item-categories.index');
        Route::get('/item-categories/data', [ItemCategoryController::class, 'data'])->middleware('permission:wms.item-categories.view')->name('item-categories.data');
        Route::get('/item-categories/create', [ItemCategoryController::class, 'create'])->middleware('permission:wms.item-categories.create')->name('item-categories.create');
        Route::post('/item-categories', [ItemCategoryController::class, 'store'])->middleware('permission:wms.item-categories.create')->name('item-categories.store');
        Route::get('/item-categories/{category}/edit', [ItemCategoryController::class, 'edit'])->middleware('permission:wms.item-categories.update')->name('item-categories.edit');
        Route::put('/item-categories/{category}', [ItemCategoryController::class, 'update'])->middleware('permission:wms.item-categories.update')->name('item-categories.update');
        Route::delete('/item-categories/{category}', [ItemCategoryController::class, 'destroy'])->middleware('permission:wms.item-categories.delete')->name('item-categories.destroy');
        Route::delete('/items/{item}', [ItemController::class, 'destroy'])->middleware('permission:wms.items.delete')->name('items.destroy');
        Route::get('/uoms', [UomController::class, 'index'])->middleware('permission:wms.uoms.view')->name('uoms.index');
        Route::get('/uoms/data', [UomController::class, 'data'])->middleware('permission:wms.uoms.view')->name('uoms.data');
        Route::get('/uoms/options', [UomController::class, 'options'])->middleware('permission:wms.uoms.view')->name('uoms.options');
        Route::get('/uoms/create', [UomController::class, 'create'])->middleware('permission:wms.uoms.create')->name('uoms.create');
        Route::post('/uoms', [UomController::class, 'store'])->middleware('permission:wms.uoms.create')->name('uoms.store');
        Route::get('/uoms/{uom}/edit', [UomController::class, 'edit'])->middleware('permission:wms.uoms.update')->name('uoms.edit');
        Route::put('/uoms/{uom}', [UomController::class, 'update'])->middleware('permission:wms.uoms.update')->name('uoms.update');
        Route::delete('/uoms/{uom}', [UomController::class, 'destroy'])->middleware('permission:wms.uoms.delete')->name('uoms.destroy');
        Route::get('/uom-conversions', [UomController::class, 'conversions'])->middleware('permission:wms.uom-conversions.view')->name('uom-conversions.index');
        Route::get('/uom-conversions/data', [UomController::class, 'conversionData'])->middleware('permission:wms.uom-conversions.view')->name('uom-conversions.data');
        Route::post('/uom-conversions', [UomController::class, 'conversionStore'])->middleware('permission:wms.uom-conversions.create')->name('uom-conversions.store');
        Route::delete('/uom-conversions/{conversion}', [UomController::class, 'conversionDestroy'])->middleware('permission:wms.uom-conversions.delete')->name('uom-conversions.destroy');
    });
});
