@extends('Finance::layout')
@section('title', 'เงินทดรองจ่ายพนักงาน | Finance')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">FINANCE / EMPLOYEE ADVANCE</p><h1 class="h3 mb-1">เงินทดรองจ่ายพนักงาน</h1><p class="text-secondary mb-0">ติดตามเงินทดรองจ่ายของ User ในสาขาและคลังปัจจุบัน</p></div>@if(auth()->user()->hasPermission('finance.employee-advances.create'))<a class="btn btn-app-primary" href="{{ route('finance.employee-advances.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>สร้างใบเงินทดรอง</a>@endif</div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center gap-3 mb-3"><div><h2 class="h5 mb-1">ตัวกรอง</h2><p class="small text-secondary mb-0">กรองสถานะและวันที่เอกสารก่อนดูรายการ</p></div><button id="employee-advance-reset" class="btn btn-sm btn-app-soft" type="button"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-md-4"><label class="form-label" for="employee-advance-status">สถานะ</label><select id="employee-advance-status" class="form-select"><option value="">ทุกสถานะ</option>@foreach(['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','PARTIAL'=>'ตัดบางส่วน','CLEARED'=>'เคลียร์แล้ว','VOID'=>'ยกเลิก','REVERSED'=>'ยกเลิกรายการแล้ว'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label" for="employee-advance-date-from">วันที่เอกสารตั้งแต่</label><input id="employee-advance-date-from" class="form-control" type="date"></div><div class="col-md-4"><label class="form-label" for="employee-advance-date-to">วันที่เอกสารถึง</label><input id="employee-advance-date-to" class="form-control" type="date"></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">รายการเงินทดรองจ่าย</h2><div class="table-responsive"><table id="employee-advances-table" class="table table-hover align-middle w-100" data-url="{{ route('finance.employee-advances.data') }}"><thead><tr><th>เลขที่</th><th>วันที่</th><th>พนักงาน</th><th>บัญชีจ่าย</th><th class="text-end">จำนวนเงิน</th><th>สถานะ</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){var $t=$('#employee-advances-table'),text=$.fn.dataTable.render.text(),filters=function(){return {status:$('#employee-advance-status').val(),date_from:$('#employee-advance-date-from').val(),date_to:$('#employee-advance-date-to').val()};},labels={DRAFT:'ร่าง',SUBMITTED:'รออนุมัติ',APPROVED:'อนุมัติแล้ว',POSTED:'ลงบัญชีแล้ว',PARTIAL:'ตัดบางส่วน',CLEARED:'เคลียร์แล้ว',VOID:'ยกเลิก',REVERSED:'ยกเลิกรายการแล้ว'};var table=$t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$t.data('url'),data:function(d){$.extend(d,filters());}},order:[[1,'desc']],buttons:[window.erpExcelButton($t,filters)],columns:[{data:'document_number',render:text.display},{data:'document_date_label',render:text.display},{data:'employee_label',render:text.display},{data:'bank_account_label',render:text.display},{data:'amount',className:'text-end',render:$.fn.dataTable.render.number(',','.',2)},{data:'status_label',render:function(v,type,row){return type==='display'?'<span class="badge '+text.display(row.status_class||'app-status-neutral')+'">'+text.display(v||labels[row.status]||row.status)+'</span>':v;}},{data:null,orderable:false,searchable:false,className:'text-end text-nowrap',render:function(_,type,row){if(type!=='display')return '';var actions=['<a class="btn btn-sm btn-app-soft" href="'+text.display(row.show_url)+'" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-file-find" aria-hidden="true"></i></a>'];if(row.edit_url)actions.push('<a class="btn btn-sm btn-app-soft" href="'+text.display(row.edit_url)+'" title="แก้ไข" aria-label="แก้ไข"><i class="bx bx-edit" aria-hidden="true"></i></a>');if(row.delete_url)actions.push('<button class="btn btn-sm btn-app-danger js-delete-advance" type="button" data-url="'+text.display(row.delete_url)+'" title="ลบร่าง" aria-label="ลบร่าง"><i class="bx bx-trash" aria-hidden="true"></i></button>');return actions.join(' ');}}]}));$('#employee-advance-status,#employee-advance-date-from,#employee-advance-date-to').on('change',function(){table.ajax.reload();});$('#employee-advance-reset').on('click',function(){$('#employee-advance-status').val('');$('#employee-advance-date-from,#employee-advance-date-to').val('');table.ajax.reload();});window.erpAjaxDelete({button:'.js-delete-advance',reload:'#employee-advances-table',confirm:'ยืนยันการลบใบเงินทดรองฉบับร่างนี้หรือไม่?',confirmButtonText:'ลบร่าง',cancelButtonText:'กลับ'});});</script>@endpush
