@extends('Pos::layout')

@section('title', ($priceList->exists ? 'แก้ไข' : 'เพิ่ม').' รายการราคา | POS')

@section('content')
@php($places = \App\Modules\Wms\Support\WmsDecimal::places())
@php($step = 1 / (10 ** $places))
@php($formatDecimal = fn ($value) => $value === null || $value === '' ? '' : number_format((float) $value, $places, '.', ''))
@php($zero = $formatDecimal(0))
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">POS / MASTER DATA</p><h1 class="h3 mb-1">{{ $priceList->exists ? 'แก้ไข' : 'เพิ่ม' }}รายการราคา</h1><p class="text-secondary mb-4">ราคาจะถูกเลือกตามกลุ่มลูกค้า วันที่มีผล หน่วย และจำนวนขั้นต่ำ แล้วบันทึก snapshot เมื่อออกเอกสารขาย</p>
    <form id="price-list-form" method="POST" action="{{ $priceList->exists ? route('pos.price-lists.update',$priceList) : route('pos.price-lists.store') }}">
        @csrf @if($priceList->exists) @method('PUT') @endif
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-3">
            <div class="col-md-3"><label class="form-label" for="pl-code">รหัส <span class="text-danger">*</span></label><input id="pl-code" class="form-control text-uppercase" name="code" maxlength="50" value="{{ old('code',$priceList->code) }}" required><div class="invalid-feedback" data-error-for="code"></div></div>
            <div class="col-md-5"><label class="form-label" for="pl-name">ชื่อรายการราคา <span class="text-danger">*</span></label><input id="pl-name" class="form-control" name="name" maxlength="255" value="{{ old('name',$priceList->name) }}" required><div class="invalid-feedback" data-error-for="name"></div></div>
            <div class="col-md-2"><label class="form-label" for="pl-currency">สกุลเงิน <span class="text-danger">*</span></label><input id="pl-currency" class="form-control text-uppercase" name="currency" maxlength="3" value="{{ old('currency',$priceList->currency ?: 'THB') }}" required><div class="invalid-feedback" data-error-for="currency"></div></div>
            <div class="col-md-2"><label class="form-label" for="pl-priority">ลำดับความสำคัญ <span class="text-danger">*</span></label><input id="pl-priority" class="form-control text-end" name="priority" type="number" min="0" step="1" value="{{ old('priority',$priceList->priority ?? 0) }}" required><div class="invalid-feedback" data-error-for="priority"></div></div>
            <div class="col-md-4"><label class="form-label">กลุ่มลูกค้า (ไม่เลือก = ทุกกลุ่ม)</label><select class="form-select js-price-group" name="customer_group_code" data-url="{{ route('pos.price-lists.group-options') }}"><option value="">ทุกกลุ่ม</option>@if($priceList->customer_group_code)<option value="{{ $priceList->customer_group_code }}" selected>{{ $priceList->customer_group_code }}</option>@endif</select><div class="invalid-feedback" data-error-for="customer_group_code"></div></div>
            <div class="col-md-4"><label class="form-label" for="pl-from">วันที่เริ่มมีผล</label><input id="pl-from" class="form-control" type="date" name="effective_from" value="{{ old('effective_from',$priceList->effective_from?->format('Y-m-d')) }}"><div class="invalid-feedback" data-error-for="effective_from"></div></div>
            <div class="col-md-4"><label class="form-label" for="pl-to">วันที่สิ้นสุด</label><input id="pl-to" class="form-control" type="date" name="effective_to" value="{{ old('effective_to',$priceList->effective_to?->format('Y-m-d')) }}"><div class="invalid-feedback" data-error-for="effective_to"></div></div>
            <div class="col-12 form-check"><input type="hidden" name="is_active" value="0"><input class="form-check-input" id="pl-active" type="checkbox" name="is_active" value="1" @checked(old('is_active',$priceList->is_active ?? true))><label class="form-check-label" for="pl-active">เปิดใช้งาน Price List</label></div>
        </div></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">รายการราคา</h2><p class="text-secondary small mb-0">หน่วยว่างหมายถึงใช้กับหน่วยใดก็ได้ และราคาต้องไม่ซ้ำสินค้าหน่วยเดียวกันที่จำนวนขั้นต่ำเท่ากัน</p></div><button class="btn btn-sm btn-app-soft" id="add-price-line" type="button"><i class="bx bx-plus" aria-hidden="true"></i> เพิ่มรายการ</button></div>
            <div class="table-responsive"><table class="table align-middle price-lines-table"><thead><tr><th style="min-width:260px">สินค้า</th><th style="min-width:180px">หน่วย</th><th style="min-width:140px">จำนวนขั้นต่ำ</th><th style="min-width:150px">ราคาต่อหน่วย</th><th style="min-width:130px">ส่วนลด %</th><th>เริ่มมีผล</th><th>สิ้นสุด</th><th>จัดการ</th></tr></thead><tbody id="price-lines">@foreach($lines as $index=>$line)<tr class="price-line" data-index="{{ $index }}"><td><select class="form-select js-price-item" name="lines[{{ $index }}][item_id]" data-url="{{ route('pos.price-lists.item-options') }}" required>@if($line->item)<option value="{{ $line->item_id }}" selected>{{ $line->item->code }} · {{ $line->item->name }}</option>@else<option value="">ค้นหาสินค้า</option>@endif</select></td><td><select class="form-select js-price-uom" name="lines[{{ $index }}][uom_id]" data-url="{{ route('pos.price-lists.uom-options') }}"><option value="">ทุกหน่วย</option>@if($line->uom)<option value="{{ $line->uom_id }}" selected>{{ $line->uom->code }} · {{ $line->uom->name }}</option>@endif</select></td><td><input class="form-control text-end" type="number" min="0" step="{{ $step }}" name="lines[{{ $index }}][minimum_quantity]" value="{{ old("lines.$index.minimum_quantity", $formatDecimal($line->minimum_quantity ?? 0)) }}" required></td><td><input class="form-control text-end" type="number" min="0" step="{{ $step }}" name="lines[{{ $index }}][unit_price]" value="{{ old("lines.$index.unit_price", $formatDecimal($line->unit_price)) }}" required></td><td><input class="form-control text-end" type="number" min="0" max="100" step="{{ $step }}" name="lines[{{ $index }}][discount_percent]" value="{{ old("lines.$index.discount_percent", $formatDecimal($line->discount_percent ?? 0)) }}" required></td><td><input class="form-control" type="date" name="lines[{{ $index }}][effective_from]" value="{{ old("lines.$index.effective_from", $line->effective_from?->format('Y-m-d')) }}"></td><td><input class="form-control" type="date" name="lines[{{ $index }}][effective_to]" value="{{ old("lines.$index.effective_to", $line->effective_to?->format('Y-m-d')) }}"></td><td><button class="btn btn-sm btn-outline-danger js-remove-price-line" title="ลบรายการ" type="button"><i class="bx bx-trash" aria-hidden="true"></i><span class="visually-hidden">ลบรายการ</span></button></td></tr>@endforeach</tbody></table></div>
            <div class="mt-4"><button class="btn btn-dark" type="submit">บันทึก</button> <a class="btn btn-outline-secondary" href="{{ route('pos.price-lists.index') }}">ย้อนกลับ</a></div>
        </div></div>
    </form>
</div>
<template id="price-line-template"><tr class="price-line" data-index="__INDEX__"><td><select class="form-select js-price-item" name="lines[__INDEX__][item_id]" data-url="{{ route('pos.price-lists.item-options') }}" required><option value="">ค้นหาสินค้า</option></select></td><td><select class="form-select js-price-uom" name="lines[__INDEX__][uom_id]" data-url="{{ route('pos.price-lists.uom-options') }}"><option value="">ทุกหน่วย</option></select></td><td><input class="form-control text-end" type="number" min="0" step="{{ $step }}" name="lines[__INDEX__][minimum_quantity]" value="{{ $zero }}" required></td><td><input class="form-control text-end" type="number" min="0" step="{{ $step }}" name="lines[__INDEX__][unit_price]" required></td><td><input class="form-control text-end" type="number" min="0" max="100" step="{{ $step }}" name="lines[__INDEX__][discount_percent]" value="{{ $zero }}" required></td><td><input class="form-control" type="date" name="lines[__INDEX__][effective_from]"></td><td><input class="form-control" type="date" name="lines[__INDEX__][effective_to]"></td><td><button class="btn btn-sm btn-outline-danger js-remove-price-line" title="ลบรายการ" type="button"><i class="bx bx-trash" aria-hidden="true"></i><span class="visually-hidden">ลบรายการ</span></button></td></tr></template>
@endsection

@push('scripts')
<script>
$(function(){
    function select2($el, placeholder){$el.select2({theme:'bootstrap-5',width:'100%',allowClear:true,placeholder:placeholder,ajax:{url:$el.data('url'),dataType:'json',delay:250,data:function(p){return {q:p.term||'',page:p.page||1};},processResults:function(data,p){p.page=p.page||1;return data;}}});}
    function wire($row){select2($row.find('.js-price-item'),'ค้นหาสินค้า');select2($row.find('.js-price-uom'),'ทุกหน่วย');}
    $('.price-line').each(function(){wire($(this));});
    $('#add-price-line').on('click',function(){var i=$('#price-lines .price-line').length,html=$('#price-line-template').html().replaceAll('__INDEX__',i);var $row=$(html);$('#price-lines').append($row);wire($row);});
    $(document).on('click','.js-remove-price-line',function(){if($('#price-lines .price-line').length>1)$(this).closest('.price-line').remove();});
    select2($('.js-price-group'),'ทุกกลุ่ม');
    window.erpAjaxForm({form:'#price-list-form',redirect:{{ $priceList->exists?'false':'true' }}});
});
</script>
@endpush
