@extends('Wms::layout')
@section('title', 'ตรวจสอบ Opening Balance Import')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">WMS / OPENING BALANCE / IMPORT</p><h1 class="h3 mb-2">ตรวจสอบไฟล์ยอดยกมา</h1><p class="text-secondary mb-0">{{ $batch->original_filename }} · {{ number_format($batch->total_rows) }} รายการ</p></div><a class="btn btn-outline-secondary" href="{{ route('wms.opening-balances.create') }}">กลับ</a></div>
<div class="alert {{ $batch->error_rows ? 'alert-warning' : 'alert-success' }} border-0 shadow-sm d-flex flex-wrap justify-content-between align-items-center gap-2"><span>ตรวจสอบแล้ว: ผ่าน {{ number_format($batch->valid_rows) }} รายการ · ผิดพลาด {{ number_format($batch->error_rows) }} รายการ @if($batch->error_rows) — ต้องแก้ไขไฟล์แล้วอัปโหลดใหม่ก่อน Commit @else — พร้อมสำหรับขั้นตอนอนุมัติ/Commit (ยังไม่ลงสต็อก) @endif</span><span class="d-flex gap-2">@if($batch->error_rows)<a class="btn btn-outline-danger btn-sm" href="{{ route('wms.opening-balances.import.errors', $batch) }}"><i class="bx bx-download me-1"></i>ดาวน์โหลด Error Workbook</a>@endif @if(!$batch->error_rows && $batch->status === 'VALIDATED')<button class="btn btn-dark btn-sm" id="commit-import">อนุมัติและสร้างยอดยกมา</button>@endif</span></div>
<div class="card border-0 shadow-sm"><div class="card-body p-3"><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>แถว</th><th>Row Key</th><th>สาขา/คลัง</th><th>สินค้า</th><th class="text-end">จำนวน</th><th class="text-end">ต้นทุนรวม</th><th>ผลตรวจ</th></tr></thead><tbody>@foreach($batch->staged_rows as $row)<tr><td>{{ $row['row_number'] }}</td><td>{{ $row['normalized']['row_key'] }}</td><td>{{ $row['normalized']['branch_code'] }} / {{ $row['normalized']['warehouse_code'] }}</td><td>{{ $row['normalized']['item_code'] }} · {{ $row['normalized']['uom_code'] }}</td><td class="text-end">{{ $row['normalized']['quantity'] }}</td><td class="text-end">{{ $row['normalized']['total_value'] }}</td><td>@if($row['errors'])<span class="badge text-bg-warning">{{ implode(' | ', $row['errors']) }}</span>@else<span class="badge text-bg-success">ผ่าน</span>@endif</td></tr>@endforeach</tbody></table></div></div></div></div>
@endsection
@push('scripts')
@if(!$batch->error_rows && $batch->status === 'VALIDATED')<script>$('#commit-import').on('click',function(){var b=$(this).prop('disabled',true);$.ajax({url:'{{ route('wms.opening-balances.import.commit',$batch) }}',method:'PUT',headers:{'X-CSRF-TOKEN':'{{ csrf_token() }}',Accept:'application/json'}}).done(function(r){window.location=r.redirect;}).fail(function(x){Swal.fire({icon:'error',text:x.responseJSON?.message||'อนุมัติไม่สำเร็จ'});b.prop('disabled',false);});});</script>@endif
@endpush
