@extends($moduleRoutePrefix === 'purchasing' ? 'Purchasing::layout' : 'Wms::layout')
@section('title', ($requisition->exists ? 'แก้ไข' : 'สร้าง').'ใบขอซื้อ | Purchasing')
@section('content')
@php($moduleRoutePrefix=$moduleRoutePrefix??'wms')
@php($quantityDecimals=\App\Modules\Wms\Support\WmsDecimal::places())
@php($quantityStep=$quantityDecimals>0?'0.'.str_repeat('0',$quantityDecimals-1).'1':'1')
@php($formatQuantity=fn($value)=>\Brick\Math\BigDecimal::of((string)($value===''||$value===null?'0':$value))->toScale($quantityDecimals,\Brick\Math\RoundingMode::HALF_UP)->__toString())
@php($prefillRows=$requisition->exists?$lines->map(fn($l)=>['item_id'=>$l->item_id,'uom_id'=>$l->uom_id,'quantity'=>$l->quantity,'description'=>$l->description])->all():collect($lines??[])->map(fn($l)=>['item_id'=>$l['item_id']??'','uom_id'=>$l['uom_id']??'','quantity'=>$l['quantity']??'1','description'=>$l['description']??''])->all())
@php($rows=old('lines',count($prefillRows)?$prefillRows:[['item_id'=>'','uom_id'=>'','quantity'=>'1','description'=>'']]))
<div class="container-fluid px-3 px-lg-4 py-4">
@php($moduleRoutePrefix=$moduleRoutePrefix??'wms')
@if($requisition->exists && auth()->user()->hasPermission($moduleRoutePrefix.'.purchase-requisitions.print'))<div class="mb-3"><a class="btn btn-sm btn-app-soft" target="_blank" href="{{route($moduleRoutePrefix.'.purchase-requisitions.pdf',$requisition)}}">พิมพ์ PDF</a></div>@endif
<p class="eyebrow mb-2">PURCHASING / REQUISITIONS</p><h1 class="h3 mb-4">{{$requisition->exists?'แก้ไข':'สร้าง'}}ใบขอซื้อ</h1><form id="purchase-requisition-form" method="{{$requisition->exists?'PUT':'POST'}}" action="{{$requisition->exists?route($moduleRoutePrefix.'.purchase-requisitions.update',$requisition):route($moduleRoutePrefix.'.purchase-requisitions.store')}}">@csrf
@if(($prefillSource ?? null) === 'min-max')<div class="alert alert-info border-0 small mb-4"><i class="bx bx-info-circle me-1" aria-hidden="true"></i>รายการนี้มาจากการแจ้งเตือน Min/Max ระบบใส่สินค้าและจำนวนแนะนำให้เท่านั้น กรุณาตรวจสอบ/แก้ไขก่อนกดบันทึก</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="row g-3"><div class="col-md-3"><label class="form-label">วันที่เอกสาร</label><input class="form-control" type="date" name="document_date" value="{{old('document_date',$requisition->document_date?->format('Y-m-d')??today()->toDateString())}}" required><div class="invalid-feedback" data-error-for="document_date"></div></div><div class="col-md-6"><label class="form-label">Supplier (ถ้าทราบ)</label><select class="form-select" id="pr-supplier" name="supplier_id" data-url="{{route($moduleRoutePrefix.'.purchase-requisitions.supplier-options')}}">@if($supplier)<option value="{{$supplier->id}}" selected>{{$supplier->code}} · {{$supplier->name}}</option>@endif</select><div class="invalid-feedback" data-error-for="supplier_id"></div></div><div class="col-12"><label class="form-label">คำอธิบาย/เหตุผลการซื้อ</label><textarea class="form-control" name="description" rows="2">{{old('description',$requisition->description)}}</textarea></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">รายการสินค้า</h2><button class="btn btn-sm btn-app-soft" type="button" id="add-pr-line"><i class="bx bx-plus me-1"></i>เพิ่มบรรทัด</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th style="min-width:260px">สินค้า</th><th style="min-width:180px">หน่วย</th><th style="min-width:150px">จำนวน</th><th style="min-width:260px">รายละเอียด</th><th></th></tr></thead><tbody id="pr-lines">@foreach($rows as $i=>$row)<tr class="pr-line"><td><select class="form-select js-pr-item" name="lines[{{$i}}][item_id]" data-url="{{route($moduleRoutePrefix.'.purchase-requisitions.item-options')}}" required><option value="">ค้นหาสินค้า</option>@if(!empty($row['item_id'])) @php($item=\App\Modules\Wms\Models\Item::find($row['item_id'])) @if($item)<option value="{{$item->id}}" selected>{{$item->code}} · {{$item->name}}</option>@endif @endif</select></td><td><select class="form-select js-pr-uom" name="lines[{{$i}}][uom_id]" data-url="{{route($moduleRoutePrefix.'.purchase-requisitions.uom-options')}}" required><option value="">เลือกหน่วย</option>@if(!empty($row['uom_id'])) @php($uom=\App\Modules\Wms\Models\Uom::find($row['uom_id'])) @if($uom)<option value="{{$uom->id}}" selected>{{$uom->code}} · {{$uom->name}}</option>@endif @endif</select></td><td><input class="form-control text-end" type="number" min="{{$quantityStep}}" step="{{$quantityStep}}" name="lines[{{$i}}][quantity]" value="{{$formatQuantity($row['quantity']??'1')}}" required></td><td><input class="form-control" name="lines[{{$i}}][description]" value="{{$row['description']??''}}"></td><td><button class="btn btn-sm btn-outline-danger js-remove-pr-line" type="button"><i class="bx bx-trash"></i></button></td></tr>@endforeach</tbody></table></div><div class="invalid-feedback d-block" data-error-for="lines"></div><div class="mt-4"><button class="btn btn-dark" type="submit"><i class="bx bx-save me-1"></i>บันทึกร่าง</button><a class="btn btn-outline-secondary" href="{{route($moduleRoutePrefix.'.purchase-requisitions.index')}}">ยกเลิก</a></div></div></div></form>
@if($requisition->exists)
<div class="card border-0 shadow-sm mt-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center"><div><small class="text-secondary d-block">สถานะเอกสาร</small><span class="badge app-status-{{in_array($requisition->status,['APPROVED','SUBMITTED'],true)?'success':($requisition->status==='REJECTED'?'warning':($requisition->status==='VOID'?'danger':'neutral'))}}">{{['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'อนุมัติแล้ว','REJECTED'=>'ตีกลับ','VOID'=>'ยกเลิก'][$requisition->status]??$requisition->status}}</span></div>@if(in_array($requisition->status,['DRAFT','REJECTED'],true) && auth()->user()->hasPermission($moduleRoutePrefix.'.purchase-requisitions.delete'))<button type="button" class="btn btn-outline-danger js-delete-document" data-url="{{route($moduleRoutePrefix.'.purchase-requisitions.destroy',$requisition)}}">ลบใบขอซื้อ</button>@endif</div></div></div>
<div class="card border-0 shadow-sm mt-4"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history ?? [] as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{$event->created_at->format('d/m/Y H:i')}}</div><div><strong>{{$event->action}}</strong><div class="small text-secondary">{{$event->user?->name ?? 'ระบบ'}}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">เหตุผล:</span> {{$event->reason}}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติ</p>@endforelse</div></div>
@endif
</div>
@endsection
@push('scripts')
<script>
$(function(){var l=$('#pr-lines'),itemUrl='{{route($moduleRoutePrefix.'.purchase-requisitions.item-options')}}',uomUrl='{{route($moduleRoutePrefix.'.purchase-requisitions.uom-options')}}',quantityStep=@json($quantityStep),quantityDefault=@json($formatQuantity('1'));function item(s){s.select2({width:'100%',placeholder:'ค้นหาสินค้า',ajax:{url:itemUrl,dataType:'json',delay:250,data:function(p){return{q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});}function uom(s){s.select2({width:'100%',placeholder:'เลือกหน่วย',ajax:{url:uomUrl,dataType:'json',delay:250,data:function(p){return{q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});}$('.js-pr-item').each(function(){item($(this));});$('.js-pr-uom').each(function(){uom($(this));});$('#pr-supplier').select2({width:'100%',allowClear:true,placeholder:'ค้นหา Supplier',ajax:{url:$('#pr-supplier').data('url'),dataType:'json',delay:250,data:function(p){return{q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});function reindex(){l.find('tr').each(function(i){$(this).find('[name]').each(function(){this.name=this.name.replace(/lines\[\d+\]/,'lines['+i+']');});});}$('#add-pr-line').on('click',function(){var i=l.children().length,r=$('<tr class="pr-line"><td><select class="form-select js-pr-item" name="lines['+i+'][item_id]" required><option value="">ค้นหาสินค้า</option></select></td><td><select class="form-select js-pr-uom" name="lines['+i+'][uom_id]" required><option value="">เลือกหน่วย</option></select></td><td><input class="form-control text-end" type="number" min="'+quantityStep+'" step="'+quantityStep+'" name="lines['+i+'][quantity]" value="'+quantityDefault+'" required></td><td><input class="form-control" name="lines['+i+'][description]"></td><td><button class="btn btn-sm btn-outline-danger js-remove-pr-line" type="button"><i class="bx bx-trash"></i></button></td></tr>');l.append(r);item(r.find('.js-pr-item'));uom(r.find('.js-pr-uom'));});l.on('click','.js-remove-pr-line',function(){if(l.children().length>1){$(this).closest('tr').remove();reindex();}});window.erpAjaxForm({form:'#purchase-requisition-form',redirect:true});});
</script>
@endpush
@push('scripts')<script>$(function(){$('.js-delete-document').on('click',function(){var b=$(this);Swal.fire({title:'ลบใบขอซื้อ?',text:'ลบได้เฉพาะเอกสารที่ยังไม่อนุมัติ',icon:'warning',showCancelButton:true,confirmButtonText:'ลบเอกสาร',cancelButtonText:'ยกเลิก'}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.ajax({url:b.data('url'),method:'DELETE',data:{_token:$('meta[name=csrf-token]').attr('content')}}).done(function(v){window.location='{{route($moduleRoutePrefix.'.purchase-requisitions.index')}}';}).fail(function(q){Swal.fire({icon:'error',text:(q.responseJSON||{}).message||'ลบเอกสารไม่สำเร็จ'});b.prop('disabled',false);});});});});</script>@endpush
