@extends($moduleRoutePrefix === 'purchasing' ? 'Purchasing::layout' : 'Wms::layout')
@section('title', 'ใบขอซื้อ | Purchasing')
@section('content')
@php($moduleRoutePrefix=$moduleRoutePrefix??'wms')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><p class="eyebrow mb-2">PURCHASING / REQUISITIONS</p><h1 class="h3 mb-2">ใบขอซื้อ</h1><p class="text-secondary mb-0">เริ่มจากความต้องการซื้อ แล้วส่งอนุมัติก่อนสร้าง PO</p></div>@if(auth()->user()->hasPermission($moduleRoutePrefix.'.purchase-requisitions.create'))<a class="btn btn-dark" href="{{route($moduleRoutePrefix.'.purchase-requisitions.create')}}"><i class="bx bx-plus me-1"></i>สร้างใบขอซื้อ</a>@endif</div>
<div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="purchase-requisitions-table" data-url="{{route($moduleRoutePrefix.'.purchase-requisitions.data')}}"><thead><tr><th>เลขที่</th><th>วันที่</th><th>Supplier</th><th>PO ที่สร้าง</th><th>คำอธิบาย</th><th>สถานะ</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div></div>
@endsection
@push('scripts')
<script>
$(function(){
    var t=$('#purchase-requisitions-table'),x=$.fn.dataTable.render.text();
    $('<div class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">วันที่เอกสาร ตั้งแต่</label><input id="pr-filter-date-from" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">ถึง</label><input id="pr-filter-date-to" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">Supplier</label><select id="pr-filter-supplier" class="form-select" data-url="{{route($moduleRoutePrefix.'.purchase-requisitions.supplier-options')}}"></select></div><div class="col-md-3"><label class="form-label">สถานะ</label><select id="pr-filter-status" class="form-select"><option value="">ทั้งหมด</option><option value="DRAFT">ร่าง</option><option value="SUBMITTED">รออนุมัติ</option><option value="APPROVED">อนุมัติแล้ว</option><option value="REJECTED">ตีกลับ</option><option value="VOID">ยกเลิก</option></select></div><div class="col-md-3"><button id="pr-filter-reset" type="button" class="btn btn-outline-secondary">ล้างตัวกรอง</button></div></div></div></div>').insertBefore(t.closest('.card'));
    window.erpInitSelect2('#pr-filter-supplier',{placeholder:'ค้นหา Supplier',allowClear:true,ajax:{url:$('#pr-filter-supplier').data('url'),delay:250,data:function(p){return{q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});
    var table=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.document_date_from=$('#pr-filter-date-from').val();d.document_date_to=$('#pr-filter-date-to').val();d.supplier_id=$('#pr-filter-supplier').val();d.status=$('#pr-filter-status').val();}},order:[[1,'desc']],buttons:[window.erpExcelButton(t)],columns:[
        {data:'document_number',name:'document_number',render:function(v,z,r){return z==='display'&&r.show_url?'<a href="'+x.display(r.show_url)+'">'+x.display(v)+'</a>':x.display(v);}},
        {data:'document_date_label',name:'document_date',render:x.display},{data:'supplier_label',name:'supplier_id',render:x.display},
        {data:'purchase_order_label',name:'purchase_order_id',render:function(v,z,r){return z==='display'&&r.purchase_order_url?'<a href="'+x.display(r.purchase_order_url)+'">'+x.display(v)+'</a>':x.display(v);}},
        {data:'description',name:'description',defaultContent:'-',render:x.display},
        {data:'status_label',name:'status',render:function(v,z,r){if(z!=='display')return r.status;var c={DRAFT:'app-status-neutral',SUBMITTED:'app-status-warning',APPROVED:'app-status-success',REJECTED:'app-status-danger',VOID:'app-status-neutral'};return '<span class="badge '+(c[r.status]||c.DRAFT)+'">'+x.display(v)+'</span>'; }},
        {data:null,orderable:false,searchable:false,className:'text-end text-nowrap',render:function(v,z,r){if(z!=='display')return '';var a=[];if(r.edit_url)a.push('<a class="btn btn-sm btn-outline-dark" title="แก้ไข" aria-label="แก้ไข" href="'+x.display(r.edit_url)+'"><i class="bx bx-edit"></i></a>');if(r.submit_url)a.push('<button class="btn btn-sm btn-app-soft js-pr-action" title="ส่งอนุมัติ" aria-label="ส่งอนุมัติ" data-url="'+x.display(r.submit_url)+'" data-label="ส่งอนุมัติ"><i class="bx bx-send"></i></button>');if(r.approve_url)a.push('<button class="btn btn-sm btn-app-soft js-pr-action" title="อนุมัติ" aria-label="อนุมัติ" data-url="'+x.display(r.approve_url)+'" data-label="อนุมัติ"><i class="bx bx-check"></i></button>');if(r.reject_url)a.push('<button class="btn btn-sm btn-outline-warning js-pr-action" title="ตีกลับ" aria-label="ตีกลับ" data-url="'+x.display(r.reject_url)+'" data-label="ตีกลับ"><i class="bx bx-undo"></i></button>');if(r.create_po_url)a.push('<a class="btn btn-sm btn-app-soft" title="สร้าง PO" aria-label="สร้าง PO" href="'+x.display(r.create_po_url)+'"><i class="bx bx-cart-add"></i></a>');if(r.void_url)a.push('<button class="btn btn-sm btn-outline-danger js-pr-action" title="ยกเลิก" aria-label="ยกเลิก" data-url="'+x.display(r.void_url)+'" data-label="ยกเลิก"><i class="bx bx-x"></i></button>');if(r.delete_url)a.push('<button class="btn btn-sm btn-outline-danger js-pr-delete" title="ลบเอกสาร" aria-label="ลบเอกสาร" data-url="'+x.display(r.delete_url)+'"><i class="bx bx-trash"></i></button>');return a.join(' ');}}
    ]}));
    t.on('click','.js-pr-action',function(){var b=$(this);if(b.data('busy'))return;var label=b.data('label'),needsReason=label==='ตีกลับ'||label==='ยกเลิก';var opts={icon:'warning',title:label+'ใบขอซื้อ',showCancelButton:true,confirmButtonText:label,cancelButtonText:'ยกเลิก',preConfirm:function(v){if(needsReason&&!$.trim(v||''))return Swal.showValidationMessage('กรุณาระบุเหตุผล');return v||'';}};if(needsReason)opts.input='textarea',opts.inputLabel='เหตุผล';Swal.fire(opts).then(function(r){if(!r.isConfirmed)return;b.data('busy',true).prop('disabled',true);$.post({url:b.data('url'),data:{reason:r.value||''},headers:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}}).done(function(v){Swal.fire({icon:'success',text:v.msg});table.ajax.reload(null,false);}).fail(function(q){var e=q.responseJSON||{};Swal.fire({icon:'error',text:e.message||'ไม่สามารถดำเนินการได้'});}).always(function(){b.data('busy',false).prop('disabled',false);});});});
    t.on('click','.js-pr-delete',function(){var b=$(this);Swal.fire({icon:'warning',title:'ลบใบขอซื้อ?',text:'ลบได้เฉพาะเอกสารที่ยังไม่อนุมัติ',showCancelButton:true,confirmButtonText:'ลบเอกสาร',cancelButtonText:'ยกเลิก'}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.ajax({url:b.data('url'),method:'DELETE',data:{_token:$('meta[name="csrf-token"]').attr('content')}}).done(function(v){Swal.fire({icon:'success',text:v.msg});table.ajax.reload(null,false);}).fail(function(q){Swal.fire({icon:'error',text:(q.responseJSON||{}).message||'ลบเอกสารไม่สำเร็จ'});}).always(function(){b.prop('disabled',false);});});});
    $('#pr-filter-date-from,#pr-filter-date-to,#pr-filter-status').on('change',function(){table.ajax.reload();});
    $('#pr-filter-supplier').on('change',function(){table.ajax.reload();});
    $('#pr-filter-reset').on('click',function(){$('#pr-filter-date-from,#pr-filter-date-to,#pr-filter-status').val('');$('#pr-filter-supplier').val(null).trigger('change');table.ajax.reload();});
});
    table.on('draw',function(){table.rows({page:'current'}).every(function(){var r=this.data(),$cell=$(this.node()).find('td:last');if(r.print_url&&!$cell.find('.js-pdf-print').length)$cell.prepend('<a class="btn btn-sm btn-app-soft js-pdf-print" target="_blank" title="พิมพ์ PDF" aria-label="พิมพ์ PDF" href="'+x.display(r.print_url)+'"><i class="bx bx-printer"></i></a> ');});});
</script>
@endpush
