@extends('Purchasing::layout')
@section('title', $requisition->document_number.' | ใบขอซื้อ')
@section('content')
@php($labels=['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'อนุมัติแล้ว','REJECTED'=>'ตีกลับ','VOID'=>'ยกเลิก'])
@php($classes=['DRAFT'=>'neutral','SUBMITTED'=>'warning','APPROVED'=>'success','REJECTED'=>'danger','VOID'=>'danger'])
@php($canEdit=in_array($requisition->status,['DRAFT','REJECTED'],true)&&auth()->user()->hasPermission('purchasing.purchase-requisitions.update'))
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">PURCHASING / REQUISITIONS</p><h1 class="h3 mb-2">{{ $requisition->document_number }}</h1><span class="badge app-status-{{ $classes[$requisition->status] ?? 'neutral' }}">{{ $labels[$requisition->status] ?? $requisition->status }}</span></div>
        <div class="d-flex flex-wrap gap-2">
            <a class="btn btn-outline-secondary" href="{{ route('purchasing.purchase-requisitions.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a>
            @if($canEdit)<a class="btn btn-app-soft" href="{{ route('purchasing.purchase-requisitions.edit',$requisition) }}"><i class="bx bx-edit me-1" aria-hidden="true"></i>แก้ไข</a>@endif
            @if(auth()->user()->hasPermission('purchasing.purchase-requisitions.print'))<a class="btn btn-app-soft" target="_blank" href="{{ route('purchasing.purchase-requisitions.pdf',$requisition) }}"><i class="bx bx-printer me-1" aria-hidden="true"></i>พิมพ์</a>@endif
            @if(in_array($requisition->status,['DRAFT','REJECTED'],true)&&auth()->user()->hasPermission('purchasing.purchase-requisitions.submit'))<button class="btn btn-app-primary js-pr-action" data-action="submit" data-url="{{ route('purchasing.purchase-requisitions.submit',$requisition) }}"><i class="bx bx-send me-1" aria-hidden="true"></i>ส่งอนุมัติ</button>@endif
            @if($requisition->status==='SUBMITTED'&&auth()->user()->hasPermission('purchasing.purchase-requisitions.approve'))<button class="btn btn-app-primary js-pr-action" data-action="approve" data-url="{{ route('purchasing.purchase-requisitions.approve',$requisition) }}"><i class="bx bx-check me-1" aria-hidden="true"></i>อนุมัติ</button>@endif
            @if($requisition->status==='APPROVED'&&!$requisition->purchaseOrder&&auth()->user()->hasPermission('purchasing.purchase-requisitions.create-po')&&auth()->user()->hasPermission('purchasing.purchase-orders.create'))<a class="btn btn-app-primary" href="{{ route('purchasing.purchase-orders.create',['purchase_requisition_id'=>$requisition->id]) }}"><i class="bx bx-cart-add me-1" aria-hidden="true"></i>สร้าง PO</a>@endif
            @if($requisition->status==='SUBMITTED'&&auth()->user()->hasPermission('purchasing.purchase-requisitions.reject'))<button class="btn btn-app-danger js-pr-action" data-action="reject" data-url="{{ route('purchasing.purchase-requisitions.reject',$requisition) }}"><i class="bx bx-undo me-1" aria-hidden="true"></i>ตีกลับ</button>@endif
            @if($requisition->status!=='VOID'&&!$requisition->purchaseOrder&&auth()->user()->hasPermission('purchasing.purchase-requisitions.void'))<button class="btn btn-app-danger js-pr-action" data-action="void" data-url="{{ route('purchasing.purchase-requisitions.void',$requisition) }}"><i class="bx bx-x-circle me-1" aria-hidden="true"></i>ยกเลิกเอกสาร</button>@endif
            @if($canEdit&&auth()->user()->hasPermission('purchasing.purchase-requisitions.delete'))<button class="btn btn-app-danger js-pr-delete" data-url="{{ route('purchasing.purchase-requisitions.destroy',$requisition) }}"><i class="bx bx-trash me-1" aria-hidden="true"></i>ลบร่าง</button>@endif
        </div>
    </div>
    <div class="alert alert-info border-0 mb-4"><strong>ขั้นตอนถัดไป:</strong> {{ in_array($requisition->status,['DRAFT','REJECTED'],true)?'ตรวจสอบรายการแล้วกด “ส่งอนุมัติ”':($requisition->status==='SUBMITTED'?'รอผู้มีสิทธิ์กด “อนุมัติ”':($requisition->status==='APPROVED'&&!$requisition->purchaseOrder?'พร้อมสร้าง PO':'เอกสารนี้ไม่มีขั้นตอนที่ต้องดำเนินการต่อ')) }}</div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-3"><small class="text-secondary">วันที่เอกสาร</small><div class="fw-semibold">{{ $requisition->document_date?->format('d/m/Y') }}</div></div><div class="col-md-4"><small class="text-secondary">Supplier</small><div class="fw-semibold">{{ $requisition->supplier?->code ? $requisition->supplier->code.' · '.$requisition->supplier->name : '-' }}</div></div><div class="col-md-5"><small class="text-secondary">คำอธิบาย</small><div class="fw-semibold">{{ $requisition->description ?: '-' }}</div></div></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">รายการสินค้า</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>สินค้า</th><th>หน่วย</th><th class="text-end">จำนวน</th><th>รายละเอียด</th></tr></thead><tbody>@foreach($requisition->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->item?->code }} · {{ $line->item?->name }}</td><td>{{ $line->uom?->code }}</td><td class="text-end">{{ $line->quantity }}</td><td>{{ $line->description ?: '-' }}</td></tr>@endforeach</tbody></table></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="border-bottom py-2"><strong>{{ $event->action }}</strong><small class="text-secondary ms-2">{{ $event->created_at?->format('d/m/Y H:i') }} · {{ $event->user?->name ?? '-' }}</small></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){$('.js-pr-action').on('click',function(){var button=$(this),action=button.data('action'),needsReason=['reject','void'].includes(action),labels={submit:'ส่งอนุมัติ',approve:'อนุมัติ',reject:'ตีกลับ',void:'ยกเลิกเอกสาร'};Swal.fire({icon:'warning',title:labels[action]+'ใบขอซื้อ?',input:needsReason?'textarea':undefined,inputLabel:needsReason?'เหตุผล':undefined,showCancelButton:true,confirmButtonText:labels[action],cancelButtonText:'กลับ',preConfirm:function(value){if(needsReason&&!$.trim(value||'')){Swal.showValidationMessage('กรุณาระบุเหตุผล');return false;}return value||'';}}).then(function(result){if(!result.isConfirmed)return;button.prop('disabled',true);$.post(button.data('url'),{_token:$('meta[name=csrf-token]').attr('content'),reason:result.value||''}).done(function(response){Swal.fire({icon:'success',text:response.msg,timer:1200,showConfirmButton:false}).then(function(){location.reload();});}).fail(function(xhr){button.prop('disabled',false);Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ดำเนินการไม่สำเร็จ'});});});});window.erpAjaxDelete({button:'.js-pr-delete',redirect:'{{ route('purchasing.purchase-requisitions.index') }}',title:'ลบร่างใบขอซื้อ?',text:'เอกสารร่างจะถูกลบและไม่สามารถกู้คืนได้',confirmButtonText:'ลบร่าง',cancelButtonText:'กลับ'});});</script>
@endpush
