@extends('Finance::layout')
@php($isAdvance = $instrumentType === 'ADVANCE')
@php($isDeposit = $instrumentType === 'DEPOSIT')
@section('title', ($isAdvance ? 'เงินล่วงหน้า' : ($isDeposit ? 'เงินมัดจำ' : 'เงินล่วงหน้า / เงินมัดจำ')).' | Finance')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><p class="eyebrow mb-2">FINANCE / ADVANCE & DEPOSIT</p><h1 class="h3 mb-2">{{ $isAdvance ? 'เงินล่วงหน้า' : ($isDeposit ? 'เงินมัดจำ' : 'เงินล่วงหน้า / เงินมัดจำ') }}</h1><p class="text-secondary mb-4">ดูรายการที่มาจาก Settlement ที่ลงบัญชีแล้ว และนำไปตัดกับเอกสารของคู่ค้า</p><div class="alert alert-warning">การสร้างรายการเริ่มจาก Settlement ที่ลงบัญชีแล้ว ระบบจะเชื่อม Journal ให้อัตโนมัติ</div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h6 mb-3">ตัวกรอง</h2><div class="row g-3"><div class="col-12 col-md-3"><label class="form-label" for="advance-filter-status">สถานะ</label><select class="form-select" id="advance-filter-status"><option value="">ทั้งหมด</option><option value="POSTED">ลงบัญชีแล้ว</option><option value="PARTIAL">ตัดบางส่วน</option><option value="APPLIED">ตัดครบแล้ว</option><option value="REVERSED">กลับรายการแล้ว</option><option value="VOID">ยกเลิก</option></select></div><div class="col-12 col-md-3"><label class="form-label" for="advance-filter-direction">ทิศทาง</label><select class="form-select" id="advance-filter-direction"><option value="">ทั้งหมด</option><option value="RECEIPT">รับล่วงหน้า</option><option value="PAYMENT">จ่ายล่วงหน้า</option></select></div><div class="col-12 col-md-3"><label class="form-label" for="advance-filter-from">วันที่ Post ตั้งแต่</label><input class="form-control" id="advance-filter-from" type="date"></div><div class="col-12 col-md-3"><label class="form-label" for="advance-filter-to">วันที่ Post ถึง</label><input class="form-control" id="advance-filter-to" type="date"></div><div class="col-12 col-md-3"><label class="form-label" for="advance-filter-min">ยอดตั้งต้นขั้นต่ำ</label><input class="form-control" id="advance-filter-min" type="number" min="0" step="0.01"></div><div class="col-12 col-md-3"><label class="form-label" for="advance-filter-max">ยอดตั้งต้นสูงสุด</label><input class="form-control" id="advance-filter-max" type="number" min="0" step="0.01"></div><div class="col-12 d-flex justify-content-end"><button class="btn btn-outline-secondary" id="advance-filter-reset" type="button">ล้างตัวกรอง</button></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h6 mb-3">รายการ{{ $isAdvance ? 'เงินล่วงหน้า' : ($isDeposit ? 'เงินมัดจำ' : 'เงินล่วงหน้า / เงินมัดจำ') }}</h2><div class="table-responsive"><table id="advance-deposits-table" class="table table-hover align-middle w-100" data-url="{{ route($isAdvance ? 'finance.advances.data' : ($isDeposit ? 'finance.deposits.data' : 'finance.advance-deposits.data')) }}"><thead><tr><th>เลขที่</th><th>ประเภท</th><th>ทิศทาง</th><th>คู่ค้า</th><th>วันที่ Post</th><th class="text-end">ยอดตั้งต้น</th><th class="text-end">ตัดแล้ว</th><th class="text-end">คงเหลือ</th><th>สถานะ</th><th>จัดการ</th></tr></thead></table></div></div></div></div>
@endsection
@push('scripts')
<script>$(function(){var t=$('#advance-deposits-table'),x=$.fn.dataTable.render.text(),dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.status=$('#advance-filter-status').val();d.direction=$('#advance-filter-direction').val();d.date_from=$('#advance-filter-from').val();d.date_to=$('#advance-filter-to').val();d.amount_min=$('#advance-filter-min').val();d.amount_max=$('#advance-filter-max').val();}},order:[[4,'desc']],buttons:[window.erpExcelButton(t)],columns:[{data:'document_number',render:x.display},{data:'instrument_label',render:x.display},{data:'direction_label',render:x.display},{data:'party_label',render:x.display},{data:'posting_date_label',render:x.display},{data:'original_amount',className:'text-end',render:$.fn.dataTable.render.number(',','.',2)},{data:'applied_amount',className:'text-end',render:$.fn.dataTable.render.number(',','.',2)},{data:null,className:'text-end',render:function(v,z,r){var n=(parseFloat(r.original_amount)||0)-(parseFloat(r.applied_amount)||0);return z==='display'?n.toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2}):n;}},{data:'status_label',render:function(v,z,r){return z==='display'?'<span class="badge '+x.display(r.status_class||'app-status-neutral')+'">'+x.display(v)+'</span>':v;}},{data:null,orderable:false,searchable:false,className:'text-end text-nowrap',render:function(v,z,r){if(z!=='display')return '';var h='<a class="btn btn-sm btn-app-soft" href="'+x.display(r.show_url)+'" title="ดูรายละเอียด"><i class="bx bx-show"></i></a>';if(r.apply_url)h+=' <a class="btn btn-sm btn-app-soft" href="'+x.display(r.apply_url)+'" title="ตัดกับเอกสาร"><i class="bx bx-link"></i></a>';return h;}}]}));$('#advance-filter-status,#advance-filter-direction,#advance-filter-from,#advance-filter-to').on('change',function(){dt.ajax.reload();});$('#advance-filter-min,#advance-filter-max').on('keyup',function(e){if(e.key==='Enter')dt.ajax.reload();});$('#advance-filter-reset').on('click',function(){$('#advance-filter-status,#advance-filter-direction').val('');$('#advance-filter-from,#advance-filter-to,#advance-filter-min,#advance-filter-max').val('');dt.ajax.reload();});});</script>
@endpush
