@extends('Finance::layout')

@section('title', $advance->document_number.' | Finance')

@section('content')
    @php
        $statusLabels = ['POSTED' => 'ลงบัญชีแล้ว', 'PARTIAL' => 'ตัดบางส่วน', 'APPLIED' => 'ตัดครบแล้ว', 'REVERSED' => 'กลับรายการแล้ว', 'VOID' => 'ยกเลิก'];
        $statusClasses = ['POSTED' => 'app-status-success', 'PARTIAL' => 'app-status-info', 'APPLIED' => 'app-status-neutral', 'REVERSED' => 'app-status-danger', 'VOID' => 'app-status-danger'];
        $remaining = (float) $advance->original_amount - (float) $advance->applied_amount;
    @endphp
    <div class="container-fluid px-3 px-lg-4 py-4">
        <p class="eyebrow mb-2">FINANCE / ADVANCE & DEPOSIT</p>
        <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4">
            <div><h1 class="h3 mb-2">{{ $advance->document_number }}</h1><div class="text-secondary">{{ $advance->party?->code ?? '—' }} · {{ $advance->party?->name ?? '—' }}</div></div>
            <div class="d-flex gap-2"><span class="badge {{ $statusClasses[$advance->status] ?? 'app-status-neutral' }}">{{ $statusLabels[$advance->status] ?? $advance->status }}</span>@if(in_array($advance->status, ['POSTED', 'PARTIAL'], true) && auth()->user()->hasPermission('finance.advance-deposits.apply'))<a class="btn btn-app-soft" href="{{ route('finance.advance-deposits.applications.create', $advance) }}" title="ตัดกับเอกสาร" aria-label="ตัดกับเอกสาร"><i class="bx bx-link" aria-hidden="true"></i></a>@endif<a class="btn btn-outline-secondary" href="{{ route('finance.advance-deposits.index') }}">กลับ</a></div>
        </div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="alert alert-info border-0">รายการนี้สร้างจาก Settlement ที่ลงบัญชีแล้ว ระบบจะไม่สร้าง Journal ซ้ำเมื่อมีการตัดเงินล่วงหน้า/เงินมัดจำ</div><div class="row g-3"><div class="col-md-3"><div class="small text-secondary">ประเภท</div>{{ $advance->instrument_type === 'DEPOSIT' ? 'เงินมัดจำ' : 'เงินล่วงหน้า' }} · {{ $advance->direction === 'RECEIPT' ? 'รับล่วงหน้า' : 'จ่ายล่วงหน้า' }}</div><div class="col-md-3"><div class="small text-secondary">วันที่ Post</div>{{ $advance->posting_date?->format($dateFormat) ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">เอกสารต้นทาง</div>{{ $advance->sourceSettlement?->document_number ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">Journal</div>{{ $advance->journalEntry?->entry_number ?? '—' }}</div><div class="col-md-4"><div class="small text-secondary">ยอดตั้งต้น</div><strong>{{ number_format((float) $advance->original_amount, 2) }}</strong></div><div class="col-md-4"><div class="small text-secondary">ตัดแล้ว</div><strong>{{ number_format((float) $advance->applied_amount, 2) }}</strong></div><div class="col-md-4"><div class="small text-secondary">คงเหลือ</div><strong>{{ number_format($remaining, 2) }}</strong></div></div></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">รายการตัดเงินล่วงหน้า / เงินมัดจำ</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>วันที่ตัด</th><th>เอกสารปลายทาง</th><th class="text-end">จำนวนเงิน</th><th>Journal</th><th>สถานะ</th></tr></thead><tbody>@forelse($advance->applications as $application)<tr><td>{{ $application->application_date?->format($dateFormat) ?? '—' }}</td><td>{{ $application->openItem?->document_number ?? '—' }}</td><td class="text-end">{{ number_format((float) $application->amount, 2) }}</td><td>{{ $application->journalEntry?->entry_number ?? '—' }}</td><td><span class="badge {{ $application->reversed_at ? 'app-status-danger' : 'app-status-success' }}">{{ $application->reversed_at ? 'กลับรายการแล้ว' : 'ใช้งานอยู่' }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary">ยังไม่มีรายการตัด</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{ $event->created_at->format('d/m/Y H:i') }}</div><div><strong>{{ $event->action }}</strong><div class="small text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">รายละเอียด:</span> {{ $event->reason }}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติ</p>@endforelse</div></div>
    </div>
@endsection
