@extends('Finance::layout')
@section('title', $commissionRequest->document_number.' | ใบขอจ่ายคอมมิชชั่น')
@section('content')
@php($requestLabels = ['DRAFT' => 'ร่าง', 'SUBMITTED' => 'รออนุมัติ', 'APPROVED' => 'อนุมัติแล้ว', 'CANCELLED' => 'ยกเลิก'])
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">FINANCE / COMMISSION REQUESTS</p>
    <h1 class="h3 mb-2">{{ $commissionRequest->document_number }}</h1>
    <p class="text-secondary mb-4">ใบขอจ่ายคอมมิชชั่น · ชุด {{ $commissionRequest->paymentBatch->document_number }}</p>
    <div class="d-flex justify-content-end gap-2 mb-3">
        <a class="btn btn-outline-secondary" href="{{ route('finance.commission-payouts.show', $commissionRequest->paymentBatch) }}">ย้อนกลับ</a>
        @if($commissionRequest->status === 'DRAFT')
            <button class="btn btn-dark js-action" data-url="{{ route('finance.commission-requests.submit', $commissionRequest) }}">ส่งอนุมัติ</button>
        @elseif($commissionRequest->status === 'SUBMITTED')
            <button class="btn btn-primary js-action" data-url="{{ route('finance.commission-requests.approve', $commissionRequest) }}">อนุมัติ</button>
        @elseif($commissionRequest->status === 'APPROVED' && ! $commissionRequest->voucher && auth()->user()->hasPermission('finance.payment-vouchers.create'))
            <a class="btn btn-dark" href="{{ route('finance.payment-vouchers.create', ['commission_request_id' => $commissionRequest->id]) }}">สร้างใบสำคัญจ่าย</a>
        @endif
        @if(in_array($commissionRequest->status, ['DRAFT', 'SUBMITTED', 'APPROVED'], true) && auth()->user()->hasPermission('finance.commission-payouts.void'))
            <button class="btn btn-outline-danger js-cancel-request" data-url="{{ route('finance.commission-requests.cancel', $commissionRequest) }}" @disabled($commissionRequest->voucher && $commissionRequest->voucher->status !== 'VOID') title="{{ $commissionRequest->voucher && $commissionRequest->voucher->status !== 'VOID' ? 'ต้องยกเลิกใบสำคัญจ่ายก่อน' : '' }}">ยกเลิกเอกสาร</button>
        @endif
    </div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-4"><div class="small text-secondary">พนักงาน</div><strong>{{ $commissionRequest->recipient->name }}</strong></div><div class="col-md-4"><div class="small text-secondary">Supplier</div><strong>{{ $commissionRequest->supplier->code }} · {{ $commissionRequest->supplier->name }}</strong></div><div class="col-md-4 text-md-end"><div class="small text-secondary">ยอดขอจ่าย</div><strong class="h4">{{ number_format((float) $commissionRequest->amount, 2) }}</strong></div></div><hr><span class="badge {{ $commissionRequest->status === 'CANCELLED' ? 'app-status-danger' : ($commissionRequest->status === 'APPROVED' ? 'app-badge-success' : ($commissionRequest->status === 'SUBMITTED' ? 'app-badge-info' : 'app-badge-soft')) }}">{{ $requestLabels[$commissionRequest->status] ?? $commissionRequest->status }}</span></div></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><h2 class="h6 mb-3">สถานะการจ่าย</h2>@if(! $commissionRequest->voucher)<div class="d-flex align-items-center gap-2"><span class="badge {{ $commissionRequest->status === 'CANCELLED' ? 'app-status-danger' : 'app-status-info' }}">{{ $commissionRequest->status === 'CANCELLED' ? 'ไม่จ่าย (ยกเลิกใบขอจ่ายแล้ว)' : 'รอสร้างใบสำคัญจ่าย' }}</span></div>@else<div class="row g-3 align-items-center"><div class="col-md-5"><div class="small text-secondary">ใบสำคัญจ่าย</div><a class="fw-semibold" href="{{ route('finance.payment-vouchers.show', $commissionRequest->voucher) }}">{{ $commissionRequest->voucher->document_number }}</a></div><div class="col-md-4"><div class="small text-secondary">สถานะใบสำคัญจ่าย</div><span class="badge {{ $commissionRequest->voucher->status === 'VOID' ? 'app-status-danger' : ($commissionRequest->voucher->status === 'APPROVED' ? 'app-status-success' : 'app-status-info') }}">{{ ['DRAFT' => 'ร่าง', 'SUBMITTED' => 'รออนุมัติ', 'APPROVED' => 'อนุมัติแล้ว', 'VOID' => 'ยกเลิก'][$commissionRequest->voucher->status] ?? $commissionRequest->voucher->status }}</span></div><div class="col-md-3 text-md-end"><div class="small text-secondary">ผลการจ่าย</div><span class="badge {{ $commissionRequest->voucher->status === 'VOID' ? 'app-status-danger' : ($commissionRequest->voucher->settlement?->status === 'POSTED' ? 'app-status-success' : 'app-status-info') }}">{{ $commissionRequest->voucher->status === 'VOID' ? 'ไม่จ่าย (ยกเลิกแล้ว)' : ($commissionRequest->voucher->settlement?->status === 'POSTED' ? 'จ่ายแล้ว' : 'อยู่ระหว่างจ่าย') }}</span></div></div>@endif</div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h6 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{ $event->created_at?->format('d/m/Y H:i') }}</div><div><strong>{{ $event->action }}</strong><div class="small text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">เหตุผล:</span> {{ $event->reason }}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติเอกสาร</p>@endforelse</div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){$('.js-action').click(function(){const b=$(this);$.ajax({url:b.data('url'),method:'POST',headers:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content'),Accept:'application/json'}}).done(x=>location.href=x.redirect).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถทำรายการได้'}));});$('.js-cancel-request').click(function(){const b=$(this);Swal.fire({icon:'warning',title:'ยกเลิกเอกสาร?',input:'text',inputPlaceholder:'ระบุเหตุผล',inputValidator:v=>!v?'กรุณาระบุเหตุผล':undefined,showCancelButton:true,confirmButtonText:'ยกเลิกเอกสาร',cancelButtonText:'ย้อนกลับ'}).then(r=>{if(r.isConfirmed)$.post(b.data('url'),{reason:r.value,_token:$('meta[name="csrf-token"]').attr('content')},x=>location.href=x.redirect).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถยกเลิกใบขอจ่ายได้'}));});});});</script>
@endpush
