@extends('Purchasing::layout')
@section('title', 'สร้าง Landed Cost | Purchasing')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="mb-4"><p class="eyebrow mb-2">PURCHASING / LANDED COST</p><h1 class="h3 mb-2">สร้าง Landed Cost</h1><p class="text-secondary mb-0">เลือก Goods Receipt ที่ลง Stock แล้ว และระบุต้นทุนที่ต้องการกระจาย</p></div>
<form id="landed-cost-form" method="post" action="{{ route('purchasing.landed-costs.store') }}">@csrf
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">ข้อมูลเอกสาร</h2><div class="row g-3"><div class="col-12 col-md-4"><label class="form-label" for="business-date">วันที่เอกสาร</label><input id="business-date" class="form-control" type="date" name="business_date" value="{{ today()->toDateString() }}" required></div><div class="col-12 col-md-4"><label class="form-label" for="allocation-basis">วิธีกระจายต้นทุน</label><select id="allocation-basis" class="form-select" name="allocation_basis" required><option value="VALUE">ตามมูลค่า</option><option value="QUANTITY">ตามจำนวน</option><option value="WEIGHT">ตามน้ำหนัก</option></select><div class="form-text">เลือกฐานที่เหมาะกับลักษณะของค่าใช้จ่าย</div></div><div class="col-12 col-md-4"><label class="form-label">เลขที่เอกสาร</label><div class="form-control bg-light text-secondary"><i class="bx bx-hash me-1" aria-hidden="true"></i>ระบบจะรันเลขอัตโนมัติ</div><div class="form-text">ใช้รูปแบบจาก Global Setting / Document Sequences</div></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">Goods Receipt ต้นทาง</h2><p class="text-secondary small mb-0">เลือกอย่างน้อย 1 รายการที่รับเข้าและลง Stock แล้ว</p></div><span class="badge app-status-info">{{ $receipts->count() }} รายการพร้อมใช้</span></div>@if($receipts->isEmpty())<div class="alert alert-warning border-0 mb-3"><i class="bx bx-info-circle me-1" aria-hidden="true"></i>ยังไม่มี Goods Receipt ที่ลง Stock แล้ว จึงยังสร้าง Landed Cost ไม่ได้</div>@endif<div class="row g-2">@foreach($receipts as $receipt)<div class="col-12 col-md-6 col-xl-4"><label class="border rounded p-3 d-flex gap-2 h-100"><input type="checkbox" name="receipt_ids[]" value="{{ $receipt->id }}" class="form-check-input mt-1" required><span><strong class="d-block">{{ $receipt->receipt_number }}</strong><small class="text-secondary">{{ $receipt->supplier?->name ?? '-' }} · {{ $receipt->business_date?->format('d/m/Y') }}</small></span></label></div>@endforeach</div>@if($pendingReceipts->isNotEmpty())<div class="alert alert-info border-0 mt-3 mb-0"><div class="d-flex gap-2"><i class="bx bx-time-five fs-5" aria-hidden="true"></i><div><strong>{{ $pendingReceipts->count() }} Goods Receipt รอ Post เข้า Stock</strong><div class="small mt-1">{{ $pendingReceipts->pluck('receipt_number')->take(5)->join(', ') }}{{ $pendingReceipts->count() > 5 ? ' และรายการอื่น ๆ' : '' }}</div>@if(auth()->user()->hasPermission('purchasing.purchase-receipts.view'))<a class="btn btn-sm btn-app-soft mt-2" href="{{ route('purchasing.purchase-receipts.index') }}">ไปหน้า Goods Receipt</a>@endif</div></div></div>@endif</div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">รายการค่าใช้จ่าย</h2><p class="text-secondary small mb-0">ค่าใช้จ่ายทั้งหมดจะถูกกระจายไปยังสินค้าที่เลือก</p></div><button type="button" class="btn btn-app-soft btn-sm" id="add-expense-line"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มรายการ</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th style="min-width:280px">บัญชีค่าใช้จ่าย</th><th style="min-width:160px" class="text-end">จำนวนเงิน</th><th style="min-width:240px">รายละเอียด</th><th></th></tr></thead><tbody id="expense-lines"></tbody></table></div><div class="d-flex flex-wrap gap-2 mt-4"><button class="btn btn-dark" type="submit"><i class="bx bx-save me-1" aria-hidden="true"></i>บันทึกร่าง</button><a class="btn btn-outline-secondary" href="{{ route('purchasing.landed-costs.index') }}">ยกเลิก</a></div></div></div>
</form></div>
@endsection
@push('scripts')<script>$(function(){let i=0;const options=@json($accounts->map(fn($a)=>['id'=>$a->id,'label'=>$a->code.' · '.$a->name])->values());function addLine(){const n=i++;let select='<select class="form-select" name="lines['+n+'][account_id]" required><option value="">เลือกบัญชีค่าใช้จ่าย</option>'+options.map(o=>'<option value="'+o.id+'">'+$('<div>').text(o.label).html()+'</option>').join('')+'</select>';$('#expense-lines').append('<tr><td>'+select+'</td><td><input class="form-control text-end" name="lines['+n+'][amount]" type="number" min="0.01" step="0.00000001" placeholder="0.00" required></td><td><input class="form-control" name="lines['+n+'][description]" maxlength="500" placeholder="เช่น ค่าขนส่ง"></td><td class="text-end"><button type="button" class="btn btn-outline-danger js-remove-line" title="ลบรายการ" aria-label="ลบรายการ"><i class="bx bx-trash" aria-hidden="true"></i></button></td></tr>');}addLine();$('#add-expense-line').on('click',addLine);$(document).on('click','.js-remove-line',function(){if($('#expense-lines tr').length>1)$(this).closest('tr').remove();});window.erpAjaxForm({form:'#landed-cost-form',redirect:true});});</script>@endpush
