@extends('Purchasing::layout')
@section('title', $document->document_number.' | Landed Cost')
@section('content')
@php($statusLabels=['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','VOID'=>'ยกเลิก'])
@php($statusClasses=['DRAFT'=>'neutral','SUBMITTED'=>'warning','APPROVED'=>'info','POSTED'=>'success','VOID'=>'danger'])
@php($basisLabels=['VALUE'=>'ตามมูลค่า','QUANTITY'=>'ตามจำนวน','WEIGHT'=>'ตามน้ำหนัก'])
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><p class="eyebrow mb-2">PURCHASING / LANDED COST</p><h1 class="h3 mb-2">{{ $document->document_number }}</h1><div class="d-flex flex-wrap gap-2"><span class="badge app-status-{{ $statusClasses[$document->status] ?? 'neutral' }}">{{ $statusLabels[$document->status] ?? $document->status }}</span><span class="badge app-status-neutral">{{ $basisLabels[$document->allocation_basis] ?? $document->allocation_basis }}</span></div></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="{{ route('purchasing.landed-costs.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับรายการ</a>@if($document->status==='DRAFT' && auth()->user()->hasPermission('purchasing.landed-costs.submit'))<button type="button" class="btn btn-app-soft js-action" data-url="{{ route('purchasing.landed-costs.submit',$document) }}" data-title="ส่ง Landed Cost เพื่ออนุมัติ?" data-confirm="ส่งอนุมัติ">ส่งอนุมัติ</button>@elseif($document->status==='SUBMITTED' && auth()->user()->hasPermission('purchasing.landed-costs.approve'))<button type="button" class="btn btn-app-soft js-action" data-url="{{ route('purchasing.landed-costs.approve',$document) }}" data-title="อนุมัติ Landed Cost?" data-confirm="อนุมัติ">อนุมัติ</button>@elseif($document->status==='APPROVED' && auth()->user()->hasPermission('purchasing.landed-costs.post'))<button type="button" class="btn btn-app-primary js-action" data-url="{{ route('purchasing.landed-costs.post',$document) }}" data-title="Post Landed Cost?" data-confirm="Post">Post</button>@endif @if(in_array($document->status,['DRAFT','SUBMITTED','APPROVED'],true) && auth()->user()->hasPermission('purchasing.landed-costs.void'))<button type="button" class="btn btn-outline-danger js-action" data-url="{{ route('purchasing.landed-costs.void',$document) }}" data-title="ยกเลิกเอกสาร?" data-confirm="ยกเลิก">ยกเลิก</button>@endif</div></div>
<div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-secondary d-block">วันที่เอกสาร</small><strong>{{ $document->business_date?->format('d/m/Y') }}</strong></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-secondary d-block">ยอดต้นทุนรวม</small><strong class="fs-5">{{ number_format((float)$document->total_amount,2) }}</strong></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-secondary d-block">Goods Receipt</small><strong>{{ $document->receipts->count() }} รายการ</strong></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-secondary d-block">Allocation</small><strong>{{ $document->allocations->count() }} รายการ</strong></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">ค่าใช้จ่าย</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>บัญชี</th><th>รายละเอียด</th><th class="text-end">จำนวนเงิน</th></tr></thead><tbody>@foreach($document->lines as $line)<tr><td>{{ $line->account?->code }} · {{ $line->account?->name }}</td><td>{{ $line->description ?: '-' }}</td><td class="text-end">{{ number_format((float)$line->amount,2) }}</td></tr>@endforeach</tbody><tfoot class="fw-semibold"><tr><td colspan="2" class="text-end">รวม</td><td class="text-end">{{ number_format((float)$document->total_amount,2) }}</td></tr></tfoot></table></div></div></div>
<div class="row g-3"><div class="col-12 col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Goods Receipt ที่อ้างอิง</h2>@foreach($document->receipts as $receipt)<div class="d-flex justify-content-between gap-3 border-bottom py-2"><span><strong class="d-block">{{ $receipt->goodsReceipt?->receipt_number ?: '-' }}</strong><small class="text-secondary">มูลค่าฐาน {{ number_format((float)$receipt->selected_value,2) }}</small></span><strong>{{ number_format((float)$receipt->allocated_amount,2) }}</strong></div>@endforeach</div></div></div><div class="col-12 col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">ผลการกระจายต้นทุน</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>สินค้า</th><th>หน่วย</th><th class="text-end">สัดส่วน</th><th class="text-end">ต้นทุนที่เพิ่ม</th></tr></thead><tbody>@forelse($document->allocations as $allocation)<tr><td>{{ $allocation->item?->code }}<small class="text-secondary d-block">{{ $allocation->item?->name }}</small></td><td>{{ $allocation->uom?->code ?: '-' }}</td><td class="text-end">{{ number_format((float)$allocation->allocation_ratio*100,2) }}%</td><td class="text-end">{{ number_format((float)$allocation->allocated_amount,2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">ยังไม่มี allocation — จะสร้างเมื่อ Post เอกสาร</td></tr>@endforelse</tbody></table></div></div></div></div></div></div>
@endsection
@push('scripts')<script>$(function(){$('.js-action').on('click',function(){const b=$(this);Swal.fire({icon:'warning',title:b.data('title'),showCancelButton:true,confirmButtonText:b.data('confirm'),cancelButtonText:'กลับ'}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.post(b.data('url'),{_token:$('meta[name=csrf-token]').attr('content')}).done(function(r){Swal.fire({icon:'success',text:r.msg||'ดำเนินการแล้ว',timer:1200,showConfirmButton:false}).then(function(){location.reload();});}).fail(function(x){b.prop('disabled',false);Swal.fire({icon:'error',text:x.responseJSON?.message||'ดำเนินการไม่สำเร็จ'});});});});});</script>@endpush
