@extends('Crm::layout')
@section('title', 'งานของทีม | CRM')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page module-dashboard module-dashboard--crm">
<div class="module-dashboard-hero d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4 crm-page-header"><div><p class="module-dashboard-kicker mb-2"><span></span>CRM / TEAM WORK</p><h1>งานของทีมขาย</h1><p class="mb-0">เห็นงานค้างและงานเกินกำหนดของทีม เพื่อช่วยจัดลำดับและมอบหมายงานได้ทันเวลา</p></div></div>
<section class="row g-3 mb-4 module-dashboard-summary crm-work-summary" aria-label="สรุปงานของทีม">@foreach([['TODAY','วันนี้','today_count','bx-calendar-star'],['OVERDUE','เกินกำหนด','overdue_count','bx-alarm-exclamation'],['UPCOMING','ถัดไป','upcoming_count','bx-calendar-event'],['NO_NEXT_ACTION','ยังไม่มีงานถัดไป','no_next_count','bx-calendar-x'],['COMPLETED','เสร็จล่าสุด','completed_count','bx-check-circle']] as [$code,$label,$field,$icon])<div class="col-6 col-lg"><button class="card border-0 shadow-sm h-100 w-100 text-start crm-work-filter {{ $filters['view']===$code?'is-active':'' }}" type="button" data-view="{{ $code }}"><span class="card-body d-block"><i class="bx {{ $icon }} crm-work-summary-icon" aria-hidden="true"></i><span class="small text-secondary d-block mt-2">{{ $label }}</span><strong class="fs-3 crm-kpi-value">{{ number_format((int)($summary->{$field}??0)) }}</strong></span></button></div>@endforeach</section>
@if($workload->isNotEmpty())<section class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h6 mb-3">ภาระงานรายคน</h2><div class="row g-2">@foreach($workload as $person)<div class="col-6 col-md-4 col-xl-3"><button class="crm-team-load w-100 text-start js-team-user" type="button" data-user-id="{{ $person->id }}"><strong class="d-block text-truncate">{{ $person->name }}</strong><span>{{ number_format($person->open_count) }} งาน · <span class="{{ $person->overdue_count?'text-danger':'' }}">เกิน {{ number_format($person->overdue_count) }}</span></span></button></div>@endforeach</div></div></section>@endif
<div class="card border-0 shadow-sm mb-4 crm-filter-card"><div class="card-body p-3 p-lg-4"><form class="row g-2" id="team-work-form"><input type="hidden" name="view" id="team-work-view" value="{{ $filters['view'] }}"><div class="col-12 col-lg-4"><label class="visually-hidden" for="team-work-q">ค้นหา</label><input class="form-control" id="team-work-q" name="q" value="{{ $filters['q'] }}" maxlength="100" placeholder="ค้นหางาน Opportunity หรือลูกค้า"></div><div class="col-12 col-sm-6 col-lg-2"><label class="visually-hidden" for="sales-team">ทีมขาย</label><select class="form-select" id="sales-team" name="team_id"><option value="">ทุกทีมที่มีสิทธิ์</option>@foreach($teams as $team)<option value="{{ $team->id }}" @selected($filters['team_id']===$team->id)>{{ $team->name }}</option>@endforeach</select></div><div class="col-12 col-sm-6 col-lg-3"><label class="visually-hidden" for="team-user">พนักงาน</label><select class="form-select" id="team-user" name="user_id" data-url="{{ route('crm.opportunities.owner-options') }}"><option value="">พนักงานทุกคน</option>@if($selectedUser)<option value="{{ $selectedUser->id }}" selected>{{ $selectedUser->employee_code ? $selectedUser->employee_code.' · ':'' }}{{ $selectedUser->name }}</option>@endif</select></div><div class="col-6 col-sm-3 col-lg-2"><select class="form-select" name="type" aria-label="ประเภทกิจกรรม"><option value="">ทุกประเภท</option>@foreach(['CALL'=>'โทรศัพท์','MEETING'=>'นัดหมาย','TASK'=>'งานติดตาม','NOTE'=>'บันทึก'] as $value=>$label)<option value="{{ $value }}" @selected($filters['type']===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-6 col-lg-2"><label class="visually-hidden" for="team-date-from">ตั้งแต่วันที่</label><input class="form-control" id="team-date-from" name="date_from" type="date" value="{{ $filters['date_from'] }}" title="ตั้งแต่วันที่"></div><div class="col-6 col-lg-2"><label class="visually-hidden" for="team-date-to">ถึงวันที่</label><input class="form-control" id="team-date-to" name="date_to" type="date" value="{{ $filters['date_to'] }}" title="ถึงวันที่"></div><div class="col-6 col-sm-3 col-lg-auto"><button class="btn btn-app-primary w-100" type="submit"><i class="bx bx-search me-1" aria-hidden="true"></i>ค้นหา</button></div></form></div></div>
<div class="d-flex justify-content-between align-items-center gap-2 mb-3"><h2 class="h5 mb-0" id="team-work-heading">งานของทีม</h2><span class="small text-secondary" id="team-work-summary">กำลังโหลด...</span></div><div class="row g-3" id="team-work-list" aria-live="polite" aria-busy="true"><div class="col-12 text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2"></span>กำลังโหลดงาน...</div></div><nav class="mt-4" id="team-work-pagination" aria-label="หน้ารายการงานของทีม"></nav>
</div>
@endsection
@push('scripts')
<script>
$(function(){const form=$('#team-work-form'),list=$('#team-work-list'),pagination=$('#team-work-pagination'),summary=$('#team-work-summary'),view=$('#team-work-view'),user=$('#team-user'),indexUrl=@json(route('crm.team-work.index')),dataUrl=@json(route('crm.team-work.data'));let request;window.erpInitSelect2(user,{theme:'bootstrap-5',placeholder:'พนักงานทุกคน',allowClear:true,ajax:{url:user.data('url'),dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:d=>d}});function load(page,push){if(request)request.abort();const params=new URLSearchParams(new FormData(form[0]));if(page>1)params.set('page',page);list.attr('aria-busy','true').html('<div class="col-12 text-center py-5 text-secondary"><span class="spinner-border spinner-border-sm me-2"></span>กำลังโหลดงาน...</div>');request=$.getJSON(dataUrl,params.toString()).done(function(data){list.html(data.html).attr('aria-busy','false');pagination.html(data.pagination);summary.text(data.total?'แสดง '+data.from+'–'+data.to+' จาก '+Number(data.total).toLocaleString('th-TH')+' รายการ':'ไม่พบรายการ');if(push)history.pushState({},'',indexUrl+'?'+params.toString());}).fail(function(xhr,status){if(status==='abort')return;list.attr('aria-busy','false').html('<div class="col-12"><div class="alert alert-danger">โหลดงานของทีมไม่สำเร็จ</div></div>');});}$('.crm-work-filter').on('click',function(){view.val($(this).data('view'));$('.crm-work-filter').removeClass('is-active');$(this).addClass('is-active');load(1,true);});$('.js-team-user').on('click',function(){const id=String($(this).data('user-id')),name=$(this).find('strong').text();user.empty().append(new Option(name,id,true,true)).trigger('change');load(1,true);});form.on('submit',function(e){e.preventDefault();load(1,true);});pagination.on('click','a.page-link',function(e){e.preventDefault();load(Number(new URL(this.href).searchParams.get('page')||1),true);});window.addEventListener('popstate',function(){location.reload();});load(Number(new URL(location.href).searchParams.get('page')||1),false);});
</script>
@endpush
