@extends('Wms::layout')
@section('content')
<script>window.erpDataTableDefaults&&($.fn.dataTable.defaults.pageLength=window.erpDataTableDefaults.pageLength,$.fn.dataTable.defaults.lengthMenu=window.erpDataTableDefaults.lengthMenu);</script>
@push('scripts')<script>$(function(){const t=$('#counts'),f=$('#count-filters');t.on('preXhr.dt',function(e,s,d){d.status=f.find('.js-wms-filter-status').val();d.date_from=f.find('.js-wms-filter-from').val();d.date_to=f.find('.js-wms-filter-to').val();});t.on('draw.dt',function(){t.find('tbody tr').each(function(){var c=$(this).find('td').eq(4),v=c.text().trim(),k={'ร่าง':'app-status-neutral','ตรวจนับแล้ว':'app-status-info','อนุมัติแล้ว':'app-status-success','ปิดผลตรวจนับ':'app-status-success','ยกเลิก':'app-status-danger','กลับรายการแล้ว':'app-status-warning'}[v]||'app-status-neutral';if(!c.find('.badge').length)c.html('<span class="badge '+k+'">'+$('<div>').text(v).html()+'</span>');});});f.on('click','.js-wms-apply-filter,.js-wms-reset-filter',function(){if($(this).hasClass('js-wms-reset-filter'))f.find('select,input').val('');t.DataTable().ajax.reload();});});</script>@endpush
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow">WMS / STOCK COUNT</p><h1>ตรวจนับสินค้า</h1><p class="text-secondary mb-0">บันทึกยอดตรวจนับเทียบกับยอดในระบบ ดูผลต่าง และเก็บประวัติการตรวจนับ</p></div><div class="d-flex flex-wrap align-items-end gap-2">@include('Wms::partials.warehouse-selector') <a class="btn btn-dark" href="{{ route('wms.stock-counts.create') }}"><i class="bx bx-plus"></i> สร้างเอกสารตรวจนับ</a></div></div>
@include('Wms::partials.document-filters', ['filterId' => 'count-filters', 'statusOptions' => ['DRAFT' => 'ร่าง', 'COUNTED' => 'ตรวจนับแล้ว', 'APPROVED' => 'อนุมัติแล้ว', 'POSTED' => 'ปิดผลตรวจนับ', 'VOID' => 'ยกเลิก', 'REVERSED' => 'กลับรายการแล้ว']])
<section class="card border-0 shadow-sm"><div class="card-body p-4"><button class="btn btn-app-soft mb-3" id="export-count"><i class="bx bx-download"></i> ส่งออก Excel</button><div class="table-responsive"><table id="counts" class="table align-middle"><thead><tr><th>เลขที่เอกสาร</th><th>วันที่</th><th>รายการ</th><th>ผลต่างรวม</th><th>สถานะ</th><th>จัดการ</th></tr></thead></table></div></div></section></div>
@endsection
@push('scripts')<script>$(function(){const table=$('#counts').DataTable({processing:true,serverSide:true,ajax:'{{ route('wms.stock-counts.data') }}',dom:'Bfrtip',buttons:[{extend:'excelHtml5',text:'ส่งออก Excel',className:'d-none',exportOptions:{columns:':not(:last-child)'}}],order:[[1,'desc']],columns:[{data:'document_number'},{data:'date_label'},{data:'line_count'},{data:'variance_label'},{data:'status_label'},{data:'show_url',orderable:false,searchable:false,render:function(u,t,r){let x='<a class="btn btn-sm btn-app-soft" title="ดูรายละเอียด" href="'+u+'"><i class="bx bx-show"></i></a>';if(r.can_edit)x+=' <a class="btn btn-sm btn-app-soft" title="แก้ไขร่าง" href="'+u+'/edit"><i class="bx bx-edit"></i></a>';if(r.can_approve)x+=' <button class="btn btn-sm btn-app-soft js-count-approve" data-url="'+u+'/approve" title="อนุมัติ"><i class="bx bx-check"></i></button>';if(r.can_delete)x+=' <button class="btn btn-sm btn-outline-danger js-count-delete" data-url="'+u+'" title="ลบร่าง"><i class="bx bx-trash"></i></button>';return x;}}]});$('#export-count').on('click',()=>table.button('.buttons-excel').trigger());$(document).on('click','.js-count-approve',function(){const b=$(this);$.post(b.data('url'),{_token:'{{ csrf_token() }}'}).done(r=>{Swal.fire({icon:'success',text:r.msg}).then(()=>table.ajax.reload(null,false))}).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ดำเนินการไม่สำเร็จ'}))});$(document).on('click','.js-count-delete',function(){const b=$(this);Swal.fire({icon:'warning',text:'ยืนยันการลบร่างเอกสาร?',showCancelButton:true}).then(x=>{if(!x.isConfirmed)return;$.ajax({url:b.data('url'),method:'DELETE',data:{_token:'{{ csrf_token() }}'}}).done(r=>Swal.fire({icon:'success',text:r.msg}).then(()=>table.ajax.reload(null,false))).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ลบเอกสารไม่สำเร็จ'}))})});});</script>@endpush
