@extends('Wms::layout')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex justify-content-between align-items-end mb-4"><div><p class="eyebrow">WMS / STOCK COUNT</p><h1>{{ $document->document_number }}</h1><p class="text-secondary">วันที่ {{ $document->document_date?->format($dateFormat) }} · สถานะ {{ ['DRAFT'=>'ร่าง','COUNTED'=>'ตรวจนับแล้ว','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ปิดผลตรวจนับ','VOID'=>'ยกเลิก','REVERSED'=>'กลับรายการแล้ว'][$document->status] ?? $document->status }}</p></div><a class="btn btn-outline-secondary" href="{{ route('wms.stock-counts.index') }}">กลับรายการ</a></div>
    <section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5">ผลการตรวจนับ</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>สินค้า</th><th>ยอดในระบบ</th><th>นับจริง</th><th>ผลต่าง</th><th>มูลค่าผลต่าง</th><th>หมายเหตุ</th></tr></thead><tbody>
    @foreach($document->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->item?->code }} · {{ $line->item?->name }}</td><td>{{ \App\Modules\Wms\Support\WmsDecimal::format($line->snapshot_quantity) }} {{ $line->uom?->code }}</td><td>{{ \App\Modules\Wms\Support\WmsDecimal::format($line->counted_quantity) }}</td><td class="{{ (float)$line->variance_quantity < 0 ? 'text-danger':'text-success' }}">{{ \App\Modules\Wms\Support\WmsDecimal::format($line->variance_quantity) }}</td><td>{{ \App\Modules\Wms\Support\WmsDecimal::format($line->variance_value) }}</td><td>{{ $line->note ?: '-' }}</td></tr>@endforeach
    </tbody></table></div><div class="alert alert-info mb-0">ผลต่างนี้ใช้สำหรับตรวจสอบและเก็บประวัติเท่านั้น ระบบจะไม่สร้างเอกสาร Adjustment และจะไม่ลง Stock หรือ GL อัตโนมัติจากเอกสารตรวจนับ</div><div class="d-flex flex-wrap gap-2 mt-3">@if(in_array($document->status, ['DRAFT', 'COUNTED'], true) && auth()->user()->hasPermission('wms.stock-counts.approve'))<button class="btn btn-app-soft js-action" data-url="{{ route('wms.stock-counts.approve',$document) }}">อนุมัติผลตรวจนับ</button>@endif</div></div></section>
    @if($adjustmentDocuments->isNotEmpty())<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5">เอกสาร Adjustment เดิม (ข้อมูลประวัติ)</h2><div class="alert alert-warning">รายการนี้เป็นข้อมูล legacy ที่มีอยู่ก่อนยกเลิก flow อัตโนมัติ ใช้ดูย้อนหลังเท่านั้น และระบบจะไม่สร้างหรือแก้ไขเอกสารจากผลตรวจนับนี้</div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>เลขที่เอกสาร</th><th>ประเภท</th><th>รายการ</th><th>สถานะ</th><th>ดูรายละเอียด</th></tr></thead><tbody>@foreach($adjustmentDocuments as $adjustment)<tr><td>{{ $adjustment->document_number }}</td><td>{{ $adjustment->direction === 'GAIN' ? 'ปรับเพิ่ม':'ปรับลด' }}</td><td>{{ $adjustment->lines->count() }} รายการ</td><td>{{ ['APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','REVERSED'=>'กลับรายการแล้ว'][$adjustment->status] ?? $adjustment->status }}</td><td><a class="btn btn-sm btn-app-soft" href="{{ route('wms.inventory-adjustments.documents.show',$adjustment) }}" title="ดูเอกสาร Adjustment เดิม" aria-label="ดูเอกสาร Adjustment เดิม"><i class="bx bx-show"></i></a></td></tr>@endforeach</tbody></table></div></div></section>@endif
    <section class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="border-bottom py-2"><small class="text-secondary">{{ $event->created_at?->format($dateFormat.' H:i') }}</small> · {{ ['wms.stock_count.created'=>'สร้างเอกสารตรวจนับ','wms.stock_count.updated'=>'แก้ไขเอกสารตรวจนับ','wms.stock_count.approved'=>'อนุมัติผลตรวจนับ','wms.stock_count.posted'=>'ปิดผลตรวจนับ','wms.stock_count.reversed'=>'กลับรายการเอกสารตรวจนับ','wms.stock_count.deleted'=>'ลบร่างเอกสารตรวจนับ'][$event->event] ?? $event->event }} · {{ $event->user?->name ?: 'ระบบ' }}</div>@empty<p class="text-secondary">ยังไม่มีประวัติ</p>@endforelse</div></section>
</div>
@endsection

@push('scripts')<script>$(function(){$('.js-action').on('click',function(){let b=$(this);Swal.fire({icon:'question',text:'ยืนยันการอนุมัติผลตรวจนับ?',showCancelButton:true,confirmButtonText:'อนุมัติ',cancelButtonText:'ยกเลิก'}).then(x=>{if(x.isConfirmed)$.post(b.data('url'),{_token:'{{ csrf_token() }}'}).done(r=>Swal.fire({icon:'success',text:r.msg}).then(()=>location.reload())).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ดำเนินการไม่สำเร็จ'}))})});});</script>@endpush
