@extends('Production::layout')
@section('title', $bom->code.' | BOM')
@php($labels=['DRAFT'=>'ร่าง','ACTIVE'=>'ใช้งาน','INACTIVE'=>'เลิกใช้'])
@php($classes=['DRAFT'=>'app-status-neutral','ACTIVE'=>'app-status-success','INACTIVE'=>'app-status-danger'])
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-start gap-3 mb-4"><div><p class="eyebrow mb-2">PRODUCTION / BOM</p><h1 class="h3 mb-2">{{ $bom->code }} · {{ $bom->name }}</h1><div class="d-flex flex-wrap gap-2 align-items-center"><span class="badge {{ $classes[$revision->status] ?? 'app-status-neutral' }}">{{ $labels[$revision->status] ?? $revision->status }}</span><span class="text-secondary">Revision {{ $revision->revision_number }}</span></div></div><div class="d-flex flex-wrap gap-2">
        <a class="btn btn-outline-secondary" href="{{ route('production.boms.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a>
        @if($revision->status==='DRAFT' && auth()->user()->hasPermission('production.boms.update'))<a class="btn btn-app-soft" href="{{ route('production.boms.revisions.edit',[$bom,$revision]) }}"><i class="bx bx-edit me-1" aria-hidden="true"></i>แก้ไข</a>@endif
        @if(auth()->user()->hasPermission('production.boms.create'))<button class="btn btn-app-soft js-copy" type="button" data-url="{{ route('production.boms.revisions.copy',[$bom,$revision]) }}"><i class="bx bx-copy me-1" aria-hidden="true"></i>คัดลอก Revision</button>@endif
        @if($revision->status==='DRAFT' && auth()->user()->hasPermission('production.boms.activate'))<button class="btn btn-app-primary js-activate" type="button" data-url="{{ route('production.boms.revisions.activate',[$bom,$revision]) }}"><i class="bx bx-check me-1" aria-hidden="true"></i>เปิดใช้ Revision</button>@endif
        @if($revision->status==='ACTIVE' && auth()->user()->hasPermission('production.boms.deactivate'))<button class="btn btn-app-warning js-deactivate" type="button" data-url="{{ route('production.boms.revisions.deactivate',[$bom,$revision]) }}"><i class="bx bx-pause-circle me-1" aria-hidden="true"></i>ปิดใช้งาน</button>@endif
        @if($revision->status==='DRAFT' && auth()->user()->hasPermission('production.boms.delete'))<button class="btn btn-app-danger js-delete" type="button" data-url="{{ route('production.boms.destroy',[$bom,$revision]) }}"><i class="bx bx-trash me-1" aria-hidden="true"></i>ลบร่าง</button>@endif
    </div></div>
    @if($revision->status==='DRAFT')<div class="alert alert-info border-0"><strong>ขั้นตอนถัดไป:</strong> ตรวจสอบวัตถุดิบ จำนวน และวันที่เริ่มใช้ แล้วกด “เปิดใช้ Revision” ระบบจะปิด Revision เดิมและ Revision นี้จะแก้ไขไม่ได้</div>@endif
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ข้อมูล BOM</h2><div class="row g-3"><div class="col-12 col-md-5"><small class="text-secondary d-block">สินค้าสำเร็จรูป</small><div class="d-flex align-items-center gap-3"><div class="app-cover-thumb rounded-3 bg-light d-flex align-items-center justify-content-center">@if($bom->finishedItem?->cover_image_path && auth()->user()->hasPermission('wms.items.view'))<img src="{{ route('wms.items.cover-image', $bom->finishedItem) }}" alt="ภาพปก {{ $bom->finishedItem->name }}" class="w-100 h-100 object-fit-cover">@else<i class="bx bx-package fs-2 text-secondary" aria-hidden="true"></i>@endif</div><div class="fw-semibold">{{ $bom->finishedItem?->code }} · {{ $bom->finishedItem?->name }}</div></div></div><div class="col-6 col-md-2"><small class="text-secondary">หน่วยฐาน</small><div class="fw-semibold">{{ $bom->baseUom?->code }}</div></div><div class="col-6 col-md-2"><small class="text-secondary">เริ่มใช้</small><div class="fw-semibold">{{ $revision->effective_from?->format('d/m/Y') ?: '-' }}</div></div><div class="col-6 col-md-2"><small class="text-secondary">สิ้นสุด</small><div class="fw-semibold">{{ $revision->effective_to?->format('d/m/Y') ?: '-' }}</div></div><div class="col-12"><small class="text-secondary">หมายเหตุ</small><div>{{ $revision->notes ?: '-' }}</div></div></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">Routing / Operations</h2>@forelse($revision->operations as $operation)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $operation->sequence }}. {{ $operation->name }}</span><span class="text-secondary">{{ $operation->planned_minutes ? $operation->planned_minutes.' นาที' : 'ไม่กำหนดเวลา' }}</span></div>@empty<div class="text-secondary">ยังไม่มี Routing · สามารถสร้าง WO และดำเนินงานผลิตได้ตามปกติ</div>@endforelse</div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">วัตถุดิบ {{ number_format($revision->lines->count()) }} รายการ</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>วัตถุดิบ</th><th>หน่วย</th><th class="text-end">จำนวน</th><th>หมายเหตุ</th></tr></thead><tbody>@forelse($revision->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->componentItem?->code }} · {{ $line->componentItem?->name }}@if($line->substitutes->isNotEmpty())<div class="small text-secondary">ทดแทน: {{ $line->substitutes->map(fn($sub) => $sub->substituteItem?->code)->filter()->join(', ') }}</div>@endif</td><td>{{ $line->uom?->code }}</td><td class="text-end">{{ \App\Modules\Wms\Support\WmsDecimal::format($line->quantity) }}</td><td>{{ $line->notes ?: '-' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">ไม่พบวัตถุดิบ</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><h2 class="h5 mb-0">Revision ทั้งหมด</h2><span class="text-secondary small">เลือก Revision เพื่อดูรายละเอียด</span></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Revision</th><th>สถานะ</th><th>เริ่มใช้</th><th>สิ้นสุด</th><th>ผู้เปิดใช้</th><th>จัดการ</th></tr></thead><tbody>@foreach($bom->revisions as $row)<tr class="{{ $row->id===$revision->id?'table-active':'' }}"><td>Rev {{ $row->revision_number }}</td><td><span class="badge {{ $classes[$row->status] ?? 'app-status-neutral' }}">{{ $labels[$row->status] ?? $row->status }}</span></td><td>{{ $row->effective_from?->format('d/m/Y') ?: '-' }}</td><td>{{ $row->effective_to?->format('d/m/Y') ?: '-' }}</td><td>{{ $row->activator?->name ?: '-' }}</td><td><a class="btn btn-sm btn-app-soft" href="{{ route('production.boms.show',[$bom,'revision_id'=>$row->id]) }}"><i class="bx bx-file-find me-1" aria-hidden="true"></i>ดูรายละเอียด</a></td></tr>@endforeach</tbody></table></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ประวัติ</h2>@forelse($history as $row)<div class="border-bottom py-2"><strong>{{ $row->action }}</strong><small class="text-secondary ms-2">{{ $row->created_at?->format('d/m/Y H:i') }} · {{ $row->user?->name ?? '-' }}</small></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection
@push('scripts')
<script>
$(function(){
    function post(button,title,text,confirm){Swal.fire({icon:'warning',title:title,text:text,showCancelButton:true,confirmButtonText:confirm,cancelButtonText:'กลับ'}).then(function(r){if(!r.isConfirmed)return;button.prop('disabled',true);$.post(button.data('url'),{_token:$('meta[name=csrf-token]').attr('content')}).done(function(x){Swal.fire({icon:'success',text:x.msg,timer:1200,showConfirmButton:false}).then(function(){location.href=x.redirect||location.href;});}).fail(function(xhr){button.prop('disabled',false);Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ดำเนินการไม่สำเร็จ'});});});}
    $('.js-copy').on('click',function(){post($(this),'คัดลอก Revision?','ระบบจะสร้าง Revision ร่างใหม่จากข้อมูลชุดนี้','คัดลอก Revision');});
    $('.js-activate').on('click',function(){post($(this),'เปิดใช้ Revision?','Revision ที่ใช้งานอยู่จะถูกปิด และ Revision นี้จะแก้ไขไม่ได้','เปิดใช้ Revision');});
    $('.js-deactivate').on('click',function(){post($(this),'ปิดใช้งาน BOM?','BOM นี้จะไม่ถูกใช้สร้าง WO ใหม่','ปิดใช้งาน');});
    $('.js-delete').on('click',function(){post($(this),'ลบร่าง BOM?','การลบร่างไม่สามารถย้อนกลับได้','ลบร่าง');});
});
</script>
@endpush
