@extends('Pos::layout')

@section('title', $promotion->code.' | โปรโมชั่น | POS')

@section('content')
@php($quantityPlaces = \App\Modules\Wms\Support\WmsDecimal::places())
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">POS / PROMOTION</p>
    <div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h3 mb-2">{{ $promotion->code }} · {{ $promotion->name }}</h1><span class="badge {{ $promotion->is_active ? 'app-badge-success' : 'app-badge-soft' }}">{{ $promotion->is_active ? 'ใช้งาน' : 'ปิดใช้งาน' }}</span></div><div class="d-flex flex-wrap gap-2">@if(auth()->user()->hasPermission('pos.promotions.update'))<a class="btn btn-dark" href="{{ route('pos.promotions.edit', $promotion) }}"><i class="bx bx-edit-alt me-1" aria-hidden="true"></i>แก้ไข</a>@endif <a class="btn btn-outline-secondary" href="{{ route('pos.promotions.index') }}">ย้อนกลับ</a></div></div>
    <div class="alert alert-info">เมื่อเข้าเงื่อนไข ระบบเลือกโปรโมชั่นก่อน Price List และบันทึกราคา/ส่วนลดที่ใช้ลง snapshot ของเอกสารขาย</div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-3"><div class="small text-secondary">กลุ่มลูกค้า</div><strong>{{ $promotion->customer_group_code ?: 'ทุกกลุ่ม' }}</strong></div><div class="col-md-2"><div class="small text-secondary">ประเภท</div>{{ $promotion->application_scope === 'DOCUMENT' ? 'ท้ายบิล' : 'ต่อรายการสินค้า' }}</div><div class="col-md-2"><div class="small text-secondary">ใช้ร่วมกับอื่น</div>{{ $promotion->stackable ? 'อนุญาต' : 'ไม่อนุญาต' }}</div><div class="col-md-2"><div class="small text-secondary">สกุลเงิน</div>{{ $promotion->currency }}</div><div class="col-md-3"><div class="small text-secondary">ลำดับความสำคัญ</div>{{ $promotion->priority }}</div></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">Campaign และค่าใช้จ่ายจริง</h2><div class="row g-3 mb-4"><div class="col-md-3"><div class="small text-secondary">งบประมาณ</div><strong>{{ $promotion->campaign_budget_amount === null ? '—' : number_format((float) $promotion->campaign_budget_amount, 2) }}</strong></div><div class="col-md-3"><div class="small text-secondary">เป้ายอดขาย</div><strong>{{ $promotion->campaign_target_sales_amount === null ? '—' : number_format((float) $promotion->campaign_target_sales_amount, 2) }}</strong></div><div class="col-md-3"><div class="small text-secondary">เป้ากำไรขั้นต้น</div><strong>{{ $promotion->campaign_target_gross_profit_amount === null ? '—' : number_format((float) $promotion->campaign_target_gross_profit_amount, 2) }}</strong></div><div class="col-md-3"><div class="small text-secondary">ผู้รับผิดชอบ</div><strong>{{ $promotion->campaignOwner?->name ?: '—' }}</strong></div></div>@if(auth()->user()->hasPermission('pos.promotions.update'))<form id="campaign-cost-form" action="{{ route('pos.promotions.campaign-costs.store', $promotion) }}" method="POST" class="row g-3 align-items-end border-top pt-3">@csrf<div class="col-md-3"><label class="form-label">วันที่ <span class="text-danger">*</span></label><input class="form-control" type="date" name="cost_date" value="{{ now()->format('Y-m-d') }}" required></div><div class="col-md-2"><label class="form-label">ค่าใช้จ่าย <span class="text-danger">*</span></label><input class="form-control text-end" type="number" step="0.01" name="amount" required></div><div class="col-md-2"><label class="form-label">เลขอ้างอิง</label><input class="form-control" name="reference" maxlength="100"></div><div class="col-md-3"><label class="form-label">รายละเอียด <span class="text-danger">*</span></label><input class="form-control" name="note" maxlength="500" required></div><div class="col-md-2"><button class="btn btn-dark w-100" type="submit">บันทึกค่าใช้จ่าย</button></div></form><p class="form-text mb-0 mt-2">รายการนี้เป็น append-only; ใช้ยอดติดลบพร้อมเหตุผลเพื่อกลับรายการ</p>@endif<div class="table-responsive mt-3"><table class="table align-middle mb-0"><thead><tr><th>วันที่</th><th>อ้างอิง</th><th>รายละเอียด</th><th class="text-end">ค่าใช้จ่าย</th><th>ผู้บันทึก</th></tr></thead><tbody>@forelse($campaignCosts as $cost)<tr><td>{{ $cost->cost_date?->format('d/m/Y') }}</td><td>{{ $cost->reference ?: '—' }}</td><td>{{ $cost->note }}</td><td class="text-end {{ $cost->amount < 0 ? 'text-danger' : '' }}">{{ number_format((float) $cost->amount, 2) }}</td><td>{{ $cost->creator?->name ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary">ยังไม่มีค่าใช้จ่ายในสาขาปัจจุบัน</td></tr>@endforelse</tbody></table></div></div></div>
    @if($promotion->application_scope === 'DOCUMENT')
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ส่วนลดท้ายบิล</h2><div class="row g-3"><div class="col-md-6"><div class="small text-secondary">ยอดลด</div><strong>{{ $promotion->bill_discount_amount === null ? '—' : number_format((float) $promotion->bill_discount_amount, 2) }}</strong></div><div class="col-md-6"><div class="small text-secondary">ส่วนลด</div><strong>{{ $promotion->bill_discount_percent === null ? '—' : number_format((float) $promotion->bill_discount_percent, $quantityPlaces).'%' }}</strong></div></div></div></div>
    @else
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">เงื่อนไขสินค้า</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>สินค้า</th><th>หน่วย</th><th class="text-end">จำนวนขั้นต่ำ</th><th class="text-end">ราคาโปรโมชั่น</th><th class="text-end">ราคาตั้งต้น</th><th class="text-end">ส่วนลด</th><th>สถานะ</th></tr></thead><tbody>@forelse($promotion->items as $line)<tr><td>{{ $line->item?->code }} · {{ $line->item?->name }}</td><td>{{ $line->uom?->code ?: 'ทุกหน่วย' }}</td><td class="text-end">{{ number_format((float) $line->minimum_quantity, $quantityPlaces) }}</td><td class="text-end">{{ $line->unit_price === null ? '—' : number_format((float) $line->unit_price, 2) }}</td><td class="text-end">{{ $line->base_unit_price === null ? '—' : number_format((float) $line->base_unit_price, 2) }}</td><td class="text-end">{{ $line->discount_percent === null ? '—' : number_format((float) $line->discount_percent, $quantityPlaces).'%' }}</td><td><span class="badge {{ $line->is_active ? 'app-badge-success' : 'app-badge-soft' }}">{{ $line->is_active ? 'ใช้งาน' : 'ปิดใช้งาน' }}</span></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary">ไม่พบเงื่อนไขสินค้า</td></tr>@endforelse</tbody></table></div></div></div>
    @endif
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ประวัติการเปลี่ยนแปลง</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>เวลา</th><th>เหตุการณ์</th><th>ผู้ดำเนินการ</th></tr></thead><tbody>@forelse($history as $entry)<tr><td>{{ $entry->created_at?->format('d/m/Y H:i') ?: '—' }}</td><td>{{ $entry->event }}</td><td>{{ $entry->user?->name ?: 'ระบบ' }}</td></tr>@empty<tr><td colspan="3" class="text-center text-secondary">ยังไม่มีประวัติการเปลี่ยนแปลง</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){window.erpAjaxForm({form:'#campaign-cost-form',redirect:false,reload:true});});</script>
@endpush
