@extends('Wms::layout')

@section('content')
@php($allocation = $review->allocation)
@php($wmsDecimal = \App\Modules\Wms\Support\WmsDecimal::class)
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex justify-content-between align-items-end mb-4"><div><div class="eyebrow">WMS / LEGACY REVIEW</div><h1 class="h3 mb-1">ตรวจสอบ Allocation #{{ $review->allocation_id }}</h1><p class="text-secondary mb-0">Revision {{ $review->revision }} · {{ $allocation?->warehouse?->code ?? 'คลังปัจจุบัน' }}</p></div><a class="btn btn-outline-secondary" href="{{ route('wms.legacy-allocation-reviews.index') }}" title="กลับรายการ" aria-label="กลับรายการ"><i class="bx bx-arrow-back" aria-hidden="true"></i></a></div>
    <div class="alert alert-danger border-0 shadow-sm"><i class="bx bx-lock-alt me-2" aria-hidden="true"></i><strong>ห้ามแก้ไขอัตโนมัติ</strong> — สถานะที่เสนอคือ <span class="badge app-status-info">REVIEW_REQUIRED</span> เท่านั้น การตัดสินใจต้องตรวจหลักฐานและดำเนินการตาม approval policy</div>
    <div class="row g-4">
        <div class="col-12 col-xl-7"><div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3">สรุป Allocation</h2><dl class="row mb-0"><dt class="col-sm-4">สถานะ Review</dt><dd class="col-sm-8"><span class="badge app-status-warning">เปิดรอตรวจสอบ</span></dd><dt class="col-sm-4">สถานะ Allocation</dt><dd class="col-sm-8">{{ $allocation?->status ?? '-' }} / {{ $allocation?->cost_status ?? '-' }}</dd><dt class="col-sm-4">จำนวน / มูลค่า</dt><dd class="col-sm-8">{{ $allocation ? $wmsDecimal::format($allocation->quantity) : '-' }} / {{ $wmsDecimal::format($allocation?->value) }}</dd><dt class="col-sm-4">Warehouse / Item</dt><dd class="col-sm-8">{{ $allocation?->warehouse?->code ?? '-' }} / {{ $allocation?->movement?->item?->code ?? '-' }} · {{ $allocation?->movement?->item?->name ?? '-' }}</dd><dt class="col-sm-4">เหตุผลเดิม</dt><dd class="col-sm-8">{{ $review->reason }}</dd><dt class="col-sm-4">Evidence hash</dt><dd class="col-sm-8"><code class="small">{{ $review->evidence_hash }}</code></dd></dl></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">หลักฐานที่บันทึกไว้</h2><pre class="bg-light rounded p-3 small mb-0" style="white-space:pre-wrap">{{ json_encode($review->evidence, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre></div></div></div>
        <div class="col-12 col-xl-5"><div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3">Journal / Movement / Cost Layer</h2><div class="small text-secondary mb-2">Journal link</div>@forelse($allocation?->journalLineLinks ?? [] as $link)<div class="border rounded p-2 mb-2">Journal line #{{ $link->journal_entry_line_id }}<br><span class="text-secondary">{{ $link->journalEntryLine?->entry?->entry_number ?? '-' }} · {{ $link->journalEntryLine?->entry?->status ?? '-' }}</span></div>@empty<p class="text-secondary mb-2">ไม่มี Journal line link</p>@endforelse<div class="small text-secondary mb-2 mt-3">Movement</div><div class="border rounded p-2">{{ $allocation?->movement?->id ? '#'.$allocation->movement->id.' '.$allocation->movement->movement_type.' / '.$allocation->movement->direction : 'ไม่มี Movement' }}</div><div class="small text-secondary mb-2 mt-3">Cost Layer</div><div class="border rounded p-2">{{ $allocation?->layer?->id ? '#'.$allocation->layer->id.' · '.$allocation->layer->cost_status : 'ไม่มี Cost Layer' }}</div></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">ประวัติการตรวจสอบ</h2>@forelse($audit as $entry)<div class="border-bottom py-2"><div><strong>{{ $entry->action }}</strong> <span class="text-secondary">โดย {{ $entry->user?->name ?? 'ระบบ' }}</span></div><div class="small text-secondary">{{ $entry->created_at?->format('d/m/Y H:i') }}{{ $entry->reason ? ' · '.$entry->reason : '' }}</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติ</p>@endforelse</div></div></div>
    </div>
</div>
@endsection
