@extends('Finance::layout')
@section('title', 'สถานะเงินสดและธนาคาร | Finance')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><p class="eyebrow mb-2">FINANCE / REPORTS</p><h1 class="h3 mb-2">สถานะเงินสดและธนาคาร</h1><p class="text-secondary mb-4">ยอดเคลื่อนไหวสุทธิจาก Journal ที่ลงบัญชีแล้ว แยกตามบัญชีและสาขา</p>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">ตัวกรอง</h2><button class="btn btn-sm btn-outline-secondary" id="cash-position-reset" type="button">ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-md-3"><label class="form-label">สาขา</label><select class="form-select" id="cash-position-branch"><option value="current">สาขาปัจจุบัน</option><option value="all">ทุกสาขาที่มีสิทธิ์</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->code }} · {{ $branch->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">ประเภทบัญชี</label><select class="form-select" id="cash-position-type"><option value="">ทั้งหมด</option><option value="CASH">เงินสด</option><option value="BANK">ธนาคาร</option></select></div><div class="col-md-3"><label class="form-label">วันที่เริ่มต้น</label><input class="form-control" type="date" id="cash-position-from"></div><div class="col-md-3"><label class="form-label">วันที่สิ้นสุด</label><input class="form-control" type="date" id="cash-position-to"></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="cash-position-table" data-url="{{ route('finance.reports.cash-position.data') }}"><thead><tr><th>บัญชี</th><th>ประเภท</th><th>สาขา</th><th>คลัง</th><th>สกุลเงิน</th><th class="text-end">เดบิต</th><th class="text-end">เครดิต</th><th class="text-end">ยอดสุทธิ</th></tr></thead></table></div></div></div></div>
@endsection
@push('scripts')
<script>$(function(){var t=$('#cash-position-table'),branch=$('#cash-position-branch'),type=$('#cash-position-type'),from=$('#cash-position-from'),to=$('#cash-position-to'),x=$.fn.dataTable.render.text(),money=$.fn.dataTable.render.number(',','.',2);var dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.branch_scope=branch.val();d.account_type=type.val();d.from=from.val();d.to=to.val()}},order:[[0,'asc']],buttons:[window.erpExcelButton(t,function(){return{branch_scope:branch.val(),account_type:type.val(),from:from.val(),to:to.val()}})],columns:[{data:'account_label',name:'ba.code',render:x.display},{data:'type_label',name:'ba.type',render:x.display},{data:'branch_code',name:'b.code',render:x.display},{data:'warehouse_code',name:'w.code',render:x.display},{data:'currency_code',name:'ba.currency_code',render:x.display},{data:'debit_total',name:'debit_total',className:'text-end',render:money},{data:'credit_total',name:'credit_total',className:'text-end',render:money},{data:'balance_amount',name:'balance_amount',className:'text-end fw-semibold',render:money}]}));branch.add(type).add(from).add(to).on('change',function(){dt.ajax.reload()});$('#cash-position-reset').on('click',function(){branch.val('current');type.val('');from.val('');to.val('');dt.ajax.reload()});});</script>
@endpush
