@extends('Finance::layout')
@section('title', 'รายงานเงินสดย่อย | Finance')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">FINANCE / REPORTS</p><h1 class="h3 mb-2">รายงานเงินสดย่อย</h1><p class="text-secondary mb-4">ยอดวงเงิน เงินเติม เงินจ่าย และยอดคงเหลือจากรายการที่ลงบัญชีแล้ว</p>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">ตัวกรอง</h2><button class="btn btn-sm btn-outline-secondary" id="petty-report-reset" type="button">ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-md-3"><label class="form-label">สาขา</label><select class="form-select" id="petty-report-branch"><option value="current">สาขาปัจจุบัน</option><option value="all">ทุกสาขาที่มีสิทธิ์</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->code }} · {{ $branch->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">วันที่เริ่มต้น</label><input class="form-control" type="date" id="petty-report-from"></div><div class="col-md-3"><label class="form-label">วันที่สิ้นสุด</label><input class="form-control" type="date" id="petty-report-to"></div><div class="col-md-3"><label class="form-label">สถานะวงเงิน</label><select class="form-select" id="petty-report-status"><option value="">ทั้งหมด</option><option value="ACTIVE">ใช้งาน</option><option value="INACTIVE">ปิดใช้งาน</option></select></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="finance-petty-cash-report" data-url="{{ route('finance.reports.petty-cash.data') }}"><thead><tr><th>วงเงินสดย่อย</th><th>สาขา</th><th>คลัง</th><th>สถานะ</th><th class="text-end">วงเงิน</th><th class="text-end">เงินเติม</th><th class="text-end">เงินจ่าย</th><th class="text-end">คงเหลือ</th><th class="text-end">ใช้ไป (%)</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){var t=$('#finance-petty-cash-report'),branch=$('#petty-report-branch'),from=$('#petty-report-from'),to=$('#petty-report-to'),status=$('#petty-report-status'),x=$.fn.dataTable.render.text(),money=$.fn.dataTable.render.number(',','.',2);var dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.branch_scope=branch.val();d.from=from.val();d.to=to.val();d.fund_status=status.val()}},order:[[0,'asc']],buttons:[window.erpExcelButton(t,function(){return{branch_scope:branch.val(),from:from.val(),to:to.val(),fund_status:status.val()}})],columns:[{data:'fund_label',name:'f.name',render:x.display},{data:'branch_code',name:'b.code',render:x.display},{data:'warehouse_code',name:'w.code',render:x.display},{data:'status_label',name:'f.is_active',render:x.display},{data:'fund_limit',name:'f.fund_limit',className:'text-end',render:money},{data:'top_up_amount',name:'top_up_amount',className:'text-end',render:money},{data:'voucher_amount',name:'voucher_amount',className:'text-end',render:money},{data:'balance_amount',name:'balance_amount',className:'text-end',render:money},{data:'utilization',name:'utilization',className:'text-end',render:function(v){return Number(v||0).toFixed(2)+'%';}},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,type,row){return type==='display'?'<a class="btn btn-sm btn-app-soft" href="'+x.display(row.show_url)+'" title="ดูวงเงินสดย่อย" aria-label="ดูวงเงินสดย่อย"><i class="bx bx-show" aria-hidden="true"></i></a>':'';}}]}));branch.add(from).add(to).add(status).on('change',function(){dt.ajax.reload()});$('#petty-report-reset').on('click',function(){branch.val('current');from.val('');to.val('');status.val('');dt.ajax.reload()});});</script>
@endpush
