@extends('Finance::layout')
@section('title', 'รายงาน Settlement และ Allocation | Finance')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><p class="eyebrow mb-2">FINANCE / REPORTS</p><h1 class="h3 mb-2">รายงาน Settlement และ Allocation</h1><p class="text-secondary mb-4">ตรวจสอบการรับ–จ่ายและรายการ Open Item ที่ถูกจัดสรร</p>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">ตัวกรอง</h2><button class="btn btn-sm btn-outline-secondary" id="settlement-allocation-reset" type="button">ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-md-3"><label class="form-label">สาขา</label><select class="form-select" id="settlement-allocation-branch"><option value="current">สาขาปัจจุบัน</option><option value="all">ทุกสาขาที่มีสิทธิ์</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->code }} · {{ $branch->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">คลัง</label><select class="form-select" id="settlement-allocation-warehouse"><option value="">ทุกคลัง</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->code }} · {{ $warehouse->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">ประเภท</label><select class="form-select" id="settlement-allocation-type"><option value="">ทั้งหมด</option><option value="RECEIPT">รับเงิน</option><option value="PAYMENT">จ่ายเงิน</option></select></div><div class="col-md-3"><label class="form-label">วันที่เริ่มต้น</label><input class="form-control" type="date" id="settlement-allocation-from"></div><div class="col-md-3"><label class="form-label">วันที่สิ้นสุด</label><input class="form-control" type="date" id="settlement-allocation-to"></div><div class="col-md-3"><label class="form-label">สถานะ Settlement</label><select class="form-select" id="settlement-allocation-status"><option value="">ทั้งหมด</option><option value="DRAFT">ร่าง</option><option value="APPROVED">อนุมัติแล้ว</option><option value="POSTED">ลงบัญชีแล้ว</option><option value="VOID">ยกเลิก</option></select></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="settlement-allocation-report" data-url="{{ route('finance.reports.settlement-allocations.data') }}"><thead><tr><th>เลขที่ Settlement</th><th>ประเภท</th><th>วันที่</th><th>คู่ค้า</th><th>คลัง</th><th>Open Item</th><th class="text-end">ยอดจัดสรร</th><th>สถานะ Allocation</th><th>จัดการ</th></tr></thead></table></div></div></div></div>
@endsection
@push('scripts')
<script>$(function(){var t=$('#settlement-allocation-report'),branch=$('#settlement-allocation-branch'),warehouse=$('#settlement-allocation-warehouse'),type=$('#settlement-allocation-type'),from=$('#settlement-allocation-from'),to=$('#settlement-allocation-to'),status=$('#settlement-allocation-status'),x=$.fn.dataTable.render.text(),money=$.fn.dataTable.render.number(',','.',2);var dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.branch_scope=branch.val();d.warehouse_id=warehouse.val();d.document_type=type.val();d.from=from.val();d.to=to.val();d.status=status.val()}},order:[[2,'desc']],buttons:[window.erpExcelButton(t,function(){return{branch_scope:branch.val(),warehouse_id:warehouse.val(),document_type:type.val(),from:from.val(),to:to.val(),status:status.val()}})],columns:[{data:'document_number',name:'s.document_number',render:function(v,t,r){return r.settlement_url?'<a href="'+x.display(r.settlement_url)+'">'+x.display(v)+'</a>':x.display(v)}},{data:'type_label',name:'s.document_type',render:x.display},{data:'date_label',name:'s.settlement_date',render:x.display},{data:null,name:'p.code',render:function(v,t,r){return x.display((r.party_code||'')+' · '+(r.party_name||''))}},{data:'warehouse_code',name:'w.code',render:x.display},{data:'open_item_number',name:'oi.document_number',defaultContent:'—',render:function(v,t,r){return r.open_item_url?'<a href="'+x.display(r.open_item_url)+'">'+x.display(v)+'</a>':'—'}},{data:'amount',name:'i.amount',className:'text-end',render:money},{data:'allocation_status',name:'a.reversal_date',render:x.display},{data:null,orderable:false,searchable:false,className:'text-end',render:function(v,t,r){return t==='display'&&r.settlement_url?'<a class="btn btn-sm btn-app-soft" href="'+x.display(r.settlement_url)+'" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-show" aria-hidden="true"></i></a>':'';}}]}));branch.add(warehouse).add(type).add(from).add(to).add(status).on('change',function(){dt.ajax.reload()});$('#settlement-allocation-reset').on('click',function(){branch.val('current');warehouse.val('');type.val('');from.val('');to.val('');status.val('');dt.ajax.reload()});});</script>
@endpush
