@extends('Asset::layout')
@section('title', $disposal->document_number.' | New ERP')
@section('content')
@php
    $labels=['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','CANCELLED'=>'ยกเลิก'];
    $badges=['DRAFT'=>'app-badge-soft','SUBMITTED'=>'app-badge-info','APPROVED'=>'app-badge-info','POSTED'=>'app-badge-success','CANCELLED'=>'app-status-danger'];
    $types=['SALE'=>'ขาย','WRITE_OFF'=>'ตัดจำหน่าย'];
@endphp
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-xl-row justify-content-between align-items-xl-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / DISPOSAL</p><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><h1 class="h3 mb-0">{{ $disposal->document_number }}</h1><span class="badge {{ $badges[$disposal->status] ?? 'app-status-neutral' }}">{{ $labels[$disposal->status] ?? $disposal->status }}</span></div><p class="text-secondary mb-0">{{ $types[$disposal->disposal_type] ?? $disposal->disposal_type }} · วันที่ {{ $disposal->disposal_date?->format('d/m/Y') }}</p></div>
        <div class="d-flex flex-wrap gap-2">
            @if($disposal->status==='DRAFT')<button class="btn btn-primary js-action" data-url="{{ route('asset.disposals.submit',$disposal) }}" data-title="ส่งอนุมัติเอกสารนี้หรือไม่?">ส่งอนุมัติ</button>@elseif($disposal->status==='SUBMITTED')<button class="btn btn-success js-action" data-url="{{ route('asset.disposals.approve',$disposal) }}" data-title="อนุมัติการจำหน่ายสินทรัพย์หรือไม่?">อนุมัติ</button>@elseif($disposal->status==='APPROVED')<button class="btn btn-dark js-action" data-url="{{ route('asset.disposals.post',$disposal) }}" data-title="ลงบัญชีการจำหน่ายสินทรัพย์หรือไม่?">ลงบัญชี</button>@elseif($disposal->status==='POSTED')<button class="btn btn-outline-danger js-action" data-url="{{ route('asset.disposals.reverse',$disposal) }}" data-title="กลับรายการจำหน่ายสินทรัพย์หรือไม่?" data-reason="1">กลับรายการ</button>@endif
            @if(in_array($disposal->status,['DRAFT','SUBMITTED','APPROVED'],true))<button class="btn btn-outline-danger js-cancel" data-url="{{ route('asset.disposals.cancel',$disposal) }}">ยกเลิก</button>@endif
            <a class="btn btn-outline-dark" href="{{ route('asset.disposals.index') }}">รายการทั้งหมด</a>
        </div>
    </div>
    <div class="alert alert-info border-0 shadow-sm" role="note"><i class="bx bx-info-circle me-1" aria-hidden="true"></i>การลงบัญชีจะตัดราคาทุน ค่าเสื่อมสะสม และด้อยค่าสะสมออกจากสินทรัพย์ พร้อมคำนวณกำไรหรือขาดทุน</div>
    <div class="row g-4 mb-4"><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">รายการสินทรัพย์</div><div class="fs-4 fw-semibold mt-1">{{ number_format($disposal->lines?->count() ?? 0) }}</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">เงินรับรวม</div><div class="fs-4 fw-semibold mt-1">{{ number_format((float)$disposal->proceeds,2) }}</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">Journal Entry</div><div class="fs-4 fw-semibold mt-1">{{ $disposal->journal_entry_id ? '#'.$disposal->journal_entry_id : 'รอลงบัญชี' }}</div></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h5 mb-1">รายละเอียดการจำหน่าย</h2><p class="small text-secondary mb-0">{{ $types[$disposal->disposal_type] ?? '-' }} · {{ $disposal->reason }}</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-3 ps-lg-4">สินทรัพย์</th><th class="text-end">ราคาทุน</th><th class="text-end">ค่าเสื่อมสะสม</th><th class="text-end">ด้อยค่าสะสม</th><th class="text-end">มูลค่าตามบัญชี</th><th class="text-end pe-3 pe-lg-4">กำไร/ขาดทุน</th></tr></thead><tbody>@forelse($disposal->lines as $line)<tr><td class="ps-3 ps-lg-4"><a class="fw-semibold text-decoration-none" href="{{ route('asset.assets.show',$line->asset) }}">{{ $line->asset?->asset_number ?? '-' }}</a><div class="small text-secondary">{{ $line->asset?->name ?? '-' }}</div></td><td class="text-end">{{ number_format((float)$line->cost,2) }}</td><td class="text-end">{{ number_format((float)$line->accumulated_depreciation,2) }}</td><td class="text-end">{{ number_format((float)$line->accumulated_impairment,2) }}</td><td class="text-end fw-semibold">{{ number_format((float)$line->carrying_amount,2) }}</td><td class="text-end pe-3 pe-lg-4 fw-semibold">{{ number_format((float)$line->gain_loss,2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">ยังไม่มีรายการสินทรัพย์</td></tr>@endforelse</tbody></table></div></div>
    <div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white border-0 pt-4 px-4"><h2 class="h5 mb-1">ประวัติการทำรายการ</h2><p class="small text-secondary mb-0">Audit Trail · เวลาไทย (UTC+7)</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>เหตุการณ์</th><th>วันเวลา</th><th>ผู้ดำเนินการ</th><th>หมายเหตุ</th></tr></thead><tbody>@foreach([['สร้างเอกสาร',$disposal->created_at,$disposal->createdBy?->name,null],['ส่งอนุมัติ',$disposal->submitted_at,null,null],['อนุมัติ',$disposal->approved_at,null,null],['ลงบัญชี',$disposal->posted_at,null,null],['ยกเลิก',$disposal->cancelled_at,null,$disposal->cancellation_reason]] as [$event,$at,$actor,$note]) @if($at)<tr><td>{{ $event }}</td><td>{{ $at->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</td><td>{{ $actor ?? '-' }}</td><td>{{ $note ?? '-' }}</td></tr>@endif @endforeach</tbody></table></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){function run($b,reason,field){Swal.fire({icon:'warning',title:$b.data('title'),input:reason?'textarea':undefined,inputLabel:reason?'เหตุผล':'',showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'กลับ',preConfirm:function(v){if(reason&&(!v||v.trim().length<10)){Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร');}}}).then(function(r){if(!r.isConfirmed)return;$b.prop('disabled',true);var data={_token:'{{ csrf_token() }}'};if(reason){data[field||'reason']=r.value;if(field==='reason')data.reversal_date='{{ today()->toDateString() }}';}$.post($b.data('url'),data).done(function(x){Swal.fire({icon:'success',title:x.msg}).then(function(){location.href=x.redirect;});}).fail(window.erpAjaxError).always(function(){$b.prop('disabled',false);});});}$('.js-action').on('click',function(){run($(this),$(this).data('reason'),$(this).data('reason')?'reason':null);});$('.js-cancel').on('click',function(){var b=$(this);b.data('title','ยืนยันยกเลิกเอกสารนี้หรือไม่?');run(b,true,'cancellation_reason');});});</script>@endpush
