<?php

use App\Modules\Finance\Controllers\AdvanceDepositController;
use App\Modules\Finance\Controllers\BankAccountController;
use App\Modules\Finance\Controllers\CommissionPayoutController;
use App\Modules\Finance\Controllers\DocumentSequenceController;
use App\Modules\Finance\Controllers\EmployeeAdvanceController;
use App\Modules\Finance\Controllers\EmployeeAdvanceClearingController;
use App\Modules\Finance\Controllers\EntryController;
use App\Modules\Finance\Controllers\FinanceReportController;
use App\Modules\Finance\Controllers\OpenItemController;
use App\Modules\Finance\Controllers\OtherCategoryController;
use App\Modules\Finance\Controllers\InternalTransferController;
use App\Modules\Finance\Controllers\PaymentTermController;
use App\Modules\Finance\Controllers\PaymentVoucherController;
use App\Modules\Finance\Controllers\PettyCashController;
use App\Modules\Finance\Controllers\PettyCashAttachmentController;
use App\Modules\Finance\Controllers\PettyCashClearingController;
use App\Modules\Finance\Controllers\PettyCashFundController;
use App\Modules\Finance\Controllers\PettyCashTopUpController;
use App\Modules\Finance\Controllers\SettlementController;
use App\Modules\Finance\Controllers\WorkflowController;
use App\Modules\Finance\Models\DocumentSequence;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'program:finance', 'warehouse'])->prefix('finance')->name('finance.')->group(function () {
    Route::get('/', EntryController::class)->middleware('permission:finance.dashboard.view')->name('index');
    Route::get('/dashboard/data/{section}', [EntryController::class, 'data'])->middleware('permission:finance.dashboard.view')->name('dashboard.data');
    Route::get('/workflow', [WorkflowController::class, 'index'])->name('workflow.index');
    Route::get('/reports/payment-activity', [FinanceReportController::class, 'paymentIndex'])->middleware('permission:finance.reports.payment-activity.view')->name('reports.payment-activity.index');
    Route::get('/reports/payment-activity/data', [FinanceReportController::class, 'paymentData'])->middleware('permission:finance.reports.payment-activity.view')->name('reports.payment-activity.data');
    Route::get('/reports/settlement-allocations', [FinanceReportController::class, 'settlementAllocationIndex'])->middleware('permission:finance.reports.settlement-allocations.view')->name('reports.settlement-allocations.index');
    Route::get('/reports/settlement-allocations/data', [FinanceReportController::class, 'settlementAllocationData'])->middleware('permission:finance.reports.settlement-allocations.view')->name('reports.settlement-allocations.data');
    Route::get('/reports/petty-cash', [FinanceReportController::class, 'pettyCashIndex'])->middleware('permission:finance.reports.petty-cash.view')->name('reports.petty-cash.index');
    Route::get('/reports/petty-cash/data', [FinanceReportController::class, 'pettyCashData'])->middleware('permission:finance.reports.petty-cash.view')->name('reports.petty-cash.data');
    Route::get('/reports/cash-position', [FinanceReportController::class, 'cashPositionIndex'])->middleware('permission:finance.reports.cash-position.view')->name('reports.cash-position.index');
    Route::get('/reports/cash-position/data', [FinanceReportController::class, 'cashPositionData'])->middleware('permission:finance.reports.cash-position.view')->name('reports.cash-position.data');
    Route::get('/reports/expected', [FinanceReportController::class, 'expectedIndex'])->middleware('permission:finance.reports.expected.view')->name('reports.expected.index');
    Route::get('/reports/expected/data', [FinanceReportController::class, 'expectedData'])->middleware('permission:finance.reports.expected.view')->name('reports.expected.data');
    Route::get('/reports/employee-advances', [FinanceReportController::class, 'employeeAdvanceIndex'])->middleware('permission:finance.reports.employee-advances.view')->name('reports.employee-advances.index');
    Route::get('/reports/employee-advances/data', [FinanceReportController::class, 'employeeAdvanceData'])->middleware('permission:finance.reports.employee-advances.view')->name('reports.employee-advances.data');
    Route::get('/reports/reconciliation', [FinanceReportController::class, 'reconciliationIndex'])->middleware('permission:finance.reports.reconciliation.view')->name('reports.reconciliation.index');
    Route::get('/reports/reconciliation/data', [FinanceReportController::class, 'reconciliationData'])->middleware('permission:finance.reports.reconciliation.view')->name('reports.reconciliation.data');
    Route::get('/advances', [AdvanceDepositController::class, 'index'])->middleware('permission:finance.advance-deposits.view')->name('advances.index');
    Route::get('/advances/data', [AdvanceDepositController::class, 'data'])->middleware('permission:finance.advance-deposits.view')->name('advances.data');
    Route::get('/deposits', [AdvanceDepositController::class, 'index'])->middleware('permission:finance.advance-deposits.view')->name('deposits.index');
    Route::get('/deposits/data', [AdvanceDepositController::class, 'data'])->middleware('permission:finance.advance-deposits.view')->name('deposits.data');
    Route::get('/advance-deposits', [AdvanceDepositController::class, 'index'])->middleware('permission:finance.advance-deposits.view')->name('advance-deposits.index');
    Route::get('/advance-deposits/data', [AdvanceDepositController::class, 'data'])->middleware('permission:finance.advance-deposits.view')->name('advance-deposits.data');
    Route::get('/advance-deposits/{advance}', [AdvanceDepositController::class, 'show'])->middleware('permission:finance.advance-deposits.view')->name('advance-deposits.show');
    Route::get('/advance-deposits/{advance}/applications/create', [AdvanceDepositController::class, 'createApplication'])->middleware('permission:finance.advance-deposits.apply')->name('advance-deposits.applications.create');
    Route::post('/advance-deposits/{advance}/applications', [AdvanceDepositController::class, 'storeApplication'])->middleware('permission:finance.advance-deposits.apply')->name('advance-deposits.applications.store');
    Route::get('/employee-advances', [EmployeeAdvanceController::class, 'index'])->middleware('permission:finance.employee-advances.view')->name('employee-advances.index');
    Route::get('/employee-advances/data', [EmployeeAdvanceController::class, 'data'])->middleware('permission:finance.employee-advances.view')->name('employee-advances.data');
    Route::get('/employee-advances/create', [EmployeeAdvanceController::class, 'create'])->middleware('permission:finance.employee-advances.create')->name('employee-advances.create');
    Route::post('/employee-advances', [EmployeeAdvanceController::class, 'store'])->middleware('permission:finance.employee-advances.create')->name('employee-advances.store');
    Route::get('/employee-advances/{advance}', [EmployeeAdvanceController::class, 'show'])->middleware('permission:finance.employee-advances.view')->name('employee-advances.show');
    Route::get('/employee-advances/{advance}/edit', [EmployeeAdvanceController::class, 'edit'])->middleware('permission:finance.employee-advances.update')->name('employee-advances.edit');
    Route::put('/employee-advances/{advance}', [EmployeeAdvanceController::class, 'update'])->middleware('permission:finance.employee-advances.update')->name('employee-advances.update');
    Route::post('/employee-advances/{advance}/submit', [EmployeeAdvanceController::class, 'submit'])->middleware('permission:finance.employee-advances.submit')->name('employee-advances.submit');
    Route::post('/employee-advances/{advance}/approve', [EmployeeAdvanceController::class, 'approve'])->middleware('permission:finance.employee-advances.approve')->name('employee-advances.approve');
    Route::post('/employee-advances/{advance}/reject', [EmployeeAdvanceController::class, 'reject'])->middleware('permission:finance.employee-advances.approve')->name('employee-advances.reject');
    Route::delete('/employee-advances/{advance}', [EmployeeAdvanceController::class, 'destroy'])->middleware('permission:finance.employee-advances.update')->name('employee-advances.destroy');
    Route::post('/employee-advances/{advance}/void', [EmployeeAdvanceController::class, 'void'])->middleware('permission:finance.employee-advances.void')->name('employee-advances.void');
    Route::post('/employee-advances/{advance}/post', [EmployeeAdvanceController::class, 'post'])->middleware('permission:finance.employee-advances.post')->name('employee-advances.post');
    Route::post('/employee-advances/{advance}/reverse', [EmployeeAdvanceController::class, 'reverse'])->middleware('permission:finance.employee-advances.reverse')->name('employee-advances.reverse');
    Route::get('/employee-advance-clearings', [EmployeeAdvanceClearingController::class, 'index'])->middleware('permission:finance.employee-advance-clearings.view')->name('employee-advance-clearings.index');
    Route::get('/employee-advance-clearings/data', [EmployeeAdvanceClearingController::class, 'data'])->middleware('permission:finance.employee-advance-clearings.view')->name('employee-advance-clearings.data');
    Route::get('/employee-advance-clearings/create', [EmployeeAdvanceClearingController::class, 'create'])->middleware('permission:finance.employee-advance-clearings.create')->name('employee-advance-clearings.create');
    Route::post('/employee-advance-clearings', [EmployeeAdvanceClearingController::class, 'store'])->middleware('permission:finance.employee-advance-clearings.create')->name('employee-advance-clearings.store');
    Route::get('/employee-advance-clearings/{clearing}', [EmployeeAdvanceClearingController::class, 'show'])->middleware('permission:finance.employee-advance-clearings.view')->name('employee-advance-clearings.show');
    Route::get('/employee-advance-clearings/{clearing}/edit', [EmployeeAdvanceClearingController::class, 'edit'])->middleware('permission:finance.employee-advance-clearings.update')->name('employee-advance-clearings.edit');
    Route::put('/employee-advance-clearings/{clearing}', [EmployeeAdvanceClearingController::class, 'update'])->middleware('permission:finance.employee-advance-clearings.update')->name('employee-advance-clearings.update');
    Route::post('/employee-advance-clearings/{clearing}/submit', [EmployeeAdvanceClearingController::class, 'submit'])->middleware('permission:finance.employee-advance-clearings.submit')->name('employee-advance-clearings.submit');
    Route::post('/employee-advance-clearings/{clearing}/approve', [EmployeeAdvanceClearingController::class, 'approve'])->middleware('permission:finance.employee-advance-clearings.approve')->name('employee-advance-clearings.approve');
    Route::post('/employee-advance-clearings/{clearing}/reject', [EmployeeAdvanceClearingController::class, 'reject'])->middleware('permission:finance.employee-advance-clearings.approve')->name('employee-advance-clearings.reject');
    Route::delete('/employee-advance-clearings/{clearing}', [EmployeeAdvanceClearingController::class, 'destroy'])->middleware('permission:finance.employee-advance-clearings.update')->name('employee-advance-clearings.destroy');
    Route::post('/employee-advance-clearings/{clearing}/void', [EmployeeAdvanceClearingController::class, 'void'])->middleware('permission:finance.employee-advance-clearings.void')->name('employee-advance-clearings.void');
    Route::post('/employee-advance-clearings/{clearing}/post', [EmployeeAdvanceClearingController::class, 'post'])->middleware('permission:finance.employee-advance-clearings.post')->name('employee-advance-clearings.post');
    Route::post('/employee-advance-clearings/{clearing}/reverse', [EmployeeAdvanceClearingController::class, 'reverse'])->middleware('permission:finance.employee-advance-clearings.reverse')->name('employee-advance-clearings.reverse');
    Route::get('/employee-advance-clearings/{clearing}/attachments', [PettyCashAttachmentController::class, 'employeeAdvanceClearingIndex'])->middleware('permission:finance.employee-advance-clearings.view')->name('employee-advance-clearings.attachments.index');
    Route::post('/employee-advance-clearings/{clearing}/attachments', [PettyCashAttachmentController::class, 'employeeAdvanceClearingStore'])->middleware('permission:finance.employee-advance-clearings.update')->name('employee-advance-clearings.attachments.store');
    Route::get('/employee-advance-clearings/{clearing}/attachments/{attachment}/download', [PettyCashAttachmentController::class, 'employeeAdvanceClearingDownload'])->middleware('permission:finance.employee-advance-clearings.view')->name('employee-advance-clearings.attachments.download');
    Route::get('/employee-advance-clearings/{clearing}/attachments/{attachment}/preview', [PettyCashAttachmentController::class, 'employeeAdvanceClearingPreview'])->middleware('permission:finance.employee-advance-clearings.view')->name('employee-advance-clearings.attachments.preview');
    Route::delete('/employee-advance-clearings/{clearing}/attachments/{attachment}', [PettyCashAttachmentController::class, 'employeeAdvanceClearingDestroy'])->middleware('permission:finance.employee-advance-clearings.update')->name('employee-advance-clearings.attachments.destroy');
    Route::prefix('receivables')->name('receivables.')->group(function () {
        Route::get('/open-items', [OpenItemController::class, 'index'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-open-items.view')->name('open-items.index');
        Route::get('/open-items/data', [OpenItemController::class, 'data'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-open-items.view')->name('open-items.data');
        Route::get('/open-items/{openItem}', [OpenItemController::class, 'show'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-open-items.view')->name('open-items.show');
        Route::get('/party-options', [OpenItemController::class, 'partyOptions'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-open-items.view')->name('party-options');
        Route::get('/aging', [OpenItemController::class, 'agingIndex'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-aging.view')->name('aging.index');
        Route::get('/aging/data', [OpenItemController::class, 'agingData'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-aging.view')->name('aging.data');
    });
    Route::prefix('payables')->name('payables.')->group(function () {
        Route::get('/open-items', [OpenItemController::class, 'index'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-open-items.view')->name('open-items.index');
        Route::get('/open-items/data', [OpenItemController::class, 'data'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-open-items.view')->name('open-items.data');
        Route::get('/open-items/{openItem}', [OpenItemController::class, 'show'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-open-items.view')->name('open-items.show');
        Route::get('/party-options', [OpenItemController::class, 'partyOptions'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-open-items.view')->name('party-options');
        Route::get('/aging', [OpenItemController::class, 'agingIndex'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-aging.view')->name('aging.index');
        Route::get('/aging/data', [OpenItemController::class, 'agingData'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-aging.view')->name('aging.data');
    });
    Route::get('/bank-accounts', [BankAccountController::class, 'index'])->middleware('permission:finance.bank-accounts.view')->name('bank-accounts.index');
    Route::get('/petty-cash', [PettyCashController::class, 'index'])->middleware('permission:finance.petty-cash.view')->name('petty-cash.index');
    Route::get('/petty-cash/clearings', [PettyCashClearingController::class, 'index'])->middleware('permission:finance.petty-cash-clearings.view')->name('petty-cash-clearings.index');
    Route::get('/petty-cash/clearings/data', [PettyCashClearingController::class, 'data'])->middleware('permission:finance.petty-cash-clearings.view')->name('petty-cash-clearings.data');
    Route::get('/petty-cash/clearings/create', [PettyCashClearingController::class, 'create'])->middleware('permission:finance.petty-cash-clearings.create')->name('petty-cash-clearings.create');
    Route::post('/petty-cash/clearings', [PettyCashClearingController::class, 'store'])->middleware('permission:finance.petty-cash-clearings.create')->name('petty-cash-clearings.store');
    Route::get('/petty-cash/clearings/{clearing}', [PettyCashClearingController::class, 'show'])->middleware('permission:finance.petty-cash-clearings.view')->name('petty-cash-clearings.show');
    Route::get('/petty-cash/clearings/{clearing}/attachments', [PettyCashAttachmentController::class, 'clearingIndex'])->middleware('permission:finance.petty-cash-clearings.view')->name('petty-cash-clearings.attachments.index');
    Route::post('/petty-cash/clearings/{clearing}/attachments', [PettyCashAttachmentController::class, 'clearingStore'])->middleware('permission:finance.petty-cash-clearings.update')->name('petty-cash-clearings.attachments.store');
    Route::get('/petty-cash/clearings/{clearing}/attachments/{attachment}/download', [PettyCashAttachmentController::class, 'clearingDownload'])->middleware('permission:finance.petty-cash-clearings.view')->name('petty-cash-clearings.attachments.download');
    Route::get('/petty-cash/clearings/{clearing}/attachments/{attachment}/preview', [PettyCashAttachmentController::class, 'clearingPreview'])->middleware('permission:finance.petty-cash-clearings.view')->name('petty-cash-clearings.attachments.preview');
    Route::delete('/petty-cash/clearings/{clearing}/attachments/{attachment}', [PettyCashAttachmentController::class, 'clearingDestroy'])->middleware('permission:finance.petty-cash-clearings.update')->name('petty-cash-clearings.attachments.destroy');
    Route::get('/petty-cash/clearings/{clearing}/edit', [PettyCashClearingController::class, 'edit'])->middleware('permission:finance.petty-cash-clearings.update')->name('petty-cash-clearings.edit');
    Route::put('/petty-cash/clearings/{clearing}', [PettyCashClearingController::class, 'update'])->middleware('permission:finance.petty-cash-clearings.update')->name('petty-cash-clearings.update');
    Route::put('/petty-cash/clearings/{clearing}/submit', [PettyCashClearingController::class, 'submit'])->middleware('permission:finance.petty-cash-clearings.submit')->name('petty-cash-clearings.submit');
    Route::put('/petty-cash/clearings/{clearing}/approve', [PettyCashClearingController::class, 'approve'])->middleware('permission:finance.petty-cash-clearings.approve')->name('petty-cash-clearings.approve');
    Route::put('/petty-cash/clearings/{clearing}/reject', [PettyCashClearingController::class, 'reject'])->middleware('permission:finance.petty-cash-clearings.approve')->name('petty-cash-clearings.reject');
    Route::delete('/petty-cash/clearings/{clearing}', [PettyCashClearingController::class, 'destroy'])->middleware('permission:finance.petty-cash-clearings.update')->name('petty-cash-clearings.destroy');
    Route::post('/petty-cash/clearings/{clearing}/post', [PettyCashClearingController::class, 'post'])->middleware('permission:finance.petty-cash-clearings.post')->name('petty-cash-clearings.post');
    Route::put('/petty-cash/clearings/{clearing}/reverse', [PettyCashClearingController::class, 'reverse'])->middleware('permission:finance.petty-cash-clearings.reverse')->name('petty-cash-clearings.reverse');
    Route::put('/petty-cash/clearings/{clearing}/void', [PettyCashClearingController::class, 'void'])->middleware('permission:finance.petty-cash-clearings.void')->name('petty-cash-clearings.void');
    Route::get('/petty-cash-funds', [PettyCashFundController::class, 'index'])->middleware('permission:finance.petty-cash.manage-funds')->name('petty-cash-funds.index');
    Route::get('/petty-cash-funds/data', [PettyCashFundController::class, 'data'])->middleware('permission:finance.petty-cash.manage-funds')->name('petty-cash-funds.data');
    Route::get('/petty-cash-funds/create', [PettyCashFundController::class, 'create'])->middleware('permission:finance.petty-cash.manage-funds')->name('petty-cash-funds.create');
    Route::post('/petty-cash-funds', [PettyCashFundController::class, 'store'])->middleware('permission:finance.petty-cash.manage-funds')->name('petty-cash-funds.store');
    Route::get('/petty-cash-funds/{fund}/edit', [PettyCashFundController::class, 'edit'])->middleware('permission:finance.petty-cash.manage-funds')->name('petty-cash-funds.edit');
    Route::put('/petty-cash-funds/{fund}', [PettyCashFundController::class, 'update'])->middleware('permission:finance.petty-cash.manage-funds')->name('petty-cash-funds.update');
    Route::delete('/petty-cash-funds/{fund}', [PettyCashFundController::class, 'destroy'])->middleware('permission:finance.petty-cash.manage-funds')->name('petty-cash-funds.destroy');
    Route::get('/petty-cash/top-ups', [PettyCashTopUpController::class, 'index'])->middleware('permission:finance.petty-cash-top-ups.view')->name('petty-cash-top-ups.index');
    Route::get('/petty-cash/top-ups/data', [PettyCashTopUpController::class, 'data'])->middleware('permission:finance.petty-cash-top-ups.view')->name('petty-cash-top-ups.data');
    Route::get('/petty-cash/top-ups/create', [PettyCashTopUpController::class, 'create'])->middleware('permission:finance.petty-cash-top-ups.create')->name('petty-cash-top-ups.create');
    Route::post('/petty-cash/top-ups', [PettyCashTopUpController::class, 'store'])->middleware('permission:finance.petty-cash-top-ups.create')->name('petty-cash-top-ups.store');
    Route::get('/petty-cash/top-ups/{topUp}', [PettyCashTopUpController::class, 'show'])->middleware('permission:finance.petty-cash-top-ups.view')->name('petty-cash-top-ups.show');
    Route::get('/petty-cash/top-ups/{topUp}/edit', [PettyCashTopUpController::class, 'edit'])->middleware('permission:finance.petty-cash-top-ups.update')->name('petty-cash-top-ups.edit');
    Route::put('/petty-cash/top-ups/{topUp}', [PettyCashTopUpController::class, 'update'])->middleware('permission:finance.petty-cash-top-ups.update')->name('petty-cash-top-ups.update');
    Route::put('/petty-cash/top-ups/{topUp}/submit', [PettyCashTopUpController::class, 'submit'])->middleware('permission:finance.petty-cash-top-ups.submit')->name('petty-cash-top-ups.submit');
    Route::put('/petty-cash/top-ups/{topUp}/approve', [PettyCashTopUpController::class, 'approve'])->middleware('permission:finance.petty-cash-top-ups.approve')->name('petty-cash-top-ups.approve');
    Route::put('/petty-cash/top-ups/{topUp}/reject', [PettyCashTopUpController::class, 'reject'])->middleware('permission:finance.petty-cash-top-ups.approve')->name('petty-cash-top-ups.reject');
    Route::delete('/petty-cash/top-ups/{topUp}', [PettyCashTopUpController::class, 'destroy'])->middleware('permission:finance.petty-cash-top-ups.update')->name('petty-cash-top-ups.destroy');
    Route::put('/petty-cash/top-ups/{topUp}/void', [PettyCashTopUpController::class, 'void'])->middleware('permission:finance.petty-cash-top-ups.void')->name('petty-cash-top-ups.void');
    Route::post('/petty-cash/top-ups/{topUp}/post', [PettyCashTopUpController::class, 'post'])->middleware('permission:finance.petty-cash-top-ups.post')->name('petty-cash-top-ups.post');
    Route::put('/petty-cash/top-ups/{topUp}/reverse', [PettyCashTopUpController::class, 'reverse'])->middleware('permission:finance.petty-cash-top-ups.reverse')->name('petty-cash-top-ups.reverse');
    Route::get('/petty-cash/create', [PettyCashController::class, 'create'])->middleware('permission:finance.petty-cash.create')->name('petty-cash.create');
    Route::get('/petty-cash/data', [PettyCashController::class, 'data'])->middleware('permission:finance.petty-cash.view')->name('petty-cash.data');
    Route::post('/petty-cash', [PettyCashController::class, 'store'])->middleware('permission:finance.petty-cash.create')->name('petty-cash.store');
    Route::get('/petty-cash/{voucher}', [PettyCashController::class, 'show'])->middleware('permission:finance.petty-cash.view')->name('petty-cash.show');
    Route::get('/petty-cash/{voucher}/attachments', [PettyCashAttachmentController::class, 'voucherIndex'])->middleware('permission:finance.petty-cash.view')->name('petty-cash.attachments.index');
    Route::post('/petty-cash/{voucher}/attachments', [PettyCashAttachmentController::class, 'voucherStore'])->middleware('permission:finance.petty-cash.update')->name('petty-cash.attachments.store');
    Route::get('/petty-cash/{voucher}/attachments/{attachment}/download', [PettyCashAttachmentController::class, 'voucherDownload'])->middleware('permission:finance.petty-cash.view')->name('petty-cash.attachments.download');
    Route::get('/petty-cash/{voucher}/attachments/{attachment}/preview', [PettyCashAttachmentController::class, 'voucherPreview'])->middleware('permission:finance.petty-cash.view')->name('petty-cash.attachments.preview');
    Route::delete('/petty-cash/{voucher}/attachments/{attachment}', [PettyCashAttachmentController::class, 'voucherDestroy'])->middleware('permission:finance.petty-cash.update')->name('petty-cash.attachments.destroy');
    Route::get('/petty-cash/{voucher}/edit', [PettyCashController::class, 'edit'])->middleware('permission:finance.petty-cash.update')->name('petty-cash.edit');
    Route::put('/petty-cash/{voucher}', [PettyCashController::class, 'update'])->middleware('permission:finance.petty-cash.update')->name('petty-cash.update');
    Route::put('/petty-cash/{voucher}/submit', [PettyCashController::class, 'submit'])->middleware('permission:finance.petty-cash.submit')->name('petty-cash.submit');
    Route::put('/petty-cash/{voucher}/approve', [PettyCashController::class, 'approve'])->middleware('permission:finance.petty-cash.approve')->name('petty-cash.approve');
    Route::put('/petty-cash/{voucher}/reject', [PettyCashController::class, 'reject'])->middleware('permission:finance.petty-cash.approve')->name('petty-cash.reject');
    Route::delete('/petty-cash/{voucher}', [PettyCashController::class, 'destroy'])->middleware('permission:finance.petty-cash.update')->name('petty-cash.destroy');
    Route::put('/petty-cash/{voucher}/void', [PettyCashController::class, 'void'])->middleware('permission:finance.petty-cash.void')->name('petty-cash.void');
    Route::post('/petty-cash/{voucher}/post', [PettyCashController::class, 'post'])->middleware('permission:finance.petty-cash.post')->name('petty-cash.post');
    Route::put('/petty-cash/{voucher}/reverse', [PettyCashController::class, 'reverse'])->middleware('permission:finance.petty-cash.reverse')->name('petty-cash.reverse');
    Route::get('/bank-accounts/account-options', [BankAccountController::class, 'accountOptions'])->middleware('permission:finance.bank-accounts.view')->name('bank-accounts.account-options');
    Route::get('/bank-accounts/data', [BankAccountController::class, 'data'])->middleware('permission:finance.bank-accounts.view')->name('bank-accounts.data');
    Route::get('/bank-accounts/create', [BankAccountController::class, 'create'])->middleware('permission:finance.bank-accounts.create')->name('bank-accounts.create');
    Route::post('/bank-accounts', [BankAccountController::class, 'store'])->middleware('permission:finance.bank-accounts.create')->name('bank-accounts.store');
    Route::get('/bank-accounts/{bankAccount}/edit', [BankAccountController::class, 'edit'])->middleware('permission:finance.bank-accounts.update')->name('bank-accounts.edit');
    Route::put('/bank-accounts/{bankAccount}', [BankAccountController::class, 'update'])->middleware('permission:finance.bank-accounts.update')->name('bank-accounts.update');
    Route::delete('/bank-accounts/{bankAccount}', [BankAccountController::class, 'destroy'])->middleware('permission:finance.bank-accounts.delete')->name('bank-accounts.destroy');
    Route::get('/payment-terms', [PaymentTermController::class, 'index'])->middleware('permission:finance.payment-terms.view')->name('payment-terms.index');
    Route::get('/payment-terms/data', [PaymentTermController::class, 'data'])->middleware('permission:finance.payment-terms.view')->name('payment-terms.data');
    Route::get('/payment-terms/create', [PaymentTermController::class, 'create'])->middleware('permission:finance.payment-terms.create')->name('payment-terms.create');
    Route::post('/payment-terms', [PaymentTermController::class, 'store'])->middleware('permission:finance.payment-terms.create')->name('payment-terms.store');
    Route::get('/payment-terms/{paymentTerm}/edit', [PaymentTermController::class, 'edit'])->middleware('permission:finance.payment-terms.update')->name('payment-terms.edit');
    Route::put('/payment-terms/{paymentTerm}', [PaymentTermController::class, 'update'])->middleware('permission:finance.payment-terms.update')->name('payment-terms.update');
    Route::delete('/payment-terms/{paymentTerm}', [PaymentTermController::class, 'destroy'])->middleware('permission:finance.payment-terms.delete')->name('payment-terms.destroy');
    Route::get('/other-categories', [OtherCategoryController::class, 'index'])->middleware('permission:finance.other-categories.view')->name('other-categories.index');
    Route::get('/other-categories/account-options', [OtherCategoryController::class, 'accountOptions'])->middleware('permission:finance.other-categories.view')->name('other-categories.account-options');
    Route::get('/other-categories/data', [OtherCategoryController::class, 'data'])->middleware('permission:finance.other-categories.view')->name('other-categories.data');
    Route::get('/other-categories/create', [OtherCategoryController::class, 'create'])->middleware('permission:finance.other-categories.create')->name('other-categories.create');
    Route::post('/other-categories', [OtherCategoryController::class, 'store'])->middleware('permission:finance.other-categories.create')->name('other-categories.store');
    Route::get('/other-categories/{otherCategory}/edit', [OtherCategoryController::class, 'edit'])->middleware('permission:finance.other-categories.update')->name('other-categories.edit');
    Route::put('/other-categories/{otherCategory}', [OtherCategoryController::class, 'update'])->middleware('permission:finance.other-categories.update')->name('other-categories.update');
    Route::delete('/other-categories/{otherCategory}', [OtherCategoryController::class, 'destroy'])->middleware('permission:finance.other-categories.delete')->name('other-categories.destroy');
    Route::redirect('/document-sequences', '/settings/document-sequences')->middleware('permission:finance.document-sequences.view')->name('document-sequences.index');
    Route::redirect('/document-sequences/data', '/settings/document-sequences/data')->middleware('permission:finance.document-sequences.view')->name('document-sequences.data');
    Route::get('/document-sequences/{documentSequence}/edit', fn (DocumentSequence $documentSequence) => redirect()->route('settings.document-sequences.edit', $documentSequence))->middleware('permission:finance.document-sequences.update')->name('document-sequences.edit');
    Route::put('/document-sequences/{documentSequence}', [DocumentSequenceController::class, 'update'])->middleware('permission:finance.document-sequences.update')->name('document-sequences.update');
    Route::get('/settlements', [SettlementController::class, 'index'])->middleware('permission:finance.settlements.view')->name('settlements.index');
    Route::get('/settlements/data', [SettlementController::class, 'data'])->middleware('permission:finance.settlements.view')->name('settlements.data');
    Route::get('/settlements/party-options', [SettlementController::class, 'partyOptions'])->middleware('permission:finance.settlements.create')->name('settlements.party-options');
    Route::get('/settlements/open-item-options', [SettlementController::class, 'openItemOptions'])->middleware('permission:finance.settlements.create')->name('settlements.open-item-options');
    Route::get('/settlements/create', [SettlementController::class, 'create'])->middleware('permission:finance.settlements.create')->name('settlements.create');
    Route::post('/settlements', [SettlementController::class, 'store'])->middleware('permission:finance.settlements.create')->name('settlements.store');
    Route::get('/settlements/{settlement}', [SettlementController::class, 'show'])->middleware('permission:finance.settlements.view')->name('settlements.show');
    Route::put('/settlements/{settlement}/approve', [SettlementController::class, 'approve'])->middleware('permission:finance.settlements.approve')->name('settlements.approve');
    Route::put('/settlements/{settlement}/void', [SettlementController::class, 'void'])->middleware('permission:finance.settlements.void')->name('settlements.void');
    Route::post('/settlements/{settlement}/post', [SettlementController::class, 'post'])->middleware('permission:finance.settlements.post')->name('settlements.post');
    Route::post('/settlements/{settlement}/advance-deposit', [SettlementController::class, 'createAdvanceDeposit'])->middleware('permission:finance.advance-deposits.create')->name('settlements.advance-deposit');
    Route::put('/settlements/{settlement}/reverse', [SettlementController::class, 'reverse'])->middleware('permission:finance.settlements.reverse')->name('settlements.reverse');
    Route::get('/internal-transfers', [InternalTransferController::class, 'index'])->middleware('permission:finance.internal-transfers.view')->name('internal-transfers.index');
    Route::get('/internal-transfers/data', [InternalTransferController::class, 'data'])->middleware('permission:finance.internal-transfers.view')->name('internal-transfers.data');
    Route::get('/internal-transfers/create', [InternalTransferController::class, 'create'])->middleware('permission:finance.internal-transfers.create')->name('internal-transfers.create');
    Route::post('/internal-transfers', [InternalTransferController::class, 'store'])->middleware('permission:finance.internal-transfers.create')->name('internal-transfers.store');
    Route::get('/internal-transfers/{transfer}', [InternalTransferController::class, 'show'])->middleware('permission:finance.internal-transfers.view')->name('internal-transfers.show');
    Route::get('/internal-transfers/{transfer}/edit', [InternalTransferController::class, 'edit'])->middleware('permission:finance.internal-transfers.update')->name('internal-transfers.edit');
    Route::put('/internal-transfers/{transfer}', [InternalTransferController::class, 'update'])->middleware('permission:finance.internal-transfers.update')->name('internal-transfers.update');
    Route::delete('/internal-transfers/{transfer}', [InternalTransferController::class, 'destroy'])->middleware('permission:finance.internal-transfers.delete')->name('internal-transfers.destroy');
    Route::put('/internal-transfers/{transfer}/submit', [InternalTransferController::class, 'submit'])->middleware('permission:finance.internal-transfers.submit')->name('internal-transfers.submit');
    Route::put('/internal-transfers/{transfer}/approve', [InternalTransferController::class, 'approve'])->middleware('permission:finance.internal-transfers.approve')->name('internal-transfers.approve');
    Route::put('/internal-transfers/{transfer}/void', [InternalTransferController::class, 'void'])->middleware('permission:finance.internal-transfers.void')->name('internal-transfers.void');
    Route::post('/internal-transfers/{transfer}/post', [InternalTransferController::class, 'post'])->middleware('permission:finance.internal-transfers.post')->name('internal-transfers.post');
    Route::put('/internal-transfers/{transfer}/reverse', [InternalTransferController::class, 'reverse'])->middleware('permission:finance.internal-transfers.reverse')->name('internal-transfers.reverse');
    Route::get('/pre-payment-vouchers', [PaymentVoucherController::class, 'index'])->middleware('permission:finance.payment-vouchers.view')->name('pre-payment-vouchers.index');
    Route::get('/pre-payment-vouchers/data', [PaymentVoucherController::class, 'data'])->middleware('permission:finance.payment-vouchers.view')->name('pre-payment-vouchers.data');
    Route::get('/pre-payment-vouchers/create', [PaymentVoucherController::class, 'create'])->middleware('permission:finance.payment-vouchers.create')->name('pre-payment-vouchers.create');
    Route::get('/payment-vouchers', [PaymentVoucherController::class, 'index'])->middleware('permission:finance.payment-vouchers.view')->name('payment-vouchers.index');
    Route::get('/commission-payouts', [CommissionPayoutController::class, 'index'])->middleware('permission:finance.commission-payouts.view')->name('commission-payouts.index');
    Route::get('/commission-payouts/data', [CommissionPayoutController::class, 'data'])->middleware('permission:finance.commission-payouts.view')->name('commission-payouts.data');
    Route::get('/commission-payouts/{commissionPaymentBatch}', [CommissionPayoutController::class, 'show'])->middleware('permission:finance.commission-payouts.view')->name('commission-payouts.show');
    Route::post('/commission-payouts/{commissionPaymentBatch}/verify', [CommissionPayoutController::class, 'verify'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.verify');
    Route::post('/commission-payouts/{commissionPaymentBatch}/cancel', [CommissionPayoutController::class, 'cancel'])->middleware('permission:finance.commission-payouts.void')->name('commission-payouts.cancel');
    Route::get('/commission-payouts/{commissionPaymentBatch}/payouts/create', [CommissionPayoutController::class, 'createPayout'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.payouts.create');
    Route::post('/commission-payouts/{commissionPaymentBatch}/payouts', [CommissionPayoutController::class, 'storePayout'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.payouts.store');
    Route::get('/commission-payouts/{commissionPaymentBatch}/payouts/{payout}', [CommissionPayoutController::class, 'showPayout'])->middleware('permission:finance.commission-payouts.view')->name('commission-payouts.payouts.show');
    Route::post('/commission-payouts/{commissionPaymentBatch}/payouts/{payout}/post', [CommissionPayoutController::class, 'postPayout'])->middleware('permission:finance.commission-payouts.post')->name('commission-payouts.payouts.post');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests/create-all', [CommissionPayoutController::class, 'createAllRequests'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.requests.create-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests/submit-all', [CommissionPayoutController::class, 'submitAllRequests'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.requests.submit-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests/approve-all', [CommissionPayoutController::class, 'approveAllRequests'])->middleware('permission:finance.commission-payouts.post')->name('commission-payouts.requests.approve-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/vouchers/create-all', [CommissionPayoutController::class, 'createAllVouchers'])->middleware('permission:finance.payment-vouchers.create')->name('commission-payouts.vouchers.create-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests/cancel-all', [CommissionPayoutController::class, 'cancelAllRequests'])->middleware('permission:finance.commission-payouts.void')->name('commission-payouts.requests.cancel-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests', [CommissionPayoutController::class, 'createRequest'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.requests.store');
    Route::get('/commission-requests/{commissionRequest}', [CommissionPayoutController::class, 'showRequest'])->middleware('permission:finance.commission-payouts.view')->name('commission-requests.show');
    Route::post('/commission-requests/{commissionRequest}/submit', [CommissionPayoutController::class, 'submitRequest'])->middleware('permission:finance.commission-payouts.create')->name('commission-requests.submit');
    Route::post('/commission-requests/{commissionRequest}/approve', [CommissionPayoutController::class, 'approveRequest'])->middleware('permission:finance.commission-payouts.post')->name('commission-requests.approve');
    Route::post('/commission-requests/{commissionRequest}/cancel', [CommissionPayoutController::class, 'cancelRequest'])->middleware('permission:finance.commission-payouts.void')->name('commission-requests.cancel');
    Route::get('/payment-vouchers/data', [PaymentVoucherController::class, 'data'])->middleware('permission:finance.payment-vouchers.view')->name('payment-vouchers.data');
    Route::get('/payment-vouchers/party-options', [PaymentVoucherController::class, 'partyOptions'])->middleware('permission:finance.payment-vouchers.create')->name('payment-vouchers.party-options');
    Route::get('/payment-vouchers/open-item-options', [PaymentVoucherController::class, 'openItemOptions'])->middleware('permission:finance.payment-vouchers.create')->name('payment-vouchers.open-item-options');
    Route::get('/payment-vouchers/create', [PaymentVoucherController::class, 'create'])->middleware('permission:finance.payment-vouchers.create')->name('payment-vouchers.create');
    Route::post('/payment-vouchers', [PaymentVoucherController::class, 'store'])->middleware('permission:finance.payment-vouchers.create')->name('payment-vouchers.store');
    Route::get('/payment-vouchers/{voucher}', [PaymentVoucherController::class, 'show'])->middleware('permission:finance.payment-vouchers.view')->name('payment-vouchers.show');
    Route::put('/payment-vouchers/{voucher}/submit', [PaymentVoucherController::class, 'submit'])->middleware('permission:finance.payment-vouchers.submit')->name('payment-vouchers.submit');
    Route::put('/payment-vouchers/{voucher}/approve', [PaymentVoucherController::class, 'approve'])->middleware('permission:finance.payment-vouchers.approve')->name('payment-vouchers.approve');
    Route::put('/payment-vouchers/{voucher}/void', [PaymentVoucherController::class, 'void'])->middleware('permission:finance.payment-vouchers.void')->name('payment-vouchers.void');
    Route::post('/payment-vouchers/{voucher}/settle', [PaymentVoucherController::class, 'settle'])->middleware('permission:finance.payment-vouchers.settle')->name('payment-vouchers.settle');
});
