<?php

use App\Modules\Finance\Controllers\AdvanceDepositController;
use App\Modules\Finance\Controllers\BankAccountController;
use App\Modules\Finance\Controllers\CommissionPayoutController;
use App\Modules\Finance\Controllers\DocumentSequenceController;
use App\Modules\Finance\Controllers\EntryController;
use App\Modules\Finance\Controllers\FinanceReportController;
use App\Modules\Finance\Controllers\OpenItemController;
use App\Modules\Finance\Controllers\OtherCategoryController;
use App\Modules\Finance\Controllers\PaymentTermController;
use App\Modules\Finance\Controllers\PaymentVoucherController;
use App\Modules\Finance\Controllers\SettlementController;
use App\Modules\Finance\Controllers\WorkflowController;
use App\Modules\Finance\Models\DocumentSequence;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'program:finance', 'warehouse'])->prefix('finance')->name('finance.')->group(function () {
    Route::get('/', EntryController::class)->middleware('permission:finance.dashboard.view')->name('index');
    Route::get('/workflow', [WorkflowController::class, 'index'])->name('workflow.index');
    Route::get('/reports/payment-activity', [FinanceReportController::class, 'paymentIndex'])->middleware('permission:finance.reports.payment-activity.view')->name('reports.payment-activity.index');
    Route::get('/reports/payment-activity/data', [FinanceReportController::class, 'paymentData'])->middleware('permission:finance.reports.payment-activity.view')->name('reports.payment-activity.data');
    Route::get('/advance-deposits', [AdvanceDepositController::class, 'index'])->middleware('permission:finance.advance-deposits.view')->name('advance-deposits.index');
    Route::get('/advance-deposits/data', [AdvanceDepositController::class, 'data'])->middleware('permission:finance.advance-deposits.view')->name('advance-deposits.data');
    Route::get('/advance-deposits/{advance}', [AdvanceDepositController::class, 'show'])->middleware('permission:finance.advance-deposits.view')->name('advance-deposits.show');
    Route::get('/advance-deposits/{advance}/applications/create', [AdvanceDepositController::class, 'createApplication'])->middleware('permission:finance.advance-deposits.apply')->name('advance-deposits.applications.create');
    Route::post('/advance-deposits/{advance}/applications', [AdvanceDepositController::class, 'storeApplication'])->middleware('permission:finance.advance-deposits.apply')->name('advance-deposits.applications.store');
    Route::prefix('receivables')->name('receivables.')->group(function () {
        Route::get('/open-items', [OpenItemController::class, 'index'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-open-items.view')->name('open-items.index');
        Route::get('/open-items/data', [OpenItemController::class, 'data'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-open-items.view')->name('open-items.data');
        Route::get('/open-items/{openItem}', [OpenItemController::class, 'show'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-open-items.view')->name('open-items.show');
        Route::get('/party-options', [OpenItemController::class, 'partyOptions'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-open-items.view')->name('party-options');
        Route::get('/aging', [OpenItemController::class, 'agingIndex'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-aging.view')->name('aging.index');
        Route::get('/aging/data', [OpenItemController::class, 'agingData'])->defaults('ledgerType', 'AR')->middleware('permission:finance.ar-aging.view')->name('aging.data');
    });
    Route::prefix('payables')->name('payables.')->group(function () {
        Route::get('/open-items', [OpenItemController::class, 'index'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-open-items.view')->name('open-items.index');
        Route::get('/open-items/data', [OpenItemController::class, 'data'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-open-items.view')->name('open-items.data');
        Route::get('/open-items/{openItem}', [OpenItemController::class, 'show'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-open-items.view')->name('open-items.show');
        Route::get('/party-options', [OpenItemController::class, 'partyOptions'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-open-items.view')->name('party-options');
        Route::get('/aging', [OpenItemController::class, 'agingIndex'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-aging.view')->name('aging.index');
        Route::get('/aging/data', [OpenItemController::class, 'agingData'])->defaults('ledgerType', 'AP')->middleware('permission:finance.ap-aging.view')->name('aging.data');
    });
    Route::get('/bank-accounts', [BankAccountController::class, 'index'])->middleware('permission:finance.bank-accounts.view')->name('bank-accounts.index');
    Route::get('/bank-accounts/account-options', [BankAccountController::class, 'accountOptions'])->middleware('permission:finance.bank-accounts.view')->name('bank-accounts.account-options');
    Route::get('/bank-accounts/data', [BankAccountController::class, 'data'])->middleware('permission:finance.bank-accounts.view')->name('bank-accounts.data');
    Route::get('/bank-accounts/create', [BankAccountController::class, 'create'])->middleware('permission:finance.bank-accounts.create')->name('bank-accounts.create');
    Route::post('/bank-accounts', [BankAccountController::class, 'store'])->middleware('permission:finance.bank-accounts.create')->name('bank-accounts.store');
    Route::get('/bank-accounts/{bankAccount}/edit', [BankAccountController::class, 'edit'])->middleware('permission:finance.bank-accounts.update')->name('bank-accounts.edit');
    Route::put('/bank-accounts/{bankAccount}', [BankAccountController::class, 'update'])->middleware('permission:finance.bank-accounts.update')->name('bank-accounts.update');
    Route::delete('/bank-accounts/{bankAccount}', [BankAccountController::class, 'destroy'])->middleware('permission:finance.bank-accounts.delete')->name('bank-accounts.destroy');
    Route::get('/payment-terms', [PaymentTermController::class, 'index'])->middleware('permission:finance.payment-terms.view')->name('payment-terms.index');
    Route::get('/payment-terms/data', [PaymentTermController::class, 'data'])->middleware('permission:finance.payment-terms.view')->name('payment-terms.data');
    Route::get('/payment-terms/create', [PaymentTermController::class, 'create'])->middleware('permission:finance.payment-terms.create')->name('payment-terms.create');
    Route::post('/payment-terms', [PaymentTermController::class, 'store'])->middleware('permission:finance.payment-terms.create')->name('payment-terms.store');
    Route::get('/payment-terms/{paymentTerm}/edit', [PaymentTermController::class, 'edit'])->middleware('permission:finance.payment-terms.update')->name('payment-terms.edit');
    Route::put('/payment-terms/{paymentTerm}', [PaymentTermController::class, 'update'])->middleware('permission:finance.payment-terms.update')->name('payment-terms.update');
    Route::delete('/payment-terms/{paymentTerm}', [PaymentTermController::class, 'destroy'])->middleware('permission:finance.payment-terms.delete')->name('payment-terms.destroy');
    Route::get('/other-categories', [OtherCategoryController::class, 'index'])->middleware('permission:finance.other-categories.view')->name('other-categories.index');
    Route::get('/other-categories/account-options', [OtherCategoryController::class, 'accountOptions'])->middleware('permission:finance.other-categories.view')->name('other-categories.account-options');
    Route::get('/other-categories/data', [OtherCategoryController::class, 'data'])->middleware('permission:finance.other-categories.view')->name('other-categories.data');
    Route::get('/other-categories/create', [OtherCategoryController::class, 'create'])->middleware('permission:finance.other-categories.create')->name('other-categories.create');
    Route::post('/other-categories', [OtherCategoryController::class, 'store'])->middleware('permission:finance.other-categories.create')->name('other-categories.store');
    Route::get('/other-categories/{otherCategory}/edit', [OtherCategoryController::class, 'edit'])->middleware('permission:finance.other-categories.update')->name('other-categories.edit');
    Route::put('/other-categories/{otherCategory}', [OtherCategoryController::class, 'update'])->middleware('permission:finance.other-categories.update')->name('other-categories.update');
    Route::delete('/other-categories/{otherCategory}', [OtherCategoryController::class, 'destroy'])->middleware('permission:finance.other-categories.delete')->name('other-categories.destroy');
    Route::redirect('/document-sequences', '/settings/document-sequences')->middleware('permission:finance.document-sequences.view')->name('document-sequences.index');
    Route::redirect('/document-sequences/data', '/settings/document-sequences/data')->middleware('permission:finance.document-sequences.view')->name('document-sequences.data');
    Route::get('/document-sequences/{documentSequence}/edit', fn (DocumentSequence $documentSequence) => redirect()->route('settings.document-sequences.edit', $documentSequence))->middleware('permission:finance.document-sequences.update')->name('document-sequences.edit');
    Route::put('/document-sequences/{documentSequence}', [DocumentSequenceController::class, 'update'])->middleware('permission:finance.document-sequences.update')->name('document-sequences.update');
    Route::get('/settlements', [SettlementController::class, 'index'])->middleware('permission:finance.settlements.view')->name('settlements.index');
    Route::get('/settlements/data', [SettlementController::class, 'data'])->middleware('permission:finance.settlements.view')->name('settlements.data');
    Route::get('/settlements/party-options', [SettlementController::class, 'partyOptions'])->middleware('permission:finance.settlements.create')->name('settlements.party-options');
    Route::get('/settlements/open-item-options', [SettlementController::class, 'openItemOptions'])->middleware('permission:finance.settlements.create')->name('settlements.open-item-options');
    Route::get('/settlements/create', [SettlementController::class, 'create'])->middleware('permission:finance.settlements.create')->name('settlements.create');
    Route::post('/settlements', [SettlementController::class, 'store'])->middleware('permission:finance.settlements.create')->name('settlements.store');
    Route::get('/settlements/{settlement}', [SettlementController::class, 'show'])->middleware('permission:finance.settlements.view')->name('settlements.show');
    Route::put('/settlements/{settlement}/approve', [SettlementController::class, 'approve'])->middleware('permission:finance.settlements.approve')->name('settlements.approve');
    Route::put('/settlements/{settlement}/void', [SettlementController::class, 'void'])->middleware('permission:finance.settlements.void')->name('settlements.void');
    Route::post('/settlements/{settlement}/post', [SettlementController::class, 'post'])->middleware('permission:finance.settlements.post')->name('settlements.post');
    Route::post('/settlements/{settlement}/advance-deposit', [SettlementController::class, 'createAdvanceDeposit'])->middleware('permission:finance.advance-deposits.create')->name('settlements.advance-deposit');
    Route::put('/settlements/{settlement}/reverse', [SettlementController::class, 'reverse'])->middleware('permission:finance.settlements.reverse')->name('settlements.reverse');
    Route::get('/payment-vouchers', [PaymentVoucherController::class, 'index'])->middleware('permission:finance.payment-vouchers.view')->name('payment-vouchers.index');
    Route::get('/commission-payouts', [CommissionPayoutController::class, 'index'])->middleware('permission:finance.commission-payouts.view')->name('commission-payouts.index');
    Route::get('/commission-payouts/data', [CommissionPayoutController::class, 'data'])->middleware('permission:finance.commission-payouts.view')->name('commission-payouts.data');
    Route::get('/commission-payouts/{commissionPaymentBatch}', [CommissionPayoutController::class, 'show'])->middleware('permission:finance.commission-payouts.view')->name('commission-payouts.show');
    Route::post('/commission-payouts/{commissionPaymentBatch}/verify', [CommissionPayoutController::class, 'verify'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.verify');
    Route::post('/commission-payouts/{commissionPaymentBatch}/cancel', [CommissionPayoutController::class, 'cancel'])->middleware('permission:finance.commission-payouts.void')->name('commission-payouts.cancel');
    Route::get('/commission-payouts/{commissionPaymentBatch}/payouts/create', [CommissionPayoutController::class, 'createPayout'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.payouts.create');
    Route::post('/commission-payouts/{commissionPaymentBatch}/payouts', [CommissionPayoutController::class, 'storePayout'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.payouts.store');
    Route::get('/commission-payouts/{commissionPaymentBatch}/payouts/{payout}', [CommissionPayoutController::class, 'showPayout'])->middleware('permission:finance.commission-payouts.view')->name('commission-payouts.payouts.show');
    Route::post('/commission-payouts/{commissionPaymentBatch}/payouts/{payout}/post', [CommissionPayoutController::class, 'postPayout'])->middleware('permission:finance.commission-payouts.post')->name('commission-payouts.payouts.post');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests/create-all', [CommissionPayoutController::class, 'createAllRequests'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.requests.create-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests/submit-all', [CommissionPayoutController::class, 'submitAllRequests'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.requests.submit-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests/approve-all', [CommissionPayoutController::class, 'approveAllRequests'])->middleware('permission:finance.commission-payouts.post')->name('commission-payouts.requests.approve-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/vouchers/create-all', [CommissionPayoutController::class, 'createAllVouchers'])->middleware('permission:finance.payment-vouchers.create')->name('commission-payouts.vouchers.create-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests/cancel-all', [CommissionPayoutController::class, 'cancelAllRequests'])->middleware('permission:finance.commission-payouts.void')->name('commission-payouts.requests.cancel-all');
    Route::post('/commission-payouts/{commissionPaymentBatch}/requests', [CommissionPayoutController::class, 'createRequest'])->middleware('permission:finance.commission-payouts.create')->name('commission-payouts.requests.store');
    Route::get('/commission-requests/{commissionRequest}', [CommissionPayoutController::class, 'showRequest'])->middleware('permission:finance.commission-payouts.view')->name('commission-requests.show');
    Route::post('/commission-requests/{commissionRequest}/submit', [CommissionPayoutController::class, 'submitRequest'])->middleware('permission:finance.commission-payouts.create')->name('commission-requests.submit');
    Route::post('/commission-requests/{commissionRequest}/approve', [CommissionPayoutController::class, 'approveRequest'])->middleware('permission:finance.commission-payouts.post')->name('commission-requests.approve');
    Route::post('/commission-requests/{commissionRequest}/cancel', [CommissionPayoutController::class, 'cancelRequest'])->middleware('permission:finance.commission-payouts.void')->name('commission-requests.cancel');
    Route::get('/payment-vouchers/data', [PaymentVoucherController::class, 'data'])->middleware('permission:finance.payment-vouchers.view')->name('payment-vouchers.data');
    Route::get('/payment-vouchers/party-options', [PaymentVoucherController::class, 'partyOptions'])->middleware('permission:finance.payment-vouchers.create')->name('payment-vouchers.party-options');
    Route::get('/payment-vouchers/open-item-options', [PaymentVoucherController::class, 'openItemOptions'])->middleware('permission:finance.payment-vouchers.create')->name('payment-vouchers.open-item-options');
    Route::get('/payment-vouchers/create', [PaymentVoucherController::class, 'create'])->middleware('permission:finance.payment-vouchers.create')->name('payment-vouchers.create');
    Route::post('/payment-vouchers', [PaymentVoucherController::class, 'store'])->middleware('permission:finance.payment-vouchers.create')->name('payment-vouchers.store');
    Route::get('/payment-vouchers/{voucher}', [PaymentVoucherController::class, 'show'])->middleware('permission:finance.payment-vouchers.view')->name('payment-vouchers.show');
    Route::put('/payment-vouchers/{voucher}/submit', [PaymentVoucherController::class, 'submit'])->middleware('permission:finance.payment-vouchers.submit')->name('payment-vouchers.submit');
    Route::put('/payment-vouchers/{voucher}/approve', [PaymentVoucherController::class, 'approve'])->middleware('permission:finance.payment-vouchers.approve')->name('payment-vouchers.approve');
    Route::put('/payment-vouchers/{voucher}/void', [PaymentVoucherController::class, 'void'])->middleware('permission:finance.payment-vouchers.void')->name('payment-vouchers.void');
    Route::post('/payment-vouchers/{voucher}/settle', [PaymentVoucherController::class, 'settle'])->middleware('permission:finance.payment-vouchers.settle')->name('payment-vouchers.settle');
});
