@extends('Pos::layout')
@section('title', 'สร้างใบวางบิล | POS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><p class="eyebrow mb-2">POS / BILLING NOTE</p><h1 class="h3 mb-2">สร้างใบวางบิล</h1><p class="text-secondary mb-0">เลือก Invoice หรือใบขายเชื่อที่ Post แล้วและยังมียอดคงค้างของลูกค้ารายเดียวกัน</p></div><a class="btn btn-outline-secondary" href="{{ route('pos.billing-notes.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับ</a></div>
<form id="billing-note-form" method="post" action="{{ route('pos.billing-notes.store') }}"><div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-12 col-md-4"><label class="form-label">ลูกค้า <span class="text-danger">*</span></label><select class="form-select" id="billing-party" name="party_id" required><option value="">ค้นหาลูกค้า</option></select></div><div class="col-12 col-md-3"><label class="form-label">วันที่วางบิล <span class="text-danger">*</span></label><input class="form-control" type="date" name="document_date" value="{{ $documentDate }}" required></div><div class="col-12 col-md-3"><label class="form-label">กำหนดชำระ</label><input class="form-control" type="date" name="due_date"></div><div class="col-12 col-md-2"><label class="form-label">ยอดรวม</label><input class="form-control text-end" id="billing-total" value="0.00" readonly></div><div class="col-12"><label class="form-label">เอกสารที่ต้องการวางบิล <span class="text-danger">*</span></label><select class="form-select" id="billing-invoices" name="billing_source_keys[]" multiple required></select><div class="form-text">เลือกได้เฉพาะ Invoice และใบขายเชื่อที่ลงบัญชีแล้วและยังไม่ถูกวางบิล</div></div><div class="col-12"><label class="form-label">หมายเหตุ</label><textarea class="form-control" name="description" rows="3" maxlength="500"></textarea></div></div></div><div class="card-footer bg-transparent border-0 p-3 p-lg-4"><button class="btn btn-dark" type="submit">บันทึกร่าง</button> <a class="btn btn-outline-secondary" href="{{ route('pos.billing-notes.index') }}">ยกเลิก</a></div></div></form></div>
@endsection
@push('scripts')
<script>
$(function(){var party=$('#billing-party'),invoices=$('#billing-invoices'); window.erpInitSelect2(party,{ajax:{url:'{{ route('pos.billing-notes.party-options') }}',dataType:'json',delay:250,data:function(p){return{q:p.term||''}},processResults:function(d){return d;}}}); window.erpInitSelect2(invoices,{multiple:true,ajax:{url:'{{ route('pos.billing-notes.invoice-options') }}',dataType:'json',delay:250,data:function(p){return{q:p.term||'',party_id:party.val()}},processResults:function(d){return d;}}}); party.on('change',function(){invoices.val(null).trigger('change');}); invoices.on('change',function(){var total=0;invoices.select2('data').forEach(function(x){total+=Number(x.amount||0);});$('#billing-total').val(total.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}));}); window.erpAjaxForm({form:'#billing-note-form',url:'{{ route('pos.billing-notes.store') }}',method:'POST',redirect:true});});
</script>
@endpush
