@extends('Pos::layout')
@section('title', 'ใบวางบิล | POS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><p class="eyebrow mb-2">POS / RECEIVABLES</p><h1 class="h3 mb-2">ใบวางบิล</h1><p class="text-secondary mb-0">รวม Invoice ที่ค้างชำระเพื่อแจ้งลูกค้าก่อนรับชำระ</p></div>@if(auth()->user()->hasPermission('pos.billing-notes.create'))<a class="btn btn-dark" href="{{ route('pos.billing-notes.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>สร้างใบวางบิล</a>@endif</div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">ตัวกรอง</h2><p class="text-secondary small mb-0">กรองตามสถานะและวันที่เอกสาร</p></div><button type="button" class="btn btn-sm btn-app-soft" id="billing-note-reset"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3 align-items-end"><div class="col-12 col-md-4"><label class="form-label" for="billing-note-status">สถานะ</label><select class="form-select" id="billing-note-status"><option value="">ทุกสถานะ</option><option value="DRAFT">ร่าง</option><option value="ISSUED">ออกใบวางบิลแล้ว</option><option value="CANCELLED">ยกเลิก</option></select></div><div class="col-12 col-md-3"><label class="form-label" for="billing-note-from">วันที่เริ่มต้น</label><input class="form-control" type="date" id="billing-note-from"></div><div class="col-12 col-md-3"><label class="form-label" for="billing-note-to">วันที่สิ้นสุด</label><input class="form-control" type="date" id="billing-note-to"></div><div class="col-12 col-md-2"><button class="btn btn-dark w-100" type="button" id="billing-note-filter">ค้นหา</button></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="billing-notes-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.billing-notes.data') }}"><thead><tr><th>เลขที่</th><th>วันที่</th><th>ลูกค้า</th><th class="text-end">จำนวน Invoice</th><th class="text-end">ยอดรวม</th><th>สถานะ</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')
<script>
$(function () { var t=$('#billing-notes-table'), text=$.fn.dataTable.render.text(), status={DRAFT:'app-status-neutral',ISSUED:'app-status-success',CANCELLED:'app-status-danger'}; var dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.status=$('#billing-note-status').val();d.date_from=$('#billing-note-from').val();d.date_to=$('#billing-note-to').val();}},order:[[1,'desc']],buttons:[window.erpExcelButton(t)],columns:[{data:'document_number',render:text.display},{data:'document_date',render:text.display},{data:'party_label',render:text.display},{data:'lines_count',className:'text-end',render:text.display},{data:'total_amount',className:'text-end',render:$.fn.dataTable.render.number(',', '.', 2)},{data:'status_label',render:function(v,type,row){return type==='display'?'<span class="badge '+(status[row.status]||'app-status-neutral')+'">'+text.display(v)+'</span>':v;}},{data:null,orderable:false,searchable:false,className:'text-end text-nowrap',render:function(v,type,row){return type==='display'?'<a class="btn btn-sm btn-app-soft" href="'+text.display(row.show_url)+'" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-show" aria-hidden="true"></i></a>':'';}}]})); $('#billing-note-filter').on('click',function(){dt.ajax.reload();}); $('#billing-note-reset').on('click',function(){$('#billing-note-status,#billing-note-from,#billing-note-to').val('');dt.ajax.reload();}); });
</script>
@endpush
