@extends('Accounting::layout')

@section('title', 'Bank Reconciliation | New ERP')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">ACCOUNTING / RECONCILIATION</p><h1 class="h3 mb-2">Bank Reconciliation</h1><p class="text-secondary mb-0">นำเข้า Bank Statement จาก CSV และเตรียมรายการสำหรับจับคู่กับ Journal</p></div>
    @if (session('success'))<div class="alert alert-success border-0 shadow-sm">{{ session('success') }}</div>@endif
    @if ($errors->any())<div class="alert alert-danger border-0 shadow-sm">{{ $errors->first() }}</div>@endif
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3"><div><h2 class="h6 mb-1">นำเข้า Bank Statement (CSV)</h2><p class="small text-secondary mb-0">รูปแบบคอลัมน์: วันที่, รายละเอียด, Reference, จำนวนเงิน, ยอดคงเหลือ · เงินเข้าเป็นบวก เงินออกเป็นลบ</p></div><a class="btn btn-outline-secondary btn-sm" href="{{ route('accounting.bank-reconciliation.template') }}"><i class="bx bx-download me-1" aria-hidden="true"></i>ดาวน์โหลด Template CSV</a></div><form method="post" action="{{ route('accounting.bank-reconciliation.store') }}" enctype="multipart/form-data" class="row g-3">@csrf<div class="col-12 col-md-4"><label class="form-label">บัญชีธนาคาร</label><select class="form-select" name="bank_account_id" required><option value="">เลือกบัญชี</option>@foreach($bankAccounts as $bank)<option value="{{ $bank->id }}">{{ $bank->code }} · {{ $bank->name }}</option>@endforeach</select></div><div class="col-12 col-md-4"><label class="form-label">วันที่ Statement</label><input class="form-control" type="date" name="statement_date" value="{{ now()->toDateString() }}" required></div><div class="col-6 col-md-2"><label class="form-label">ยอดยกมา</label><input class="form-control" type="number" step="0.01" name="opening_balance" value="0"></div><div class="col-6 col-md-2"><label class="form-label">ยอดปิด</label><input class="form-control" type="number" step="0.01" name="closing_balance" value="0"></div><div class="col-12 col-md-8"><input class="form-control" type="file" name="statement" accept=".csv,.txt" required></div><div class="col-12 col-md-4 text-md-end"><button class="btn btn-dark" type="submit"><i class="bx bx-upload me-1" aria-hidden="true"></i>นำเข้า CSV</button></div></form></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h6 mb-3">รายการ Statement ล่าสุด</h2><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>บัญชี</th><th>วันที่</th><th class="text-end">ยอดยกมา</th><th class="text-end">ยอดปิด</th><th>ไฟล์</th><th>สถานะ</th><th></th></tr></thead><tbody>@forelse($statements as $statement)<tr><td>{{ $statement->bankAccount->code }} · {{ $statement->bankAccount->name }}</td><td>{{ $statement->statement_date->format('d/m/Y') }}</td><td class="text-end">{{ number_format((float) $statement->opening_balance, 2) }}</td><td class="text-end">{{ number_format((float) $statement->closing_balance, 2) }}</td><td>{{ $statement->source_file_name ?: '—' }}</td><td><span class="badge {{ $statement->status === 'RECONCILED' ? 'text-bg-success' : 'text-bg-warning' }}">{{ $statement->status === 'RECONCILED' ? 'กระทบยอดแล้ว' : 'รอจับคู่' }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-dark" href="{{ route('accounting.bank-reconciliation.show', $statement) }}">เปิดรายการ</a></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-4">ยังไม่มี Bank Statement</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
