@extends('Accounting::layout')
@section('title', 'จับคู่ Bank Statement | New ERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex justify-content-between align-items-end mb-4"><div><p class="eyebrow mb-2">ACCOUNTING / BANK RECONCILIATION</p><h1 class="h3 mb-2">จับคู่รายการธนาคาร</h1><p class="text-secondary mb-0">{{ $bankStatement->bankAccount->code }} · {{ $bankStatement->statement_date->format('d/m/Y') }}</p></div><a class="btn btn-outline-dark" href="{{ route('accounting.bank-reconciliation.index') }}">กลับรายการ</a></div>@if(session('success'))<div class="alert alert-success border-0">{{ session('success') }}</div>@endif
@php($statementMovement = (float) $bankStatement->lines->sum('amount'))
@php($glMovement = (float) $bankStatement->lines->where('status', 'MATCHED')->sum(fn ($line) => (float) $line->matchedJournalLine?->debit - (float) $line->matchedJournalLine?->credit))
@php($difference = $statementMovement - $glMovement)
<div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">ยอดยกมา</div><div class="fs-5 fw-semibold">{{ number_format((float) $bankStatement->opening_balance, 2) }}</div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">Statement Movement</div><div class="fs-5 fw-semibold">{{ number_format($statementMovement, 2) }}</div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">GL Movement</div><div class="fs-5 fw-semibold">{{ number_format($glMovement, 2) }}</div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">ผลต่าง</div><div class="fs-5 fw-semibold {{ abs($difference) > 0.01 ? 'text-danger' : 'text-success' }}">{{ number_format($difference, 2) }}</div></div></div></div></div>
@if($errors->has('reconcile'))<div class="alert alert-danger border-0">{{ $errors->first('reconcile') }}</div>@endif
<div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">รายการ Statement</h2>@if($bankStatement->status !== 'RECONCILED')<form method="post" action="{{ route('accounting.bank-reconciliation.reconcile', $bankStatement) }}">@csrf<button class="btn btn-dark btn-sm" type="submit" @disabled($bankStatement->lines->contains(fn ($line) => $line->status !== 'MATCHED'))>ยืนยันกระทบยอด</button></form>@else<span class="badge text-bg-success">กระทบยอดแล้ว</span>@endif</div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>วันที่</th><th>รายละเอียด</th><th>Reference</th><th class="text-end">จำนวนเงิน</th><th>สถานะ/Journal</th></tr></thead><tbody>@foreach($bankStatement->lines as $line)<tr><td>{{ $line->transaction_date->format('d/m/Y') }}</td><td>{{ $line->description ?: '—' }}</td><td>{{ $line->reference ?: '—' }}</td><td class="text-end">{{ number_format((float) $line->amount, 2) }}</td><td>@if($line->status === 'MATCHED')<span class="badge text-bg-success">จับคู่แล้ว</span><div class="small text-secondary mt-1">{{ $line->matchedJournalLine?->entry?->entry_number ?: '—' }}</div>@else<span class="badge text-bg-warning">ยังไม่จับคู่</span>@php($lineCandidates = $candidatesByLine->get($line->id, collect()))<form method="post" action="{{ route('accounting.bank-reconciliation.match', $line) }}" class="d-flex gap-2 mt-2">@csrf<select class="form-select form-select-sm" name="journal_entry_line_id" required><option value="">{{ $lineCandidates->isEmpty() ? 'ไม่พบยอดตรงกัน' : 'เลือก Journal ที่ยอดตรงกัน' }}</option>@foreach($lineCandidates as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->entry->entry_number }} · {{ number_format((float) ($candidate->debit ?: $candidate->credit), 2) }} · {{ $candidate->description ?: $candidate->account->name }}</option>@endforeach</select><button class="btn btn-sm btn-outline-dark" type="submit" @disabled($lineCandidates->isEmpty())>จับคู่</button></form>@endif</td></tr>@endforeach</tbody></table></div></div></div></div>
@endsection
