@extends('Asset::layout')

@section('title', 'สถานที่สินทรัพย์ | New ERP')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / MASTER DATA</p><h1 class="h3 mb-2">สถานที่สินทรัพย์</h1><p class="text-secondary mb-0">ตำแหน่งสำหรับสาขา {{ $branch->code }} · {{ $branch->name }}</p></div>@if(auth()->user()->hasPermission('asset.locations.manage'))<a class="btn btn-app-primary" href="{{ route('asset.locations.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มสถานที่</a>@endif</div><div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">ตัวกรอง</h2><p class="small text-secondary mb-0">กรองตามสถานะก่อนดูรายการ</p></div><button class="btn btn-sm btn-app-soft" id="location-filter-reset" type="button"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-12 col-md-4"><label class="form-label" for="location-filter-status">สถานะ</label><select class="form-select" id="location-filter-status"><option value="">ทุกสถานะ</option><option value="1">ใช้งาน</option><option value="0">ปิดใช้งาน</option></select></div></div></div></div><div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="locations-table" data-url="{{ route('asset.locations.data') }}" data-can-manage="{{ auth()->user()->hasPermission('asset.locations.manage') ? '1' : '0' }}"><thead><tr><th>รหัส</th><th>ชื่อ</th><th>ประเภท</th><th>สถานที่แม่</th><th>คลัง</th><th>สถานะ</th>@if(auth()->user()->hasPermission('asset.locations.manage'))<th class="text-end">จัดการ</th>@endif</tr></thead></table></div></div></div></div>
@endsection

@push('scripts')
<script>
$(function(){var $table=$('#locations-table'),text=$.fn.dataTable.render.text(),types={BRANCH:'สาขา',WAREHOUSE:'คลัง',BUILDING:'อาคาร',FLOOR:'ชั้น',ROOM:'ห้อง',SITE:'พื้นที่',OTHER:'อื่น ๆ'},columns=[{data:'code',name:'asset_locations.code',render:text.display},{data:'name',name:'asset_locations.name',render:text.display},{data:'location_type',name:'asset_locations.location_type',render:function(v,t){return t==='display'?text.display(types[v]||v):v;}},{data:null,name:'parents.code',render:function(v,t,row){var x=row.parent_code?(row.parent_code+' · '+row.parent_name):'-';return t==='display'?text.display(x):x;}},{data:null,name:'warehouses.code',render:function(v,t,row){var x=row.warehouse_code?(row.warehouse_code+' · '+row.warehouse_name):'-';return t==='display'?text.display(x):x;}},{data:'is_active',name:'asset_locations.is_active',searchable:false,render:function(v,t){return t==='display'?'<span class="badge '+(v?'app-status-success':'app-status-neutral')+'">'+(v?'ใช้งาน':'ปิดใช้งาน')+'</span>':v;}}];if($table.data('can-manage'))columns.push({data:null,orderable:false,searchable:false,className:'text-end',render:function(v,t,row){if(t!=='display')return '';var a=[];if(row.edit_url)a.push('<a class="btn btn-sm btn-app-soft" href="'+text.display(row.edit_url)+'" title="แก้ไข" aria-label="แก้ไข"><i class="bx bx-edit" aria-hidden="true"></i></a>');if(row.delete_url)a.push('<button class="btn btn-sm btn-app-danger js-delete-location" data-url="'+text.display(row.delete_url)+'" type="button" title="ลบ" aria-label="ลบ"><i class="bx bx-trash" aria-hidden="true"></i></button>');return a.join(' ');}});var table=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(data){data.is_active=$('#location-filter-status').val();}},order:[[0,'asc']],buttons:[window.erpExcelButton($table)],columns:columns}));$('#location-filter-status').on('change',function(){table.ajax.reload();});$('#location-filter-reset').on('click',function(){$('#location-filter-status').val('');table.ajax.reload();});window.erpAjaxDelete({button:'.js-delete-location',reload:'#locations-table',confirm:'ยืนยันการลบสถานที่นี้หรือไม่?'});});
</script>
@endpush
