@extends('Wms::layout')
@php($moduleRoutePrefix = $moduleRoutePrefix ?? 'wms')
@php($editing = $receipt !== null)
@section('title', ($editing ? 'แก้ไข' : 'สร้าง').' Goods Receipt | Purchasing')
@section('content')
@if($editing && auth()->user()->hasPermission('wms.purchase-receipts.print'))<div class="mb-3"><a class="btn btn-sm btn-app-soft" target="_blank" href="{{route($moduleRoutePrefix.'.purchase-receipts.pdf',$receipt)}}">พิมพ์ PDF</a></div>@endif
<div class="container-fluid px-3 px-lg-4 py-4"><p class="eyebrow mb-2">PURCHASING / GOODS RECEIPT</p><h1 class="h3 mb-4">{{ $editing ? 'แก้ไข' : 'สร้าง' }} Goods Receipt</h1><div class="alert alert-warning border-0 small">เอกสารนี้ยังไม่ลง Stock, Cost Layer หรือ GL; หลังบันทึกสามารถอนุมัติ/ยกเลิกตามสิทธิ์ได้</div><form id="goods-receipt-form" method="POST" action="{{ $editing ? route($moduleRoutePrefix.'.purchase-receipts.update',$receipt) : route($moduleRoutePrefix.'.purchase-receipts.store') }}">@csrf @if($editing) @method('PUT') @endif<div class="card border-0 shadow-sm mb-4"><div class="card-body row g-3">@if(!$editing)<div class="col-md-6"><label class="form-label">Purchase Order</label><select id="receipt-po" class="form-select" name="purchase_order_id" data-url="{{ route($moduleRoutePrefix.'.purchase-receipts.purchase-options') }}" required></select></div>@else<div class="col-md-6"><label class="form-label">Purchase Order</label><input class="form-control" value="{{ $receipt->purchaseOrder?->document_number ?? $receipt->purchase_order_id }}" disabled></div>@endif@if($editing)<div class="col-md-3"><label class="form-label">เลขที่ Receipt</label><input class="form-control" value="{{ $receipt->receipt_number }}" disabled></div>@endif<div class="col-md-3"><label class="form-label">วันที่รับ</label><input class="form-control" type="date" name="business_date" value="{{ $today }}" required><div class="form-text">ระบบออกเลขตามสาขาและวันที่รับ</div></div><div class="col-12"><label class="form-label">หมายเหตุ</label><textarea class="form-control" name="description" rows="2">{{ $editing ? $receipt->description : '' }}</textarea></div>@if(!$editing)<input type="hidden" name="idempotency_key" value="gr-{{ now()->format('YmdHisv') }}">@endif</div></div><div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">รายการรับสินค้า</h2><button class="btn btn-app-soft btn-sm" type="button" id="add-receipt-line">เพิ่มรายการ</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>รายการ PO</th><th>จำนวนรับ</th><th>ต้นทุนรวม</th><th></th></tr></thead><tbody id="receipt-lines"></tbody></table></div><div class="mt-4"><button class="btn btn-dark" type="submit">บันทึกร่าง</button> <a class="btn btn-outline-secondary" href="{{ route($moduleRoutePrefix.'.purchase-receipts.index') }}">ยกเลิก</a></div></div></div></form></div>
@endsection
@push('scripts')
<script>$(function(){var po=$('#receipt-po'),body=$('#receipt-lines'),lineUrl='{{ route($moduleRoutePrefix.'.purchase-receipts.line-options') }}',n=0,available=[];function initSelect(s){window.erpInitSelect2(s,{theme:'bootstrap-5',placeholder:'ค้นหา PO line',allowClear:true});}function addLine(option){var i=n++,row=$('<tr><td><select class="form-select js-line" name="lines['+i+'][purchase_order_line_id]" required></select><div class="small text-secondary js-remaining"></div></td><td><input class="form-control text-end js-qty" type="number" min="0.00000001" step="0.00000001" name="lines['+i+'][purchase_qty]" required></td><td><input class="form-control text-end" type="number" min="0" step="0.00000001" name="lines['+i+'][total_cost]" value="0"></td><td><button type="button" class="btn btn-sm btn-outline-danger js-remove">ลบ</button></td></tr>');body.append(row);initSelect(row.find('.js-line'));if(option){row.find('.js-line').append(new Option(option.text,option.id,true,true)).trigger('change');applyOption(row,option);}else{available.forEach(function(o){row.find('.js-line').append(new Option(o.text,o.id,false,false));});}}function applyOption(row,option){row.find('.js-qty').attr('max',option.remaining_quantity).val(option.purchase_quantity||option.remaining_quantity);row.find('.js-remaining').text('คงเหลือ '+option.remaining_quantity);row.find('input[name$="[total_cost]"]').val(option.total_cost||0);}function loadLines(id){body.empty();$.getJSON(lineUrl,{purchase_order_id:id}).done(function(data){available=data.results||[];available.forEach(addLine);if(!available.length)Swal.fire({icon:'info',text:'PO นี้รับครบแล้วหรือไม่มีรายการสินค้า'});});}if(po.length){window.erpInitSelect2(po,{theme:'bootstrap-5',placeholder:'ค้นหา Purchase Order',allowClear:true,ajax:{url:po.data('url'),delay:250,data:function(p){return{q:p.term||'',page:p.page||1}},processResults:function(x){return x}}});po.on('change',function(){if(po.val())loadLines(po.val());else body.empty();});}else{@foreach($receipt?->lines ?? [] as $line) addLine({id:{{ $line->purchase_order_line_id }},text:'PO line #{{ $line->purchase_order_line_id }}',purchase_quantity:'{{ $line->purchase_quantity }}',remaining_quantity:'{{ $line->purchase_quantity }}',total_cost:'{{ $line->total_cost }}'}); @endforeach}$('#add-receipt-line').on('click',function(){if(po.length&&po.val())addLine();});body.on('change','.js-line',function(){var row=$(this).closest('tr'),o=available.find(function(x){return String(x.id)===String($(this).val());}.bind(this));if(o)applyOption(row,o);});body.on('click','.js-remove',function(){$(this).closest('tr').remove();});window.erpAjaxForm({form:'#goods-receipt-form',redirect:true});});</script>
@endpush
