@extends('Pos::layout')

@section('title', 'รายงาน Campaign ROI | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">POS / REPORTS</p><h1 class="h3 mb-2">รายงาน Campaign ROI</h1><p class="text-secondary mb-0">อ้างอิง HS/IV และใบรับคืนที่ Post แล้ว, ต้นทุนจริงจาก COGS, คอมมิชชั่นที่คำนวณแล้ว และค่าใช้จ่าย Campaign ของสาขาปัจจุบัน</p></div>
    <div class="alert alert-info">Promotion ที่ซ้อนกันจะแบ่งยอดขาย ต้นทุนขาย และคอมมิชชั่นตามสัดส่วนส่วนลดจริง จึงไม่ถูกนับซ้ำระหว่าง Campaign</div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3 align-items-end"><div class="col-md-3"><label for="campaign-roi-from" class="form-label">วันที่เริ่ม</label><input id="campaign-roi-from" type="date" class="form-control" value="{{ now()->startOfMonth()->format('Y-m-d') }}"></div><div class="col-md-3"><label for="campaign-roi-to" class="form-label">ถึงวันที่</label><input id="campaign-roi-to" type="date" class="form-control" value="{{ now()->endOfMonth()->format('Y-m-d') }}"></div><div class="col-md-4"><label for="campaign-roi-promotion" class="form-label">Campaign / Promotion</label><select id="campaign-roi-promotion" class="form-select" data-url="{{ route('pos.sales-reports.promotion-options') }}"><option value="">ทั้งหมด</option></select></div><div class="col-md-2"><button id="campaign-roi-filter" class="btn btn-outline-secondary" type="button"><i class="bx bx-filter-alt me-1" aria-hidden="true"></i>กรอง</button></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="campaign-roi-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.sales-reports.campaign-roi.data') }}"><thead><tr><th>Campaign</th><th>ผู้รับผิดชอบ</th><th>รูปแบบ</th><th class="text-end">ใช้</th><th class="text-end">ส่วนลด</th><th class="text-end">เป้ายอดขาย</th><th class="text-end">ยอดขายสุทธิ</th><th class="text-end">ต่างจากเป้า</th><th class="text-end">เป้า GP</th><th class="text-end">กำไรขั้นต้น</th><th class="text-end">ต่างจากเป้า GP</th><th class="text-end">งบประมาณ</th><th class="text-end">ค่าใช้จ่ายจริง</th><th class="text-end">คงเหลืองบ</th><th class="text-end">Contribution</th><th class="text-end">ROI</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>$(function(){var $table=$('#campaign-roi-table'),$promotion=$('#campaign-roi-promotion'),text=$.fn.dataTable.render.text(),money=$.fn.dataTable.render.number(',', '.', 2),percent=$.fn.dataTable.render.number(',', '.', 2),nullableMoney=function(v){return v===null?'—':money.display(v);};$promotion.select2({width:'100%',placeholder:'ค้นหา Campaign',allowClear:true,ajax:{url:$promotion.data('url'),dataType:'json',delay:250,data:function(p){return{q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});var report=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(d){d.date_from=$('#campaign-roi-from').val();d.date_to=$('#campaign-roi-to').val();d.promotion_id=$promotion.val();}},order:[[14,'desc']],buttons:[window.erpExcelButton($table)],columns:[{data:'promotion_code',render:function(v,t,row){return text.display(v+' · '+row.promotion_name);}},{data:'owner_name',render:function(v){return text.display(v||'—');}},{data:'scope_label',render:text.display},{data:'usage_count',className:'text-end',render:function(v){return Number(v||0).toLocaleString();}},{data:'promotion_discount_amount',className:'text-end',render:money},{data:'target_sales_amount',className:'text-end',render:nullableMoney},{data:'net_sales',className:'text-end',render:money},{data:'sales_target_variance',className:'text-end',render:nullableMoney},{data:'target_gross_profit_amount',className:'text-end',render:nullableMoney},{data:'gross_profit',className:'text-end fw-semibold',render:money},{data:'gross_profit_target_variance',className:'text-end',render:nullableMoney},{data:'campaign_budget_amount',className:'text-end',render:nullableMoney},{data:'external_spend',className:'text-end',render:money},{data:'budget_remaining',className:'text-end',render:nullableMoney},{data:'contribution',className:'text-end fw-semibold',render:money},{data:'roi_percent',className:'text-end',render:function(v){return v===null?'—':percent.display(v)+'%';}}]}));$('#campaign-roi-filter').on('click',function(){report.ajax.reload();});});</script>
@endpush
