@extends('Pos::layout')

@section('title', 'รายงานยอดขายตามลูกค้า | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">POS / REPORTS</p><h1 class="h3 mb-2">รายงานยอดขายตามลูกค้า</h1><p class="text-secondary mb-0">ยอดจาก HS/IV และใบรับคืนในช่วงวันที่เลือก พร้อมยอดค้างชำระของ IV ณ วันนี้</p></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3 align-items-end"><div class="col-md-3"><label for="customer-sales-from" class="form-label">วันที่เริ่ม</label><input id="customer-sales-from" type="date" class="form-control" value="{{ now()->startOfMonth()->format('Y-m-d') }}"></div><div class="col-md-3"><label for="customer-sales-to" class="form-label">ถึงวันที่</label><input id="customer-sales-to" type="date" class="form-control" value="{{ now()->endOfMonth()->format('Y-m-d') }}"></div><div class="col-md-4"><label for="customer-sales-party" class="form-label">ลูกค้า</label><select id="customer-sales-party" class="form-select" data-url="{{ route('pos.sales-reports.customer-options') }}"><option value="">ทั้งหมด</option></select></div><div class="col-md-2"><button id="customer-sales-filter" class="btn btn-outline-secondary" type="button"><i class="bx bx-filter-alt me-1" aria-hidden="true"></i>กรอง</button></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="customer-sales-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.sales-reports.customer.data') }}"><thead><tr><th>ลูกค้า</th><th class="text-end">HS</th><th class="text-end">IV</th><th class="text-end">รับคืน</th><th class="text-end">ยอดขายสด</th><th class="text-end">ยอดขายเชื่อ</th><th class="text-end">ยอดรับคืน</th><th class="text-end">ยอดขายสุทธิ</th><th class="text-end">คงเหลือ ณ วันนี้</th><th>สถานะรับชำระ</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>$(function(){var $table=$('#customer-sales-table'),$party=$('#customer-sales-party'),text=$.fn.dataTable.render.text(),money=$.fn.dataTable.render.number(',', '.', 2),number=function(value){return Number(value||0).toLocaleString();};$party.select2({width:'100%',placeholder:'ค้นหาลูกค้า',allowClear:true,ajax:{url:$party.data('url'),dataType:'json',delay:250,data:function(params){return{q:params.term||'',page:params.page||1};},processResults:function(data){return data;}}});var report=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(data){data.date_from=$('#customer-sales-from').val();data.date_to=$('#customer-sales-to').val();data.party_id=$party.val();}},order:[[7,'desc']],buttons:[window.erpExcelButton($table)],columns:[{data:'party_label',render:text.display},{data:'hs_document_count',className:'text-end',render:number},{data:'iv_document_count',className:'text-end',render:number},{data:'return_document_count',className:'text-end',render:number},{data:'hs_amount',className:'text-end',render:money},{data:'iv_amount',className:'text-end',render:money},{data:'return_amount',className:'text-end',render:money},{data:'net_sales',className:'text-end fw-semibold',render:money},{data:'outstanding_amount',className:'text-end',render:money},{data:'payment_status',render:function(value,type){if(type!=='display')return value;var status=value==='OUTSTANDING'?['warning','ค้างชำระ']:['success','ชำระครบ'];return '<span class="badge bg-'+status[0]+'-subtle text-'+status[0]+'-emphasis">'+status[1]+'</span>';}}]}));$('#customer-sales-filter').on('click',function(){report.ajax.reload();});});</script>
@endpush
