@extends('Pos::layout')

@section('title', 'รายงานกำไรขั้นต้น | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">POS / REPORTS</p><h1 class="h3 mb-2">รายงานกำไรขั้นต้น</h1><p class="text-secondary mb-0">รายได้ไม่รวม VAT และต้นทุนจริงจาก Cost Allocation ของ HS/IV ที่ลงบัญชีแล้ว</p></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3 align-items-end"><div class="col-md-3"><label for="gross-profit-from" class="form-label">วันที่เริ่ม</label><input id="gross-profit-from" type="date" class="form-control" value="{{ now()->startOfMonth()->format('Y-m-d') }}"></div><div class="col-md-3"><label for="gross-profit-to" class="form-label">ถึงวันที่</label><input id="gross-profit-to" type="date" class="form-control" value="{{ now()->endOfMonth()->format('Y-m-d') }}"></div><div class="col-md-3"><label for="gross-profit-party" class="form-label">ลูกค้า</label><select id="gross-profit-party" class="form-select" data-url="{{ route('pos.sales-reports.customer-options') }}"><option value="">ทั้งหมด</option></select></div><div class="col-md-3"><label for="gross-profit-item" class="form-label">สินค้า</label><select id="gross-profit-item" class="form-select" data-url="{{ route('pos.sales-reports.item-options') }}"><option value="">ทั้งหมด</option></select></div><div class="col-12"><button id="gross-profit-filter" class="btn btn-outline-secondary" type="button"><i class="bx bx-filter-alt me-1" aria-hidden="true"></i>กรอง</button></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="gross-profit-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.sales-reports.gross-profit.data') }}"><thead><tr><th>วันที่ Post</th><th>เอกสาร</th><th>ลูกค้า</th><th>สินค้า</th><th>หน่วย</th><th class="text-end">จำนวนสุทธิ</th><th class="text-end">ส่วนลด Promotion</th><th class="text-end">ยอดขายสุทธิ</th><th class="text-end">ต้นทุนขาย</th><th class="text-end">กำไรขั้นต้น</th><th class="text-end">GP%</th><th>จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>$(function(){var $table=$('#gross-profit-table'),text=$.fn.dataTable.render.text(),money=$.fn.dataTable.render.number(',', '.', 2),quantity=$.fn.dataTable.render.number(',', '.', 4),percent=$.fn.dataTable.render.number(',', '.', 2);function select2($el){$el.select2({width:'100%',placeholder:'ทั้งหมด',allowClear:true,ajax:{url:$el.data('url'),dataType:'json',delay:250,data:function(p){return{q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});}select2($('#gross-profit-party'));select2($('#gross-profit-item'));var report=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(d){d.date_from=$('#gross-profit-from').val();d.date_to=$('#gross-profit-to').val();d.party_id=$('#gross-profit-party').val();d.item_id=$('#gross-profit-item').val();}},order:[[0,'desc']],buttons:[window.erpExcelButton($table)],columns:[{data:'posting_date',render:text.display},{data:'document_label',render:text.display},{data:'party_label',render:text.display},{data:'item_label',render:text.display},{data:'uom_code',render:text.display},{data:'net_quantity',className:'text-end',render:quantity},{data:'promotion_discount_amount',className:'text-end',render:money},{data:'net_sales',className:'text-end',render:money},{data:'cogs_amount',className:'text-end',render:money},{data:'gross_profit',className:'text-end fw-semibold',render:money},{data:'gross_profit_percent',className:'text-end',render:function(v){return percent.display(v)+'%';}},{data:'detail_url',orderable:false,searchable:false,className:'text-center',render:function(url){return url?'<a class="btn btn-sm btn-app-soft" href="'+text.display(url)+'" title="ดู HS/IV"><i class="bx bx-show" aria-hidden="true"></i><span class="visually-hidden">ดู HS/IV</span></a>':'-';}}]}));$('#gross-profit-filter').on('click',function(){report.ajax.reload();});});</script>
@endpush
