@extends('Pos::layout')

@section('title', 'รายงานยอดขายตามสินค้า | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">POS / REPORTS</p><h1 class="h3 mb-2">รายงานยอดขายตามสินค้า</h1><p class="text-secondary mb-0">จำนวนและยอดขายสุทธิจาก HS/IV และใบรับคืนที่ลงบัญชีแล้ว ในคลังสินค้าที่เลือก</p></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3 align-items-end"><div class="col-md-3"><label for="item-sales-from" class="form-label">วันที่เริ่ม</label><input id="item-sales-from" type="date" class="form-control" value="{{ now()->startOfMonth()->format('Y-m-d') }}"></div><div class="col-md-3"><label for="item-sales-to" class="form-label">ถึงวันที่</label><input id="item-sales-to" type="date" class="form-control" value="{{ now()->endOfMonth()->format('Y-m-d') }}"></div><div class="col-md-4"><label for="item-sales-item" class="form-label">สินค้า</label><select id="item-sales-item" class="form-select" data-url="{{ route('pos.sales-reports.item-options') }}"><option value="">ทั้งหมด</option></select></div><div class="col-md-2"><button id="item-sales-filter" class="btn btn-outline-secondary" type="button"><i class="bx bx-filter-alt me-1" aria-hidden="true"></i>กรอง</button></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="item-sales-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.sales-reports.item.data') }}"><thead><tr><th>สินค้า</th><th>หน่วย</th><th class="text-end">HS</th><th class="text-end">IV</th><th class="text-end">รับคืน</th><th class="text-end">สุทธิ</th><th class="text-end">ยอด HS</th><th class="text-end">ยอด IV</th><th class="text-end">ยอดรับคืน</th><th class="text-end">ยอดขายสุทธิ</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>$(function(){var $table=$('#item-sales-table'),$item=$('#item-sales-item'),text=$.fn.dataTable.render.text(),money=$.fn.dataTable.render.number(',', '.', 2),quantity=$.fn.dataTable.render.number(',', '.', 4);$item.select2({width:'100%',placeholder:'ค้นหาสินค้า',allowClear:true,ajax:{url:$item.data('url'),dataType:'json',delay:250,data:function(params){return{q:params.term||'',page:params.page||1};},processResults:function(data){return data;}}});var report=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(data){data.date_from=$('#item-sales-from').val();data.date_to=$('#item-sales-to').val();data.item_id=$item.val();}},order:[[9,'desc']],buttons:[window.erpExcelButton($table)],columns:[{data:'item_label',render:text.display},{data:'unit',render:text.display},{data:'hs_quantity',className:'text-end',render:quantity},{data:'iv_quantity',className:'text-end',render:quantity},{data:'return_quantity',className:'text-end',render:quantity},{data:'net_quantity',className:'text-end fw-semibold',render:quantity},{data:'hs_amount',className:'text-end',render:money},{data:'iv_amount',className:'text-end',render:money},{data:'return_amount',className:'text-end',render:money},{data:'net_sales',className:'text-end fw-semibold',render:money}]}));$('#item-sales-filter').on('click',function(){report.ajax.reload();});});</script>
@endpush
