@extends('Pos::layout')

@section('title', 'รายงานผล Promotion | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">POS / REPORTS</p><h1 class="h3 mb-2">รายงานผล Promotion</h1><p class="text-secondary mb-0">ผลการใช้งานจาก Promotion snapshot ของ HS/IV ที่ลงบัญชีแล้ว หักผลของใบรับคืนตามยอดสุทธิ</p></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3 align-items-end"><div class="col-md-3"><label for="promotion-report-from" class="form-label">วันที่เริ่ม</label><input id="promotion-report-from" type="date" class="form-control" value="{{ now()->startOfMonth()->format('Y-m-d') }}"></div><div class="col-md-3"><label for="promotion-report-to" class="form-label">ถึงวันที่</label><input id="promotion-report-to" type="date" class="form-control" value="{{ now()->endOfMonth()->format('Y-m-d') }}"></div><div class="col-md-4"><label for="promotion-report-promotion" class="form-label">Promotion</label><select id="promotion-report-promotion" class="form-select" data-url="{{ route('pos.sales-reports.promotion-options') }}"><option value="">ทั้งหมด</option></select></div><div class="col-md-2"><button id="promotion-report-filter" class="btn btn-outline-secondary" type="button"><i class="bx bx-filter-alt me-1" aria-hidden="true"></i>กรอง</button></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="promotion-report-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.sales-reports.promotion.data') }}"><thead><tr><th>Promotion</th><th>รูปแบบ</th><th class="text-end">จำนวนครั้งใช้</th><th class="text-end">จำนวนสุทธิ (ต่อรายการ)</th><th class="text-end">ส่วนลด Promotion</th><th class="text-end">ยอดขายสุทธิ (ไม่รวม VAT)</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>$(function(){var $table=$('#promotion-report-table'),$promotion=$('#promotion-report-promotion'),text=$.fn.dataTable.render.text(),money=$.fn.dataTable.render.number(',', '.', 2),quantity=$.fn.dataTable.render.number(',', '.', 4);$promotion.select2({width:'100%',placeholder:'ค้นหา Promotion',allowClear:true,ajax:{url:$promotion.data('url'),dataType:'json',delay:250,data:function(params){return{q:params.term||'',page:params.page||1};},processResults:function(data){return data;}}});var report=$table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:$table.data('url'),data:function(data){data.date_from=$('#promotion-report-from').val();data.date_to=$('#promotion-report-to').val();data.promotion_id=$promotion.val();}},order:[[4,'desc']],buttons:[window.erpExcelButton($table)],columns:[{data:'promotion_code',render:text.display},{data:'scope_label',render:text.display},{data:'usage_count',className:'text-end',render:function(value){return Number(value||0).toLocaleString();}},{data:'net_quantity',className:'text-end',render:function(value,type,row){return row.application_scope==='DOCUMENT'?'-':quantity.display(value);}},{data:'promotion_discount_amount',className:'text-end fw-semibold',render:money},{data:'net_sales',className:'text-end',render:money}]}));$('#promotion-report-filter').on('click',function(){report.ajax.reload();});});</script>
@endpush
