@extends('Pos::layout')

@section('title', 'รายงานผลงานเทียบเป้าหมาย | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">POS / REPORTS</p><h1 class="h3 mb-2">รายงานผลงานเทียบเป้าหมายขาย</h1><p class="text-secondary mb-0">เลือกช่วงวันที่ให้ตรงกับงวดเป้าหมายที่ตั้งค่าไว้; ยอดจริงจาก HS/IV ที่ Post แล้ว หักคืนสินค้า และใช้ต้นทุน FINAL COGS; พนักงานอ้างอิงผู้จัดทำใบรับข้อมูลตามสายเอกสาร หรือผู้สร้าง HS/IV หากไม่มีต้นทาง</p></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label" for="target-from">วันที่เริ่ม</label><input id="target-from" type="date" class="form-control" value="{{ now()->startOfMonth()->format('Y-m-d') }}"></div><div class="col-md-3"><label class="form-label" for="target-to">ถึงวันที่</label><input id="target-to" type="date" class="form-control" value="{{ now()->endOfMonth()->format('Y-m-d') }}"></div><div class="col-12"><button id="target-filter" class="btn btn-outline-secondary" type="button"><i class="bx bx-filter-alt me-1" aria-hidden="true"></i>กรอง</button></div></div></div></div>
    <div class="row g-3 mb-3"><div class="col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><h2 class="h6 mb-1">กราฟผลงานสาขา</h2><p class="small text-secondary mb-3"><span class="text-primary">■</span> ฟ้าอ่อน = เป้า &nbsp; <span class="text-primary fw-bold">■</span> ฟ้าเข้ม = ทำได้</p><canvas id="branch-target-chart" class="w-100" role="img" aria-label="กราฟผลงานสาขา"></canvas></div></div></div><div class="col-xl-8"><div class="card border-0 shadow-sm h-100"><div class="card-body p-3 p-lg-4"><h2 class="h6 mb-1">กราฟผลงานพนักงาน</h2><p class="small text-secondary mb-3"><span class="text-primary">■</span> ฟ้าอ่อน = เป้า &nbsp; <span class="text-primary fw-bold">■</span> ฟ้าเข้ม = ทำได้</p><canvas id="employee-target-chart" class="w-100" role="img" aria-label="กราฟผลงานพนักงาน"></canvas></div></div></div></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ผลงานสาขา</h2><div class="table-responsive"><table id="branch-sales-target-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.sales-reports.sales-target-performance.data') }}"><thead><tr><th>สาขา</th><th class="text-end">เป้ายอดขาย</th><th class="text-end">ยอดขายจริง</th><th class="text-end">ต่าง</th><th class="text-end">เป้า GP</th><th class="text-end">GP จริง</th><th class="text-end">ต่าง</th></tr></thead></table></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ผลงานพนักงานขาย</h2><div class="table-responsive"><table id="employee-sales-target-table" class="table table-hover align-middle w-100" data-url="{{ route('pos.sales-reports.sales-target-performance.data') }}"><thead><tr><th>พนักงานขาย</th><th class="text-end">เป้ายอดขาย</th><th class="text-end">ยอดขายจริง</th><th class="text-end">ต่าง</th><th class="text-end">เป้า GP</th><th class="text-end">GP จริง</th><th class="text-end">ต่าง</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>
$(function () {
    var text = $.fn.dataTable.render.text(), money = $.fn.dataTable.render.number(',', '.', 2);
    var params = function (scope) { return { date_from: $('#target-from').val(), date_to: $('#target-to').val(), scope: scope }; };
    var columns = [{ data: 'label', render: text.display }, { data: 'target_sales_amount', className: 'text-end', render: function (v) { return v === null ? '—' : money.display(v); } }, { data: 'actual_sales_amount', className: 'text-end fw-semibold', render: money }, { data: 'sales_variance', className: 'text-end', render: function (v) { return v === null ? '—' : money.display(v); } }, { data: 'target_gross_profit_amount', className: 'text-end', render: function (v) { return v === null ? '—' : money.display(v); } }, { data: 'actual_gross_profit_amount', className: 'text-end fw-semibold', render: money }, { data: 'gross_profit_variance', className: 'text-end', render: function (v) { return v === null ? '—' : money.display(v); } }];
    var targetTable = function (selector, scope) { return $(selector).DataTable($.extend(true, {}, window.erpDataTableDefaults, { ajax: { url: $(selector).data('url'), data: function (data) { $.extend(data, params(scope)); } }, order: [[0, 'asc']], buttons: [window.erpExcelButton($(selector))], columns: columns })); };
    var drawChart = function (canvas, rows) { var width = Math.max(canvas.clientWidth, 320), height = Math.max(150, (rows.length || 1) * 52 + 42), ratio = window.devicePixelRatio || 1, ctx = canvas.getContext('2d'), max = Math.max.apply(null, rows.map(function (row) { return Math.max(Number(row.target_sales_amount || 0), Number(row.actual_sales_amount || 0)); }).concat([1])), left = Math.min(180, width * .38), barWidth = width - left - 30; canvas.width = width * ratio; canvas.height = height * ratio; canvas.style.height = height + 'px'; ctx.scale(ratio, ratio); ctx.clearRect(0, 0, width, height); if (!rows.length) { ctx.fillStyle = '#6c757d'; ctx.font = '14px sans-serif'; ctx.fillText('ยังไม่มีข้อมูลในช่วงที่เลือก', 16, 42); return; } rows.forEach(function (row, index) { var y = 24 + index * 52, target = Number(row.target_sales_amount || 0), actual = Number(row.actual_sales_amount || 0), achievement = target > 0 ? (actual / target * 100).toFixed(2) + '%' : '—'; ctx.fillStyle = '#343a40'; ctx.font = '13px sans-serif'; ctx.fillText(String(row.label).slice(0, 24), 8, y); ctx.fillStyle = '#e9ecef'; ctx.fillRect(left, y - 12, barWidth, 10); ctx.fillStyle = '#7aa7e8'; ctx.fillRect(left, y - 12, barWidth * (target / max), 10); ctx.fillStyle = '#1f6feb'; ctx.fillRect(left, y + 4, barWidth * (actual / max), 12); ctx.fillStyle = '#495057'; ctx.font = '12px sans-serif'; ctx.fillText('เป้า ' + money.display(target) + ' · จริง ' + money.display(actual) + ' · ทำได้ ' + achievement, left, y + 33); }); };
    var loadCharts = function () { $.getJSON($('#branch-sales-target-table').data('url'), params()).done(function (json) { var rows = json.data || []; drawChart(document.getElementById('branch-target-chart'), rows.filter(function (row) { return row.scope === 'BRANCH'; })); drawChart(document.getElementById('employee-target-chart'), rows.filter(function (row) { return row.scope === 'EMPLOYEE'; })); }); };
    var branchTable = targetTable('#branch-sales-target-table', 'BRANCH'), employeeTable = targetTable('#employee-sales-target-table', 'EMPLOYEE');
    $('#target-filter').on('click', function () { branchTable.ajax.reload(); employeeTable.ajax.reload(); loadCharts(); });
    loadCharts();
});
</script>
@endpush
