@extends('Asset::layout')

@section('title', 'รายงานค่าเสื่อมราคา | New ERP')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">ASSET / REPORTS</p><h1 class="h3 mb-2">รายงานค่าเสื่อมราคา</h1><p class="text-secondary mb-0">แสดงเฉพาะชุดคำนวณที่ลงบัญชีแล้ว แยก Book, Tax และผลต่างของงวด</p></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h6 mb-3">ตัวกรอง</h2><div class="row g-3"><div class="col-12 col-md-6 col-xl-4"><label class="form-label" for="depreciation-report-period">งวดบัญชี</label><select class="form-select js-select2" id="depreciation-report-period">@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->name }} · {{ $period->start_date->format('d/m/Y') }} – {{ $period->end_date->format('d/m/Y') }}</option>@endforeach</select></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label" for="depreciation-report-category">หมวดสินทรัพย์</label><select class="form-select js-select2" id="depreciation-report-category"><option value="">ทุกหมวด</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->code }} · {{ $category->name }}</option>@endforeach</select></div><div class="col-12 col-xl-2 ms-auto"><button class="btn btn-outline-secondary w-100" id="depreciation-report-filter-reset" type="button">ล้างตัวกรอง</button></div></div></div></div>
    <ul class="nav nav-tabs mb-3" id="depreciation-report-tabs" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#book-schedule" type="button">ตารางค่าเสื่อม Book</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#tax-schedule" type="button">ตารางค่าเสื่อม Tax</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#book-tax-comparison" type="button">เปรียบเทียบ Book กับ Tax</button></li></ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="book-schedule"><div class="row g-3 mb-3"><div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">ค่าเสื่อมงวดนี้</div><div class="h4 mb-0" data-schedule-total="period_depreciation">0.00</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">Catch-up</div><div class="h4 mb-0" data-schedule-total="catch_up_adjustment">0.00</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">มูลค่าปิดงวด</div><div class="h4 mb-0" data-schedule-total="closing_value">0.00</div></div></div></div></div><div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100 js-schedule-table" data-book-type="BOOK" data-url="{{ route('asset.reports.depreciation.schedule.data') }}"><thead><tr><th>เอกสาร</th><th>สินทรัพย์</th><th>หมวด</th><th class="text-end">มูลค่าเปิดงวด</th><th class="text-end">ค่าเสื่อมงวดนี้</th><th class="text-end">Catch-up</th><th class="text-end">มูลค่าปิดงวด</th></tr></thead></table></div></div></div></div>
        <div class="tab-pane fade" id="tax-schedule"><div class="alert alert-info border-0">Tax schedule ใช้เพื่อการรายงานภาษีเท่านั้น และไม่สร้าง Journal Entry</div><div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100 js-schedule-table" data-book-type="TAX" data-url="{{ route('asset.reports.depreciation.schedule.data') }}"><thead><tr><th>เอกสาร</th><th>สินทรัพย์</th><th>หมวด</th><th class="text-end">มูลค่าเปิดงวด</th><th class="text-end">ค่าเสื่อมงวดนี้</th><th class="text-end">Catch-up</th><th class="text-end">มูลค่าปิดงวด</th></tr></thead></table></div></div></div></div>
        <div class="tab-pane fade" id="book-tax-comparison"><div class="row g-3 mb-3"><div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">ค่าเสื่อม Book</div><div class="h4 mb-0" data-comparison-total="book_depreciation">0.00</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">ค่าเสื่อม Tax</div><div class="h4 mb-0" data-comparison-total="tax_depreciation">0.00</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">ผลต่าง Book – Tax</div><div class="h4 mb-0" data-comparison-total="difference">0.00</div></div></div></div></div><div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="book-tax-comparison-table" data-url="{{ route('asset.reports.depreciation.comparison.data') }}"><thead><tr><th>สินทรัพย์</th><th>หมวด</th><th class="text-end">ค่าเสื่อม Book</th><th class="text-end">ค่าเสื่อม Tax</th><th class="text-end">ผลต่าง</th><th class="text-end">มูลค่าปิด Book</th><th class="text-end">มูลค่าปิด Tax</th></tr></thead></table></div></div></div></div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$(function () {
    var $period = $('#depreciation-report-period'), $category = $('#depreciation-report-category'), text = $.fn.dataTable.render.text(), money = function (value) { return Number(value || 0).toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2}); }, tables = [];
    function scheduleColumns() { return [{data: 'document_number', name: 'runs.document_number', render: text.display}, {data: 'asset_number', name: 'lines.asset_number', render: text.display}, {data: 'category_name', name: 'lines.category_name', render: text.display}, {data: 'opening_cost', name: 'lines.opening_cost', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value; }}, {data: 'period_depreciation', name: 'lines.period_depreciation', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value; }}, {data: 'catch_up_adjustment', name: 'lines.catch_up_adjustment', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value; }}, {data: 'closing_value', name: 'closing_value', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value; }}]; }
    $('.js-schedule-table').each(function () { var $table = $(this), type = $table.data('book-type'), table = $table.DataTable($.extend(true, {}, window.erpDataTableDefaults, {ajax: {url: $table.data('url'), data: function (data) { data.period_id = $period.val(); data.book_type = type; data.asset_category_id = $category.val(); }, dataSrc: function (response) { if (type === 'BOOK') { $.each(response.totals || {}, function (key, value) { $('[data-schedule-total="' + key + '"]').text(money(value)); }); } return response.data; }}, order: [[1, 'asc']], buttons: [window.erpExcelButton($table, function () { return {period_id: $period.val(), book_type: type, asset_category_id: $category.val()}; })], columns: scheduleColumns()})); tables.push(table); });
    var $comparison = $('#book-tax-comparison-table'), comparison = $comparison.DataTable($.extend(true, {}, window.erpDataTableDefaults, {ajax: {url: $comparison.data('url'), data: function (data) { data.period_id = $period.val(); data.asset_category_id = $category.val(); }, dataSrc: function (response) { $.each(response.totals || {}, function (key, value) { $('[data-comparison-total="' + key + '"]').text(money(value)); }); return response.data; }}, order: [[0, 'asc']], buttons: [window.erpExcelButton($comparison, function () { return {period_id: $period.val(), asset_category_id: $category.val()}; })], columns: [{data: 'asset_number', name: 'assets.asset_number', render: function (value, type, row) { return type === 'display' ? '<div class="fw-semibold">' + text.display(value) + '</div><div class="small text-secondary">' + text.display(row.name) + '</div>' : value; }}, {data: 'category_name', name: 'categories.name', render: text.display}, {data: 'book_depreciation', name: 'book_depreciation', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value; }}, {data: 'tax_depreciation', name: 'tax_depreciation', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value; }}, {data: 'difference', name: 'difference', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value; }}, {data: 'book_closing_value', name: 'book_closing_value', className: 'text-end', render: function (value, type) { return type === 'display' ? (value === null ? '-' : money(value)) : value; }}, {data: 'tax_closing_value', name: 'tax_closing_value', className: 'text-end', render: function (value, type) { return type === 'display' ? (value === null ? '-' : money(value)) : value; }}]})); tables.push(comparison);
    $period.add($category).on('change', function () { $.each(tables, function (_, table) { table.ajax.reload(); }); }); $('#depreciation-report-filter-reset').on('click', function () { $period.val($period.find('option:first').val()).trigger('change.select2'); $category.val('').trigger('change'); });
    $('#depreciation-report-tabs [data-bs-toggle="tab"]').on('shown.bs.tab', function () { $.fn.dataTable.tables({visible: true, api: true}).columns.adjust(); });
});
</script>
@endpush
