@extends('Asset::layout')

@section('title', 'รายงานงานซ่อมบำรุง | New ERP')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="eyebrow mb-2">ASSET / REPORTS</p><h1 class="h3 mb-1">รายงานงานซ่อมบำรุง</h1><p class="text-secondary mb-0">สรุปจำนวน ค่าใช้จ่าย และเวลาหยุดใช้งานจากใบแจ้งซ่อม</p></div><a class="btn btn-outline-dark" href="{{ route('asset.maintenance.index') }}">รายการแจ้งซ่อม</a></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h6 mb-3">ตัวกรอง</h2><div class="row g-3"><div class="col-12 col-md-3"><label class="form-label" for="maintenance-report-from">วันที่แจ้งตั้งแต่</label><input class="form-control" id="maintenance-report-from" type="date"></div><div class="col-12 col-md-3"><label class="form-label" for="maintenance-report-to">วันที่แจ้งถึง</label><input class="form-control" id="maintenance-report-to" type="date"></div><div class="col-12 col-md-2"><label class="form-label" for="maintenance-report-status">สถานะ</label><select class="form-select" id="maintenance-report-status"><option value="">ทั้งหมด</option><option value="OPEN">เปิดงาน</option><option value="ASSIGNED">มอบหมายแล้ว</option><option value="IN_PROGRESS">กำลังซ่อม</option><option value="WAITING_PARTS">รออะไหล่</option><option value="COMPLETED">ปิดงานแล้ว</option><option value="CANCELLED">ยกเลิก</option></select></div><div class="col-12 col-md-2"><label class="form-label" for="maintenance-report-priority">ความเร่งด่วน</label><select class="form-select" id="maintenance-report-priority"><option value="">ทั้งหมด</option><option value="LOW">ต่ำ</option><option value="NORMAL">ปกติ</option><option value="HIGH">สูง</option><option value="CRITICAL">วิกฤต</option></select></div><div class="col-12 col-md-2"><label class="form-label" for="maintenance-report-asset">สินทรัพย์</label><select class="form-select" id="maintenance-report-asset" data-url="{{ route('asset.assets.options') }}"></select></div></div></div></div>
    <div class="row g-4 mb-4"><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">จำนวนงาน</div><div class="h4 mb-0" id="maintenance-total-count">0</div></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">ค่าใช้จ่ายประมาณการ</div><div class="h4 mb-0" id="maintenance-total-estimated">0.00</div></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">ค่าใช้จ่ายจริง</div><div class="h4 mb-0" id="maintenance-total-actual">0.00</div></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary">เวลาหยุดใช้งาน (นาที)</div><div class="h4 mb-0" id="maintenance-total-downtime">0</div></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="maintenance-report-table" data-url="{{ route('asset.reports.maintenance.data') }}"><thead class="table-light"><tr><th>เลขที่เอกสาร</th><th>วันที่แจ้ง</th><th>สินทรัพย์</th><th>ผู้รับผิดชอบ</th><th>สถานะ</th><th class="text-end">ค่าใช้จ่ายจริง</th><th class="text-end">เวลาหยุด (นาที)</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>
$(function(){var t=$('#maintenance-report-table'),x=$.fn.dataTable.render.text(),labels={OPEN:'เปิดงาน',ASSIGNED:'มอบหมายแล้ว',IN_PROGRESS:'กำลังซ่อม',WAITING_PARTS:'รออะไหล่',COMPLETED:'ปิดงานแล้ว',CANCELLED:'ยกเลิก'},classes={OPEN:'app-status-neutral',ASSIGNED:'app-status-info',IN_PROGRESS:'app-status-warning',WAITING_PARTS:'app-status-warning',COMPLETED:'app-status-success',CANCELLED:'app-status-danger'},money=function(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});};window.erpInitSelect2('#maintenance-report-asset',{placeholder:'ทั้งหมด',allowClear:true,ajax:{url:$('#maintenance-report-asset').data('url'),delay:250,data:function(p){return{type:'asset',q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}});var table=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:t.data('url'),data:function(d){d.date_from=$('#maintenance-report-from').val();d.date_to=$('#maintenance-report-to').val();d.status=$('#maintenance-report-status').val();d.priority=$('#maintenance-report-priority').val();d.asset_id=$('#maintenance-report-asset').val();},dataSrc:function(json){var q=json.totals||{};$('#maintenance-total-count').text(Number(q.count||0).toLocaleString());$('#maintenance-total-estimated').text(money(q.estimated_cost));$('#maintenance-total-actual').text(money(q.actual_cost));$('#maintenance-total-downtime').text(Number(q.downtime_minutes||0).toLocaleString());return json.data;}},order:[[1,'desc']],buttons:[window.erpExcelButton(t)],columns:[{data:'document_number',render:x.display},{data:'reported_date_label',render:x.display},{data:'asset_label',render:x.display},{data:'assigned_to_label',render:x.display},{data:'status',render:function(v,z){return z==='display'?'<span class="badge '+(classes[v]||'app-status-neutral')+'">'+x.display(labels[v]||v)+'</span>':v;}},{data:'actual_cost',className:'text-end',render:function(v,z){return z==='display'?money(v):v;}},{data:'downtime_minutes',className:'text-end',render:function(v,z){return z==='display'?Number(v||0).toLocaleString():v;}}]}));$('#maintenance-report-from,#maintenance-report-to,#maintenance-report-status,#maintenance-report-priority').on('change',function(){table.ajax.reload();});$('#maintenance-report-asset').on('change',function(){table.ajax.reload();});});
</script>
<script>
$(function(){var $reset=$('<div class="col-12 col-md-2 ms-auto"><button class="btn btn-outline-secondary w-100" id="maintenance-report-filter-reset" type="button">ล้างตัวกรอง</button></div>');$('.card-body.p-4 .row.g-3').first().append($reset);$('#maintenance-report-filter-reset').on('click',function(){$('#maintenance-report-from,#maintenance-report-to,#maintenance-report-status,#maintenance-report-priority').val('');$('#maintenance-report-asset').val(null).trigger('change');});});
</script>
@endpush
