@extends('Asset::layout')

@section('title', 'กระทบยอดทะเบียนสินทรัพย์ | New ERP')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">ASSET / RECONCILIATION</p><h1 class="h3 mb-2">กระทบยอดทะเบียนสินทรัพย์กับ GL</h1><p class="text-secondary mb-0">ตรวจสอบมูลค่าทุน ค่าเสื่อมสะสม และค่าเผื่อด้อยค่า ณ วันสิ้นงวด</p></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h6 mb-3">ตัวกรอง</h2><div class="row g-3"><div class="col-12 col-md-6 col-xl-4"><label class="form-label" for="reconciliation-period">งวดบัญชี</label><select class="form-select js-select2" id="reconciliation-period">@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->name }} · {{ $period->start_date->format('d/m/Y') }} – {{ $period->end_date->format('d/m/Y') }}</option>@endforeach</select></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label" for="reconciliation-account">บัญชี</label><select class="form-select" id="reconciliation-account"><option value="">ทุกบัญชี</option></select></div><div class="col-12 col-md-6 col-xl-4"><label class="form-label" for="reconciliation-type">ประเภท</label><select class="form-select" id="reconciliation-type"><option value="">ทุกประเภท</option><option value="COST">มูลค่าทุน</option><option value="ACCUMULATED_DEPRECIATION">ค่าเสื่อมสะสม</option><option value="ACCUMULATED_IMPAIRMENT">ค่าเผื่อด้อยค่า</option></select></div><div class="col-12 col-xl-2 ms-auto"><button class="btn btn-outline-secondary w-100" id="reconciliation-filter-reset" type="button">ล้างตัวกรอง</button></div></div></div></div>
    <div class="alert alert-info border-0 shadow-sm d-flex gap-2" role="note"><i class="bx bx-info-circle fs-5" aria-hidden="true"></i><div>ยอด Opening แสดงแยกจากยอดที่ต้องเทียบ GL เพราะเป็นยอดยกมาก่อนเริ่มใช้ระบบและไม่สร้าง Journal ซ้ำ</div></div>
    <div class="alert alert-warning border-0 shadow-sm d-none" id="reconciliation-next-step" role="alert"><i class="bx bx-error-circle fs-5" aria-hidden="true"></i><div><strong>พบผลต่างที่ต้องตรวจสอบ</strong><div class="small mt-1">เปิดดูบรรทัดที่มีผลต่าง แล้วตรวจ Journal linkage, mapping และเอกสารต้นทาง จากนั้นแก้ด้วยการ Post/Retry หรือ Reversal ตาม workflow ห้ามปรับยอดใน Journal ที่ Post แล้ว</div><a class="btn btn-sm btn-outline-dark mt-2" href="{{ route('asset.workflow.index') }}">เปิด Workflow Center</a></div></div>
    <div class="row g-3 mb-4"><div class="col-12 col-md-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-secondary small">Asset subledger (ไม่รวม Opening)</div><div class="h4 mb-0" data-total="subledger_balance">0.00</div></div></div></div><div class="col-12 col-md-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-secondary small">ยอด GL</div><div class="h4 mb-0" data-total="gl_balance">0.00</div></div></div></div><div class="col-12 col-md-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-secondary small">ผลต่างที่ต้องตรวจสอบ</div><div class="h4 mb-0" data-total="variance">0.00</div></div></div></div><div class="col-12 col-md-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="text-secondary small">Opening แยกต่างหาก</div><div class="h4 mb-0" data-total="opening_balance">0.00</div></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100" id="asset-reconciliation-table" data-url="{{ route('asset.reports.reconciliation.data') }}"><thead><tr><th>ประเภท</th><th>บัญชี</th><th class="text-end">ทะเบียน (ไม่รวม Opening)</th><th class="text-end">GL</th><th class="text-end">ผลต่าง</th><th class="text-end">Opening</th><th>สถานะ</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>
$(function () {
    var $table = $('#asset-reconciliation-table'), $period = $('#reconciliation-period'), $account = $('#reconciliation-account'), $type = $('#reconciliation-type'), text = $.fn.dataTable.render.text(), money = function (value) { return Number(value || 0).toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2}); }, labels = {COST: 'มูลค่าทุน', ACCUMULATED_DEPRECIATION: 'ค่าเสื่อมสะสม', ACCUMULATED_IMPAIRMENT: 'ค่าเผื่อด้อยค่า'};
    $account.select2({width: '100%', allowClear: true, placeholder: 'ทุกบัญชี', ajax: {url: @json(route('asset.reports.reconciliation.accounts')), dataType: 'json', delay: 250, data: function (params) { return {q: params.term || '', page: params.page || 1}; }, processResults: function (data) { return data; }, cache: true}});
    var table = $table.DataTable($.extend(true, {}, window.erpDataTableDefaults, {ajax: {url: $table.data('url'), data: function (data) { data.period_id = $period.val(); data.account_id = $account.val(); data.balance_type = $type.val(); }, dataSrc: function (response) { var totals = response.totals || {}; $.each(totals, function (key, value) { $('[data-total="' + key + '"]').text(money(value)); }); $('#reconciliation-next-step').toggleClass('d-none', Math.abs(Number(totals.variance || 0)) <= 0.005); return response.data; }}, order: [[1, 'asc']], buttons: [window.erpExcelButton($table, function () { return {period_id: $period.val(), account_id: $account.val(), balance_type: $type.val()}; })], columns: [
        {data: 'balance_type', name: 'balance_type', render: function (value, type) { return type === 'display' ? text.display(labels[value] || value) : value;}}, {data: null, name: 'accounts.code', render: function (value, type, row) { if (type !== 'display') return row.code; var label = '<div class="fw-semibold">' + text.display(row.code) + '</div><div class="small text-secondary">' + text.display(row.name) + '</div>'; return label;}}, {data: 'subledger_balance', name: 'subledger_balance', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value;}}, {data: 'gl_balance', name: 'gl_balance', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value;}}, {data: 'difference', name: 'difference', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value;}}, {data: 'opening_balance', name: 'opening_balance', className: 'text-end', render: function (value, type) { return type === 'display' ? money(value) : value;}}, {data: 'difference', name: 'difference', render: function (value, type) { if (type !== 'display') return value; return Number(value || 0) === 0 ? '<span class="badge app-badge-success">ตรงกัน</span>' : '<span class="badge app-status-danger">ต้องตรวจสอบ</span>'; }}, {data: 'account_url', orderable: false, searchable: false, className: 'text-end', render: function (value, type, row) { return type === 'display' && value ? '<a class="btn btn-sm btn-outline-dark" href="' + text.display(value) + '">' + text.display(row.drilldown_label || 'เปิด GL') + '</a>' : ''; }}
    ]}));
    $period.add($account).add($type).on('change', function () { table.ajax.reload(); }); $('#reconciliation-filter-reset').on('click', function () { $period.val($period.find('option:first').val()).trigger('change.select2'); $account.val(null).trigger('change'); $type.val(''); table.ajax.reload(); });
});
</script>
@endpush
