@extends('Asset::layout')

@section('title', $count->document_number.' | New ERP')

@section('content')
@php($audit = collect([
    ['สร้างใบตรวจนับ', $count->created_at, $count->createdBy?->name, null],
    ['ส่งอนุมัติ', $count->submitted_at, $count->submittedBy?->name, null],
    ['อนุมัติ', $count->approved_at, $count->approvedBy?->name, null],
    ['ยกเลิก', $count->cancelled_at, $count->cancelledBy?->name, $count->cancellation_reason],
])->filter(fn ($event) => $event[1])->sortByDesc(fn ($event) => $event[1]))
@php($statusLabels = ['DRAFT' => 'ร่าง', 'SUBMITTED' => 'รออนุมัติ', 'APPROVED' => 'อนุมัติแล้ว', 'CANCELLED' => 'ยกเลิก'])
@php($statusClasses = ['DRAFT' => 'app-badge-soft', 'SUBMITTED' => 'app-badge-info', 'APPROVED' => 'app-badge-success', 'CANCELLED' => 'app-status-danger'])
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-xl-row justify-content-between align-items-xl-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">ASSET / PHYSICAL COUNT</p><div class="d-flex align-items-center gap-2"><h1 class="h3 mb-1">{{ $count->document_number }}</h1><span class="badge {{ $statusClasses[$count->status] }}">{{ $statusLabels[$count->status] }}</span></div><p class="text-secondary mb-0">Freeze ณ {{ $count->freeze_date->format('d/m/Y') }} · {{ $count->lines_count }} รายการ</p></div>
        <div class="d-flex flex-wrap gap-2">
            @if($count->status === 'DRAFT' && auth()->user()->hasPermission('asset.counts.create'))
                <button class="btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#extra-modal">พบสินทรัพย์นอกขอบเขต</button>
                <button class="btn btn-dark js-action" data-url="{{ route('asset.counts.submit', $count) }}">ส่งอนุมัติ</button>
            @endif
            @if($count->status === 'SUBMITTED' && auth()->user()->hasPermission('asset.counts.approve'))<button class="btn btn-primary js-action" data-url="{{ route('asset.counts.approve', $count) }}">อนุมัติ</button>@endif
            @if(in_array($count->status, ['DRAFT', 'SUBMITTED'], true) && auth()->user()->hasPermission('asset.counts.create'))<button class="btn btn-outline-danger" id="cancel-count">ยกเลิก</button>@endif
            <a class="btn btn-outline-dark" href="{{ route('asset.counts.index') }}">รายการทั้งหมด</a>
        </div>
    </div>
    <div class="row g-3 mb-4"><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary mb-1">ขอบเขตการตรวจนับ</div><div class="fw-semibold">{{ $count->location?->name ?? 'ทุกสถานที่' }}</div><div class="small text-secondary">{{ $count->category?->name ?? 'ทุกหมวดสินทรัพย์' }}</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary mb-1">รายการที่ freeze</div><div class="display-6 fw-semibold">{{ number_format($count->lines_count) }}</div><div class="small text-secondary">นับและบันทึกผลรายรายการ</div></div></div></div><div class="col-12 col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-secondary mb-1">การจัดการผลต่าง</div><div class="fw-semibold">ติดตามต่อ</div><div class="small text-secondary">ไม่ตัดจำหน่ายและไม่สร้าง GL อัตโนมัติ</div></div></div></div></div>
    <div class="alert alert-info border-0 shadow-sm d-flex gap-2" role="note"><i class="bx bx-info-circle fs-5" aria-hidden="true"></i><div>บันทึกผลให้ครบทุกรายการก่อนส่งอนุมัติ สินทรัพย์สูญหาย ชำรุด หรืออยู่นอกขอบเขตจะถูกทำเครื่องหมายให้ติดตามต่อ</div></div>
    <div class="card border-0 shadow-sm"><div class="card-header bg-white border-0 d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2 py-3 px-3 px-lg-4"><div><h2 class="h5 mb-1">รายการตรวจนับ</h2><p class="small text-secondary mb-0">ค้นหา เรียงลำดับ และบันทึกผลทีละรายการ</p></div><span class="badge app-status-neutral">{{ number_format($count->lines_count) }} รายการ</span></div><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table class="table table-hover align-middle w-100 mb-0" id="count-lines-table" data-url="{{ route('asset.counts.lines.data', $count) }}" data-editable="{{ $count->status === 'DRAFT' && auth()->user()->hasPermission('asset.counts.create') ? '1' : '0' }}"><thead class="table-light"><tr><th class="ps-3 ps-lg-4">สินทรัพย์</th><th>ตำแหน่งที่คาด</th><th>ตำแหน่งที่พบ</th><th>รหัสที่สแกน</th><th>ผลตรวจนับ</th><th>หมายเหตุ</th><th>สถานะบันทึก</th><th class="text-end pe-3 pe-lg-4">จัดการ</th></tr></thead></table></div></div></div>
    <div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white border-0 py-3 px-3 px-lg-4"><h2 class="h5 mb-1">ประวัติการทำรายการ</h2><p class="small text-secondary mb-0">Audit Trail ของใบตรวจนับนี้ · เวลาไทย (UTC+7)</p></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-3 ps-lg-4">วันเวลา</th><th>เหตุการณ์</th><th>ผู้ดำเนินการ</th><th class="pe-3 pe-lg-4">หมายเหตุ</th></tr></thead><tbody>@forelse($audit as [$event, $at, $actor, $note])<tr><td class="ps-3 ps-lg-4 text-nowrap">{{ $at->timezone('Asia/Bangkok')->format('d/m/Y H:i') }}</td><td class="fw-semibold">{{ $event }}</td><td>{{ $actor ?? '-' }}</td><td class="pe-3 pe-lg-4">{{ $note ?? '-' }}</td></tr>@empty<tr><td class="text-center text-secondary py-4" colspan="4">ยังไม่มีประวัติการทำรายการ</td></tr>@endforelse</tbody></table></div></div>
</div>

@if($count->status === 'DRAFT' && auth()->user()->hasPermission('asset.counts.create'))
<div class="modal fade" id="extra-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form class="modal-content" id="extra-form">@csrf<div class="modal-header"><h2 class="modal-title fs-5">บันทึกสินทรัพย์นอกขอบเขต</h2><button class="btn-close" data-bs-dismiss="modal" type="button" aria-label="ปิด"></button></div><div class="modal-body"><p class="small text-secondary">บันทึกเพื่อให้ตรวจสอบต่อ ไม่เพิ่มทะเบียนหรือสร้าง GL</p><div class="mb-3"><label class="form-label">รหัสที่สแกน <span class="text-danger">*</span></label><input class="form-control" name="scanned_code" maxlength="100" required></div><div class="mb-3"><label class="form-label">ชื่อที่พบ <span class="text-danger">*</span></label><input class="form-control" name="asset_name" maxlength="255" required></div><div class="mb-3"><label class="form-label">ตำแหน่งที่พบ</label><select class="form-select js-extra-option" data-type="location" name="found_location_id"></select></div><div class="mb-3"><label class="form-label">ผู้ดูแลที่พบ</label><select class="form-select js-extra-option" data-type="custodian" name="found_custodian_user_id"></select></div><div><label class="form-label">หมายเหตุ</label><textarea class="form-control" name="note" maxlength="500"></textarea></div></div><div class="modal-footer"><button class="btn btn-outline-dark" data-bs-dismiss="modal" type="button">ยกเลิก</button><button class="btn btn-dark">บันทึกเพื่อติดตาม</button></div></form></div></div>
@endif
@endsection

@push('scripts')
<script>
$(function () {
    var $table = $('#count-lines-table'), editable = String($table.data('editable')) === '1', text = $.fn.dataTable.render.text(), optionUrl = @json(route('asset.assets.options'));
    var escape = function (value) { return $('<div>').text(value || '').html(); };
    var resultLabels = {FOUND: 'พบ', MISSING: 'ไม่พบ', WRONG_LOCATION: 'พบผิดสถานที่', DAMAGED: 'ชำรุด', EXTRA: 'นอกขอบเขต'};
    var resultOptions = function (value) { return $.map(['FOUND', 'MISSING', 'WRONG_LOCATION', 'DAMAGED'], function (key) { return '<option value="' + key + '"' + (key === value ? ' selected' : '') + '>' + resultLabels[key] + '</option>'; }).join(''); };
    var option = function (type, id, label) { return '<select class="form-select form-select-sm js-found-option" data-type="' + type + '"><option value=""></option>' + (id ? '<option value="' + escape(id) + '" selected>' + escape(label) + '</option>' : '') + '</select>'; };
    var table = $table.DataTable($.extend(true, {}, window.erpDataTableDefaults, {ajax: {url: $table.data('url')}, order: [[0, 'asc']], buttons: [window.erpExcelButton($table)], columns: [
        {data: 'asset_number_snapshot', name: 'asset_number_snapshot', render: function (value, type, row) { return type === 'display' ? '<div class="fw-semibold">' + text.display(value) + '</div><div class="small text-secondary">' + text.display(row.asset_name_snapshot) + (row.result === 'EXTRA' ? ' · นอกขอบเขต' : '') + '</div>' : value; }},
        {data: 'expected_location_label', render: text.display},
        {data: null, orderable: false, searchable: false, render: function (value, type, row) { return type === 'display' ? (editable && row.result !== 'EXTRA' ? option('location', row.found_location_id, row.found_location_label) + '<div class="mt-1">' + option('custodian', row.found_custodian_user_id, row.found_custodian_label) + '</div>' : text.display(row.found_location_label || '-')) : row.found_location_label; }},
        {data: 'scanned_code', render: function (value, type) { return type === 'display' ? (editable ? '<input class="form-control form-control-sm js-scanned" maxlength="100" value="' + escape(value) + '">' : text.display(value || '-')) : value; }},
        {data: 'result', render: function (value, type) { return type === 'display' ? (editable && value !== 'EXTRA' ? '<select class="form-select form-select-sm js-result">' + resultOptions(value) + '</select>' : text.display(resultLabels[value] || value)) : value; }},
        {data: 'note', render: function (value, type) { return type === 'display' ? (editable ? '<input class="form-control form-control-sm js-note" maxlength="500" value="' + escape(value) + '">' : text.display(value || '-')) : value; }},
        {data: 'is_saved', name: 'counted_at', render: function (value, type, row) { if (type !== 'display') return value ? 1 : 0; return value ? '<span class="badge app-badge-success">บันทึกแล้ว</span><div class="small text-secondary mt-1">' + text.display(row.saved_at_label) + '</div>' : '<span class="badge app-badge-soft">ยังไม่บันทึก</span>'; }},
        {data: null, orderable: false, searchable: false, className: 'text-end', render: function (value, type, row) { return type === 'display' && editable && row.result !== 'EXTRA' ? '<button class="btn btn-sm btn-outline-dark js-save-line" data-id="' + row.id + '">บันทึก</button>' : ''; }}
    ], drawCallback: function () { if (!editable) return; $table.find('.js-found-option').each(function () { var $element = $(this); if ($element.hasClass('select2-hidden-accessible')) return; window.erpInitSelect2($element, {placeholder: $element.data('type') === 'location' ? 'ตำแหน่งที่พบ' : 'ผู้ดูแลที่พบ', allowClear: true, ajax: {url: optionUrl, delay: 250, data: function (params) { return {type: $element.data('type'), q: params.term || '', page: params.page || 1}; }, processResults: function (data) { return data; }}}); }); }}));
    $table.on('click', '.js-save-line', function () { var $button = $(this), $row = $button.closest('tr'); $.ajax({url: @json(route('asset.counts.lines.save', [$count, '__line__'])).replace('__line__', $button.data('id')), method: 'PUT', data: {_token: @json(csrf_token()), scanned_code: $row.find('.js-scanned').val(), result: $row.find('.js-result').val(), found_location_id: $row.find('.js-found-option[data-type=location]').val(), found_custodian_user_id: $row.find('.js-found-option[data-type=custodian]').val(), note: $row.find('.js-note').val()}}).done(function (response) { Swal.fire({icon: 'success', title: response.msg, timer: 1200, showConfirmButton: false}); table.ajax.reload(null, false); }).fail(window.erpAjaxError); });
    $('.js-action').on('click', function () { var $button = $(this); Swal.fire({icon: 'question', title: 'ยืนยันดำเนินการ?', showCancelButton: true}).then(function (result) { if (result.isConfirmed) $.post($button.data('url'), {_token: @json(csrf_token())}).done(function (response) { Swal.fire({icon: 'success', title: response.msg}).then(function () { location = response.redirect || location.href; }); }).fail(window.erpAjaxError); }); });
    $('#cancel-count').on('click', function () { Swal.fire({icon: 'warning', title: 'ยกเลิกใบตรวจนับ?', input: 'textarea', showCancelButton: true, preConfirm: function (value) { if (!value || value.trim().length < 10) Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร'); }}).then(function (result) { if (result.isConfirmed) $.post(@json(route('asset.counts.cancel', $count)), {_token: @json(csrf_token()), cancellation_reason: result.value}).done(function (response) { Swal.fire({icon: 'success', title: response.msg}).then(function () { location = response.redirect || location.href; }); }).fail(window.erpAjaxError); }); });
    $('.js-extra-option').each(function () { var $element = $(this); window.erpInitSelect2($element, {dropdownParent: $('#extra-modal'), placeholder: 'ไม่ระบุ', allowClear: true, ajax: {url: optionUrl, delay: 250, data: function (params) { return {type: $element.data('type'), q: params.term || '', page: params.page || 1}; }, processResults: function (data) { return data; }}}); });
    $('#extra-form').on('submit', function (event) { event.preventDefault(); var $form = $(this); $.post(@json(route('asset.counts.extras.store', $count)), $form.serialize()).done(function (response) { bootstrap.Modal.getInstance(document.getElementById('extra-modal')).hide(); Swal.fire({icon: 'success', title: response.msg}); $form[0].reset(); table.ajax.reload(null, false); }).fail(window.erpAjaxError); });
});
</script>
@endpush
