@extends('Asset::layout')

@section('title', ($assetCategory->exists ? 'แก้ไข' : 'เพิ่ม').'หมวดสินทรัพย์ | New ERP')

@section('content')
    <div class="container-fluid px-3 px-lg-4 py-4"><div class="mb-4"><p class="eyebrow mb-2">ASSET / MASTER DATA</p><h1 class="h3 mb-2">{{ $assetCategory->exists ? 'แก้ไข' : 'เพิ่ม' }}หมวดสินทรัพย์</h1><p class="text-secondary mb-0">ค่าเริ่มต้นนี้จะใช้กับสินทรัพย์ที่สร้างใหม่เท่านั้น</p></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4 p-md-5"><form id="asset-category-form" method="post" action="{{ $assetCategory->exists ? route('asset.categories.update', $assetCategory) : route('asset.categories.store') }}" novalidate>@csrf @if($assetCategory->exists) @method('PUT') @endif
        <div class="row g-3"><div class="col-12 col-md-4"><label class="form-label" for="code">รหัส</label><input class="form-control text-uppercase" id="code" name="code" maxlength="30" value="{{ old('code', $assetCategory->code) }}" required><div class="invalid-feedback" data-error-for="code"></div></div><div class="col-12 col-md-8"><label class="form-label" for="name">ชื่อหมวด</label><input class="form-control" id="name" name="name" value="{{ old('name', $assetCategory->name) }}" required><div class="invalid-feedback" data-error-for="name"></div></div>
        <div class="col-12"><label class="form-label" for="description">รายละเอียด</label><textarea class="form-control" id="description" name="description" rows="2">{{ old('description', $assetCategory->description) }}</textarea><div class="invalid-feedback" data-error-for="description"></div></div>
        <div class="col-12 col-md-4"><label class="form-label" for="capitalization_threshold">เกณฑ์บันทึกเป็นสินทรัพย์</label><input class="form-control" type="number" min="0" step="0.01" id="capitalization_threshold" name="capitalization_threshold" value="{{ old('capitalization_threshold', $assetCategory->capitalization_threshold ?? 0) }}" required><div class="invalid-feedback" data-error-for="capitalization_threshold"></div></div>
        <div class="col-12 col-md-4"><label class="form-label d-block">การคิดค่าเสื่อม</label><input type="hidden" name="is_depreciable" value="0"><div class="form-check form-switch mt-2"><input class="form-check-input" type="checkbox" role="switch" id="is_depreciable" name="is_depreciable" value="1" @checked(old('is_depreciable', $assetCategory->is_depreciable))><label class="form-check-label" for="is_depreciable">คิดค่าเสื่อม</label></div><div class="form-text">ที่ดินให้ปิดตัวเลือกนี้</div><div class="invalid-feedback" data-error-for="is_depreciable"></div></div>
        <div class="col-12 col-md-4"><label class="form-label d-block">สถานะ</label><input type="hidden" name="is_active" value="0"><div class="form-check form-switch mt-2"><input class="form-check-input" type="checkbox" role="switch" id="is_active" name="is_active" value="1" @checked(old('is_active', $assetCategory->is_active))><label class="form-check-label" for="is_active">เปิดใช้งาน</label></div><div class="invalid-feedback" data-error-for="is_active"></div></div></div>
        <hr class="my-4"><h2 class="h5 mb-3">ค่าเสื่อมตามบัญชี</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">วิธี</label><select class="form-select" name="book_method"><option value="STRAIGHT_LINE" @selected(old('book_method', $assetCategory->book_method) === 'STRAIGHT_LINE')>เส้นตรง</option></select><div class="invalid-feedback" data-error-for="book_method"></div></div><div class="col-md-4 js-depreciable"><label class="form-label">อายุใช้งาน (เดือน)</label><input class="form-control" type="number" min="1" max="1200" name="book_useful_life_months" value="{{ old('book_useful_life_months', $assetCategory->book_useful_life_months) }}"><div class="invalid-feedback" data-error-for="book_useful_life_months"></div></div><div class="col-md-4"><label class="form-label">มูลค่าซาก (%)</label><input class="form-control" type="number" min="0" max="100" step="0.0001" name="book_residual_value_percent" value="{{ old('book_residual_value_percent', $assetCategory->book_residual_value_percent ?? 0) }}" required><div class="invalid-feedback" data-error-for="book_residual_value_percent"></div></div></div>
        <hr class="my-4"><h2 class="h5 mb-3">ค่าเสื่อมภาษี</h2><div class="row g-3"><div class="col-md-3"><label class="form-label">วิธี</label><select class="form-select" name="tax_method"><option value="STRAIGHT_LINE" @selected(old('tax_method', $assetCategory->tax_method) === 'STRAIGHT_LINE')>เส้นตรง</option></select><div class="invalid-feedback" data-error-for="tax_method"></div></div><div class="col-md-3"><label class="form-label">อายุใช้งาน (เดือน)</label><input class="form-control" type="number" min="1" max="1200" name="tax_useful_life_months" value="{{ old('tax_useful_life_months', $assetCategory->tax_useful_life_months) }}"><div class="invalid-feedback" data-error-for="tax_useful_life_months"></div></div><div class="col-md-3"><label class="form-label">อัตราภาษี (%)</label><input class="form-control" type="number" min="0" max="100" step="0.0001" name="tax_rate_percent" value="{{ old('tax_rate_percent', $assetCategory->tax_rate_percent) }}"><div class="invalid-feedback" data-error-for="tax_rate_percent"></div></div><div class="col-md-3"><label class="form-label">เพดานต้นทุนภาษี</label><input class="form-control" type="number" min="0" step="0.01" name="tax_cost_cap" value="{{ old('tax_cost_cap', $assetCategory->tax_cost_cap) }}"><div class="invalid-feedback" data-error-for="tax_cost_cap"></div></div></div>
        <hr class="my-4"><h2 class="h5 mb-3">บัญชี GL</h2><div class="row g-3">
        @foreach (['asset_account_id' => 'บัญชีสินทรัพย์ *', 'accumulated_depreciation_account_id' => 'ค่าเสื่อมสะสม', 'depreciation_expense_account_id' => 'ค่าเสื่อมราคา', 'accumulated_impairment_account_id' => 'ด้อยค่าสะสม', 'impairment_loss_account_id' => 'ขาดทุนจากการด้อยค่า', 'disposal_clearing_account_id' => 'บัญชีพักเงินรับจากการจำหน่าย', 'disposal_gain_account_id' => 'กำไรจากการจำหน่าย', 'disposal_loss_account_id' => 'ขาดทุนจากการจำหน่าย'] as $field => $label)
            @php($account = $selectedAccounts->get(old($field, $assetCategory->{$field})))
            <div class="col-12 col-md-6"><label class="form-label" for="{{ $field }}">{{ $label }}{{ in_array($field, ['accumulated_depreciation_account_id', 'depreciation_expense_account_id']) ? ' (เมื่อคิดค่าเสื่อม)' : '' }}</label><select class="form-select js-account" id="{{ $field }}" name="{{ $field }}" data-field="{{ $field }}" @if($field === 'asset_account_id') required @endif><option value="">ไม่กำหนด</option>@if($account)<option value="{{ $account->id }}" selected>{{ $account->code }} · {{ $account->name }}</option>@endif</select><div class="invalid-feedback" data-error-for="{{ $field }}"></div></div>
        @endforeach
        </div><div class="d-flex justify-content-between mt-4"><a class="btn btn-outline-dark" href="{{ route('asset.categories.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับ</a><button class="btn btn-dark" type="submit" data-busy-text="กำลังบันทึก..."><i class="bx bx-save me-1" aria-hidden="true"></i>บันทึกหมวดสินทรัพย์</button></div>
    </form></div></div></div>
@endsection

@push('scripts')
<script>
$(function () {
    $('.js-account').each(function () { var $select=$(this); $select.select2({width:'100%',allowClear:true,placeholder:'ค้นหาบัญชี GL',ajax:{url:@json(route('asset.categories.accounts')),dataType:'json',delay:250,data:function(params){return {q:params.term||'',page:params.page||1,field:$select.data('field')};},processResults:function(data){return data;},cache:true}}); });
    function depreciationFields() { $('.js-depreciable').toggle($('#is_depreciable').is(':checked')); }
    $('#is_depreciable').on('change', depreciationFields); depreciationFields();
    window.erpAjaxForm({form:'#asset-category-form',redirect:@json(! $assetCategory->exists),reload:false});
});
</script>
@endpush
