@extends('Finance::layout')
@section('title', $voucher->document_number.' | Finance')
@section('content')
    @php($labels=['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'อนุมัติแล้ว','VOID'=>'ยกเลิก'])
    @php($classes=['DRAFT'=>'app-status-neutral','SUBMITTED'=>'app-status-info','APPROVED'=>'app-status-success','VOID'=>'app-status-danger'])
    <div class="container-fluid px-3 px-lg-4 py-4"><p class="eyebrow mb-2">FINANCE / VOUCHERS</p><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><h1 class="h3 mb-2">{{ $voucher->document_number }}</h1><div class="text-secondary">{{ $voucher->voucher_type === 'PRE_PAYMENT' ? 'ใบขอจ่ายล่วงหน้า' : 'ใบสำคัญจ่าย' }}</div></div><div class="d-flex gap-2"><span class="badge {{ $classes[$voucher->status] ?? 'app-status-neutral' }}">{{ $labels[$voucher->status] ?? $voucher->status }}</span><a class="btn btn-outline-secondary" href="{{ route('finance.payment-vouchers.index') }}">กลับ</a></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="row g-3"><div class="col-md-3"><div class="small text-secondary">วันที่เอกสาร</div>{{ $voucher->document_date?->format($dateFormat) ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">คู่ค้า</div>{{ $voucher->party?->code ?? '—' }} · {{ $voucher->party?->name ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">บัญชีเงิน</div>{{ $voucher->bankAccount?->code ?? '—' }} · {{ $voucher->bankAccount?->name ?? '—' }}</div><div class="col-md-3"><div class="small text-secondary">จำนวนเงิน</div><strong>{{ number_format((float) $voucher->amount, 2) }}</strong></div><div class="col-12"><div class="small text-secondary">Settlement</div>{{ $voucher->settlement?->document_number ?? 'ยังไม่ได้สร้าง Settlement' }}</div>@if($voucher->description)<div class="col-12"><div class="small text-secondary">รายละเอียด</div>{{ $voucher->description }}</div>@endif</div></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">รายการจัดสรรเจ้าหนี้</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>เอกสารเจ้าหนี้</th><th>รายละเอียด</th><th class="text-end">จำนวนเงิน</th></tr></thead><tbody>@forelse($voucher->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->openItem?->document_number ?? $line->open_item_document_number ?? '—' }}</td><td>{{ $line->description ?? '—' }}</td><td class="text-end">{{ number_format((float) $line->amount, 2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary">ยังไม่มีรายการจัดสรร</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{ $event->created_at->format('d/m/Y H:i') }}</div><div><strong>{{ $event->action }}</strong><div class="small text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">รายละเอียด:</span> {{ $event->reason }}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติ</p>@endforelse</div></div>
    </div>
@endsection
