@extends('Production::layout')
@section('title', 'ใบสั่งผลิต | Production')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">PRODUCTION / WORK ORDERS</p><h1 class="h3 mb-1">ใบสั่งผลิต</h1><p class="text-secondary mb-0">ติดตาม WO ที่สร้างจากคำสั่งขายหรือสร้างเพื่อ Stock</p></div>
        <div class="d-flex flex-wrap gap-2">@if(auth()->user()->hasPermission('production.orders.create'))@if(auth()->user()->hasPermission('production.orders.view'))<a class="btn btn-app-soft" href="{{ route('production.demand.index') }}"><i class="bx bx-list-plus me-1" aria-hidden="true"></i>สร้างจากคำสั่งขาย</a>@endif<a class="btn btn-app-primary" href="{{ route('production.orders.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>สร้างใบสั่งผลิต</a>@endif</div>
    </div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-header bg-transparent d-flex justify-content-between align-items-center"><strong>ตัวกรอง</strong><button class="btn btn-sm btn-app-soft" id="reset-production-order-filters" type="button"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="card-body"><form id="production-order-filters" class="row g-3"><div class="col-12 col-md-4"><label class="form-label" for="production-order-status">สถานะ</label><select class="form-select" id="production-order-status" name="status"><option value="">ทั้งหมด</option><option value="DRAFT">ร่าง</option><option value="RELEASED">พร้อมผลิต</option><option value="IN_PROGRESS">กำลังผลิต</option><option value="COMPLETED">เสร็จแล้ว</option><option value="CANCELLED">ยกเลิกเอกสาร</option></select></div><div class="col-6 col-md-3"><label class="form-label" for="production-order-date-from">วันที่สร้างตั้งแต่</label><input class="form-control" id="production-order-date-from" name="date_from" type="date"></div><div class="col-6 col-md-3"><label class="form-label" for="production-order-date-to">ถึง</label><input class="form-control" id="production-order-date-to" name="date_to" type="date"></div><div class="col-12 col-md-2 d-flex align-items-end"><button class="btn btn-app-primary w-100" type="submit"><i class="bx bx-search me-1" aria-hidden="true"></i>ค้นหา</button></div></form></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="production-orders-table" class="table table-hover align-middle w-100" data-url="{{ route('production.orders.data') }}"><thead><tr><th>ลำดับ</th><th>เลข WO</th><th>Source</th><th>สินค้า</th><th class="text-end">จำนวน</th><th>สถานะ</th><th>จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')
<script>
$(function(){ const esc=$.fn.dataTable.render.text().display, table=$('#production-orders-table'), filters=$('#production-order-filters'), statusClasses={DRAFT:'app-status-neutral',RELEASED:'app-status-info',IN_PROGRESS:'app-status-warning',COMPLETED:'app-status-success',CANCELLED:'app-status-danger'}; const dt=table.DataTable({...window.erpDataTableDefaults, buttons:[window.erpExcelButton(table)], ajax:{url:table.data('url'),data:function(d){ filters.serializeArray().forEach(function(x){d[x.name]=x.value;}); }}, columns:[window.erpRowNumberColumn(), {data:'document_number', render:function(d,t,r){return t==='display'?'<a href="'+esc(r.show_url)+'">'+esc(d)+'</a>':d;}}, {data:'source_label', render:esc}, {data:'finished_item_label', render:esc}, {data:'quantity_label', className:'text-end', render:esc}, {data:'status_label', render:function(d,t,r){return '<span class="badge '+(statusClasses[r.status]||'app-status-neutral')+'">'+esc(d)+'</span>'; }}, {data:null, orderable:false, searchable:false, render:function(_,t,r){if(t!=='display')return ''; let html='<a class="btn btn-sm btn-app-soft" href="'+esc(r.show_url)+'" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-show" aria-hidden="true"></i></a>'; if(r.edit_url) html+=' <a class="btn btn-sm btn-app-soft" href="'+esc(r.edit_url)+'" title="แก้ไข" aria-label="แก้ไข"><i class="bx bx-edit" aria-hidden="true"></i></a>'; return html;}}]}); filters.on('submit',function(e){e.preventDefault();dt.ajax.reload();}); $('#reset-production-order-filters').on('click',function(){filters[0].reset();dt.ajax.reload();}); });
</script>
@endpush
