@extends('Finance::layout')

@section('title', ($topUp->exists ? 'แก้ไข' : 'สร้าง').'เติมเงินสดย่อย | New ERP')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">FINANCE / PETTY CASH</p><h1 class="h3 mb-1">{{ $topUp->exists ? 'แก้ไขเอกสารเติมเงินสดย่อย' : 'สร้างเอกสารเติมเงินสดย่อย' }}</h1><p class="text-secondary mb-0">บันทึกได้เฉพาะ Draft และระบบจะกำหนดเลขเอกสารอัตโนมัติ</p></div><a class="btn btn-outline-secondary" href="{{ $topUp->exists ? route('finance.petty-cash-top-ups.show',$topUp) : route('finance.petty-cash-top-ups.index') }}">กลับ</a></div><form id="top-up-form" method="POST" action="{{ $topUp->exists ? route('finance.petty-cash-top-ups.update',$topUp) : route('finance.petty-cash-top-ups.store') }}">@csrf @if($topUp->exists)@method('PUT')@endif<div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-6"><label class="form-label">วงเงินสดย่อย</label><select class="form-select" name="petty_cash_fund_id" required><option value="">เลือกวงเงินสดย่อย</option>@foreach($fundOptions as $id=>$label)<option value="{{ $id }}" @selected((int)old('petty_cash_fund_id',$topUp->petty_cash_fund_id)===(int)$id)>{{ $label }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">บัญชีธนาคารต้นทาง</label><select class="form-select" name="source_bank_account_id" required><option value="">เลือกบัญชีธนาคาร</option>@foreach($sourceBankAccountOptions as $id=>$label)<option value="{{ $id }}" @selected((int)old('source_bank_account_id',$topUp->source_bank_account_id)===(int)$id)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">วันที่เอกสาร</label><input class="form-control" type="date" name="document_date" value="{{ old('document_date',optional($topUp->document_date)->format('Y-m-d')) }}" required></div><div class="col-md-4"><label class="form-label">จำนวนเงิน</label><input class="form-control text-end" type="number" name="amount" min="0.01" step="0.01" value="{{ old('amount',$topUp->amount) }}" required></div><div class="col-12"><label class="form-label">รายละเอียด</label><textarea class="form-control" name="description" maxlength="500" rows="3">{{ old('description',$topUp->description) }}</textarea></div></div></div></div><div class="mt-4 d-flex gap-2"><button class="btn btn-dark" type="submit">{{ $topUp->exists ? 'บันทึกการแก้ไข' : 'บันทึกฉบับร่าง' }}</button><a class="btn btn-outline-secondary" href="{{ route('finance.petty-cash-top-ups.index') }}">ยกเลิก</a></div></form></div>
@endsection

@push('scripts')<script>$(function(){window.erpAjaxForm({form:'#top-up-form',redirect:true});});</script>@endpush
