@extends('Wms::layout')
@section('title', 'รายละเอียด Stock Card | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">WMS / STOCK</p><h1 class="h3 mb-2">รายละเอียด Stock Card</h1><p class="text-secondary mb-0">{{ $item->code }} · {{ $item->name }}</p></div>
        <a class="btn btn-app-soft" href="{{ route('wms.stock.index') }}"><i class="bx bx-arrow-back me-1"></i>กลับรายการสินค้า</a>
    </div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body row g-3"><div class="col-md-3"><div class="small text-secondary">รหัสสินค้า</div><div class="fw-semibold">{{ $item->code }}</div></div><div class="col-md-5"><div class="small text-secondary">ชื่อสินค้า</div><div class="fw-semibold">{{ $item->name }}</div></div><div class="col-md-2"><div class="small text-secondary">ประเภท</div><div>{{ $item->item_type === 'SERVICE' ? 'บริการ' : 'สินค้า' }}</div></div><div class="col-md-2"><div class="small text-secondary">ณ วันที่</div><input id="stock-detail-as-of" class="form-control form-control-sm" type="date" value="{{ now()->format('Y-m-d') }}"></div></div></div>
    <div class="row g-3 mb-4"><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">คงเหลือ</div><div class="h4" id="stock-on-hand">-</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">จอง</div><div class="h4" id="stock-reserved">-</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="small text-secondary">ใช้ได้</div><div class="h4" id="stock-available">-</div></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">การเคลื่อนไหวสินค้า</h2><div class="table-responsive"><table id="stock-movement-table" class="table table-hover w-100" data-url="{{ route('wms.stock.data') }}"><thead><tr><th rowspan="2">ลำดับ</th><th rowspan="2">วันที่เวลา</th><th colspan="2" class="text-center">เอกสาร</th><th colspan="3" class="text-center text-success">รับเข้า</th><th colspan="3" class="text-center text-danger">จ่ายออก</th><th colspan="3" class="text-center text-info">คงเหลือ</th><th rowspan="2">Manual</th></tr><tr><th>เลขเอกสาร</th><th>รายละเอียด</th><th class="text-success">จำนวน</th><th class="text-success">ต่อหน่วย</th><th class="text-success">รวม</th><th class="text-danger">จำนวน</th><th class="text-danger">ต่อหน่วย</th><th class="text-danger">รวม</th><th class="text-info">จำนวน</th><th class="text-info">ต่อหน่วย</th><th class="text-info">รวม</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')
<script>$(function(){var t=$('#stock-movement-table'),x=$.fn.dataTable.render.text(),wmsPlaces={{ \App\Modules\Wms\Support\WmsDecimal::places() }},hasValue=function(v){return v!==null&&v!==undefined&&v!=='';},fmt=function(v){if(!hasValue(v))return '-';var n=Number(v);return Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:wmsPlaces,maximumFractionDigits:wmsPlaces}):'-';},colored=function(cls,v){return '<span class="'+cls+'">'+x.display(fmt(v))+'</span>';};var dt=t.DataTable($.extend(true,{},window.erpDataTableDefaults,{order:[[1,'asc']],ajax:{url:t.data('url'),data:function(d){d.item_id={{ $item->id }};d.as_of=$('#stock-detail-as-of').val();}},buttons:[window.erpExcelButton(t)],columns:[{data:null,orderable:false,searchable:false,render:function(v,type,row,meta){return type==='display'?meta.row+meta.settings._iDisplayStart+1:'';}},{data:'movement_datetime',name:'wms_stock_movements.business_date',render:x.display},{data:'source_reference',orderable:false,render:function(v){return x.display(v||'-')}},{data:'movement_type_label',orderable:false,render:x.display},{data:null,orderable:false,render:function(v,type,row){return type==='display'?colored('text-success',row.direction==='IN'?row.base_quantity:'-'):' ';}},{data:'unit_cost',orderable:false,className:'text-end',render:function(v,type){return type==='display'?colored('text-success',hasValue(v)?v:'-'):v;}},{data:'movement_total',orderable:false,className:'text-end',render:function(v,type){return type==='display'?colored('text-success',v):v;}},{data:null,orderable:false,render:function(v,type,row){return type==='display'?colored('text-danger',row.direction==='OUT'?row.base_quantity:'-'):' ';}},{data:'unit_cost',orderable:false,className:'text-end',render:function(v,type,row){return type==='display'?colored('text-danger',row.direction==='OUT'&&hasValue(row.unit_cost)?row.unit_cost:'-'):v;}},{data:null,orderable:false,render:function(v,type,row){return type==='display'?colored('text-danger',row.direction==='OUT'?row.movement_total:'-'):' ';}},{data:'running_balance',orderable:false,className:'text-end',render:function(v,type){return type==='display'?colored('text-info',v):v;}},{data:'unit_cost',orderable:false,className:'text-end',render:function(v,type){return type==='display'?colored('text-info',hasValue(v)?v:'-'):v;}},{data:'running_value',orderable:false,className:'text-end',render:function(v,type){return type==='display'?colored('text-info',v):v;}},{data:null,orderable:false,searchable:false,render:function(){return '<span class="text-secondary">-</span>';}}],drawCallback:function(s){var b=s.json&&s.json.balance||{};$('#stock-on-hand').text(b.on_hand||'-');$('#stock-reserved').text(b.reserved||'-');$('#stock-available').text(b.available||'-')}}));$('#stock-detail-as-of').on('change',function(){dt.ajax.reload()})});</script>
@endpush
