@php
    $statusLabels = ['DRAFT' => 'ร่าง', 'SENT' => 'ส่งแล้ว', 'REVIEWED' => 'ตรวจสอบแล้ว', 'CLOSED' => 'ปิดแล้ว', 'CANCELLED' => 'ยกเลิก'];
    $status = $statusLabels[$salesRfq->status] ?? $salesRfq->status;
    $branchLabel = !empty($companyTaxBranchCode) ? ($companyTaxBranchCode === '00000' ? 'สำนักงานใหญ่' : 'สาขา '.$companyTaxBranchCode) : null;
@endphp
<htmlpageheader name="sales-rfq-reference"><div style="font-family:notosansthai;font-size:8.5pt;color:#737b83;text-align:right">{{ $companyName }} · {{ $salesRfq->document_number }} · {{ optional($salesRfq->document_date)->format($dateFormat) }}</div></htmlpageheader>
<sethtmlpageheader name="sales-rfq-reference" value="on" show-this-page="1" />
<div class="pdf-tax-invoice">
    <table class="pdf-header"><tr>
        @if($logo)<td class="invoice-logo" width="16%"><img src="{{ $logo }}" style="width:24mm;max-height:22mm"></td>@endif
        <td class="pdf-header-company" width="{{ $logo ? '44%' : '60%' }}"><h1>{{ $companyName ?: 'บริษัท' }}</h1><div>{{ $companyAddress ?: '—' }}</div>@if($branchLabel)<div class="muted">{{ $branchLabel }}</div>@endif @if(!empty($companyTaxId))<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $companyTaxId }}</div>@endif</td>
        <td class="pdf-header-title" width="40%"><div class="pdf-copy">เอกสารทางการค้า</div><h2>ใบขอราคา / RFQ</h2><div class="invoice-number">{{ $salesRfq->document_number }}</div><div class="muted">สถานะ: {{ $status }}</div></td>
    </tr></table>
    @if($salesRfq->status === 'DRAFT')<p class="pdf-watermark">ร่าง — ยังไม่ใช่เอกสารที่ยืนยันแล้ว</p>@endif
    @if($salesRfq->status === 'CANCELLED')<p class="pdf-watermark">ยกเลิกเอกสาร</p>@endif
    <table class="pdf-party"><tr><td width="60%" class="invoice-buyer"><div class="pdf-label">ผู้ขอราคา</div><div class="pdf-value">{{ $salesRfq->party_code }} · {{ $salesRfq->party_name }}</div><div>{{ $salesRfq->party_address ?: '—' }}</div>@if($salesRfq->party_tax_id)<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $salesRfq->party_tax_id }}</div>@endif @if($salesRfq->party_branch_code)<div class="muted">{{ $salesRfq->party_branch_code === '00000' ? 'สำนักงานใหญ่' : 'สาขา '.$salesRfq->party_branch_code }}</div>@endif</td><td width="40%" class="invoice-details"><table class="invoice-meta"><tr><td>เลขที่</td><td class="right">{{ $salesRfq->document_number }}</td></tr><tr><td>วันที่เอกสาร</td><td class="right">{{ optional($salesRfq->document_date)->format($dateFormat) ?: '—' }}</td></tr><tr><td>ใช้ได้ถึง</td><td class="right">{{ optional($salesRfq->valid_until)->format($dateFormat) ?: '—' }}</td></tr>@if($sourceLabel)<tr><td>อ้างอิง</td><td class="right">{{ $sourceLabel }}</td></tr>@endif</table></td></tr></table>
    <table class="pdf-product" autosize="1"><thead><tr><th width="5%">#</th><th width="55%" class="invoice-item-heading">รายการสินค้า / รายละเอียด</th><th width="15%">จำนวน</th><th width="15%">หน่วย</th><th width="10%" class="right">ราคาเสนอ</th></tr></thead><tbody>@forelse($salesRfq->lines as $line)<tr><td class="center">{{ $line->line_number }}</td><td><div>{{ data_get($line->item_snapshot, 'name', '—') }}</div><div class="invoice-item-code">{{ data_get($line->item_snapshot, 'code') }}</div>@if($line->description)<div class="muted">{{ $line->description }}</div>@endif</td><td class="right">{{ number_format((float) $line->quantity, 2) }}</td><td class="center">{{ $line->uom?->code ?: data_get($line->uom_snapshot, 'code', '—') }}</td><td class="right">—</td></tr>@empty<tr><td colspan="5" class="center">ไม่มีรายการสินค้า</td></tr>@endforelse</tbody></table>
</div>
<!-- invoice-closing -->
<div class="pdf-tax-invoice"><table class="pdf-footer"><tr><td width="55%" class="pdf-footer-payment"><div class="pdf-footer-heading">รายละเอียดเพิ่มเติม</div><p class="muted">เอกสารนี้จัดทำขึ้นเพื่อขอราคาและยังไม่ใช่คำสั่งซื้อ</p>@if($salesRfq->description)<p class="pdf-note"><b>หมายเหตุ:</b> {{ $salesRfq->description }}</p>@endif</td><td width="45%" class="pdf-footer-total"><table class="pdf-total-summary"><tr><td>จำนวนรายการ</td><td class="right">{{ $salesRfq->lines->count() }}</td></tr><tr class="total"><td>สถานะเอกสาร</td><td class="right">{{ $status }}</td></tr></table></td></tr></table><x-platform::pdf-signatures :document="$salesRfq" :slots="[['role' => 'prepared', 'label' => 'ผู้ขอราคา'], ['role' => 'approved', 'label' => 'ผู้ตรวจสอบ']]" /><p class="pdf-control">{{ $salesRfq->document_number }} · ใบขอราคา / RFQ</p></div>
