<style>body{font-family:sans-serif;font-size:10.5pt;color:#20252b}h1{margin:0 0 2px}h2{text-align:center;margin:16px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid #b8c0ca;padding:6px;vertical-align:top}thead{display:table-header-group}.right{text-align:right}.muted{color:#68727d}.total td{font-weight:bold}.history{page-break-inside:avoid}</style>
@if($logo)<img src="{{ $logo }}" style="height:55px">@endif
<h1>{{ $companyName }}</h1><div class="muted">{{ $companyAddress ?: '—' }}</div>
<h2>ใบรับคืน / ใบลดหนี้จาก HS/IV</h2>
<table><tbody><tr><td>เลขที่: <b>{{ $returnDocument->document_number }}</b></td><td>วันที่: {{ $returnDocument->document_date?->format($dateFormat) }}</td><td>สถานะ: {{ ['DRAFT'=>'ร่าง','POSTED'=>'ลงบัญชีแล้ว','VOID'=>'ยกเลิก'][$returnDocument->status] ?? $returnDocument->status }}</td></tr><tr><td colspan="3">ลูกค้า: {{ $returnDocument->party_code }} · {{ $returnDocument->party_name }}<br>เอกสารต้นทาง HS/IV: {{ $returnDocument->sale?->document_number ?: '—' }}<br>เหตุผล: {{ $returnDocument->reason }}</td></tr></tbody></table>
<br><table><thead><tr><th>#</th><th>สินค้า</th><th>หน่วย</th><th>จำนวนคืน</th><th>ราคา/หน่วย</th><th>รวม</th></tr></thead><tbody>
@forelse($returnDocument->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ data_get($line->item_snapshot,'code') }} · {{ data_get($line->item_snapshot,'name') }}</td><td>{{ $line->uom?->code ?: '—' }}</td><td class="right">{{ number_format((float) $line->quantity, $decimalPlaces) }}</td><td class="right">{{ number_format((float) $line->unit_price, 2) }}</td><td class="right">{{ number_format((float) $line->line_total, 2) }}</td></tr>@empty<tr><td colspan="6">ไม่มีรายการสินค้า</td></tr>@endforelse
<tr class="total"><td colspan="5" class="right">รวมสุทธิ</td><td class="right">{{ number_format((float) $returnDocument->total_amount, 2) }}</td></tr></tbody></table>
<div class="history"><h3>ประวัติเอกสาร</h3><table><thead><tr><th>วันเวลา</th><th>รายการ</th><th>ผู้ดำเนินการ</th></tr></thead><tbody>@forelse($history as $event)<tr><td>{{ $event->created_at?->format($dateFormat.' H:i') }}</td><td>{{ ['pos.sales-return.created'=>'สร้างร่างใบรับคืน'][$event->action] ?? 'ดำเนินการกับเอกสาร' }}</td><td>{{ $event->user?->name ?: 'ระบบ' }}</td></tr>@empty<tr><td colspan="3">ยังไม่มีประวัติ</td></tr>@endforelse</tbody></table></div>
