@php($status = ['DRAFT' => 'ร่าง', 'POSTED' => 'ลงบัญชีแล้ว', 'VOID' => 'ยกเลิก'][$returnDocument->status] ?? $returnDocument->status)
<htmlpageheader name="sales-return-reference"><div style="font-family:notosansthai;font-size:8.5pt;color:#737b83;text-align:right">{{ $companyName }} · {{ $returnDocument->document_number }} · {{ optional($returnDocument->document_date)->format($dateFormat) }}</div></htmlpageheader>
<sethtmlpageheader name="sales-return-reference" value="on" show-this-page="1" />
<div class="pdf-tax-invoice">
    @if($returnDocument->status === 'DRAFT')<p class="pdf-watermark">ร่าง — ยังไม่ใช่เอกสารรับคืนฉบับสมบูรณ์</p>@elseif($returnDocument->status === 'VOID')<p class="pdf-watermark">ยกเลิกเอกสาร</p>@endif
    <table class="pdf-header"><tr>@if($logo)<td class="invoice-logo" width="16%"><img src="{{ $logo }}" style="width:24mm;max-height:22mm"></td>@endif<td class="pdf-header-company" width="{{ $logo ? '44%' : '60%' }}"><h1>{{ $companyName ?: 'บริษัท' }}</h1><div>{{ $companyAddress ?: '—' }}</div>@if($companyTaxId)<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $companyTaxId }}</div>@endif</td><td class="pdf-header-title" width="40%"><div class="pdf-copy">เอกสารรับคืน</div><h2>ใบรับคืนสินค้า</h2><div class="invoice-number">{{ $returnDocument->document_number }}</div><div class="muted">สถานะ: {{ $status }}</div></td></tr></table>
    <table class="pdf-party"><tr><td width="60%" class="invoice-buyer"><div class="pdf-label">ลูกค้า</div><div class="pdf-value">{{ $returnDocument->party_code }} · {{ $returnDocument->party_name }}</div><div>{{ $returnDocument->party_address ?: '—' }}</div></td><td width="40%" class="invoice-details"><table class="invoice-meta"><tr><td>วันที่เอกสาร</td><td class="right">{{ $returnDocument->document_date?->format($dateFormat) ?: '—' }}</td></tr><tr><td>เอกสารต้นทาง</td><td class="right">{{ $returnDocument->sale?->document_number ?: '—' }}</td></tr></table></td></tr></table>
    <table class="pdf-product"><thead><tr><th width="8%">#</th><th width="42%">สินค้า / รายละเอียด</th><th width="14%">หน่วย</th><th width="14%" class="right">จำนวนคืน</th><th width="11%" class="right">ราคา/หน่วย</th><th width="11%" class="right">จำนวนเงิน</th></tr></thead><tbody>@forelse($returnDocument->lines as $line)<tr><td class="center">{{ $line->line_number }}</td><td><div>{{ data_get($line->item_snapshot, 'name', '—') }}</div><div class="invoice-item-code">{{ data_get($line->item_snapshot, 'code') }}</div></td><td class="center">{{ $line->uom?->code ?: '—' }}</td><td class="right">{{ number_format((float) $line->quantity, $decimalPlaces) }}</td><td class="right">{{ number_format((float) $line->unit_price, 2) }}</td><td class="right">{{ number_format((float) $line->line_total, 2) }}</td></tr>@empty<tr><td colspan="6" class="center">ไม่มีรายการสินค้า</td></tr>@endforelse</tbody></table>
</div>
<!-- invoice-closing -->
<div class="pdf-tax-invoice"><table class="pdf-footer"><tr><td width="55%" class="pdf-footer-payment"><div class="pdf-footer-heading">รายละเอียดการรับคืน</div><p class="muted">เอกสารนี้ไม่ใช่ใบลดหนี้หรือใบกำกับภาษี</p><p class="pdf-note"><b>เหตุผล:</b> {{ $returnDocument->reason ?: '—' }}</p></td><td width="45%" class="pdf-footer-total"><table class="pdf-total-summary"><tr class="total"><td>รวมมูลค่ารับคืน</td><td class="right">{{ number_format((float) $returnDocument->total_amount, 2) }}</td></tr></table></td></tr></table><x-platform::pdf-signatures :document="$returnDocument" :slots="[['role' => 'prepared', 'label' => 'ผู้รับคืนสินค้า'], ['role' => 'posted', 'label' => 'ผู้อนุมัติ']]" /><p class="pdf-control">{{ $returnDocument->document_number }} · ใบรับคืนสินค้า</p></div>
