@php
    $statusLabels = ['DRAFT' => 'ร่าง', 'COMPLETED' => 'เสร็จสิ้น', 'CANCELLED' => 'ยกเลิก'];
    $status = $statusLabels[$intake->status] ?? $intake->status;
    $hasTax = (float) $intake->tax_amount > 0;
    $taxBase = $hasTax ? (float) $intake->tax_base : (float) $intake->grand_total;
    $vat = $hasTax ? (float) $intake->tax_amount : 0;
    $branchLabel = !empty($companyTaxBranchCode) ? ($companyTaxBranchCode === '00000' ? 'สำนักงานใหญ่' : 'สาขา '.$companyTaxBranchCode) : null;
@endphp
<htmlpageheader name="sales-intake-reference"><div style="font-family:notosansthai;font-size:8.5pt;color:#737b83;text-align:right">{{ $companyName }} · {{ $intake->document_number }} · {{ optional($intake->document_date)->format($dateFormat) }}</div></htmlpageheader>
<sethtmlpageheader name="sales-intake-reference" value="on" show-this-page="1" />
<div class="pdf-tax-invoice">
    <table class="pdf-header"><tr>
        @if($logo)<td class="invoice-logo" width="16%"><img src="{{ $logo }}" style="width:24mm;max-height:22mm"></td>@endif
        <td class="pdf-header-company" width="{{ $logo ? '44%' : '60%' }}"><h1>{{ $companyName ?: 'บริษัท' }}</h1><div>{{ $companyAddress ?: '—' }}</div>@if($branchLabel)<div class="muted">{{ $branchLabel }}</div>@endif @if(!empty($companyTaxId))<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $companyTaxId }}</div>@endif</td>
        <td class="pdf-header-title" width="40%"><div class="pdf-copy">เอกสารทางการค้า</div><h2>ใบรับข้อมูล</h2><div class="invoice-number">{{ $intake->document_number }}</div><div class="muted">สถานะ: {{ $status }}</div></td>
    </tr></table>
    @if($intake->status === 'DRAFT')<p class="pdf-watermark">ร่าง — ยังไม่ใช่เอกสารที่ยืนยันแล้ว</p>@endif
    @if($intake->status === 'CANCELLED')<p class="pdf-watermark">ยกเลิกเอกสาร</p>@endif
    <table class="pdf-party"><tr><td width="60%" class="invoice-buyer"><div class="pdf-label">ลูกค้า</div><div class="pdf-value">{{ $intake->party_code }} · {{ $intake->party_name }}</div><div>{{ $intake->party_address ?: '—' }}</div>@if($intake->party_tax_id)<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $intake->party_tax_id }}</div>@endif @if($intake->party_branch_code)<div class="muted">{{ $intake->party_branch_code === '00000' ? 'สำนักงานใหญ่' : 'สาขา '.$intake->party_branch_code }}</div>@endif</td><td width="40%" class="invoice-details"><table class="invoice-meta"><tr><td>เลขที่</td><td class="right">{{ $intake->document_number }}</td></tr><tr><td>วันที่เอกสาร</td><td class="right">{{ optional($intake->document_date)->format($dateFormat) ?: '—' }}</td></tr><tr><td>วิธีการสั่งซื้อ</td><td class="right">{{ $intake->order_method ?: '—' }}</td></tr><tr><td>วิธีการจัดส่ง</td><td class="right">{{ $intake->delivery_method ?: '—' }}</td></tr></table></td></tr></table>
    <table class="pdf-product" autosize="1"><thead><tr><th width="5%">#</th><th width="38%" class="invoice-item-heading">รายการสินค้า / รายละเอียด</th><th width="10%">จำนวน</th><th width="10%">หน่วย</th><th width="14%" class="right">ราคา/หน่วย</th><th width="11%" class="right">ส่วนลด</th><th width="12%" class="right">จำนวนเงิน</th></tr></thead><tbody>@forelse($intake->lines as $line)<tr><td class="center">{{ $line->line_number }}</td><td><div>{{ data_get($line->item_snapshot, 'name', $line->description) }}</div><div class="invoice-item-code">{{ data_get($line->item_snapshot, 'code') }}</div>@if($line->description)<div class="muted">{{ $line->description }}</div>@endif</td><td class="right">{{ number_format((float) $line->quantity, $decimalPlaces) }}</td><td class="center">{{ $line->uom?->code ?: data_get($line->uom_snapshot, 'code', '—') }}</td><td class="right">{{ number_format((float) ($line->requested_unit_price ?? $line->standard_unit_price ?? 0), 2) }}</td><td class="right">{{ number_format((float) $line->discount_amount, 2) }}</td><td class="right">{{ number_format((float) $line->line_total, 2) }}</td></tr>@empty<tr><td colspan="7" class="center">ไม่มีรายการสินค้า</td></tr>@endforelse</tbody></table>
</div>
<!-- invoice-closing -->
<div class="pdf-tax-invoice"><table class="pdf-footer"><tr><td width="55%" class="pdf-footer-payment"><div class="pdf-footer-heading">รายละเอียดเพิ่มเติม</div><p class="muted">เอกสารนี้จัดทำขึ้นเพื่อบันทึกข้อมูลการรับคำสั่งซื้อ</p>@if($intake->description)<p class="pdf-note"><b>หมายเหตุ:</b> {{ $intake->description }}</p>@endif</td><td width="45%" class="pdf-footer-total"><table class="pdf-total-summary"><tr><td>ยอดรวม</td><td class="right">{{ number_format((float) $intake->subtotal, 2) }}</td></tr><tr><td>ส่วนลด</td><td class="right">{{ number_format((float) $intake->discount_amount, 2) }}</td></tr>@if($hasTax)<tr><td>ฐานภาษี</td><td class="right">{{ number_format($taxBase, 2) }}</td></tr><tr><td>ภาษีมูลค่าเพิ่ม / VAT</td><td class="right">{{ number_format($vat, 2) }}</td></tr>@endif<tr class="total"><td>รวมทั้งสิ้น</td><td class="right">{{ number_format((float) $intake->grand_total, 2) }}</td></tr></table></td></tr></table><table class="pdf-signatures"><tr><td width="45%"><div class="invoice-sign-space">&nbsp;</div><div>........................................................</div><div>ผู้จัดทำ</div><div class="invoice-sign-date">วันที่ .......... / .......... / ..........</div></td><td width="10%" class="invoice-sign-gap"></td><td width="45%"><div class="invoice-sign-space">&nbsp;</div><div>........................................................</div><div>ผู้ตรวจสอบ</div><div class="invoice-sign-date">วันที่ .......... / .......... / ..........</div></td></tr></table><p class="pdf-control">{{ $intake->document_number }} · ใบรับข้อมูล</p></div>
