@php
    $statusLabels = ['DRAFT' => 'ร่าง', 'CONFIRMED' => 'ยืนยันแล้ว', 'FULFILLED' => 'ดำเนินการแล้ว', 'CANCELLED' => 'ยกเลิก'];
    $status = $statusLabels[$order->status] ?? $order->status;
    $hasTax = $sourceIntake && (float) $sourceIntake->tax_amount > 0;
    $taxBase = $hasTax ? (float) $sourceIntake->tax_base : (float) $order->total_amount;
    $vat = $hasTax ? (float) $sourceIntake->tax_amount : 0;
    $taxMethod = $hasTax ? 'มี VAT' : 'ไม่มีภาษี';
    $branchLabel = !empty($companyTaxBranchCode) ? ($companyTaxBranchCode === '00000' ? 'สำนักงานใหญ่' : 'สาขา '.$companyTaxBranchCode) : null;
@endphp
<htmlpageheader name="sales-order-reference"><div style="font-family:notosansthai;font-size:8.5pt;color:#737b83;text-align:right">{{ $companyName }} · {{ $order->document_number }} · {{ optional($order->document_date)->format($dateFormat) }}</div></htmlpageheader>
<sethtmlpageheader name="sales-order-reference" value="on" show-this-page="1" />
<div class="pdf-tax-invoice">
    <table class="pdf-header"><tr>
        @if($logo)<td class="invoice-logo" width="16%"><img src="{{ $logo }}" style="width:24mm;max-height:22mm"></td>@endif
        <td class="pdf-header-company" width="{{ $logo ? '44%' : '60%' }}"><h1>{{ $companyName ?: 'บริษัท' }}</h1><div>{{ $companyAddress ?: '—' }}</div>@if($branchLabel)<div class="muted">{{ $branchLabel }}</div>@endif @if(!empty($companyTaxId))<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $companyTaxId }}</div>@endif</td>
        <td class="pdf-header-title" width="40%"><div class="pdf-copy">เอกสารทางการค้า</div><h2>ใบสั่งขาย / SALES ORDER</h2><div class="invoice-number">{{ $order->document_number }}</div><div class="muted">สถานะ: {{ $status }}</div></td>
    </tr></table>
    @if($order->status === 'DRAFT')<p class="pdf-watermark">ร่าง — ยังไม่ใช่เอกสารที่ยืนยันแล้ว</p>@endif
    @if($order->status === 'CANCELLED')<p class="pdf-watermark">ยกเลิกเอกสาร</p>@endif
    <table class="pdf-party"><tr><td width="60%" class="invoice-buyer"><div class="pdf-label">ลูกค้า</div><div class="pdf-value">{{ $order->party_code }} · {{ $order->party_name }}</div><div>{{ $order->party_address ?: '—' }}</div>@if($order->party_tax_id)<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $order->party_tax_id }}</div>@endif @if($order->party_branch_code)<div class="muted">{{ $order->party_branch_code === '00000' ? 'สำนักงานใหญ่' : 'สาขา '.$order->party_branch_code }}</div>@endif</td><td width="40%" class="invoice-details"><table class="invoice-meta"><tr><td>เลขที่</td><td class="right">{{ $order->document_number }}</td></tr><tr><td>วันที่เอกสาร</td><td class="right">{{ optional($order->document_date)->format($dateFormat) }}</td></tr><tr><td>ใช้ได้ถึง</td><td class="right">{{ optional($order->valid_until)->format($dateFormat) ?: '—' }}</td></tr><tr><td>ภาษี</td><td class="right">{{ $taxMethod }}</td></tr>@if($sourceLabel)<tr><td>อ้างอิง</td><td class="right">{{ $sourceLabel }}</td></tr>@endif</table></td></tr></table>
    <table class="pdf-product" autosize="1"><thead><tr><th width="5%">#</th><th width="38%" class="invoice-item-heading">รายการสินค้า / รายละเอียด</th><th width="10%">จำนวน</th><th width="10%">หน่วย</th><th width="14%" class="right">ราคา/หน่วย</th><th width="11%" class="right">ส่วนลด</th><th width="12%" class="right">จำนวนเงิน</th></tr></thead><tbody>@forelse($order->lines as $line)<tr><td class="center">{{ $line->line_number }}</td><td><div>{{ data_get($line->item_snapshot, 'name', $line->description) }}</div><div class="invoice-item-code">{{ data_get($line->item_snapshot, 'code') }}</div>@if($line->description && $line->description !== data_get($line->item_snapshot, 'name'))<div class="muted">{{ $line->description }}</div>@endif</td><td class="right">{{ number_format((float) $line->quantity, $decimalPlaces) }}</td><td class="center">{{ data_get($line->uom_snapshot, 'code') ?: '—' }}</td><td class="right">{{ number_format((float) $line->unit_price, 2) }}</td><td class="right">{{ number_format((float) $line->discount_amount, 2) }}</td><td class="right">{{ number_format((float) $line->line_total, 2) }}</td></tr>@empty<tr><td colspan="7" class="center">ไม่มีรายการสินค้า</td></tr>@endforelse</tbody></table>
</div>
<!-- invoice-closing -->
<div class="pdf-tax-invoice"><table class="pdf-footer"><tr><td width="55%" class="pdf-footer-payment"><div class="pdf-footer-heading">เงื่อนไขใบสั่งขาย</div><p class="muted">เอกสารนี้ใช้สำหรับยืนยันรายการสั่งซื้อและยังไม่ใช่ใบกำกับภาษี</p>@if($order->description)<p class="pdf-note"><b>หมายเหตุ:</b> {{ $order->description }}</p>@endif</td><td width="45%" class="pdf-footer-total"><table class="pdf-total-summary"><tr><td>ยอดรวม</td><td class="right">{{ number_format((float) $order->subtotal, 2) }}</td></tr><tr><td>ส่วนลด</td><td class="right">{{ number_format((float) $order->discount_amount, 2) }}</td></tr>@if($hasTax)<tr><td>ฐานภาษี</td><td class="right">{{ number_format($taxBase, 2) }}</td></tr><tr><td>ภาษีมูลค่าเพิ่ม / VAT</td><td class="right">{{ number_format($vat, 2) }}</td></tr>@endif<tr class="total"><td>รวมทั้งสิ้น</td><td class="right">{{ number_format((float) $order->total_amount, 2) }}</td></tr></table></td></tr></table><x-platform::pdf-signatures :document="$order" :slots="[['role' => 'prepared', 'label' => 'ผู้สั่งซื้อ'], ['role' => 'approved', 'label' => 'ผู้อนุมัติ']]" /><p class="pdf-control">{{ $order->document_number }} · ใบสั่งขาย / SALES ORDER</p></div>
