@php($status = ['DRAFT'=>'ร่าง','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','VOID'=>'ยกเลิก'][$document->status] ?? $document->status)
@php($title = $document->document_type === 'CREDIT_NOTE' ? 'ใบลดหนี้' : 'ใบแจ้งหนี้')
<htmlpageheader name="sales-document-reference"><div style="font-family:notosansthai;font-size:8.5pt;color:#737b83;text-align:right">{{ $companyName }} · {{ $document->document_number }} · {{ optional($document->document_date)->format($dateFormat) }}</div></htmlpageheader>
<sethtmlpageheader name="sales-document-reference" value="on" show-this-page="1" />
<div class="pdf-tax-invoice">
    <table class="pdf-header"><tr>@if($logo)<td class="invoice-logo" width="16%"><img src="{{ $logo }}" style="width:24mm;max-height:22mm"></td>@endif<td class="pdf-header-company" width="{{ $logo ? '44%' : '60%' }}"><h1>{{ $companyName ?: 'บริษัท' }}</h1><div>{{ $companyAddress ?: '—' }}</div>@if($companyTaxId)<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $companyTaxId }}</div>@endif</td><td class="pdf-header-title" width="40%"><div class="pdf-copy">เอกสารการเงิน</div><h2>{{ $title }}</h2><div class="invoice-number">{{ $document->document_number }}</div><div class="muted">สถานะ: {{ $status }}</div></td></tr></table>
    @if($document->status === 'DRAFT')<p class="pdf-watermark">ร่าง — ยังไม่ใช่เอกสารที่ยืนยันแล้ว</p>@elseif($document->status === 'VOID')<p class="pdf-watermark">ยกเลิกเอกสาร</p>@endif
    <table class="pdf-party"><tr><td width="60%" class="invoice-buyer"><div class="pdf-label">ลูกค้า</div><div class="pdf-value">{{ $document->party_code }} · {{ $document->party_name }}</div><div>{{ $document->party_address ?: '—' }}</div>@if($document->party_tax_id)<div class="muted">เลขประจำตัวผู้เสียภาษี {{ $document->party_tax_id }}</div>@endif</td><td width="40%" class="invoice-details"><table class="invoice-meta"><tr><td>วันที่เอกสาร</td><td class="right">{{ $document->document_date?->format($dateFormat) ?: '—' }}</td></tr><tr><td>ครบกำหนด</td><td class="right">{{ $document->due_date?->format($dateFormat) ?: '—' }}</td></tr>@if($document->sourceInvoice)<tr><td>อ้างอิงใบแจ้งหนี้</td><td class="right">{{ $document->sourceInvoice->document_number }}</td></tr>@endif</table></td></tr></table>
    <table class="pdf-product"><thead><tr><th width="6%">#</th><th width="40%">สินค้า / รายละเอียด</th><th width="12%">หน่วย</th><th width="12%" class="right">จำนวน</th><th width="14%" class="right">ราคา/หน่วย</th><th width="16%" class="right">จำนวนเงิน</th></tr></thead><tbody>@forelse($document->lines as $line)<tr><td class="center">{{ $line->line_number }}</td><td><div>{{ data_get($line->item_snapshot,'name',$line->description) }}</div><div class="invoice-item-code">{{ data_get($line->item_snapshot,'code') }}</div></td><td class="center">{{ $line->uom?->code ?: '—' }}</td><td class="right">{{ number_format((float)$line->quantity,$decimalPlaces) }}</td><td class="right">{{ number_format((float)$line->unit_price,2) }}</td><td class="right">{{ number_format((float)$line->line_total,2) }}</td></tr>@empty<tr><td colspan="6" class="center">ไม่มีรายการสินค้า</td></tr>@endforelse</tbody></table>
</div>
<!-- invoice-closing -->
<div class="pdf-tax-invoice"><table class="pdf-footer"><tr><td width="55%" class="pdf-footer-payment"><div class="pdf-footer-heading">รายละเอียดเพิ่มเติม</div><p class="muted">{{ $document->document_type === 'CREDIT_NOTE' ? 'เอกสารนี้ใช้ปรับลดหนี้จากใบแจ้งหนี้เดิม' : 'เอกสารนี้ใช้แจ้งยอดที่ลูกค้าต้องชำระ' }}</p>@if($document->description)<p class="pdf-note"><b>หมายเหตุ:</b> {{ $document->description }}</p>@endif</td><td width="45%" class="pdf-footer-total"><table class="pdf-total-summary"><tr><td>ยอดรวม</td><td class="right">{{ number_format((float)$document->subtotal,2) }}</td></tr><tr><td>ส่วนลด</td><td class="right">{{ number_format((float)$document->discount_amount,2) }}</td></tr><tr><td>ภาษีมูลค่าเพิ่ม / VAT</td><td class="right">{{ number_format((float)$document->tax_amount,2) }}</td></tr><tr class="total"><td>รวมทั้งสิ้น</td><td class="right">{{ number_format((float)$document->total_amount,2) }}</td></tr></table></td></tr></table><x-platform::pdf-signatures :document="$document" :slots="[['role' => 'prepared', 'label' => 'ผู้จัดทำ'], ['role' => 'posted', 'label' => 'ผู้อนุมัติ']]" /><p class="pdf-control">{{ $document->document_number }} · {{ $title }}</p></div>
