@extends('Wms::layout')
@section('title', 'สร้าง Transfer | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><p class="eyebrow mb-2">WMS / TRANSFER OUT</p><h1 class="h3 mb-4">สร้างใบโอนสินค้าออก</h1><form id="transfer-form" method="POST" action="{{ route('wms.transfers.store') }}">@csrf
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="row g-3"><div class="col-md-4"><label class="form-label">คลังต้นทาง</label><input class="form-control" value="{{ $sourceWarehouse->name }}" disabled></div><div class="col-md-4"><label class="form-label">คลังปลายทาง</label><select class="form-select" name="destination_warehouse_id" required><option value="">เลือกคลังปลายทาง</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">วันที่เอกสาร</label><input class="form-control" type="date" name="document_date" value="{{ now()->toDateString() }}" required><div class="form-text">ระบบออกเลขตามสาขาและวันที่เอกสาร</div></div><input type="hidden" name="idempotency_key" value="transfer-{{ now()->format('YmdHisv') }}"></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">รายการสินค้า</h2><div class="form-text">ใช้หน่วย Stock ของสินค้าโดยอัตโนมัติ จำนวนฐานจะเท่ากับจำนวนที่กรอกใน MVP</div></div><button class="btn btn-app-soft btn-sm" type="button" id="add-transfer-line"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มรายการ</button></div><div class="table-responsive"><table class="table align-middle transfer-lines-table"><thead><tr><th>สินค้า</th><th>หน่วย Stock</th><th>จำนวน</th><th></th></tr></thead><tbody id="transfer-lines"><tr class="transfer-line"><td><select class="form-select js-item" name="lines[0][item_id]" required></select></td><td><span class="js-stock-uom text-secondary">เลือกสินค้า</span><input type="hidden" class="js-uom-id" name="lines[0][uom_id]" required><input type="hidden" class="js-base-quantity" name="lines[0][planned_base_quantity]" value="1" required></td><td><input class="form-control text-end js-quantity" type="number" min="0.00000001" step="0.00000001" name="lines[0][planned_quantity]" value="1" required></td><td><button class="btn btn-sm btn-outline-danger js-remove-line" type="button" aria-label="ลบรายการ">ลบ</button></td></tr></tbody></table></div><div class="mt-4"><button class="btn btn-dark" type="submit">บันทึกร่าง</button> <a class="btn btn-outline-secondary" href="{{ route('wms.transfers.index') }}">ยกเลิก</a></div></div></div></form></div>
@endsection
@push('scripts')
<script>$(function(){var n=1,itemUrl='{{ route('wms.stock.item-options') }}';function select2($s,url,p){window.erpInitSelect2($s,{theme:'bootstrap-5',placeholder:p,allowClear:true,ajax:{url:url,dataType:'json',delay:250,data:function(x){return{q:x.term||'',page:x.page||1};},processResults:function(x){return x;},cache:true}});}function sync($r){var item=$r.find('.js-item').select2('data')[0],qty=$r.find('.js-quantity').val()||'';$r.find('.js-stock-uom').text(item?.uom_label||'เลือกสินค้า');$r.find('.js-uom-id').val(item?.uom_id||'');$r.find('.js-base-quantity').val(qty);}function init($r){select2($r.find('.js-item'),itemUrl,'ค้นหาสินค้า');$r.find('.js-item').on('select2:select select2:clear',function(){sync($r);});$r.find('.js-quantity').on('input change',function(){ $r.find('.js-base-quantity').val(this.value); });}function reindex(){$('#transfer-lines .transfer-line').each(function(i){$(this).find('[name]').each(function(){this.name=this.name.replace(/lines\[\d+\]/,'lines['+i+']');});});}init($('#transfer-lines .transfer-line'));$('#add-transfer-line').on('click',function(){var r=$('<tr class="transfer-line"><td><select class="form-select js-item" required></select></td><td><span class="js-stock-uom text-secondary">เลือกสินค้า</span><input type="hidden" class="js-uom-id" required><input type="hidden" class="js-base-quantity" value="1" required></td><td><input class="form-control text-end js-quantity" type="number" min="0.00000001" step="0.00000001" value="1" required></td><td><button class="btn btn-sm btn-outline-danger js-remove-line" type="button" aria-label="ลบรายการ">ลบ</button></td></tr>');r.find('.js-item').attr('name','lines['+n+'][item_id]');r.find('.js-uom-id').attr('name','lines['+n+'][uom_id]');r.find('.js-quantity').attr('name','lines['+n+'][planned_quantity]');r.find('.js-base-quantity').attr('name','lines['+n+'][planned_base_quantity]');n++;$('#transfer-lines').append(r);init(r);});$('#transfer-lines').on('click','.js-remove-line',function(){if($('.transfer-line').length>1){$(this).closest('tr').remove();reindex();}});window.erpAjaxForm({form:'#transfer-form',redirect:true});});</script>
@endpush
