<?php
namespace Tests\Unit;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;
final class CrmCustomerCreationContractTest extends TestCase
{
 #[Test] public function crm_customer_creation_is_separately_permissioned_and_installer_versioned():void{$routes=file_get_contents(base_path('app/Modules/Crm/Routes/web.php'));$rbac=file_get_contents(base_path('database/seeders/RbacSeeder.php'));$defaults=file_get_contents(base_path('app/Modules/Installer/Services/SystemDefaultOrchestrator.php'));self::assertStringContainsString('permission:crm.customers.create',$routes);self::assertStringContainsString("[CustomerController::class, 'edit']",$routes);self::assertStringContainsString("[CustomerController::class, 'update']",$routes);self::assertStringContainsString('permission:crm.customers.update',$routes);self::assertStringContainsString('permission:crm.customers.delete',$routes);self::assertStringContainsString("'crm.customers.create' =>",$rbac);self::assertStringContainsString("'crm.customers.update' =>",$rbac);self::assertStringContainsString("'crm.customers.delete' =>",$rbac);self::assertStringContainsString("'core.rbac' => '3.0'",$defaults);}
 #[Test] public function crm_reuses_pos_customer_validation_duplicate_detection_and_transactional_creation():void{$controller=file_get_contents(base_path('app/Modules/Crm/Controllers/CustomerController.php'));$form=file_get_contents(base_path('app/Modules/Crm/Views/customers/form.blade.php'));self::assertStringContainsString('SaveCustomerRequest $request',$controller);self::assertStringContainsString('PosCustomerController $customers',$controller);self::assertStringContainsString('quickOptions($request)',$controller);self::assertStringContainsString('phoneDuplicate((string)$request->input(\'phone\'))',$controller);self::assertStringContainsString("ValidationException::withMessages(['phone'",$controller);self::assertStringContainsString('customers->store($request,$audit,$sequences)',$controller);self::assertStringContainsString('hasBusinessHistory($customer)',$controller);self::assertStringContainsString('customers->destroy($request,$customer,$audit)',$controller);foreach(['sales_intakes','sales_rfqs','sales_quotations','sales_orders','sales_documents','pos_physical_sales','pos_billing_notes','finance_advance_deposits','finance_open_items','finance_settlements'] as $table)self::assertStringContainsString("'{$table}'",$controller);self::assertStringContainsString("'crm.customer.updated'",$controller);self::assertStringContainsString("'crm.customer.deactivated'",$controller);self::assertStringContainsString("'crm.customer.activated'",$controller);self::assertStringContainsString("route('crm.customers.duplicate-options')",$form);self::assertStringContainsString('data.hard_match',$form);self::assertStringContainsString(".replace('__ID__',customer.id)))",$form);self::assertStringContainsString("route('crm.customers.show'",$controller);}
 #[Test] public function customer_form_is_mobile_ready_and_collects_shared_master_fields():void{$form=file_get_contents(base_path('app/Modules/Crm/Views/customers/form.blade.php'));foreach(['name="name"','name="type"','name="tax_id"','name="branch_code"','name="contact_name"','name="phone"','name="email"','name="address"'] as $field)self::assertStringContainsString($field,$form);self::assertStringContainsString('crm-form-actions',$form);self::assertStringContainsString("route('crm.customers.update',\$customer)",$form);self::assertStringContainsString("\$editing?'บันทึกการแก้ไข':'สร้างลูกค้า'",$form);}
}
