<?php
namespace Tests\Unit;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;
final class CrmKanbanPipelineContractTest extends TestCase
{
 #[Test] public function kanban_is_branch_scoped_filtered_and_bounded():void{$controller=file_get_contents(base_path('app/Modules/Crm/Controllers/KanbanController.php'));self::assertStringContainsString("->where('branch_id',\$this->branchId(\$request))",$controller);self::assertStringContainsString("->where('stage',\$stage)",$controller);self::assertStringContainsString("->paginate(10)",$controller);self::assertStringContainsString("'team_id'",$controller);self::assertStringContainsString("'value_min'",$controller);self::assertStringContainsString("'close_month'",$controller);}
 #[Test] public function kanban_uses_ajax_cards_filters_history_and_mobile_horizontal_board():void{$view=file_get_contents(base_path('app/Modules/Crm/Views/opportunities/kanban.blade.php'));$layout=file_get_contents(base_path('app/Modules/Crm/Views/layout.blade.php'));$routes=file_get_contents(base_path('app/Modules/Crm/Routes/web.php'));self::assertStringContainsString("route('crm.opportunities.kanban.data')",$view);self::assertStringContainsString('history.pushState',$view);self::assertStringContainsString('js-load-more',$view);self::assertStringContainsString('repeat(7, minmax(18rem, 1fr))',$layout);self::assertStringContainsString("permission:crm.opportunities.view",$routes);}
 #[Test] public function stage_transition_is_locked_audited_and_requires_close_data():void{$controller=file_get_contents(base_path('app/Modules/Crm/Controllers/KanbanController.php'));$cards=file_get_contents(base_path('app/Modules/Crm/Views/opportunities/_kanban-cards.blade.php'));$view=file_get_contents(base_path('app/Modules/Crm/Views/opportunities/kanban.blade.php'));self::assertStringContainsString('lockForUpdate()',$controller);self::assertStringContainsString("'crm.opportunity.updated'",$controller);self::assertStringContainsString("\$request->input('stage')==='LOST'",$controller);self::assertStringContainsString("\$request->input('stage')==='WON'",$controller);self::assertStringContainsString("'before_or_equal:today'",$controller);self::assertStringContainsString('draggable="true"',$cards);self::assertStringContainsString(".on('drop'",$view);self::assertStringContainsString('js-change-stage',$cards);}
}
