<?php
namespace Tests\Unit;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;
final class CrmNotificationContractTest extends TestCase
{
 #[Test] public function notification_storage_is_reversible_installer_managed_and_idempotent():void{$m=file_get_contents(base_path('database/migrations/2026_09_17_180000_create_crm_notifications.php'));$s=file_get_contents(base_path('app/Modules/Installer/Services/DatabasePreparationService.php'));$service=file_get_contents(base_path('app/Modules/Crm/Services/CrmNotificationService.php'));self::assertStringContainsString("Schema::create('notifications'",$m);self::assertStringContainsString("'idempotency_key'",$m);self::assertStringContainsString("Schema::dropIfExists('crm_notification_deliveries')",$m);self::assertStringContainsString("'crm_notification_deliveries' =>",$s);self::assertStringContainsString('insertOrIgnore',$service);}
 #[Test] public function reminders_and_digests_are_queued_and_scheduled():void{$n=file_get_contents(base_path('app/Modules/Crm/Notifications/CrmWorkNotification.php'));$c=file_get_contents(base_path('routes/console.php'));self::assertStringContainsString('implements ShouldQueue',$n);self::assertStringContainsString("Schedule::command('crm:send-reminders')->everyMinute()",$c);self::assertStringContainsString("Schedule::command('crm:send-daily-digests')->dailyAt",$c);self::assertStringContainsString('withoutOverlapping()->onOneServer()',$c);}
 #[Test] public function users_can_configure_idempotent_due_reminders():void{$m=file_get_contents(base_path('database/migrations/2026_09_17_240000_create_crm_notification_preferences.php'));$c=file_get_contents(base_path('app/Modules/Crm/Controllers/NotificationController.php'));$s=file_get_contents(base_path('app/Modules/Crm/Services/CrmNotificationService.php'));$i=file_get_contents(base_path('app/Modules/Installer/Services/DatabasePreparationService.php'));self::assertStringContainsString("Schema::create('crm_notification_preferences'",$m);self::assertStringContainsString("Schema::dropIfExists('crm_notification_preferences')",$m);self::assertStringContainsString('updatePreference',$c);self::assertStringContainsString('reminder_enabled',$s);self::assertStringContainsString('reminder_minutes',$s);self::assertStringContainsString("'crm_notification_preferences' =>",$i);}
 #[Test] public function inbox_is_user_scoped_ajax_paginated_and_supports_mark_read():void{$c=file_get_contents(base_path('app/Modules/Crm/Controllers/NotificationController.php'));$v=file_get_contents(base_path('app/Modules/Crm/Views/notifications/index.blade.php'));self::assertStringContainsString("->notifications()",$c);self::assertStringContainsString('paginate(12)',$c);self::assertStringContainsString('notifiable_id',$c);self::assertStringContainsString("session()->put('selected_branch_id'",$c);self::assertStringContainsString('$.getJSON(url',$v);}
}
