<?php
namespace Tests\Unit;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;
final class CrmProductInterestContractTest extends TestCase
{
 #[Test] public function product_interest_schema_is_reversible_and_installer_managed():void{$migration=file_get_contents(base_path('database/migrations/2026_09_17_200000_create_crm_product_interests.php'));$schema=file_get_contents(base_path('app/Modules/Installer/Services/DatabasePreparationService.php'));self::assertStringContainsString("Schema::create('crm_product_interests'",$migration);self::assertStringContainsString("Schema::dropIfExists('crm_product_interests')",$migration);self::assertStringContainsString("'crm_product_interests' =>",$schema);self::assertStringContainsString("'crm_product_interests'",$schema);}
 #[Test] public function product_interest_crud_is_scoped_validated_locked_and_audited():void{$controller=file_get_contents(base_path('app/Modules/Crm/Controllers/ProductInterestController.php'));$routes=file_get_contents(base_path('app/Modules/Crm/Routes/web.php'));self::assertStringContainsString('WmsDecimal::rule()',$controller);self::assertStringContainsString("['WON','LOST']",$controller);self::assertStringContainsString("'crm.product-interest.created'",$controller);self::assertStringContainsString('lockForUpdate()',$controller);self::assertStringContainsString('permission:crm.opportunities.update',$routes);self::assertStringContainsString('paginate(8)',$controller);}
 #[Test] public function opportunity_page_uses_ajax_item_search_and_mobile_crud_cards():void{$view=file_get_contents(base_path('app/Modules/Crm/Views/opportunities/show.blade.php'));$cards=file_get_contents(base_path('app/Modules/Crm/Views/opportunities/_product-interests.blade.php'));self::assertStringContainsString("route('crm.opportunities.product-item-options')",$view);self::assertStringContainsString('loadInterests',$view);self::assertStringContainsString('product-interest-pagination',$view);self::assertStringContainsString('badge app-status-info',$view);self::assertStringContainsString('js-send-pos',$view);self::assertStringContainsString('เพิ่มสินค้าอย่างน้อย 1 รายการก่อนสร้างใบรับข้อมูลใน POS',$view);self::assertStringContainsString('js-edit-interest',$cards);self::assertStringContainsString('WmsDecimal::input($interest->quantity)',$cards);self::assertStringContainsString('WmsDecimal::input($interest->target_unit_price)',$cards);self::assertStringContainsString('js-delete-interest',$cards);}
 #[Test] public function commercial_preview_reuses_pos_resolvers_and_branch_stock_projection():void{$service=file_get_contents(base_path('app/Modules/Crm/Services/ProductInterestCommercialService.php'));$controller=file_get_contents(base_path('app/Modules/Crm/Controllers/ProductInterestController.php'));$cards=file_get_contents(base_path('app/Modules/Crm/Views/opportunities/_product-interests.blade.php'));self::assertStringContainsString('PriceListResolver',$service);self::assertStringContainsString('PromotionResolver',$service);self::assertStringContainsString("->where('warehouse.branch_id',\$branchId)",$service);self::assertStringContainsString("->where('warehouse.is_active',true)",$service);self::assertStringContainsString('ProductInterestCommercialService $commercialService',$controller);self::assertStringContainsString('ยังไม่จอง Stock',$cards);self::assertStringContainsString('Stock พร้อมใช้รวมในสาขา',$cards);}
}
