<?php
namespace Tests\Unit;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;
final class CrmProductInterestToPosContractTest extends TestCase
{
 #[Test] public function crm_requires_an_authorized_branch_warehouse_and_bounded_product_interests():void{$controller=file_get_contents(base_path('app/Modules/Crm/Controllers/OpportunityController.php'));$view=file_get_contents(base_path('app/Modules/Crm/Views/opportunities/show.blade.php'));self::assertStringContainsString("\$warehouses->count()===1",$controller);self::assertStringContainsString("\$request->validate(['warehouse_id'",$controller);self::assertStringContainsString("->where('warehouses.branch_id',\$opportunity->branch_id)",$controller);self::assertStringContainsString('$interestCount<1||$interestCount>100',$controller);self::assertStringContainsString('send-pos-modal',$view);self::assertStringContainsString('$warehouses->count()===1',$view);self::assertStringContainsString('js-send-pos-direct',$view);self::assertStringContainsString('name="warehouse_id"',$view);self::assertStringContainsString('opportunity-document-trail-title',$view);self::assertStringContainsString("route('crm.opportunities.documents.open'",$view);self::assertStringContainsString('SalesDocumentTrail::for',$controller);self::assertStringContainsString('finance_settlement_allocation_intents',$controller);self::assertStringContainsString('function openDocument',$controller);}
 #[Test] public function pos_prefills_lines_but_remains_the_document_owner():void{$controller=file_get_contents(base_path('app/Modules/Pos/Controllers/SalesIntakeController.php'));$routes=file_get_contents(base_path('app/Modules/Pos/Routes/web.php'));$show=file_get_contents(base_path('app/Modules/Pos/Views/sales-intakes/show.blade.php'));self::assertStringContainsString("[SalesIntakeController::class, 'openCrm']",$routes);self::assertStringContainsString('function openCrm',$controller);self::assertStringContainsString("where('sales_intake_id',\$salesIntake->id)",$controller);self::assertStringContainsString("route('pos.sales-intakes.open-crm',\$x)",$show);self::assertStringContainsString("productInterests.item.baseUom",$controller);self::assertStringContainsString('PriceListResolver $prices',$controller);self::assertStringContainsString('PromotionResolver $promotions',$controller);self::assertStringContainsString('WmsDecimal::input($interest->quantity)',$controller);self::assertStringContainsString("'crm_opportunity_id'",file_get_contents(base_path('app/Modules/Pos/Requests/SaveSalesIntakeRequest.php')));self::assertStringContainsString("'crm.opportunity.linked-pos'",$controller);}
}
