<?php

namespace App\Modules\Crm\Services;

use App\Models\User;
use App\Modules\Crm\Models\Opportunity;
use App\Modules\Crm\Models\SalesTeam;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

final class SalesForecastService
{
    public function __construct(private readonly OpportunityRiskService $risk){}
    private const OPEN_STAGES=['NEW','CONTACTED','QUALIFIED','PROPOSAL','NEGOTIATION'];

    public function snapshot(Request $request,array $filters):array
    {
        $branchId=(int)$request->attributes->get('selectedBranch')->id;$month=Carbon::createFromFormat('Y-m',$filters['month']??now()->format('Y-m'))->startOfMonth();$from=$month->toDateString();$to=$month->copy()->endOfMonth()->toDateString();$ownerIds=$this->ownerIds($request,$filters['team_id']??null,$filters['owner_id']??null);
        $opportunities=Opportunity::query()->where('branch_id',$branchId)->whereIn('stage',self::OPEN_STAGES)->whereBetween('expected_close_date',[$from,$to])->when($ownerIds!==null,fn($query)=>$query->whereIn('owner_id',$ownerIds));
        $forecast=(clone $opportunities)->selectRaw('owner_id, COUNT(*) opportunity_count, SUM(expected_value) pipeline, SUM(expected_value * probability / 100) forecast')->groupBy('owner_id')->get()->keyBy('owner_id');
        $stages=(clone $opportunities)->selectRaw('stage, COUNT(*) opportunity_count, SUM(expected_value) pipeline, SUM(expected_value * probability / 100) forecast')->groupBy('stage')->get()->keyBy('stage');
        $targets=DB::table('pos_employee_sales_targets')->where('branch_id',$branchId)->where('period_start',$from)->where('period_end',$to)->whereNull('deleted_at')->when($ownerIds!==null,fn($query)=>$query->whereIn('user_id',$ownerIds))->get()->keyBy('user_id');
        $actual=$this->actualSales($branchId,$from,$to,$ownerIds)->keyBy('employee_id');$ids=$forecast->keys()->merge($targets->keys())->merge($actual->keys())->filter()->map(fn($id)=>(int)$id)->unique();$users=User::withTrashed()->whereIn('id',$ids)->orderBy('name')->get(['id','name','employee_code'])->keyBy('id');
        $rows=$ids->map(function($id)use($users,$forecast,$targets,$actual,$month,$from,$to){$user=$users->get($id);if(!$user)return null;$pipeline=(float)($forecast->get($id)?->pipeline??0);$weighted=(float)($forecast->get($id)?->forecast??0);$target=$targets->get($id)?->sales_target;$target=$target===null?null:(float)$target;$sold=(float)($actual->get($id)?->actual_sales??0);return ['user_id'=>$id,'label'=>($user->employee_code?$user->employee_code.' · ':'').$user->name,'opportunity_count'=>(int)($forecast->get($id)?->opportunity_count??0),'pipeline'=>$pipeline,'forecast'=>$weighted,'target'=>$target,'actual'=>$sold,'coverage'=>$target&&$target>0?($pipeline/$target)*100:null,'gap'=>$target===null?null:$target-($sold+$weighted),'opportunity_url'=>route('crm.opportunities.index',['owner_id'=>$id,'date_from'=>$from,'date_to'=>$to])];})->filter()->sortBy('label')->values();
        $page=max(1,(int)($filters['page']??1));$perPage=12;$paginator=new LengthAwarePaginator($rows->forPage($page,$perPage)->values(),$rows->count(),$perPage,$page,['path'=>route('crm.forecast.index'),'query'=>$request->query()]);$branchTarget=$ownerIds===null?DB::table('pos_branch_sales_targets')->where('branch_id',$branchId)->where('period_start',$from)->where('period_end',$to)->whereNull('deleted_at')->value('target_sales_amount'):($targets->isEmpty()?null:$targets->sum('sales_target'));$summary=['pipeline'=>(float)$forecast->sum('pipeline'),'forecast'=>(float)$forecast->sum('forecast'),'actual'=>(float)$actual->sum('actual_sales'),'target'=>$branchTarget===null?null:(float)$branchTarget];$summary['coverage']=$summary['target']&&$summary['target']>0?($summary['pipeline']/$summary['target'])*100:null;$summary['gap']=$summary['target']===null?null:$summary['target']-($summary['actual']+$summary['forecast']);
        $performance=$this->performance($branchId,$from,$to,$ownerIds);$insights=$this->insights($branchId,$from,$to,$ownerIds);$risks=$this->risk->query($branchId,$ownerIds)->with(['party:id,code,name','owner:id,name'])->orderByRaw('expected_close_date IS NULL')->orderBy('expected_close_date')->orderByRaw('next_action_at IS NULL DESC')->orderBy('next_action_at')->limit(12)->get()->map(fn(Opportunity $opportunity)=>['id'=>$opportunity->id,'title'=>$opportunity->title,'customer'=>collect([$opportunity->party?->code,$opportunity->party?->name])->filter()->join(' · '),'owner'=>$opportunity->owner?->name,'expected_value'=>(float)$opportunity->expected_value,'expected_close_date'=>$opportunity->expected_close_date?->format('d/m/Y'),'next_action_at'=>$opportunity->next_action_at?->format('d/m/Y H:i'),'reasons'=>$this->risk->reasons($opportunity),'url'=>route('crm.opportunities.show',$opportunity)])->all();
        return compact('summary','stages','paginator','month','performance','insights','risks');
    }

    public function teams(Request $request)
    {
        return SalesTeam::query()->where('branch_id',(int)$request->attributes->get('selectedBranch')->id)->where('is_active',true)->when(!$request->user()->hasPermission('crm.team-work.view-all'),fn($query)=>$query->where(fn($query)=>$query->where('manager_id',$request->user()->id)->orWhereHas('members',fn($query)=>$query->where('users.id',$request->user()->id))))->orderBy('name')->get(['id','name']);
    }

    private function ownerIds(Request $request,mixed $teamId,mixed $ownerId):?array
    {
        $teams=$this->teams($request);if($teamId){$team=$teams->firstWhere('id',(int)$teamId);if(!$team)throw ValidationException::withMessages(['team_id'=>'ไม่มีสิทธิ์ดู Forecast ของทีมนี้']);$ids=$team->members()->pluck('users.id')->map(fn($id)=>(int)$id)->all();}elseif(!$request->user()->hasPermission('crm.team-work.view-all')){$ids=$teams->flatMap(fn($team)=>$team->members()->pluck('users.id'))->push($request->user()->id)->map(fn($id)=>(int)$id)->unique()->all();}else{$ids=null;}if($ownerId){$ownerId=(int)$ownerId;if($ids!==null&&!in_array($ownerId,$ids,true))throw ValidationException::withMessages(['owner_id'=>'ไม่มีสิทธิ์ดู Forecast ของพนักงานนี้']);return [$ownerId];}return $ids;
    }

    private function performance(int $branchId,string $from,string $to,?array $ownerIds):array
    {
        $scope=Opportunity::query()->where('branch_id',$branchId)->when($ownerIds!==null,fn($query)=>$query->whereIn('owner_id',$ownerIds));$created=(clone $scope)->whereBetween('created_at',[$from.' 00:00:00',$to.' 23:59:59']);$createdCount=(clone $created)->count();$won=(clone $scope)->whereBetween('won_at',[$from.' 00:00:00',$to.' 23:59:59']);$lost=(clone $scope)->whereBetween('lost_at',[$from.' 00:00:00',$to.' 23:59:59']);$wonCount=(clone $won)->count();$lostCount=(clone $lost)->count();$funnel=[];$stages=['NEW','CONTACTED','QUALIFIED','PROPOSAL','NEGOTIATION','WON'];foreach(array_slice($stages,0,5) as $index=>$stage){$later=array_slice($stages,$index);$count=$stage==='NEW'?$createdCount:(clone $created)->where(fn($query)=>$query->whereIn('stage',$later)->orWhereExists(fn($audit)=>$audit->selectRaw('1')->from('audit_logs')->whereColumn('audit_logs.subject_id','crm_opportunities.id')->where('audit_logs.subject_type',Opportunity::class)->whereIn('audit_logs.action',['crm.opportunity.updated','crm.opportunity.won-from-pos'])->whereIn(DB::raw("JSON_UNQUOTE(JSON_EXTRACT(audit_logs.new_values, '$.stage'))"),$later)))->count();$previous=$funnel[$index-1]['reached']??null;$funnel[]=['stage'=>$stage,'reached'=>$count,'conversion'=>$previous?($count/$previous)*100:null];}
        $events=DB::table('crm_opportunities as opportunity')->where('opportunity.branch_id',$branchId)->when($ownerIds!==null,fn($query)=>$query->whereIn('opportunity.owner_id',$ownerIds))->selectRaw("opportunity.id opportunity_id, 'NEW' stage, opportunity.created_at event_at")->unionAll(DB::table('audit_logs as audit')->join('crm_opportunities as opportunity','opportunity.id','=','audit.subject_id')->where('opportunity.branch_id',$branchId)->where('audit.subject_type',Opportunity::class)->whereIn('audit.action',['crm.opportunity.updated','crm.opportunity.won-from-pos'])->whereNotNull(DB::raw("JSON_EXTRACT(audit.new_values, '$.stage')"))->whereRaw("JSON_UNQUOTE(JSON_EXTRACT(audit.old_values, '$.stage')) <> JSON_UNQUOTE(JSON_EXTRACT(audit.new_values, '$.stage'))")->when($ownerIds!==null,fn($query)=>$query->whereIn('opportunity.owner_id',$ownerIds))->selectRaw("opportunity.id opportunity_id, JSON_UNQUOTE(JSON_EXTRACT(audit.new_values, '$.stage')) stage, audit.created_at event_at"));$transitions=DB::query()->fromSub(clone $events,'event_a')->joinSub(clone $events,'event_b',fn($join)=>$join->on('event_b.opportunity_id','=','event_a.opportunity_id')->whereColumn('event_b.event_at','>','event_a.event_at'))->selectRaw('event_a.opportunity_id, event_a.stage, event_a.event_at, MIN(event_b.event_at) next_at')->groupBy('event_a.opportunity_id','event_a.stage','event_a.event_at');$durations=DB::query()->fromSub($transitions,'transitions')->whereBetween('next_at',[$from.' 00:00:00',$to.' 23:59:59'])->whereIn('stage',array_slice($stages,0,5))->selectRaw('stage, AVG(TIMESTAMPDIFF(HOUR,event_at,next_at))/24 average_days, COUNT(*) transition_count')->groupBy('stage')->get()->keyBy('stage');
        return ['created'=>$createdCount,'won'=>$wonCount,'lost'=>$lostCount,'win_rate'=>($wonCount+$lostCount)>0?$wonCount/($wonCount+$lostCount)*100:null,'average_cycle_days'=>($average=(clone $won)->selectRaw('AVG(TIMESTAMPDIFF(HOUR,created_at,won_at))/24 average_days')->value('average_days'))===null?null:(float)$average,'funnel'=>$funnel,'durations'=>$durations->map(fn($row)=>['stage'=>$row->stage,'average_days'=>(float)$row->average_days,'transition_count'=>(int)$row->transition_count])->values()->all()];
    }

    private function insights(int $branchId,string $from,string $to,?array $ownerIds):array
    {
        $scope=fn($query)=>$query->where('opportunity.branch_id',$branchId)->whereNull('opportunity.deleted_at')->when($ownerIds!==null,fn($query)=>$query->whereIn('opportunity.owner_id',$ownerIds));$created=fn($query)=>$scope($query)->whereBetween('opportunity.created_at',[$from.' 00:00:00',$to.' 23:59:59']);$sources=$created(DB::table('crm_opportunities as opportunity'))->selectRaw("COALESCE(NULLIF(TRIM(opportunity.source),''),'ไม่ระบุ') label, COUNT(*) opportunity_count, SUM(opportunity.expected_value) pipeline, SUM(CASE WHEN opportunity.stage='WON' THEN 1 ELSE 0 END) won_count")->groupBy('label')->orderByDesc('opportunity_count')->limit(8)->get()->map(fn($row)=>['label'=>$row->label,'opportunity_count'=>(int)$row->opportunity_count,'pipeline'=>(float)$row->pipeline,'won_count'=>(int)$row->won_count])->all();$products=$created(DB::table('crm_product_interests as interest')->join('crm_opportunities as opportunity','opportunity.id','=','interest.opportunity_id')->join('wms_items as item','item.id','=','interest.item_id'))->selectRaw("item.id item_id, CONCAT(item.code,' · ',item.name) label, COUNT(DISTINCT opportunity.id) opportunity_count, COUNT(*) interest_count, SUM(COALESCE(interest.budget_amount,0)) budget")->groupBy('item.id','item.code','item.name')->orderByDesc('opportunity_count')->orderByDesc('budget')->limit(8)->get()->map(fn($row)=>['item_id'=>(int)$row->item_id,'label'=>$row->label,'opportunity_count'=>(int)$row->opportunity_count,'interest_count'=>(int)$row->interest_count,'budget'=>(float)$row->budget])->all();$lost=$scope(DB::table('crm_opportunities as opportunity'))->whereBetween('opportunity.lost_at',[$from.' 00:00:00',$to.' 23:59:59'])->selectRaw("COALESCE(NULLIF(TRIM(opportunity.lost_reason),''),'ไม่ระบุเหตุผล') label, COUNT(*) opportunity_count, SUM(opportunity.expected_value) lost_value")->groupBy('label')->orderByDesc('opportunity_count')->orderByDesc('lost_value')->limit(8)->get()->map(fn($row)=>['label'=>$row->label,'opportunity_count'=>(int)$row->opportunity_count,'lost_value'=>(float)$row->lost_value])->all();return compact('sources','products','lost');
    }

    private function actualSales(int $branchId,string $from,string $to,?array $ownerIds)
    {
        $returned=DB::table('pos_sales_return_lines as return_lines')->join('pos_sales_returns as returns','returns.id','=','return_lines.sales_return_id')->where('returns.status','POSTED')->selectRaw('return_lines.physical_sale_line_id, SUM(return_lines.quantity) returned_quantity')->groupBy('return_lines.physical_sale_line_id');$net='GREATEST(lines.quantity - COALESCE(returned.returned_quantity,0),0)';$ratio="CASE WHEN lines.quantity=0 THEN 0 ELSE {$net}/lines.quantity END";$employee='COALESCE(intake_direct.prepared_by,intake_quote.prepared_by,intake_quote_rfq.prepared_by,intake_order_rfq.prepared_by,sales.created_by)';
        return DB::table('pos_physical_sale_lines as lines')->join('pos_physical_sales as sales','sales.id','=','lines.physical_sale_id')->leftJoin('sales_orders as orders',fn($join)=>$join->on('orders.id','=','sales.source_id')->where('sales.source_type','SALES_ORDER'))->leftJoin('sales_intakes as intake_direct','intake_direct.id','=','orders.source_sales_intake_id')->leftJoin('sales_quotations as quotations','quotations.id','=','orders.sales_quotation_id')->leftJoin('sales_intakes as intake_quote','intake_quote.id','=','quotations.source_sales_intake_id')->leftJoin('sales_rfqs as quote_rfqs','quote_rfqs.id','=','quotations.sales_rfq_id')->leftJoin('sales_intakes as intake_quote_rfq','intake_quote_rfq.id','=','quote_rfqs.source_sales_intake_id')->leftJoin('sales_rfqs as order_rfqs','order_rfqs.id','=','orders.sales_rfq_id')->leftJoin('sales_intakes as intake_order_rfq','intake_order_rfq.id','=','order_rfqs.source_sales_intake_id')->leftJoinSub($returned,'returned','returned.physical_sale_line_id','=','lines.id')->where('sales.branch_id',$branchId)->where('sales.status','POSTED')->whereBetween('sales.posting_date',[$from,$to])->when($ownerIds!==null,fn($query)=>$query->whereIn(DB::raw($employee),$ownerIds))->selectRaw("{$employee} employee_id, SUM(lines.tax_base * ({$ratio})) actual_sales")->groupByRaw($employee)->get();
    }
}
