@extends('Finance::layout')

@section('title', $voucher->document_number.' | เงินสดย่อย')

@section('content')
    @php($labels=['DRAFT'=>'ร่าง','SUBMITTED'=>'รออนุมัติ','APPROVED'=>'อนุมัติแล้ว','POSTED'=>'ลงบัญชีแล้ว','REVERSED'=>'ยกเลิกรายการแล้ว','VOID'=>'ยกเลิก'])
    @php($classes=['DRAFT'=>'app-status-neutral','SUBMITTED'=>'app-status-info','APPROVED'=>'app-status-info','POSTED'=>'app-status-success','REVERSED'=>'app-status-danger','VOID'=>'app-status-danger'])
    <div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><p class="eyebrow mb-2">FINANCE / PETTY CASH</p><h1 class="h3 mb-1">{{ $voucher->document_number }}</h1><span class="badge {{ $classes[$voucher->status] ?? 'app-status-neutral' }}">{{ $labels[$voucher->status] ?? $voucher->status }}</span></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="{{ route('finance.petty-cash.index') }}">กลับ</a>
        @if($voucher->journalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-app-soft" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $voucher->journalEntry) }}"><i class="bx bx-book-open me-1" aria-hidden="true"></i>ดู GL</button>@endif
        @if($voucher->reversalJournalEntry && auth()->user()->hasPermission('accounting.journal-entries.view'))<button class="btn btn-outline-danger" type="button" data-journal-preview-url="{{ route('accounting.journal-preview.show', $voucher->reversalJournalEntry) }}"><i class="bx bx-undo me-1" aria-hidden="true"></i>ดู GL ยกเลิก</button>@endif
        @if($voucher->status === 'DRAFT' && auth()->user()->hasPermission('finance.petty-cash.update'))<a class="btn btn-outline-dark" href="{{ route('finance.petty-cash.edit', $voucher) }}">แก้ไข</a> <form method="POST" action="{{ route('finance.petty-cash.destroy', $voucher) }}" class="d-inline" onsubmit="event.preventDefault(); var form=this; Swal.fire({icon:'warning',title:'ลบเอกสาร Draft?',text:'เอกสารจะถูกลบออกจากรายการ',showCancelButton:true,confirmButtonText:'ลบเอกสาร',cancelButtonText:'ยกเลิก',confirmButtonColor:'#dc3545'}).then(function(result){if(!result.isConfirmed)return; $.ajax({url:form.action,method:'DELETE',data:{_token:$('meta[name=csrf-token]').attr('content')},headers:{Accept:'application/json'}}).done(function(response){Swal.fire({icon:'success',text:response.msg||'ลบเอกสารแล้ว'}).then(function(){window.location.href=response.redirect;});}).fail(function(xhr){Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ไม่สามารถลบเอกสารได้'});});});">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">ลบ Draft</button></form>@endif
        @if($voucher->status === 'DRAFT' && auth()->user()->hasPermission('finance.petty-cash.submit'))<button class="btn btn-dark js-petty-cash-action" data-url="{{ route('finance.petty-cash.submit', $voucher) }}" data-method="PUT" data-confirm="ส่งเอกสารเพื่ออนุมัติ?">ส่งอนุมัติ</button>@endif
        @if($voucher->status === 'SUBMITTED' && auth()->user()->hasPermission('finance.petty-cash.approve'))<button class="btn btn-dark js-petty-cash-action" data-url="{{ route('finance.petty-cash.approve', $voucher) }}" data-method="PUT" data-confirm="อนุมัติเอกสารนี้?">อนุมัติ</button><button class="btn btn-outline-danger js-petty-cash-reason" data-url="{{ route('finance.petty-cash.reject', $voucher) }}" data-title="ไม่อนุมัติเอกสาร">ไม่อนุมัติ</button>@endif
        @if($voucher->status === 'APPROVED' && auth()->user()->hasPermission('finance.petty-cash.post'))<button class="btn btn-dark js-petty-cash-action" data-url="{{ route('finance.petty-cash.post', $voucher) }}" data-method="POST" data-confirm="ลงบัญชีใบสำคัญเงินสดย่อย?">ลงบัญชี</button>@endif
        @if(in_array($voucher->status, ['SUBMITTED', 'APPROVED'], true) && auth()->user()->hasPermission('finance.petty-cash.void'))<button class="btn btn-outline-danger js-petty-cash-reason" data-url="{{ route('finance.petty-cash.void', $voucher) }}" data-title="ยกเลิกเอกสาร">ยกเลิก</button>@endif
        @if($voucher->status === 'POSTED' && auth()->user()->hasPermission('finance.petty-cash.reverse'))<button class="btn btn-outline-danger js-petty-cash-reason" data-url="{{ route('finance.petty-cash.reverse', $voucher) }}" data-title="ยกเลิกรายการ" data-reversal="1">ยกเลิกรายการ</button>@endif
    </div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-3"><div class="small text-secondary">วันที่เอกสาร</div>{{ $voucher->document_date?->format($dateFormat ?? 'd/m/Y') }}</div><div class="col-md-3"><div class="small text-secondary">วงเงินสดย่อย</div><strong>{{ $voucher->fund?->name ?: '—' }}</strong><div class="small text-secondary">{{ $voucher->fund?->cashBankAccount?->code ?? 'ไม่พบบัญชี' }} · {{ $voucher->fund?->cashBankAccount?->name ?? '' }}</div></div><div class="col-md-3"><div class="small text-secondary">ผู้รับเงิน</div><div class="small text-secondary">{{ ['EMPLOYEE' => 'Employee', 'SUPPLIER' => 'Supplier', 'OTHER' => 'อื่น ๆ'][$voucher->payee_type ?? 'OTHER'] ?? 'อื่น ๆ' }}</div>{{ $voucher->payee_name ?: '—' }}</div><div class="col-md-3"><div class="small text-secondary">ยอดรวม</div><strong>{{ number_format((float) $voucher->total_amount,2) }}</strong></div><div class="col-12"><div class="small text-secondary">รายละเอียด</div>{{ $voucher->description ?: '—' }}</div>
            @if($voucher->journalEntry)<div class="col-md-6"><div class="small text-secondary">Journal</div>{{ $voucher->journalEntry->entry_number ?? $voucher->journal_entry_id }}</div>@endif
            @if($voucher->reversalJournalEntry)<div class="col-md-6"><div class="small text-secondary">Journal ยกเลิกรายการ</div>{{ $voucher->reversalJournalEntry->entry_number ?? $voucher->reversal_journal_entry_id }}</div>@endif
        </div></div></div>
        @php($netAmount = (float) $voucher->net_amount > 0 ? (float) $voucher->net_amount : (float) $voucher->total_amount)
        <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">รายการค่าใช้จ่าย</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>#</th><th>หมวดค่าใช้จ่าย</th><th>บัญชี GL</th><th>รายละเอียด</th><th>เลขใบเสร็จ</th><th>VAT</th><th>WHT</th><th class="text-end">ฐานค่าใช้จ่าย</th></tr></thead><tbody>@forelse($voucher->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->expense_category_code }} · {{ $line->expense_category_name }}</td><td>{{ $line->expense_account_code }} · {{ $line->expense_account_name }}</td><td>{{ $line->description ?: '—' }}</td><td>{{ $line->receipt_reference ?: '—' }}</td><td>{{ $line->tax_code_code ?: '—' }}<div class="small text-secondary">{{ $line->tax_amount ? number_format((float) $line->tax_amount, 2) : '0.00' }}</div></td><td>{{ $line->withholding_tax_code ?: '—' }}<div class="small text-secondary">{{ $line->withholding_amount ? number_format((float) $line->withholding_amount, 2) : '0.00' }}</div></td><td class="text-end">{{ number_format((float) $line->amount,2) }}</td></tr>@empty<tr><td colspan="8" class="text-center text-secondary">ยังไม่มีรายการ</td></tr>@endforelse</tbody><tfoot><tr><th colspan="7" class="text-end">ฐานค่าใช้จ่าย</th><th class="text-end">{{ number_format((float) $voucher->total_amount - (float) $voucher->tax_amount, 2) }}</th></tr><tr><th colspan="7" class="text-end">VAT</th><th class="text-end">{{ number_format((float) $voucher->tax_amount, 2) }}</th></tr><tr><th colspan="7" class="text-end">WHT</th><th class="text-end">{{ number_format((float) $voucher->withholding_amount, 2) }}</th></tr><tr><th colspan="7" class="text-end">ยอดจ่ายสุทธิ</th><th class="text-end">{{ number_format($netAmount, 2) }}</th></tr></tfoot></table></div></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history ?? [] as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{ $event->created_at?->format('d/m/Y H:i') }}</div><div><strong>{{ $event->action }}</strong><div class="small text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">รายละเอียด:</span> {{ $event->reason }}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติเอกสาร</p>@endforelse</div></div>
        @include('Finance::partials.petty-cash-attachments', ['subject' => $voucher, 'subjectType' => 'PETTY_CASH_VOUCHER'])
    </div>
@endsection

@push('scripts')
<script>
$(function(){function send($button,data){if($button.data('submitting'))return;$button.data('submitting',true).prop('disabled',true);$.ajax({url:$button.data('url'),method:$button.data('method')||'PUT',data:data||{},headers:{Accept:'application/json','X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}}).done(function(r){Swal.fire({icon:'success',text:r.msg||'บันทึกเรียบร้อย'}).then(function(){window.location.reload();});}).fail(function(x){var r=x.responseJSON||{};Swal.fire({icon:'error',text:r.message||r.errors?.reason?.[0]||'ไม่สามารถดำเนินการได้'});}).always(function(){$button.data('submitting',false).prop('disabled',false);});}$('.js-petty-cash-action').on('click',function(){var $b=$(this);Swal.fire({icon:'question',text:$b.data('confirm'),showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ย้อนกลับ'}).then(function(r){if(r.isConfirmed)send($b);});});$('.js-petty-cash-reason').on('click',function(){var $b=$(this);Swal.fire({title:$b.data('title'),input:'textarea',inputLabel:'เหตุผล',inputAttributes:{maxlength:500},showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ย้อนกลับ',preConfirm:function(reason){reason=$.trim(reason||'');if(!reason){Swal.showValidationMessage('กรุณาระบุเหตุผล');return false;}return reason;}}).then(function(r){if(!r.isConfirmed)return;var data={reason:r.value};if($b.data('reversal'))data.reversal_date=new Date().toISOString().slice(0,10);send($b,data);});});});
</script>
@endpush
