@extends('Wms::layout')
@section('title', 'ใบรับคืน '.$document->document_number.' | WMS')
@php
    $statusLabels = ['DRAFT' => 'ร่าง', 'APPROVED' => 'อนุมัติแล้ว', 'POSTED' => 'ลง Stock แล้ว', 'VOID' => 'ยกเลิกเอกสาร', 'REVERSED' => 'ยกเลิกเอกสารแล้ว'];
    $statusClasses = ['DRAFT' => 'neutral', 'APPROVED' => 'info', 'POSTED' => 'success', 'VOID' => 'danger', 'REVERSED' => 'warning'];
    $issueTypeLabels = ['GENERAL' => 'เบิกทั่วไป', 'PRODUCTION' => 'เบิกเข้าผลิต', 'PROJECT' => 'เบิกโครงการ'];
    $sourceIssue = $document->issue;
    $sourceIssueUrl = $sourceIssue ? ($sourceIssue->issue_type === 'PRODUCTION' ? route('wms.production.material-issues.show', $sourceIssue) : route('wms.issues.show', $sourceIssue)) : null;
    $canApprove = auth()->user()->hasPermission('wms.issue-returns.approve');
    $canPost = auth()->user()->hasPermission('wms.issue-returns.post');
    $canDelete = auth()->user()->hasPermission('wms.issue-returns.delete');
    $nextStep = match ($document->status) {
        'DRAFT' => 'ตรวจสอบรายการ แล้วกด “อนุมัติ” เพื่อส่งต่อขั้นตอนลง Stock',
        'APPROVED' => 'เอกสารพร้อมลง Stock แล้ว กด “ลง Stock” เพื่อบันทึกผลกระทบยอดคงเหลือ',
        'POSTED' => 'เอกสารลง Stock แล้ว หากพบข้อผิดพลาด ให้ยกเลิกเอกสารเพื่อสร้างรายการย้อนกลับ',
        default => 'เอกสารนี้ไม่มีขั้นตอนที่ต้องดำเนินการต่อ',
    };
@endphp
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">WMS / ISSUE RETURN</p><h1 class="h3 mb-2">{{ $document->document_number }}</h1><span class="badge app-status-{{ $statusClasses[$document->status] ?? 'neutral' }}">{{ $statusLabels[$document->status] ?? $document->status }}</span></div>
        <div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="{{ route('wms.issue-returns.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a>@if($document->status==='DRAFT' && $canApprove)<button class="btn btn-app-primary js-act" data-action="approve"><i class="bx bx-check me-1" aria-hidden="true"></i>อนุมัติ</button>@endif @if($document->status==='APPROVED' && $canPost)<button class="btn btn-app-primary js-act" data-action="post"><i class="bx bx-package me-1" aria-hidden="true"></i>ลง Stock</button>@endif @if(in_array($document->status, ['DRAFT', 'APPROVED'], true) && $canApprove)<button class="btn btn-app-danger js-cancel" type="button" data-url="{{ route('wms.issue-returns.cancel', $document) }}"><i class="bx bx-x-circle me-1" aria-hidden="true"></i>ยกเลิกเอกสาร</button>@endif @if($document->status==='POSTED' && $canPost)<button class="btn btn-app-danger js-reverse" type="button" data-url="{{ route('wms.issue-returns.reverse', $document) }}"><i class="bx bx-undo me-1" aria-hidden="true"></i>ยกเลิกเอกสาร</button>@endif @if($document->status==='DRAFT' && $canDelete)<button class="btn btn-app-danger js-delete" type="button" data-url="{{ route('wms.issue-returns.destroy', $document) }}"><i class="bx bx-trash me-1" aria-hidden="true"></i>ลบร่าง</button>@endif</div>
    </div>
    <div class="alert alert-info border-0 d-flex gap-2 align-items-start mb-4"><i class="bx bx-info-circle fs-5" aria-hidden="true"></i><div><strong>ขั้นตอนถัดไป</strong><div>{{ $nextStep }}</div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-3"><small class="text-secondary">วันที่เอกสาร</small><div class="fw-semibold">{{ $document->document_date?->format($dateFormat) ?: '-' }}</div></div><div class="col-md-3"><small class="text-secondary">ใบเบิกต้นทาง</small><div class="fw-semibold">@if($sourceIssueUrl)<a href="{{ $sourceIssueUrl }}" class="link-primary">{{ $sourceIssue->document_number }}<i class="bx bx-link-external ms-1" aria-hidden="true"></i></a>@else-@endif</div></div><div class="col-md-3"><small class="text-secondary">สถานะใบเบิกต้นทาง</small><div class="fw-semibold">{{ $sourceIssue ? ($statusLabels[$sourceIssue->status] ?? $sourceIssue->status) : '-' }}</div></div><div class="col-md-3"><small class="text-secondary">ประเภทการเบิก</small><div class="fw-semibold">{{ $sourceIssue ? ($issueTypeLabels[$sourceIssue->issue_type] ?? $sourceIssue->issue_type) : '-' }}</div></div><div class="col-12"><small class="text-secondary">เหตุผลใบรับคืน</small><div class="fw-semibold">{{ $document->reason ?: '-' }}</div></div></div></div></div>
    @include('Wms::partials.document-photos', ['photoTitle' => 'รูปหลักฐานการรับคืนสินค้า', 'photoStoreRoute' => 'wms.issue-returns.photos.store', 'photoPreviewRoute' => 'wms.issue-returns.photos.preview', 'photoUploadPermission' => 'wms.issue-returns.create'])
    @if($sourceIssue)<div class="card border-primary-subtle shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">รายละเอียดใบเบิกต้นทาง</h2><a class="btn btn-sm btn-app-soft" href="{{ $sourceIssueUrl }}"><i class="bx bx-file-find me-1" aria-hidden="true"></i>ดูใบเบิกต้นทาง</a></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>#</th><th>สินค้า</th><th>หน่วย</th><th class="text-end">จำนวนเบิก</th></tr></thead><tbody>@foreach($sourceIssue->lines as $sourceLine)<tr><td>{{ $sourceLine->line_number }}</td><td>{{ $sourceLine->item?->code }} · {{ $sourceLine->item?->name }}</td><td>{{ $sourceLine->uom?->code ?: '-' }}</td><td class="text-end">{{ \App\Modules\Wms\Support\WmsDecimal::format($sourceLine->quantity) }}</td></tr>@endforeach</tbody></table></div></div></div>@endif
    <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3">รายการรับคืน</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>สินค้า</th><th>หน่วย</th><th class="text-end">จำนวน</th><th>Movement</th><th>ต้นทุน</th></tr></thead><tbody>@forelse($document->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->issueLine?->item?->code }} · {{ $line->issueLine?->item?->name }}</td><td>{{ $line->issueLine?->uom?->code }}</td><td class="text-end">{{ \App\Modules\Wms\Support\WmsDecimal::format($line->quantity) }}</td><td>{{ $line->movement?->id ? '#'.$line->movement->id : '-' }}</td><td class="text-end">{{ $line->allocation ? \App\Modules\Wms\Support\WmsDecimal::format($line->allocation->value) : '-' }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary">ไม่พบรายการรับคืน</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history as $h)<div class="border-bottom py-2"><strong>{{ $h->action }}</strong><small class="text-secondary ms-2">{{ $h->created_at?->format($dateFormat.' H:i') }} · {{ $h->user?->name ?? '-' }}</small></div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection
@push('scripts')<script>$(function(){$('.js-cancel').on('click',function(){const button=$(this);Swal.fire({icon:'warning',title:'ยกเลิกเอกสารรับคืน?',input:'textarea',inputLabel:'เหตุผลการยกเลิกเอกสาร',inputPlaceholder:'ระบุเหตุผลอย่างน้อย 5 ตัวอักษร',showCancelButton:true,confirmButtonText:'ยืนยันยกเลิกเอกสาร',cancelButtonText:'กลับ',inputValidator:value=>!value||value.trim().length<5?'กรุณาระบุเหตุผลอย่างน้อย 5 ตัวอักษร':undefined}).then(result=>{if(!result.isConfirmed)return;button.prop('disabled',true);$.post(button.data('url'),{_token:$('meta[name=csrf-token]').attr('content'),reason:result.value}).done(response=>Swal.fire({icon:'success',text:response.msg,timer:1200,showConfirmButton:false}).then(()=>{window.location.href=response.redirect;})).fail(xhr=>{button.prop('disabled',false);Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ยกเลิกเอกสารไม่สำเร็จ'});});});});$('.js-reverse').on('click',function(){const button=$(this);Swal.fire({icon:'warning',title:'ยกเลิกเอกสารรับคืน?',text:'ระบบจะสร้างรายการย้อนกลับเพื่อแก้ผลกระทบ Stock',input:'textarea',inputLabel:'เหตุผลการยกเลิกเอกสาร',inputPlaceholder:'ระบุเหตุผลอย่างน้อย 10 ตัวอักษร',showCancelButton:true,confirmButtonText:'ยืนยันยกเลิกเอกสาร',cancelButtonText:'กลับ',inputValidator:value=>!value||value.trim().length<10?'กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร':undefined}).then(result=>{if(!result.isConfirmed)return;button.prop('disabled',true);$.post(button.data('url'),{_token:$('meta[name=csrf-token]').attr('content'),reason:result.value}).done(response=>Swal.fire({icon:'success',text:response.msg,timer:1200,showConfirmButton:false}).then(()=>{window.location.href=response.redirect;})).fail(xhr=>{button.prop('disabled',false);Swal.fire({icon:'error',text:xhr.responseJSON?.message||'ยกเลิกเอกสารไม่สำเร็จ'});});});});window.erpAjaxDelete({button:'.js-delete',title:'ลบร่างใบรับคืน?',text:'เอกสารร่างจะถูกลบและไม่สามารถกู้คืนได้',confirmButtonText:'ลบร่าง',cancelButtonText:'กลับ'});});</script>@endpush
@push('scripts')<script>$(function(){$('.js-act').on('click',function(){const a=$(this).data('action');Swal.fire({icon:'warning',title:a==='approve'?'อนุมัติใบรับคืน?':'ลง Stock ใบรับคืน?',showCancelButton:true,confirmButtonText:'ยืนยัน',cancelButtonText:'ยกเลิก'}).then(x=>{if(!x.isConfirmed)return;$.post('{{ route('wms.issue-returns.show',$document) }}/'+a,{_token:$('meta[name=csrf-token]').attr('content')}).done(()=>location.reload()).fail(e=>Swal.fire({icon:'error',text:e.responseJSON?.message||'ดำเนินการไม่สำเร็จ'}));});});});</script>@endpush
