@extends($moduleRoutePrefix === 'purchasing' ? 'Purchasing::layout' : 'Wms::layout')
@section('title','Purchase Order '.$order->document_number)
@section('content')
@php($moduleRoutePrefix=$moduleRoutePrefix??'wms')
@php($statusLabels=['DRAFT'=>'ร่าง','APPROVED'=>'อนุมัติแล้ว','VOID'=>'ยกเลิก'])
@php($wmsDecimal = \App\Modules\Wms\Support\WmsDecimal::class)
@php($statusClass=['DRAFT'=>'neutral','APPROVED'=>'success','VOID'=>'danger'])
<div class="container-fluid px-3 px-lg-4 py-4">
@if(auth()->user()->hasPermission($moduleRoutePrefix.'.purchase-orders.print'))<div class="mb-3"><a class="btn btn-sm btn-app-soft" target="_blank" href="{{route($moduleRoutePrefix.'.purchase-orders.pdf',$order)}}">พิมพ์ PDF</a></div>@endif
<div class="d-flex justify-content-between mb-4"><div><p class="eyebrow mb-2">PURCHASING / PO</p><h1 class="h3">{{$order->document_number}}</h1><p class="text-secondary mb-0">{{$order->supplier_code}} · {{$order->supplier_name}} · วันที่เอกสาร {{$order->document_date->format($dateFormat)}}</p>@if($order->purchaseRequisition)<p class="mb-0 mt-2">อ้างอิง PR: <a href="{{route($moduleRoutePrefix.'.purchase-requisitions.edit',$order->purchaseRequisition)}}">{{$order->purchaseRequisition->document_number}}</a></p>@endif</div><div class="text-end"><span class="badge app-status-{{$statusClass[$order->status]??'neutral'}}">{{$statusLabels[$order->status]??$order->status}}</span>@if($order->status==='DRAFT' && auth()->user()->hasPermission($moduleRoutePrefix.'.purchase-orders.update'))<div class="mt-3"><a class="btn btn-sm btn-outline-dark" href="{{route($moduleRoutePrefix.'.purchase-orders.edit',$order)}}">แก้ไข PO / กรอกราคา</a></div>@endif @if($order->status==='DRAFT' && auth()->user()->hasPermission($moduleRoutePrefix.'.purchase-orders.delete'))<button type="button" class="btn btn-sm btn-outline-danger mt-3 js-delete-document" data-url="{{route($moduleRoutePrefix.'.purchase-orders.destroy',$order)}}">ลบ PO</button>@endif</div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-4"><small class="text-secondary d-block">Supplier</small><strong>{{$order->supplier_code}} · {{$order->supplier_name}}</strong></div><div class="col-md-4"><small class="text-secondary d-block">เงื่อนไขชำระเงิน</small><strong>{{$order->paymentTerm?->code ? $order->paymentTerm->code.' · '.$order->paymentTerm->name : 'ไม่กำหนด'}}</strong></div><div class="col-md-2"><small class="text-secondary d-block">คาดรับสินค้า</small><strong>{{$order->expected_date?->format($dateFormat) ?? '—'}}</strong></div><div class="col-md-2"><small class="text-secondary d-block">ประเภท</small><strong>{{$order->purchase_requisition_id ? 'สร้างจาก PR' : 'สร้างโดยตรง'}}</strong></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="table-responsive"><table class="table"><thead><tr><th>#</th><th>สินค้า/รายละเอียด</th><th>หน่วย</th><th class="text-end">จำนวน</th><th class="text-end">ราคา/หน่วย</th><th class="text-end">รวม</th></tr></thead><tbody>@foreach($order->lines as $line)<tr><td>{{$line->line_number}}</td><td>{{($line->item?->code ? $line->item->code.' · ' : '').$line->description}}</td><td>{{$line->uom?->code ?? '-'}}</td><td class="text-end">{{$wmsDecimal::format($line->quantity)}}</td><td class="text-end">{{$wmsDecimal::format($line->unit_price)}}</td><td class="text-end">{{$wmsDecimal::format($line->line_total)}}</td></tr>@endforeach</tbody><tfoot><tr><th colspan="5" class="text-end">รวม</th><th class="text-end">{{$wmsDecimal::format($order->total_amount)}}</th></tr></tfoot></table></div><a class="btn btn-outline-secondary" href="{{route($moduleRoutePrefix.'.purchase-orders.index')}}">กลับรายการ</a></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">ประวัติเอกสาร</h2>@forelse($history ?? [] as $event)<div class="d-flex gap-3 border-bottom py-2"><div class="small text-secondary text-nowrap">{{$event->created_at->format('d/m/Y H:i')}}</div><div><strong>{{$event->action}}</strong><div class="small text-secondary">{{$event->user?->name ?? 'ระบบ'}}</div>@if($event->reason)<div class="small mt-1"><span class="text-secondary">เหตุผล:</span> {{$event->reason}}</div>@endif</div></div>@empty<p class="text-secondary mb-0">ยังไม่มีประวัติ</p>@endforelse</div></div>
</div>
@endsection
@push('scripts')<script>$(function(){$('.js-delete-document').on('click',function(){var b=$(this);Swal.fire({title:'ลบ Purchase Order?',text:'ลบได้เฉพาะเอกสารที่ยังเป็นร่าง',icon:'warning',showCancelButton:true,confirmButtonText:'ลบเอกสาร',cancelButtonText:'ยกเลิก'}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.ajax({url:b.data('url'),method:'DELETE',data:{_token:$('meta[name=csrf-token]').attr('content')}}).done(function(){window.location='{{route($moduleRoutePrefix.'.purchase-orders.index')}}';}).fail(function(q){Swal.fire({icon:'error',text:(q.responseJSON||{}).message||'ลบเอกสารไม่สำเร็จ'});b.prop('disabled',false);});});});});</script>@endpush
