@extends('Crm::layout')
@section('title', 'CRM Dashboard | MintERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 crm-page module-dashboard module-dashboard--crm">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4 crm-page-header module-dashboard-hero">
        <div><p class="module-dashboard-kicker mb-2"><span></span>CRM / DASHBOARD</p><h1 class="h3 mb-1">ภาพรวมลูกค้าสัมพันธ์</h1><p class="text-secondary mb-0">เห็นสถานะ Pipeline งานที่ต้องทำ และเริ่มงานถัดไปของสาขาปัจจุบัน</p></div>
        <div class="module-dashboard-actions d-flex flex-wrap gap-2"><button class="btn btn-app-soft d-none" type="button" data-crm-install><i class="bx bx-mobile-alt me-1" aria-hidden="true"></i>ติดตั้งบนมือถือ</button>@if(auth()->user()->hasPermission('crm.opportunities.view'))<a class="btn btn-app-soft" href="{{ route('crm.my-work.index') }}"><i class="bx bx-task me-1" aria-hidden="true"></i>งานของฉัน</a>@endif @if(auth()->user()->hasPermission('crm.opportunities.create'))<a class="btn btn-app-primary" href="{{ route('crm.opportunities.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>สร้างโอกาสการขาย</a>@endif</div>
    </div>

    <div class="row g-3 mb-4 module-dashboard-summary crm-dashboard-summary">
        <div class="col-6 col-xl-3"><a class="card border-0 shadow-sm h-100 crm-kpi text-decoration-none" href="{{ route('crm.opportunities.index') }}"><div class="card-body"><span class="crm-kpi-icon is-blue"><i class="bx bx-target-lock" aria-hidden="true"></i></span><div class="small text-secondary">กำลังติดตาม</div><div class="fs-2 fw-semibold crm-kpi-value">{{ number_format($openCount) }}</div><small class="text-secondary">ไม่มี Next action {{ number_format($noNextActionCount) }}</small></div></a></div>
        <div class="col-6 col-xl-3"><a class="card border-0 shadow-sm h-100 crm-kpi text-decoration-none" href="{{ auth()->user()->hasPermission('crm.forecast.view') ? route('crm.forecast.index') : route('crm.opportunities.index') }}"><div class="card-body"><span class="crm-kpi-icon is-violet"><i class="bx bx-line-chart" aria-hidden="true"></i></span><div class="small text-secondary">มูลค่า Pipeline</div><div class="fs-2 fw-semibold crm-kpi-value">฿{{ number_format((float)$pipelineValue, 2) }}</div><small class="text-secondary">ถ่วงน้ำหนัก ฿{{ number_format((float)$weightedValue, 2) }}</small></div></a></div>
        <div class="col-6 col-xl-3"><a class="card border-0 shadow-sm h-100 crm-kpi text-decoration-none" href="{{ route('crm.my-work.index', ['view'=>'TODAY']) }}"><div class="card-body"><span class="crm-kpi-icon is-teal"><i class="bx bx-calendar-check" aria-hidden="true"></i></span><div class="small text-secondary">กิจกรรมวันนี้</div><div class="fs-2 fw-semibold crm-kpi-value">{{ number_format($todayCount) }}</div><small class="text-secondary">ปิดการขายเดือนนี้ {{ number_format($wonMonthCount) }}</small></div></a></div>
        <div class="col-6 col-xl-3"><a class="card border-0 shadow-sm h-100 crm-kpi text-decoration-none" href="{{ route('crm.my-work.index', ['view'=>'OVERDUE']) }}"><div class="card-body"><span class="crm-kpi-icon is-danger"><i class="bx bx-error-circle" aria-hidden="true"></i></span><div class="small text-secondary">กิจกรรมเกินกำหนด</div><div class="fs-2 fw-semibold crm-kpi-value {{ $overdueCount ? 'text-danger' : 'text-success' }}">{{ number_format($overdueCount) }}</div><small class="text-secondary">{{ $overdueCount ? 'ควรจัดการเป็นลำดับแรก' : 'ไม่มีงานค้างเกินกำหนด' }}</small></div></a></div>
    </div>

    <div class="row g-4 mb-4">
        <div class="col-12 col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Pipeline ตามขั้นตอน</h2><a class="btn btn-sm btn-app-soft" href="{{ route('crm.opportunities.kanban') }}">เปิด Kanban</a></div>@foreach(\App\Modules\Crm\Models\Opportunity::STAGES as $code => $stage)<a class="crm-dashboard-stage" href="{{ route('crm.opportunities.index', ['stage' => $code]) }}"><span class="badge {{ $stage['class'] }}">{{ $stage['label'] }}</span><strong>{{ number_format((int)($stageCounts[$code] ?? 0)) }} <i class="bx bx-chevron-right" aria-hidden="true"></i></strong></a>@endforeach</div></div></div>
        <div class="col-12 col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">งานถัดไป</h2><p class="small text-secondary mb-0">เรียงตามกำหนดเวลา เพื่อเลือกงานที่ควรทำต่อ</p></div><a class="btn btn-sm btn-app-soft" href="{{ route('crm.calendar.index') }}">เปิดปฏิทิน</a></div><div class="list-group list-group-flush">@forelse($nextActions as $opportunity)<a class="list-group-item list-group-item-action px-0 py-3" href="{{ route('crm.opportunities.show', $opportunity) }}"><div class="d-flex justify-content-between gap-3 crm-next-action"><div class="min-w-0"><strong class="d-block text-truncate">{{ $opportunity->title }}</strong><div class="small text-secondary text-truncate">{{ $opportunity->party?->name ?: $opportunity->contact_name ?: 'ยังไม่ผูกลูกค้า' }} · {{ $opportunity->owner?->name ?: '-' }}</div></div><span class="small crm-next-action-time {{ $opportunity->next_action_at->isPast() ? 'text-danger fw-semibold' : 'text-secondary' }} text-nowrap">{{ $opportunity->next_action_at->format('d/m/Y H:i') }}</span></div></a>@empty<div class="text-secondary py-4 text-center"><i class="bx bx-calendar-check fs-2 d-block mb-2" aria-hidden="true"></i>ยังไม่มีงานที่กำหนดเวลา</div>@endforelse</div></div></div></div>
    </div>

    <div class="row g-4">
        <div class="col-12 col-lg-7"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-1">เริ่มงานอย่างรวดเร็ว</h2><p class="small text-secondary mb-3">ไปยังงานหลักโดยไม่ต้องค้นหาเมนู</p><div class="crm-dashboard-shortcuts"><a href="{{ route('crm.customers.index') }}"><i class="bx bx-user-circle" aria-hidden="true"></i><span>ลูกค้า 360°</span></a><a href="{{ route('crm.opportunities.index') }}"><i class="bx bx-target-lock" aria-hidden="true"></i><span>โอกาสการขาย</span></a><a href="{{ route('crm.calendar.index') }}"><i class="bx bx-calendar" aria-hidden="true"></i><span>ปฏิทินงาน</span></a><a href="{{ route('crm.workflow.index') }}"><i class="bx bx-map-alt" aria-hidden="true"></i><span>คู่มือการทำงาน</span></a></div></div></div></div>
        <div class="col-12 col-lg-5"><div class="card border-0 shadow-sm h-100 crm-install-card"><div class="card-body p-4 d-flex align-items-center gap-3"><span class="crm-install-icon"><i class="bx bx-mobile-alt" aria-hidden="true"></i></span><div class="flex-grow-1"><h2 class="h5 mb-1">ใช้ CRM เหมือนแอปบนมือถือ</h2><p class="small text-secondary mb-3">เพิ่ม MintERP CRM ลงหน้าจอหลัก เปิดใช้งานได้เร็วโดยไม่เก็บข้อมูลธุรกิจแบบ Offline</p><button class="btn btn-app-primary d-none" type="button" data-crm-install><i class="bx bx-download me-1" aria-hidden="true"></i>ติดตั้งบนหน้าจอหลัก</button></div></div></div></div>
    </div>
</div>
@endsection
