@extends('Pos::layout')
@section('title', 'สร้างชุดจ่ายคอมมิชชั่น | POS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">POS / COMMISSIONS</p><h1 class="h3 mb-2">สร้างชุดจ่ายคอมมิชชั่น</h1><p class="text-secondary mb-4">เลือกช่วงวันที่และพนักงาน ระบบจะสรุปเฉพาะรายการคอมมิชชั่นที่อนุมัติแล้วเพื่อส่งต่อฝ่ายการเงิน</p>
    <form id="commission-payment-batch-form" action="{{ route('pos.sales-commission-payment-batches.store') }}" method="post"><div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="row g-3">
        <div class="col-12 col-md-3"><label class="form-label">วันที่เริ่ม <span class="text-danger">*</span></label><input class="form-control" type="date" name="period_from" value="{{ now()->startOfMonth()->format('Y-m-d') }}" required></div>
        <div class="col-12 col-md-3"><label class="form-label">ถึงวันที่ <span class="text-danger">*</span></label><input class="form-control" type="date" name="period_to" value="{{ now()->endOfMonth()->format('Y-m-d') }}" required></div>
        <div class="col-12"><label class="form-label d-block">ผู้รับคอมมิชชั่น <span class="text-danger">*</span></label><div class="form-check mb-2"><input class="form-check-input" type="radio" name="selection_mode" id="commission-all" value="ALL" checked><label class="form-check-label" for="commission-all">จ่ายทุกคนที่มีคอมมิชชั่นอนุมัติแล้ว</label></div><div class="form-check"><input class="form-check-input" type="radio" name="selection_mode" id="commission-selected" value="SELECTED"><label class="form-check-label" for="commission-selected">เลือกเฉพาะพนักงาน</label></div>
            <select class="form-select mt-3" name="recipient_ids[]" id="commission-recipients" multiple disabled>@foreach($recipients as $recipient)<option value="{{ $recipient->id }}">{{ $recipient->name }}</option>@endforeach</select><div class="form-text">รายการพนักงานอ้างอิงจากคอมมิชชั่นที่อนุมัติแล้วในสาขาปัจจุบัน</div></div>
    </div><div class="mt-4 d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ route('pos.sales-commissions.index') }}">ย้อนกลับ</a><button class="btn btn-dark" type="submit">บันทึกชุดจ่าย</button></div></div></div></form>
</div>
@endsection
@push('scripts')<script>$(function(){const f=$('#commission-payment-batch-form'),r=$('#commission-recipients');r.select2({theme:'bootstrap-5',width:'100%',placeholder:'เลือกพนักงานขาย',closeOnSelect:false});$('input[name="selection_mode"]').on('change',function(){r.prop('disabled',this.value!=='SELECTED');if(this.value==='SELECTED')r.select2('open');});f.on('submit',function(e){e.preventDefault();const b=f.find(':submit').prop('disabled',true);$.ajax({url:f.attr('action'),method:'POST',data:f.serialize(),headers:{Accept:'application/json','X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}}).done(x=>location.href=x.redirect).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถสร้างชุดจ่ายได้'})).always(()=>b.prop('disabled',false));});});</script>@endpush
