@extends('Pos::layout')
@section('title', $batch->document_number.' | ชุดจ่ายคอมมิชชั่น')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">POS / COMMISSIONS</p><div class="d-flex justify-content-between gap-3 align-items-start mb-4"><div><h1 class="h3 mb-1">{{ $batch->document_number }}</h1><p class="text-secondary mb-0">รอบ {{ $batch->period_from->format('d/m/Y') }} - {{ $batch->period_to->format('d/m/Y') }}</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ route('pos.sales-commissions.index') }}">ย้อนกลับ</a>@if($batch->status === 'DRAFT')<button class="btn btn-dark js-submit" data-url="{{ route('pos.sales-commission-payment-batches.submit',$batch) }}">ส่งให้ฝ่ายการเงิน</button><button class="btn btn-outline-danger js-cancel" data-url="{{ route('pos.sales-commission-payment-batches.cancel',$batch) }}">ยกเลิกเอกสาร</button>@endif</div></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="row g-3"><div class="col-md-4"><div class="small text-secondary">สถานะเอกสาร</div><div class="mt-1">@if($batch->status === 'SUBMITTED')<span class="badge app-badge-info">ส่งให้การเงินแล้ว</span>@elseif($batch->status === 'VERIFIED')<span class="badge app-badge-success">ฝ่ายการเงินตรวจสอบแล้ว</span>@elseif($batch->status === 'CANCELLED')<span class="badge app-status-danger">ยกเลิกแล้ว</span>@else<span class="badge app-badge-soft">ร่าง</span>@endif</div></div><div class="col-md-4"><div class="small text-secondary">จำนวนรายการ</div><strong>{{ $batch->lines->count() }}</strong></div><div class="col-md-4 text-md-end"><div class="small text-secondary">ยอดรวม</div><strong class="h4">{{ number_format((float)$batch->total_amount,2) }}</strong></div></div></div></div>
    @if($batch->status === 'CANCELLED' && $batch->cancellation_reason)<div class="alert alert-warning border-0 mb-3"><div class="fw-semibold mb-1">{{ $batch->cancellation_source === 'FINANCE' ? 'เหตุผลที่ฝ่ายการเงินยกเลิกเอกสาร' : 'เหตุผลที่ยกเลิกเอกสารใน POS' }}</div><div>{{ $batch->cancellation_reason }}</div></div>@endif
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h6 mb-3">สรุปตามพนักงานขาย</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>ผู้รับคอมมิชชั่น</th><th class="text-end">จำนวนรายการ</th><th class="text-end">ยอดคอมมิชชั่น</th><th class="text-end">จัดการ</th></tr></thead><tbody>@foreach($recipientTotals as $recipientId => $total)<tr><td>{{ $total['name'] }}</td><td class="text-end">{{ $total['lines'] }}</td><td class="text-end fw-semibold">{{ number_format($total['amount'],2) }}</td><td class="text-end"><button type="button" class="btn btn-sm btn-app-soft" data-bs-toggle="modal" data-bs-target="#commission-reference-{{ $recipientId }}"><i class="bx bx-show me-1" aria-hidden="true"></i>ดูรายละเอียด</button></td></tr>@endforeach</tbody></table></div></div></div>
    @foreach($recipientDetails as $recipientId => $lines)<div class="modal fade" id="commission-reference-{{ $recipientId }}" tabindex="-1" aria-labelledby="commission-reference-label-{{ $recipientId }}" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h2 class="modal-title fs-5" id="commission-reference-label-{{ $recipientId }}">รายละเอียดคอมมิชชั่น</h2><div class="text-secondary small">{{ $lines->first()->commissionRecord->recipient?->name ?? '—' }}</div></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>เอกสารอ้างอิง</th><th class="text-end">ฐานคำนวณ</th><th class="text-end">อัตรา</th><th class="text-end">ค่าคอมมิชชั่น</th></tr></thead><tbody>@foreach($lines as $line)<tr><td>{{ $line->commissionRecord->physicalSale?->document_number ?? $line->commissionRecord->source_id }}</td><td class="text-end">{{ number_format((float) $line->commissionRecord->base_amount, 2) }}</td><td class="text-end">{{ number_format((float) $line->commissionRecord->rate_percent, 4) }}%</td><td class="text-end fw-semibold">{{ number_format((float) $line->amount, 2) }}</td></tr>@endforeach</tbody><tfoot class="table-light"><tr><th colspan="3" class="text-end">รวม</th><th class="text-end">{{ number_format((float) $lines->sum('amount'), 2) }}</th></tr></tfoot></table></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">ปิด</button></div></div></div></div>@endforeach
    <div class="card border-0 shadow-sm mt-3"><div class="card-body p-3 p-lg-4"><h2 class="h6 mb-3">ประวัติเอกสาร</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-light"><tr><th>วันเวลา</th><th>เหตุการณ์</th><th>ผู้ดำเนินการ</th><th>เหตุผล</th></tr></thead><tbody>@forelse($history as $log)<tr><td>{{ $log->created_at?->format('d/m/Y H:i') }}</td><td>{{ $log->action }}</td><td>{{ $log->user?->name ?? 'ระบบ' }}</td><td>{{ $log->reason ?? '—' }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">ยังไม่มีประวัติเอกสาร</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){$.ajaxSetup({headers:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content'),'Accept':'application/json'}});$('.js-submit').on('click',function(){const b=$(this);Swal.fire({icon:'question',text:'ส่งชุดจ่ายทั้งหมดให้ฝ่ายการเงินดำเนินการต่อ?',showCancelButton:true,confirmButtonText:'ส่งให้การเงิน',cancelButtonText:'ย้อนกลับ'}).then(r=>{if(!r.isConfirmed)return;b.prop('disabled',true);$.post(b.data('url'),{},x=>location.href=x.redirect).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถส่งให้การเงินได้'})).always(()=>b.prop('disabled',false));});});$('.js-cancel').on('click',function(){const b=$(this);Swal.fire({icon:'warning',title:'ยกเลิกเอกสาร?',input:'text',inputLabel:'เหตุผล',inputValidator:v=>!v?'กรุณาระบุเหตุผล':undefined,showCancelButton:true,confirmButtonText:'ยกเลิกเอกสาร',cancelButtonText:'ย้อนกลับ'}).then(r=>{if(!r.isConfirmed)return;b.prop('disabled',true);$.post(b.data('url'),{reason:r.value},x=>location.href=x.redirect).fail(x=>Swal.fire({icon:'error',text:x.responseJSON?.message||'ไม่สามารถยกเลิกเอกสารได้'})).always(()=>b.prop('disabled',false));});});});</script>@endpush
