@extends('Wms::layout')
@section('title', 'สินค้า | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><h1 class="h3 mb-4">{{ $item->exists ? 'แก้ไข' : 'เพิ่ม' }}สินค้า</h1>
<form id="item-form" method="POST" action="{{ $item->exists ? route('wms.items.update', $item) : route('wms.items.store') }}">@csrf @if($item->exists) @method('PUT') @endif
<div class="card border-0 shadow-sm"><div class="card-body p-4 row g-3">
<div class="col-md-3"><label class="form-label">รหัส</label><input class="form-control" name="code" value="{{ old('code', $item->code) }}" required></div>
<div class="col-md-5"><label class="form-label">ชื่อ</label><input class="form-control" name="name" value="{{ old('name', $item->name) }}" required></div>
<div class="col-md-4"><label class="form-label">หมวดสินค้า</label><select class="form-select js-category" name="category_id" data-url="{{ route('wms.items.category-options') }}" required>@if($selectedCategory)<option value="{{ $selectedCategory->id }}" selected>{{ $selectedCategory->code }} · {{ $selectedCategory->name }}</option>@endif</select></div>
<div class="col-md-3"><label class="form-label">ประเภท</label><select class="form-select" name="item_type"><option value="GOODS" @selected(old('item_type', $item->item_type) === 'GOODS')>สินค้า</option><option value="SERVICE" @selected(old('item_type', $item->item_type) === 'SERVICE')>บริการ</option></select></div>
<div class="col-md-3"><label class="form-label">หน่วยหลัก</label><select class="form-select js-uom" name="base_uom_id" data-url="{{ route('wms.items.uom-options') }}" required>@if($selectedUom)<option value="{{ $selectedUom->id }}" selected>{{ $selectedUom->code }} · {{ $selectedUom->name }}</option>@endif</select><input type="hidden" name="base_uom" value="{{ old('base_uom', $item->base_uom ?: 'EA') }}"></div>
<div class="col-md-3 form-check mt-5"><input class="form-check-input" type="checkbox" name="is_stock_item" value="1" @checked(old('is_stock_item', $item->is_stock_item))><label class="form-check-label">ติดตามสต็อก</label></div><div class="col-md-3 form-check mt-5"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active', $item->is_active ?? true))><label class="form-check-label">ใช้งาน</label></div>
@foreach([['inventory_account_id', 'บัญชีสินค้าคงเหลือ', 'ASSET', false], ['sales_account_id', 'บัญชีรายได้', 'REVENUE', true], ['cogs_account_id', 'บัญชีต้นทุน', 'COGS', false]] as [$field, $label, $type, $required])<div class="col-md-4"><label class="form-label">{{ $label }}</label><select class="form-select js-account" name="{{ $field }}" data-type="{{ $type }}" @required($required)><option value="">{{ $required ? 'เลือกบัญชี' : 'ไม่กำหนด' }}</option>@if($a = $accounts->get($item->{$field}))<option value="{{ $a->id }}" selected>{{ $a->code }} · {{ $a->name }}</option>@endif</select></div>@endforeach
</div><div class="p-4"><button class="btn btn-dark" type="submit">บันทึก</button></div></div></form></div>
@endsection
@push('scripts')<script>$(function(){$('.js-account').each(function(){var s=$(this);s.select2({width:'100%',theme:'bootstrap-5',ajax:{url:'{{route('wms.items.account-options')}}',delay:250,data:function(p){return{q:p.term||'',page:p.page||1,type:s.data('type')};},processResults:function(d){return d;}}})});$('.js-category,.js-uom').each(function(){var s=$(this);s.select2({width:'100%',theme:'bootstrap-5',placeholder:'ค้นหารหัสหรือชื่อ',ajax:{url:s.data('url'),delay:250,data:function(p){return{q:p.term||'',page:p.page||1};},processResults:function(d){return d;}}})});window.erpAjaxForm({form:'#item-form',redirect:true})});</script>@endpush
