@extends('Wms::layout')

@section('title', 'สินค้า | WMS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4">
        <div><p class="eyebrow mb-2">WMS / MASTER DATA</p><h1 class="h3 mb-2">สินค้า</h1><p class="text-secondary mb-0">จัดการสินค้า บริการ หน่วยนับ และข้อมูลบัญชีที่ใช้กับรายการ WMS</p></div>
        <div class="d-flex flex-wrap gap-2">@if(auth()->user()->hasPermission('wms.items.print'))<button class="btn btn-app-soft" id="print-item-labels" type="button" disabled><i class="bx bx-barcode me-1" aria-hidden="true"></i>พิมพ์สติกเกอร์ <span class="badge app-status-info ms-1" id="selected-item-count">0</span></button>@endif @if(auth()->user()->hasPermission('wms.items.create'))<a class="btn btn-app-primary" href="{{ route('wms.items.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มสินค้า</a>@endif</div>
    </div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">ตัวกรองสินค้า</h2><p class="small text-secondary mb-0">กรองก่อนค้นหาจากข้อมูลที่แสดงในตาราง</p></div><button type="button" class="btn btn-app-soft" id="item-filter-reset"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-12 col-md-3"><label class="form-label">หมวดสินค้า</label><select class="form-select js-item-filter" id="item-category-filter" data-url="{{ route('wms.items.category-options') }}"><option value="">ทุกหมวดสินค้า</option></select></div><div class="col-12 col-md-3"><label class="form-label">หน่วยนับ</label><select class="form-select js-item-filter" id="item-uom-filter" data-url="{{ route('wms.items.uom-options') }}"><option value="">ทุกหน่วยนับ</option></select></div><div class="col-12 col-md-2"><label class="form-label">ประเภท</label><select class="form-select js-item-filter" id="item-type-filter"><option value="">ทุกประเภท</option><option value="GOODS">สินค้า</option><option value="SERVICE">บริการ</option></select></div><div class="col-12 col-md-2"><label class="form-label">การรับรู้สินทรัพย์</label><select class="form-select js-item-filter" id="item-asset-filter"><option value="">ทั้งหมด</option><option value="1">รับรู้สินทรัพย์</option><option value="0">ไม่รับรู้สินทรัพย์</option></select></div><div class="col-12 col-md-2"><label class="form-label">สถานะ</label><select class="form-select js-item-filter" id="item-status-filter"><option value="">ทุกสถานะ</option><option value="1" selected>ใช้งาน</option><option value="0">ปิดใช้งาน</option></select></div></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="mb-3"><h2 class="h5 mb-1">รายการสินค้า</h2><p class="small text-secondary mb-0">ใช้ช่องค้นหาในตารางเพื่อค้นหารหัส ชื่อ และข้อมูลที่แสดง</p></div><div class="table-responsive"><table class="table table-hover align-middle w-100" id="items-table"><thead><tr><th>ลำดับ</th>@if(auth()->user()->hasPermission('wms.items.print'))<th class="no-export text-center"><input class="form-check-input" id="select-page-items" type="checkbox" aria-label="เลือกสินค้าทั้งหมดในหน้านี้"></th>@endif<th>รูป</th><th>รหัส</th><th>ชื่อ</th><th>หมวด</th><th>ประเภท</th><th>หน่วย</th><th>รับรู้สินทรัพย์</th><th>สถานะ</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')
<script>
$(function(){
 const tableElement=$('#items-table'),text=$.fn.dataTable.render.text(),category=$('#item-category-filter'),uom=$('#item-uom-filter'),type=$('#item-type-filter'),asset=$('#item-asset-filter'),status=$('#item-status-filter');
 $('.js-item-filter[data-url]').each(function(){const select=$(this);window.erpInitSelect2(select,{theme:'bootstrap-5',placeholder:select.find('option:first').text(),allowClear:true,ajax:{url:select.data('url'),delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:data=>data}});});
 const selectedItems=new Set(),canPrint={{ auth()->user()->hasPermission('wms.items.print') ? 'true' : 'false' }};
 const table=tableElement.DataTable($.extend(true,{},window.erpDataTableDefaults,{processing:true,serverSide:true,order:[[canPrint?3:2,'asc']],ajax:{url:'{{ route('wms.items.data') }}',data:function(data){data.category_id=category.val();data.base_uom_id=uom.val();data.item_type=type.val();data.asset_capitalizable=asset.val();data.is_active=status.val();}},buttons:[window.erpExcelButton(tableElement)],columns:[
  {data:null,orderable:false,searchable:false,className:'text-center',render:(value,rowType,row,meta)=>rowType==='display'?meta.settings._iDisplayStart+meta.row+1:''},
  ...(canPrint?[{data:'id',orderable:false,searchable:false,className:'no-export text-center',render:(id,rowType,row)=>rowType==='display'?'<input class="form-check-input js-item-select" type="checkbox" value="'+Number(id)+'" aria-label="เลือก '+text.display(row.code)+'" '+(selectedItems.has(Number(id))?'checked':'')+'>':''}]:[]),
  {data:'cover_image_url',orderable:false,searchable:false,render:(value,rowType,row)=>rowType==='display'&&value?'<img src="'+text.display(value)+'" alt="รูปหน้าปกสินค้า '+text.display(row.code)+'" class="img-thumbnail rounded" loading="lazy" width="48" height="48" style="width:48px;height:48px;object-fit:cover;">':'—'},
  {data:'code',name:'code',render:text.display},{data:'name',name:'name',render:text.display},{data:'category_label',name:'category.name',render:text.display},{data:'item_type',name:'item_type',render:(value,rowType)=>rowType==='display'?(value==='GOODS'?'สินค้า':'บริการ'):value},{data:'base_uom_label',name:'baseUom.name',render:text.display},{data:'asset_capitalization_label',orderable:false,render:text.display},{data:'status_label',name:'is_active',render:function(value,rowType,row){return rowType==='display'?'<span class="badge '+(row.is_active?'app-status-success':'app-status-neutral')+'">'+text.display(value)+'</span>':value;}},{data:null,orderable:false,searchable:false,className:'text-end text-nowrap',render:function(value,rowType,row){if(rowType!=='display')return '';let html=row.edit_url?'<a class="btn btn-sm btn-app-soft" href="'+row.edit_url+'" title="แก้ไข" aria-label="แก้ไข '+text.display(row.code)+'"><i class="bx bx-edit" aria-hidden="true"></i></a>':'';if(row.delete_url)html+=' <button type="button" class="btn btn-sm btn-app-danger js-item-delete" data-url="'+row.delete_url+'" title="ลบ" aria-label="ลบ '+text.display(row.code)+'"><i class="bx bx-trash" aria-hidden="true"></i></button>';return html;}}
 ]}));
 function refreshSelection(){const count=selectedItems.size;$('#selected-item-count').text(count);$('#print-item-labels').prop('disabled',count===0);const ids=table.rows({page:'current'}).data().toArray().map(row=>Number(row.id));$('#select-page-items').prop('checked',ids.length>0&&ids.every(id=>selectedItems.has(id))).prop('indeterminate',ids.some(id=>selectedItems.has(id))&&!ids.every(id=>selectedItems.has(id)));}
 table.on('draw',refreshSelection);tableElement.on('change','.js-item-select',function(){const id=Number(this.value);this.checked?selectedItems.add(id):selectedItems.delete(id);refreshSelection();});$('#select-page-items').on('change',function(){const checked=this.checked;table.rows({page:'current'}).data().each(row=>checked?selectedItems.add(Number(row.id)):selectedItems.delete(Number(row.id)));tableElement.find('.js-item-select').prop('checked',checked);refreshSelection();});$('#print-item-labels').on('click',function(){const params=new URLSearchParams();selectedItems.forEach(id=>params.append('item_ids[]',id));window.location.href='{{ route('wms.items.labels.create') }}?'+params.toString();});
 $('.js-item-filter').on('change',()=>table.ajax.reload());$('#item-filter-reset').on('click',function(){category.val(null).trigger('change');uom.val(null).trigger('change');type.val('');asset.val('');status.val('1');table.ajax.reload();});
 window.erpAjaxDelete({button:'.js-item-delete',reload:'#items-table',title:'ลบสินค้า?',text:'ลบได้เฉพาะสินค้าที่ยังไม่ถูกใช้งาน',confirmButtonText:'ลบ',cancelButtonText:'กลับ'});
});
</script>
@endpush
