@extends('Production::layout')
@section('title', 'ปัญหาหน้างานผลิต | MintERP')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><p class="eyebrow mb-2">PRODUCTION / SHOP FLOOR</p><h1 class="h3 mb-1">ปัญหาหน้างานผลิต</h1><p class="text-secondary mb-0">รายการที่พนักงานแจ้งให้ Supervisor เข้าตรวจสอบ</p></div><a class="btn btn-outline-secondary" href="{{ route('production.shop-floor.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้างานผลิต</a></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-transparent d-flex justify-content-between align-items-center"><strong>ตัวกรองปัญหาหน้างาน</strong><button class="btn btn-sm btn-app-soft" type="button" id="reset-production-issues-filters"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="card-body"><form id="production-issues-filters" class="row g-3 align-items-end"><div class="col-12 col-md-3"><label class="form-label" for="production-issues-status">สถานะ</label><select class="form-select" id="production-issues-status" name="status"><option value="">ทั้งหมด</option><option value="OPEN">รอตรวจสอบ</option><option value="RESOLVED">แก้ไขแล้ว</option></select></div><div class="col-12 col-md-3"><label class="form-label" for="production-issues-severity">ความรุนแรง</label><select class="form-select" id="production-issues-severity" name="severity"><option value="">ทั้งหมด</option><option value="HIGH">สูง</option><option value="MEDIUM">กลาง</option><option value="LOW">ต่ำ</option></select></div><div class="col-12 col-md-2"><label class="form-label" for="production-issues-date-from">แจ้งตั้งแต่</label><input class="form-control" id="production-issues-date-from" type="date" name="date_from"></div><div class="col-12 col-md-2"><label class="form-label" for="production-issues-date-to">ถึงวันที่</label><input class="form-control" id="production-issues-date-to" type="date" name="date_to"></div><div class="col-12 col-md-2"><button class="btn btn-app-primary w-100" type="submit"><i class="bx bx-search me-1" aria-hidden="true"></i>ค้นหา</button></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="table-responsive"><table id="production-issues-table" class="table table-hover align-middle w-100" data-url="{{ route('production.shop-floor.issues.data') }}"><thead><tr><th>ลำดับ</th><th>WO</th><th>ความรุนแรง</th><th>ปัญหา</th><th>ผู้แจ้ง</th><th>วันที่แจ้ง</th><th>ผู้แก้ปัญหา</th><th>วิธีการแก้ปัญหา</th><th>แก้เสร็จเมื่อ</th><th>ระยะเวลา</th><th>สถานะ</th><th>จัดการ</th></tr></thead></table></div></div></div></div>
@endsection
@push('scripts')
<script>
$(function(){const table=$('#production-issues-table'),filters=$('#production-issues-filters'),text=$.fn.dataTable.render.text(),severity={LOW:['ต่ำ','app-status-info'],MEDIUM:['กลาง','app-status-warning'],HIGH:['สูง','app-status-danger']},status={OPEN:['รอตรวจสอบ','app-status-danger'],RESOLVED:['แก้ไขแล้ว','app-status-success']};table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:{url:table.data('url'),data:function(d){filters.serializeArray().forEach(function(field){if(field.value)d[field.name]=field.value;});}},order:[[5,'desc']],buttons:[window.erpExcelButton(table)],columns:[window.erpRowNumberColumn(),{data:'wo_label',name:'wo_label',render:function(v,t,r){return t==='display'?'<a href="'+text.display(r.show_url)+'">'+text.display(v)+'</a>':v;}},{data:'severity',name:'severity',render:function(v,t){if(t!=='display')return v;const s=severity[v]||[v,'app-status-neutral'];return '<span class="badge '+s[1]+'">'+text.display(s[0])+'</span>'; }},{data:'description',name:'description',render:text.display},{data:'reporter_label',name:'reporter_label',render:text.display},{data:'reported_at_label',name:'reported_at',render:text.display},{data:'resolver_label',name:'resolver_label',render:text.display},{data:'resolution_method_label',name:'resolution_method',render:text.display},{data:'resolved_at_label',name:'resolved_at',render:text.display},{data:'resolution_duration_label',name:'resolved_at',orderable:false,render:text.display},{data:'status',name:'status',render:function(v,t){if(t!=='display')return v;const s=status[v]||[v,'app-status-neutral'];return '<span class="badge '+s[1]+'">'+text.display(s[0])+'</span>'; }},{data:null,orderable:false,searchable:false,className:'text-end',render:function(_,t,r){if(t!=='display')return '';return '<a class="btn btn-sm btn-app-soft" href="'+text.display(r.show_url)+'?issue_id='+encodeURIComponent(r.id)+'#issues" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-show" aria-hidden="true"></i></a>'; }}]}));filters.on('submit',function(e){e.preventDefault();table.DataTable().ajax.reload();});$('#reset-production-issues-filters').on('click',function(){filters[0].reset();table.DataTable().ajax.reload();});});
</script>
@endpush
