@extends('Production::layout')
@section('title', 'งานผลิต '.$order->document_number.' | MintERP')
@section('content')
@php($labels = ['RELEASED' => 'พร้อมผลิต', 'IN_PROGRESS' => 'กำลังผลิต', 'COMPLETED' => 'เสร็จแล้ว'])
@php($progress = $order->status === 'COMPLETED' ? 100 : ($receiptDocument?->status === 'POSTED' ? 100 : ($receiptDocument?->status === 'APPROVED' ? 85 : ($receiptDocument ? 75 : ($order->started_at ? 60 : ($issue?->status === 'POSTED' ? 45 : ($issue?->status === 'APPROVED' ? 30 : ($issue ? 15 : 0))))))));
@php($progressLabel = $progress >= 100 ? 'เสร็จสิ้น' : ($progress >= 60 ? 'กำลังดำเนินการผลิต' : ($progress > 0 ? 'เตรียมงานผลิต' : 'ยังไม่เริ่ม')))
<div class="container-fluid px-3 px-lg-4 py-4 module-dashboard">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4 p-4 rounded-4 bg-info-subtle">
        <div><p class="eyebrow mb-2">PRODUCTION / SHOP FLOOR WORK</p><div class="d-flex align-items-center gap-3"><div class="app-cover-thumb rounded-3 bg-white d-flex align-items-center justify-content-center">@if($order->finishedItem?->cover_image_path)<img src="{{ route('production.shop-floor.item-image', [$order, $order->finishedItem]) }}" alt="ภาพสินค้า {{ $order->finishedItem->name }}" class="w-100 h-100"></div>@else<i class="bx bx-package fs-2 text-secondary" aria-hidden="true"></i></div>@endif<h1 class="h2 mb-0">{{ $order->document_number }}</h1></div><p class="mb-0 mt-2 text-secondary">{{ $order->finishedItem?->code }} · {{ $order->finishedItem?->name }}</p></div>
        <div class="text-end"><span class="badge app-status-{{ $order->status === 'IN_PROGRESS' ? 'warning' : 'info' }} fs-6">{{ $labels[$order->status] ?? $order->status }}</span>@if($order->started_at)<div class="small text-secondary mt-2">เริ่มงาน {{ $order->started_at->format('d/m/Y H:i') }}</div>@endif @if($order->status === 'IN_PROGRESS')<button class="btn btn-app-warning mt-3" type="button" data-bs-toggle="modal" data-bs-target="#production-issue-modal"><i class="bx bx-error-circle me-1" aria-hidden="true"></i>แจ้งปัญหาการผลิต</button>@endif @if($order->status === 'RELEASED' && auth()->user()->hasPermission('production.orders.cancel'))<button class="btn btn-app-danger mt-3 js-shop-action" type="button" data-url="{{ route('production.orders.cancel', $order) }}"><i class="bx bx-x-circle me-1" aria-hidden="true"></i>ยกเลิกเอกสาร</button>@endif</div>
    </div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body py-3"><div class="d-flex justify-content-between align-items-center mb-2"><strong>ความคืบหน้างานผลิต</strong><span class="badge app-status-{{ $progress >= 100 ? 'success' : ($progress >= 60 ? 'warning' : 'info') }}">{{ $progressLabel }} · {{ $progress }}%</span></div><div class="progress" role="progressbar" aria-label="ความคืบหน้างานผลิต" aria-valuenow="{{ $progress }}" aria-valuemin="0" aria-valuemax="100" style="height:14px"><div class="progress-bar bg-{{ $progress >= 100 ? 'success' : ($progress >= 60 ? 'warning' : 'info') }}" style="width:{{ $progress }}%"></div></div><div class="row g-2 text-center small mt-2"><div class="col-4"><span class="badge app-status-{{ $issue?->status === 'POSTED' ? 'success' : 'neutral' }} mb-1">1</span><div>เตรียมใบเบิก</div></div><div class="col-4"><span class="badge app-status-{{ $order->started_at ? 'success' : 'neutral' }} mb-1">2</span><div>ยืนยันเริ่มงาน</div></div><div class="col-4"><span class="badge app-status-{{ $order->status === 'COMPLETED' ? 'success' : 'neutral' }} mb-1">3</span><div>รับผลิตเสร็จ</div></div></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body py-3 d-flex justify-content-between align-items-center"><span class="text-secondary"><i class="bx bx-time-five me-1" aria-hidden="true"></i>เวลาที่ใช้ผลิต</span><strong class="js-production-elapsed" data-started-at="{{ $order->started_at?->toIso8601String() }}" data-ended-at="{{ $order->completed_at?->toIso8601String() }}">{{ $order->started_at ? 'กำลังคำนวณ...' : 'ยังไม่เริ่ม' }}</strong></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body py-3"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">ขั้นตอนการผลิต</h2>@if(in_array($order->status, ['DRAFT','RELEASED'], true) && auth()->user()->hasPermission('production.routing.create'))<button class="btn btn-sm btn-app-soft js-operation-add" type="button" data-url="{{ route('production.shop-floor.operation.store', $order) }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มขั้นตอน</button>@endif</div>@foreach($order->operations as $operation)<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 border-bottom py-2"><div><strong>{{ $operation->sequence }}. {{ $operation->name }}</strong><div class="small text-secondary">{{ $operation->planned_minutes ? $operation->planned_minutes.' นาที' : 'ไม่กำหนดเวลา' }}</div></div><div>@if($operation->status === 'PENDING')<span class="badge app-status-neutral">รอดำเนินการ</span>@elseif($operation->status === 'IN_PROGRESS')<span class="badge app-status-warning">กำลังทำ</span>@elseif($operation->status === 'COMPLETED')<span class="badge app-status-success">เสร็จแล้ว</span>@else<span class="badge app-status-neutral">ข้าม</span>@endif @if($operation->status === 'PENDING' && auth()->user()->hasPermission('production.routing.update'))<button class="btn btn-sm btn-app-soft js-operation-edit ms-1" type="button" data-url="{{ route('production.shop-floor.operation.update', [$order, $operation]) }}" data-name="{{ $operation->name }}" data-minutes="{{ $operation->planned_minutes }}" title="แก้ไข Operation" aria-label="แก้ไข Operation"><i class="bx bx-edit" aria-hidden="true"></i></button>@endif @if($operation->status === 'PENDING' && auth()->user()->hasPermission('production.routing.delete'))<button class="btn btn-sm btn-app-danger js-operation-delete ms-1" type="button" data-url="{{ route('production.shop-floor.operation.delete', [$order, $operation]) }}" title="ลบ Operation" aria-label="ลบ Operation"><i class="bx bx-trash" aria-hidden="true"></i></button>@endif @if(auth()->user()->hasPermission('production.operations.execute') && $operation->status === 'PENDING' && ! $order->held_at)<button class="btn btn-sm btn-app-primary js-shop-action ms-2" type="button" data-url="{{ route('production.shop-floor.operation.start', [$order, $operation]) }}">เริ่ม</button>@elseif(auth()->user()->hasPermission('production.operations.execute') && $operation->status === 'IN_PROGRESS' && ! $order->held_at)<button class="btn btn-sm btn-app-success js-shop-action ms-2" type="button" data-url="{{ route('production.shop-floor.operation.complete', [$order, $operation]) }}">จบขั้นตอน</button>@endif</div></div>@endforeach</div></div>
    <div id="shop-floor-network-status" class="alert alert-warning d-none" role="status" aria-live="polite"><i class="bx bx-wifi-off me-1" aria-hidden="true"></i>เครือข่ายขัดข้อง กรุณาตรวจสอบการเชื่อมต่อก่อนทำรายการ</div>
    <div class="d-flex flex-wrap gap-2 mb-3"><a class="btn btn-outline-secondary btn-lg" href="{{ route('production.shop-floor.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้างานผลิต</a><span class="badge app-status-neutral align-self-center">ขั้นตอนถัดไปจะแสดงในหน้านี้</span></div><div id="shop-floor-feedback" class="alert d-none" role="status" aria-live="polite"></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body py-3"><div class="d-flex justify-content-between align-items-center"><strong><i class="bx bx-error-circle me-1" aria-hidden="true"></i>ปัญหาการผลิต</strong><span class="badge app-status-{{ $productionIssues->where('status','OPEN')->count() ? 'danger' : 'success' }}">{{ $productionIssues->count() }} รายการ · เปิด {{ $productionIssues->where('status','OPEN')->count() }}</span></div>@if($productionIssues->isNotEmpty())<div class="table-responsive mt-3"><table class="table table-sm align-middle mb-0"><thead><tr><th>เวลา</th><th>ความรุนแรง</th><th>รายละเอียด</th><th>สถานะ</th></tr></thead><tbody>@foreach($productionIssues as $productionIssue)<tr><td>{{ $productionIssue->reported_at?->format('d/m/Y H:i') }}</td><td><span class="badge app-status-{{ $productionIssue->severity === 'HIGH' ? 'danger' : ($productionIssue->severity === 'MEDIUM' ? 'warning' : 'info') }}">{{ ['LOW'=>'ต่ำ','MEDIUM'=>'กลาง','HIGH'=>'สูง'][$productionIssue->severity] }}</span></td><td>{{ $productionIssue->description }}<div class="small text-secondary">แจ้งโดย {{ $productionIssue->reporter?->name ?: '-' }}</div></td><td>@if($productionIssue->status === 'OPEN')<span class="badge app-status-danger">รอตรวจสอบ</span>@else<span class="badge app-status-success">แก้ไขแล้ว</span><div class="small text-secondary">{{ $productionIssue->resolved_at?->format('d/m/Y H:i') }} · {{ $productionIssue->resolver?->name ?: '-' }}</div>@endif</td></tr>@endforeach</tbody></table></div>@else<div class="small text-secondary mt-2">ยังไม่มีการแจ้งปัญหา</div>@endif</div></div>
    <div class="row g-4">
        <div class="col-12 col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header bg-info-subtle border-0"><h2 class="h5 mb-0"><i class="bx bx-list-check me-1" aria-hidden="true"></i>วัตถุดิบที่ต้องใช้</h2><div class="small text-secondary mt-1">ตรวจสอบรายการนี้ก่อนยืนยันเริ่มงาน</div></div><div class="card-body p-0"><div class="shop-floor-material-list table-responsive"><table class="table align-middle mb-0"><thead><tr><th>วัตถุดิบ</th><th class="text-end">จำนวน</th><th>หน่วย</th></tr></thead><tbody>@forelse($order->materials as $line)<tr><td><div class="d-flex align-items-center gap-2"><div class="app-cover-thumb app-cover-thumb-sm rounded-2 bg-light d-flex align-items-center justify-content-center">@if($line->item?->cover_image_path)<img src="{{ route('production.shop-floor.item-image', [$order, $line->item]) }}" alt="ภาพวัตถุดิบ {{ $line->item->name }}" class="w-100 h-100">@else<i class="bx bx-package text-secondary" aria-hidden="true"></i>@endif</div><div><strong>{{ $line->item?->code }}</strong><div class="small text-secondary">{{ $line->item?->name }}</div></div></div></td><td class="text-end">{{ number_format((float)$line->required_quantity, 2) }}</td><td>{{ $line->uom?->code }}</td></tr>@empty<tr><td colspan="3" class="text-secondary text-center py-4">ยังไม่มีรายการวัตถุดิบ</td></tr>@endforelse</tbody></table></div></div></div></div>
        <div class="col-12 col-lg-5"><div class="card border-0 shadow-sm mb-4"><div class="card-header bg-success-subtle border-0"><h2 class="h5 mb-0"><i class="bx bx-target-lock me-1" aria-hidden="true"></i>เป้าหมายการผลิต</h2></div><div class="card-body"><div class="row g-3"><div class="col-6"><div class="small text-secondary">จำนวนผลิต</div><strong class="fs-4">{{ number_format((float)$order->planned_quantity, 2) }}</strong> {{ $order->uom?->code }}</div><div class="col-6"><div class="small text-secondary">เริ่มตามแผน</div><strong>{{ $order->planned_start_at?->format('d/m/Y H:i') ?: ($order->planned_start_date?->format('d/m/Y').' ไม่ระบุเวลา') }}</strong></div><div class="col-6"><div class="small text-secondary">กำหนดเสร็จ</div><strong>{{ $order->planned_finish_at?->format('d/m/Y H:i') ?: ($order->planned_finish_date?->format('d/m/Y').' ไม่ระบุเวลา') }}</strong></div><div class="col-6"><div class="small text-secondary">กำหนดส่ง</div><strong>{{ $order->required_delivery_at?->format('d/m/Y H:i') ?: ($order->required_delivery_date?->format('d/m/Y').' ไม่ระบุเวลา' ?: 'ไม่ระบุ') }}</strong></div></div></div></div><div class="card border-0 shadow-sm border-start border-4 border-warning"><div class="card-header bg-warning-subtle border-0"><h2 class="h5 mb-0"><i class="bx bx-run me-1" aria-hidden="true"></i>ขั้นตอนปฏิบัติงาน</h2></div><div class="card-body"><ol class="text-secondary ps-3 mb-3"><li>ตรวจสอบสินค้าที่ต้องผลิตและจำนวนเป้าหมาย</li><li>ตรวจสอบวัตถุดิบตามรายการด้านซ้าย</li><li>กดยืนยันเริ่มงานก่อนเริ่มผลิตจริง</li><li>เมื่อเสร็จแล้วจึงสร้างใบรับผลิตเสร็จ</li></ol>@if($order->notes)<div class="alert alert-info mb-3"><strong>คำแนะนำจากหัวหน้างาน</strong><div>{{ $order->notes }}</div></div>@endif<div class="d-grid gap-2">
@if($order->status === 'RELEASED' && ! $issue)<form method="POST" action="{{ route('production.orders.material-issue', $order) }}" class="js-shop-create">@csrf<button class="btn btn-app-info btn-lg" type="submit"><i class="bx bx-package me-1" aria-hidden="true"></i>สร้างร่างใบเบิกวัตถุดิบ</button></form>@elseif($order->status === 'RELEASED' && $issue?->status === 'DRAFT')<button class="btn btn-app-info btn-lg js-shop-action" data-url="{{ route('production.orders.material-issues.approve', [$order, $issue]) }}">อนุมัติใบเบิก</button>@elseif($order->status === 'RELEASED' && $issue?->status === 'APPROVED')<button class="btn btn-app-success btn-lg js-shop-action" data-url="{{ route('production.orders.material-issues.post', [$order, $issue]) }}">ลง Stock และยืนยันเริ่มงาน</button>@elseif($order->status === 'IN_PROGRESS' && ! $issue)
<div class="alert alert-warning mb-0"><i class="bx bx-error-circle me-1" aria-hidden="true"></i>ยังไม่พบใบเบิกวัตถุดิบที่ลง Stock แล้ว กรุณาดำเนินการใบเบิกก่อนเริ่มขั้นตอนถัดไป</div>
@elseif($order->status === 'IN_PROGRESS')
@if(! $order->started_at)<button class="btn btn-app-warning btn-lg js-shop-action" data-url="{{ route('production.shop-floor.start', $order) }}"><i class="bx bx-play-circle me-1" aria-hidden="true"></i>ยืนยันเริ่มงานผลิต</button>@else
@if($order->held_at)<button class="btn btn-app-success btn-lg w-100 js-shop-resume" type="button" data-url="{{ route('production.shop-floor.resume', $order) }}"><i class="bx bx-play-circle me-1" aria-hidden="true"></i>เปิดงานผลิตต่อ</button><div class="alert alert-warning small mb-2">พักงาน: {{ $order->hold_reason }}</div>@elseif(auth()->user()->hasPermission('production.orders.hold'))<button class="btn btn-app-warning btn-lg w-100 js-shop-hold" type="button" data-url="{{ route('production.shop-floor.hold', $order) }}"><i class="bx bx-pause-circle me-1" aria-hidden="true"></i>พักงานผลิต</button>@endif
<div class="border rounded-3 p-2"><div class="small fw-semibold text-success mb-2"><i class="bx bx-package me-1" aria-hidden="true"></i>รับสินค้าผลิตเสร็จ</div>@if($receiptDocument?->status === 'DRAFT')<button class="btn btn-app-info btn-lg js-shop-action" data-url="{{ route('production.orders.finished-receipts.approve', [$order, $receiptDocument]) }}">อนุมัติใบรับผลิต</button>@elseif($receiptDocument?->status === 'APPROVED')<button class="btn btn-app-success btn-lg js-shop-action" data-url="{{ route('production.orders.finished-receipts.post', [$order, $receiptDocument]) }}">ลง Stock และจบงาน</button>@else<form method="POST" action="{{ route('production.orders.finished-receipt', $order) }}" class="js-shop-create">@csrf<input type="hidden" name="reason" value="รับสินค้าผลิตเสร็จจาก WO {{ $order->document_number }}"><button class="btn btn-app-success btn-lg" type="submit">สร้างร่างรับผลิตเสร็จ</button></form>@endif</div>
<div class="border rounded-3 p-2"><div class="small fw-semibold text-info mb-2"><i class="bx bx-undo me-1" aria-hidden="true"></i>คืนวัตถุดิบ (ถ้ามี)</div>@if($returnDocument?->status === 'DRAFT')<button class="btn btn-app-info btn-lg js-shop-action" data-url="{{ route('production.orders.material-returns.approve', [$order, $returnDocument]) }}">อนุมัติใบรับคืน</button>@elseif($returnDocument?->status === 'APPROVED')<button class="btn btn-app-success btn-lg js-shop-action" data-url="{{ route('production.orders.material-returns.post', [$order, $returnDocument]) }}">ลง Stock ใบรับคืน</button>@else<form method="POST" action="{{ route('production.orders.material-return', $order) }}" class="js-shop-create">@csrf<label class="form-label small" for="shop-floor-return-reason">เหตุผลการรับคืนวัตถุดิบ</label><textarea class="form-control mb-2" id="shop-floor-return-reason" name="reason" minlength="10" required>คืนวัตถุดิบจาก WO {{ $order->document_number }}</textarea><button class="btn btn-app-info btn-lg w-100" type="submit">สร้างร่างรับคืนวัตถุดิบ</button></form>@endif</div>
<button class="btn btn-app-warning btn-lg js-shop-scrap" data-url="{{ route('production.orders.non-recoverable-scrap', $order) }}" data-uom-id="{{ $order->uom_id }}">บันทึกร่าง Scrap</button>@endif
@endif
</div></div></div></div>
    </div>
</div>
@if($order->status === 'IN_PROGRESS')<div class="modal fade" id="production-issue-modal" tabindex="-1" aria-labelledby="production-issue-title" aria-hidden="true"><div class="modal-dialog"><form class="modal-content" id="production-issue-form" action="{{ route('production.shop-floor.issues.report', $order) }}"><div class="modal-header"><h2 class="modal-title fs-5" id="production-issue-title">แจ้งปัญหาการผลิต</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="ปิด"></button></div><div class="modal-body"><p class="text-secondary">แจ้ง Supervisor เพื่อเข้าตรวจสอบก่อนดำเนินงานต่อ</p><label class="form-label" for="production-issue-severity">ความรุนแรง</label><select class="form-select mb-3" id="production-issue-severity" name="severity" required><option value="HIGH">สูง — หยุดงาน</option><option value="MEDIUM" selected>กลาง</option><option value="LOW">ต่ำ</option></select><label class="form-label" for="production-issue-description">รายละเอียดปัญหา</label><textarea class="form-control" id="production-issue-description" name="description" rows="4" minlength="10" maxlength="2000" required placeholder="ระบุอาการ ปัญหา และสิ่งที่ต้องการให้ตรวจสอบ"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">ยกเลิก</button><button class="btn btn-app-warning" type="submit">แจ้ง Supervisor</button></div></form></div></div>@endif
@push('scripts')
<script>
$(function(){
$('.js-production-elapsed').each(function(){const el=$(this),started=Date.parse(el.data('started-at')),ended=Date.parse(el.data('ended-at'))||Date.now();if(!started)return;const render=()=>{let seconds=Math.max(0,Math.floor(((el.data('ended-at')?ended:Date.now())-started)/1000)),h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;el.text((h?h+' ชม. ':'')+m+' นาที '+String(s).padStart(2,'0')+' วินาที');};render();if(!el.data('ended-at'))setInterval(render,1000);});
$('#production-issue-form').on('submit',function(e){e.preventDefault();if(!navigator.onLine){$('#shop-floor-network-status').removeClass('d-none');return}const f=$(this),b=f.find('[type=submit]');Swal.fire({icon:'warning',title:'แจ้งปัญหาการผลิต?',text:'Supervisor จะได้รับรายการให้เข้าตรวจสอบ',showCancelButton:true,confirmButtonText:'แจ้งปัญหา',cancelButtonText:'ยกเลิก'}).then(r=>{if(!r.isConfirmed)return;b.prop('disabled',true);$.post(f.attr('action'),f.serialize()+'&_token='+encodeURIComponent($('meta[name="csrf-token"]').attr('content'))).done(x=>location.href=x.redirect).fail(x=>{b.prop('disabled',false);Swal.fire({icon:'error',text:x.responseJSON?.message||'แจ้งปัญหาไม่สำเร็จ'});});});});
const networkStatus=$('#shop-floor-network-status'),setNetworkStatus=()=>networkStatus.toggleClass('d-none',navigator.onLine);setNetworkStatus();$(window).on('online offline',setNetworkStatus);const feedback=(message,success=false)=>$('#shop-floor-feedback').removeClass('d-none alert-success alert-danger').addClass(success?'alert-success':'alert-danger').text(message);
const confirmAction=(title,text)=>Swal.fire({icon:'question',title,text,showCancelButton:true,confirmButtonText:'ดำเนินการ',cancelButtonText:'ยกเลิก',reverseButtons:true}).then(r=>r.isConfirmed);
function operationForm(url,method,name,minutes){Swal.fire({title:name?'แก้ไขขั้นตอนการผลิต':'เพิ่มขั้นตอนการผลิต',html:'<input id="swal-operation-name" class="swal2-input" placeholder="ชื่อขั้นตอน" value="'+(name||'')+'"><input id="swal-operation-minutes" class="swal2-input" type="number" min="0" placeholder="เวลาที่วางแผน (นาที)" value="'+(minutes||'')+'">',showCancelButton:true,confirmButtonText:name?'บันทึก':'เพิ่ม',cancelButtonText:'ยกเลิก',preConfirm:function(){const operationName=$('#swal-operation-name').val().trim(),planned=$('#swal-operation-minutes').val();if(!operationName||operationName.length>150){Swal.showValidationMessage('กรุณาระบุชื่อขั้นตอน');return false}return{name:operationName,planned_minutes:planned||null};}}).then(function(r){if(!r.isConfirmed)return;$.ajax({url,type:method,data:{_token:$('meta[name="csrf-token"]').attr('content'),name:r.value.name,planned_minutes:r.value.planned_minutes}}).done(x=>location.href=x.redirect).fail(x=>feedback(x.responseJSON?.message||'บันทึกขั้นตอนไม่สำเร็จ'));});}
$(document).on('click','.js-operation-add',function(){operationForm($(this).data('url'),'POST','','');});$(document).on('click','.js-operation-edit',function(){operationForm($(this).data('url'),'PUT',$(this).data('name'),$(this).data('minutes'));});$(document).on('click','.js-operation-delete',async function(){const b=$(this);if(!await confirmAction('ลบขั้นตอนการผลิต?','ขั้นตอนที่ยังไม่เริ่มเท่านั้นที่ลบได้'))return;$.post(b.data('url'),{_token:$('meta[name="csrf-token"]').attr('content'),_method:'DELETE'}).done(x=>location.href=x.redirect).fail(x=>feedback(x.responseJSON?.message||'ลบขั้นตอนไม่สำเร็จ'));});
$(document).on('click','.js-shop-action',async function(){const button=$(this);if(!navigator.onLine){networkStatus.removeClass('d-none');return}if(!await confirmAction('ยืนยันการทำรายการ?',button.text().trim()))return;button.prop('disabled',true);$.post(button.data('url'),{_token:$('meta[name="csrf-token"]').attr('content')}).done(()=>location.reload()).fail(x=>{const errors=x.responseJSON?.errors||{};const detail=Object.values(errors).flat()[0];feedback(detail||x.responseJSON?.message||`ทำรายการไม่สำเร็จ (${x.status})`);button.prop('disabled',false)})});
$(document).on('submit','.js-shop-create',async function(e){e.preventDefault();const form=$(this);if(!navigator.onLine){networkStatus.removeClass('d-none');return}if(!await confirmAction('สร้างร่างเอกสาร?',form.find('[type=submit]').text().trim()))return;const button=form.find('[type=submit]').prop('disabled',true);$.post(form.attr('action'),form.serialize()).done(()=>location.reload()).fail(x=>{const errors=x.responseJSON?.errors||{};const detail=Object.values(errors).flat()[0];feedback(detail||x.responseJSON?.message||`สร้างร่างไม่สำเร็จ (${x.status})`);button.prop('disabled',false)})});
$(document).on('click','.js-shop-hold',function(){const b=$(this);Swal.fire({icon:'warning',title:'พักงานผลิต?',input:'textarea',inputLabel:'เหตุผลที่พักงาน',inputPlaceholder:'ระบุปัญหาหรือเหตุผลอย่างน้อย 10 ตัวอักษร',inputAttributes:{minlength:10},showCancelButton:true,confirmButtonText:'พักงานผลิต',cancelButtonText:'ยกเลิก',preConfirm:function(value){if(!value||value.trim().length<10){Swal.showValidationMessage('กรุณาระบุเหตุผลอย่างน้อย 10 ตัวอักษร');return false}return value.trim();}}).then(function(r){if(!r.isConfirmed)return;b.prop('disabled',true);$.post(b.data('url'),{_token:$('meta[name="csrf-token"]').attr('content'),reason:r.value}).done(x=>location.href=x.redirect).fail(x=>{b.prop('disabled',false);feedback(x.responseJSON?.message||'พักงานไม่สำเร็จ');});});});
$(document).on('click','.js-shop-resume',async function(){const b=$(this);if(!await confirmAction('เปิดงานผลิตต่อ?','ระบบจะล้างสถานะพักงานและให้ดำเนินการต่อ'))return;b.prop('disabled',true);$.post(b.data('url'),{_token:$('meta[name="csrf-token"]').attr('content')}).done(x=>location.href=x.redirect).fail(x=>{b.prop('disabled',false);feedback(x.responseJSON?.message||'เปิดงานต่อไม่สำเร็จ');});});
$(document).on('click','.js-shop-scrap',async function(){if(!navigator.onLine){networkStatus.removeClass('d-none');return}const button=$(this),result=await Swal.fire({title:'สร้างร่าง Scrap',html:'<input id="swal-scrap-quantity" class="swal2-input" type="number" min="0.00000001" step="0.00000001" placeholder="จำนวนของเสีย"><textarea id="swal-scrap-reason" class="swal2-textarea" placeholder="เหตุผลอย่างน้อย 5 ตัวอักษร"></textarea>',showCancelButton:true,confirmButtonText:'ดำเนินการ',cancelButtonText:'ยกเลิก',preConfirm:function(){const quantity=$('#swal-scrap-quantity').val(),reason=$('#swal-scrap-reason').val().trim();if(!quantity||!reason||reason.length<5){Swal.showValidationMessage('กรุณาระบุจำนวนและเหตุผลอย่างน้อย 5 ตัวอักษร');return false}return{quantity,reason}}});if(!result.isConfirmed)return;button.prop('disabled',true);$.post(button.data('url'),{_token:$('meta[name="csrf-token"]').attr('content'),quantity:result.value.quantity,uom_id:button.data('uom-id'),reason:result.value.reason}).done(()=>location.reload()).fail(x=>{feedback(x.responseJSON?.message||'บันทึก Scrap ไม่สำเร็จ');button.prop('disabled',false)})});
});
</script>
@endpush
@endsection
