@extends('Wms::layout')
@section('title', 'แปลงหน่วย | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    <div class="mb-4"><p class="eyebrow mb-2">WMS / MASTER DATA</p><h1 class="h3 mb-2">อัตราแปลงหน่วย</h1><p class="text-secondary mb-0">กำหนดความสัมพันธ์ระหว่างหน่วยนับตามช่วงเวลาที่มีผล</p></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h6 mb-3">เพิ่มอัตราแปลงหน่วย</h2><form id="conversion-form" method="POST" action="{{ route('wms.uom-conversions.store') }}">@csrf<div class="row g-3 align-items-end"><div class="col-12 col-md-3"><label class="form-label" for="from-uom">จากหน่วย</label><select id="from-uom" class="form-select js-uom" name="from_uom_id" data-url="{{ route('wms.uoms.options') }}" required></select></div><div class="col-12 col-md-3"><label class="form-label" for="to-uom">เป็นหน่วย</label><select id="to-uom" class="form-select js-uom" name="to_uom_id" data-url="{{ route('wms.uoms.options') }}" required></select></div><div class="col-12 col-md-2"><label class="form-label" for="conversion-factor">ตัวคูณ</label><input id="conversion-factor" class="form-control text-end" name="factor" type="number" min="0.00000001" step="0.00000001" required></div><div class="col-12 col-md-2"><label class="form-label" for="effective-from">มีผลตั้งแต่</label><input id="effective-from" class="form-control" name="effective_from" type="date" value="{{ today()->format('Y-m-d') }}" required></div><div class="col-12 col-md-2"><label class="form-label" for="effective-to">ถึงวันที่</label><input id="effective-to" class="form-control" name="effective_to" type="date"></div></div><div class="d-flex gap-2 mt-4"><button class="btn btn-dark" type="submit"><i class="bx bx-save me-1" aria-hidden="true"></i>บันทึกอัตราแปลง</button><a class="btn btn-outline-secondary" href="{{ route('wms.uoms.index') }}">กลับหน่วยนับ</a></div></form></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><h2 class="h6 mb-0">รายการอัตราแปลงหน่วย</h2><span class="text-secondary small">ประวัติ conversion ที่บันทึกไว้</span></div><div class="table-responsive"><table class="table table-hover align-middle w-100" id="conversions-table" data-url="{{ route('wms.uom-conversions.data') }}"><thead><tr><th>จากหน่วย</th><th>เป็นหน่วย</th><th class="text-end">ตัวคูณ</th><th>มีผลตั้งแต่</th><th>ถึงวันที่</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){var table=$('#conversions-table'),text=$.fn.dataTable.render.text();$('.js-uom').each(function(){var select=$(this);window.erpInitSelect2(select,{theme:'bootstrap-5',ajax:{url:select.data('url'),delay:250,data:function(p){return{q:p.term||'',page:p.page||1}},processResults:function(d){return d}}});});table.DataTable($.extend(true,{},window.erpDataTableDefaults,{ajax:table.data('url'),buttons:[window.erpExcelButton(table)],order:[[3,'desc']],columns:[{data:'from_label',name:'from_uom_id',render:text.display},{data:'to_label',name:'to_uom_id',render:text.display},{data:'factor',name:'factor',className:'text-end',render:text.display},{data:'effective_from',name:'effective_from',render:text.display},{data:'effective_to',name:'effective_to',render:text.display}]}));window.erpAjaxForm({form:'#conversion-form',reload:'#conversions-table'});});</script>@endpush
