@extends('Wms::layout')
@php($decimalStep = \App\Modules\Wms\Support\WmsDecimal::step())
@section('title', 'อัตราแปลงหน่วย | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
 <div class="mb-4"><p class="eyebrow mb-2">WMS / MASTER DATA</p><h1 class="h3 mb-2">อัตราแปลงหน่วย</h1><p class="text-secondary mb-0">กำหนดความสัมพันธ์ระหว่างหน่วยนับตามช่วงวันที่มีผล</p></div>
 <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="mb-3"><h2 class="h5 mb-1">เพิ่มอัตราแปลงหน่วย</h2><p class="small text-secondary mb-0">ระบบป้องกันช่วงวันที่ทับซ้อนของคู่หน่วยเดียวกัน</p></div><form id="conversion-form" method="POST" action="{{ route('wms.uom-conversions.store') }}">@csrf<div class="row g-3 align-items-end"><div class="col-12 col-md-3"><label class="form-label" for="from-uom">จากหน่วย</label><select id="from-uom" class="form-select js-uom" name="from_uom_id" data-url="{{ route('wms.uoms.options') }}" required></select></div><div class="col-12 col-md-3"><label class="form-label" for="to-uom">เป็นหน่วย</label><select id="to-uom" class="form-select js-uom" name="to_uom_id" data-url="{{ route('wms.uoms.options') }}" required></select></div><div class="col-12 col-md-2"><label class="form-label" for="conversion-factor">ตัวคูณ</label><input id="conversion-factor" class="form-control text-end" name="factor" type="number" min="{{ $decimalStep }}" step="{{ $decimalStep }}" required></div><div class="col-12 col-md-2"><label class="form-label" for="effective-from">มีผลตั้งแต่</label><input id="effective-from" class="form-control" name="effective_from" type="date" value="{{ today()->format('Y-m-d') }}" required></div><div class="col-12 col-md-2"><label class="form-label" for="effective-to">ถึงวันที่</label><input id="effective-to" class="form-control" name="effective_to" type="date"></div></div><div class="d-flex flex-wrap gap-2 mt-4"><button class="btn btn-app-primary" type="submit"><i class="bx bx-save me-1" aria-hidden="true"></i>บันทึกอัตราแปลง</button><a class="btn btn-outline-secondary" href="{{ route('wms.uoms.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้าหน่วยนับ</a></div></form></div></div>
 <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="mb-3"><h2 class="h5 mb-1">รายการอัตราแปลงหน่วย</h2><p class="small text-secondary mb-0">ค้นหา ส่งออก และลบเฉพาะรายการที่ไม่ต้องใช้อีกต่อไป</p></div><div class="table-responsive"><table class="table table-hover align-middle w-100" id="conversions-table"><thead><tr><th>ลำดับ</th><th>จากหน่วย</th><th>เป็นหน่วย</th><th class="text-end">ตัวคูณ</th><th>มีผลตั้งแต่</th><th>ถึงวันที่</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){const tableElement=$('#conversions-table'),text=$.fn.dataTable.render.text();$('.js-uom').each(function(){const select=$(this);window.erpInitSelect2(select,{theme:'bootstrap-5',ajax:{url:select.data('url'),delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:data=>data}});});const table=tableElement.DataTable($.extend(true,{},window.erpDataTableDefaults,{processing:true,serverSide:true,order:[[4,'desc']],ajax:'{{ route('wms.uom-conversions.data') }}',buttons:[window.erpExcelButton(tableElement)],columns:[{data:null,orderable:false,searchable:false,className:'text-center',render:(value,type,row,meta)=>type==='display'?meta.settings._iDisplayStart+meta.row+1:''},{data:'from_label',name:'from_uom_id',render:text.display},{data:'to_label',name:'to_uom_id',render:text.display},{data:'factor',name:'factor',className:'text-end',render:text.display},{data:'effective_from',name:'effective_from',render:text.display},{data:'effective_to',name:'effective_to',render:text.display},{data:null,orderable:false,searchable:false,className:'text-end',render:(value,type,row)=>type==='display'&&row.delete_url?'<button type="button" class="btn btn-sm btn-app-danger js-conversion-delete" data-url="'+row.delete_url+'" title="ลบ" aria-label="ลบอัตราแปลงหน่วย"><i class="bx bx-trash" aria-hidden="true"></i></button>':''}]}));window.erpAjaxForm({form:'#conversion-form',reload:'#conversions-table'});window.erpAjaxDelete({button:'.js-conversion-delete',reload:'#conversions-table',title:'ลบอัตราแปลงหน่วย?',text:'ตรวจสอบก่อนลบ เพราะรายการนี้อาจมีผลต่อการแปลงหน่วยย้อนหลัง',confirmButtonText:'ลบ',cancelButtonText:'กลับ'});});</script>@endpush
