@extends('Wms::layout')
@section('title', 'หน่วยนับ | WMS')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
 <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><p class="eyebrow mb-2">WMS / MASTER DATA</p><h1 class="h3 mb-2">หน่วยนับ</h1><p class="text-secondary mb-0">กำหนดหน่วยนับและจำนวนตำแหน่งทศนิยมที่สินค้าใช้คำนวณ</p></div>@if(auth()->user()->hasPermission('wms.uoms.create'))<a class="btn btn-app-primary" href="{{ route('wms.uoms.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>เพิ่มหน่วยนับ</a>@endif</div>
 <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><div class="d-flex justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">ตัวกรองหน่วยนับ</h2><p class="small text-secondary mb-0">กรองตามสถานะก่อนค้นหาจากตาราง</p></div><button type="button" class="btn btn-app-soft" id="uom-filter-reset"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3"><div class="col-12 col-md-3"><label class="form-label" for="uom-status-filter">สถานะ</label><select class="form-select" id="uom-status-filter"><option value="">ทุกสถานะ</option><option value="1" selected>ใช้งาน</option><option value="0">ปิดใช้งาน</option></select></div></div></div></div>
 <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="mb-3"><h2 class="h5 mb-1">รายการหน่วยนับ</h2><p class="small text-secondary mb-0">ใช้ช่องค้นหาในตารางเพื่อค้นหารหัสและชื่อหน่วยนับ</p></div><div class="table-responsive"><table class="table table-hover align-middle w-100" id="uoms-table"><thead><tr><th>ลำดับ</th><th>รหัส</th><th>ชื่อ</th><th class="text-end">ทศนิยม</th><th>สถานะ</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection
@push('scripts')<script>$(function(){const element=$('#uoms-table'),status=$('#uom-status-filter'),text=$.fn.dataTable.render.text(),table=element.DataTable($.extend(true,{},window.erpDataTableDefaults,{processing:true,serverSide:true,order:[[1,'asc']],ajax:{url:'{{ route('wms.uoms.data') }}',data:function(data){data.is_active=status.val();}},buttons:[window.erpExcelButton(element)],columns:[{data:null,orderable:false,searchable:false,className:'text-center',render:(value,type,row,meta)=>type==='display'?meta.settings._iDisplayStart+meta.row+1:''},{data:'code',name:'code',render:text.display},{data:'name',name:'name',render:text.display},{data:'decimal_places',name:'decimal_places',className:'text-end',render:text.display},{data:'status_label',name:'is_active',render:(value,type,row)=>type==='display'?'<span class="badge '+(row.is_active?'app-status-success':'app-status-neutral')+'">'+text.display(value)+'</span>':value},{data:null,orderable:false,searchable:false,className:'text-end text-nowrap',render:(value,type,row)=>{if(type!=='display')return '';let html=row.edit_url?'<a class="btn btn-sm btn-app-soft" href="'+row.edit_url+'" title="แก้ไข" aria-label="แก้ไข '+text.display(row.code)+'"><i class="bx bx-edit" aria-hidden="true"></i></a>':'';if(row.delete_url)html+=' <button type="button" class="btn btn-sm btn-app-danger js-uom-delete" data-url="'+row.delete_url+'" title="ลบ" aria-label="ลบ '+text.display(row.code)+'"><i class="bx bx-trash" aria-hidden="true"></i></button>';return html;}}]}));status.on('change',()=>table.ajax.reload());$('#uom-filter-reset').on('click',()=>status.val('1').trigger('change'));window.erpAjaxDelete({button:'.js-uom-delete',reload:'#uoms-table',title:'ลบหน่วยนับ?',text:'ลบได้เฉพาะหน่วยนับที่ยังไม่ถูกใช้งาน',confirmButtonText:'ลบ',cancelButtonText:'กลับ'});});</script>@endpush
