@extends('Pos::layout')

@section('title', 'คอมมิชชั่นขาย | POS')

@section('content')
<div class="container-fluid px-3 px-lg-4 py-4">
    @include('Pos::partials.sales-list-header', ['eyebrow' => 'SALES / COMMISSIONS', 'title' => 'คอมมิชชั่นขาย', 'description' => 'ตรวจสอบสิทธิ์ ติดตามสถานะ และเปิดรายละเอียดเพื่ออนุมัติรายการคอมมิชชั่น'])
    @if(auth()->user()->hasPermission('pos.sales-commissions.pay'))<div class="d-flex justify-content-end mb-3"><a class="btn btn-app-primary" href="{{ route('pos.sales-commission-payment-batches.create') }}"><i class="bx bx-plus me-1" aria-hidden="true"></i>สร้างชุดจ่าย</a></div>@endif
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">ตัวกรองคอมมิชชั่น</h2><p class="text-secondary small mb-0">กรองตามงวด ผู้รับ และสถานะก่อนค้นหาจากตาราง</p></div><button class="btn btn-sm btn-app-soft" id="commission-reset" type="button"><i class="bx bx-reset me-1" aria-hidden="true"></i>ล้างตัวกรอง</button></div><div class="row g-3 align-items-end"><div class="col-12 col-md-4 col-lg-3"><label class="form-label" for="commission-from">วันที่เริ่ม</label><input class="form-control" id="commission-from" type="date" value="{{ now()->startOfMonth()->format('Y-m-d') }}"></div><div class="col-12 col-md-4 col-lg-3"><label class="form-label" for="commission-to">ถึงวันที่</label><input class="form-control" id="commission-to" type="date" value="{{ now()->endOfMonth()->format('Y-m-d') }}"></div><div class="col-12 col-md-4 col-lg-3"><label class="form-label" for="commission-recipient">ผู้รับคอมมิชชั่น</label><select class="form-select" id="commission-recipient" data-url="{{ route('pos.sales-commissions.recipient-options') }}"><option value="">ทั้งหมด</option></select></div><div class="col-12 col-md-4 col-lg-2"><label class="form-label" for="commission-status">สถานะ</label><select class="form-select" id="commission-status"><option value="">ทั้งหมด</option><option value="PENDING">รออนุมัติ</option><option value="APPROVED">อนุมัติแล้ว</option><option value="REJECTED">ไม่อนุมัติ</option><option value="PAID">จ่ายแล้ว</option><option value="REVERSED">กลับรายการแล้ว</option></select></div><div class="col-12 col-md-4 col-lg-1"><button class="btn btn-app-primary w-100" id="commission-filter" type="button"><i class="bx bx-search me-1" aria-hidden="true"></i>ค้นหา</button></div></div></div></div>
    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-3 p-lg-4"><div class="mb-3"><h2 class="h5 mb-1">รายการคอมมิชชั่น</h2><p class="small text-secondary mb-0">เปิดรายละเอียดเพื่อตรวจสอบข้อมูลและดำเนินการตามสถานะ</p></div><div class="table-responsive"><table id="sales-commissions-table" class="table table-hover align-middle w-100 mb-0" data-url="{{ route('pos.sales-commissions.data') }}"><thead class="table-light"><tr><th>ลำดับ</th><th>วันที่คำนวณ</th><th>ผู้รับคอมมิชชั่น</th><th>แผนคอมมิชชั่น</th><th>วิธีคำนวณ</th><th>เอกสารขาย</th><th class="text-end">ฐานคำนวณ</th><th class="text-end">อัตรา</th><th class="text-end">คอมมิชชั่น</th><th>สถานะรายการ</th><th>สถานะการจ่าย</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><div class="mb-3"><h2 class="h5 mb-1">ชุดจ่ายคอมมิชชั่น</h2><p class="small text-secondary mb-0">เปิดรายละเอียดชุดจ่ายเพื่อติดตามขั้นตอนส่งการเงินและผลการจ่าย</p></div><div class="table-responsive"><table id="commission-payment-batches-table" class="table table-hover align-middle w-100 mb-0" data-url="{{ route('pos.sales-commission-payment-batches.data') }}"><thead class="table-light"><tr><th>ลำดับ</th><th>เลขที่</th><th>ช่วงวันที่</th><th class="text-end">จำนวนรายการ</th><th>สถานะใบขอจ่าย</th><th>ผลการจ่าย</th><th class="text-end">ยอดรวม</th><th>สถานะชุด</th><th class="text-end">จัดการ</th></tr></thead></table></div></div></div>
</div>
@endsection

@push('scripts')
<script>
$(function () {
    const table = $('#sales-commissions-table'), esc = $.fn.dataTable.render.text(), money = $.fn.dataTable.render.number(',', '.', 2), rate = $.fn.dataTable.render.number(',', '.', 4);
    const badge = status => ({ PENDING: 'app-status-info', APPROVED: 'app-status-success', REJECTED: 'app-status-danger', PAID: 'app-status-success', REVERSED: 'app-status-danger' }[status] || 'app-status-neutral');
    const dt = table.DataTable($.extend(true, {}, window.erpDataTableDefaults, { ajax: { url: table.data('url'), data: d => { d.date_from = $('#commission-from').val(); d.date_to = $('#commission-to').val(); d.recipient_user_id = $('#commission-recipient').val(); d.status = $('#commission-status').val(); } }, order: [[1, 'desc']], buttons: [window.erpExcelButton(table)], columns: [window.erpRowNumberColumn(),{ data: 'calculated_at_label', name: 'calculated_at', render: esc.display }, { data: 'recipient_label', render: esc.display }, { data: 'plan_label', render: esc.display }, { data: 'basis_label', render: esc.display }, { data: 'sale_label', render: (d, _, r) => r.sale_url ? '<a href="' + esc.display(r.sale_url) + '">' + esc.display(d) + '</a>' : esc.display(d) }, { data: 'base_amount', className: 'text-end', render: money }, { data: 'rate_percent', className: 'text-end', render: d => rate.display(d) + '%' }, { data: 'commission_amount', className: 'text-end fw-semibold', render: money }, { data: 'status_label', render: (d, _, r) => '<span class="badge ' + badge(r.status) + '">' + esc.display(d) + '</span>' }, { data: 'payment_progress', orderable: false, render: value => '<span class="badge ' + esc.display(value.class) + '">' + esc.display(value.label) + '</span>' }, { data: 'show_url', orderable: false, searchable: false, className: 'text-end text-nowrap', render: url => '<a class="btn btn-sm btn-app-soft" href="' + esc.display(url) + '" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-file-find" aria-hidden="true"></i></a>' }] }));
    const batchTable = $('#commission-payment-batches-table'), batchEsc = $.fn.dataTable.render.text();
    batchTable.DataTable($.extend(true, {}, window.erpDataTableDefaults, { ajax: batchTable.data('url'), order: [[1, 'desc']], buttons: [window.erpExcelButton(batchTable)], columns: [window.erpRowNumberColumn(),{ data: 'document_number', render: batchEsc.display }, { data: 'period_label', render: batchEsc.display }, { data: 'lines_count', className: 'text-end' }, { data: 'request_summary', orderable: false, render: value => '<span class="badge ' + batchEsc.display(value.class) + '">' + batchEsc.display(value.label) + '</span>' }, { data: 'payment_summary', orderable: false, render: value => '<span class="badge ' + batchEsc.display(value.class) + '">' + batchEsc.display(value.label) + '</span>' }, { data: 'total_amount', className: 'text-end fw-semibold', render: money }, { data: 'status_label', render: (d, _, r) => '<span class="badge ' + (r.status === 'VERIFIED' ? 'app-status-success' : (r.status === 'SUBMITTED' ? 'app-status-info' : (r.status === 'CANCELLED' ? 'app-status-danger' : 'app-status-neutral'))) + '">' + batchEsc.display(d) + '</span>' }, { data: 'show_url', className: 'text-end text-nowrap', orderable: false, searchable: false, render: url => '<a class="btn btn-sm btn-app-soft" href="' + batchEsc.display(url) + '" title="ดูรายละเอียด" aria-label="ดูรายละเอียด"><i class="bx bx-file-find" aria-hidden="true"></i></a>' }] }));
    $('#commission-recipient').select2({ theme: 'bootstrap-5', width: '100%', allowClear: true, ajax: { url: $('#commission-recipient').data('url'), dataType: 'json', delay: 250, data: p => ({ q: p.term || '' }), processResults: d => d } });
    $('#commission-filter').on('click', () => dt.ajax.reload());
    $('#commission-reset').on('click', () => { $('#commission-from').val(@json(now()->startOfMonth()->format('Y-m-d'))); $('#commission-to').val(@json(now()->endOfMonth()->format('Y-m-d'))); $('#commission-recipient').val(null).trigger('change'); $('#commission-status').val(''); dt.ajax.reload(); });
});
</script>
@endpush
