@extends('Pos::layout')

@section('title', 'คอมมิชชั่น '.$record->id.' | POS')

@section('content')
@php($statusLabels = ['PENDING' => 'รออนุมัติ', 'APPROVED' => 'อนุมัติแล้ว', 'REJECTED' => 'ไม่อนุมัติ', 'PAID' => 'จ่ายแล้ว', 'REVERSED' => 'กลับรายการแล้ว'])
@php($statusBadges = ['PENDING' => 'app-status-info', 'APPROVED' => 'app-status-success', 'REJECTED' => 'app-status-danger', 'PAID' => 'app-status-success', 'REVERSED' => 'app-status-danger'])
<div class="container-fluid px-3 px-lg-4 py-4">
    <p class="eyebrow mb-2">SALES / COMMISSIONS</p>
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-start gap-3 mb-4">
        <div><h1 class="h3 mb-2">คอมมิชชั่น #{{ $record->id }}</h1><span class="badge {{ $statusBadges[$record->status] ?? 'app-status-neutral' }}">{{ $statusLabels[$record->status] ?? $record->status }}</span></div>
        <div class="d-flex flex-wrap gap-2">
            <a class="btn btn-app-soft" href="{{ route('pos.sales-commissions.index') }}"><i class="bx bx-arrow-back me-1" aria-hidden="true"></i>กลับหน้ารายการ</a>
            @if($record->physicalSale && auth()->user()->hasPermission('pos.physical-sales.view'))<a class="btn btn-app-soft" href="{{ route('pos.physical-sales.show', $record->physicalSale) }}"><i class="bx bx-receipt me-1" aria-hidden="true"></i>ดูเอกสารขาย</a>@endif
            @if($record->status === 'PENDING' && auth()->user()->hasPermission('pos.sales-commissions.approve'))<button class="btn btn-app-primary js-commission-approve" data-url="{{ route('pos.sales-commissions.approve', $record) }}" type="button"><i class="bx bx-check me-1" aria-hidden="true"></i>อนุมัติ</button><button class="btn btn-app-danger js-commission-reject" data-url="{{ route('pos.sales-commissions.reject', $record) }}" type="button"><i class="bx bx-x-circle me-1" aria-hidden="true"></i>ไม่อนุมัติ</button>@endif
            @if($canEditStatus && auth()->user()->hasPermission('pos.sales-commissions.approve'))<button class="btn btn-app-soft js-commission-edit-status" data-url="{{ route('pos.sales-commissions.update-status', $record) }}" type="button"><i class="bx bx-edit me-1" aria-hidden="true"></i>แก้ไขสถานะ</button>@endif
        </div>
    </div>

    @if($record->status === 'PENDING')<div class="alert alert-info border-0 shadow-sm mb-4"><strong>ขั้นถัดไป:</strong> ตรวจสอบยอดฐานคำนวณ อัตรา และเอกสารขายก่อนอนุมัติหรือไม่อนุมัติ</div>@elseif($record->status === 'APPROVED')<div class="alert alert-success border-0 shadow-sm mb-4"><strong>อนุมัติแล้ว:</strong> เลือกรายการนี้เมื่อสร้างชุดจ่ายคอมมิชชั่น</div>@elseif($record->status === 'REJECTED')<div class="alert alert-danger border-0 shadow-sm mb-4"><strong>ไม่อนุมัติแล้ว</strong>{{ $record->rejection_reason ? ' · เหตุผล: '.$record->rejection_reason : '' }}</div>@endif

    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">รายละเอียดคอมมิชชั่น</h2><div class="row g-3"><div class="col-md-3"><div class="small text-secondary">วันที่คำนวณ</div><strong>{{ $record->calculated_at?->format('d/m/Y') ?: '—' }}</strong></div><div class="col-md-3"><div class="small text-secondary">ผู้รับคอมมิชชั่น</div><strong>{{ $record->recipient?->name ?: '—' }}</strong></div><div class="col-md-3"><div class="small text-secondary">แผนคอมมิชชั่น</div><strong>{{ $record->plan ? $record->plan->code.' · '.$record->plan->name : '—' }}</strong></div><div class="col-md-3"><div class="small text-secondary">เอกสารขาย</div><strong>{{ $record->physicalSale?->document_number ?: '—' }}</strong></div><div class="col-md-4"><div class="small text-secondary">ฐานคำนวณ</div><strong>{{ number_format((float) $record->base_amount, 2) }}</strong></div><div class="col-md-4"><div class="small text-secondary">อัตรา</div><strong>{{ number_format((float) $record->rate_percent, 4) }}%</strong></div><div class="col-md-4"><div class="small text-secondary">คอมมิชชั่น</div><strong>{{ number_format((float) $record->commission_amount, 2) }}</strong></div></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">สถานะการจ่าย</h2><span class="badge {{ $paymentProgress['class'] }}">{{ $paymentProgress['label'] }}</span></div></div>
    <div class="card border-0 shadow-sm"><div class="card-body p-3 p-lg-4"><h2 class="h5 mb-3">ประวัติรายการ</h2>@forelse($history as $event)<div class="border-bottom py-2"><span class="text-secondary small">{{ $event->created_at?->format('d/m/Y H:i') }}</span> <strong>{{ $event->action }}</strong> <span class="text-secondary">{{ $event->user?->name ?? 'ระบบ' }}</span>@if($event->reason)<div class="small text-secondary mt-1">{{ $event->reason }}</div>@endif</div>@empty<div class="text-secondary">ยังไม่มีประวัติ</div>@endforelse</div></div>
</div>
@endsection

@push('scripts')
<script>
$(function () {
    const csrf = $('meta[name="csrf-token"]').attr('content') || '', reload = () => location.reload();
    $('.js-commission-approve').on('click', function () { const button = $(this); Swal.fire({ icon: 'question', text: 'ยืนยันอนุมัติคอมมิชชั่นรายการนี้?', showCancelButton: true, confirmButtonText: 'อนุมัติ', cancelButtonText: 'กลับ' }).then(result => { if (!result.isConfirmed) return; button.prop('disabled', true); $.ajax({ url: button.data('url'), method: 'PUT', headers: { Accept: 'application/json', 'X-CSRF-TOKEN': csrf } }).done(response => Swal.fire({ icon: 'success', text: response.msg }).then(reload)).fail(xhr => Swal.fire({ icon: 'error', text: xhr.responseJSON?.message || 'ไม่สามารถอนุมัติคอมมิชชั่นได้' })).always(() => button.prop('disabled', false)); }); });
    $('.js-commission-reject').on('click', function () { const button = $(this); Swal.fire({ icon: 'warning', title: 'ไม่อนุมัติคอมมิชชั่น?', input: 'textarea', inputLabel: 'เหตุผล', inputValidator: value => !value?.trim() ? 'กรุณาระบุเหตุผล' : undefined, showCancelButton: true, confirmButtonText: 'ไม่อนุมัติ', cancelButtonText: 'กลับ' }).then(result => { if (!result.isConfirmed) return; button.prop('disabled', true); $.ajax({ url: button.data('url'), method: 'PUT', data: { reason: result.value.trim() }, headers: { Accept: 'application/json', 'X-CSRF-TOKEN': csrf } }).done(response => Swal.fire({ icon: 'success', text: response.msg }).then(reload)).fail(xhr => Swal.fire({ icon: 'error', text: xhr.responseJSON?.message || 'ไม่สามารถไม่อนุมัติคอมมิชชั่นได้' })).always(() => button.prop('disabled', false)); }); });
    $('.js-commission-edit-status').on('click', function () { const button = $(this); Swal.fire({ title: 'แก้ไขสถานะคอมมิชชั่น', input: 'select', inputOptions: { PENDING: 'รออนุมัติ', REJECTED: 'ไม่อนุมัติ' }, inputPlaceholder: 'เลือกสถานะ', showCancelButton: true, confirmButtonText: 'ถัดไป', cancelButtonText: 'กลับ' }).then(choice => { if (!choice.isConfirmed) return; const submit = reason => { button.prop('disabled', true); $.ajax({ url: button.data('url'), method: 'PUT', data: { status: choice.value, reason: reason || '' }, headers: { Accept: 'application/json', 'X-CSRF-TOKEN': csrf } }).done(response => Swal.fire({ icon: 'success', text: response.msg }).then(reload)).fail(xhr => Swal.fire({ icon: 'error', text: xhr.responseJSON?.message || 'ไม่สามารถแก้ไขสถานะได้' })).always(() => button.prop('disabled', false)); }; if (choice.value === 'REJECTED') Swal.fire({ title: 'เหตุผลที่ไม่อนุมัติ', input: 'textarea', inputValidator: value => !value?.trim() ? 'กรุณาระบุเหตุผล' : undefined, showCancelButton: true, confirmButtonText: 'บันทึก', cancelButtonText: 'กลับ' }).then(reason => { if (reason.isConfirmed) submit(reason.value.trim()); }); else submit(); }); });
});
</script>
@endpush
